### ISSUE TITLE
Some error DecordDecode for kinetics400

### ISSUE THREAD

**Issue by barbecacov** [open-mmlab/mmaction2#1001]
kinetics400:   I download it in the web

data input: 
    dict(type='DecordInit'),
    dict(type='DenseSampleFrames', clip_len=1, frame_interval=1, num_clips=8),
    dict(type='DecordDecode'),

    videos_per_gpu=8,
    workers_per_gpu=4,

error info : decord._ffi.base.DECORDError: [16:47:59] /io/decord/src/video/video_reader.cc:125: Check failed: st_nb >= 0 
                  (-1381258232 vs. 0) ERROR cannot find video stream with wanted index: -1

my question:
       
     This error message means that the video cant decorded by decord? or the problem of the video？Thank you very much

**Comment by innerlee** [comment]
The meta file of the video is corrupted. You can try to re-encode that file

**Comment by barbecacov** [comment]
so  i should redownload the kinetics400 dataset?

**Comment by innerlee** [comment]
no. If the file can be played by media player, then simply re-encode it by ffmpeg is good enough

**Comment by barbecacov** [comment]
But I dont know which video file is needed to be re-encoded?Is there anyway to check it?

**Comment by innerlee** [comment]
https://mmaction2.readthedocs.io/en/latest/useful_tools.html#check-videos

**Comment by barbecacov** [comment]
Awesome Tool
