### ISSUE TITLE
Spatial Temporal Action Detection SlowFast with my data.

### ISSUE THREAD

**Issue by mostar39** [open-mmlab/mmaction2#1002]
I am learning Spatial Temporal Action Detection SlowFast with my data.
However, in the case of AVA data, I saw that the video length was fixed from 902 to 1798.
I would like to proceed with learning with each video being very short, but the length of each video is different.
I changed timestamp_start in ava_dataset.py to 1 according to my data, can I change it like this?
Also, I don't know how to set timstamp_end because the length of the video is different.
Is there any problem with learning even if the length of the video is different?

**Comment by mostar39** [comment]
And I wonder. written in the config file
     dict(type='SampleAVAFrames', clip_len=32, frame_interval=2),
What is the meaning of My data also cut a video into a photo at 30fps like AVA data, is clip_len meaningful with that?

**Comment by kennymckormick** [comment]
1. It's OK to have videos of different lengths. However, you may need to modify the AVADataset.
2. `clip_len` means the roi_feature of the bbox is extracted from a  clip with `clip_len x frame_interval` frames. So keep its original value.

**Comment by TripodTripod** [comment]
> 1. It's OK to have videos of different lengths. However, you may need to modify the AVADataset.
> 2. `clip_len` means the roi_feature of the bbox is extracted from a  clip with `clip_len x frame_interval` frames. So keep its original value.

About 1, would you mind to explain the details about modifying the AVADataset with different length videos ?

The way I suppose be like :
In /mmaction/datasets/ava_dataset.py/AVADataset/Load_annotations:
Step1: I get a dict like dict_start_end={'all videos': [{timestamp_start}, {timestamp_end}], ...}
Step2: let self.timestamp_end = dict_start_end['video_name'][1]

But how to modify the timestamp_end at other place like result['timestamp_end'] in ava_dataset.py/AVADataset/prepare_train_frames?
https://github.com/open-mmlab/mmaction2/blob/2b6f9ac69b3609b96a514501ffe30fc90545f518/mmaction/datasets/ava_dataset.py#L280
@kennymckormick
