### ISSUE TITLE
Some problems with tools/data/resize_video.py

### ISSUE THREAD

**Issue by makecent** [open-mmlab/mmaction2#1004]
1. its name should be ``resize_videos.py`` instead of ``resize_video.py``.
2. When I used it to resize **.webm** videos,  it raised error as below:
```diff
- [webm @ 0x555ba3b3e640] Only VP8 or VP9 or AV1 video and Vorbis or Opus audio and WebVTT subtitles are supported for WebM.
- Could not write header for output file #0 (incorrect codec parameters ?): Invalid argument

```
3. I used it to resize **.mkv** videos and it worked, only after I manually added the 'mkv' into the choice of ``--ext``.

**Comment by dreamerlin** [comment]
For 1 and 3, https://github.com/open-mmlab/mmaction2/pull/1012
For 2, you may need to manually convert the format from webm to other formats, since current ffmpeg only supports VP8 or VP9 or AV1 video and Vorbis or Opus audio and WebVTT subtitles
