### ISSUE TITLE
Get started Colab tutorial - mmcv version incompatible

### ISSUE THREAD

**Issue by onnkeat** [open-mmlab/mmaction2#1006]
Refer to the Getting Started colab tutorial(https://colab.research.google.com/github/open-mmlab/mmaction2/blob/master/demo/mmaction2_tutorial.ipynb), `import mmaction` failed after installing initial packages.

To reproduce the error, just run the top 2 code cells directly without editing any codes in the notebook.

Error message: `AssertionError: MMCV==1.3.5 is used but incompatible. Please install mmcv>=1.3.6, <=1.4.0`

![image](https://user-images.githubusercontent.com/30517908/125106666-7a277800-e112-11eb-9129-28b190bc8931.png)

**Comment by dreamerlin** [comment]
Thx for your report. We have updated it! https://github.com/open-mmlab/mmaction2/blob/master/demo/mmaction2_tutorial.ipynb
