### ISSUE TITLE
About demo/demo_posec3d.py

### ISSUE THREAD

**Issue by mostar39** [open-mmlab/mmaction2#1014]
Currently, we see that demo_posec3d.py only predicts one class per video.
When will the long video demo for predicting multiple classes in one video be uploaded?
I really didn't know anything about this field, so I'm always grateful for a lot of information.

**Comment by kennymckormick** [comment]
Currently, we do not have a plan for the PoseC3D long video demo. Basically, to create a long video demo for PoseC3D, you need to apply a sliding window to the long video and make predictions for each sliding window.

**Comment by mostar39** [comment]
Thank you!
