### ISSUE TITLE
Document code error

### ISSUE THREAD

**Issue by YixiaoZhang** [open-mmlab/mmaction2#1017]
Document
https://mmaction2.readthedocs.io/en/latest/getting_started.html

Code Block under
Here is an example of building the model and testing with a given video url.

Code
model = init_recognizer(config_file, checkpoint_file, device=device, use_frames=True)
results = inference_recognizer(model, video, labels, use_frames=True)

It seems that the **_use_frames_** option should be False (default) as it is for video recognition.
model = init_recognizer(config_file, checkpoint_file, device=device)
results = inference_recognizer(model, video, labels)

The Chinese version also has the problem
https://mmaction2.readthedocs.io/zh_CN/latest/getting_started.html

**Comment by kennymckormick** [comment]
Thanks for point out that problem, we will raise a PR to fix it.
