### ISSUE TITLE
Encountered some problems when running the demo_posec3d.py

### ISSUE THREAD

**Issue by SKBL5694** [open-mmlab/mmaction2#1018]
My envrinment: mmcv:1.3.8 mmdet:  2.14.0(2.13.0 has also been tried) mmaction2 0.16.0
When I run the code in [demo/readme](https://github.com/open-mmlab/mmaction2/tree/master/demo#readme) 
"python demo/demo_posec3d.py demo/ntu_sample.avi demo/posec3d_demo.mp4     --config configs/skeleton/posec3d/slowonly_r50_u48_240e_ntu120_xsub_keypoint.py ..."(hide some commands because it's too long for reading), it raises some warnings and an error.
Warnings:
1st `anaconda3/envs/mmaction2/lib/python3.7/site-packages/mmcv/cnn/bricks/transformer.py:27: UserWarning: Fail to import ``MultiScaleDeformableAttention`` from ``mmcv.ops.multi_scale_deform_attn``, You should install ``mmcv-full`` if you need this module..` and 
2nd  `/anaconda3/envs/mmaction2/lib/python3.7/site-packages/mmdet/models/utils/transformer.py:22: UserWarning: MultiScaleDeformableAttention in MMCV has been moved to mmcv.ops.multi_scale_deform_attn, please update your MMCV`. The 2nd warnings repeat 4 times.
And 1 error: 
`Traceback (most recent call last):
  File "demo/demo_posec3d.py", line 274, in <module>
    main()
  File "demo/demo_posec3d.py", line 212, in main
    det_results = detection_inference(args, frame_paths)
  File "demo/demo_posec3d.py", line 164, in detection_inference
    model = init_detector(args.det_config, args.det_checkpoint, args.device)
  File "/home/zy/anaconda3/envs/mmaction2/lib/python3.7/site-packages/mmaction/utils/decorators.py", line 12, in new_func
    f'Please install {module_name} to use {func.__name__}.')
ImportError: Please install mmdet to use init_detector.`
But I'm sure I've installed the mmdet as I show in the first line, my environment.
What's more, I run this command in ipython `from mmdet.apis import inference_detector` as it causes the errors, it raise another error ` ImportError: libcudart.so.10.2: cannot open shared object file: No such file or directory`
Can anybody tell me what causes this error and those warnings and how I can solve them? I'm very grateful for your reply.

**Comment by limcherhang** [comment]
Hi, can you told me how to fixed this problem?

**Comment by belzx** [comment]
this issue has been soluted？

**Comment by belzx** [comment]
I meet same problem，has this issue been soluted？

**Comment by lyooyl** [comment]
I meet same problem too...., how soluted?
