### ISSUE TITLE
Can not play the video generated from the pose_c3d demo.

### ISSUE THREAD

**Issue by SKBL5694** [open-mmlab/mmaction2#1019]
I run the commmand 
` python demo/demo_posec3d.py demo/ntu_sample.avi demo/posec3d_demo.mp4     --config configs/skeleton/posec3d/slowonly_r50_u48_240e_ntu120_xsub_keypoint.py     --checkpoint https://download.openmmlab.com/mmaction/skeleton/posec3d/slowonly_r50_u48_240e_ntu120_xsub_keypoint/slowonly_r50_u48_240e_ntu120_xsub_keypoint-6736b03f.pth     --det-config demo/faster_rcnn_r50_fpn_2x_coco.py     --det-checkpoint http://download.openmmlab.com/mmdetection/v2.0/faster_rcnn/faster_rcnn_r50_fpn_2x_coco/faster_rcnn_r50_fpn_2x_coco_bbox_mAP-0.384_20200504_210434-a5d8aa15.pth     --det-score-thr 0.9     --pose-config demo/hrnet_w32_coco_256x192.py     --pose-checkpoint https://download.openmmlab.com/mmpose/top_down/hrnet/hrnet_w32_coco_256x192-c78dce93_20200708.pth     --label-map demo/label_map_ntu120.txt ` successfully and it shows the info
```
 "Moviepy - Building video demo/posec3d_demo.mp4.
Moviepy - Writing video demo/posec3d_demo.mp4

Moviepy - Done !                                                                                                                                               
Moviepy - video ready demo/posec3d_demo.mp4
"
```
But when I try to play the file 'posec3d_demo.mp4' in VLC, It can't show anything, the same question is also found when I try it on windows by the default media player.
How can I solve this problem? I'm very grateful for your reply.

**Comment by kennymckormick** [comment]
Would you please first check the output file size (is it an empty video)? Besides, can you read the video with python packages cv2, decord or moviepy?

**Comment by kennymckormick** [comment]
Close it due to no response in a week. Feel free to reopen it if there is any update.

**Comment by sunfeiran0228** [comment]
@SKBL5694  hello, I'm having the same issue. My video cannot play either whose size is 204kb. Could you please tell me how you solve the problem? Thank you very  much!
