### ISSUE TITLE
Is there any tool for calculating flops of the model?

### ISSUE THREAD

**Issue by SKBL5694** [open-mmlab/mmaction2#1022]
I want to see the flops of the model in mmaction2. In other project I use thop.profile to do this. But I can do this in mmaction2, because the model in mmac2 use a dict as input not the tensor. I have no idea how to deal with this situation. Can anybody help me with that? Thx a lot.

**Comment by irvingzhang0512** [comment]
[get_flops.py](https://github.com/open-mmlab/mmaction2/blob/master/tools/analysis/get_flops.py)

**Comment by SKBL5694** [comment]
> [get_flops.py](https://github.com/open-mmlab/mmaction2/blob/master/tools/analysis/get_flops.py)

Thx a lot.

**Comment by SKBL5694** [comment]
> [get_flops.py](https://github.com/open-mmlab/mmaction2/blob/master/tools/analysis/get_flops.py) and [docs](https://mmaction2.readthedocs.io/en/latest/useful_tools.html#model-complexity)

QAQ, I think it's not useful for the model posec3d. I tried to modify some code about input_shape in get_flops.py, But it seems not helpful.

**Comment by kennymckormick** [comment]
Calculating FLOPs for PoseC3D is the same as other 3D-CNNs. To test the FLOPs of PoseC3D, first build the Recognizer3D, then set the input_shape as (1, input_channel, temporal_lenght, height, width).

**Comment by SKBL5694** [comment]
> Calculating FLOPs for PoseC3D is the same as other 3D-CNNs. To test the FLOPs of PoseC3D, first build the Recognizer3D, then set the input_shape as (1, input_channel, temporal_lenght, height, width).

I got it, thx for your reply.
