### ISSUE TITLE
The Accuracy of tsm-mobilenetv2 in test

### ISSUE THREAD

**Issue by barbecacov** [open-mmlab/mmaction2#1024]
dataset:  my own dataset

tsm-ckpt:  I finetue my own dataset by the TSM official repo, then get the ckpt; 

mm-ckpt: depends on the key of tsm-mobilnetv2 in mmaction2, I copy the weight of tsm-ckpt to mm-ckpt.

test: I use tsm-ckpt to take a test with TSM official repo then get a result A; another way, I use mm-ckpt to take a test with mmaction2 then get a result B: But the B and the A is apparently different.

onnx: I trans the two ckpt to onnx respectively. and the result of inference is same.

Question: I wander if the preprocess and the sampling is a little different between the TSM official repo and mmaction2

**Comment by irvingzhang0512** [comment]
Can you please share your scripts or codes of testing both TSM official repo and MMAction2? I may take a look when I have time

**Comment by barbecacov** [comment]
test details in TSM official repo:

python test_models.py --test_segments=8 --test_crops=1 --batch_size=16 --gpus 0,2 --weights=***.pth --dense_sample False --twice_sample False --full_res False --input_size 224

  cropping = torchvision.transforms.Compose([
      GroupScale(net.scale_size),
      GroupCenterCrop(input_size),
  ])
   Stack(roll=(this_arch in ['BNInception', 'InceptionV3'])),
   ToTorchFormatTensor(div=(this_arch not in ['BNInception', 'InceptionV3'])),
   GroupNormalize(net.input_mean, net.input_std),


test details in TSM official repo:

img_norm_cfg = dict(
    mean=[123.675, 116.28, 103.53], std=[58.395, 57.12, 57.375], to_bgr=False)

val_pipeline = [
    dict(
        type='SampleFrames',
        clip_len=1,
        frame_interval=1,
        num_clips=8,
        test_mode=True),
    dict(type='RawFrameDecode'),
    dict(type='Resize', scale=(-1, 256)),
    dict(type='CenterCrop', crop_size=224),
    dict(type='Normalize', **img_norm_cfg),
    dict(type='FormatShape', input_format='NCHW'),
    dict(type='Collect', keys=['imgs', 'label'], meta_keys=[]),
    dict(type='ToTensor', keys=['imgs'])
]
test_pipeline = [
    dict(
        type='SampleFrames',
        clip_len=1,
        frame_interval=1,
        num_clips=8,
        test_mode=True),
    dict(type='RawFrameDecode'),
    dict(type='Resize', scale=(-1, 256)),
    dict(type='CenterCrop', crop_size=224),
    dict(type='Normalize', **img_norm_cfg),
    dict(type='FormatShape', input_format='NCHW'),
    dict(type='Collect', keys=['imgs', 'label'], meta_keys=[]),
    dict(type='ToTensor', keys=['imgs'])
]

**Comment by dreamerlin** [comment]
Their test pipelines are almost the same to each other.

**Comment by dreamerlin** [comment]
We port the TSM-MobileNetV2 [here](https://github.com/open-mmlab/mmaction2/pull/1163), the acc of the test is higher than the original repo.
