### ISSUE TITLE
A bug in demo/visualize_heatmap_volume.ipynb caused by the mismatch of the version of mmpose

### ISSUE THREAD

**Issue by SKBL5694** [open-mmlab/mmaction2#1029]
When  I run a cell  
`# Visualize Skeleton
vis_frames = vis_skeleton(vid_path, anno, gym_categories[anno['label']])
vid = mpy.ImageSequenceClip(vis_frames, fps=24)
vid.ipython_display()` 
in [visualize_heatmap_volume.ipynb](demo/visualize_heatmap_volume.ipynb), it raise an 'devided by zero' error, I can run it correctly before.
I check the traceback, and I remember I changed my mmpose version from 0.13.0 to 0.16.0 yesterday to use the latest [posec3d](demo/demo_posec3d.py) demo.(Posec3d demo can't use with the version of mmpose under 0.16.0)
And I reinstall the 0.13.0 mmpose, the [visualize_heatmap_volume.ipynb](demo/visualize_heatmap_volume.ipynb) works again.
So the case seems to be: demo_posec3d needs the version of mmpose not lower than 0.16.0(latest), however,   visualize_heatmap_volume can not run through the 0.16.0 version of mmpose. These two demo can not run at the same time.

**Comment by SKBL5694** [comment]
@kennymckormick

**Comment by Deep-learning999** [comment]
I also encountered this problem

**Comment by kennymckormick** [comment]
We will raise a PR to fix this problem.

**Comment by kennymckormick** [comment]
PR #796 is already merged in MMPose.
