### ISSUE TITLE
Official SlowOnly-Sthsthv1 Checkpoint Is Missing

### ISSUE THREAD

**Issue by rogercmq** [open-mmlab/mmaction2#1033]
If you feel we have help you, give us a STAR! :satisfied:

**Notice**

There are several common situations in the reimplementation issues as below

1. Reimplement a model in the model zoo using the provided configs
2. Reimplement a model in the model zoo on other dataset (e.g., custom datasets)
3. Reimplement a custom model but all the components are implemented in MMAction2
4. Reimplement a custom model with new modules implemented by yourself

There are several things to do for different cases as below.

- For case 1 & 3, please follow the steps in the following sections thus we could help to quick identify the issue.
- For case 2 & 4, please understand that we are not able to do much help here because we usually do not know the full code and the users should be responsible to the code they write.
- One suggestion for case 2 & 4 is that the users should first check whether the bug lies in the self-implemented code or the original code. For example, users can first make sure that the same model runs well on supported datasets. If you still need help, please describe what you have done and what you obtain in the issue, and follow the steps in the following sections and try as clear as possible so that we can better help you.

**Checklist**

1. I have searched related issues but cannot get the expected help.
2. The issue has not been fixed in the latest version.

**Describe the issue**

The checkpoint & log url for [slowonly-sthsthv1 config](https://github.com/open-mmlab/mmaction2/blob/647ba48b45ea3a4a29f5305666c0077151222ea8/configs/recognition/slowonly/slowonly_imagenet_pretrained_r50_8x4x1_64e_sthv1_rgb.py) is actually slowonly-ucf101. While in my implementation (using the same cfg file except that random flipping is not implemented), the top1 accuracy is around 44 (<<46).

**Comment by dreamerlin** [comment]
You can try https://github.com/open-mmlab/mmaction2/pull/1034

**Comment by rogercmq** [comment]
Thanks!
