### ISSUE TITLE
About the input of posec3d

### ISSUE THREAD

**Issue by Deep-learning999** [open-mmlab/mmaction2#1037]
Before raising a question, you may need to check the following listed items.

**Checklist**

1. I have searched related issues but cannot get the expected help.
2. I have read the [FAQ documentation](https://mmaction2.readthedocs.io/en/latest/faq.html) but cannot get the expected help.

When performing motion detection, the input of posec3d is 1, 20, 17, 48, 64, 64. What is the 48 of this dimension? If there are three people in the current frame, what is the input dimension? It is the detection frame extraction for each person The heatmap, the formed Keypoint Heatmap Volume are input into posec3d separately, or the Keypoint Heatmap Volume of three people is input together
@kennymckormick

**Comment by kennymckormick** [comment]
48 is the temporal dimension; The input shape is the same no matter how many people are in the videos, keypoints of different persons will be drawn on the same canvas.

**Comment by Deep-learning999** [comment]
Thanks for the answer
