### ISSUE TITLE
How to config the mobilenetv2 widen_factor=0.5 and the pretrained ckpt

### ISSUE THREAD

**Issue by barbecacov** [open-mmlab/mmaction2#1039]
backbone=dict(
        type='MobileNetV2TSM',
        shift_div=8,
        num_segments=8,
        is_shift=True,
        widen_factor=0.5,
        pretrained='mmcls://mobilenet_v2'),

But the pretrained is still the mobilenet_v2(widen_factor=1.0)'s， So How can i change it for the "pretrained="

**Comment by dreamerlin** [comment]
you can change the `pretrained='mmcls://mobilenet_v2'` to other one that uses mobilenet_v2(widen_factor=1.0)

**Comment by barbecacov** [comment]
But I want to use smaller backbone(mobilenet_v2(widen_factor=0.5))

**Comment by dreamerlin** [comment]
The pretrained model is provided in mmcls which seemingly only contains `widen_factor=1.0` now @LXXXXR @ycxioooong

**Comment by kennymckormick** [comment]
For now, we do not provide Imagenet pretrained mobilenet_v2(widen_factor=0.5), you can try to find a pretrain model with this configuration or train it from scratch.
