### ISSUE TITLE
Where can I download ntu120_xsub_train.pkl

### ISSUE THREAD

**Issue by Deep-learning999** [open-mmlab/mmaction2#1041]
Before raising a question, you may need to check the following listed items.

**Checklist**

1. I have searched related issues but cannot get the expected help.
2. I have read the [FAQ documentation](https://mmaction2.readthedocs.io/en/latest/faq.html) but cannot get the expected help.
Where can I download ntu120_xsub_train.pkl

**Comment by kennymckormick** [comment]
Due to the conditions of use of NTURGB-D dataset, we can not release our pose annotations at that time. If you need them, please send a request to my email: dhd.efz@gmail.com. We will release the scripts to generate NTURGB-D pose annotations in several weeks.

**Comment by Deep-learning999** [comment]
Sent, thank you
