### ISSUE TITLE
Optimizing the spatio temporal Action Detection Models pretrained/custom trained

### ISSUE THREAD

**Issue by arvindchandel** [open-mmlab/mmaction2#1042]
Hi, How i can further optimise the spatio temporal model for making them more efficient like pruning or quantizing it, if possible. Need suggestions on this.

**Comment by arvindchandel** [comment]
@kennymckormick Hi kenny, sorry to drag you in the old issue, but i am still looking for a way to optimize the slowfast model file by converting it to tensorrt/onnx or through other way. ONNX conversion script doesn't support for slowfast model. seek your inputs on this.

**Comment by kennymckormick** [comment]
Sorry, we haven't supported tensorrt/onnx conversion of spatio-temporal action detection yet.
