### ISSUE TITLE
PoseC3D paper question

### ISSUE THREAD

**Issue by HoBeom** [open-mmlab/mmaction2#1043]
![image](https://user-images.githubusercontent.com/37523098/126307146-90142a8f-564f-4f8f-b0a3-85ccf39ada74.png)
I don't know if it's right to ask here, but I'm leaving a question out of curiosity.

1. When PoseC3D is tested on NTU60, I wonder if it is a common phenomenon that the performance is reduced for longer videos.
2. What exactly does % mean?

**Comment by kennymckormick** [comment]
1. Yes.
2. % means the quantile of video length, for example, 10% means the shortest 10% of videos.

Besides, if you have any other questions, you can ask me via email: dhd.efz@gmail.com.
