### ISSUE TITLE
SampleFrames ignore tail frames

### ISSUE THREAD

**Issue by makecent** [open-mmlab/mmaction2#1048]
**Reproduce**
```python
from mmaction.datasets.pipelines import SampleFrames
from matplotlib import pyplot as plt
import numpy as np

f = dict(total_frames=1000, start_index=0)
s = SampleFrames(clip_len=1, num_clips=128)

# Sample 1000 times
a = []
for i in range(1000):
    a.append(s(f)['frame_inds'])
a = np.stack(a)

# Count occurance of each index
u, counts = np.unique(a, return_counts=True)
b = []
for i in range(1000):
    try:
        b.append(counts[u.tolist().index(i)])
    except ValueError:
        b.append(0)

# Plot
plt.plot(b)
plt.show()
```
**outs:**
![myplot](https://user-images.githubusercontent.com/42603768/126599016-65397230-64e3-4d9e-ae5e-f32374e9c812.png)
**Comments**
``SampleFrames`` will ignore tail frames because the ``//`` used:
https://github.com/open-mmlab/mmaction2/blob/b8115d918330ccfa451d4aa0ca61877b4dcd806a/mmaction/datasets/pipelines/loading.py#L142-L143

**Comment by kennymckormick** [comment]
Use '/' instead of '//' can be more reasonable, we will add an option to do so.
