### ISSUE TITLE
[Suggestion] Convert data to float32 Tensor by default with warning

### ISSUE THREAD

**Issue by makecent** [open-mmlab/mmaction2#1051]
**Motivation**
It's very common to get ``nan`` problems when the ``dtype`` of data are different. And sometimes it's very hard to debug.

**Feature suggestion**
Currently, the pipeline ``ToTensor`` inherit the dtype from original data:
https://github.com/open-mmlab/mmaction2/blob/76db1813f01d157aaf12f8b034358b305052d522/mmaction/datasets/pipelines/formating.py#L11-L27
I suggest adding some postprocessing codes to detect the float type, 32 or 64, of the generated Tensor. If they are of ``tensor.float64``, maybe we can convert them to ``tensor.float32`` by default with a warning. And provide an argument to control the default behavior,

**Comment by kennymckormick** [comment]
We shouldn't assume 'float32' a default float type, since 'float16' might also be used during training.
