### ISSUE TITLE
How to speed the module called GeneratePoseTarget in testline

### ISSUE THREAD

**Issue by ZhangLei999** [open-mmlab/mmaction2#1052]
I want to speed the preprocess of posec3d, such as GeneratePoseTarget. Can you give some advice. Thanks!

**Comment by kennymckormick** [comment]
That's not easy ... That implement of GeneratePoseTarget is already a relatively fast one, and it consumes a large proportion of pre-processing time. Maybe you can ignore keypoints with low confidence scores to speed up the preprocessing.

**Comment by ZhangLei999** [comment]
Thanks for your reply. I think the heatmap generated by testline can be replaced by the gaussian-heatmap of keyponits-detect. But I'm not sure.

**Comment by kennymckormick** [comment]
> Thanks for your reply. I think the heatmap generated by testline can be replaced by the gaussian-heatmap of keyponits-detect. But I'm not sure.

Yes, it's OK to use estimated heatmaps directly.
