### ISSUE TITLE
Is there a way to use precise_bn during testing (after training)?

### ISSUE THREAD

**Issue by lambert-x** [open-mmlab/mmaction2#1054]
I want to test my previous trained models with precise_bn and notice that **current precise_bn hook can only be used in training**. Is there an elegant way to **test with precise_bn**?

**Comment by kennymckormick** [comment]
@gengenkai  Would you please take a look at this issue

**Comment by gengenkai** [comment]
got it.

**Comment by gengenkai** [comment]
> I want to test my previous trained models with precise_bn and notice that **current precise_bn hook can only be used in training**. Is there an elegant way to **test with precise_bn**?

**Comment by gengenkai** [comment]
> I want to test my previous trained models with precise_bn and notice that **current precise_bn hook can only be used in training**. Is there an elegant way to **test with precise_bn**?

Hi, I have tried testing with precise_bn  to update the mean and var of all the BN layers and retest, the results are almost the same ( acc top1 & top5 0.7564 0.9222 -> 0.7558 0.9223) .
