### ISSUE TITLE
Can someone share the something-something v2?

### ISSUE THREAD

**Issue by kami93** [open-mmlab/mmaction2#1055]
Hi. As some people here might have already noticed, the something-something v2 dataset is not available online anymore, for unknown reasons. Since the dataset is widely used among SOTA models, including those available in mmaction2, it would be useful for people to have an unofficial source for the dataset for reproducibility.

Can someone please share the dataset? Or make it available in, for example, https://academictorrents.com/ ?

**Comment by kennymckormick** [comment]
Sorry, due to the terms of this dataset, a third party can not share the videos or annotations with other people. Maybe you can try to contact 20BN or the author of the dataset paper.
