### ISSUE TITLE
how to use mixup/cutmix/label_smooth at the same time

### ISSUE THREAD

**Issue by nbl97** [open-mmlab/mmaction2#1057]
I have learned that the mixup/cutmix/labem_smooth could be used by fill the `blending` parameter in `train_cfg`. However, how to use these three augmentations at the same time? For example, MViT [https://arxiv.org/abs/2104.11227](url) uses these 3 augmentations simultaneously.

**Comment by irvingzhang0512** [comment]
For now, MMAction2 doesn't support mixup/cutmix/label_smoth at the same time. I may take a look in August
