### ISSUE TITLE
hmdb51 label maps

### ISSUE THREAD

**Issue by LiUzHiAn** [open-mmlab/mmaction2#1062]
Hi,

Could you please share the lable map of `hmdb51` dataset, just as `Kinetics400 `?

**Comment by dreamerlin** [comment]
The label map will be generated when you generate the filelist.
Ref: https://github.com/open-mmlab/mmaction2/blob/master/tools/data/parse_file_list.py#L420-L506

**Comment by LiUzHiAn** [comment]
Thanks for the quick reply. Will check it later.
