### ISSUE TITLE
Why it needs more GPU memory than training when it is testing？

### ISSUE THREAD

**Issue by barbecacov** [open-mmlab/mmaction2#1063]
I use this [Config File](https://github.com/open-mmlab/mmaction2/blob/master/configs/recognition/tsm/tsm_mobilenetv2_video_dense_1x1x8_100e_kinetics400_rgb.py) ,Even I set the 
test_pipeline = [
    dict(type='DecordInit'),
    dict(
        type='DenseSampleFrames',
        clip_len=1,
        frame_interval=1,
        num_clips=8,
        test_mode=True),
    dict(type='DecordDecode'),
    dict(type='Resize', scale=(-1, 256)),
    dict(type='CenterCrop', crop_size=256),
    dict(type='Normalize', **img_norm_cfg),
    dict(type='FormatShape', input_format='NCHW'),
    dict(type='Collect', keys=['imgs', 'label'], meta_keys=[]),
    dict(type='ToTensor', keys=['imgs'])
].

And the Validation is very slow

**Comment by YNawal** [comment]
num_clips=1 it worked for me

**Comment by dreamerlin** [comment]
For testing, if you use 'DenseSampleFrames', it will sample more frames (10 times) than that in training.
Ref: https://github.com/open-mmlab/mmaction2/blob/master/mmaction/datasets/pipelines/loading.py#L381-L404
