### ISSUE TITLE
Data Augmentation for Video

### ISSUE THREAD

**Issue by wenjun90** [open-mmlab/mmaction2#1064]
Hello @dreamerlin,

Thank you and your team for your contribution.
 Could I ask you a question for Data Augmentation, please?

How can we set the config for augmentation data during training?

Thank you very much!

**Comment by dreamerlin** [comment]
Ref: https://github.com/open-mmlab/mmaction2/blob/master/configs/recognition/tsn/tsn_fp16_r50_1x1x3_100e_kinetics400_rgb.py#L15-L31

You can set your Data Augmentation in config like this.

**Comment by dreamerlin** [comment]
And I you find this repo help you, you can give us a star : ) !

**Comment by irvingzhang0512** [comment]
There are 4 kinds of data augmentation for training

1. Native MMAction2 data augmentation pipelines [here](https://github.com/open-mmlab/mmaction2/blob/master/mmaction/datasets/pipelines/augmentations.py), such as flip/resize/crop/colorjitter...
2. Third-party library Imgaug, such as RandAugment. Demos could be find #492 #585
3. Third-party library TorchVideo, such as RandAugment/AugMix. Demos could be find #1008
4. Mixup and Cutmix, demos could be find #681

**Comment by irvingzhang0512** [comment]
Besides, you can refer to the configs of [tsm-r50/sthv1](https://github.com/open-mmlab/mmaction2/tree/master/configs/recognition/tsm), which contains a lot of different data augmentation pipelines.

**Comment by wenjun90** [comment]
Thank you @dreamerlin  and @irvingzhang0512 

Could I ask you more question, please @dreamerlin?
I still don't quite understand these parameters: **dict(type='SampleFrames', clip_len=1, frame_interval=1, num_clips=3)**

- clip_len=1, it means that len of clip = 1s extract randomly from the total length of clip (for exemple length of clip = 10s)
- frame_interval = 1 and num_clips = 3, what means?

Thank you very much!

**Comment by irvingzhang0512** [comment]
@wenjun90 https://github.com/open-mmlab/mmaction2/discussions/655#discussioncomment-409496

**Comment by wenjun90** [comment]
thank you @irvingzhang0512  and @dreamerlin,
I did the data augmentation like that:

**_base_ = ['./slowfast_r50_4x16x1_256e_kinetics400_rgb.py']

model = dict(
    backbone=dict(
        resample_rate=8,  # tau
        speed_ratio=8,  # alpha
        channel_ratio=8  # beta_inv
    ))

# dataset settings
dataset_type = 'VideoDataset'
data_root = 'data/kinetics400/videos_train'
data_root_val = 'data/kinetics400/videos_val'
ann_file_train = 'data/kinetics400/kinetics400_train_list_videos.txt'
ann_file_val = 'data/kinetics400/kinetics400_val_list_videos.txt'
ann_file_test = 'data/kinetics400/kinetics400_val_list_videos.txt'
img_norm_cfg = dict(
    mean=[123.675, 116.28, 103.53], std=[58.395, 57.12, 57.375], to_bgr=False)
train_pipeline = [
    dict(type='DecordInit'),
    dict(type='SampleFrames', clip_len=32, frame_interval=2, num_clips=1),
    dict(type='DecordDecode'),
    dict(type='Resize', scale=(-1, 256)),
    dict(type='RandomResizedCrop'),
    dict(type='Resize', scale=(224, 224), keep_ratio=False),
    dict(type='Flip', flip_ratio=0.5),
    dict(type='Imgaug', transforms='default'),
    #dict(type='MultiScaleCrop', input_size=224, scales=(1, 0.875, 0.75, 0.66), random_crop=False, max_wh_scale_gap=1),    
    dict(type='Normalize', **img_norm_cfg),
    dict(type='FormatShape', input_format='NCTHW'),
    dict(type='Collect', keys=['imgs', 'label'], meta_keys=[]),
    dict(type='ToTensor', keys=['imgs', 'label'])
]
val_pipeline = [
    dict(type='DecordInit'),
    dict(
        type='SampleFrames',
        clip_len=32,
        frame_interval=2,
        num_clips=1,
        test_mode=True),
    dict(type='DecordDecode'),
    dict(type='Resize', scale=(-1, 256)),
    dict(type='CenterCrop', crop_size=224),
    dict(type='Normalize', **img_norm_cfg),
    dict(type='FormatShape', input_format='NCTHW'),
    dict(type='Collect', keys=['imgs', 'label'], meta_keys=[]),
    dict(type='ToTensor', keys=['imgs'])
]
test_pipeline = [
    dict(type='DecordInit'),
    dict(
        type='SampleFrames',
        clip_len=32,
        frame_interval=2,
        num_clips=10,
        test_mode=True),
    dict(type='DecordDecode'),
    dict(type='Resize', scale=(-1, 256)),
    dict(type='ThreeCrop', crop_size=256),
    dict(type='Normalize', **img_norm_cfg),
    dict(type='FormatShape', input_format='NCTHW'),
    dict(type='Collect', keys=['imgs', 'label'], meta_keys=[]),
    dict(type='ToTensor', keys=['imgs'])
]
data = dict(
    videos_per_gpu=8,
    workers_per_gpu=4,
    train=dict(
        type=dataset_type,
        ann_file=ann_file_train,
        data_prefix=data_root,
        pipeline=train_pipeline),
    val=dict(
        type=dataset_type,
        ann_file=ann_file_val,
        data_prefix=data_root_val,
        pipeline=val_pipeline),
    test=dict(
        type=dataset_type,
        ann_file=ann_file_test,
        data_prefix=data_root_val,
        pipeline=test_pipeline))

# runtime settings
work_dir = './work_dirs/slowfast_r50_video_3d_4x16x1_256e_kinetics400_rgb'**

But there is an error:

**Traceback (most recent call last):
  File "mmaction2/train.py", line 96, in <module>
    train_model(model, datasets, cfg, distributed=False, validate=True)
  File "/home//user/mmaction2/mmaction/apis/train.py", line 164, in train_model
    runner.run(data_loaders, cfg.workflow, cfg.total_epochs, **runner_kwargs)
  File "/home//user/miniconda3/envs/MMaction2/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 127, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/home//user/miniconda3/envs/MMaction2/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 47, in train
    for i, data_batch in enumerate(self.data_loader):
  File "/home//user/miniconda3/envs/MMaction2/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 517, in __next__
    data = self._next_data()
  File "/home//user/miniconda3/envs/MMaction2/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1199, in _next_data
    return self._process_data(data)
  File "/home//user/miniconda3/envs/MMaction2/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1225, in _process_data
    data.reraise()
  File "/home//user/miniconda3/envs/MMaction2/lib/python3.7/site-packages/torch/_utils.py", line 429, in reraise
    raise self.exc_type(msg)
RuntimeError: Caught RuntimeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home//user/miniconda3/envs/MMaction2/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 202, in _worker_loop
    data = fetcher.fetch(index)
  File "/home//user/miniconda3/envs/MMaction2/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 47, in fetch
    return self.collate_fn(data)
  File "/home//user/miniconda3/envs/MMaction2/lib/python3.7/site-packages/mmcv/parallel/collate.py", line 81, in collate
    for key in batch[0]
  File "/home//user/miniconda3/envs/MMaction2/lib/python3.7/site-packages/mmcv/parallel/collate.py", line 81, in <dictcomp>
    for key in batch[0]
  File "/home//user/miniconda3/envs/MMaction2/lib/python3.7/site-packages/mmcv/parallel/collate.py", line 84, in collate
    return default_collate(batch)
  File "/home//user/miniconda3/envs/MMaction2/lib/python3.7/site-packages/torch/utils/data/_utils/collate.py", line 55, in default_collate
    return torch.stack(batch, 0, out=out)
RuntimeError: stack expects each tensor to be equal size, but got [1, 3, 32, 224, 224] at entry 0 and [1, 3, 32, 112, 112] at entry 1**


How can we fix this error?


Thank you so much!

**Comment by wenjun90** [comment]
Hey @dreamerlin and @irvingzhang0512 ,
Could I ask you a question for learning rate in slowfast, please?
I do my training with 1GPU and 8 video/gpu, so learning rate need to set 0.01?
Beacause  lr=0.01 for 4 GPUs x 2 video/gpu and lr=0.08 for 16 GPUs x 4 video/gpu.
Thank you very much.

**Comment by wenjun90** [comment]
Hi @irvingzhang0512 ,
I did training with pytorchvideo.AugMix, training time is more long than I don't use augmentation. It is normal?

**Comment by irvingzhang0512** [comment]
Yes, it's normal, DataAugment requires a lot of cpu resources.

**Comment by wenjun90** [comment]
thank @irvingzhang0512 ,

Could I ask you 2 question, please?
+ How can I use the config slowfast_r152_r50_4x16x1_256e_kinetics400_rgb with typedataset is "VideosDataset"?
+ Can I use the multiscale like that:
    dict(
        type='MultiScaleCrop',
        input_size=224,
        scales=(1, 0.875, 0.75, 0.66),
        random_crop=False,
        max_wh_scale_gap=1,
        num_fixed_crops=13),
for slowfast 

Thank you very much.

**Comment by kennymckormick** [comment]
1. You should: 
    1. set `dataset_type` as `VideoDataset`; 
    2. use data list for videos (each line is like `video.mp4 label`); 
    3. modify data pipeline, use `DecordInit` and `DecordDecode`. 
2. That's OK, but the performance might be inferior.

**Comment by bit-scientist** [comment]
I am finding it hard to calculate a value for learning rate when different number of GPUs available. Since `lr` is set to 0.01 for 4 GPUs x 2 video/gpu and `lr`=0.08 for 16 GPUs x 4 video/gpu, what exact value should I choose for my `lr` if I have one GPU (32 Gb) with batchsize = 64?

**Comment by kennymckormick** [comment]
Since the total batch size is still 64, you can use 0.08.

**Comment by WEIZHIHONG720** [comment]
Will the video data use "cutout" as data augmentation? If so, what is the typical cutout ratio setting? Thanks!
