### ISSUE TITLE
20bn website is not available, where can I download data?

### ISSUE THREAD

**Issue by JiaMingLin** [open-mmlab/mmaction2#1069]
Hi, 
I need to download the something-to-something and jester datasets. But the 20bn website are not available for weeks, the error message is "503 Service Temporarily Unavailable". 

I have already downloaded the video data of something-to-something v2, and I need the label dataset. For the Jester, I need both video and label data. Can someone share me the download link?

Please let me know if this post is not appropriate here, I will close it immediately.

Thanks.

**Comment by kennymckormick** [comment]
Sorry, due to the terms of this dataset, a third party can not share the videos or annotations with other people. Maybe you can try to contact 20BN or the author of the dataset paper.
