### ISSUE TITLE
Including label maps for all datasets

### ISSUE THREAD

**Issue by bicsi** [open-mmlab/mmaction2#1070]
Currently as I've seen that there is no label maps file for any dataset other than Kinetics400. As far as I understand that the label map files are generated by the scripts inside each dataset; however, it feels superfluous to have to download a (potentially large) dataset, especially in the case where one only wants to use the pre-trained models. 

This currently makes the usage of `inference_recognizer` function (and inference in general) more involved than necessary in my opinion. 

I think it would be a good suggestion to add label maps for all datasets as standalone files in the repo. Alternatively, is there a way one could generate them without having to download the datasets?

**Comment by kennymckormick** [comment]
That makes sense. We will include label maps for the datasets.
