### ISSUE TITLE
BMN result gap with original paper

### ISSUE THREAD

**Issue by pengjinqiang** [open-mmlab/mmaction2#1074]
1. I found that there is a huge gap of mAP between mmaction2 and original paper. Do you solve the problem, or do you know how is that and how to reproduce the result.
2. Did you reproduce the BMN result on THUMOS datasets, I try to reproduce the result, but it still has a gap with original paper.

**Comment by kennymckormick** [comment]
1. Perhaps MMAction2 and BMN use different ways to assign action labels for each proposal: MMAction2 useS the CUHK17-ActivityNet solution for untrimmed video recognition to assign action labels for all clips that belong to an untrimmed video. We don't know how BMN assigns action labels to proposals (not mentioned in the paper & no code was released). With the same label assigning strategies, our re-implementation has a higher mAP than the original BMN repo.
2. We haven't trained BMN on THUMOS.

**Comment by pengjinqiang** [comment]
Thanks for you reply. In BMN paper, they seem to use CUHK17 too. 

![99](https://user-images.githubusercontent.com/38968032/129012388-1cedc5b7-81f6-45cb-84ab-3b727397dd87.png)
![111](https://user-images.githubusercontent.com/38968032/129012397-c72deb42-228e-415c-a556-2fe0bd6cf70d.png)

**Comment by pengjinqiang** [comment]
> 1. Perhaps MMAction2 and BMN use different ways to assign action labels for each proposal: MMAction2 useS the CUHK17-ActivityNet solution for untrimmed video recognition to assign action labels for all clips that belong to an untrimmed video. We don't know how BMN assigns action labels to proposals (not mentioned in the paper & no code was released). With the same label assigning strategies, our re-implementation has a higher mAP than the original BMN repo.
> 2. We haven't trained BMN on THUMOS.

Thanks for you reply. In BMN paper, they seem to use CUHK17 too. 

![99](https://user-images.githubusercontent.com/38968032/129012388-1cedc5b7-81f6-45cb-84ab-3b727397dd87.png)
![111](https://user-images.githubusercontent.com/38968032/129012397-c72deb42-228e-415c-a556-2fe0bd6cf70d.png)

**Comment by kennymckormick** [comment]
> > 1. Perhaps MMAction2 and BMN use different ways to assign action labels for each proposal: MMAction2 useS the CUHK17-ActivityNet solution for untrimmed video recognition to assign action labels for all clips that belong to an untrimmed video. We don't know how BMN assigns action labels to proposals (not mentioned in the paper & no code was released). With the same label assigning strategies, our re-implementation has a higher mAP than the original BMN repo.
> > 2. We haven't trained BMN on THUMOS.
> 
> Thanks for you reply. In BMN paper, they seem to use CUHK17 too.
> 
> ![99](https://user-images.githubusercontent.com/38968032/129012388-1cedc5b7-81f6-45cb-84ab-3b727397dd87.png)
> ![111](https://user-images.githubusercontent.com/38968032/129012397-c72deb42-228e-415c-a556-2fe0bd6cf70d.png)

However, we are sure that our label assigning strategy is not the same as theirs. We have tested their proposals with our labeling strategy: the mAP is not the same as the BMN paper, and even inferior to our implementation.
