### ISSUE TITLE
Why the update_interval affects the running speed?

### ISSUE THREAD

**Issue by nbl97** [open-mmlab/mmaction2#1077]
I understand that the `update_interval` in `optimizer_config` is equivalent to the accumulations-steps technique, which should not affect the running speed (or just slightly). However, I found that with the same `videos_per_gpu=16`, there is a big difference in the running speed of two experiments with different `update_interval`.
Experiment 1:
`update_interval=2` which means 8 videos/gpu in one batch. A line in log
`Epoch [6][1300/1838]	lr: 2.166e-04, eta: 4 days, 10:01:10, time: 1.044, data_time: 0.001, memory: 11653, loss_cls: 5.2737, loss: 5.2737`

Experiment 2:
`update_interval=8` which means 2 videos/gpu in one batch. The same line in log
`Epoch [6][1300/7349]	lr: 2.039e-04, eta: 9 days, 10:45:26, time: 0.553, data_time: 0.001, memory: 3533, loss_cls: 5.1432, loss: 5.1432`

It can be seen that the more videos put on gpu, the faster the training.  The time for an 8 videos batch forward in experiment 1 is 1.044 but that for 2 videos batch in experiment 2 is 0.553. The ratio of time doesn't match the ratio of batch size. I am sure all the other settings are exactly the same.

What is the potential reason for that phenomenon?  The inappropriate setting such as workers or the inherent problem in recording?

Thanks a lot!

**Comment by kennymckormick** [comment]
I can not find this option in our project, the keyword `update_interval` can not be found in mmaction2 / mmcv
