### ISSUE TITLE
In the command of converting C3d model to onnx, the following error occurs,does this code not support the conversion of C3d model to onnx?

### ISSUE THREAD

**Issue by lotuser1** [open-mmlab/mmaction2#1079]
In the command of converting C3d model to onnx, the following error occurs.
run this command`python tools/deployment/pytorch2onnx.py /home/文档/mmaction2/configs/recognition/c3d/c3d_sports1m_16x1x1_45e_ucf101_rgb.py /home/文档/mmaction2/checkpoint/c3d.pth --shape 1 1 3 32 128 171`
but alert `RuntimeError: size mismatch, m1: [1 x 30720], m2: [8192 x 4096] at /opt/conda/conda-bld/pytorch_1587428398394/work/aten/src/TH/generic/THTensorMath.cpp:41
`does this code not support the conversion of C3d model to onnx?

**Comment by irvingzhang0512** [comment]
Current implementation of C3D only supports fixed size input `(1, 1, 3, 16, 112, 112)`
