### ISSUE TITLE
how to download something-something dataset? official website is unavailable now

### ISSUE THREAD

**Issue by caopulan** [open-mmlab/mmaction2#1080]
Official website of something-something v1 & v2 (TwentyBN) is unavailable now [sth-sth-v2](https://20bn.com/datasets/something-something/v2).  I don't find any shared copy. Could you help me? Thanks a lot.

**Comment by irvingzhang0512** [comment]
#1069

> Sorry, due to the terms of this dataset, a third party can not share the videos or annotations with other people. Maybe you can try to contact 20BN or the author of the dataset paper.
