### ISSUE TITLE
A large performance gap between the saved checkpoints (best_top1_acc_epoch_xx.pth and epoch_xx.pth)

### ISSUE THREAD

**Issue by lambert-x** [open-mmlab/mmaction2#1082]
I am using precisebn and notice that the performance with the two checkpoints (best_top1_acc_epoch_xx.pth and epoch_xx.pth) have a large gap around 5 percentage. **They have same training epochs,** and the performance with best_top1_acc_epoch_xx.pth seems to be accurate compared to the validation results during training. By the way, their size is not same (best_top1_acc_epoch_xx.pth is smaller). I think this is a bug and should be fixed. Could you please check it?

**Comment by kennymckormick** [comment]
@gengenkai

**Comment by gengenkai** [comment]
> I am using precisebn and notice that the performance with the two checkpoints (best_top1_acc_epoch_xx.pth and epoch_xx.pth) have a large gap around 5 percentage. **They have same training epochs,** and the performance with best_top1_acc_epoch_xx.pth seems to be accurate compared to the validation results during training. By the way, their size is not same (best_top1_acc_epoch_xx.pth is smaller). I think this is a bug and should be fixed. Could you please check it?

Thanks for your advice. We will check it within this week.

**Comment by gengenkai** [comment]
> I am using precisebn and notice that the performance with the two checkpoints (best_top1_acc_epoch_xx.pth and epoch_xx.pth) have a large gap around 5 percentage. **They have same training epochs,** and the performance with best_top1_acc_epoch_xx.pth seems to be accurate compared to the validation results during training. By the way, their size is not same (best_top1_acc_epoch_xx.pth is smaller). I think this is a bug and should be fixed. Could you please check it?

Hi. By the way, could you provide the config file you used ? Thanks.

**Comment by lambert-x** [comment]
> > I am using precisebn and notice that the performance with the two checkpoints (best_top1_acc_epoch_xx.pth and epoch_xx.pth) have a large gap around 5 percentage. **They have same training epochs,** and the performance with best_top1_acc_epoch_xx.pth seems to be accurate compared to the validation results during training. By the way, their size is not same (best_top1_acc_epoch_xx.pth is smaller). I think this is a bug and should be fixed. Could you please check it?
> 
> Hi. By the way, could you provide the config file you used ? Thanks.

Sorry, I cannot offer the config now because there is some custom code still in progress. I just use precise_bn as the offered example: `precise_bn = dict(num_iters=200, interval=5)`

**Comment by gengenkai** [comment]
If you use our provided config files and find this problem, please let us know. As you use your custom config file, we have no idea to help you find out the problem. Maybe you can set some breakpoints in your custom modules and check it.

**Comment by gengenkai** [comment]
> > > I am using precisebn and notice that the performance with the two checkpoints (best_top1_acc_epoch_xx.pth and epoch_xx.pth) have a large gap around 5 percentage. **They have same training epochs,** and the performance with best_top1_acc_epoch_xx.pth seems to be accurate compared to the validation results during training. By the way, their size is not same (best_top1_acc_epoch_xx.pth is smaller). I think this is a bug and should be fixed. Could you please check it?
> > 
> > 
> > Hi. By the way, could you provide the config file you used ? Thanks.
> 
> Sorry, I cannot offer the config now because there is some custom code still in progress. I just use precise_bn as the offered example: `precise_bn = dict(num_iters=200, interval=5)`

If you use our provided config files and find this problem, please let us know. As you use your custom config file, we have no idea to help you find out the problem. Maybe you can set some breakpoints in your custom modules and check it.

**Comment by dreamerlin** [comment]
Reopen this issue if you encounter any problems.
