### ISSUE TITLE
bug in support multiple metrics

### ISSUE THREAD

**Issue by Uriya3** [open-mmlab/mmaction2#1083]
hi,
if metrics list included 'mean_average_precision' and 'mmit_mean_average_precision', it corrupts gt_labels for the second iteration.
gt_labels should be save in a different variable or put it inside the [for metric in metrics] scope 

https://github.com/open-mmlab/mmaction2/blob/79fba89a5e01580c851ea9fce7e28fa7024b8830/mmaction/datasets/base.py#L226

**Comment by kennymckormick** [comment]
@gengenkai , would you please help fix this issue?

**Comment by gengenkai** [comment]
> @gengenkai , would you please help fix this issue?

Got it.
