### ISSUE TITLE
ntu_pose_extraction.py

### ISSUE THREAD

**Issue by mostar39** [open-mmlab/mmaction2#1085]
Hello..
 
Other than that, I looked at the ntu_pose_extraction.py file, is it correct to extract the skeleton data from the video data?
If so, is it possible to extract skeleton data from any other videos?

**Comment by kennymckormick** [comment]
Yes, it extracts skeleton data from NTURGB+D videos. It can also be used to extract skeleton data from any other videos, but remember to remove the specific post-processing for NTU videos.
