### ISSUE TITLE
Can someone provide the tag proposals of SSN? Download failed.

### ISSUE THREAD

**Issue by HongdongZheng** [open-mmlab/mmaction2#1089]
Can someone provide the tag proposals of SSN in these two links below:
https://open-mmlab.s3.ap-northeast-2.amazonaws.com/mmaction/filelist/thumos14_tag_val_normalized_proposal_list.txt
https://open-mmlab.s3.ap-northeast-2.amazonaws.com/mmaction/filelist/thumos14_tag_test_normalized_proposal_list.txt

Download failed because of 404 Not Found:

$ bash fetch_tag_proposals.sh
--2021-08-11 17:09:12--  https://open-mmlab.s3.ap-northeast-2.amazonaws.com/mmaction/filelist/thumos14_tag_val_normalized_proposal_list.txt
Resolving open-mmlab.s3.ap-northeast-2.amazonaws.com (open-mmlab.s3.ap-northeast-2.amazonaws.com)... 52.219.144.19
Connecting to open-mmlab.s3.ap-northeast-2.amazonaws.com (open-mmlab.s3.ap-northeast-2.amazonaws.com)|52.219.144.19|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2021-08-11 17:09:13 ERROR 404: Not Found.

--2021-08-11 17:09:13--  https://open-mmlab.s3.ap-northeast-2.amazonaws.com/mmaction/filelist/thumos14_tag_test_normalized_proposal_list.txt
Resolving open-mmlab.s3.ap-northeast-2.amazonaws.com (open-mmlab.s3.ap-northeast-2.amazonaws.com)... 52.219.58.19
Connecting to open-mmlab.s3.ap-northeast-2.amazonaws.com (open-mmlab.s3.ap-northeast-2.amazonaws.com)|52.219.58.19|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2021-08-11 17:09:15 ERROR 404: Not Found.

**Comment by kennymckormick** [comment]
Sorry, it seems that these files have been removed by the administrator, we have no backup either.
