### ISSUE TITLE
想制作自己的数据集，仿造ava2.2格式，但是看了教程，并没有写关于这部分（人体检测proposal+行为检测）

### ISSUE THREAD

**Issue by gzchenjiajun** [open-mmlab/mmaction2#1092]
教程中《制造新数据集》的部分只有视频识别和activitynet，而不涉及人体proposal后的行为检测这部分 nethttps://mmaction2.readthedocs.io/zh_CN/stable/tutorials/3_new_dataset.html

我看到了mmaction/datasets/ava_dataset.py,mmaction.datasets.pipelines.loading.SampleAVAFrames的相关源码，但是有没更加简易清晰的ava数据集制作“脚手架“可以开箱即制作的？
我目前在用slowfast_kinetics_pretrained_r50_8x8x1_cosine_10e_ava22_rgb.py相关模型

**Comment by gzchenjiajun** [comment]
.. code-block:: JSON

        {
            ...
            '0f39OWEqJ24,0902':
                array([[0.011   , 0.157   , 0.655   , 0.983   , 0.998163]]),
            '0f39OWEqJ24,0912':
                array([[0.054   , 0.088   , 0.91    , 0.998   , 0.068273],
                       [0.016   , 0.161   , 0.519   , 0.974   , 0.984025],
                       [0.493   , 0.283   , 0.981   , 0.984   , 0.983621]]),
            ...
        }


想请问下，array里第一列到第五列分别是什么含义呀？（没在注释里看到，也可能能是我漏看了哪个doc？）

**Comment by kennymckormick** [comment]
You can refer PR #1097 for AVA annotation format.

**Comment by gzchenjiajun** [comment]
Thanks  ! This is so good!
