### ISSUE TITLE
`"[mov,mp4,m4a,3gp,3g2,mj2 @ 0x564bb98b99e0] moov atom not found,Invalid data found when processing input"`

### ISSUE THREAD

**Issue by gzchenjiajun** [open-mmlab/mmaction2#1093]
`"[mov,mp4,m4a,3gp,3g2,mj2 @ 0x564bb98b99e0] moov atom not found
../../../data/ava/videos/_ithRWANKB0.mp4: Invalid data found when processing input"`

源数据 ../../../data/ava/videos/_ithRWANKB0.mp4 是存在的，但是ffmpeg在cut_videos.sh时报这个错，我在想是不是ffmpeg版本差异问题导致？

想问下作者的ffmpeg版本是多少？

我的是”ffmpeg version 3.4.8-0ubuntu0.2 Copyright (c) 2000-2020 the FFmpeg developers
built with gcc 7 (Ubuntu 7.5.0-3ubuntu1~18.04)“

**Comment by irvingzhang0512** [comment]
Maybe the video is broken, try to redownload this video first

**Comment by gzchenjiajun** [comment]
> Maybe the video is broken, try to redownload this video first

Yes,video is broken
