### ISSUE TITLE
想自己标注ava数据集，ava数据集的标注工具，有推荐的资料吗？

### ISSUE THREAD

**Issue by gzchenjiajun** [open-mmlab/mmaction2#1094]
我们采集了一部分自己场景下的数据集，想要自己标注，想请问下有没方便好用的标注工具推荐？（我知道这部分属于ava的issue，但就是上来问一下~~）

**Comment by gzchenjiajun** [comment]
想请问下，关于proposal.pkl的数据内容注释，有文档吗？我不太理解每一列的含义
如下
 '7SGCpWCNN84,1732': array([[0.257   , 0.138   , 0.319   , 0.304   , 0.937366]]),

**Comment by kennymckormick** [comment]
Please refer to PR #1097 on the annotation format of AVA.

**Comment by gzchenjiajun** [comment]
Thanks  ! This is so good!
