### ISSUE TITLE
AttributeError: 'ABC' object has no attribute 'XXX'

### ISSUE THREAD

**Issue by rlleshi** [open-mmlab/mmaction2#1095]
@ntu_pose_extraction.py, [this](https://github.com/open-mmlab/mmaction2/blob/master/tools/data/skeleton/ntu_pose_extraction.py#L27) assignment will throw an error for python 3.8+

**Reproduction**
```
>>> import abc
>>> args = abc.ABC()
>>> args.number = 1
```

**Error traceback**
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'ABC' object has no attribute 'number'
```

**Comment by kennymckormick** [comment]
You are right, we should use abc.abstractproperty() instead
