### ISSUE TITLE
单机单卡训练已经work了，但是单机多卡训练报错

### ISSUE THREAD

**Issue by gzchenjiajun** [open-mmlab/mmaction2#1100]
单机单卡训练命令：
python -m tools.train  configs/detection/ava/slowfast_kinetics_pretrained_r50_8x8x1_cosine_10e_ava22_rgb.py
正常

单机多卡训练命令：
bash ./tools/dist_train.sh  configs/detection/ava/slowfast_kinetics_pretrained_r50_8x8x1_cosine_10e_ava22_rgb.py 2
python -m tools.train  configs/detection/ava/slowfast_kinetics_pretrained_r50_8x8x1_cosine_10e_ava22_rgb.py --gpu-ids 0 1  --launcher pytorch
python -m tools.train  configs/detection/ava/slowfast_kinetics_pretrained_r50_8x8x1_cosine_10e_ava22_rgb.py --gpu-ids 0 1  --launcher 

以上三个单机多卡训练命令均报错，dist_train.sh 对应的报错内容是：
![image](https://user-images.githubusercontent.com/13104274/129694911-60f08e04-3b48-4d6e-b3c1-877e970a19e8.png)

我的GPU及cuda情况：
![image](https://user-images.githubusercontent.com/13104274/129694783-a75fcfea-b14a-4ee3-9da7-51854573d48d.png)

请问如何解决？

**Comment by kennymckormick** [comment]
Please try it with python 3.7. It seems AVA training is not compatible with python 3.6

**Comment by gzchenjiajun** [comment]
My device's python version is 3.7, and I've trained the single card successfully.
any other suggestions? Thank you @kennymckormick
