### ISSUE TITLE
Error during Kinetics 400 download IndexError: list index out of range 

### ISSUE THREAD

**Issue by mbilalshaikh** [open-mmlab/mmaction2#1110]
Thanks for your error report and we appreciate it a lot.
If you feel we have help you, give us a STAR! :satisfied:

**Checklist**

1. I have searched related issues but cannot get the expected help.
2. The bug has not been fixed in the latest version.

**Describe the bug**

**Reproduction**

1. What command or script did you run?

```
bash download_videos.sh kinetics400
```

2. Did you make any modifications on the code or config? Did you understand what you have modified?
 No
3. What dataset did you use?

Kinetics400
**Environment**
sys.platform: linux
Python: 3.7.11 (default, Jul 27 2021, 14:32:16) [GCC 7.5.0]
CUDA available: True
GPU 0,1,2,3,4,5,6,7: GeForce GTX 1080 Ti
CUDA_HOME: /usr
NVCC: Cuda compilation tools, release 10.0, V10.0.130
GCC: gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
PyTorch: 1.4.0+cu100
PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - Intel(R) Math Kernel Library Version 2019.0.4 Product Build 20190411 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v0.21.1 (Git Hash 7d2fd500bc78936d1d648ca713b901012f470dbc)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CUDA Runtime 10.0
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_37,code=compute_37
  - CuDNN 7.6.3
  - Magma 2.5.1
  - Build settings: BLAS=MKL, BUILD_NAMEDTENSOR=OFF, BUILD_TYPE=Release, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -fopenmp -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -O2 -fPIC -Wno-narrowing -Wall -Wextra -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Wno-stringop-overflow, DISABLE_NUMA=1, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, USE_CUDA=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_STATIC_DISPATCH=OFF, 

TorchVision: 0.5.0+cu100
OpenCV: 4.5.3
MMCV: 1.3.11
MMCV Compiler: GCC 7.5
MMCV CUDA Compiler: 10.0
MMAction2: 0.17.0+acce52d

2. You may add addition that may be helpful for locating the problem, such as
    - How you installed PyTorch [e.g., pip, conda, source]
    - pip
    - Other environment variables that may be related (such as `$PATH`, `$LD_LIBRARY_PATH`, `$PYTHONPATH`, etc.)
    - $PATH : bash: /home/muhammadbsheikh/anaconda3/envs/open-mmlab2/bin:/home/muhammadbsheikh/anaconda3/bin:/home/muhammadbsheikh/anaconda3/bin:/home/muhammadbsheikh/app/bin:/home/muhammadbsheikh/anaconda3/condabin:/home/muhammadbsheikh/.vscode-server/bin/c3f126316369cd610563c75b1b1725e0679adfb3/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin: No such file or directory
    - $PYTHONPATH: 

**Error traceback**

If applicable, paste the error traceback here.

```
Traceback (most recent call last):
  File "download.py", line 230, in <module>
    main(**vars(p.parse_args()))
  File "download.py", line 197, in main
    for i, row in dataset.iterrows())
  File "/home/muhammadbsheikh/anaconda3/envs/kinetics/lib/python3.7/site-packages/joblib/parallel.py", line 1042, in __call__
    self.retrieve()
  File "/home/muhammadbsheikh/anaconda3/envs/kinetics/lib/python3.7/site-packages/joblib/parallel.py", line 921, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
  File "/home/muhammadbsheikh/anaconda3/envs/kinetics/lib/python3.7/site-packages/joblib/_parallel_backends.py", line 540, in wrap_future_result
    return future.result(timeout=timeout)
  File "/home/muhammadbsheikh/anaconda3/envs/kinetics/lib/python3.7/concurrent/futures/_base.py", line 435, in result
    return self.__get_result()
  File "/home/muhammadbsheikh/anaconda3/envs/kinetics/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
IndexError: list index out of range
```

Cannot download kinetics-400 due to this issue.

**Comment by irvingzhang0512** [comment]
FYI, download kinetics400 from [cvdf](https://github.com/cvdfoundation/kinetics-dataset) may be a better solution.

**Comment by mbilalshaikh** [comment]
> FYI, download kinetics400 from [cvdf](https://github.com/cvdfoundation/kinetics-dataset) may be a better solution.

Thanks, downloaded using your link. Now how to integrate the dataset with mmaction2. As mmaction2 follows a particular folder for this purpose.

**Comment by kennymckormick** [comment]
The preprocessing of Kinetics-400 is simple: 
1. Trim the video given kinetics annotations if the videos are untrimmed. 
2. Generate train / val  list given kinetics annotations:
    - Each line in the list looks like: ‘{youtube-id}.mp4 {label_index}’ 
    - You can refer to [label_map](https://github.com/open-mmlab/mmaction2/blob/master/tools/data/kinetics/label_map_k400.txt) for the mapping from action name to label_index. Basically, it's the alphabetical order.
