### ISSUE TITLE
What's the elegant way to implement different learning rate schedulers for different parts?

### ISSUE THREAD

**Issue by lambert-x** [open-mmlab/mmaction2#1111]
I am trying to implement the learning rate scheduler in Simsiam https://github.com/facebookresearch/simsiam/blob/a7bc1772896d0dad0806c51f0bb6f3b16d290468/main_simsiam.py#L359.  I think it might be a solution to write a custom hook to reset the learning rate of the head with a fix learning rate. However, I don't fully understand the priority used in mmcv. Could you give some suggestions?

**Comment by kennymckormick** [comment]
It's a good idea to implement your own `OptimizerConstructor` and use it to replace the `DefaultOptimizerConstructor`, you can set the learning rate schedule for each parameter there. You can refer to `TSMConstructor` in this repo.

**Comment by kennymckormick** [comment]
Actually, there is an option named fix_lr, you can create the Constructor for SimSiam like this: 
![image](https://user-images.githubusercontent.com/34324155/131216314-b76df798-4d14-45c8-831d-d18acb5455f1.png)
