### ISSUE TITLE
How to slove  'ImportError: Please install mmdet for spatial temporal detection tasks.

### ISSUE THREAD

**Issue by pokameng** [open-mmlab/mmaction2#1112]
how to solve 'ImportError: Please install mmdet for spatial temporal detection tasks.'? I have installed this mmdet

**Comment by irvingzhang0512** [comment]
This error only occurs when mmdet is not properly installed, or your aren't in the right python environment.
Try to open a new terminal, enter python interpreter and run `import mmdet`

**Comment by pokameng** [comment]
AttributeError: module 'mmcv' has no attribute '__version__'   

it means mmdet is not correctly installed?
@irvingzhang0512

**Comment by irvingzhang0512** [comment]
Yes, mmdet is not properly installed, you can refer to mmdet repo for the installation tutorial

**Comment by irvingzhang0512** [comment]
I guess you should reinstall mmcv-full

**Comment by pokameng** [comment]
ok thanks!!!
，i am trying to reinstall all package


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "open-mmlab/mmaction2"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年8月24日(星期二) 下午5:10
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [open-mmlab/mmaction2] How to slove  'ImportError: Please install mmdet for spatial temporal detection tasks. (#1112)





 
I guess you should reinstall mmcv-full
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by pokameng** [comment]
hello，i have a problem
TypeError: FastRCNN: AVARoIHead: ACRNHead: __init__() got an unexpected keyword argument 'pretrained'


do you have the same problem?




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "open-mmlab/mmaction2"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年8月24日(星期二) 下午5:10
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [open-mmlab/mmaction2] How to slove  'ImportError: Please install mmdet for spatial temporal detection tasks. (#1112)





 
I guess you should reinstall mmcv-full
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by kennymckormick** [comment]
Seems that this issue is resolved and the user raised issue #1113 for the new problem.
