### ISSUE TITLE
TypeError: FastRCNN: AVARoIHead: ACRNHead: __init__() got an unexpected keyword argument 'pretrained'

### ISSUE THREAD

**Issue by pokameng** [open-mmlab/mmaction2#1113]
TypeError: FastRCNN: AVARoIHead: ACRNHead: __init__() got an unexpected keyword argument 'pretrained'
 
When i run this code ,some wrong has occured

I want to use FastRCNN to spatial temporal action

**Comment by kennymckormick** [comment]
Are you using the latest MMAction2?  This error has already been fixed now.

**Comment by pokameng** [comment]
I&nbsp; install mmdet&nbsp; from&nbsp; github.mmdetection,i do not&nbsp; find the latest version.&nbsp; Can you show&nbsp; me address？？？



---Original---
From: "Haodong ***@***.***&gt;
Date: Wed, Aug 25, 2021 13:55 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [open-mmlab/mmaction2] TypeError: FastRCNN: AVARoIHead: ACRNHead: __init__() got an unexpected keyword argument 'pretrained' (#1113)




 
Are you using the latest MMAction2?  This error has already been fixed now.
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by kennymckormick** [comment]
Please check this line: 
https://github.com/open-mmlab/mmaction2/blob/acce52d21a2545d9351b1060853c3bcd171b7158/mmaction/models/heads/misc_head.py#L45

An argument `kwargs` is added to ACRNHead, so it will accept `pretrained` now.
