### ISSUE TITLE
Codefile that combine Backbone and Head

### ISSUE THREAD

**Issue by AslanDevbrat** [open-mmlab/mmaction2#1122]
Hey, I want to know how You are combining backbone and the cls_head? Can you give me the code file in which the whole model is being prepared?

**Comment by dreamerlin** [comment]
https://github.com/open-mmlab/mmaction2/blob/master/mmaction/models/recognizers/base.py#L15-L112

**Comment by AslanDevbrat** [comment]
Thanks a lotfor your help. Your answer help he a lot. Just one more thing, How mmcv joins backbone and a cls_head. Can you show me the exact code line for it

**Comment by dreamerlin** [comment]
In [`def __init__()`](https://github.com/open-mmlab/mmaction2/blob/master/mmaction/models/recognizers/base.py#L15-L112), we define backbone and head for a model. And in [`def forward_train()`](https://github.com/open-mmlab/mmaction2/blob/master/mmaction/models/recognizers/recognizer2d.py#L13-L46), the feat will go through the backbone and head separately.

**Comment by AslanDevbrat** [comment]
Thanks a lot, for clarifying it for me. Your precise explanation was very helpful
