### ISSUE TITLE
When will you add "Multigrid training"?

### ISSUE THREAD

**Issue by donnyyou** [open-mmlab/mmaction2#113]
Multigrid training.

**Comment by dreamerlin** [comment]
Work in progress in [this](https://github.com/open-mmlab/mmaction2/pull/29).

**Comment by donnyyou** [comment]
I have had a look at your code. There seems no dataset implementation! Could you present me some examples?  The getitem of dataset is a list of tuple(idx, size_id). @dreamerlin

**Comment by SuX97** [comment]
> I have had a look at your code. There seems no dataset implementation! Could you present me some examples? The getitem of dataset is a list of tuple(idx, size_id). @dreamerlin

This part is still WIP, but you can imitate [Pyslowfast's implementation](https://github.com/facebookresearch/SlowFast/blob/19e68d0f494332e63df1deb6de6c7be68bfd58b1/slowfast/datasets/kinetics.py#L134) in `rawframe_dataset.py', an example can be:
```python
    def prepare_train_frames(self, idx):
        """Prepare the frames for training given the index."""
        short_cycle_idx = None
        if isinstance(idx, tuple):
            idx, short_cycle_idx = idx
        if short_cycle_idx is not None:
            if short_cycle_idx in [0, 1]:
                last_resize = None
                for trans in self.pipeline.transforms:
                    if isinstance(trans, Resize):
                        last_resize = trans
                last_resize.scale *= int(
                    round(
                        short_cycle_factors[short_cycle_idx]
                        )
                    )

        results = copy.deepcopy(self.video_infos[idx])
        results['filename_tmpl'] = self.filename_tmpl
        results['modality'] = self.modality
        results['start_index'] = self.start_index
        return self.pipeline(results)
```
We will release it after it is tested OK.

**Comment by donnyyou** [comment]
# change the scale of Resize in piplines
Do we need to change the scale of Resize here?

**Comment by SuX97** [comment]
> # change the scale of Resize in piplines
> Do we need to change the scale of Resize here?

Yes, short cycle means change the size of the tensor at each iter. Reference here:
https://github.com/facebookresearch/SlowFast/blob/19e68d0f494332e63df1deb6de6c7be68bfd58b1/slowfast/datasets/kinetics.py#L144
