### ISSUE TITLE
only accept 1 sample at test mode

### ISSUE THREAD

**Issue by pokameng** [open-mmlab/mmaction2#1130]
when i test on acrn ,i set the batchsize==8,but it reports only accept 1 sample at test mode
so how to can i set bigger batchsize?
in mmaction2/mmaction/models/heads line 77:
assert x_shape[0] == 1, 'only accept 1 sample at test mode'
            assert x_shape[0] == len(img_metas) == len(proposal_list)
@lindahua @yuta1125tp @hellock @innerlee @MMLAB-CUHK

**Comment by kennymckormick** [comment]
Sorry, we do not support multi-batch testing for Spatio-temporal detection now.

**Comment by coldmanck** [comment]
> Sorry, we do not support multi-batch testing for Spatio-temporal detection now.

Hi @kennymckormick I'm interested in implementing multi-batch testing for Spatio-temporal detection. Could you please share some hints (or any reference material) on how to implement this? Thanks a lot!

**Comment by kennymckormick** [comment]
Hi, coldmanck. Actually I do not recommend you to implement this feature. The reasons are: 1) The implementation is difficult. 2) Multi-batch testing may not lead to large speed improvement. 

If you really need to implement this feature, you may need to write a sampler to organize images with similar shape in the same batch. You may also need to alter some codes for the detector.
