### ISSUE TITLE
Feature Extraction for UCF101 and Kinetics 400 using TSM?

### ISSUE THREAD

**Issue by mbilalshaikh** [open-mmlab/mmaction2#1133]
Thanks for your feature request and we will review and plan for it when necessary.
If you feel we have help you, give us a STAR! :satisfied:

**Describe the feature**

A feature extractor for UCF101 and kinetics400 using TSM.

**Motivation**
Extracting 2D and 3D features from established model foe popular datasets like UCF101 and Kinetics 400 will help the community.

**Comment by gengenkai** [comment]
> Thanks for your feature request and we will review and plan for it when necessary.
> If you feel we have help you, give us a STAR! 
> 
> **Describe the feature**
> 
> A feature extractor for UCF101 and kinetics400 using TSM.
> 
> **Motivation**
> Extracting 2D and 3D features from established model foe popular datasets like UCF101 and Kinetics 400 will help the community.

Hi. Thanks for your interest. Please refer to our docs/feature_extraction.md, which provides detailed information about feature extraction.
