### ISSUE TITLE
excluded_timestamps相关文件的生成规则是怎么样的？

### ISSUE THREAD

**Issue by gzchenjiajun** [open-mmlab/mmaction2#1135]
我现在正在搜集和标注自有数据，仿造项目的格式数据进行精细化训练，现在遇到一个问题。

我理解就是可以忽略的帧（即未标注的帧）。
但是我看了csv里的内容，例如ava_val_excluded_timestamps_v2.2.csv中5BDj0ow5hnA的1038是未标注帧（如图，1038，1058，1065）
![image](https://user-images.githubusercontent.com/13104274/132272687-30ef84ad-330b-4f51-8e0a-12b8982d6573.png)

但是，在ava_val_v2.2.csv中，其实远远不止1038，1058，1065属于未标注的帧，还包括1030，1031，1036，等帧也是未标注帧
![image](https://user-images.githubusercontent.com/13104274/132272791-0fa261ae-7dab-4a45-909c-057b4790db0f.png)

问题：
1、excluded_timestamps 请问如何理解呢？
2、excluded_timestamps和included_timestamps是否重要，我只将ava_train和ava_val给弄好（自有数据），能否直接开始训练，会不会影响模型效果？

**Comment by kennymckormick** [comment]
1. `excluded_timestamps` just means they are not used for training (we don't know the reason). Actually, they are not included in train/val annotations. 
2. For a custom dataset, you don't need to prepare the `excluded_timestamps` file.

**Comment by gzchenjiajun** [comment]
> 1. `excluded_timestamps` just means they are not used for training (we don't know the reason). Actually, they are not included in train/val annotations.
> 2. For a custom dataset, you don't need to prepare the `excluded_timestamps` file.

补充一个问题：
源码没太看明白，csv中已经有了对应的xmin,xmax,ymin,ymax指示出人体数据了，那么在自己补充的custom数据训练中，ava_dense_proposals_train*.pkl中的人体proposal数据是否还需要生成？好像还是要再生成一份的，是吗？
一直以为觉得这份pkl proposal数据比较多余..

**Comment by gzchenjiajun** [comment]
补充一个问题：
1、自有添加的数据训练与原数据一起混合训练时，是否需要生成proposal.pkl文件？看代码感觉是要的，但是从训练行为模型的角度，感觉不需要也可以训练。
2、我看了下pkl文件内容，有些person proposal包含的帧在csv中没有，这部分帧应该就是当做负样本了吧？

**Comment by gzchenjiajun** [comment]
> 1. `excluded_timestamps` just means they are not used for training (we don't know the reason). Actually, they are not included in train/val annotations.
> 2. For a custom dataset, you don't need to prepare the `excluded_timestamps` file.

补充一个问题：
1、自有添加的数据训练与原数据一起混合训练时，是否需要生成proposal.pkl文件？看代码感觉是要的，但是从训练行为模型的角度，感觉不需要也可以训练。
2、我看了下pkl文件内容，有些person proposal包含的帧在csv中没有，这部分帧应该就是当做负样本了吧？

**Comment by gzchenjiajun** [comment]
@irvingzhang0512

**Comment by gzchenjiajun** [comment]
@dreamerlin 
 thks

**Comment by kennymckormick** [comment]
1. No `proposal.pkl` for new data is OK.
2. These proposals are not used in training, there are no negative samples in the current pipeline. 

BTW, please ask questions **in English**, so that other users who have the same question can benefit from our dialogs.

**Comment by gzchenjiajun** [comment]
OK @kennymckormick

**Comment by gzchenjiajun** [comment]
I added the video data labeled by myself (less than 15 minutes), but there was a limit of 15 minutes frame in the code and an error was reported. I tried to make a change.
Is there a faster way to solve this problem?

FileNotFoundError: [Errno 2] No such file or directory: './data/ava/rawframes/doze_1/img_26999.jpg'
