### ISSUE TITLE
AssertionError: max_testing_views is only compatible with batch_size == 1

### ISSUE THREAD

**Issue by Umaruchain** [open-mmlab/mmaction2#1136]
Before raising a question, you may need to check the following listed items.

**Checklist**

1. I have searched related issues but cannot get the expected help.
2. I have read the [FAQ documentation](https://mmaction2.readthedocs.io/en/latest/faq.html) but cannot get the expected help.

I use 8 gpu to run slowfast in ucf101 and I have changed the cls head from 400 to 101
./tools/dist_train.sh  configs/recognition/slowfast/slowfast_r152_r50_4x16x1_256e_kinetics400_rgb.py 8 --work-dir work_dirs/slowfast_r152_r50_4x16x1_256e_kinetics400_rgb/ --validate --seed 0 --deterministic
it is ok while training but while tesing has error

**Comment by kennymckormick** [comment]
Please set test batch_size to 1 by adding `test_dataloader=dict(videos_per_gpu=1)` in the config file to avoid this problem.
