### ISSUE TITLE
Training (pre-training) and fine-tuning models

### ISSUE THREAD

**Issue by Tortoise17** [open-mmlab/mmaction2#1137]
I have three questions from you. 
1) Is there any possibility to add additional class (in configuration) while fine-tuning any trained model available with your archive? Please if you can guide.
2) Is there any configuration which allows the videos `.mp4 `for training without frame exporting and optical flow? or if not, can take the` mp4` and export the frames and train in same workflow/ configuration instead of exporting first those and than making list, and than training.
3) How much time roughly it should take for optical flow export as by reference e.g., for `kinetics 400 dataset` and how much it may take time for training with default setting and on which `GPU  / no of GPUs` . If you can kindly guide me.

**Comment by gengenkai** [comment]
> 1. Is there any possibility to add additional class (in configuration) while fine-tuning any trained model available with your archive? Please if you can guide.

1. Sure. If you want to add additional class, the num_classes in the cls_head need to be modified. Besides, you can refer to our 'Tutorial 2: Finetuning Models' in our docs.
2. Yes, there already exists some configurations in our mmAction2, such as the config files under the path 'configs/recognition/omnisource'. 
3. As for the time of optical flow extraction on Kinetics400 dataset, it basically takes 3-4 days on 8GPUs/ 1-2 weeks on CPU.
