### ISSUE TITLE
Custom Training of SpatioTemporal Model SlowaFast giving mAP 0.0 

### ISSUE THREAD

**Issue by memona008** [open-mmlab/mmaction2#1140]
Tried to train the model with our custom data (over 200+ videos). After training it with 50 apochs. mAP was still 0.0 after every epoch while validation. Can you help me in this? 

Note: For annotations, I'm using normalized x1,y1 (top left corner) x2,y2 (bottom-right corner). Is it correct format or I need to change it ?

Below is my custom config file:

```

custom_classes = [1, 2, 3, 4, 5]
num_classes = 6
model = dict(
    type='FastRCNN',
    backbone=dict(
        type='ResNet3dSlowOnly',
        depth=50,
        pretrained=None,
        pretrained2d=False,
        lateral=False,
        num_stages=4,
        conv1_kernel=(1, 7, 7),
        conv1_stride_t=1,
        pool1_stride_t=1,
        spatial_strides=(1, 2, 2, 1)),
    roi_head=dict(
        type='AVARoIHead',
        bbox_roi_extractor=dict(
            type='SingleRoIExtractor3D',
            roi_layer_type='RoIAlign',
            output_size=8,
            with_temporal_pool=True),
        bbox_head=dict(
            type='BBoxHeadAVA',
            in_channels=2048,
            num_classes=6,
            multilabel=True,
            topk=(2, 3),
            dropout_ratio=0.5)),
    train_cfg=dict(
        rcnn=dict(
            assigner=dict(
                type='MaxIoUAssignerAVA',
                pos_iou_thr=0.9,
                neg_iou_thr=0.9,
                min_pos_iou=0.9),
            sampler=dict(
                type='RandomSampler',
                num=32,
                pos_fraction=1,
                neg_pos_ub=-1,
                add_gt_as_proposals=True),
            pos_weight=1.0,
            debug=False)),
    test_cfg=dict(rcnn=dict(action_thr=0.002)))
dataset_type = 'AVADataset'
data_root = 'tools/data/SAI/rawframes'
anno_root = 'tools/data/SAI/Annotations'
ann_file_train = 'tools/data/SAI/Annotations/ava_format_train.csv'
ann_file_val = 'tools/data/SAI/Annotations/ava_format_test.csv'
label_file = 'tools/data/SAI/Annotations/action_list.pbtxt'
proposal_file_train = 'tools/data/SAI/Annotations/proposals_train.pkl'
proposal_file_val = 'tools/data/SAI/Annotations/proposals_test.pkl'
img_norm_cfg = dict(
    mean=[123.675, 116.28, 103.53], std=[58.395, 57.12, 57.375], to_bgr=False)
train_pipeline = [
    dict(type='SampleAVAFrames', clip_len=32, frame_interval=16),
    dict(type='RawFrameDecode'),
    dict(type='RandomRescale', scale_range=(256, 320)),
    dict(type='RandomCrop', size=256),
    dict(type='Flip', flip_ratio=0.5),
    dict(
        type='Normalize',
        mean=[123.675, 116.28, 103.53],
        std=[58.395, 57.12, 57.375],
        to_bgr=False),
    dict(type='FormatShape', input_format='NCTHW', collapse=True),
    dict(type='Rename', mapping=dict(imgs='img')),
    dict(type='ToTensor', keys=['img', 'proposals', 'gt_bboxes', 'gt_labels']),
    dict(
        type='ToDataContainer',
        fields=[
            dict(key=['proposals', 'gt_bboxes', 'gt_labels'], stack=False)
        ]),
    dict(
        type='Collect',
        keys=['img', 'proposals', 'gt_bboxes', 'gt_labels'],
        meta_keys=['scores', 'entity_ids'])
]
val_pipeline = [
    dict(type='SampleAVAFrames', clip_len=32, frame_interval=16),
    dict(type='RawFrameDecode'),
    dict(type='Resize', scale=(-1, 256)),
    dict(
        type='Normalize',
        mean=[123.675, 116.28, 103.53],
        std=[58.395, 57.12, 57.375],
        to_bgr=False),
    dict(type='FormatShape', input_format='NCTHW', collapse=True),
    dict(type='Rename', mapping=dict(imgs='img')),
    dict(type='ToTensor', keys=['img', 'proposals']),
    dict(type='ToDataContainer', fields=[dict(key='proposals', stack=False)]),
    dict(
        type='Collect',
        keys=['img', 'proposals'],
        meta_keys=['scores', 'img_shape'],
        nested=True)
]
data = dict(
    videos_per_gpu=1,
    workers_per_gpu=4,
    val_dataloader=dict(
        videos_per_gpu=1, workers_per_gpu=4, persistent_workers=False),
    train_dataloader=dict(
        videos_per_gpu=1, workers_per_gpu=4, persistent_workers=False),
    test_dataloader=dict(
        videos_per_gpu=1, workers_per_gpu=4, persistent_workers=False),
    train=dict(
        type='AVADataset',
        ann_file='tools/data/SAI/Annotations/ava_format_train.csv',
        pipeline=[
            dict(type='SampleAVAFrames', clip_len=32, frame_interval=16),
            dict(type='RawFrameDecode'),
            dict(type='RandomRescale', scale_range=(256, 320)),
            dict(type='RandomCrop', size=256),
            dict(type='Flip', flip_ratio=0.5),
            dict(
                type='Normalize',
                mean=[123.675, 116.28, 103.53],
                std=[58.395, 57.12, 57.375],
                to_bgr=False),
            dict(type='FormatShape', input_format='NCTHW', collapse=True),
            dict(type='Rename', mapping=dict(imgs='img')),
            dict(
                type='ToTensor',
                keys=['img', 'proposals', 'gt_bboxes', 'gt_labels']),
            dict(
                type='ToDataContainer',
                fields=[
                    dict(
                        key=['proposals', 'gt_bboxes', 'gt_labels'],
                        stack=False)
                ]),
            dict(
                type='Collect',
                keys=['img', 'proposals', 'gt_bboxes', 'gt_labels'],
                meta_keys=['scores', 'entity_ids'])
        ],
        label_file='tools/data/SAI/Annotations/action_list.pbtxt',
        proposal_file='tools/data/SAI/Annotations/proposals_train.pkl',
        person_det_score_thr=0.9,
        num_classes=6,
        custom_classes=[1, 2, 3, 4, 5],
        data_prefix='tools/data/SAI/rawframes'),
    val=dict(
        type='AVADataset',
        ann_file='tools/data/SAI/Annotations/ava_format_test.csv',
        pipeline=[
            dict(type='SampleAVAFrames', clip_len=32, frame_interval=16),
            dict(type='RawFrameDecode'),
            dict(type='Resize', scale=(-1, 256)),
            dict(
                type='Normalize',
                mean=[123.675, 116.28, 103.53],
                std=[58.395, 57.12, 57.375],
                to_bgr=False),
            dict(type='FormatShape', input_format='NCTHW', collapse=True),
            dict(type='Rename', mapping=dict(imgs='img')),
            dict(type='ToTensor', keys=['img', 'proposals']),
            dict(
                type='ToDataContainer',
                fields=[dict(key='proposals', stack=False)]),
            dict(
                type='Collect',
                keys=['img', 'proposals'],
                meta_keys=['scores', 'img_shape'],
                nested=True)
        ],
        label_file='tools/data/SAI/Annotations/action_list.pbtxt',
        proposal_file='tools/data/SAI/Annotations/proposals_test.pkl',
        person_det_score_thr=0.9,
        num_classes=6,
        custom_classes=[1, 2, 3, 4, 5],
        data_prefix='tools/data/SAI/rawframes'),
    test=dict(
        type='AVADataset',
        ann_file='tools/data/SAI/Annotations/ava_format_test.csv',
        pipeline=[
            dict(type='SampleAVAFrames', clip_len=32, frame_interval=16),
            dict(type='RawFrameDecode'),
            dict(type='Resize', scale=(-1, 256)),
            dict(
                type='Normalize',
                mean=[123.675, 116.28, 103.53],
                std=[58.395, 57.12, 57.375],
                to_bgr=False),
            dict(type='FormatShape', input_format='NCTHW', collapse=True),
            dict(type='Rename', mapping=dict(imgs='img')),
            dict(type='ToTensor', keys=['img', 'proposals']),
            dict(
                type='ToDataContainer',
                fields=[dict(key='proposals', stack=False)]),
            dict(
                type='Collect',
                keys=['img', 'proposals'],
                meta_keys=['scores', 'img_shape'],
                nested=True)
        ],
        label_file='tools/data/SAI/Annotations/action_list.pbtxt',
        proposal_file='tools/data/SAI/Annotations/proposals_test.pkl',
        person_det_score_thr=0.9,
        num_classes=6,
        custom_classes=[1, 2, 3, 4, 5],
        data_prefix='tools/data/SAI/rawframes'))
optimizer = dict(type='SGD', lr=0.025, momentum=0.9, weight_decay=1e-05)
optimizer_config = dict(grad_clip=dict(max_norm=40, norm_type=2))
lr_config = dict(
    policy='step',
    step=[10, 15],
    warmup='linear',
    warmup_by_epoch=True,
    warmup_iters=5,
    warmup_ratio=0.1)
total_epochs = 50
train_ratio = [1, 1]
checkpoint_config = dict(interval=1)
workflow = [('train', 1)]
evaluation = dict(interval=1, save_best='mAP@0.5IOU')
log_config = dict(interval=20, hooks=[dict(type='TextLoggerHook')])
dist_params = dict(backend='nccl')
log_level = 'INFO'
work_dir = './SAI/slowfast_context_kinetics_pretrained_r50_4x16x1_20e_ava_rgb'
load_from = 'https://download.openmmlab.com/mmaction/recognition/slowfast/slowfast_r50_4x16x1_256e_kinetics400_rgb/slowfast_r50_4x16x1_256e_kinetics400_rgb_20200704-bcde7ed7.pth'
resume_from = None
find_unused_parameters = False
omnisource = False
module_hooks = []
gpu_ids = range(0, 1)


```

**Comment by kennymckormick** [comment]
Please paste some lines of ur annotation.csv

**Comment by arvindchandel** [comment]
@memona008 check your pkl file as well, it should be in defined format as well. I guess pkl is creating some issue in ur case.

**Comment by memona008** [comment]
> <style> </style>
> video	middle_frame_timestamp	x1	y1	x2	y2	action	person_id
> 10x01	4	0.041	0.386	0.217	0.857	2	1
> 10x01	7	0.05	0.333	0.218	0.836	2	1
> 10x01	10	0.054	0.333	0.218	0.834	2	1
> 10x01	13	0.064	0.638	0.297	0.968	5	1
> 10x01	13	0.906	0.501	0.998	0.742	1	2
> 10x01	16	0.61	0.738	0.829	0.998	3	1
> 10x01	19	0.8	0.614	0.998	0.915	1	1
> 10x01	22	0.32	0.857	0.485	0.998	5	1
> 10x01	25	0.028	0.546	0.199	0.876	1	1
> 10x01	28	0.044	0.33	0.21	0.802	2	1
> 10x01	31	0.036	0.341	0.209	0.81	2	1
> 10x01	34	0.127	0.701	0.373	0.998	5	1

Can you confirm that this format is fine? @kennymckormick

**Comment by memona008** [comment]
> @memona008 check your pkl file as well, it should be in defined format as well. I guess pkl is creating some issue in ur case.

I checked my .pkl files , it is according to the format you mentioned in #652 . Still I could,nt even overfit the model on my data.
I have 100+ videos of 80-100 seconds and I have annotated 1 frame out of each 3 seconds segment.

**Comment by arvindchandel** [comment]
@memona008 to overfit and validate the process, u dont need 100+ videos, just take 2-3 videos to try to overfit and validate the process. CSV looks fine to me, can you share the sample of pkl as well.

**Comment by kennymckormick** [comment]
> > <style> </style>
> > video	middle_frame_timestamp	x1	y1	x2	y2	action	person_id
> > 10x01	4	0.041	0.386	0.217	0.857	2	1
> > 10x01	7	0.05	0.333	0.218	0.836	2	1
> > 10x01	10	0.054	0.333	0.218	0.834	2	1
> > 10x01	13	0.064	0.638	0.297	0.968	5	1
> > 10x01	13	0.906	0.501	0.998	0.742	1	2
> > 10x01	16	0.61	0.738	0.829	0.998	3	1
> > 10x01	19	0.8	0.614	0.998	0.915	1	1
> > 10x01	22	0.32	0.857	0.485	0.998	5	1
> > 10x01	25	0.028	0.546	0.199	0.876	1	1
> > 10x01	28	0.044	0.33	0.21	0.802	2	1
> > 10x01	31	0.036	0.341	0.209	0.81	2	1
> > 10x01	34	0.127	0.701	0.373	0.998	5	1
> 
> Can you confirm that this format is fine? @kennymckormick

The format of ur annotation.csv is OK. Maybe you can give a try to @arvindchandel 's proposal: try to overfit your training set at first, and check if you still get 0.0 mAP

**Comment by memona008** [comment]
![E436E66A-60C0-4E2E-8D6D-34170DF6994F](https://user-images.githubusercontent.com/43179211/134766708-c4731441-040e-4196-affc-321cb581791f.jpeg)


@kennymckormick here is my pkl file. Moreover i'm not using any exclude file right now.

**Comment by memona008** [comment]
@arvindchandel , @kennymckormick 
One need I want to mention, I am not using any exclude file. What effect it would have on training?

**Comment by arvindchandel** [comment]
Exclude file u can keep blank, its not mandatory.

**Comment by memona008** [comment]
Tried training again but still it's giving mAP 0.0 on all classes
Have a look
![training_error](https://user-images.githubusercontent.com/43179211/134822775-cf882871-713a-4b41-8568-75023da7b2ba.png)

**Comment by memona008** [comment]
Posted a screenshot of my training mAP above also here are some entries from pkl file:
@arvindchandel , @kennymckormick 
 {'10x18,4': array([[0.658, 0.384, 0.88 , 0.746, 1.   ]]), '10x18,7': array([[0.741, 0.471, 0.988, 0.787, 1.   ]]), '10x09,4': array([[0.108, 0.524, 0.363, 0.947, 1.   ]]), '10x09,7': array([[0.105, 0.532, 0.348, 0.951, 1.   ]]), '10x09,10': array([[0.063, 0.417, 0.272, 0.828, 1.   ]]), '10x09,13': array([[0.208, 0.4  , 0.455, 0.837, 1.   ]])}

**Comment by kennymckormick** [comment]
OK, seems I found a potential problem: you set clip_len as 32, frame_interval as 16, which will cover a long temporal span (~17s), which doesn't fix the pretrain weight and the characteristic of this task. Maybe you can set frame_interval to 2.

**Comment by memona008** [comment]
Ok got it. Also on average my video's length is around 50-60 seconds and the middle frame is extracted and annotated after every 3 seconds which means 20 keyframes in a 60 seconds video. Is these dataset settings correct?

**Comment by kennymckormick** [comment]
It's OK I think

**Comment by memona008** [comment]
@kennymckormick I have changed the frame interval value in config and tried training again. 
It's giving the same result as https://github.com/open-mmlab/mmaction2/issues/1140#issuecomment-927364091
During each epoch recall and precision values are atleast greater than 0. But when epoch ends it gives 0.0 mAP for each class. 
Am I missing something?

**Comment by memona008** [comment]
![image](https://user-images.githubusercontent.com/43179211/135061816-1957e397-dd7d-4670-ac9a-f268076bb34e.png)

@kennymckormick getting these results with trained weights when I try to overfit the model on 10 videos. (length 7-10 seconds)

**Comment by memona008** [comment]
@arvindchandel @kennymckormick please help here.

**Comment by kennymckormick** [comment]
Another possible debugging method is to check the output value of the bbox_head, to see if the predicted score of the GT action class is larger than other classes. If not, there might be some bugs.

**Comment by memona008** [comment]
@kennymckormick  Thank you for quick response. 

I am puzzled about the generated results.csv through test.py script  why it's giving 0,0,1,1 as bounding box? 
During training the recall and precision seems fine but when the validation runs it gives 0 AP on each class as well as 0.0 mAP 
Below is the results.csv generated by my trained weights/ckpt with custom slowfast config. 

![new_csv](https://user-images.githubusercontent.com/43179211/135270486-4d28c20d-5fe5-484a-9a30-a6b6da469dad.png)

**Comment by memona008** [comment]
@kennymckormick can you confirm if my Custom SlowFast Config is fine or not? 
`
custom_classes = [1,2,3,4,5]
num_classes = len(custom_classes) + 1

# model setting
model = dict(
    type='FastRCNN',
    backbone=dict(
        type='ResNet3dSlowFast',
        pretrained=None,
        resample_rate=8,
        speed_ratio=8,
        channel_ratio=8,
        slow_pathway=dict(
            type='resnet3d',
            depth=50,
            pretrained=None,
            lateral=True,
            conv1_kernel=(1, 7, 7),
            dilations=(1, 1, 1, 1),
            conv1_stride_t=1,
            pool1_stride_t=1,
            inflate=(0, 0, 1, 1),
            spatial_strides=(1, 2, 2, 1)),
        fast_pathway=dict(
            type='resnet3d',
            depth=50,
            pretrained=None,
            lateral=False,
            base_channels=8,
            conv1_kernel=(5, 7, 7),
            conv1_stride_t=1,
            pool1_stride_t=1,
            spatial_strides=(1, 2, 2, 1))),
    roi_head=dict(
        type='AVARoIHead',
        bbox_roi_extractor=dict(
            type='SingleRoIExtractor3D',
            roi_layer_type='RoIAlign',
            output_size=8,
            with_temporal_pool=True,
            with_global=True),
        bbox_head=dict(
            type='BBoxHeadAVA',
            in_channels=4608,
            num_classes=num_classes,
            multilabel=True,
            topk=(1,2),
            dropout_ratio=0.5)),
    train_cfg=dict(
        rcnn=dict(
            assigner=dict(
                type='MaxIoUAssignerAVA',
                pos_iou_thr=0.9,
                neg_iou_thr=0.9,
                min_pos_iou=0.9),
            sampler=dict(
                type='RandomSampler',
                num=32,
                pos_fraction=1,
                neg_pos_ub=-1,
                add_gt_as_proposals=True),
            pos_weight=1.0,
            debug=False)),
    test_cfg=dict(rcnn=dict(action_thr=0.002)))

dataset_type = 'AVADataset'
data_root = 'tools/data/SAI/overfit_frames'
anno_root = 'tools/data/SAI/overfit_annotations'

ann_file_train = f'{anno_root}/ava_format_train.csv'
ann_file_val = f'{anno_root}/ava_format_test.csv'

# exclude_file_train = f'{anno_root}/ava_train_excluded_timestamps_v2.1.csv'
# exclude_file_val = f'{anno_root}/ava_val_excluded_timestamps_v2.1.csv'

label_file = f'{anno_root}/action_list.pbtxt'

proposal_file_train = (f'{anno_root}/proposals_train.pkl')
proposal_file_val = f'{anno_root}/proposals_test.pkl'

img_norm_cfg = dict(
    mean=[123.675, 116.28, 103.53], std=[58.395, 57.12, 57.375], to_bgr=False)

train_pipeline = [
    dict(type='SampleAVAFrames', clip_len=32, frame_interval=2),
    dict(type='RawFrameDecode'),
    dict(type='RandomRescale', scale_range=(256, 320)),
    dict(type='RandomCrop', size=256),
    dict(type='Flip', flip_ratio=0.5),
    dict(type='Normalize', **img_norm_cfg),
    dict(type='FormatShape', input_format='NCTHW', collapse=True),
    # Rename is needed to use mmdet detectors
    dict(type='Rename', mapping=dict(imgs='img')),
    dict(type='ToTensor', keys=['img', 'proposals', 'gt_bboxes', 'gt_labels']),
    dict(
        type='ToDataContainer',
        fields=[
            dict(key=['proposals', 'gt_bboxes', 'gt_labels'], stack=False)
        ]),
    dict(
        type='Collect',
        keys=['img', 'proposals', 'gt_bboxes', 'gt_labels'],
        meta_keys=['scores', 'entity_ids'])
]
# The testing is w/o. any cropping / flipping
val_pipeline = [
    dict(type='SampleAVAFrames', clip_len=32, frame_interval=2),
    dict(type='RawFrameDecode'),
    dict(type='Resize', scale=(-1, 256)),
    dict(type='Normalize', **img_norm_cfg),
    dict(type='FormatShape', input_format='NCTHW', collapse=True),
    # Rename is needed to use mmdet detectors
    dict(type='Rename', mapping=dict(imgs='img')),
    dict(type='ToTensor', keys=['img', 'proposals']),
    dict(type='ToDataContainer', fields=[dict(key='proposals', stack=False)]),
    dict(
        type='Collect',
        keys=['img', 'proposals'],
        meta_keys=['scores', 'img_shape'],
        nested=True)
]
data = dict(
    videos_per_gpu=9,
    workers_per_gpu=2,
    val_dataloader=dict(videos_per_gpu=1),
    test_dataloader=dict(videos_per_gpu=1),
    train_dataloader=dict(videos_per_gpu=1),
    train=dict(
        type=dataset_type,
        ann_file=ann_file_train,
#         exclude_file=exclude_file_train,
        pipeline=train_pipeline,
        label_file=label_file,
        proposal_file=proposal_file_train,
        person_det_score_thr=0.7,
        num_classes=num_classes,
        custom_classes=custom_classes,
        data_prefix=data_root),
    val=dict(
        type=dataset_type,
        ann_file=ann_file_val,
#         exclude_file=exclude_file_val,
        pipeline=val_pipeline,
        label_file=label_file,
        proposal_file=proposal_file_val,
        person_det_score_thr=0.7,
        num_classes=num_classes,
        custom_classes=custom_classes,
        data_prefix=data_root))
data['test'] = data['val']


optimizer = dict(type='SGD', lr=0.1125, momentum=0.9, weight_decay=0.00001)
# optimizer = dict(type='SGD', lr=0.1125 momentum=0.9, weight_decay=0.00001)
# this lr is used for 8 gpus

optimizer_config = dict(grad_clip=dict(max_norm=40, norm_type=2))
# learning policy

lr_config = dict(
    policy='step',
    step=[10, 15],
    warmup='linear',
    warmup_by_epoch=True,
    warmup_iters=5,
    warmup_ratio=0.1)
total_epochs = 20
train_ratio=[1,1]
checkpoint_config = dict(interval=1)
workflow = [('train', 1)]
evaluation = dict(interval=1, save_best='mAP@0.5IOU')
log_config = dict(
    interval=20, hooks=[
        dict(type='TextLoggerHook'),
    ])
dist_params = dict(backend='nccl')
log_level = 'INFO'
work_dir = ('./SAI/'
            'custom_slowfast')
load_from = ('https://download.openmmlab.com/mmaction/recognition/slowfast/'
             'slowfast_r50_4x16x1_256e_kinetics400_rgb/'
             'slowfast_r50_4x16x1_256e_kinetics400_rgb_20200704-bcde7ed7.pth')
resume_from = None
find_unused_parameters = False`

**Comment by arvindchandel** [comment]
@memona008 I trained my model on 2070 GPU machine. few parameters i changed in my config file like below:
resample_rate=4,
 speed_ratio=4,

videos_per_gpu=1,
 workers_per_gpu=4,

person_det_score_thr=0.9,

Just check them if they are helpful.

**Comment by memona008** [comment]
@arvindchandel Thanks for your quick response. Can you tell on how many custom classes have you trained your model? Also i am training my model on tesla.t4

**Comment by arvindchandel** [comment]
@memona008 i trained model on 3 classes.

**Comment by memona008** [comment]
> @kennymckormick Thank you for quick response.
> 
> I am puzzled about the generated results.csv through test.py script why it's giving 0,0,1,1 as bounding box? During training the recall and precision seems fine but when the validation runs it gives 0 AP on each class as well as 0.0 mAP Below is the results.csv generated by my trained weights/ckpt with custom slowfast config **Ground Truth** ![GT](https://user-images.githubusercontent.com/43179211/135280395-5e119d3a-72ea-47ae-a1a6-72dccb92c91a.png)
> 
> **Predicted** ![resultsCSv](https://user-images.githubusercontent.com/43179211/135279751-a8479397-a40f-438d-ab32-a8b0c8419173.png)
> 
> and corresponding **bbox_head scores** printed
> 
> ![scores](https://user-images.githubusercontent.com/43179211/135279876-00013f3f-3595-4da5-b09e-f715c8bc953e.png)
> 

@kennymckormick  I was wondering if you have had a chance to look at the details yet

**Comment by memona008** [comment]
> Seems that there are some problems with your proposal file used for validation:
> 
> You can look at here:
> 
> https://github.com/open-mmlab/mmaction2/blob/d5ab34805fe6a02bb98e4af158626a21790b6974/mmaction/datasets/ava_dataset.py#L283
> 
> Since your annotation is invalid, the program directly uses [0, 0, 1, 1] as the proposal, which leads to bad predictions.
> 
> For the correct format of annotations files, you can download a proposal file follow the guide in https://github.com/open-mmlab/mmaction2/tree/master/tools/data/ava, and mimick its format.
> 
> Besides, it seems that your model does learn something: the scores corresponding to the GT labels are relatively large.

@kennymckormick  good catch, we were generating proposals keys like "10x10,4" but the code expects a key with leading zeros in timestamp like "10x10,0004" 
It fixed the issue. 

Thanks a lot for helping.

**Comment by kuangxiaoye** [comment]
芜湖 从这个issue学习到很多！

**Comment by kuangxiaoye** [comment]
> 

Hi memona! Can you takle some about how to normalize the xyxy coordinate？

Thank you very much！

**Comment by SiriusLLL** [comment]
> 
How to generate results.csv by trained weights/ckpt?

**Comment by vaibhav030798** [comment]
@memona008 Hey Memona008, please could you explain this to me? I'm new to mmaction2. Please explain it to me in simple steps.
