### ISSUE TITLE
How to modify the default optimizer hook?

### ISSUE THREAD

**Issue by Cogito2012** [open-mmlab/mmaction2#1142]
Before raising a question, you may need to check the following listed items.

**Checklist**

1. I have searched related issues but cannot get the expected help.
2. I have read the [FAQ documentation](https://mmaction2.readthedocs.io/en/latest/faq.html) but cannot get the expected help.

* * * *
I would like to **modify the gradient**s in each training iteration. 

From the following lines of codes in `EpochBasedRunner`, it seems that I need to customize the `after_train_iter` function from the [mmcv optimizer hook](https://github.com/open-mmlab/mmcv/blob/b4bfeb53c57f2c843cb5015f9c0a2d1689dba9c4/mmcv/runner/hooks/optimizer.py#L22), which is a **built-in class in mmcv**.

```python
    self.call_hook('before_train_epoch')
    time.sleep(2)  # Prevent possible deadlock during epoch transition
    for i, data_batch in enumerate(self.data_loader):
        self._inner_iter = i
        self.call_hook('before_train_iter')
        self.run_iter(data_batch, train_mode=True, **kwargs)  # forward pass
        self.call_hook('after_train_iter')  #  zero_grad, backward, grad_clip, and step.
        self._iter += 1
    
    self.call_hook('after_train_epoch')
    self._epoch += 1
```
So, my question is how to customize the optimizer hook from mmcv, and incorporate it in mmaction2?

**Comment by dreamerlin** [comment]
`OptimizerHook` is built [here](https://github.com/open-mmlab/mmaction2/blob/master/mmaction/apis/train.py#L112) and if you want to customize `OptimizerHook`, you can rewrite it in MMAction2.

Or you can customize a new Hook by inheritance `class Hook` like [this](https://github.com/open-mmlab/mmaction2/blob/master/mmaction/core/scheduler/lr_updater.py) and then register it in `apis/train.py` like [this](https://github.com/open-mmlab/mmaction2/blob/master/mmaction/apis/train.py#L121-L124)

Any suggestion @zhouzaida ?

**Comment by Cogito2012** [comment]
@dreamerlin Thanks! 
Following your hint, I eventually figured out how to customize and register a new optimizer hook, in which I could manipulate the gradient now.
