### ISSUE TITLE
cannot understand this parameter format for audio generation.

### ISSUE THREAD

**Issue by mbilalshaikh** [open-mmlab/mmaction2#1147]
Before raising a question, you may need to check the following listed items.

**Checklist**

1. I have searched related issues but cannot get the expected help.
2. I have read the [FAQ documentation](https://mmaction2.readthedocs.io/en/latest/faq.html) but cannot get the expected help.

'''
python tools/data/extract_audio.py ${ROOT} ${DST_ROOT} [--ext ${EXT}] [--num-workers ${N_WORKERS}] \
    [--level ${LEVEL}]
'''

I am able to understand parameters with $ but don't know how to put other parameters. Can anyone some an example for this?

**Comment by dreamerlin** [comment]
Just like
```
python tools/data/extract_audio.py src_data/ dst_data --ext avi --num-workers 4 --level 2
```

**Comment by mbilalshaikh** [comment]
This approach is not wroking.

There are wrong parameters to variable mappings with extract_audio.py

for example, 'root' is out_dir in the source.

**Comment by dreamerlin** [comment]
Thanks for your report, we will fix it !

**Comment by mbilalshaikh** [comment]
Please share an example for the below format.

python tools/data/build_audio_features.py ${AUDIO_HOME_PATH} ${SPECTROGRAM_SAVE_PATH} [--level ${LEVEL}] \
    [--ext $EXT] [--num-workers $N_WORKERS] [--part $PART]
