### ISSUE TITLE
checkpoint for ucf101 audio 51 classes

### ISSUE THREAD

**Issue by mbilalshaikh** [open-mmlab/mmaction2#1149]
Thanks for your feature request and we will review and plan for it when necessary.
If you feel we have help you, give us a STAR! :satisfied:

**Describe the feature**

**Motivation**

For validation of audio classification on UCF101 with video classification on relevant 51 classes a checkpoint to test TSM an TSN models is critical. Therefore, I request if you can provide a TSM checkpoint for 51 audio classes of UCF101. 

**Related resources**

If there is an official code released or third-party implementations, please also provide the information here, which would be very helpful.

**Additional context**

If you would like to implement the feature and create a PR, please leave a comment here and that would be much appreciated.

**Comment by kennymckormick** [comment]
Sorry, we do not have audio ckpts for ucf101 and hmdb51 right now. If you would like to implement the feature and create a PR, it would be much appreciated.
