### ISSUE TITLE
Useless forward Test code

### ISSUE THREAD

**Issue by 944284742** [open-mmlab/mmaction2#115]
mmaction\models\recognizers\recognizer3d.py       def forward_test(self, imgs):

Loss is not calculated, and accuracy is not calculated. So why do I use it? I recommend printing the accuracy after the evaluation

**Comment by innerlee** [comment]
Could you be more specific about "So why do I use it?"

**Comment by 944284742** [comment]
configs\recognition\slowonly\slowonly_r50_4x16x1_256e_kinetics400_flow.py   In the file, I added the following Settings: workflow = [('train', 1),('val', 1)]。
I wanted to train a epoch after it was used, and val was executed without any printing information.Neither accuracy nor loss shows anything.So Val doesn't have any reference.
You can look at the  run  function in mmcv\runner\epoch_based_runner.py

**Comment by innerlee** [comment]
If i remembered correctly, the val workflow was not the best practice any more.
one can use `--validate` to run validation, which was implemented by hooks https://github.com/open-mmlab/mmaction2/blob/master/mmaction/apis/train.py#L105

**Comment by dreamerlin** [comment]
Hi, `def forward_test(self, imgs)` outputs scores for each classes (The last dimension of it match the num of classes). Then the score will be used for [evaluation](https://github.com/open-mmlab/mmaction2/blob/master/mmaction/datasets/rawframe_dataset.py#L149-L225) (in action recognition, it is usually for `top_k_accuracy`).
`def forward_test(self, imgs)` is used in evaluation and testing. In evaluation, it is called by `EvalHook` or `DistEvalHook`, and then call the [`evalute` function](https://github.com/open-mmlab/mmaction2/blob/master/mmaction/datasets/rawframe_dataset.py#L149-L225) to calculate the performance according to the metrics. Here are the [details](https://github.com/open-mmlab/mmaction2/blob/master/mmaction/core/evaluation/eval_hooks.py#L113-L121). In testing, it also [calculates the score](https://github.com/open-mmlab/mmaction2/blob/master/tools/test.py#L115-L124) and then [does evalutation](https://github.com/open-mmlab/mmaction2/blob/master/tools/test.py#L133)

**Comment by 944284742** [comment]
这是我训练打印的log。可以看到我的设置是workflow: [('train', 1), ('val', 1)]，train模式的打印很正常，但是没有val相关的任何打印，log如下：
2020-08-13 11:19:51,535 - mmaction - INFO - Set random seed to 0, deterministic: True
2020-08-13 11:19:53,414 - mmaction - INFO - Start running, host: root@ebe12713b2cb, work_dir: /work/2.ChiPeak/5.OpenMMLab/1.mmaction2/1.mmaction2/1.mmaction2-init-master/work_dirs/my_slowfast_r50_4x16x1_256e_ucf101_rgb
2020-08-13 11:19:53,414 - mmaction - INFO - workflow: [('train', 1), ('val', 1)], max: 256 epochs
2020-08-13 11:20:03,277 - mmaction - INFO - Epoch [1][20/146]	lr: 1.000e-01, eta: 5:06:58, time: 0.493, data_time: 0.118, memory: 1812, top1_acc: 0.0000, top5_acc: 0.0250, loss_cls: 12.2490, loss: 12.2490, grad_norm: 15.9032
2020-08-13 11:20:10,771 - mmaction - INFO - Epoch [1][40/146]	lr: 1.000e-01, eta: 4:29:59, time: 0.375, data_time: 0.000, memory: 1812, top1_acc: 0.0125, top5_acc: 0.0375, loss_cls: 7.4154, loss: 7.4154, grad_norm: 9.1539
2020-08-13 11:20:18,280 - mmaction - INFO - Epoch [1][60/146]	lr: 1.000e-01, eta: 4:17:43, time: 0.375, data_time: 0.000, memory: 1812, top1_acc: 0.0000, top5_acc: 0.0375, loss_cls: 5.4207, loss: 5.4207, grad_norm: 2.8598
2020-08-13 11:20:25,814 - mmaction - INFO - Epoch [1][80/146]	lr: 1.000e-01, eta: 4:11:44, time: 0.377, data_time: 0.000, memory: 1812, top1_acc: 0.0250, top5_acc: 0.0625, loss_cls: 5.1657, loss: 5.1657, grad_norm: 1.7056
2020-08-13 11:20:33,359 - mmaction - INFO - Epoch [1][100/146]	lr: 1.000e-01, eta: 4:08:09, time: 0.377, data_time: 0.000, memory: 1812, top1_acc: 0.0000, top5_acc: 0.0375, loss_cls: 4.8710, loss: 4.8710, grad_norm: 1.3679
2020-08-13 11:20:40,907 - mmaction - INFO - Epoch [1][120/146]	lr: 1.000e-01, eta: 4:05:44, time: 0.377, data_time: 0.000, memory: 1812, top1_acc: 0.0000, top5_acc: 0.0875, loss_cls: 4.7435, loss: 4.7435, grad_norm: 1.3582
2020-08-13 11:20:48,481 - mmaction - INFO - Epoch [1][140/146]	lr: 1.000e-01, eta: 4:04:05, time: 0.379, data_time: 0.000, memory: 1812, top1_acc: 0.0000, top5_acc: 0.0250, loss_cls: 4.8120, loss: 4.8120, grad_norm: 1.3684
2020-08-13 11:20:50,686 - mmaction - INFO - Saving checkpoint at 1 epochs
2020-08-13 11:21:07,383 - mmaction - INFO - Epoch(train) [1][146]	
2020-08-13 11:21:17,201 - mmaction - INFO - Epoch [2][20/146]	lr: 1.000e-01, eta: 4:02:23, time: 0.491, data_time: 0.110, memory: 1812, top1_acc: 0.0375, top5_acc: 0.1000, loss_cls: 4.7327, loss: 4.7327, grad_norm: 2.2757
2020-08-13 11:21:24,792 - mmaction - INFO - Epoch [2][40/146]	lr: 1.000e-01, eta: 4:01:30, time: 0.380, data_time: 0.000, memory: 1812, top1_acc: 0.0125, top5_acc: 0.0500, loss_cls: 4.7922, loss: 4.7922, grad_norm: 1.2227
2020-08-13 11:21:32,394 - mmaction - INFO - Epoch [2][60/146]	lr: 1.000e-01, eta: 4:00:48, time: 0.380, data_time: 0.000, memory: 1812, top1_acc: 0.0125, top5_acc: 0.1000, loss_cls: 4.5267, loss: 4.5267, grad_norm: 1.1660
2020-08-13 11:21:40,036 - mmaction - INFO - Epoch [2][80/146]	lr: 1.000e-01, eta: 4:00:18, time: 0.382, data_time: 0.000, memory: 1812, top1_acc: 0.0000, top5_acc: 0.1250, loss_cls: 4.7575, loss: 4.7575, grad_norm: 1.1314
2020-08-13 11:21:47,734 - mmaction - INFO - Epoch [2][100/146]	lr: 1.000e-01, eta: 4:00:01, time: 0.385, data_time: 0.000, memory: 1812, top1_acc: 0.0000, top5_acc: 0.0625, loss_cls: 4.6077, loss: 4.6077, grad_norm: 1.0771
2020-08-13 11:21:55,405 - mmaction - INFO - Epoch [2][120/146]	lr: 1.000e-01, eta: 3:59:41, time: 0.384, data_time: 0.000, memory: 1812, top1_acc: 0.0125, top5_acc: 0.0250, loss_cls: 4.7784, loss: 4.7784, grad_norm: 1.0660
2020-08-13 11:22:03,034 - mmaction - INFO - Epoch [2][140/146]	lr: 1.000e-01, eta: 3:59:17, time: 0.381, data_time: 0.000, memory: 1812, top1_acc: 0.0375, top5_acc: 0.0625, loss_cls: 4.7019, loss: 4.7019, grad_norm: 0.9423
2020-08-13 11:22:05,255 - mmaction - INFO - Saving checkpoint at 2 epochs
2020-08-13 11:22:21,814 - mmaction - INFO - Epoch(train) [2][146]	
2020-08-13 11:22:31,752 - mmaction - INFO - Epoch [3][20/146]	lr: 9.998e-02, eta: 3:58:52, time: 0.497, data_time: 0.114, memory: 1812, top1_acc: 0.0250, top5_acc: 0.0750, loss_cls: 4.5984, loss: 4.5984, grad_norm: 0.7983
2020-08-13 11:22:39,419 - mmaction - INFO - Epoch [3][40/146]	lr: 9.998e-02, eta: 3:58:37, time: 0.383, data_time: 0.000, memory: 1812, top1_acc: 0.0125, top5_acc: 0.0875, loss_cls: 4.6129, loss: 4.6129, grad_norm: 0.7506
2020-08-13 11:22:47,118 - mmaction - INFO - Epoch [3][60/146]	lr: 9.998e-02, eta: 3:58:26, time: 0.385, data_time: 0.000, memory: 1812, top1_acc: 0.0000, top5_acc: 0.0625, loss_cls: 4.6211, loss: 4.6211, grad_norm: 0.7574

**Comment by dreamerlin** [comment]
> 这是我训练打印的log。可以看到我的设置是workflow: [('train', 1), ('val', 1)]，train模式的打印很正常，但是没有val相关的任何打印，log如下：
> 2020-08-13 11:19:51,535 - mmaction - INFO - Set random seed to 0, deterministic: True
> 2020-08-13 11:19:53,414 - mmaction - INFO - Start running, host: root@ebe12713b2cb, work_dir: /work/2.ChiPeak/5.OpenMMLab/1.mmaction2/1.mmaction2/1.mmaction2-init-master/work_dirs/my_slowfast_r50_4x16x1_256e_ucf101_rgb
> 2020-08-13 11:19:53,414 - mmaction - INFO - workflow: [('train', 1), ('val', 1)], max: 256 epochs
> 2020-08-13 11:20:03,277 - mmaction - INFO - Epoch [1][20/146] lr: 1.000e-01, eta: 5:06:58, time: 0.493, data_time: 0.118, memory: 1812, top1_acc: 0.0000, top5_acc: 0.0250, loss_cls: 12.2490, loss: 12.2490, grad_norm: 15.9032
> 2020-08-13 11:20:10,771 - mmaction - INFO - Epoch [1][40/146] lr: 1.000e-01, eta: 4:29:59, time: 0.375, data_time: 0.000, memory: 1812, top1_acc: 0.0125, top5_acc: 0.0375, loss_cls: 7.4154, loss: 7.4154, grad_norm: 9.1539
> 2020-08-13 11:20:18,280 - mmaction - INFO - Epoch [1][60/146] lr: 1.000e-01, eta: 4:17:43, time: 0.375, data_time: 0.000, memory: 1812, top1_acc: 0.0000, top5_acc: 0.0375, loss_cls: 5.4207, loss: 5.4207, grad_norm: 2.8598
> 2020-08-13 11:20:25,814 - mmaction - INFO - Epoch [1][80/146] lr: 1.000e-01, eta: 4:11:44, time: 0.377, data_time: 0.000, memory: 1812, top1_acc: 0.0250, top5_acc: 0.0625, loss_cls: 5.1657, loss: 5.1657, grad_norm: 1.7056
> 2020-08-13 11:20:33,359 - mmaction - INFO - Epoch [1][100/146] lr: 1.000e-01, eta: 4:08:09, time: 0.377, data_time: 0.000, memory: 1812, top1_acc: 0.0000, top5_acc: 0.0375, loss_cls: 4.8710, loss: 4.8710, grad_norm: 1.3679
> 2020-08-13 11:20:40,907 - mmaction - INFO - Epoch [1][120/146] lr: 1.000e-01, eta: 4:05:44, time: 0.377, data_time: 0.000, memory: 1812, top1_acc: 0.0000, top5_acc: 0.0875, loss_cls: 4.7435, loss: 4.7435, grad_norm: 1.3582
> 2020-08-13 11:20:48,481 - mmaction - INFO - Epoch [1][140/146] lr: 1.000e-01, eta: 4:04:05, time: 0.379, data_time: 0.000, memory: 1812, top1_acc: 0.0000, top5_acc: 0.0250, loss_cls: 4.8120, loss: 4.8120, grad_norm: 1.3684
> 2020-08-13 11:20:50,686 - mmaction - INFO - Saving checkpoint at 1 epochs
> 2020-08-13 11:21:07,383 - mmaction - INFO - Epoch(train) [1][146]
> 2020-08-13 11:21:17,201 - mmaction - INFO - Epoch [2][20/146] lr: 1.000e-01, eta: 4:02:23, time: 0.491, data_time: 0.110, memory: 1812, top1_acc: 0.0375, top5_acc: 0.1000, loss_cls: 4.7327, loss: 4.7327, grad_norm: 2.2757
> 2020-08-13 11:21:24,792 - mmaction - INFO - Epoch [2][40/146] lr: 1.000e-01, eta: 4:01:30, time: 0.380, data_time: 0.000, memory: 1812, top1_acc: 0.0125, top5_acc: 0.0500, loss_cls: 4.7922, loss: 4.7922, grad_norm: 1.2227
> 2020-08-13 11:21:32,394 - mmaction - INFO - Epoch [2][60/146] lr: 1.000e-01, eta: 4:00:48, time: 0.380, data_time: 0.000, memory: 1812, top1_acc: 0.0125, top5_acc: 0.1000, loss_cls: 4.5267, loss: 4.5267, grad_norm: 1.1660
> 2020-08-13 11:21:40,036 - mmaction - INFO - Epoch [2][80/146] lr: 1.000e-01, eta: 4:00:18, time: 0.382, data_time: 0.000, memory: 1812, top1_acc: 0.0000, top5_acc: 0.1250, loss_cls: 4.7575, loss: 4.7575, grad_norm: 1.1314
> 2020-08-13 11:21:47,734 - mmaction - INFO - Epoch [2][100/146] lr: 1.000e-01, eta: 4:00:01, time: 0.385, data_time: 0.000, memory: 1812, top1_acc: 0.0000, top5_acc: 0.0625, loss_cls: 4.6077, loss: 4.6077, grad_norm: 1.0771
> 2020-08-13 11:21:55,405 - mmaction - INFO - Epoch [2][120/146] lr: 1.000e-01, eta: 3:59:41, time: 0.384, data_time: 0.000, memory: 1812, top1_acc: 0.0125, top5_acc: 0.0250, loss_cls: 4.7784, loss: 4.7784, grad_norm: 1.0660
> 2020-08-13 11:22:03,034 - mmaction - INFO - Epoch [2][140/146] lr: 1.000e-01, eta: 3:59:17, time: 0.381, data_time: 0.000, memory: 1812, top1_acc: 0.0375, top5_acc: 0.0625, loss_cls: 4.7019, loss: 4.7019, grad_norm: 0.9423
> 2020-08-13 11:22:05,255 - mmaction - INFO - Saving checkpoint at 2 epochs
> 2020-08-13 11:22:21,814 - mmaction - INFO - Epoch(train) [2][146]
> 2020-08-13 11:22:31,752 - mmaction - INFO - Epoch [3][20/146] lr: 9.998e-02, eta: 3:58:52, time: 0.497, data_time: 0.114, memory: 1812, top1_acc: 0.0250, top5_acc: 0.0750, loss_cls: 4.5984, loss: 4.5984, grad_norm: 0.7983
> 2020-08-13 11:22:39,419 - mmaction - INFO - Epoch [3][40/146] lr: 9.998e-02, eta: 3:58:37, time: 0.383, data_time: 0.000, memory: 1812, top1_acc: 0.0125, top5_acc: 0.0875, loss_cls: 4.6129, loss: 4.6129, grad_norm: 0.7506
> 2020-08-13 11:22:47,118 - mmaction - INFO - Epoch [3][60/146] lr: 9.998e-02, eta: 3:58:26, time: 0.385, data_time: 0.000, memory: 1812, top1_acc: 0.0000, top5_acc: 0.0625, loss_cls: 4.6211, loss: 4.6211, grad_norm: 0.7574

For evaluation. You should use ['--validate'](https://github.com/open-mmlab/mmaction2/blob/master/tools/train.py#L25-L28) to get the performance of the metrics. ('val', 1) will not do evaluation.

**Comment by innerlee** [comment]
@dreamerlin maybe we should add a warning if the 'val' workflow was detected

**Comment by dreamerlin** [comment]
> 这是我训练打印的log。可以看到我的设置是workflow: [('train', 1), ('val', 1)]，train模式的打印很正常，但是没有val相关的任何打印，log如下：
> 2020-08-13 11:19:51,535 - mmaction - INFO - Set random seed to 0, deterministic: True
> 2020-08-13 11:19:53,414 - mmaction - INFO - Start running, host: root@ebe12713b2cb, work_dir: /work/2.ChiPeak/5.OpenMMLab/1.mmaction2/1.mmaction2/1.mmaction2-init-master/work_dirs/my_slowfast_r50_4x16x1_256e_ucf101_rgb
> 2020-08-13 11:19:53,414 - mmaction - INFO - workflow: [('train', 1), ('val', 1)], max: 256 epochs
> 2020-08-13 11:20:03,277 - mmaction - INFO - Epoch [1][20/146] lr: 1.000e-01, eta: 5:06:58, time: 0.493, data_time: 0.118, memory: 1812, top1_acc: 0.0000, top5_acc: 0.0250, loss_cls: 12.2490, loss: 12.2490, grad_norm: 15.9032
> 2020-08-13 11:20:10,771 - mmaction - INFO - Epoch [1][40/146] lr: 1.000e-01, eta: 4:29:59, time: 0.375, data_time: 0.000, memory: 1812, top1_acc: 0.0125, top5_acc: 0.0375, loss_cls: 7.4154, loss: 7.4154, grad_norm: 9.1539
> 2020-08-13 11:20:18,280 - mmaction - INFO - Epoch [1][60/146] lr: 1.000e-01, eta: 4:17:43, time: 0.375, data_time: 0.000, memory: 1812, top1_acc: 0.0000, top5_acc: 0.0375, loss_cls: 5.4207, loss: 5.4207, grad_norm: 2.8598
> 2020-08-13 11:20:25,814 - mmaction - INFO - Epoch [1][80/146] lr: 1.000e-01, eta: 4:11:44, time: 0.377, data_time: 0.000, memory: 1812, top1_acc: 0.0250, top5_acc: 0.0625, loss_cls: 5.1657, loss: 5.1657, grad_norm: 1.7056
> 2020-08-13 11:20:33,359 - mmaction - INFO - Epoch [1][100/146] lr: 1.000e-01, eta: 4:08:09, time: 0.377, data_time: 0.000, memory: 1812, top1_acc: 0.0000, top5_acc: 0.0375, loss_cls: 4.8710, loss: 4.8710, grad_norm: 1.3679
> 2020-08-13 11:20:40,907 - mmaction - INFO - Epoch [1][120/146] lr: 1.000e-01, eta: 4:05:44, time: 0.377, data_time: 0.000, memory: 1812, top1_acc: 0.0000, top5_acc: 0.0875, loss_cls: 4.7435, loss: 4.7435, grad_norm: 1.3582
> 2020-08-13 11:20:48,481 - mmaction - INFO - Epoch [1][140/146] lr: 1.000e-01, eta: 4:04:05, time: 0.379, data_time: 0.000, memory: 1812, top1_acc: 0.0000, top5_acc: 0.0250, loss_cls: 4.8120, loss: 4.8120, grad_norm: 1.3684
> 2020-08-13 11:20:50,686 - mmaction - INFO - Saving checkpoint at 1 epochs
> 2020-08-13 11:21:07,383 - mmaction - INFO - Epoch(train) [1][146]
> 2020-08-13 11:21:17,201 - mmaction - INFO - Epoch [2][20/146] lr: 1.000e-01, eta: 4:02:23, time: 0.491, data_time: 0.110, memory: 1812, top1_acc: 0.0375, top5_acc: 0.1000, loss_cls: 4.7327, loss: 4.7327, grad_norm: 2.2757
> 2020-08-13 11:21:24,792 - mmaction - INFO - Epoch [2][40/146] lr: 1.000e-01, eta: 4:01:30, time: 0.380, data_time: 0.000, memory: 1812, top1_acc: 0.0125, top5_acc: 0.0500, loss_cls: 4.7922, loss: 4.7922, grad_norm: 1.2227
> 2020-08-13 11:21:32,394 - mmaction - INFO - Epoch [2][60/146] lr: 1.000e-01, eta: 4:00:48, time: 0.380, data_time: 0.000, memory: 1812, top1_acc: 0.0125, top5_acc: 0.1000, loss_cls: 4.5267, loss: 4.5267, grad_norm: 1.1660
> 2020-08-13 11:21:40,036 - mmaction - INFO - Epoch [2][80/146] lr: 1.000e-01, eta: 4:00:18, time: 0.382, data_time: 0.000, memory: 1812, top1_acc: 0.0000, top5_acc: 0.1250, loss_cls: 4.7575, loss: 4.7575, grad_norm: 1.1314
> 2020-08-13 11:21:47,734 - mmaction - INFO - Epoch [2][100/146] lr: 1.000e-01, eta: 4:00:01, time: 0.385, data_time: 0.000, memory: 1812, top1_acc: 0.0000, top5_acc: 0.0625, loss_cls: 4.6077, loss: 4.6077, grad_norm: 1.0771
> 2020-08-13 11:21:55,405 - mmaction - INFO - Epoch [2][120/146] lr: 1.000e-01, eta: 3:59:41, time: 0.384, data_time: 0.000, memory: 1812, top1_acc: 0.0125, top5_acc: 0.0250, loss_cls: 4.7784, loss: 4.7784, grad_norm: 1.0660
> 2020-08-13 11:22:03,034 - mmaction - INFO - Epoch [2][140/146] lr: 1.000e-01, eta: 3:59:17, time: 0.381, data_time: 0.000, memory: 1812, top1_acc: 0.0375, top5_acc: 0.0625, loss_cls: 4.7019, loss: 4.7019, grad_norm: 0.9423
> 2020-08-13 11:22:05,255 - mmaction - INFO - Saving checkpoint at 2 epochs
> 2020-08-13 11:22:21,814 - mmaction - INFO - Epoch(train) [2][146]
> 2020-08-13 11:22:31,752 - mmaction - INFO - Epoch [3][20/146] lr: 9.998e-02, eta: 3:58:52, time: 0.497, data_time: 0.114, memory: 1812, top1_acc: 0.0250, top5_acc: 0.0750, loss_cls: 4.5984, loss: 4.5984, grad_norm: 0.7983
> 2020-08-13 11:22:39,419 - mmaction - INFO - Epoch [3][40/146] lr: 9.998e-02, eta: 3:58:37, time: 0.383, data_time: 0.000, memory: 1812, top1_acc: 0.0125, top5_acc: 0.0875, loss_cls: 4.6129, loss: 4.6129, grad_norm: 0.7506
> 2020-08-13 11:22:47,118 - mmaction - INFO - Epoch [3][60/146] lr: 9.998e-02, eta: 3:58:26, time: 0.385, data_time: 0.000, memory: 1812, top1_acc: 0.0000, top5_acc: 0.0625, loss_cls: 4.6211, loss: 4.6211, grad_norm: 0.7574

[Docstring](https://github.com/open-mmlab/mmaction2/blob/master/mmaction/models/recognizers/base.py#L181-L183)

**Comment by dreamerlin** [comment]
> @dreamerlin maybe we should add a warning if the 'val' workflow was detected

Agree.

**Comment by 944284742** [comment]
这是我执行的指令 configs/recognition/slowfast/my_slowfast_r50_4x16x1_256e_ucf101_rgb.py   --work-dir work_dirs/my_slowfast_r50_4x16x1_256e_ucf101_rgb    --validate --seed 0 --deterministic  
我是已经添加了--validate，但是依旧没有val的任何相关信息打印。请问一下，可能是什么原因

**Comment by dreamerlin** [comment]
It is wired. You may need to check:
1. There should be a `evluation` variable in your configs like `evaluation = dict(interval=5, metrics=['top_k_accuracy', 'mean_class_accuracy'], topk=(1, 5))`
2. Just set `workflow = [('train', 1)]` in your config file and `--validate` in your CLI. It will do evaluation after each interval epoch.

**Comment by dreamerlin** [comment]
The output log will be like
```
2020-08-13 18:41:50,345 - mmaction - INFO - Saving checkpoint at 96 epochs
[>>>>>>>>>>>>>>>>>>>>>>>>] 11552/11522, 6.6 task/s, elapsed: 1750s, ETA:    -4s

2020-08-13 19:11:05,335 - mmaction - INFO - Evaluating top_k_accuracy...
2020-08-13 19:11:05,765 - mmaction - INFO -
top1_acc        0.4543
top5_acc        0.7629
2020-08-13 19:11:05,765 - mmaction - INFO - Evaluating mean_class_accuracy...
2020-08-13 19:11:05,818 - mmaction - INFO -
mean_acc        0.4209
```

**Comment by innerlee** [comment]
off-topic: does a single evaluation need half an hour?

**Comment by 944284742** [comment]
太感谢你了，根据你的提示，已经解决了我的问题，请问一下[('train', 1),('val', 1)] 中的('val', 1)的作用是怎么啊?

**Comment by dreamerlin** [comment]
> off-topic: does a single evaluation need half an hour?

It can be up-speeded by setting [`val_dataloader` options](https://github.com/open-mmlab/mmaction2/blob/master/mmaction/apis/train.py#L94-L103) in config files.

**Comment by 944284742** [comment]
啊? 这样说我不是很明白，不太了解是什么意思。

**Comment by 944284742** [comment]
为什么可以 up-speeded

**Comment by innerlee** [comment]
val workflow is useless and is ignored

**Comment by 944284742** [comment]
明白了，谢谢的热心的答复。解答了我的疑问

**Comment by dreamerlin** [comment]
> 为什么可以 up-speeded

you can set update the `videos_per_gpu` and `workers_per_gpus` etc in `val_dataloader` like
```
data = dict(
    videos_per_gpu=8,
    workers_per_gpu=4,
    val_dataloader=dict(videos_per_gpu=16, workers_per_gpu=8),
    train=dict(
        type=dataset_type,
        ann_file=ann_file_train,
        data_prefix=data_root,
        pipeline=train_pipeline),
    val=dict(
        type=dataset_type,
        ann_file=ann_file_val,
        data_prefix=data_root_val,
        pipeline=val_pipeline),
    test=dict(
        type=dataset_type,
        ann_file=ann_file_test,
        data_prefix=data_root_val,
        pipeline=test_pipeline))
```
