### ISSUE TITLE
I want to use this batch of pre-train models as custom training, is there any way? Because I saw that the map was greater

### ISSUE THREAD

**Issue by gzchenjiajun** [open-mmlab/mmaction2#1158]
I want to use this batch of pre-train models as custom training, is there any way? Because I saw that the map was greater
![image](https://user-images.githubusercontent.com/13104274/133882766-362b65ba-5d49-4ad9-926d-090d8908f791.png)

BTW, I know the bottom ones can do custom training, but I want the above pre-train
![image](https://user-images.githubusercontent.com/13104274/133882771-b57b6534-0078-4c9d-8f18-be5191afbedb.png)

**Comment by gzchenjiajun** [comment]
I changed the parameter (num_classes) in the relevant configuration file, but it failed

ValueError: Target size (torch.Size([7, 80])) must be the same as input size (torch.Size([7, 12]))

**Comment by kennymckormick** [comment]
Did you set the `load_from` argument in the config file? How do you load the pretrained weight?

**Comment by gzchenjiajun** [comment]
yes,profile is the default parameter.
In short,
slowfast_temporal_max_focal_alpha3_gamma1_kinetics_pretrained_r50_8x8x1_c
osine_10e_ava22_rgb.py
and
slowfast_temporal_max_kinetics_pretrained_r50_8x8x1_cosine_10e_ava22_rgb.py

custom training cannot be used, am I right?

**Comment by gzchenjiajun** [comment]
> yes,config file is the default parameter.
> In short,
> slowfast_temporal_max_focal_alpha3_gamma1_kinetics_pretrained_r50_8x8x1_c
> osine_10e_ava22_rgb.py
> and
> slowfast_temporal_max_kinetics_pretrained_r50_8x8x1_cosine_10e_ava22_rgb.py
> [https://download.openmmlab.com/mmaction/recognition/slowfast/slowfast_r50_8x8x1_256e_kinetics400_rgb/slowfast_r50_8x8x1_256e_kinetics400_rgb_20200716-73547d2b.pth]
> custom training cannot be used, am I right?
> 
> @kennymckormick

I added custom_classes = [1, 3, 5, 8, 10, 11, 12, 20, 34, 54, 64, 76]
num_classes = len(custom_classes) + 1

also changed 81 to custom_classes

**Comment by gzchenjiajun** [comment]
solved
