### ISSUE TITLE
Question for the clip_len!

### ISSUE THREAD

**Issue by Jianxin98** [open-mmlab/mmaction2#1161]
Hi Team,
Thank you for great your contribution. I have a question for Timesformer, please?
Can we choose the clip_len = 16 instead clip_len = 8?
Because when I change by  clip_len = 16, there is error.

Thank you for your response.

**Comment by dreamerlin** [comment]
You may need to change [this](https://github.com/open-mmlab/mmaction2/blob/master/configs/recognition/timesformer/timesformer_divST_8x32x1_15e_kinetics400_rgb.py#L10)

**Comment by wenjun90** [comment]
Hi @dreamerlin , @irvingzhang0512 
We can use the pretrained of **vit_base_patch16_384** instead of **vit_base_patch16_224** for training?
If use **vit_base_patch16_384** how can we change the config?

Thank you very much

**Comment by daitranskku** [comment]
Same question with @wenjun90.
I tried to use the **timm** model with different weights, but the author seemed to have converted to a different architecture, and it not working. Could you demonstrate how to convert .pth files from timm to mmaction2, such as **vit_large_patch32_384**? I truly appreciate it.
