### ISSUE TITLE
VideoDataset support for X3D models

### ISSUE THREAD

**Issue by mahdiabdollahpour** [open-mmlab/mmaction2#1162]
Hi

I see X3D models use RawFrameDataset. Is there any way to input a video to X3D models in mmaction2?
BR

**Comment by dreamerlin** [comment]
change the pipeline like [this](https://github.com/open-mmlab/mmaction2/blob/master/configs/recognition/tsn/tsn_r50_320p_1x1x8_100e_kinetics400_rgb.py#L42-L56), and switch `dataset_type = 'VideoDataset'` to `dataset_type = 'RawframeDataset'`

**Comment by mahdiabdollahpour** [comment]
In x3d_s_13x6x1_facebook_kinetics400_rgb the pipeline is already the same as [that](https://github.com/open-mmlab/mmaction2/blob/master/configs/recognition/tsn/tsn_r50_320p_1x1x8_100e_kinetics400_rgb.py#L42-L56) (in tsn_r50_320p_1x1x8_100e_kinetics400_rgb.py). and `dataset_type `is '`RawframeDataset`'.

I actually want to use X3D (which currently the config is defined only for `RawframeDataset`) on `VideoDataset`.
