### ISSUE TITLE
为啥测试比训练和验证都慢好多

### ISSUE THREAD

**Issue by clearlove7-s11** [open-mmlab/mmaction2#1173]
尊敬的开发者：
您好，请问mm系列测试为什么如此之慢，每个模型测试时耗时几乎是训练的十倍左右，我检查了我的显卡占用，不论训练还是测试，显卡占用几乎都是百分之百，测试集还只有训练集的一半大小

**Comment by irvingzhang0512** [comment]
There are a lot of test time augmentation in MMAction2, better to double check your config file
