### ISSUE TITLE
What is the 'label_path' in `inference_recognizer` function ?

### ISSUE THREAD

**Issue by zeakey** [open-mmlab/mmaction2#1185]
I wanna test on my own video clips with pretrained models.

What is the `label_path` here in the inference function `inference_recognizer` ? 

<https://github.com/open-mmlab/mmaction2/blob/c088cb419e364e37bd6cb7e9b0b87f840ba817d2/mmaction/apis/inference.py#L60-L65>

How can I get the `label_path` file with my own video clips ?

___

Another problem is that I cannot initiate a skeleton-based action recognisor with:
```
from mmaction.apis import init_recognizer
from mmcv import Config
init_recognizer(Config.fromfile('mmaction2/configs/skeleton/posec3d/slowonly_r50_u48_240e_gym_keypoint.py'),
                                   'data/checkpoints/slowonly_r50_u48_240e_gym_keypoint-b07a98a0.pth')
```
Above code gives me `RuntimeError: input data type should be consist with the dataset type in config, but got input type 'video' and dataset type 'PoseDataset'` no matter `use_frames=True` or `use_frames=False`.

**Comment by kennymckormick** [comment]
Hi, Zeakey, 
1. The label_path depends on the checkpoint you test with, for example, for a kinetics400 checkpoint, the label_path should be the label file that contains 400 class names.
2. Thanks for pointing out the problem, we will fix it very soon.

**Comment by zeakey** [comment]
Hi @kennymckormick , 

Thanks for the quick response.

Maybe it is more intuitive to move the `label_path` field out of the `inference_recognizer` function.
For many tasks like classification and detection, given an input, the model is expected to output probabilities.
One can map from probabilities to specific labels outside the model inference.

By the way, is there end-to-end example for your AAAI paper `Revisiting Skeleton-based Action Recognition` ? 
Currently I couple a pose estimation network from [mmpose](https://github.com/open-mmlab/mmpose) with skeleton-based action recognition network.

**Comment by kennymckormick** [comment]
1. It's a good idea, we will consider refactoring our codes.
2. The implementation in MMAction2 consists of 2 stages: 1. Pose estimation; 2. Skeleton-based Action Recognition. We haven't supported e2e training yet. BTW, we provide the demo `posec3d_demo` which can perform skeleton-based action recognition given RGB videos.

**Comment by kennymckormick** [comment]
Hi, Zeakey, 
    The PR that refactor the inference API is already merged. Now it can deal with skeleton-based (check updated `demo_posec3d.py`). The `label_path` is also moved out of the interface.

**Comment by zeakey** [comment]
@kennymckormick I found another weird behavier in the [demo_posec3d.py](https://github.com/open-mmlab/mmaction2/blob/01c94d365a429e06ff7515eac73d2a091d9cd513/demo/demo_posec3d.py) demo.

<https://github.com/open-mmlab/mmaction2/blob/01c94d365a429e06ff7515eac73d2a091d9cd513/demo/demo_posec3d.py#L16-L40>

In my case, I didn't install mmpose but the demo gives me an error:
```
ImportError: Please install mmdet to use init_detector. For OpenMMLAB codebases, you may need to install mmcv-full first before you install the particular codebase.
```
since both mmdet and mmpose were not imported.
