### ISSUE TITLE
HVU dataset bug

### ISSUE THREAD

**Issue by cir7** [open-mmlab/mmaction2#1189]
i am training HVU multi-task dataset, with _HVUDataset_, and _LoadHVULabel_.
it's ok when using all tag_categorie, but met a bug when using part of them.
i guess that there need a check when load category label from _results['label]_ in _LoadHVULabel.\_\_call\_\__
to make sure that the category is in selected tag_categories.

**Comment by kennymckormick** [comment]
Before, we assume that all categories in labels will be used for training, but I think your advice is reasonable, we will add the corresponding check soon.

**Comment by cir7** [comment]
When I use multi-task training together, the convergence performance of the model deteriorates, which contradicts the conclusion given in the paper. I found that the training results you gave did not provide the performance of multi-task joint training. Did you encounter the same problem? Can you give me some suggestions
