### ISSUE TITLE
testing a video for skeleton/posec3d config file and checkpoints 

### ISSUE THREAD

**Issue by bit-scientist** [open-mmlab/mmaction2#1190]
Here an example is given for testing a video with kinetic config files, I wanted to do the same with gym config files and modified the code as follows:

```
import torch

from mmaction.apis import init_recognizer, inference_recognizer

config_file = 'configs/skeleton/posec3d/slowonly_r50_u48_240e_gym_keypoint.py'
# download the checkpoint from model zoo and put it in `checkpoints/`
checkpoint_file = 'checkpoints/slowonly_r50_u48_240e_gym_keypoint-b07a98a0.pth'

# assign the desired device.
device = 'cuda:0' # or 'cpu'
device = torch.device(device)

 # build the model from a config file and a checkpoint file
model = init_recognizer(config_file, checkpoint_file, device=device)

# test a single video and show the result:
video = 'demo/demo.mp4' 
labels = 'tools/data/skeleton/label_map_gym99.txt'
results = inference_recognizer(model, video, labels)

# show the results
print(f'The top-5 labels with corresponding scores are:')
for result in results:
    print(f'{result[0]}: ', result[1])
```

Initially, it gave a `RuntimeError: input data type should be consist with the dataset type in config, but got input type 'video' and dataset type 'PoseDataset'`. Then I changed `slowonly_r50_u48_240e_gym_keypoint.py`'s `dataset_type =  'PoseDataset' ` to `VideoDataset` and `videos_per_gpu=16,` to `1` as suggested [here](https://github.com/open-mmlab/mmaction2/issues/371#issuecomment-732816714)

However, another error raises like below:

```
Use load_from_local loader
Traceback (most recent call last):
  File "/home/office/anaconda3/envs/openmm-lab/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 3417, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-2-e5645bf6ecf8>", line 1, in <module>
    runfile('/home/office/projects/sb_openmmaction2/demo_test_sb.py', wdir='/home/office/projects/sb_openmmaction2')
  File "/home/office/.pycharm_helpers/pydev/_pydev_bundle/pydev_umd.py", line 198, in runfile
    pydev_imports.execfile(filename, global_vars, local_vars)  # execute the script
  File "/home/office/.pycharm_helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/home/office/projects/sb_openmmaction2/demo_test_sb.py", line 19, in <module>
    results = inference_recognizer(model, video, labels)
  File "/home/office/projects/sb_openmmaction2/mmaction/apis/inference.py", line 139, in inference_recognizer
    data = test_pipeline(data)
  File "/home/office/projects/sb_openmmaction2/mmaction/datasets/pipelines/compose.py", line 50, in __call__
    data = t(data)
  File "/home/office/projects/sb_openmmaction2/mmaction/datasets/pipelines/pose_loading.py", line 115, in __call__
    num_frames = results['total_frames']
KeyError: 'total_frames'
```

Is testing a demo video not supported by skeleton/posec3d yet or there is something else to modify?

**Comment by zeakey** [comment]
Maybe the official [demo_posec3d.py] (https://github.com/open-mmlab/mmaction2/blob/5c76ee2ad6ecca22ae9da63a75800e46795d4903/demo/demo_posec3d.py) is a good point to start with.

**Comment by bit-scientist** [comment]
@zeakey thanks, I didn't notice it was there. But, although I've installed mmdet (`mmdet 2.17.0  dev_0  <develop>`), it is still showing this error.  I even restarted the terminal.

```
Traceback (most recent call last):
  File "demo_posec3d.py", line 274, in <module>
    main()
  File "demo_posec3d.py", line 212, in main
    det_results = detection_inference(args, frame_paths)
  File "demo_posec3d.py", line 164, in detection_inference
    model = init_detector(args.det_config, args.det_checkpoint, args.device)
  File "/home/office/anaconda3/envs/openmm-lab/lib/python3.7/site-packages/mmaction/utils/decorators.py", line 13, in new_func
    f'Please install {module_name} to use {func.__name__}.')
ImportError: Please install mmdet to use init_detector.
```

**Comment by kennymckormick** [comment]
Please follow this guide to install mmdet: https://github.com/open-mmlab/mmdetection/blob/master/docs/get_started.md. 
Specifically, mmcv-full of the corrected version must be installed before you install mmdet.

**Comment by bit-scientist** [comment]
@kennymckormick Thank you. I already installed mmcv-full in a proper way. It looks like for this project , although it says `ImportError: Please install mmdet to use init_detector.`, mmpose has to be installed too as `demo_posec3d.py` uses  `init_pose_model` at some point. In short, if the above error persists, simply go on and install `mmpose`. Thanks @kennymckormick once again.

**Comment by kennymckormick** [comment]
You are welcome, we are going to improve these error messages.

**Comment by BakingBrains** [comment]
@bit-scientist Were you able to resolve the above issue?
Thank you
