### ISSUE TITLE
Method of RGB fram extraction

### ISSUE THREAD

**Issue by d-li14** [open-mmlab/mmaction2#12]
Thanks for your elegant implementation of this toolbox.

The doc says `denseflow` installation is unnecessary for RGB frame extraction, but I find this [script](https://github.com/open-mmlab/mmaction2/blob/master/tools/data/build_rawframes.py) still uses `denseflow` for both RGB and flow extraction. I am wondering which one should be trusted.

**Comment by innerlee** [comment]
If you only need rgb, then denseflow is not required.

It is useful when you want the extracted frame and the computed flow to have the same number of frames, since different extraction method produces different number of frames.

**Comment by innerlee** [comment]
@dreamerlin could you improve the doc?

**Comment by d-li14** [comment]
Thanks for your prompt reply. But it is still not clear for me now.

https://github.com/open-mmlab/mmaction2/blob/master/tools/data/sthv2/preparing_sthv2.md says

> If you didn't install dense_flow in the installation or only want to play with RGB frames (since extracting optical flow can be time-consuming), consider running the following script to extract RGB-only frames.
```shell
cd $MMACTION/tools/data/sthv2/
bash extract_rgb_frames.sh
```
Actually the above shell script executes https://github.com/open-mmlab/mmaction2/blob/master/tools/data/build_rawframes.py, where denseflow command is still called on the condition of RGB-only.
(see https://github.com/open-mmlab/mmaction2/blob/master/tools/data/build_rawframes.py#L27-L36).
Maybe checking the absence of denseflow and using an alternative tool, e.g., ffmpeg, is to be added to these referred lines.

Correct me if I'm wrong.

**Comment by innerlee** [comment]
we are preparing a fix now https://github.com/open-mmlab/mmaction2/pull/14
