### ISSUE TITLE
why 'metric softmax is not supported'?

### ISSUE THREAD

**Issue by ingbeeedd** [open-mmlab/mmaction2#1201]
Before raising a question, you may need to check the following listed items.

I'm running a demo file named `mmaction2_tutorial.ipynb` ,  and I added metric as below, but why is there an error? Is there a limit to softmax?

```python
cfg.evaluation.metrics=['top_k_accuracy', 'mean_class_accuracy', 'softmax']
```

![image](https://user-images.githubusercontent.com/57895472/135743700-97bfe55e-c21a-4f31-9f21-b9dcf024c403.png)

Thank you 

**Checklist**

1. I have searched related issues but cannot get the expected help.
2. I have read the [FAQ documentation](https://mmaction2.readthedocs.io/en/latest/faq.html) but cannot get the expected help.

**Comment by dreamerlin** [comment]
`softmax` is not a metric
