### ISSUE TITLE
I'm curious about the meaning of num_clip and clip_len. And filmname_tmpl.

### ISSUE THREAD

**Issue by ingbeeedd** [open-mmlab/mmaction2#1204]
Before raising a question, you may need to check the following listed items.

1. If there is an image of 150 frames, how does num_clip and clip_len apply?
2. During training, all 150 images go into training, right?
3. In my folder, the images are in the order of 0.jpg 1.jpg, ... so should I make the file name_tmpl "{}.jpg"?

Thank you!!!!

**Checklist**

1. I have searched related issues but cannot get the expected help.
2. I have read the [FAQ documentation](https://mmaction2.readthedocs.io/en/latest/faq.html) but cannot get the expected help.

**Comment by dreamerlin** [comment]
1. See https://github.com/open-mmlab/mmaction2/blob/master/mmaction/datasets/pipelines/loading.py#L83-L109
2. Only the sampled frames
3. `filename_tmpl='{}.jpg'` and `start_index=0`

**Comment by ingbeeedd** [comment]
@dreamerlin 
Thank you for your answer. The sample seems to be random (ordered), but I want to train all the frame images in one folder in order, so what should I do?

**Comment by dreamerlin** [comment]
I suggest you write a `class SampleAllFrames` like [`class SampleAllFrames`](https://github.com/open-mmlab/mmaction2/blob/master/mmaction/datasets/pipelines/loading.py#L82-L270) just to sample all frame indexes based on `total_frames`.

**Comment by dreamerlin** [comment]
Example here (not tested):
```python
@PIPELINES.register_module()
class SampleAllFrames():

    def __call__(self, results):
        total_frames = results['total_frames']
        start_index = results['start_index']
        frame_inds = np.arange(total_frames) + start_index
        results['frame_inds'] = frame_inds.astype(np.int)
        results['clip_len'] = total_frames
        results['frame_interval'] =1
        results['num_clips'] = 1
```

**Comment by ingbeeedd** [comment]
@dreamerlin
 I'm sorry for asking you so many questions. If I do this, will there be no memory OOM problems?

**Comment by dreamerlin** [comment]
I am afraid that training all frames is costly for memory, maybe you can try to use smaller batch_size by changing the `videos_per_gpu` in config

**Comment by dreamerlin** [comment]
BTW, if you find our repo is helpful, you can give us a star! :)

**Comment by luigidamico100** [comment]
I have some more question about the class [SampleFrames](https://github.com/open-mmlab/mmaction2/blob/0dde60b56317b1133ac1adfee051374888efffc7/mmaction/datasets/pipelines/loading.py#L82-L270)

1. If I understood well, [Here](https://github.com/open-mmlab/mmaction2/issues/1204#issuecomment-933201553)  @ingbeeedd says that the video frames are mixed up randomly but I can't see it in the code, moreover I cannot find a conceptual explanation of doing this. If so, there is an easy way to take a number of `clip_len` ordered frames?
2. May you provide me a better explanation of `num_clips` parameter? At the moment my interpretation of this parameter is the **batch size**, so I cannot get the difference between the `videos_per_gpu` in the config file. 

Thanks!!

**Comment by udit01** [comment]
> 1. See https://github.com/open-mmlab/mmaction2/blob/master/mmaction/datasets/pipelines/loading.py#L83-L109
> 2. Only the sampled frames
> 3. `filename_tmpl='{}.jpg'` and `start_index=0`

I have the same issue, and I cannot find #1, could you please link the new location? or where the documentation is?
