### ISSUE TITLE
I want to resolve the 'label_path' error when I want to run the Skeleton-based Action Recognition Demo of mmaction2.

### ISSUE THREAD

**Issue by jangeunha1119** [open-mmlab/mmaction2#1206]
Hello,
I'm trying to use demo_posec3d.py, but got a problem with inference_regonizer().
`Traceback (most recent call last):
  File "demo/demo_posec3d.py", line 269, in <module>
    main()
  File "demo/demo_posec3d.py", line 246, in main
    results = inference_recognizer(model, fake_anno)
TypeError: inference_recognizer() missing 1 required positional argument: 'label_path'
`
How can I solve this problem?
If I write label_path in "inference_recognizer(model, fake_anno)", still another error occurs.

**Comment by dreamerlin** [comment]
I suggest you can try the latest version of `demo/demo_posec3d.py`. We have revised the inference API for more convenient usage.

**Comment by jangeunha1119** [comment]
> I suggest you can try the latest version of `demo/demo_posec3d.py`. We have revised the inference API for more convenient usage.

I did git clone just yesterday, so I used the latest version of demo/demo_posec3d.py and only changed the default paths of pares_args().

`python demo/demo_posec3d.py demo/climbing.mp4 demo/climbing_demo.mp4`
I used this command.

![image](https://user-images.githubusercontent.com/83445408/135812536-334b19de-38a0-45cd-8b53-dcdeb2b654d8.png)
and this is what I got.

**Comment by dreamerlin** [comment]
try `export PYTHONPATH=pwd:$PYTHONPATH` under `mmaction2`

**Comment by jangeunha1119** [comment]
> try `export PYTHONPATH=pwd:$PYTHONPATH` under `mmaction2`

![image](https://user-images.githubusercontent.com/83445408/135814744-23ec52e8-54ce-4d30-8169-9c6cac45a294.png)

Thank you for your comments, I finally solved this problem!!
Have a good day.

**Comment by dreamerlin** [comment]
That is good! BTW, if you find our repo and comments are useful, you can give us a star! : )

**Comment by TheEighthDay** [comment]
In a conda env, i meet the same problem.
and "export PYTHONPATH=pwd:$PYTHONPATH" can't address this problem
![图片](https://user-images.githubusercontent.com/26672667/148671373-4c62bfef-69da-479a-933e-8d7db5d0ba9a.png)

**Comment by TheEighthDay** [comment]
Update to v0.20,  I solved this problem~
