### ISSUE TITLE
Skeleton-based Action Recognition Demo failed, error that I need to install mmcv-full first...

### ISSUE THREAD

**Issue by wooistxx** [open-mmlab/mmaction2#1215]
I really appercaited mmaction2, it's really amazing for quick up a aciton recogition demo, but here I encounted a weired problem

## Problem
I followed the demo/README.md, and run the following demo successfully
1. spatio temporal detection
2. webcam demo
3. webcam spatio temporal detection
and when I run the skeleton action recognition demo, it's just failed and here is the console log:
```
Use load_from_local loader
Traceback (most recent call last):
  File "demo_posec3d.py", line 262, in <module>
    main()
  File "demo_posec3d.py", line 211, in main
    det_results = detection_inference(args, frame_paths)
  File "demo_posec3d.py", line 163, in detection_inference
    model = init_detector(args.det_config, args.det_checkpoint, args.device)
  File "/home/fubo/mm/mmaction2/mmaction/utils/decorators.py", line 13, in new_func
    f'Please install {module_name} to use {func.__name__}. '
ImportError: Please install mmdet to use init_detector. For OpenMMLAB codebases, you may need to install mmcv-full first before you install the particular codebase. 
Makefile:73: recipe for target 'demo_skeleton_action_recognition' failed
make: *** [demo_skeleton_action_recognition] Error 1
```
## Scripts
Here is my makefile script I run
```
.PHONY: demo_skeleton_action_recognition
demo_skeleton_action_recognition:
	python demo_posec3d.py \
		/home/fubo/Videos/motion-test.mp4 \
		/home/fubo/Videos/result_sketeton_action_recognition.mp4 \
		--config configs/skeleton/posec3d/slowonly_r50_u48_240e_ntu120_xsub_keypoint.py \
		--checkpoint checkpoints/slowonly_r50_u48_240e_ntu120_xsub_keypoint-6736b03f.pth \
		--det-config demo/faster_rcnn_r50_fpn_2x_coco.py \
		--det-checkpoint checkpoints/faster_rcnn_r50_fpn_2x_coco_bbox_mAP-0.384_20200504_210434-a5d8aa15.pth \
		--det-score-thr 0.9 \
		--pose-config demo/hrnet_w32_coco_256x192.py \
		--pose-checkpoint checkpoints/hrnet_w32_coco_256x192-c78dce93_20200708.pth \
		--label-map tools/data/skeleton/label_map_ntu120.txt
```

## Environment

1. the `PYTHONPATH=${PWD}:$PYTHONPATH python mmaction/utils/collect_env.py` info:
```
sys.platform: linux
Python: 3.7.11 (default, Jul 27 2021, 14:32:16) [GCC 7.5.0]
CUDA available: True
GPU 0: GeForce RTX 2080 Ti
CUDA_HOME: /usr/local/cuda
NVCC: Build cuda_11.1.TC455_06.29069683_0
GCC: gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
PyTorch: 1.7.1
PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) oneAPI Math Kernel Library Version 2021.3-Product Build 20210617 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v1.6.0 (Git Hash 5ef631a030a6f73131c77892041042805a06064f)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 11.0
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_37,code=compute_37
  - CuDNN 8.0.5
  - Magma 2.5.2
  - Build settings: BLAS=MKL, BUILD_TYPE=Release, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DUSE_VULKAN_WRAPPER -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, USE_CUDA=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, 

TorchVision: 0.8.2
OpenCV: 4.5.3
MMCV: 1.3.14
MMCV Compiler: GCC 7.3
MMCV CUDA Compiler: 11.0
MMAction2: 0.19.0+c2725e7
```
2. other informations
    - How you installed PyTorch : `conda install pytorch torchvision cudatoolkits=11.0 -c pytorch`
    - I install mmcv and mmdet following your mmcv project tutorials: `mim install mmdet` 

## Thanks
it's my first time to issue questions on github, for anything inappropriate and unclear I made, I apologize in advance, and I really hope any comment and help for my question.

**Comment by kennymckormick** [comment]
Did the answer solve ur problem? If so, please consider starring this project.

**Comment by Splending6** [comment]
同样的问题。。我放弃了

**Comment by kennymckormick** [comment]
> [#1215 (comment)](https://github.com/open-mmlab/mmaction2/issues/1215#issuecomment-950158811) The error happens just when I ran `demo/demo_posec3d.py`:
> 
> ```
> ~/mm/mmaction2# python demo/demo_posec3d.py ../in.flv ../our.mp4
> Use load_from_http loader
> Traceback (most recent call last):
>   File "demo/demo_posec3d.py", line 262, in <module>
>     main()
>   File "demo/demo_posec3d.py", line 211, in main
>     det_results = detection_inference(args, frame_paths)
>   File "demo/demo_posec3d.py", line 163, in detection_inference
>     model = init_detector(args.det_config, args.det_checkpoint, args.device)
>   File "/home/tsing/mm/mmaction2/mmaction/utils/decorators.py", line 12, in new_func
>     raise ImportError(
> ImportError: Please install mmdet to use init_detector. For OpenMMLAB codebases, you may need to install mmcv-full first before you install the particular codebase.
> ```

I mean, you can try to execute the two lines below, and see what is the original error message:

```python
from mmdet.apis import init_detector
model = init_detector(args.det_config, args.det_checkpoint, args.device) // of course you need to replace these args with the actual values
```

Then you can post the origin error message here or under mmdet repo.

**Comment by kennymckormick** [comment]
> 同样的问题。。我放弃了

same as above ...

**Comment by TsingWei** [comment]
> 同样的问题。。我放弃了

@kennymckormick  我解决了。我的是环境问题，cuda运行库版本和安装的mmcv版本不匹配。

我的cuda运行库版本是10.1，但是用conda装的pytorh给我装了个cuda_toolkit=11.0，然后我去找mmcv的对应版本的时候是按照cuda10.1来找的，所以跑demo出现了这个错误。 我用pip自己指定版本安装指定版本的torch后，问题消失了，demo正常跑通。

@Splending6  你可以检查一下你的nvidia-smi和nvcc来查看cuda的驱动版本和运行库版本，看看是否和mmcv的安装版本匹配

**Comment by Splending6** [comment]
> 
> 
> > 同样的问题。。我放弃了
> 
> @kennymckormick 我解决了。我的是环境问题，cuda运行库版本和安装的mmcv版本不匹配。
> 
> 我的cuda运行库版本是10.1，但是用conda装的pytorh给我装了个cuda_toolkit=11.0，然后我去找mmcv的对应版本的时候是按照cuda10.1来找的，所以跑demo出现了这个错误。 我用pip自己指定版本安装指定版本的torch后，问题消失了，demo正常跑通。
> 
> @Splending6 你可以检查一下你的nvidia-smi和nvcc来查看cuda的驱动版本和运行库版本，看看是否和mmcv的安装版本匹配

我匹配的 但就是跑不起来。。。

**Comment by liutaocode** [comment]
I have the same issue. I tried Cuda 10.1 and 11.3, but it didnot work. I think this is the bug.

**Comment by liutaocode** [comment]
> I have the same issue. I tried Cuda 10.1 and 11.3, but it didnot work. I think this is the bug.

After trying everything, I found just commenting code " try except "(line around 20) and run demo_posec3d.py.

It is OK now~~~~
