### ISSUE TITLE
Custom dataset training with PoseC3D

### ISSUE THREAD

**Issue by bit-scientist** [open-mmlab/mmaction2#1216]
I reviewed all the relevant pages for implementing PoseC3D with my custom dataset and got confused what annotation format should be prepared. 

I have a 4-class category dataset for anomaly action recognition in videos which is action recognition task.
The format of my dataset as a text file is as follows:

```
path/to/class_folder/train/1/arhstrjadefh.mp4 1
path/to/class_folder/train/1/ksitldguidjd.mp4 1
................................................
path/to/class_folder/train/2/dfgnkureae.mp4 2
path/to/class_folder/train/2/qgsjgldube.mp4 2
................................................
path/to/class_folder/train/3/adrwetrshjty.mp4 3
path/to/class_folder/train/3/ldjsrqggejhd.mp4 3
................................................
path/to/class_folder/train/4/jlshginrtdfhi.mp4 4
path/to/class_folder/train/4/jlshginrtdfhi.mp4 4
```
I have `val` and `test` annotations as well.
 
This abides by the VideoDataset rules given [Tutorial 3: Adding New Dataset ](https://github.com/open-mmlab/mmaction2/blob/master/docs/tutorials/3_new_dataset.md#customize-datasets-by-reorganizing-data)

Now, I would like to train my own dataset with PoseC3D, however [The Format of PoseC3D Annotations](https://github.com/open-mmlab/mmaction2/blob/master/tools/data/skeleton/README.md#the-format-of-posec3d-annotations) reads that dataset should be annotated as 

> each item is a dictionary that is the skeleton annotation of one video

> keypoint: The keypoint coordinates, which is a numpy array of the shape N (#person) x T (temporal length) x K (#keypoints, 17 in our case) x 2 (x, y coordinate).
> keypoint_score: The keypoint confidence scores, which is a numpy array of the shape N (#person) x T (temporal length) x K (#keypoints, 17 in our case).
> frame_dir: The corresponding video name.
> label: The action category.
> img_shape: The image shape of each frame.
> original_shape: Same as above.
> total_frames: The temporal length of the video.
 
I am confused here. If I want to have a model that takes raw video as input and outputs action category, do I have to have skeleton annotations of each video? If so how do I prepare skeleton annotation to implement PoseC3D? 

While reading the paper of [PoseC3D](https://arxiv.org/abs/2104.13586) I understood that the model only requires videos as input and generates skeleton information within the model itself and subsequently recognizes actions. Then why do we need to provide skeleton information when training?

**Comment by bit-scientist** [comment]
@kennymckormick Hi, I am trying to make a .json video annotation format that matches with PoseC3D. However, currently I haven't succeeded.

**Comment by bit-scientist** [comment]
Hi @kennymckormick. Let me outline what I got from what I read so far. 
So according to `gym_train.pkl`, its format is as shown there, but `gym_train.pkl` contains annotations of FineGYM dataset. 
Since I want to train my own dataset with PoseC3D model (skeleton based), I need to have my own so-called `custom_dataset_train.pkl` (and `custom_dataset_val.pkl`) annotation files first, right?

To achieve that, I may use `ntu_pose_extraction.py` as shown in [Prepare Annotations](https://github.com/open-mmlab/mmaction2/blob/master/tools/data/skeleton/README.md#prepare-annotations) like this:

`python ntu_pose_extraction.py some_video_from_my_dataset.mp4 some_video_from_my_dataset.pkl`

Doing so for every single video for training and val will give me `.pkl` files and I will gather them into a single list for training (and val) my dataset with PoseC3D's skeleton framework. Am I right up until this point?

Assuming the above is true, I may use the following script (with a little change) for training as shown in [PoseC3D/Train](https://github.com/open-mmlab/mmaction2/blob/master/configs/skeleton/posec3d/README.md#train)

`python tools/train.py configs/skeleton/posec3d/slowonly_r50_u48_240e_ntu120_xsub_keypoint.py --work-dir work_dirs/slowonly_r50_u48_240e_ntu120_xsub_keypoint --validate --test-best --gpus 2 --seed 0 --deterministic`

Lastly, before running the above script, I need to modify the variables 
```
ann_file_train = 'data/posec3d/custom_dataset_train.pkl'
ann_file_val = 'data/posec3d/custom_dataset_val.pkl'
```
and `num_classes=4`, `pretrained=None,` (when training from scratch, `pretrained='torchvision://resnet50'` when fine-tuning) and _training schedule_ alterations as needed in `configs/skeleton/posec3d/slowonly_r50_u48_240e_ntu120_xsub_keypoint.py` 

Does this all make sense to you?
Thank you :smiley:

**Comment by bit-scientist** [comment]
Hi, @kennymckormick. Today I was going to train my custom dataset based on what we discussed in this issue. It turns out that there should be some more changes in config file. Namely, `class_prob={i: 1 + int(i >= 60) for i in range(120)}` of  [slowonly_r50_u48_240e_ntu120_xsub_keypoint.py](https://github.com/open-mmlab/mmaction2/blob/491fe53b70ade539eea5647e6976c43959d37dd3/configs/skeleton/posec3d/slowonly_r50_u48_240e_ntu120_xsub_keypoint.py#L94). I couldn't find any related info about what `class_prob` means in the paper and didn't understand why the half classes were assigned 1 and the rest were given 2. Could you please shed some light on that and tell what its value should be for n class-custom training? Thank you.

**Comment by kennymckormick** [comment]
> Hi, @kennymckormick. Today I was going to train my custom dataset based on what we discussed in this issue. It turns out that there should be some more changes in config file. Namely, `class_prob={i: 1 + int(i >= 60) for i in range(120)}` of [slowonly_r50_u48_240e_ntu120_xsub_keypoint.py](https://github.com/open-mmlab/mmaction2/blob/491fe53b70ade539eea5647e6976c43959d37dd3/configs/skeleton/posec3d/slowonly_r50_u48_240e_ntu120_xsub_keypoint.py#L94). I couldn't find any related info about what `class_prob` means in the paper and didn't understand why the half classes were assigned 1 and the rest were given 2. Could you please shed some light on that and tell what its value should be for n class-custom training? Thank you.

That's just a trick for NTU120-XSub training: the training samples for the later 60 classes are much less than the first 60 classes. So we sample these videos more frequently. For custom training, you can set class_prob for all classes to 1, or to any values depending on your need.

**Comment by BigJoon** [comment]
@bit-scientist 
hi. By the way, have u succeed in training with custom dataset for posec3d?
I keep trying with my custom dataset  but..  failing.... 
i got this error log.
`Traceback (most recent call last):
  File "tools/train.py", line 216, in <module>
    main()
  File "tools/train.py", line 184, in main
    datasets = [build_dataset(cfg.data.train)]
  File "/mmaction2/mmaction/datasets/builder.py", line 40, in build_dataset
    dataset = build_from_cfg(cfg, DATASETS, default_args)
  File "/opt/conda/lib/python3.7/site-packages/mmcv/utils/registry.py", line 55, in build_from_cfg
    raise type(e)(f'{obj_cls.__name__}: {e}')
TypeError: PoseDataset: string indices must be integers`
Can you find out what is the problem..?

**Comment by bit-scientist** [comment]
@BigJoon It looks like you have some problem in your config file. Refer to [this](https://github.com/open-mmlab/mmaction2/blob/master/configs/skeleton/posec3d/custom_dataset_training.md) for a step by step custom training

**Comment by BigJoon** [comment]
@bit-scientist hi~ thanks for ur kindness answer. But my problem was quite simple. 
After i make some '.pkl' files with each Clip Videos, i had to tie them together into one '.pkl' file. But i didn't. I used the code below for merging every '.pkl' files.
`import os.path as osp
import os
import pickle
result = []
path = './'
for d in os.listdir(path):
    if d.endswith('.pkl'):
        with open(osp.join(path, d), 'rb') as f:
            content = pickle.load(f)
        result.append(content)
with open('train.pkl', 'wb') as out:
    pickle.dump(result, out, protocol=pickle.HIGHEST_PROTOCOL)
`

**Comment by vsc9729** [comment]
Hey, I am following the exact same method but when i run the command for training it keeps saying "grad_norm: 0.000". If is I set num_classes = 2. I get the following error: 
**_### RuntimeError: CUDA error: device-side assert triggered
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1._**
