### ISSUE TITLE
Train pipelines for X3D models

### ISSUE THREAD

**Issue by mahdiabdollahpour** [open-mmlab/mmaction2#1225]
Hi

[X3D model configs](https://github.com/open-mmlab/mmaction2/blob/master/configs/recognition/x3d/x3d_m_16x5x1_facebook_kinetics400_rgb.py) only have the test pipelines while [TSN](https://github.com/open-mmlab/mmaction2/blob/master/configs/recognition/tsn/tsn_r50_320p_1x1x3_100e_kinetics400_rgb.py) has all train test val pipelines. Would you please provide the train pipelines for X3D models? Are train pipelines same as test pipelines but added a RandomResizedCrop?

Thanks

**Comment by youwenjing** [comment]
@rlleshi could you train X3D model now? I read the README.md which says it is not support training X3D and will support later

**Comment by poincarelee** [comment]
@mahdiabdollahpour  any advance in training pipeline?  I tried SlowFast's official repository and failed.
