### ISSUE TITLE
Memcached Config

### ISSUE THREAD

**Issue by tuochi** [open-mmlab/mmaction2#1229]
Hi! I'd like to ask the problem about using memcached as backend . I install memcached by using its office document, but i can't find the files named 'server_list_cfg' or 'client_cfg'. What tool memcached client you used? Could you give me an example about "server_list_cfg","client_cfg" and "sys_path"in your spare time?Thanks a lot!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by dreamerlin** [comment]
```
mc_cfg = dict(
    server_list_cfg='/xxx/memcached_client/server_list.conf',
    client_cfg='/xxx/memcached_client/client.conf',
    sys_path='/xxx/pymc/py3')
...
dict(type='RawFrameDecode', io_backend='memcached', **mc_cfg),
```

**Comment by dreamerlin** [comment]
Sorry, we do not know the detail of the Memcached. Maybe you can find help from Memcached team!
