### ISSUE TITLE
On the nature of PoseC3D model for action recognition.

### ISSUE THREAD

**Issue by bit-scientist** [open-mmlab/mmaction2#1235]
It is known that PoseC3D recognizes actions. But I have an interesting question. Let's say I have a 120-second video and some action (say violence ) starts at **00:50** and ends at **01:05**, which is 15s duration. If a custom PoseC3D model trained on these kinds of video samples, then what will the class category be for the parts until 00:50 and after 01:05?

**Comment by kennymckormick** [comment]
The simplest solution might be that you trim the long videos before training, annotate the action part using the action label, annotate clips before and after the action with a background label.
