### ISSUE TITLE
Training data meaning of data in CSV files( ID of this bounding box.）,Whether it has an impact on training

### ISSUE THREAD

**Issue by gzchenjiajun** [open-mmlab/mmaction2#1239]
AVA annotations explained · open-mmlab/mmaction2@d7a61f7 https://github.com/open-mmlab/mmaction2/commit/d7a61f7ed6fdd9326affe8d8bca04cd15610a931

“The last item `1` is the ID of this bounding box.”

After reading this document, I would like to ask that the data of ID of this bounding Box is wrong, does it affect the training?
[For some reason this part of the data is corrupted, but the other columns are correct]

thks

**Comment by kennymckormick** [comment]
The ID of the bounding box doesn't affect the training.

**Comment by gzchenjiajun** [comment]
Then I encountered a strange phenomenon. After many experiments, the training effect was not as good as the original pretrain
I added many times the new data (normal in the image labeling software, and correct conversion from value to percentage according to the document), but the training effect was not good.

But because the data is too large to upload, only partial log data.
Training log after adding data.

My testing method is to add my newly added data to both training and testing, but the newly added data does not seem to have any effect on the model.

Training log with no new data added:
![image](https://user-images.githubusercontent.com/13104274/139612736-261b8ea0-67d1-4bc3-95ee-59443693a30f.png)



Add new data to the training log：
![image](https://user-images.githubusercontent.com/13104274/139612708-66d03997-cace-41e5-8728-6745501fb965.png)

Verify that the data files are the same.

Below is the newly added CSV data format (THE validity of the data itself has been verified by the image annotation software, which is correct, and the percentage of positive conversion should also be correct).
![image](https://user-images.githubusercontent.com/13104274/139612095-d08aa042-507c-481d-8e36-87e448934306.png)

![image](https://user-images.githubusercontent.com/13104274/139612636-59ffb218-d3ae-4659-85cf-a0c138006efb.png)




Any suggestions for this situation?

example is climb1


@kennymckormick

**Comment by gzchenjiajun** [comment]
The amount of training data added is huge, about 10 times

**Comment by gzchenjiajun** [comment]
My profile is correct because the metrics are good when I use the official validation data

**Comment by gzchenjiajun** [comment]
When I actually tested the demo, the model that added its own data actually identified some actions that pretrian failed to identify.
But the indicators are so low

**Comment by gzchenjiajun** [comment]
For the new data of training myself, I only added CSV data. Is there any other data or other places that need to be modified?

**Comment by gzchenjiajun** [comment]
I think I know the problem, I annotated data at 30fps, but actually annotated data at 1fps is ok.


Only the generated images are 30fps

Isn't it

**Comment by gzchenjiajun** [comment]
csv annotation file is 30fps, does it affect training?

**Comment by gzchenjiajun** [comment]
I changed the tagging file to 1fps and the testing is much better... 
I think I found the problem
