### ISSUE TITLE
Pre-trained audio 

### ISSUE THREAD

**Issue by Jianxin98** [open-mmlab/mmaction2#1243]
Thank you for your great job.
I would like to ask you a question for audio. There are not the pre-trained restnet50 for audio?

Thanks

**Comment by kennymckormick** [comment]
Hi, jianxin, 

Currently, we do not have Kinetics400 pre-trained restnet50 for audio. Maybe you can follow the instruction to train one. It will not take a long period of time according to the existing log of resnet18. 

BTW, if you have trained a ResNet50 audio net, you are welcome to raise a PR to submit it to the mmaction2 codebase. I'm sure lots of people will benefit from it.
