### ISSUE TITLE
How can we train mixe of video and audio

### ISSUE THREAD

**Issue by wenjun90** [open-mmlab/mmaction2#1245]
Dear Authors,

Can we train the mixe of video and audio in the same time?

Thank you very much.

**Comment by kennymckormick** [comment]
It should be OK, you can refer to [AVSlowFast](https://arxiv.org/pdf/2001.08740). However, currently, this feature is not supported in MMAction2 yet.

**Comment by rlleshi** [comment]
@kennymckormick any plans to support this feature in the (near) future?
