### ISSUE TITLE
Using a customized object detector for action recognition 

### ISSUE THREAD

**Issue by bit-scientist** [open-mmlab/mmaction2#1249]
As PoseC3D recognizes human activities (via skeleton data), the object detector (faster_rcnn_r50_fpn) used in it considers only "person" class that is trained with COCO dataset.  I am planning to use some custom-trained object detector whose classes are not only human, but also some other objects such as cars, masks, etc. And for this object detector I want to use yolov5 based object detector. This way I would have a model that recognizes actions as before, plus it detects some objects it was trained before. The reason why I need object detection is that I want to bound some action incident to some object detection first, because some activities may occur if (and only if ) a certain object is present in the scene. 

What do you think of this idea? I would like to hear some insights from you if you happen to know something. Thanks in advance.

**Comment by kennymckormick** [comment]
That's OK I think. I use a person-only detector just for better detection performance for the `person` class (however, the improvement is marginal I guess). Of course, you can use a general object detector. Depending on your need (some activities may occur if (and only if ) a certain object is present), maybe you can hardcode some logic in your recognition system.
