### ISSUE TITLE
error when calculating mean_average_precision for multi_class

### ISSUE THREAD

**Issue by suntaiwu** [open-mmlab/mmaction2#1252]
The mean_average_precision is always 1.0000, no matter for which checkpoint and what val dataset

**Comment by kennymckormick** [comment]
For which config file and dataset?

**Comment by suntaiwu** [comment]
> For which config file and dataset?

timesformer config,  my own dataset

**Comment by kennymckormick** [comment]
mean_average_precision should be only used for multi-label datasets, does your dataset a multilabel dataset? If so, you can first check the usage of mean_average_precision in some examples, like HVU dataset.
