### ISSUE TITLE
Recognizer3D is not registered in LOCALIZERS, RECOGNIZERS or DETECTORS

### ISSUE THREAD

**Issue by ououoxx** [open-mmlab/mmaction2#1254]
Dear authors,

When converting i3d model(i3d_r50_32x2x1_100e_kinetics400_rgb.py) to onnx via python2onnx.py, something wrong happened: 
 raise ValueError(f'{obj_type} is not registered in '
ValueError: Recognizer3D is not registered in LOCALIZERS, RECOGNIZERS or DETECTORS

Here's my input:
python3.7 tools/deployment/pytorch2onnx.py configs/recognition/i3d/i3d_r50_32x2x1_100e_kinetics400_rgb.py configs/recognition/i3d/i3d_r50_32x2x1_100e_kinetics400_rgb.pth --shape -1 1 3 32 224 224 --output-file i3d.onnx

I wonder whether my input form was wrong or there exists other problems.(I put my .pth file and .py file in the same folder)

**Comment by kennymckormick** [comment]
Did you use the latest version of mmaction2?

**Comment by ououoxx** [comment]
Well, I didn't. I'll give it a try. 
Thanks for your help.I really appreciate it.

**Comment by ououoxx** [comment]
@kennymckormick I tried the latest version of mmaction2, but the problem still happens.

**Comment by ououoxx** [comment]
@kennymckormick I tried the latest version, but the problem still occurs.

**Comment by dreamerlin** [comment]
Try export PYTHONPATH=`pwd`:$PYTHONPATH under the root path?

**Comment by ououoxx** [comment]
well, it's a path problem. I don't understand why ‘pytorch2onnx.py' and 'builder.py' cannot import other python files although init file does exist in other folders.
I import path from sys in 'pytorch2onnx.py' and 'builder.py' and the problem is solved.
