### ISSUE TITLE
Generating Test Files

### ISSUE THREAD

**Issue by amitbcp** [open-mmlab/mmaction2#1257]
As we generate raw_Frames and video lists, why don't we also generate the test_files in the same pattern in the processing flow ?

For example in HMDB here we have 3 splits for train and validation

**Comment by kennymckormick** [comment]
Actually, the `validation` lists in UCF & HMDB are test lists. There is only `train` and `test` in UCF & HMDB. We call them validation just to follow the convention of this repo.

**Comment by amitbcp** [comment]
Thanks @kennymckormick for the clarification
