### ISSUE TITLE
About key-value assignment  in CustomDataset

### ISSUE THREAD

**Issue by Wolfybox** [open-mmlab/mmaction2#1258]
Great repo for action recognition!
I was trying to use customed dataset for skeleton-based action recoginition (posec3d) and create a .pkl file according to the required format. However, the dataset I use provides ONLY SKELETON KEYPOINTS (without any videos or frames). Therefore, I was kinda confused when trying to fill these keys in the given format :
- frame_dir: The corresponding video name.
- label: The action category. 
- img_shape: The image shape of each frame. 
- original_shape: Same as above. 
- total_frames: The temporal length of the video. 

I tried filling them with **None** but it reported me with:
_TypeError: join() argument must be str or bytes, not 'NoneType'_ in _load_annotations_ of _pose_dataset.py_

Is the frame information a must? Or are there any suggestions for filling in these keys?

**Comment by bit-scientist** [comment]
@Wolfybox What script are you running to create .pkl files? Basically, `frame_dir` could be derived from the filename string that you  provide as arg parse. `label` too could be derived from the filename (refer to `S001C001P001R001A001_rgb` file in [Prepare Annotations](https://github.com/open-mmlab/mmaction2/blob/master/tools/data/skeleton/README.md#prepare-annotations)) or you can derive the folder if your videos are organized as class folders. `image_shape` comes from `    h, w, _ = original_frames[0].shape` where `original_frames` is the return variable of `frame_extraction` function. `original_shape` is the same as previous one. `total_frames` equals to `num_frame` of  `num_frame = len(frame_paths)` where `frame_paths` is again one the return variables of `frame_extraction`. Hope that helps.

**Comment by kennymckormick** [comment]
I guess the clear instructions from @bit-scientist can well resolve your problems, feel free to reopen it you have any other questions.
