### ISSUE TITLE
Assigning person_ids for each person's keypoints appearing in each frame appears to be erroneous. 

### ISSUE THREAD

**Issue by bit-scientist** [open-mmlab/mmaction2#1263]
Hi, @kennymckormick, I have come across very strange incident with keypoints while testing `demo_posec3d.py`. 

Well, this might be a tricky point of how the person's keypoints (detected in each frame) keep their corresponding unique ID in the subsequent frames. 
 In [demo_posec3d.py](https://github.com/open-mmlab/mmaction2/blob/master/demo/demo_posec3d.py) `keypoint` is derived from `pose_results` which is returned by `pose_inference` function. Then `keypoint` is assigned to `fake_anno['keypoint']`. I tried to check all keypoints for each person appearing in subsequent frames and found that in some frames (where two people appear) first person's keypoints interchange with another one's keypoints. To illustrate further, let me explain what I did with `fake_anno['keypoint']`.

Have a look at this code snippet:
```
universal_list = []
person_kps = dict(keypoints=None)
for fn in range(fake_anno['keypoint'].shape[1]):  # (2, F, 17, 2)
    persons_list = []
    for per_ind in range(0, fake_anno['keypoint'].shape[0] - 1):
        person_kps["keypoints"] = fake_anno['keypoint'][per_ind, fn, :, :] # 2
        kp_per_frame_list = [arr.tolist() for arr in person_kps["keypoints"]]
        persons = dict(person_index=per_ind, keypoints=kp_per_frame_list)
        persons_list.append(persons)

    required_json = dict(frame_index=fn, persons=persons_list)
    universal_list.append(required_json)

json_filename = "testfile.json"
with open(json_filename, 'w') as fp:
    json.dump(universal_list, fp, indent=4)
```
This snippet is placed right after the line 238 of [demo_posec3d.py ](https://github.com/open-mmlab/mmaction2/blob/master/demo/demo_posec3d.py#L238). This snippet iterates through each frame and [num_person](https://github.com/open-mmlab/mmaction2/blob/master/demo/demo_posec3d.py#L225) (refer to `num_person = max([len(x) for x in pose_results])`) and saves all frames and persons with their respective ids and keypoints in the form as below:

```
[
{
"frame_index": 734,
"persons": [
    {
    "person_index": 0,
    "keypoints": [ [1046.0, 231.0], [1055.0, 213.125], [1064.0, 213.125], [1055.0, 231.0], [1135.0, 222.125], [1037.0, 346.75], [1170.0, 346.75], [1001.0, 498.25], [1179.0, 471.5], [974.5, 641.0], [1170.0, 605.0], [1055.0, 623.0], [1153.0, 605.0], [1072.0, 819.0], [1108.0, 792.5], [1081.0, 1006.0], [1126.0, 961.5] ]
    },
    {
    "person_index": 1,
    "keypoints": [ [930.0, 127.125], [943.5, 120.25], [916.0, 113.4375], [957.5, 140.875], [895.5, 127.125], [984.5, 216.25], [854.5, 229.875], [1019.0, 319.0], [834.0, 346.25], [1026.0, 421.75], [813.5, 442.25], [971.0, 428.5], [875.0, 428.5], [978.0, 593.0], [861.5, 600.0], [943.5, 730.0], [875.0, 737.0] ]
    }
           ]
},
{
"frame_index": 735,
"persons": [
    {
    "person_index": 0,
    "keypoints": [ [926.0, 129.75], [946.5, 122.875], [919.0, 116.0], [960.5, 143.625], [898.0, 122.875], [988.0, 212.75], [850.0, 226.625], [1022.5, 323.5], [829.0, 344.25], [1030.0, 427.25], [808.5, 434.0], [967.5, 427.25], [877.5, 434.0], [974.5, 593.0], [863.5, 600.0], [939.5, 731.5], [870.5, 738.5] ]
    },
    {
    "person_index": 1,
    "keypoints": [ [1046.0, 230.875], [1055.0, 213.0], [1064.0, 213.0], [1055.0, 230.875], [1135.0, 221.875], [1037.0, 347.0], [1171.0, 347.0], [1001.0, 507.75], [1180.0, 472.0], [974.5, 642.0], [1162.0, 606.0], [1055.0, 615.0], [1153.0, 606.0], [1073.0, 820.5], [1108.0, 793.5], [1082.0, 1008.0], [1126.0, 963.5] ]
    }
          ]
},
]
```
`"frame_index": 734` and `"frame_index": 735` are actual frames of my test video. 

### Now comes the problematic point. 

Pay attention:
the keypoint values of frame 734 where `"person_index":0`:  `[1046.0, 231.0], [1055.0, 213.125], [1064.0, 213.125], [1055.0, 231.0]` 
and 
the keypoint values of frame 735 where `"person_index":0`: `[926.0, 129.75], [946.5, 122.875], [919.0, 116.0], [960.5, 143.625]` 

**whereas** 

the keypoint values of frame 734 where `"person_index":1`: `[930.0, 127.125], [943.5, 120.25], [916.0, 113.4375], [957.5, 140.875]` 
and 
the keypoint values of frame 735 where `"person_index":1` : `[1046.0, 230.875], [1055.0, 213.0], [1064.0, 213.0], [1055.0, 230.875]`

Have you noticed the discrepancy? The keypoints of `"person_index":0`s of two subsequent frames (734 and 735) are expected to be very close to each other, since keypoints don't move much in one frame, but they are interchaged with one another. 
Why do you think this is happening? 

I could think of one possible reason: every time person is detected in a frame, `inference_detector`  automatically assigns 0 to `person_index` (inside `detection_inference` function) whose bbox confidence score is the highest, and similarly, it assigns 1 to  `person_index` whose bbox confidence score is second highest, etc. 

If the above is all true, then this could be considered as _bug_ as long as this happens with the videos of benchmark datasets. It's also highly likely that the model gets trained with such wrong keypoints for each person appearing in frames and impact the final results negatively.

Please take your time to check if this phenomenon is true for some of your video samples as well. 
Thank you.

**Comment by kennymckormick** [comment]
Hey, bit-scientist, 
 
Actually, the `pose_results` returned by the pose estimator is a **set**: one should not assume the order of different persons to be consistent in the results of every frame. Besides, the `person_index` is never used in the training & validation of PoseC3D, we just treat the results as a set, instead of an ordered list.

**Comment by bit-scientist** [comment]
I appreciate your reply, @kennymckormick,

With all due respect, I don't think `pose_results`  returned by pose estimator is a `set`, I see it as a `list`. Let me trace back why I see it as `list`.  As stated before `pose_results ` comes from `pose_results = pose_inference(args, frame_paths, det_results)`. `pose_inference`'s return value is `ret` defined as a local `list` variable [here](https://github.com/open-mmlab/mmaction2/blob/4370f294b0707d8f62bd49545649edb7ed08d4a7/demo/demo_posec3d.py#L178). `ret` itself gets its elements appended to it by `pose`, a return value of `inference_top_down_pose_model` which resides in [_mmpose/apis/inference.py_](https://github.com/open-mmlab/mmpose/blob/4a3b12a403d78d538cb1b801112c431ae0f5060e/mmpose/apis/inference.py#L335). If that is all true, how do you conclude that `pose_results` is indeed a set?

Put all that aside, let's assume what your are saying is true, although PoseC3D doesn't use `person_index` for training, it does use keypoints, right? If so, the model sometimes trains different keypoints, because as I said keypoint coordinates got saved in a reversed order within the array when that array was exracted using pose estimator. 

Correct me if I'm wrong and guide if you can. :confused:
I hope you got my point by now. Thanks again :fist_raised:

**Comment by kennymckormick** [comment]
Yes, the data structure used for `pose_results`, I call `pose_results` a set just to emphasize the order of elements in this list makes no difference. 
Besides, your conclusion that `the model sometimes trains different keypoint` is not correct. For a single frame, we visualize all persons' skeletons on the same heatmap volume. If there exist N persons in a frame, we draw all N persons on the same heatmap volume. 

Hope the clarifications can resolve your issues.

**Comment by bit-scientist** [comment]
thanks @kennymckormick , sure, what is you say is indeed true, if we have N persons in one frame (say, `f`), we draw one heatmap volume, I understood that. But again, in the the very next frame (`f+1`), those if those N persons persist, their corresponding keypoint coordinates sometimes get drawn in an interchanged way as shown below:

```
[
{
"frame_index": 734,
"persons": [
    {
    "person_index": 0,
    "keypoints": [ [1046.0, 231.0], [1055.0, 213.125], [1064.0, 213.125], [1055.0, 231.0], [1135.0, 222.125], [1037.0, 346.75], [1170.0, 346.75], [1001.0, 498.25], [1179.0, 471.5], [974.5, 641.0], [1170.0, 605.0], [1055.0, 623.0], [1153.0, 605.0], [1072.0, 819.0], [1108.0, 792.5], [1081.0, 1006.0], [1126.0, 961.5] ]
    },
    {
    "person_index": 1,
    "keypoints": [ [930.0, 127.125], [943.5, 120.25], [916.0, 113.4375], [957.5, 140.875], [895.5, 127.125], [984.5, 216.25], [854.5, 229.875], [1019.0, 319.0], [834.0, 346.25], [1026.0, 421.75], [813.5, 442.25], [971.0, 428.5], [875.0, 428.5], [978.0, 593.0], [861.5, 600.0], [943.5, 730.0], [875.0, 737.0] ]
    }
           ]
},
{
"frame_index": 735,
"persons": [
    {
    "person_index": 0,
    "keypoints": [ [926.0, 129.75], [946.5, 122.875], [919.0, 116.0], [960.5, 143.625], [898.0, 122.875], [988.0, 212.75], [850.0, 226.625], [1022.5, 323.5], [829.0, 344.25], [1030.0, 427.25], [808.5, 434.0], [967.5, 427.25], [877.5, 434.0], [974.5, 593.0], [863.5, 600.0], [939.5, 731.5], [870.5, 738.5] ]
    },
    {
    "person_index": 1,
    "keypoints": [ [1046.0, 230.875], [1055.0, 213.0], [1064.0, 213.0], [1055.0, 230.875], [1135.0, 221.875], [1037.0, 347.0], [1171.0, 347.0], [1001.0, 507.75], [1180.0, 472.0], [974.5, 642.0], [1162.0, 606.0], [1055.0, 615.0], [1153.0, 606.0], [1073.0, 820.5], [1108.0, 793.5], [1082.0, 1008.0], [1126.0, 963.5] ]
    }
          ]
},
]
```

All what you said true, however, I am arguing what I am observing. Please, step one step into the details. Thanks a lot.

**Comment by kennymckormick** [comment]
Yes, the order of elements in the `pose_results` has changed. However, this will not influence the generated heatmap volume:

Let's say there are 2 persons p1 and p2, for `pose_results` [p1, p2] or [p2, p1], the generated heatmap volume will be the same.
