### ISSUE TITLE
valueError: num_samples should be a positive integer value, but got num_samples=0

### ISSUE THREAD

**Issue by jianxinhou** [open-mmlab/mmaction2#1265]
Before raising a question, you may need to check the following listed items.

**Checklist**

1. I have searched related issues but cannot get the expected help.
2. I have read the [FAQ documentation](https://mmaction2.readthedocs.io/en/latest/faq.html) but cannot get the expected help.
python tools/train.py configs/recognition/slowfast/my_slowfast_r50_4x16x1_256e_ucf101_rgb.py   --work-dir work_dirs/my_slowfast_r50_4x16x1_256e_ucf101_rgb    --validate --seed 0 --deterministic

**Comment by kennymckormick** [comment]
You should post your config here since you use a custom config. 

BTW, I guess you accidentally set videos_per_gpu to 0?

**Comment by kennymckormick** [comment]
Please reopen this issue if you have some updates.
