### ISSUE TITLE
Error embed_dims

### ISSUE THREAD

**Issue by wenjun90** [open-mmlab/mmaction2#1271]
Dear the authors,
When I set the config Timesformer like that:
from mmaction.models import TimeSformer
timesformer = TimeSformer(
    8, 224, 16, embed_dims=1024, attention_type='divided_space_time'
)

There is error of "**AssertionError: TransformerLayerSequence: BaseTransformerLayer: DividedTemporalAttentionWithNorm: embed_dim must be divisible by num_heads**"

How we can fix this error?

Thank you!

**Comment by kennymckormick** [comment]
Hi, wenjun,

Please check the err msg: "AssertionError: TransformerLayerSequence: BaseTransformerLayer: DividedTemporalAttentionWithNorm: embed_dim must be divisible by num_heads"

In your code embed_dims (1024) % num_heads (12) != 0

![image](https://user-images.githubusercontent.com/34324155/142350260-2420777f-2dae-46a3-99b7-0d591119f8c5.png)

**Comment by wenjun90** [comment]
Hi @kennymckormick ,
I can change the __init__(self,...)
with config embed_dim = 1024, num_heads=24 and num_transformer_later=24.Then I set: timesformer = TimeSformer(
8, 224, 16, embed_dims=1024, attention_type='divided_space_time'
)

Is this possible?

Thank you very much.

**Comment by kennymckormick** [comment]
No, (1024 % 24) != 0, you can set num_heads to 16 or 32.

**Comment by wenjun90** [comment]
Thank you @kennymckormick ,
Then, I can use the pretrained **vit_large_patch16_224.pth** with **embed_dim = 1024**, **num_heads=32** and **num_transformer_later=12** as [here](https://github.com/open-mmlab/mmaction2/pull/880): https://github.com/open-mmlab/mmaction2/pull/880
timesformer = TimeSformer(
8, 224, 16, embed_dims=1024, attention_type='divided_space_time'
)
This is correct?

Thank you again!

**Comment by kennymckormick** [comment]
It's OK I think.
