### ISSUE TITLE
The generated file is empty

### ISSUE THREAD

**Issue by Danvae** [open-mmlab/mmaction2#1272]
**Describe the bug**

Hello, may I ask if there is something wrong with this code? The “training” variable has never been assigned a value and the generated  TXT files are empty.

[https://github.com/open-mmlab/mmaction2/blob/master/tools/data/activitynet/generate_rawframes_filelist.py](url)

**Comment by kennymckormick** [comment]
Note that we use `data_dict` to refer to `training`
