### ISSUE TITLE
sh: 1 : denseflow: not found

### ISSUE THREAD

**Issue by ououoxx** [open-mmlab/mmaction2#1274]
Dear authors:
When I extract RGB frames from kinetics400 dataset following 'data_preparation.md', error happens:
sh: 1: denseflow: not found
rgb 0 W7kBmpVsgw8.mp4 None done
After finishing extracting, the out_folder is still empty.

Here is my input:
pvthon tools/data/build rawframes.py /opt/npu/kinetics400/videos_va l/home/mmaction2-15/data/kinetics400/videos_val --task rgb --level 1 --num-worker 2 --out-format jpg --ext mp4 --new-width 256 --new-height 256

How can I solve this?

**Comment by kennymckormick** [comment]
Before extracting, please refer to [install.md](/docs/install.md) for installing [denseflow](https://github.com/open-mmlab/denseflow).

**Comment by chcchc97** [comment]
Hi! how could you solve this problem? @HK-Zhong

**Comment by HK-Zhong** [comment]
I can't remember in detail, but you should add "--opencv" or "--denseflow" (something like that) in your command to specify the tools you are going to utilize. @Chenhongchang

**Comment by chcchc97** [comment]
Thank you! I have solve it by change the `.bashrc`. @HK-Zhong
