### ISSUE TITLE
How to train custom AVA data with different video length at SlowFast?

### ISSUE THREAD

**Issue by TripodTripod** [open-mmlab/mmaction2#1279]
I want to train one class action detection model with my own data. My videos are amost serveral seconds and they have different length. I check the issues and set timestamp_start=1.
https://github.com/open-mmlab/mmaction2/blob/2b6f9ac69b3609b96a514501ffe30fc90545f518/mmaction/datasets/ava_dataset.py#L108

But it doesn't help, I get this: **No such file or dictionary: 'xxx/xxx/Coffee_room_01_video_07/img_00000.jpg'**

1. I have no idea about img_00000.jpg, can you give me some suggestions ?
2. I see the answer in https://github.com/open-mmlab/mmaction2/issues/1002 , but I don't know how to modify the AVADataset. Would you mind to explain the details ?
The way I suppose be like :
Step1: Get a dict like dict_end={'video_name': {timestamp_end}, ...}
Step2: let self.timestamp_end = dict_end['video_name']
https://github.com/open-mmlab/mmaction2/blob/2b6f9ac69b3609b96a514501ffe30fc90545f518/mmaction/datasets/ava_dataset.py#L238
But how to modify the timestamp_end at other place like result['timestamp_end'] in ava_dataset.py/AVADataset/prepare_train_frames?
https://github.com/open-mmlab/mmaction2/blob/2b6f9ac69b3609b96a514501ffe30fc90545f518/mmaction/datasets/ava_dataset.py#L280

**Comment by TripodTripod** [comment]
Maybe 1. can be sovled by change 0 to 1 at :
https://github.com/open-mmlab/mmaction2/blob/28ac80cb1a96c208a3e95f76f051ebafc74390aa/mmaction/datasets/pipelines/loading.py#L1278

**Comment by TripodTripod** [comment]
The train goes well after making these changes above. I'm going to check the model that if it really learned sth.

**Comment by kennymckormick** [comment]
Your modification seems to be OK, for the problem of 'img_00000.jpg', you can also refer to this issue. A fix is provided by the user who raises this issue, and will soon be merged into the master branch.

**Comment by TripodTripod** [comment]
Thank you for your reply. Can't wait for new merge.
The trained model doesn't learn well. Maybe the change of '0 to 1' make things wrong.

**Comment by TripodTripod** [comment]
Finally，torch with cpu makes things wrong, I should have installed a version with GPU. It's recommed to use torch with 1.9.1+cu102 rather than torch with 1.8.0.
The loss stay 0 and the mAP become 1 quickly when training on CPU.
Thanks again.

**Comment by TTy32** [comment]
Bit late to the party, but in case anyone finds this issue through google:

I was able to get this working by explicitly setting `timestamp_start`, `timestamp_end`, and `shot_info` to the total number of frames (which seems to be set in `['timestamp']`.

`total_frames` is not available and is therefore set to default value of 27000.

https://github.com/open-mmlab/mmaction2/blob/4d6c93474730cad2f25e51109adcf96824efc7a3/mmaction/datasets/transforms/loading.py#L746-L760

Directly after the `def transform` definition, add:

```
results['timestamp_start'] = 1
results['timestamp_end'] = results['timestamp']
```

And change below line:

https://github.com/open-mmlab/mmaction2/blob/4d6c93474730cad2f25e51109adcf96824efc7a3/mmaction/datasets/transforms/loading.py#L760

to:

```
shot_info = (0, results['timestamp'] * fps)
```

After the if/else, add `shot_info` back to `results`:

```
results['shot_info'] = shot_info
```

Good luck!
