### ISSUE TITLE
Train custom data

### ISSUE THREAD

**Issue by IDayday** [open-mmlab/mmaction2#128]
**I write a slowfast_custom_config.py . It reads:**

model = dict(
    type='Recognizer3D',
    backbone=dict(
        type='ResNet3dSlowFast',
        pretrained=None,
        resample_rate=8,  # tau
        speed_ratio=8,  # alpha
        channel_ratio=8,  # beta_inv
        slow_pathway=dict(
            type='resnet3d',
            depth=50,
            pretrained=None,
            lateral=True,
            conv1_kernel=(1, 7, 7),
            dilations=(1, 1, 1, 1),
            conv1_stride_t=1,
            pool1_stride_t=1,
            inflate=(0, 0, 1, 1),
            norm_eval=False),
        fast_pathway=dict(
            type='resnet3d',
            depth=50,
            pretrained=None,
            lateral=False,
            base_channels=8,
            conv1_kernel=(5, 7, 7),
            conv1_stride_t=1,
            pool1_stride_t=1,
            norm_eval=False)),
    cls_head=dict(
        type='SlowFastHead',
        in_channels=2304,  # 2048+256
        num_classes=400,
        spatial_type='avg',
        dropout_ratio=0.5))
train_cfg = None
test_cfg = dict(average_clips=None)
dataset_type = 'VideoDataset'
_**data_root = '/dat01/liuzhixiong/zt/mmaction2/data/fortest/videos_train'
data_root_val = '/dat01/liuzhixiong/zt/mmaction2/data/fortest/videos_val'
ann_file_train = '/dat01/liuzhixiong/zt/mmaction2/data/fortest/train_list_videos.txt'
ann_file_val = '/dat01/liuzhixiong/zt/mmaction2/data/fortest/val_list_videos.txt'
ann_file_test = '/dat01/liuzhixiong/zt/mmaction2/data/fortest/val_list_videos.txt'**_
img_norm_cfg = dict(
    mean=[123.675, 116.28, 103.53], std=[58.395, 57.12, 57.375], to_bgr=False)
train_pipeline = [
    dict(type='DecordInit'),
    dict(type='SampleFrames', clip_len=32, frame_interval=2, num_clips=1),
    dict(type='DecordDecode'),
    dict(type='Resize', scale=(-1, 256)),
    dict(type='RandomResizedCrop'),
    dict(type='Resize', scale=(224, 224), keep_ratio=False),
    dict(type='Flip', flip_ratio=0.5),
    dict(type='Normalize', **img_norm_cfg),
    dict(type='FormatShape', input_format='NCTHW'),
    dict(type='Collect', keys=['imgs', 'label'], meta_keys=[]),
    dict(type='ToTensor', keys=['imgs', 'label'])
]
val_pipeline = [
    dict(type='DecordInit'),
    dict(
        type='SampleFrames',
        clip_len=32,
        frame_interval=2,
        num_clips=1,
        test_mode=True),
    dict(type='DecordDecode'),
    dict(type='Resize', scale=(-1, 256)),
    dict(type='CenterCrop', crop_size=224),
    dict(type='Flip', flip_ratio=0),
    dict(type='Normalize', **img_norm_cfg),
    dict(type='FormatShape', input_format='NCTHW'),
    dict(type='Collect', keys=['imgs', 'label'], meta_keys=[]),
    dict(type='ToTensor', keys=['imgs'])
]
test_pipeline = [
    dict(type='DecordInit'),
    dict(
        type='SampleFrames',
        clip_len=32,
        frame_interval=2,
        num_clips=10,
        test_mode=True),
    dict(type='DecordDecode'),
    dict(type='Resize', scale=(-1, 256)),
    dict(type='ThreeCrop', crop_size=256),
    dict(type='Flip', flip_ratio=0),
    dict(type='Normalize', **img_norm_cfg),
    dict(type='FormatShape', input_format='NCTHW'),
    dict(type='Collect', keys=['imgs', 'label'], meta_keys=[]),
    dict(type='ToTensor', keys=['imgs'])
]
data = dict(
    _**videos_per_gpu=4,**_
    workers_per_gpu=4,
    train=dict(
        type=dataset_type,
        ann_file=ann_file_train,
        data_prefix=data_root,
        pipeline=train_pipeline),
    val=dict(
        type=dataset_type,
        ann_file=ann_file_val,
        data_prefix=data_root_val,
        pipeline=val_pipeline),
    test=dict(
        type=dataset_type,
        ann_file=ann_file_test,
        data_prefix=data_root_val,
        pipeline=test_pipeline))

optimizer = dict(
    type='SGD', lr=0.1, momentum=0.9,
    weight_decay=0.0001)  # this lr is used for 8 gpus
optimizer_config = dict(grad_clip=dict(max_norm=40, norm_type=2))

lr_config = dict(
    policy='CosineAnnealing',
    min_lr=0,
    warmup='linear',
    warmup_by_epoch=True,
    warmup_iters=34)
total_epochs = 256
checkpoint_config = dict(interval=4)
workflow = [('train', 1)]
evaluation = dict(
    interval=5, metrics=['top_k_accuracy', 'mean_class_accuracy'], topk=(1, 5))
log_config = dict(
    interval=20,
    hooks=[
        dict(type='TextLoggerHook'),
        #    dict(type='TensorboardLoggerHook'),
    ])
dist_params = dict(backend='nccl')
log_level = 'INFO'
_**work_dir = './work_dirs/slowfast_r50_video_3d_4x16x1_256e_fortest_rgb'**_
load_from = None
resume_from = None
find_unused_parameters = False

**The train_list_videos.txt follows the tips.It reads:**

data/fortest/videos_train/01_trian.mp4 1
data/fortest/videos_train/02_trian.mp4 1
data/fortest/videos_train/03_trian.mp4 1
data/fortest/videos_train/04_trian.mp4 2
data/fortest/videos_train/05_trian.mp4 3
......

But when I ues:
python tools/train.py configs/recognition/slowfast/slowfast_custom_config.py \
    --work-dir work_dirs/slowfast_r50_4x16x1_256e_fortest_rgb \
    --validate --seed 0 --deterministic
to sbatch my job.

**It feedbacks:**

Traceback (most recent call last):
  File "tools/train.py", line 146, in <module>
    main()
  File "tools/train.py", line 125, in main
    datasets = [build_dataset(cfg.data.train)]
  File "/dat01/liuzhixiong/zt/mmaction2/mmaction/datasets/builder.py", line 39, in build_dataset
    dataset = build_from_cfg(cfg, DATASETS, default_args)
  File "/dat01/liuzhixiong/anaconda3/envs/mmaction/lib/python3.6/site-packages/mmcv/utils/registry.py", line 167, in build_from_cfg
    return obj_cls(**args)
  File "/dat01/liuzhixiong/zt/mmaction2/mmaction/datasets/video_dataset.py", line 43, in __init__
    super().__init__(ann_file, pipeline, start_index=start_index, **kwargs)
  File "/dat01/liuzhixiong/zt/mmaction2/mmaction/datasets/base.py", line 63, in __init__
    self.video_infos = self.load_annotations()
  File "/dat01/liuzhixiong/zt/mmaction2/mmaction/datasets/video_dataset.py", line 58, in load_annotations
    filename, label = line_split
ValueError: not enough values to unpack (expected 2, got 0)

I don't konw why it can't read my list.txt

**Comment by dreamerlin** [comment]
Seen the bug information, it seems sth went wrong with your annotation file (probably the first line or the encode style causes the problem ). you can try these codes to do some troubleshooting by printing your annotation in each line.
```
ann_file = "/dat01/liuzhixiong/zt/mmaction2/data/fortest/train_list_videos.txt"
with open(self.ann_file, 'r') as fin:
    for line in fin:
        print(line.strip().split())
```

**Comment by dreamerlin** [comment]
The content of the file is correct
```
s = 'data/fortest/videos_train/01_trian.mp4 1'
s.strip().split()
Out[3]: ['data/fortest/videos_train/01_trian.mp4', '1']
s = 'data/fortest/videos_train/01_trian.mp4 1\n'
s.strip().split()
Out[5]: ['data/fortest/videos_train/01_trian.mp4', '1']
s = 'data/fortest/videos_train/01_trian.mp4 1\r\n'
s.strip().split()
Out[7]: ['data/fortest/videos_train/01_trian.mp4', '1']
```

**Comment by IDayday** [comment]
Thanks! I find it that my list.txt has one more space, so it returns zero.
I have taken this lesson to check.
