### ISSUE TITLE
How to embed it into 3D skeleton based action recognition

### ISSUE THREAD

**Issue by PJJie** [open-mmlab/mmaction2#1280]
Do you have the task of human 3D skeleton pose estimation, that is, input a video and output human 3D skeleton video or human 3D skeleton file. I am now using NTU rgb60 data set for action recognition. I want to combine the 3D skeleton pose estimation of human body and directly obtain the action classification from a video. Thank you for your reply!

**Comment by kennymckormick** [comment]
No, 3D pose estimation is out of the scope of this codebase, maybe you can check mmpose.
