### ISSUE TITLE
question about input shape during inference

### ISSUE THREAD

**Issue by ououoxx** [open-mmlab/mmaction2#1281]
It's said that 'the input should be `$batch $clip $channel $time $height $width`(e.g. `1 1 3 32 224 224`);'

How do I understand $clip and $time ?

**Comment by kennymckormick** [comment]
$time is the temporal length of a clip, e.g., for a clip with 8 consecutive frames, time=8
$clip is the number of clips, you can aggregate the predictions for N clips to get a more accurate prediction for a video.

**Comment by ououoxx** [comment]
I got it.
Thank you.
