### ISSUE TITLE
PoseC3D with NTU-RGBD, test process got error: operands could not be broadcast together with shape

### ISSUE THREAD

**Issue by Adam-fei** [open-mmlab/mmaction2#1283]
Hi, I try to reproduce the PoseC3D with dataset NTU-RGBD

1. I downloaded the NTU-RGBD skeleton dataset via [link](https://github.com/shahroudy/NTURGB-D)

2. Then I convert the skeleton data to your format following [this guide](https://github.com/open-mmlab/mmaction2/blob/master/tools/data/skeleton/README.md):

```
python gen_ntu_rgbd_raw.py --data-path your_raw_nturgbd120_skeleton_path --ignored-sample-path NTU_RGBD120_samples_with_missing_skeletons.txt --out-folder your_nturgbd120_output_path --task ntu120
```

3. I try to reproduce the result with the pretrained model you provided [here](https://github.com/open-mmlab/mmaction2/blob/master/configs/skeleton/posec3d/README.md#train). So I downloaded the model **slowonly_r50_u48_240e_ntu120_xsub_keypoint**

4. I changed the data dir in the config file (configs/skeleton/posec3d/slowonly_r50_u48_240e_ntu120_xsub_keypoint.py) to the right path

5. Finally, I run the test command line following [this guide](https://github.com/open-mmlab/mmaction2/blob/master/configs/skeleton/posec3d/README.md#train). The specific command I used is:

```
python tools/test.py configs/skeleton/posec3d/slowonly_r50_u48_240e_ntu120_xsub_keypoint.py ./data/NTU_RGBD/model/slowonly_r50_u48_240e_ntu120_xsub_keypoint-6736b03f.pth --eval top_k_accuracy mean_class_accuracy --out ./data/NTU_RGBD/result/result.pkl
```

6. After above steps, I got the error message:

>  File "/anaconda3/envs/OPT/lib/python3.7/sitepackages/mmaction/datasets/pipelines/augmentations.py", line 1096, in _resize_kps
>     return kps * scale_factor
> ValueError: operands could not be broadcast together with shapes (2,480,25,3) (2,)

**Bug fix**

I wonder if it's the problem with dimension of compute element in 

> mmaction/datasets/pipelines/augmentations.py line 1096

or simply I've done something wrong.

Thanks

**Comment by Adam-fei** [comment]
Now I suspect that it's the problem of package version, since this error is reported in several "operands broadcast" process.

But have not figured out what caused this problem.

**Comment by kennymckormick** [comment]
@Adam-fei The corresponding descriptions are added.
