### ISSUE TITLE
The dataset corresponding to st-gcn was not found

### ISSUE THREAD

**Issue by yanhan13944047669** [open-mmlab/mmaction2#1285]
I want to train the model st-gcn with 2d keypoints,but I can't find the dataset needed to train the model.How should I get the dataset？
 I hope you can solve my problem, thank you.

**Comment by kennymckormick** [comment]
Just follow our config file: https://github.com/open-mmlab/mmaction2/blob/master/configs/skeleton/stgcn/stgcn_80e_ntu60_xsub_keypoint.py. 

We use PoseDataset for STGCN-2D, you can find the download links for the pickle annotations here: https://github.com/open-mmlab/mmaction2/tree/master/tools/data/skeleton
