### ISSUE TITLE
puzzled about the input size of posec3d 

### ISSUE THREAD

**Issue by x2ss** [open-mmlab/mmaction2#1288]
Hi,

When I read the paper "Revisiting Skeleton-based Action Recognition", I got puzzled about the input shape of 3D-CNN network. 

As stated in Section 3.2,  the 3D heatmap volume is K × T × H × W,  however in Section 4,2,  the The input size for all 3D-CNN experiments is T ×H×W. So what exactly the input of the network is? Did I miss something?

Thanks!

**Comment by kennymckormick** [comment]
K is just the channel size. Like you can call the shape of a 2D image `H x W` or `3 x H x W` (3 channels: R, G, B). Do you get it with this example?

**Comment by x2ss** [comment]
> K is just the channel size. Like you can call the shape of a 2D image `H x W` or `3 x H x W` (3 channels: R, G, B). Do you get it with this example?

As stated in the paper, K is the number of joints. From my understanding, the size K × T × H × W and T ×H×W means different things. If the size is K × T × H × W, then the input is a stack of feature map **only** having **one joint** with high amplitude, if the size is T ×H×W, then **all the joints** are in one feature map. 

As U-net、center net or something like that, the number of output channels is decided by the class. My question here is trying to figure out what does a H*W feature map look like.

Don't know if I have made myself clear. 

Thanks

**Comment by kennymckormick** [comment]
The shape is K × T × H × W.  K is the number of joints and corresponds to the channels dimension in a 3D-CNN.

**Comment by x2ss** [comment]
> The shape is K × T × H × W. K is the number of joints and corresponds to the channels dimension in a 3D-CNN.

Thanks for your reply, but my question is still not answered. 

The key of my question is that whether there is **only** one joint in the heatmap **or**  there are K joints in the heatmap of the input.

**Comment by kennymckormick** [comment]
There are K joints in the heatmap of the input, and each joint occupies one channel in the heatmap, so that the shape of a heatmap (at one timestamp)  is K x H x W

**Comment by x2ss** [comment]
Thanks！
