### ISSUE TITLE
does skeleton data based posec3d recognize several actions that happen one after another?

### ISSUE THREAD

**Issue by bit-scientist** [open-mmlab/mmaction2#1291]
I have a quick question. Let's say I have a 15s video where two people shake hands for 5s, then hug each other for 5s and hop for 5s. Can the model recognize all 3 actions? Initially, I think the model takes one input video and only one class category is drawn as the output.

**Comment by kennymckormick** [comment]
Yes, currently, this feature is not supported in PoseC3D.

**Comment by bit-scientist** [comment]
hi, @kennymckormick do you have any idea of how to handle such videos with PoseC3D? I am about to start test it with those type of action sequences. Thanks

**Comment by mayerg0** [comment]
I am interested in the above as well - as well as for multiple persons doing different actions

**Comment by LZH-94** [comment]
> Yes, currently, this feature is not supported in PoseC3D.
does posec3d need exclusive realtime script ，or posec3d can also use webcam script？
sincerely hope your reply，thanks

**Comment by kennymckormick** [comment]
For a multi-action video (sequentially), you need manually split it into multiple clips and use the clips for training, and use sliding temporal window for testing. Current implementation does not support multi-person with different actions, but you can implement this imitating our implementation for spatio-temporal action detection.
