### ISSUE TITLE
Custom Dataset Training with PoseC3D problem

### ISSUE THREAD

**Issue by Disisxhy** [open-mmlab/mmaction2#1293]
Once I skip the 'ntu_det_postproc' step as noticed and then run 'python ntu_pose_extraction.py S001C001P001R001A001_rgb.avi S001C001P001R001A001_rgb.pkl', it shows the error below:

![image](https://user-images.githubusercontent.com/51524758/143521421-75f89fb4-f98f-4e0c-bbea-2dca0c3cfd01.png)
![image](https://user-images.githubusercontent.com/51524758/143521720-2db9ca71-faf6-498c-8872-598d507f03e5.png)

Hope somebody can help

**Comment by kennymckormick** [comment]
Hello, in PR #1295, I add an option named 'skip_postproc'. Please try to extract pose with this flag, and check if it can resolve your issues.

**Comment by Disisxhy** [comment]
the ‘skip_postproc' doesn't work well. comes the error 'AttributeError: 'abstractproperty' object has no attribute 'skip_postproc'

since the 'skip' is not necessary for me, I simply change ' num_frame, num_person ' thing and it woks perfectly! thx so much!

**Comment by bit-scientist** [comment]
Hi, @Disisxhy, basically you don't exactly have to use `ntu_pose_extraction.py` as it is a burden to switch off `ntu_pose_extraction` function, you can modify `demo_posec3d.py` a bit to extract necessary keys from `fake_anno` (in `demo_posec3d.py`) and dump into a pickle file. Note that you may have to use your video's name  for `frame_dir`s value and, its string split for `label`s value (if the video name contains class label ) as shown at [#1258](https://github.com/open-mmlab/mmaction2/issues/1258). Hope that helps.

**Comment by shelly-xue** [comment]
@bit-scientist @kennymckormick hi ,my custom videos have two people, if i use ntu_pose_extraction.py to extract poses, Can it be used directly for training? because we need to maintain the continuity of everyone's time, am i right?

**Comment by kennymckormick** [comment]
I think it can be directly used for PoseC3D training, but maybe not ST-GCN. Since for ST-GCN, the skeleton input should be several continuous sequences, while ntu_pose_extraction.py does not guarantee this: the person 1 in frame t and the person 1 in frame t + 1 may not be the same person. 

> @bit-scientist @kennymckormick hi ,my custom videos have two people, if i use ntu_pose_extraction.py to extract poses, Can it be used directly for training? because we need to maintain the continuity of everyone's time, am i right?
