### ISSUE TITLE
I want to save the returned features from posec3d

### ISSUE THREAD

**Issue by BBEEEEI** [open-mmlab/mmaction2#1297]
First of all, Thank you for sharing this wonderful project.
I was studying on your work 'PoseC3D' and got curious about some things.

After running the posec3d, I want to get feature maps and save these in my computer.
When I run posec3d, the result of mmaction.apis inference_recognizer method is recognition result dict.
So that in demo_c3d the only thing I can get is the recognition result.
The comment of inference_recognizer says that if I write 'outputs' as the names of the layers it will return feature maps.
Then if I set outputs with the names of the layers, will it return feature maps after running posec3d model?
Or do I have to change any other things to get feature maps of posec3d?

**Comment by kennymckormick** [comment]
Yes, you just need to set the outputs arg.

**Comment by BBEEEEI** [comment]
Thank you for your reply, by the way how can I set the outputs arg? Are there any examples about this?
I tried writing outputs arg for so many times, but everything didn't work... :(
I was using the default config file and checkpoint file of PoseC3D.

**Comment by BBEEEEI** [comment]
> Thank you for your reply, by the way how can I set the outputs arg? Are there any examples about this? I tried writing outputs arg for so many times, but everything didn't work... :( I was using the default config file and checkpoint file of PoseC3D.

Can I get some advice please..?

**Comment by kennymckormick** [comment]
Old one closed since you have reopened a new issue.
