### ISSUE TITLE
About the supporting of FineGym datasets

### ISSUE THREAD

**Issue by Amazingren** [open-mmlab/mmaction2#13]
Will this codebase add FineGym to the data_preparation?

**Comment by innerlee** [comment]
short answer is yes. long answer is that we are still prioritizing the next thing. thanks for the question and we will consider feedback when planning.

**Comment by Amazingren** [comment]
> short answer is yes. long answer is that we are still prioritizing the next thing. thanks for the question and we will consider feedback when planning.

Thanks for the reply, and I also make a feature request in #19  RoadMap of MMaction2
