### ISSUE TITLE
Questions when using -- resume-from

### ISSUE THREAD

**Issue by ImmortalCi** [open-mmlab/mmaction2#1301]
When resuming from the former path, the epoch and inter is reset and not be Inherited.

What leads to this problem? How to solve this problem?

Thanks a lot!
<img width="1094" alt="截屏2021-11-30 11 31 35" src="https://user-images.githubusercontent.com/74886609/143981064-254bf9ce-79ca-481d-9bc7-1722fb6f4cc6.png">

**Comment by kennymckormick** [comment]
Hi, are you sure you are using --resume-from instead of --load-from? Seems you are using --load-from

**Comment by ll490187880** [comment]
This is a bug for mmcv, you can update mmcv or just modify the code in mmcv.runner.
see this issue https://github.com/open-mmlab/mmcv/pull/1108

**Comment by ImmortalCi** [comment]
Thanks for your reply！




------------------ Original ------------------
From: ll490187880 ***@***.***&gt;
Date: Mon,Dec 27,2021 8:30 PM
To: open-mmlab/mmaction2 ***@***.***&gt;
Cc: ImmortalCi ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [open-mmlab/mmaction2] Questions when using -- resume-from (Issue#1301)
