### ISSUE TITLE
How can I use all of my GPU memory to perform the inference

### ISSUE THREAD

**Issue by Disisxhy** [open-mmlab/mmaction2#1307]
When I perfrom the inference in demo/demo_posec3d.py, it shows that it only use 6 GB of the gpu memory and it's slow.
I try to change 'samples_per_gpu' and 'workers_per_gpu', but it doesn't help.
How can I use all of my GPU memory to perform the inference? Or are there other ways to perform the inference quicker?

**Comment by kennymckormick** [comment]
The speed is slow since we call the inference API of mmdet and mmpose to inference frames one by one. For acceleration, you can improve the pose & det inference part.

**Comment by Disisxhy** [comment]
Thank you for your reply, I have tried yolov3 for mmdet inference and it get's much faster.
