### ISSUE TITLE
AssertionError: (test with Slowonly_kinetics600_rgb in own mp4 video)

### ISSUE THREAD

**Issue by praymich** [open-mmlab/mmaction2#1310]
my code as follows , just like the example
import torch
from mmaction.apis import init_recognizer, inference_recognizer

config_file = '../configs/recognition/slowonly/slowonly_r50_video_8x8x1_256e_kinetics600_rgb.py'
device = 'cuda:0' # 或 'cpu'
device = torch.device(device)

checkpoint_file = '../checkpoints/slowonly_r50_video_8x8x1_256e_kinetics600_rgb_20201015-81e5153e.pth'

model = init_recognizer(config_file, checkpoint_file, device=device)
# 进行演示视频的推理
#inference_recognizer(model, 'demo/demo.mp4')
video = './demo2.mp4'
labels = '../tools/data/kinetics/label_map_k600.txt'

results = inference_recognizer(model, video)
print(results)

labels = open(labels).readlines()
labels = [x.strip() for x in labels]
results = [(labels[k[0]], k[1]) for k in results]

for result in results:
    print(f'{result[0]}: ', result[1])

###but it caused 

AssertionError                            Traceback (most recent call last)
<ipython-input-5-a5ea49a83052> in <module>
     14 labels = '/opt/ai_code/YPL/Action_recognition_models/mmaction2/tools/data/kinetics/label_map_k600.txt'
     15 
---> 16 results = inference_recognizer(model, video)
     17 print(results)
     18 

/opt/ai_code/YPL/Action_recognition_models/mmaction2/mmaction/apis/inference.py in inference_recognizer(model, video, outputs, as_tensor, **kwargs)
    160 
    161     test_pipeline = Compose(test_pipeline)
--> 162     data = test_pipeline(data)
    163     data = collate([data], samples_per_gpu=1)
    164 

/opt/ai_code/YPL/Action_recognition_models/mmaction2/mmaction/datasets/pipelines/compose.py in __call__(self, data)
     48 
     49         for t in self.transforms:
---> 50             data = t(data)
     51             if data is None:
     52                 return None

/opt/ai_code/YPL/Action_recognition_models/mmaction2/mmaction/datasets/pipelines/augmentations.py in __call__(self, results)
   1683         img_h, img_w = results['imgs'][0].shape[:2]
   1684         crop_w, crop_h = self.crop_size
-> 1685         assert crop_h == img_h or crop_w == img_w
   1686 
   1687         if crop_h == img_h:

AssertionError: 

can you help me?or i get something wrong in configs?

**Comment by kennymckormick** [comment]
Seems that you use `ThreeCrop` in test pipelines. If you use it, the img_h or img_w should be equal to crop_size. You can change `ThreeCrop` in the config file to `CenterCrop` to avoid this problem.

**Comment by praymich** [comment]
> Seems that you use `ThreeCrop` in test pipelines. If you use it, the img_h or img_w should be equal to crop_size. You can change `ThreeCrop` in the config file to `CenterCrop` to avoid this problem.

thanks，you mean change the data dict type in the XX.py ？

**Comment by praymich** [comment]
> Seems that you use `ThreeCrop` in test pipelines. If you use it, the img_h or img_w should be equal to crop_size. You can change `ThreeCrop` in the config file to `CenterCrop` to avoid this problem.

thanks，you mean change the data dict type in the XX.py ？

**Comment by dreamerlin** [comment]
1. change `ThreeCrop` to `CenterCrop` like https://github.com/open-mmlab/mmaction2/blob/master/configs/recognition/tsn/tsn_r50_1x1x3_100e_kinetics400_rgb.py#L41
2. Make sure the `crop_size` is equal to `img_w` or `img_h` like https://github.com/open-mmlab/mmaction2/blob/master/configs/recognition/slowonly/slowonly_r50_video_4x16x1_256e_kinetics400_rgb.py#L55-L56

**Comment by dreamerlin** [comment]
Reopen this issue if you encounter any problems
