### ISSUE TITLE
How to use fp16 for slowonly?

### ISSUE THREAD

**Issue by takfate** [open-mmlab/mmaction2#1315]
I add `fp16=dict()` in slowonly config, but error occured `RuntimeError: expected scalar type Float but found Half` at `I3DHead.fc_cls` `addmm op`.
Please, thanks.

**Comment by kennymckormick** [comment]
Hi, takfate, we haven't supported SlowOnly + fp16 yet.

**Comment by takfate** [comment]
Thanks for your response. But I have implemented it.

**Comment by kennymckormick** [comment]
> Thanks for your response. But I have implemented it.

Nice work! Are you willing to raise a PR about SlowOnly + fp16 training? I think it will benefit many people.
