### ISSUE TITLE
Module tools/data/kinetics/label_map_k400.txt not found

### ISSUE THREAD

**Issue by futureflsl** [open-mmlab/mmaction2#1317]
I saw https://github.com/open-mmlab/mmaction2/issues/1253 ,But it doesn't solove my problem.I just use this code:https://github.com/open-mmlab/mmaction2/blob/master/demo/demo.ipynb

error:
Traceback (most recent call last):
  File "test.py", line 19, in <module>
    results = inference_recognizer(model, video, labels)
  File "/home/fut/mmlab/mmaction2-0.20.0/mmaction/apis/inference.py", line 170, in inference_recognizer
    with OutputHook(model, outputs=outputs, as_tensor=as_tensor) as h:
  File "/home/fut/mmlab/mmaction2-0.20.0/mmaction/core/hooks/output.py", line 23, in __init__
    self.register(module)
  File "/home/fut/mmlab/mmaction2-0.20.0/mmaction/core/hooks/output.py", line 47, in register
    raise AttributeError(f'Module {name} not found')
AttributeError: Module tools/data/kinetics/label_map_k400.txt not found

**Comment by kennymckormick** [comment]
Would you please double-check the codebase version? This line
```python
results = inference_recognizer(model, video, labels)
```
no longer exists in the latest version of the codebase.

**Comment by xiangwentao666** [comment]
Could you please tell me how you've fixed that problem? The same problem occurred when I run the same code.

**Comment by kennymckormick** [comment]
> Could you please tell me how you've fixed that problem? The same problem occurred when I run the same code.

Please clone our repo and use the latest codes in master branch.

**Comment by xiangwentao666** [comment]
> > Could you please tell me how you've fixed that problem? The same problem occurred when I run the same code.
> 
> Please clone our repo and use the latest codes in master branch.

Well, thank you very much for your timely reply! I'll try the latest codes in the master branch later.
