### ISSUE TITLE
Docker installed mmcv version incompatible

### ISSUE THREAD

**Issue by yingfhu** [open-mmlab/mmaction2#1324]
In latest version, Dockerfile only builds mmcv version with 1.3.5, which is incompatible with the minimum version requirement of 1.3.6.

**Comment by kennymckormick** [comment]
The problem is fixed in this commit: https://github.com/open-mmlab/mmaction2/commit/9ff6a14c103967d97e193957370392c4acff9936. 

Please have a try.
