### ISSUE TITLE
Working with action recognition dataset

### ISSUE THREAD

**Issue by MrOCW** [open-mmlab/mmaction2#1329]
Hi,
I have an action that I want to recognize which is about 3~5 seconds long. Should I extract the relevant parts of the video and use the VideoDataset format? Will this format/method affect the accuracy in any way?

Also, for videos with multiple people inside, should I crop each person into separate videos?

**Comment by dreamerlin** [comment]
1. VideoDataset is the same with RawFrameDataset, the former decode videos into frames on the fly, and the latter decodes videos into frames on disk before training. Actually, they do not affect the accuracy.
2. In common case, there is no need to crop each person into separate videos. But I think it can obtain better performance to do that for some fine-grained labels. There are some papers do that thing.

**Comment by MrOCW** [comment]
@dreamerlin 
1. OK! would you recommend to extract only relevant action out from a long video? for example, video A is 10 seconds but action A took only 3 seconds to perform and 7 seconds of doing nothing/random things. should i trim the video to only 3 seconds?

2. Do you happen to have the link to the papers?

Thanks!

**Comment by dreamerlin** [comment]
1. It is better to extract only relevant action out from a long video if you know when the action happens. However, we actually do not know it given a random video.
2. [AdaFocus](https://arxiv.org/abs/2105.03245), [Something-Else](https://arxiv.org/pdf/1912.09930.pdf)
