### ISSUE TITLE
Where to set the batchsize while training timesformer?

### ISSUE THREAD

**Issue by deepthman** [open-mmlab/mmaction2#1330]
When I used my own data to train timesformer, I reported the following errors:

File "/root/anaconda3/envs/mmaction/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 274, in __init__
    batch_sampler = BatchSampler(sampler, batch_size, drop_last)
  File "/root/anaconda3/envs/mmaction/lib/python3.7/site-packages/torch/utils/data/sampler.py", line 219, in __init__
    "but got batch_size={}".format(batch_size))
ValueError: batch_size should be a positive integer value, but got batch_size=0

But I cannot find a file to set it,  I'm not sure if it supports training.

**Comment by TranNgocTinh0810** [comment]
I have the same problem, did you solve it? @deepthman

**Comment by deepthman** [comment]
> I have the same problem, did you solve it? @deepthman

Some can't remember, I modified the code according to the prompt, and still can't find the relevant file.

**Comment by TranNgocTinh0810** [comment]
@deepthman  Thank you for the feedback.

**Comment by iucario** [comment]
```
cfg.data.videos_per_gpu = 2
cfg.data.workers_per_gpu= 2
```

I fix mine by setting this config. It has to be **at least 1**.

I am using Google Colab and the suggested value in the `Tutorial.ipynb` would cause this error.

Hope it helps!

**Comment by TranNgocTinh0810** [comment]
> hi, @TranNgocTinh0810 did you solve it?

@JoseMiguelCh Sorry for the late response, are you running the code using the Tutorial. ipynb file right? You can fix this error by editing the config file as commented above.
