### ISSUE TITLE
What is the function of proposals in ava_dense_proposals_train.FAIR.recall_93.9.pkl during training slwofast?

### ISSUE THREAD

**Issue by yikoudamifan** [open-mmlab/mmaction2#1336]
What is the function of proposals in ava_dense_proposals_train.FAIR.recall_93.9.pkl during training slwofast?

**Comment by kennymckormick** [comment]
It provides the human proposal boxes for AVA videos, during training, we will use the proposal boxes and RoIAlign to obtain instance-level features.

**Comment by yikoudamifan** [comment]
> 
Thank you very much for answering my question.
The proposal box is already provided in train.csv. Is the proposal box provided by pkl file again to improve the recognition accuracy?

**Comment by kennymckormick** [comment]
> > 
> 
> Thank you very much for answering my question. The proposal box is already provided in train.csv. Is the proposal box provided by pkl file again to improve the recognition accuracy?

Not exactly. Boxes provided in CSV files are ground-truth (annotated by humans), boxes provided in pickles files are proposals (predicted by detectors).

**Comment by yikoudamifan** [comment]
> > > 
> > 
> > 
> > Thank you very much for answering my question. The proposal box is already provided in train.csv. Is the proposal box provided by pkl file again to improve the recognition accuracy?
> 
> Not exactly. Boxes provided in CSV files are ground-truth (annotated by humans), boxes provided in pickles files are proposals (predicted by detectors).

So what is the specific role of this pkl file?

**Comment by kennymckormick** [comment]
The pkl files contain the proposals, we use the proposal boxes and RoIAlign to obtain instance-level features in training and testing. We can not assume ground-truth bounding boxes, so we need to use proposal boxes for training and testing

**Comment by hukkai** [comment]
@kennymckormick Hello, if I want to train the model on a new dataset, is there a tool to generate such proposals?

**Comment by coldmanck** [comment]
@kennymckormick Same question as @hukkai here, could you please provide any hint on generating person proposals in the same format?

**Comment by btalberg** [comment]
@kennymckormick  -  Could you share some insight into why you chose `denseflow` to generate the bounding box proposals rather than another option like `yolo` or your `mmDetection` library? Thanks!
