### ISSUE TITLE
Error inference st-gcn

### ISSUE THREAD

**Issue by DongDem** [open-mmlab/mmaction2#1337]
Hi @openmmlab-bot. Firstly, I give my thanks for our useful framework. But, when I want to inference ST-GCN model to recognize the action, the error has happened. I ran the following command
``` shell
python demo/demo_posec3d.py demo/ntu_sample.avi demo/posec3d_demo.mp4 --config configs/skeleton/stgcn/stgcn_80e_ntu60_xsub_keypoint.py     --checkpoint https://download.openmmlab.com/mmaction/skeleton/stgcn/stgcn_80e_ntu60_xsub_keypoint/stgcn_80e_ntu60_xsub_keypoint-e7bb9653.pth     --det-config demo/faster_rcnn_r50_fpn_2x_coco.py     --det-checkpoint http://download.openmmlab.com/mmdetection/v2.0/faster_rcnn/faster_rcnn_r50_fpn_2x_coco/faster_rcnn_r50_fpn_2x_coco_bbox_mAP-0.384_20200504_210434-a5d8aa15.pth     --det-score-thr 0.9     --pose-config demo/hrnet_w32_coco_256x192.py     --pose-checkpoint https://download.openmmlab.com/mmpose/top_down/hrnet/hrnet_w32_coco_256x192-c78dce93_20200708.pth     --label-map tools/data/skeleton/label_map_ntu120.txt
```
and got the error `stgcn_80e_ntu60_xsub_keypoint-e7bb9653.pth is a zip archive (did you mean to use torch.jit.load()?)`.

I already run successfully with `PoseC3D` model.

Can you tell me what causes this error how I can solve them? Thank you very much!

**Comment by kennymckormick** [comment]
Hi, first of all, the error `stgcn_80e_ntu60_xsub_keypoint-e7bb9653.pth is a zip archive (did you mean to use torch.jit.load()?)` is because you are using an old version of PyTorch, you should use `torch>=1.5.0` I guess. 

Besides, I'm not sure if demo_posec3d also supports GCN models. When we develop this demo, it is only for PoseC3D.

**Comment by DongDem** [comment]
hi @kennymckormick. Thank you for your prompt reply. So did you create any script for st-gcn demo?

**Comment by kennymckormick** [comment]
Hi, DongDem, I have supported st-gcn demo in the latest PR #1391. you can find instructions for running st-gcn demo in that PR.
