### ISSUE TITLE
Custom Dataset Training.

### ISSUE THREAD

**Issue by kkdd0717** [open-mmlab/mmaction2#1339]
Hello, first of all, thank you very much for your work.

When I made my own dataset, in the process of generating pkl files for each video, I noticed that there were two parameters, img_shape and original_shape：(1080, 1920). I want to know whether the generated pkl file can be used for training when my video file specification is 320*240.
In addition, I also want to know that the Negev parameter represents the width of the video frame，1080？or 1920？

**Comment by kennymckormick** [comment]
For your custom dataset, you should use the **real** shape of the video instead of (1080, 1920). I hardcode it for NTU pose extraction since all videos are with height 1080 and width 1920.

**Comment by kkdd0717** [comment]
Thank you very much for your reply. 
I will try your method.
