### ISSUE TITLE
cannot import name 'init_random_seed' from 'mmaction.apis'

### ISSUE THREAD

**Issue by nyanmn** [open-mmlab/mmaction2#1341]
When I tried to train mmaction, I have error as `cannot import name 'init_random_seed' from 'mmaction.apis'`.
What could be issue?
I am using latest version of mmaction2.

```
(open-mmlab) itc@itc-Precision-7920-Tower:~/mmaction2$ python tools/train.py configs/recognition/tsn/tsn_r50_1x1x3_75e_ucf101_rgb.py --work-dir work_dirs/tsn_r50_1x1x3_75e_ucf101_rgb --validate --seed 0 --deterministic
Traceback (most recent call last):
  File "tools/train.py", line 16, in <module>
    from mmaction.apis import init_random_seed, train_model
ImportError: cannot import name 'init_random_seed' from 'mmaction.apis' (/home/itc/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmaction/apis/__init__.py)
```

**Comment by kennymckormick** [comment]
![image](https://user-images.githubusercontent.com/34324155/147042819-79c1f5df-4da7-4dbf-8352-9a5219122c16.png)

Are you sure you are using latest version of mmaction2, or mmaction?

**Comment by nyanmn** [comment]
Yes I see that in mmaction2/mmaction/apis/__init__.py
mmaction2 was installed one month ago and version is v0.20.0.
I can run test, but train has that error.

**Comment by nyanmn** [comment]
Now realized that __init.py__ inside anaconda env (/home/itc/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmaction/apis/__init__.py) has no `init_random_seed`.


```
# Copyright (c) OpenMMLab. All rights reserved.
from .inference import inference_recognizer, init_recognizer
from .test import multi_gpu_test, single_gpu_test
from .train import train_model

__all__ = [
    'train_model', 'init_recognizer', 'inference_recognizer', 'multi_gpu_test',
    'single_gpu_test'
]
```
Installed version and github source code are not same version.

**Comment by kennymckormick** [comment]
You can re-install the latest version to solve this problem by `pip install -e .` in the directory `mmaction2`
