### ISSUE TITLE
How can I obtain test accuracy and loss?

### ISSUE THREAD

**Issue by luigidamico100** [open-mmlab/mmaction2#1345]
The script tools/test.py outputs the model scores associated to each class for all the test set. In order to get the aggregate metrics and losses on the entire test set one should manually compute them. 
Do I miss something? Is there any way to automatically compute the aggregate metrics and losses on the test set?

**Comment by kennymckormick** [comment]
To get the test_accuracy, you should set the flag `--eval top_k_accuracy` when executing `test.py`. Currently, we have no API to compute test set loss, you need to compute it manually.
