### ISSUE TITLE
Model link failure

### ISSUE THREAD

**Issue by Blueyao17** [open-mmlab/mmaction2#1346]
https://mmaction2.readthedocs.io/en/latest/recognition_models.html

**Comment by kennymckormick** [comment]
@gengenkai  Can you help fix this?

**Comment by gengenkai** [comment]
> @gengenkai Can you help fix this?

Okay. Will check it these days.

**Comment by gengenkai** [comment]
> https://mmaction2.readthedocs.io/en/latest/recognition_models.html

Hey, could you tell me which recognition model link failed. Thanks.

**Comment by kennymckormick** [comment]
Fixed Now.
