### ISSUE TITLE
[Reasking] I want to save the returned features from posec3d.

### ISSUE THREAD

**Issue by BBEEEEI** [open-mmlab/mmaction2#1348]
![image](https://user-images.githubusercontent.com/95128500/147226826-698ecca9-a3cd-421e-acd4-f333c1ae74ce.png)

https://github.com/open-mmlab/mmaction2/issues/1297

I asked question above, and I want to know how to write the outputs arg of inference_recognizer in PoseC3D code.
I think this is simple question, but didn't get any response of you.
Please tell me how to set the outputs arg.

Also, I wonder how to use the relative value of human skeleton in PoseC3D.

Thank you.

**Comment by kennymckormick** [comment]
Hi, BBEEEEI, you just need to set outputs as a list of modules: you want the output feature from these modules. A minimal example is below:

```python
import torch
from mmaction.models import build_model
from mmaction.core import OutputHook
# A model cfg of PoseC3D
modelcfg = dict(
    type='Recognizer3D',
    backbone=dict(
        type='ResNet3dSlowOnly',
        depth=50,
        pretrained=None,
        in_channels=17,
        base_channels=32,
        num_stages=3,
        out_indices=(2, ),
        stage_blocks=(4, 6, 3),
        conv1_stride_s=1,
        pool1_stride_s=1,
        inflate=(0, 1, 1),
        spatial_strides=(2, 2, 2),
        temporal_strides=(1, 1, 2),
        dilations=(1, 1, 1)),
    cls_head=dict(
        type='I3DHead',
        in_channels=512,
        num_classes=99,
        spatial_type='avg',
        dropout_ratio=0.5),
    train_cfg=dict(),
    test_cfg=dict(average_clips='prob'))
# We just build this model
model = build_model(modelcfg)
# We use a fake input here, which is batch x num_clips x num_joints x temporal_length x height x width
Input = torch.randn([1, 2, 17, 48, 56, 56])
# We want intermediate feature after 'backbone.conv1.conv' module
outputs=['backbone.conv1.conv']
with OutputHook(model, outputs=outputs, as_tensor=False) as h:
    with torch.no_grad():
        scores = model(return_loss=False, imgs=Input)[0]
    returned_features = h.layer_outputs
# Now you get the intermediate features: returned_features is a dictionary: the keys are items in `outputs`, values are features we want
```

Hope this example can help you, I extract key parts from inference API to form this example.

BTW, I will close ur old issue since u open a new one :lol

**Comment by BBEEEEI** [comment]
Thank you for the example!

I'm sorry to keep asking, but what should I do to extract this 512 part of the model?
![image](https://user-images.githubusercontent.com/95128500/147550340-d6a32ba2-f79f-4aac-ade3-2075b4671863.png)
I wrote outputs=['backbone.pool1'] and this didn't work.

**Comment by kennymckormick** [comment]
You just need to follow the instructions on feature extraction: https://github.com/open-mmlab/mmaction2/blob/master/docs/feature_extraction.md. Basically, you just need to set `test_cfg=dict(feature_extraction=True)` in the config file.
