### ISSUE TITLE
About docker image

### ISSUE THREAD

**Issue by lurchycc** [open-mmlab/mmaction2#1352]
Step 9/16 : RUN pip install mmcv-full==latest -f https://download.openmmlab.com/mmcv/dist/cu101/torch1.6.0/index.html
 ---> Running in 35b8f484efec
Looking in links: https://download.openmmlab.com/mmcv/dist/cu101/torch1.6.0/index.html
ERROR: Could not find a version that satisfies the requirement mmcv-full==latest (from versions: 1.0rc0, 1.0rc2, 1.0.0, 1.0.1, 1.0.2, 1.0.3, 1.0.4, 1.0.5, 1.1.0, 1.1.1, 1.1.2, 1.1.3, 1.1.4, 1.1.5, 1.1.6, 1.2.0, 1.2.1, 1.2.2, 1.2.3, 1.2.4, 1.2.5, 1.2.6, 1.2.7, 1.3.0, 1.3.1, 1.3.2, 1.3.3, 1.3.4, 1.3.5, 1.3.6, 1.3.7, 1.3.8, 1.3.9, 1.3.10, 1.3.11, 1.3.12, 1.3.13, 1.3.14, 1.3.15, 1.3.16, 1.3.17, 1.3.18, 1.4.0, 1.4.1, 1.4.2)
ERROR: No matching distribution found for mmcv-full==latest
The command '/bin/sh -c pip install mmcv-full==latest -f https://download.openmmlab.com/mmcv/dist/cu101/torch1.6.0/index.html' returned a non-zero code: 1
when I run dockerfile,here is some problem...

**Comment by Xinxinatg** [comment]
Hi have you been able to solve this issue? I have come across exactly the same issue
