### ISSUE TITLE
I'd like to ask about the relative coordinate value of the pose.

### ISSUE THREAD

**Issue by jangeunha1119** [open-mmlab/mmaction2#1353]
Before raising a question, you may need to check the following listed items.

**Checklist**

1. I have searched related issues but cannot get the expected help.
2. I have read the [FAQ documentation](https://mmaction2.readthedocs.io/en/latest/faq.html) but cannot get the expected help.

Hello, I am using the mmaction2 you provided well. 
I'm just going to use the pose value extracted using posec3d. At this time, we analyzed that the pose value was an absolute value, and I wonder if this guess is correct. Also, if you want to use relative coordinate values, ask how to convert them.
I'd appreciate it if you could answer. Thank you!

**Comment by kennymckormick** [comment]
The keypoint coordinates should be absolute values. When you train a PoseC3D model, the absolute coordinates are converted to relative ones in [GeneratePoseTarget](https://github.com/open-mmlab/mmaction2/blob/b347cc7eb497c68667c3922fcf69d27484abe3f1/mmaction/datasets/pipelines/pose_loading.py#L349) (depends on the video height and width). When you train a GCN model, the conversion is performed in [PoseNormalize](https://github.com/open-mmlab/mmaction2/blob/b347cc7eb497c68667c3922fcf69d27484abe3f1/mmaction/datasets/pipelines/pose_loading.py#L670).

**Comment by jangeunha1119** [comment]
Thank you for your answer! 
Thank you for explaining the posec3d and the relative coordinates.
