### ISSUE TITLE
PoseC3D Training Configuration

### ISSUE THREAD

**Issue by caidonkey** [open-mmlab/mmaction2#1356]
Thanks for your work!

I'm ongoing reproduce results using your released config. file: **slowonly_r50_u48_240e_ntu60_xsub__keypoint**.

And I noticed that in Model Zoo, the log file corresponding to **slowonly_r50_u48_240e_ntu60_xsub__keypoint** indicated that you trained the model for **only 24 epoch instead of 240 epoch**. I got confused about these ten-times different total training epochs.

Would you kindly check with this setting details?

**Comment by kennymckormick** [comment]
Hi, I use RepeatDataset (training dataset repeated 10 times) to speed up the training on my hardware. Actually, the total_epochs is 240.

**Comment by caidonkey** [comment]
Got it. Thanks for your timely explanation.
