### ISSUE TITLE
Any examples of minibatch blending?

### ISSUE THREAD

**Issue by potatowarriors** [open-mmlab/mmaction2#1367]
mmaction is a very good code base, so I am using it as the code base for my project. 
Any examples or tutorials on how to use the mini-batch blending module? If so, I think it will be of great help to me. I look forward to your reply, thank you

**Comment by kennymckormick** [comment]
Hi, MiniBatchBlending is a base & virtual class, which has subclasses like MixupBlending. An example to use MixupBlending: https://github.com/open-mmlab/mmaction2/blob/28ac80cb1a96c208a3e95f76f051ebafc74390aa/configs/recognition/tsm/tsm_r50_mixup_1x1x8_50e_sthv1_rgb.py

**Comment by potatowarriors** [comment]
Thanks so much for the reply! I think I should code it with the example you gave me.
