### ISSUE TITLE
Shape of input to ResNet3dSlowFast

### ISSUE THREAD

**Issue by jhlusko** [open-mmlab/mmaction2#1368]
If I create a default ResNet3dSlowFast with
```
model = ResNet3dSlowFast(pretrained=None)
```
what shape input should my video be?

Currently I have an input tensor of shape (batchsize, channels=3 (rbg), frames/duration, height, width).

What is expected?

**Comment by kennymckormick** [comment]
ResNet3dSlowFast is a 3D-CNN backbone, which takes 5D tensors (3D + batch + channel) as input. The shape of the input tensor should be  (batchsize, channels=3 (rbg), frames (~32), height (~224), width (~224))

**Comment by jhlusko** [comment]
Fantastic, thank you! If I reshape my video to 224x224 it works. Are there parameters I can change in ResNet3dSlowFast to use a differently shaped video?
