### ISSUE TITLE
Using BMN on THUMOS'14  dataset

### ISSUE THREAD

**Issue by sean186** [open-mmlab/mmaction2#1369]
Hello, I have tried to use bmn on THUMOS'14 data and got poor results：
`auc: 16.7673  AR@1: 0.0099   AR@5: 0.0417 AR@10: 0.0654 AR@100: 0.2599`
After refer to BMN paper and some issues #263 #158 , I am still confusing about the details.
***
experiment process:
1.  I have trained rgb and flow tsn model on ucf101 dataset and got about 82%+ top1 accuracy
2. Extracted separately rgb and flow feature refer to [activitynet feature extraction](https://github.com/open-mmlab/mmaction2/tree/master/tools/data/activitynet#step-3-extract-rgb-and-flow  )  and  rescaled tensor to [100, 101]
3. Merged rgb and flow feature to get [100, 202] features
4. Trained bmn model refer to [bmn config ](https://github.com/open-mmlab/mmaction2/tree/master/configs/localization/bmn)

---
Is there anything missing? Can you help me?  Or can you provide a complete bmn process on dataset，thank you very much.
Looking forward to your reply .

**Comment by kennymckormick** [comment]
82%+ is a poor result for TSN + UCF101. Maybe you can try ImageNet pertaining when you train the TSN.

**Comment by sean186** [comment]
Thank you for your reply. I have used model zoo [ ucf101 model](https://github.com/open-mmlab/mmaction2/tree/master/configs/recognition/tsn) only rgb model about (83.03 acc) and trained flow model, but the final precision is about the same.
Is there a problem with this process? I guess THUMOS'14 is an untrimmed video and a video has multiple actions of the same type of clip, so should time series dimension features be greater than 100? 
> 82%+ is a poor result for TSN + UCF101. Maybe you can try ImageNet or Kinetics pertaining when you train the TSN.

**Comment by kennymckormick** [comment]
Please check BMN's original paper:  https://arxiv.org/pdf/1907.09702.pdf. 
They said they use a recognition model pretrained on ActivityNet v1.3 (not UCF101) for THUMOS feature extraction.

**Comment by Juice-zz** [comment]
Extracted separately rgb and flow feature refer to [activitynet feature extraction](https://github.com/open-mmlab/mmaction2/tree/master/tools/data/activitynet#step-3-extract-rgb-and-flow) and rescaled tensor to [100, 101]，how you make it？can you tell me something about it
