### ISSUE TITLE
Could you share your Kinetics400 dataset?

### ISSUE THREAD

**Issue by LiuChaoXD** [open-mmlab/mmaction2#137]
I cannot download the Kinetics400 dataset. When I train your tsn model, it's hard to reproduce your released accuracy. I don't know the problem. Please, could you share your used kinetics400 data set?

**Comment by zhangluustb** [comment]
You can download kinetics400_tiny for experiment.

**Comment by innerlee** [comment]
We discussed the issue. Sorry to say this but there is no plan to host Kinetics400 in near future. Here is a list of datasets that are currently supported by openmmlab http://openmmlab.com/data.html

**Comment by yxchng** [comment]
@innerlee what is the reason for not releasing the dataset?
