### ISSUE TITLE
Reproduce STGCN

### ISSUE THREAD

**Issue by caidonkey** [open-mmlab/mmaction2#1371]
Thanks for your work!

I'm ongoing reproduce results using your released config file: **stgcn_80e_ntu60_xsub_keypoint.py** as follow:
**bash tools/dist_train.sh configs/skeleton/stgcn/stgcn_80e_ntu60_xsub_keypoint.py 2/4 --validate --seed 0 --deterministic**

And I obtained **85.68/85.66** Top-1 accuracy using 2/4 GPUs respectively, with around 1% performance gap with that in your model zoo.

I looked into your log file and found that you did not use "Distributed training" however using 2 GPUs for training. Would you kindly help check with the way you train your model zoo models? Is this config file corresponding to single GPU training? Thanks.

**Comment by kennymckormick** [comment]
@gengenkai

**Comment by caidonkey** [comment]
I also tried training using single GPU and obtained 86.06% Top-1 accuracy, which is still ~0.9% away from reported. Would you please kindly check the released config file? **stgcn_80e_ntu60_xsub_keypoint.py**

**Comment by gengenkai** [comment]
> to your log file and found that you did not use "Distributed training" however using 2 GPUs for training. Would you kindly help check with the way you train your model zoo models? Is this config file corresponding to single GPU trainin

I  used 'GPUS=2 tools/slurm_train.sh xxx' for the config file you mentioned, instead of single GPU training. Hope this helps you.

**Comment by caidonkey** [comment]
Thanks a lot! I'll try **slurm_train** to see if it can perfectly reproduce your performance.
