### ISSUE TITLE
what config and custom object detector are best for posec3d?

### ISSUE THREAD

**Issue by bit-scientist** [open-mmlab/mmaction2#1372]
Hi, @kennymckormick!
I need your expertise here.
I would like to replace the default human detector (`faster_rcnn_r50_fpn_2x_coco_bbox_mAP-0.384_20200504_210434-a5d8aa15.pth`) with a custom object detector which includes some objects of interest along with humans. Since the default human detector is from mmdetection and mmdet supports tons of models, what detector would you suggest to use that posec3d can support out of the box? The sole reason why I want to replace the human detector is that I have some other objects to detect and, additionally, I need a faster, more accurate detector. 

Do you happen to use any recent object detector nowadays?
What about human pose estimator? If there is more better one, recommend please.

As a note my dataset's objects are annotated as bbox (x,y,w,h) per frame. 

Appreciate your advice, thanks.

**Comment by kennymckormick** [comment]
The default detector is good enough for human detection (note that it is fine-tuned on human data only). If you also want detection results for general objects, you can pick a detector in mmdet that is trained on COCO (maybe still faster_rcnn). However, I think it can be difficult to find a **faster and more accurate detector**  (difficult to achieve both).
