### ISSUE TITLE
cuda10.0

### ISSUE THREAD

**Issue by shelly-xue** [open-mmlab/mmaction2#1374]
Before raising a question, you may need to check the following listed items.

thank you for your great work!

1. my cuda version==10.0,and can i use mmcv-full==1.4.2?
2. when i use mim install mmaction2 -f https://github.com/open-mmlab/mmaction2.git to install mmaction2, the error is:
      subprocess.CalledProcessError: Command '['python', '-m', 'pip', '--default-timeout', '45', 'install', 'mmcv-full==1.4.2', '-f', 
     'https://download.openmmlab.com/mmcv/dist/cu100130/torch1.2.0/index.html']' returned non-zero exit status 1.
besides, cuda==10.0, pytorch==1.2, python==3.7

thanks very much

**Comment by kennymckormick** [comment]
Probably, but we recommend you to upgrade your cuda. Cuda 10.0 is a relatively old version: the latest pre-built PyTorch wheel for cuda 10.0 is torch 1.2.0, while mmcv provides no pre-built wheel for cuda 10.0. You can try to build mmcv from source, but upgrading ur cuda might be a better solution.

**Comment by shelly-xue** [comment]
@kennymckormick ok,thank you very much. when i change my custom video to posec3d skeleton format,i see "generate 2D pose annotations for a single video, first, you need to install **mmdetection** and **mmpose** from src code." in readme.txt .so how do i install mmdection and mmpose? i didnt find the corresponding tutorial.thank you!

**Comment by kennymckormick** [comment]
Hi, shelly, you can clone both codebases to local and execute `pip install -e .` in each codebase. For more details, you can refer to the documentations in https://github.com/open-mmlab/mmpose/ or https://github.com/open-mmlab/mmdetection.
