### ISSUE TITLE
Questions about SampleFrames class in pipelines/loading.py

### ISSUE THREAD

**Issue by luigidamico100** [open-mmlab/mmaction2#1379]
I have some more question about the class [SampleFrames](https://github.com/open-mmlab/mmaction2/blob/0dde60b56317b1133ac1adfee051374888efffc7/mmaction/datasets/pipelines/loading.py#L82-L270)

1. If I understood well, [Here](https://github.com/open-mmlab/mmaction2/issues/1204#issuecomment-933201553)  @ingbeeedd says that the video frames are mixed up randomly but I can't see it in the code, moreover I cannot find a conceptual explanation of doing this. If so, there is an easy way to take a number of `clip_len` ordered frames?
2. At the end of the day, I would like to take `clip_len` ordered non-cyclic frames. For example if I got a video composed of 10 frames and `clip_len=6`, the starting index should start randomly from 0 to 4 and the last index frame should be between 5 and 9. 
3. May you provide me a better explanation of `num_clips` parameter? At the moment my interpretation of this parameter is the **batch size**, so I cannot get any difference w.r.t. the `videos_per_gpu` param in the config file.  

Thanks!!

**Comment by dreamerlin** [comment]
1. In `SampleFrames`, video frames are not mixed up randomly (refer to https://github.com/open-mmlab/mmaction2/blob/master/mmaction/datasets/pipelines/loading.py#L163)
2. You can try to use the setting like https://github.com/open-mmlab/mmaction2/blob/master/configs/recognition/tsn/tsn_r50_1x1x3_100e_kinetics400_rgb.py#L16
3. `num_clips` != `videos_per_gpu`. `num_clips` means the sampled clips in each video and `videos_per_gpu` means the number of videos in each gpu, and the `batch_size` = `videos_per_gpu` x GPU number

**Comment by luigidamico100** [comment]
3. Ok! So I didn't get the meaning of a _clip_. So... for each video, `nun_clips` clips are sampled, it is right?
2. If my point 3. is correct, I should use `dict(type='SampleFrames', clip_len=3, frame_interval=1, num_clips=1), ` because I need one clip for each video and every clip should be composed of `clip_len` frames.

**Comment by dreamerlin** [comment]
I think `dict(type='SampleFrames', clip_len=1, frame_interval=1, num_clips=6)` is better, this is the TSN pattern, a sparse sampling strategy. And another commonly used strategy is a slide-window pattern as  `dict(type='SampleFrames', clip_len=6, frame_interval=1, num_clips=1)`. In short,

1. For TSN, it uniformly divide a video into `num_clip` segments, and randomly sample one frame in each segment.
2. For slide-window, it creates `num_clip` slide-winodw whose length is `clip_len x frame_interval` and for each slide-window it sample `clip_len ` frames in a interval striding with `frame_interval` frames.
