### ISSUE TITLE
Is Faster RCNN fined-tuned on AVA available?

### ISSUE THREAD

**Issue by Xingyu-Jin** [open-mmlab/mmaction2#1380]
Hi thanks for the work!
I wonder how the dense proposal file in spatial temporal action detection (ava) is created? Is it just bboxes from fasterrcnn?

**Comment by dreamerlin** [comment]
@kennymckormick

**Comment by kennymckormick** [comment]
The proposals are just bboxes from faster-rcnn. 
The Faster RCNN fined-tuned on AVA is not available, we directly use the proposal pickle files released by FAIR.
