### ISSUE TITLE
Which version of CUDA and cuda toolkit for RTX 3080? 

### ISSUE THREAD

**Issue by bit-scientist** [open-mmlab/mmaction2#1383]
It is said that the project works well with CUDA +9.2 (9.0). And the laptop I got is equipped with RTX 3080

![image](https://user-images.githubusercontent.com/26497571/149291523-3d0e3391-a16c-4f06-9a79-b10ad71c580f.png)

Also, I have got a wsl to work under linux OS. `lsb_release -a` outputs:
```
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.5 LTS
Release:        18.04
Codename:       bionic
```
and `nvidia-smi` prints the following:
```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 511.04.01    Driver Version: 511.09       CUDA Version: 11.6     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ...  On   | 00000000:01:00.0  On |                  N/A |
| N/A   36C    P8    14W /  N/A |    585MiB / 16384MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+ 
```
I tried to go with a CUDA version of 10.1, but it turns out that my GPU is *too new* for this version. 
So here come the question:

What is the latest stable version of CUDA and all cuda related libraries that I can use with this GPU in order to successfully install this repo?
When I run `pip install mmcv-full -f https://download.openmmlab.com/mmcv/dist/cu111/torch1.7.0/index.html` it continuously downloads mmcv-full-1.4.2.tar.gz , gives error and downloads one version down and so on.

I have been trying to set the repo up for quite a while now. Help is much appreciated. Thanks.

**Comment by kennymckormick** [comment]
First, if you want to use pytorch-gpu in wsl (assume you are on a windows machine), you need to install the nvidia-driver for wsl on windows.  
I guess you can try cuda 11.3 (it should be ok) or cuda 10.2 (Maybe 3080 doesn't work with cuda 10.2, idk), both PyTorch and mmcv provide prebuilt wheels for this cuda version. To install PyTorch with a specific cuda version, follow the instructions on https://pytorch.org/get-started/locally/

**Comment by kennymckormick** [comment]
Yes, I have succeeded installing mmaction on windows. Just use anaconda and the mmcv pre-build wheels for windows.
