### ISSUE TITLE
Freezing layers of I3D

### ISSUE THREAD

**Issue by devloper13** [open-mmlab/mmaction2#1385]
I am working with I3D and was wondering how to freeze the layers (weights) of I3D to finetune? 

I was suggested this https://github.com/open-mmlab/mmaction2/blob/master/mmaction/models/backbones/resnet.py#L344 but this for backbone, correct? I want to freeze the entire weights of pretrained weight (kinetics-400), except of course the last layer.

**Comment by dreamerlin** [comment]
Try this  https://github.com/open-mmlab/mmaction2/blob/master/docs/tutorials/2_finetune.md

**Comment by devloper13** [comment]
I did. Can you be a bit more specific? I read through the tutorials but haven't figured out how to freeze the layesrs. Or to put differently, train only the last layer of I3D.

**Comment by dreamerlin** [comment]
1. If you mean the last layer of the whole I3D recognizer, just set `frozen_stages=4` since the only layer with trainable parameters in Head is an FC layer.
2. If you mean the last layer of the I3D backbone, set `frozen_stages=3`

**Comment by devloper13** [comment]
Thanks. It will be great if you can explain what different frozen layers do. I'm having a hard time understanding. Usually when we code in pytorch or tensorflow we can control each layer of any large model to set as trainable or not. Is it the same here?

**Comment by dreamerlin** [comment]
Our code is based on PyTorch and for a more specific layer control, you can write a new module or change the optimizer setting like https://github.com/open-mmlab/mmaction2/blob/master/mmaction/core/optimizer/tsm_optimizer_constructor.py

**Comment by hirunima** [comment]
Both links are unavailable
