### ISSUE TITLE
not able run demo on docker container

### ISSUE THREAD

**Issue by bit-scientist** [open-mmlab/mmaction2#1396]
I have got a laptop which has RTX 3080 GPU. I managed to build an image with:
```
ARG PYTORCH="1.8.0"
ARG CUDA="11.1"
ARG CUDNN="8"

FROM pytorch/pytorch:${PYTORCH}-cuda${CUDA}-cudnn${CUDNN}-devel

ENV TORCH_CUDA_ARCH_LIST="6.0 6.1 7.0+PTX"
ENV TORCH_NVCC_FLAGS="-Xfatbin -compress-all"
ENV CMAKE_PREFIX_PATH="$(dirname $(which conda))/../"

RUN apt-get update && apt-get install -y git ninja-build libglib2.0-0 libsm6 libxrender-dev libxext6 ffmpeg \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Install mmcv-full
RUN pip install mmcv-full==1.3.9 -f https://download.openmmlab.com/mmcv/dist/cu111/torch1.8.0/index.html

# Install MMAction2
RUN conda clean --all
RUN git clone https://github.com/open-mmlab/mmaction2.git /mmaction2
WORKDIR /mmaction2
RUN mkdir -p /mmaction2/data
ENV FORCE_CUDA="1"
RUN pip install cython --no-cache-dir
RUN pip install --no-cache-dir -e .
```

Then I run:
`docker run --gpus all --shm-size=20g -it -v data:/mmaction2/data sb` which created `sb` container.
I verified the container with the following commands:
```

python
Python 3.8.8 (default, Feb 24 2021, 21:46:12)
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> print("Torch version: ",  torch.__version__)
Torch version:  1.8.0
>>> print("cuda version: " ,torch.version.cuda)
cuda version:  11.1
>>> print("cuda available: ", torch.cuda.is_available())
cuda available:  True
>>> from mmaction.apis import init_recognizer, inference_recognizer
>>> config_file = 'configs/recognition/tsn/tsn_r50_video_inference_1x1x3_100e_kinetics400_rgb.py'
>>> device = 'cuda:0'
>>> device = torch.device(device)
>>> model = init_recognizer(config_file, device=device)
>>> inference_recognizer(model, 'demo/demo.mp4')
[(2, 52.539494), (371, 44.24797), (186, 43.864273), (299, 43.72553), (55, 38.972267)]
```

So there was no issue at all. However, when I run 
`python demo/demo_posec3d.py data/demo --config configs/skeleton/posec3d/2class_v.py --checkpoint epoch_950.pth  --label-map tools/data/skeleton/2class_v_posec3d.txt` where `data/demo` is a folder with videos, `2class_v.py` is a config file and so on (I can run this very script in ubuntu server without any issue).

It outputs:
```
Traceback (most recent call last):
  File "demo/demo_posec3d.py", line 320, in <module>
    main()
  File "demo/demo_posec3d.py", line 216, in main
    det_results = detection_inference(args, frame_paths)
  File "demo/demo_posec3d.py", line 160, in detection_inference
    model = init_detector(args.det_config, args.det_checkpoint, args.device)
  File "/mmaction2/mmaction/utils/decorators.py", line 12, in new_func
    raise ImportError(
ImportError: Please install mmdet to use init_detector. For OpenMMLAB codebases, you may need to install mmcv-full first before you install the particular codebase.
```
How is it possible even after verification? mmcv-full, mmdet, mmcv are all installed:

```
mmaction2              0.21.0              /mmaction2
mmcv                   1.3.17
mmcv-full              1.4.0
mmdet                  2.19.0
moviepy                1.0.3
```
  NOTE: I had to reinstall some packages like torch, torchvision, mm-packages after the initial `mmdet error`, therefore it might be different than the docker file.

**Comment by bit-scientist** [comment]
@kennymckormick, sorry for urgency, could you help me out?

**Comment by rlleshi** [comment]
Not sure if this is the problem but `mmdet` was breaking things couple of months ago. 
I used `mmcv-full==1.3.15` and pip installed `mmdet 2.12.0`. Just try to install mmdet with pip to this particular version once?

**Comment by kennymckormick** [comment]
Sorry, we have not supported demo_posec3d in our Dockerfile, but you may achieve this by manually installing the required packages in docker. 

This message indicates we can not import sth. from mmdet successfully. For debugging, you can try to find a way to successfully run the following import statements:

```python
from mmdet.apis import inference_detector, init_detector
from mmpose.apis import init_pose_model, inference_top_down_pose_model, vis_pose_result

```

**Comment by bit-scientist** [comment]
Thank you, @kennymckormick, I have managed to resolve the issues.
Here are my steps on Win 11, assuming you have docker desktop installed: 
1. Go to project's folder *mmaction2* and enter command prompt (win key, type `cmd`)
2. In *docker* folder, make a copy of  Dockerfile and name it *custom_dockerfile* and change the content inside with below and save it:
```
ARG PYTORCH="1.8.0"
ARG CUDA="11.1"
ARG CUDNN="8"

FROM pytorch/pytorch:${PYTORCH}-cuda${CUDA}-cudnn${CUDNN}-devel

ENV TORCH_CUDA_ARCH_LIST="6.0 6.1 7.0+PTX"
ENV TORCH_NVCC_FLAGS="-Xfatbin -compress-all"
ENV CMAKE_PREFIX_PATH="$(dirname $(which conda))/../"

RUN apt-get update && apt-get install -y git ninja-build libglib2.0-0 libsm6 libxrender-dev libxext6 ffmpeg \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Install mmcv-full
RUN pip install mmcv-full==1.3.13 -f https://download.openmmlab.com/mmcv/dist/cu111/torch1.8.0/index.html

# Install MMAction2
RUN conda clean --all
RUN git clone https://github.com/open-mmlab/mmaction2.git /mmaction2
WORKDIR /mmaction2
RUN mkdir -p /mmaction2/data
ENV FORCE_CUDA="1"
RUN pip install moviepy
RUN pip install openmim
RUN mim install mmdet
RUN pip install cython --no-cache-dir
RUN pip install --no-cache-dir -e .
```
2. Go to your cmd (that of step 1) and  run `docker build -f ./docker/custom_dockerfile --rm -t mmaction2 .` This builds mmaction2 docker image with necessary dependencies including CUDA, cudnn, etc.
3. Then run `docker run --gpus all --shm-size=8g -it --name {CONTAINER_NAME} -v {DATA_DIR}:/mmaction2/data mmaction2`. Here, {CONTAINER_NAME} should be replaced with the desired container name and `{DATA_DIR}` should be `data`. For. ex: `docker run --gpus all --shm-size=8g -it --name posec3d_container -v data:/mmaction2/data mmaction2`. This should create `posec3d_container ` container and change the console to something like `root@8462f841w2qa#`
4. You are in the container, now run `python` to do some checking.
5. Run the following:
```
import torch
print("Torch version: ", torch.__version__)
print("cuda version: " ,torch.version.cuda)
print("cuda available: ", torch.cuda.is_available())
```
This should print out your torch and cuda versions, and whether cuda is available, respectively.
Here you may get some errors, you should tackle them all and repeat the steps again until you succeed.

6. When you run demo files, you may have errors like `ImportError: Please install mmdet to use init_detector. For OpenMMLAB codebases, you may need to install mmcv-full first before you install the particular codebase.` At this stage you enter python and try running the scripts as @kennymckormick recommended:

> `from mmdet.apis import inference_detector, init_detector`
> `from mmpose.apis import init_pose_model, inference_top_down_pose_model, vis_pose_result`

7. Resolve debugging issues of the above commands (if any) by installing packages of certain version and repeat step 6 until you succeed. That's pretty much it.
