### ISSUE TITLE
Run demo.py got Segmentation fault (core dumped) error

### ISSUE THREAD

**Issue by Ce-ZHANG** [open-mmlab/mmaction2#1399]
**Checklist**

1. I have searched related issues but cannot get the expected help.
2. The bug has not been fixed in the latest version.

**The Error**

I have installed everything inside the "Requirements" and mmAction2 step by step.
Howere, when I was testing the video demo section 4 "Recognize a video file as input by using a TSN model and then generate an mp4 file", I've got an error, said Segmentation fault (core dumped), I dont know why, And I have tried several others, same error.

**Reproduction**

The extractly command I have runned.
```
python3 demo/demo.py configs/recognition/tsn/tsn_r50_video_inference_1x1x3_100e_kinetics400_rgb.py \
    checkpoints/tsn_r50_1x1x3_100e_kinetics400_rgb_20200614-e508be42.pth \
    demo/demo.mp4 tools/data/kinetics/label_map_k400.txt --out-filename demo/demo_out.mp4
```

**Environment**

The Env I have on my PC:
```
sys.platform: linux
Python: 3.9.7 (default, Sep 16 2021, 13:09:58) [GCC 7.5.0]
CUDA available: True
GPU 0: NVIDIA GeForce RTX 2080 Ti   (12 GiB)
CUDA_HOME: /usr/local/cuda-11.3
NVCC: Build cuda_11.3.r11.3/compiler.29920130_0
GCC: gcc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
PyTorch: 1.10.1
PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) oneAPI Math Kernel Library Version 2021.4-Product Build 20210904 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.2.3 (Git Hash 7336ca9f055cf1bfa13efb658fe15dc9b41f0740)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - LAPACK is enabled (usually provided by MKL)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 11.3
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86;-gencode;arch=compute_37,code=compute_37
  - CuDNN 8.2
  - Magma 2.5.2
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.3, CUDNN_VERSION=8.2.0, CXX_COMPILER=/opt/rh/devtoolset-7/root/usr/bin/c++, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -DEDGE_PROFILER_USE_KINETO -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.10.1, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, 

TorchVision: 0.11.2
OpenCV: 4.5.5
MMCV: 1.4.3
MMCV Compiler: GCC 7.3
MMCV CUDA Compiler: 11.3
MMAction2: 0.21.0+0dde60b
```

**Error traceback**

Saidly, the error is just one line, no much details.

```
load checkpoint from local path: checkpoints/tsn/tsn_r50_1x1x3_100e_kinetics400_rgb_20200614-e508be42.pth
Segmentation fault (core dumped)
```

This error has driven me crazy. I could really use some help, even if just some hints still very grateful!!
Thanks in advance!!

**Comment by kennymckormick** [comment]
It's not possible to debug with only this information. Maybe you can try to use "print" debug to find out at which specific line the segmentation fault happens.

**Comment by Ce-ZHANG** [comment]
> It's not possible to debug with only this information. Maybe you can try to use "print" debug to find out at which specific line the segmentation fault happens.

Right, sorry, first add issue here. But anyway, I accidentally figured it out. The version of y python is way too high (py39) which lead to conflict dependencies. When I changed it back to py36, everything seems all right.

**Comment by kennymckormick** [comment]
> > It's not possible to debug with only this information. Maybe you can try to use "print" debug to find out at which specific line the segmentation fault happens.
> 
> Right, sorry, first add issue here. But anyway, I accidentally figured it out. The version of y python is way too high (py39) which lead to conflict dependencies. When I changed it back to py36, everything seems all right.

OK, we will check if this codebase works for new python versions like 3.9, thanks for your information~

**Comment by tuandoan998** [comment]
I got the same error as you when using different models like C3D, Slowonly, TSN.
I noticed an error occurred when run [model.to(device`](https://github.com/open-mmlab/mmaction2/blob/5e09bd849d844a0f64f9866cd4f26f00e56c0086/mmaction/apis/inference.py#L51).
I am using python 3.8 and tried to install many different environments and all get the same error. I'll use python==3.6 and see how it goes.

**Comment by tuandoan998** [comment]
Still got the same error.
I can run [demo_skeleton.py](https://github.com/open-mmlab/mmaction2/blob/master/demo/demo_skeleton.py) or [demo_spatiotemporal_det.py](https://github.com/open-mmlab/mmaction2/blob/master/demo/demo_spatiotemporal_det.py) normally with CUDA. But can not run [demo.py](https://github.com/open-mmlab/mmaction2/blob/master/demo/demo.py) with CUDA, with CPU it's fine.

**Comment by tuandoan998** [comment]
If I comment [line 7](https://github.com/open-mmlab/mmaction2/blob/5e09bd849d844a0f64f9866cd4f26f00e56c0086/demo/demo.py#L7), model can run normally.

**Comment by anjaeju** [comment]
@Bigwhitepear Appreciate it. This worked for me on Python 3.8, Pytorch 1.10
