### ISSUE TITLE
Denseflow - no kernel image is available for execution on the device in function 'call'

### ISSUE THREAD

**Issue by JXIONG008** [open-mmlab/mmaction2#1400]
Thanks for your error report and we appreciate it a lot.
If you feel we have help you, give us a STAR! :satisfied:

**Checklist**

1. I have searched related issues but cannot get the expected help.
2. The bug has not been fixed in the latest version.

**Describe the bug**

**Reproduction**

1. What command or script did you run?

```
bash extract_frames.sh 
```

2. Did you make any modifications on the code or config? Did you understand what you have modified?
No.
3. What dataset did you use?
UCF101

**Environment**

1. Please run `PYTHONPATH=${PWD}:$PYTHONPATH python mmaction/utils/collect_env.py` to collect necessary environment information and paste it here.
sys.platform: linux
Python: 3.8.12 (default, Oct 12 2021, 13:49:34) [GCC 7.5.0]
CUDA available: True
GPU 0,1,2: NVIDIA GeForce RTX 3090
CUDA_HOME: /usr/local/cuda
NVCC: Build cuda_11.3.r11.3/compiler.29745058_0
GCC: gcc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
PyTorch: 1.10.1+cu113
PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2020.0.0 Product Build 20191122 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.2.3 (Git Hash 7336ca9f055cf1bfa13efb658fe15dc9b41f0740)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - LAPACK is enabled (usually provided by MKL)
  - NNPACK is enabled
  - CPU capability usage: AVX512
  - CUDA Runtime 11.3
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86
  - CuDNN 8.2
  - Magma 2.5.2
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.3, CUDNN_VERSION=8.2.0, CXX_COMPILER=/opt/rh/devtoolset-7/root/usr/bin/c++, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -DEDGE_PROFILER_USE_KINETO -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.10.1, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, 

TorchVision: 0.11.2+cu113
OpenCV: 4.5.5
MMCV: 1.4.2
MMCV Compiler: GCC 9.3
MMCV CUDA Compiler: 11.3
MMAction2: 0.21.0+6ec1af7

2. You may add addition that may be helpful for locating the problem, such as
- I have installed open-cv as follow:

Name: opencv-python
Version: 4.5.5.62
Summary: Wrapper package for OpenCV python bindings.
Home-page: https://github.com/skvark/opencv-python
Author: 
Author-email: 
License: MIT
Location: /home/fyp/anaconda3/envs/open-mmlab/lib/python3.8/site-packages
Requires: numpy, numpy
Required-by: mmcv-full

**Error traceback**

If applicable, paste the error traceback here.

```
extracted frames of video "../../data/ucf101/videos/PlayingDaf/v_PlayingDaf_g15_c03.avi", 365 frames
1 videos (365 frames, 0 tvl1 flows) processed, using 0.608s, decoding speed 600.329fps, flow speed 0fps
"../../data/ucf101/videos/Rafting/v_Rafting_g11_c03.avi", frames ≈ 268
Aborted (core dumped)
both 419 SumoWrestling/v_SumoWrestling_g19_c02.avi tvl1 got something wrong
"../../data/ucf101/videos/PushUps/v_PushUps_g16_c04.avi", frames ≈ 29
Aborted (core dumped)
both 2504 BrushingTeeth/v_BrushingTeeth_g14_c05.avi tvl1 got something wrong
"../../data/ucf101/videos/Hammering/v_Hammering_g21_c05.avi", frames ≈ 150
extracted frames of video "../../data/ucf101/videos/PushUps/v_PushUps_g16_c04.avi", 29 frames
1 videos (29 frames, 0 tvl1 flows) processed, using 0.052s, decoding speed 557.692fps, flow speed 0fps
push frames gray, video_flow_idx 0, batch_size 268
loaded video "../../data/ucf101/videos/Rafting/v_Rafting_g11_c03.avi", 268 frames
load frames exit.
terminate called after throwing an instance of 'cv::Exception'
  what():  OpenCV(4.5.2) /home/fyp/FYP/opencv_contrib-4.5.2/modules/cudev/include/opencv2/cudev/grid/detail/transform.hpp:312: error: (-217:Gpu API call) no kernel image is available for execution on the device in function 'call'
```

**Bug fix**

If you have already identified the reason, you can provide the information here. If you are willing to create a PR to fix it, please also leave a comment here and that would be much appreciated!

**Comment by kennymckormick** [comment]
First, according to my experience, it's not easy to install denseflow. If you do not need flow modality, a better choice is to use FFmpeg for frame extraction. 

If you want to use denseflow, please first check these items: 
1.  If you install the denseflow hold by open-mmlab (https://github.com/open-mmlab/denseflow)? The answer should be Yes.
2. Do you strictly follow the instruction in https://github.com/open-mmlab/denseflow/blob/master/INSTALL.md (You need to install packages like OpenCV manually, so you can find it when compiling denseflow, opencv-python doesn't work. )? The answer should be Yes. 

If you answer Yes in both questions, you can raise an issue under https://github.com/open-mmlab/denseflow, @innerlee is more familiar with that software, maybe he can help you with your question.
