### ISSUE TITLE
SlowFast predicting a particular class by default

### ISSUE THREAD

**Issue by MrOCW** [open-mmlab/mmaction2#1401]
Hi,

I have trained a slowfast model with 13 classes. top 1 accuracy on an imbalanced val set (with 49 class X / 58 val data = 0.84) is 0.98 > 0.84
which means the model is not predicting class X for everything.

However, when running inference in real-time, if the person is not performing any of the 13 classes, the model defaults to predicting class X with about 0.6~0.8 probability. Any tips on debugging this?
[slowfast_prebn_r50_4x16x1_256e_kinetics400_rgb.txt](https://github.com/open-mmlab/mmaction2/files/7911019/slowfast_prebn_r50_4x16x1_256e_kinetics400_rgb.txt)

Also, may I know how exactly does the drawing_fps and inference_fps in webcam_demo.py work in simple explanation? Thanks!

**Comment by kennymckormick** [comment]
I didn't understand your question 1. Would you please describe the problem and your training/validation class statistics in detail? 

For question 2, we predict a result `inference_fps` times per second and flush the visualized results `draw_fps` times per second.
