### ISSUE TITLE
Does PoseC3D model support RGBPose-SlowFast from the paper?

### ISSUE THREAD

**Issue by FarzanehAskari** [open-mmlab/mmaction2#1402]
I was wondering if the current version of PoseC3D supports the RGBPose-SlowFast from the paper or only Pose_slowonly? Thank you.

**Comment by kennymckormick** [comment]
Current Implementation only supports Pose-SlowOnly, the rest part of the PoseC3D project (RGBPose-SlowFast & PoseC3D + Kinetics) will be released after the paper gets published.

**Comment by kennymckormick** [comment]
A duplicated issue of #1221 .
