### ISSUE TITLE
some questions about feature extraction

### ISSUE THREAD

**Issue by kkdd0717** [open-mmlab/mmaction2#1403]
First of all, thank you very much for your work.

I want to know what I should do when I want to extract the 521 dimensional feature vector in front of the full connection layer in neural network posec3d.

I checked the commentary on this part:  https://github.com/open-mmlab/mmaction2/blob/master/docs/feature_extraction.md, but I didn't find a clue.

I hope my problem can be solved.thanks.

**Comment by kkdd0717** [comment]
I tried to set test_cfg=dict(feature_extraction=True) in the "slowonly_r50_u48_240e_ntu60_xsub_keypoint.py" when testing the model, but it didn't seem to work. I didn't find the corresponding output feature.

**Comment by kennymckormick** [comment]
If you set the `--out` flag in testing, the output filename will be the same as the value you set.
