### ISSUE TITLE
NameError: name 'Inference_recognizer' is not defined

### ISSUE THREAD

**Issue by nyanmn** [open-mmlab/mmaction2#1413]
Followed all installation instruction [here ](https://mmaction2.readthedocs.io/en/latest/install.html).
Installed versions are
`pytorch1.7.0, mmcv=1.4, Centos7`

mmaction2 installation follows manual installation like
```
git clone https://github.com/open-mmlab/mmaction2.git
cd mmaction2
pip install -r requirements/build.txt
pip install -v -e .  # or "python setup.py develop"
```

When I run test program,

```
import torch
from mmaction.apis import init_recognizer, inference_recognizer

config_file = 'configs/recognition/tsn/tsn_r50_video_inference_1x1x3_100e_kinetics400_rgb.py'
device = 'cuda:0' # or 'cpu'
device = torch.device(device)

model = init_recognizer(config_file, device=device)
# inference the demo video
inference_recognizer(model, 'demo/demo.mp4')
```

The error is 
`NameError: name 'Inference_recognizer' is not defined`

What could be worng?

**Comment by kennymckormick** [comment]
It should be `inference_recognizer`, make sure you are not using `Inference_recognizer` (as ur error msg). 

Generally, If you can not import the API, it usually means you have not really installed mmaction. 
You can try to `import mmaction` in a random directory to check if you have successfully installed mmaction.

**Comment by nyanmn** [comment]
Pls see in the attached link

https://www.dropbox.com/s/jtqbr8ryc2djj4n/mmaction.png?dl=0

I can `import mmaction` 

So what could be issue?

**Comment by nyanmn** [comment]
Sorry my mistake. It is inference_recognizer

**Comment by kennymckormick** [comment]
OK~
