### ISSUE TITLE
Extremely slow Training Time w/ STGCN

### ISSUE THREAD

**Issue by FraLuca** [open-mmlab/mmaction2#1417]
Hi,

I'm one of the authors of [STSGCN](https://fraluca.github.io/), a model released at ICCV'21 for Human Pose Forecasting. I would like to implement our model into your framework!
I started from the code of STGCN but I'm having some problems. I tried to reproduce STGCN results on the NTU60 dataset but the training is extremely slow. 
Even though the model is particularly light, It takes a few days to train on 2 Nvidia Quadro P6000.  
This seems to be due to the backward pass in the optimizer hook (it takes few seconds at each iteration).
Moreover, increasing video_per_gpu or worker_per_gpu parameters in the config file results in the same training time.
Do you have suggestions to solve this problem?

I appreciate your help,
Luca

**Comment by kennymckormick** [comment]
Thanks a lot for this contribution. 
For reference, it takes ~20 hours to train ST-GCN (w. 3D keypoints) on a single 1080Ti GPU. I'm not familiar with the performance of P6000 (maybe it is for CG, not deep learning? ). Perhaps you can first make sure that you are actually using GPUs for training. Then if it is still slow, you can try some other GPUs.
