### ISSUE TITLE
demo_spatiotemporal_det.py produced output video with only one frame

### ISSUE THREAD

**Issue by nyanmn** [open-mmlab/mmaction2#1422]
I am testing actor centric action recognition model with a video.
My test command is 

`python demo/demo_spatiotemporal_det.py --config configs/detection/acrn/slowfast_acrn_kinetics_pretrained_r50_8x8x1_cosine_10e_ava22_rgb.py --checkpoint work_dirs/slowfast_acrn_kinetics_pretrained_r50_8x8x1_cosine_10e_ava22_rgb/latest.pth --video data/ava/videos/IzvOYVMltkI.mp4 --det-config demo/faster_rcnn_r50_fpn_2x_coco.py --det-checkpoint http://download.openmmlab.com/mmdetection/v2.0/faster_rcnn/faster_rcnn_r50_fpn_2x_coco/faster_rcnn_r50_fpn_2x_coco_bbox_mAP-0.384_20200504_210434-a5d8aa15.pth --det-score-thr 0.9 --action-score-thr 0.5 --label-map tools/data/ava/label_map.txt --predict-stepsize 8 --output-stepsize 4 --device cuda:4 --out-filename data/ava/output/out.mp4
`

Output video is as long as the input video but has only the first frame of input video.
What could be wrong?

**Comment by kennymckormick** [comment]
It's weird. Can you upload the video you used and we will try to reproduce the bug.

**Comment by kennymckormick** [comment]
Would you please try a different player? I played your `out.mp4` and did not find anything abnormal. The content is just like your input video.

**Comment by nyanmn** [comment]
What player do you use? I tried in linux machine with Videos player. In Windows with VLC Media player. Neither works.

**Comment by nyanmn** [comment]
Sorry I can use VLC Media player. But video is not smooth. Still for some time and still again. Not like test video.

**Comment by kennymckormick** [comment]
Hi, @nyanmn ,to get a smooth output video, you may need to set `--predict-stepsize 1 --output-stepsize 1`. However, this is not the default practice, since it takes much more computations (8x).

**Comment by nyanmn** [comment]
You mean `--predict-stepsize 1 --output-stepsize 1` are needed in testing or in training?

**Comment by nyanmn** [comment]
So how to run life from webcam? Will be staggered in display?

**Comment by nyanmn** [comment]
thanks for your discussion. I'll test with webcam. We can close this discussion.

**Comment by Xinxinatg** [comment]
> test video, output video and my trained model can be downloaded from [here](https://www.dropbox.com/s/sf7gq94hgo100ay/Desktop.zip?dl=0).
> 
> The command used is
> 
> `python demo/demo_spatiotemporal_det.py --config configs/detection/acrn/slowfast_acrn_kinetics_pretrained_r50_8x8x1_cosine_10e_ava22_rgb.py --checkpoint work_dirs/slowfast_acrn_kinetics_pretrained_r50_8x8x1_cosine_10e_ava22_rgb/latest.pth --video data/ava/videos_15min/Rm518TUhbRY.mkv --det-config demo/faster_rcnn_r50_fpn_2x_coco.py --det-checkpoint http://download.openmmlab.com/mmdetection/v2.0/faster_rcnn/faster_rcnn_r50_fpn_2x_coco/faster_rcnn_r50_fpn_2x_coco_bbox_mAP-0.384_20200504_210434-a5d8aa15.pth --det-score-thr 0.9 --action-score-thr 0.5 --label-map tools/data/ava/label_map.txt --predict-stepsize 8 --output-stepsize 4 --device cuda:4 --out-filename data/ava/output/out.mp4`

Hi may I know which kind of dataset was your model trained on? like the label type and the size of the dataset
