### ISSUE TITLE
ACRN and AVA action detection algorithms

### ISSUE THREAD

**Issue by nyanmn** [open-mmlab/mmaction2#1423]
I look at two methods ACRN and AVA. According to config files, both of them are same.
Can highlight me what is the difference in implementation for the two algorithms?

**Comment by kennymckormick** [comment]
In ACRN, a shared head is adopted to fuse RoI feature with context feature. 
```python
shared_head=dict(type='ACRNHead', in_channels=4608, out_channels=2304),
```

**Comment by nyanmn** [comment]
Thanks for clairfication.
