### ISSUE TITLE
Adding customized action to AVA dataset

### ISSUE THREAD

**Issue by nyanmn** [open-mmlab/mmaction2#1427]
I am trying to add own customized action to AVA dataset.
Looked at train/val list of actions at ava_train_v2.1.csv and ava_val_v2.1.csv, the text format has 8 columns.
Video name, time stamp, bounding boxes (four columns), column7, column8

```
-5KQ66BBWC4,0902,0.077,0.151,0.283,0.811,80,1
-5KQ66BBWC4,0902,0.077,0.151,0.283,0.811,9,1
-5KQ66BBWC4,0902,0.226,0.032,0.366,0.497,12,0
-5KQ66BBWC4,0902,0.226,0.032,0.366,0.497,17,0
```

My queries are
(1)time stamp is starting time instance of action in clip?
time stamps are listed in `ava_included_timestamps_v2.1.txt
`
(2)column-7 is action name listed in `ava_action_list_v2.1.pbtxt?`
(3) What is column-8 for?
(4)What is the purpose of ava_dense_proposals_train.FAIR.recall_93.9.pkl? For new action, do i need to include into the file?
Can someone explain?

**Comment by nyanmn** [comment]
Now understood.
(1)Original video is converted to 30fps video for 15min interval
(2)Annotation is done with 1fps
(3)timestamp_start at 900.
So time stamp 0902 means (902-900)*30fps = img_00060.jpg
(4)Another four columns are bounding boxes of a person
(5)7th column is action id listed in ava_action_list_v2.1.pbtxt
(6)8th column is person id in the 15min clip

**Comment by kennymckormick** [comment]
Great, seems you already got it~
