### ISSUE TITLE
How do I download checkpoints? I didn't find such a link.

### ISSUE THREAD

**Issue by TIMAX-159** [open-mmlab/mmaction2#1428]
Before raising a question, you may need to check the following listed items.

**Checklist**

1. I have searched related issues but cannot get the expected help.
2. I have read the [FAQ documentation](https://mmaction2.readthedocs.io/en/latest/faq.html) but cannot get the expected help.

**Comment by dreamerlin** [comment]
in config README, like https://github.com/open-mmlab/mmaction2/tree/master/configs/recognition/tsn
