### ISSUE TITLE
How to combine single pkl file?

### ISSUE THREAD

**Issue by vasanth4224** [open-mmlab/mmaction2#1431]
hi, I am going to do poseC3D training, before training I have to make single pkl file. anyone please help me, how to make single pkl files?

Custom Dataset Training with PoseC3D

Then, you will "collect all the pickle files into one list for training (and, of course, for validation) and save them as a single file" (like custom_dataset_train.pkl or custom_dataset_val.pkl). At that time, you finalize preparing annotation files for your custom dataset.

**Comment by rlleshi** [comment]
Just combine the single `.pkl` dicts for each video into a list of dicts and save this as a `.pkl` file. Sth like:

```
result = []
    for d in os.listdir(path):
        if d.endswith('.pkl'):
            with open(osp.join(path, d), 'rb') as f:
                content = pickle.load(f)
        result.append(content)
    with open('result.pkl', 'wb') as out:
        pickle.dump(result, out, protocol=pickle.HIGHEST_PROTOCOL)
```

**Comment by kennymckormick** [comment]
You can just follow the instructions from @rlleshi ~
