### ISSUE TITLE
ava_dense_proposals_train.FAIR.recall_93.9.pkl?

### ISSUE THREAD

**Issue by gurkirt** [open-mmlab/mmaction2#1435]
Before raising a question, you may need to check the following listed items.

**Checklist**

1. I have searched related issues but cannot get the expected help.
2. I have read the [FAQ documentation](https://mmaction2.readthedocs.io/en/latest/faq.html) but cannot get the expected help.

I have tried looking for ava_dense_proposals_train.FAIR.recall_93.9_tracks.pkl file but I can not find it in the repo at the moment. 
How tracks were generated? Does dense mean proposals for every frame or only keyframes?

**Comment by kennymckormick** [comment]
Hi, @gurkirt , check the data preparation instructions for AVA in our codebase, you may find the scripts to download these files. Dense just indicates 1 frame / second, not every frame.

**Comment by gurkirt** [comment]
I am talking about '*93.9_tracks.pkl' not '*93.9.pkl', I can not find the track file in https://github.com/open-mmlab/mmaction2/blob/master/tools/data/ava/fetch_ava_proposals.sh. Where did it go, has the location moved?

**Comment by kennymckormick** [comment]
Hi, @guikirt . Unfortunately, no codes in this codebase use any pickle file named `*93.9_tracks.pkl`, so I'm not sure what it is and how to download it. Where did you hear this file?

**Comment by gurkirt** [comment]
Thank you @kennymckormick , maybe I am mistaken because I have such a file and I assumed I downloaded it from here maybe some place else. Thank you for your replies though.
