### ISSUE TITLE
Why mmaction's slowonly saves a lot of memory than pytorchvideo's？

### ISSUE THREAD

**Issue by takfate** [open-mmlab/mmaction2#1436]
In my experiments, it seems that mmaction2's slowonly saves more memory than pytorchvideo's. I wonder if it is my mistake. Or is mmaction2 better optimized?

**Comment by gengenkai** [comment]
> In my experiments, it seems that mmaction2's slowonly saves more memory than pytorchvideo's. I wonder if it is my mistake. Or is mmaction2 better optimized?

Hi, takfate. Could you provide your detailed training configs of MMAction2 and pytorchvideo. Thanks.
