### ISSUE TITLE
Questions about ann_file_val ,ann_file_train in config of mmaction2

### ISSUE THREAD

**Issue by pokameng** [open-mmlab/mmaction2#1437]
hello
I have some questions about config of mmaction2:
1.Does  the  keyword 'ann_file_train' ,'ann_file_val' in mmaction/configs/detection/ava/ refer to groundtruth file?
2.Does  the  keyword 'proposal_file_train' ,'proposal_file_val' in mmaction/configs/detection/ava/ refer to detection file?
Thanks a lot!!!
@lindahua

**Comment by gengenkai** [comment]
> hello I have some questions about config of mmaction2: 1.Does the keyword 'ann_file_train' ,'ann_file_val' in mmaction/configs/detection/ava/ refer to groundtruth file? 2.Does the keyword 'proposal_file_train' ,'proposal_file_val' in mmaction/configs/detection/ava/ refer to detection file? Thanks a lot!!! @lindahua

1.Yes.
2. Proposal_file_xx are pre-computed proposal lists.
For more details about preparing AVA, please refer to our tools/data/ava/README.md.
