### ISSUE TITLE
max_testing_view is only compatible with size==1 

### ISSUE THREAD

**Issue by clannadcl** [open-mmlab/mmaction2#1440]
**Describe the bug**

max_testing_view is only compatible with size==1 

**Reproduction**

1. What command or script did you run?

When I train the skeleton model, the training process is correct, but when it begins to evaluate, it gets the error above.
I also tested it alone and made no mistakes.

2. Did you make any modifications on the code or config? Did you understand what you have modified?
The backbone is new.

3. What dataset did you use?
Ntu60.

**Error traceback**

![1644837975(1)](https://user-images.githubusercontent.com/43955209/153856368-f174512b-8a17-4178-aef4-930a35b8b464.jpg)

**Comment by dragen1860** [comment]
simply remove max_testing_views=xxx in config file. Generally the performance will drop ~1%. But you can set larger batch size and run much faster.

**Comment by kennymckormick** [comment]
I recommend you to add `test_dataloader=dict(videos_per_gpu=1),` in the dataset config. Literally, max_testing_view option is only compatible with batch size 1.

**Comment by clannadcl** [comment]
> simply remove max_testing_views=xxx in config file. Generally the performance will drop ~1%. But you can set larger batch size and run much faster.

It worked, but there is  still a bug: CUDA out of memory. Other situations are the same as above.  Testing it alone made no mistakes.

**Comment by kennymckormick** [comment]
> > simply remove max_testing_views=xxx in config file. Generally the performance will drop ~1%. But you can set larger batch size and run much faster.
> 
> It worked, but there is still a bug: CUDA out of memory. Other situations are the same as above. Testing it alone made no mistakes.

Did you add test_dataloader=dict(videos_per_gpu=1), or val_dataloader=dict(videos_per_gpu=1)?
