### ISSUE TITLE
How can I train a spatio-temporal action detection network only for action recognition?

### ISSUE THREAD

**Issue by tanchaolei** [open-mmlab/mmaction2#1443]
Now I have an action recognition dataset and I want to combine temporal and object-related information for better recognition performance. I wonder how can I train the provided spatio-temporal action detection network in mmaction2 on the action recognition dataset and use it to perform action recognition?

**Comment by kennymckormick** [comment]
Some modifications are required on top of the current AVA code. You may need to read the related and modify it on ur own.

**Comment by tanchaolei** [comment]
> Some modifications are required on top of the current AVA code. You may need to read the related and modify it on ur own.

Thanks.
