### ISSUE TITLE
基础教程中（利用高级API进行测试的结果是什么？）

### ISSUE THREAD

**Issue by LEM0NTE** [open-mmlab/mmaction2#1444]
![image](https://user-images.githubusercontent.com/74885294/153977721-fe1a164a-70a0-4c36-b7f2-b34ed70938df.png)

如图，当我进行图中所示的测试时，返回的结果是预测的标签值和相应的一个数值，我想请问这个数值（8.353993）代表的含义是什么（smoking 8.353993）
![image](https://user-images.githubusercontent.com/74885294/153977986-7becde14-7c82-4cc0-8ea2-2968a1441a19.png)
如果我想对其修改，例如返回某个标签动作持续的时间或是预测某个动作的概率，应该怎样修改呢？

谢谢您的帮助

**Comment by kennymckormick** [comment]
These values are confidence scores for each action. 
You can apply a softmax OP on top of the scores to obtain probs.

**Comment by dreamerlin** [comment]
Specifically, you can change like https://github.com/open-mmlab/mmaction2/blob/master/configs/_base_/models/tsm_r50.py#L21 to get the probability for an action.

For the duration of an action, you may need to apply the temporal detection methods
