### ISSUE TITLE
Unable to install "decord"

### ISSUE THREAD

**Issue by TIMAX-159** [open-mmlab/mmaction2#1449]
It seems that my running environment does not support "decord", even if I build from source, but it is needed in the "train a recognizer on the customized dataset" part in the tutorial you provide. I know from your features that I can "decompose a video understanding framework into different components", so is there any way that I can continue this tutorial without installing "decord", like change another similar package? Thank you very much!

**Comment by kennymckormick** [comment]
The command `pip install decord` doesn't work?

**Comment by dreamerlin** [comment]
An alternative is to use PYAV and MMCV (same to OpenCV), 

https://github.com/open-mmlab/mmaction2/blob/master/mmaction/datasets/pipelines/loading.py#L726-L865
https://github.com/open-mmlab/mmaction2/blob/master/mmaction/datasets/pipelines/loading.py#L1139-L1239

change the class name in config files

https://github.com/open-mmlab/mmaction2/blob/master/configs/recognition/tsn/tsn_r50_video_1x1x8_100e_kinetics400_rgb.py#L16
https://github.com/open-mmlab/mmaction2/blob/master/configs/recognition/tsn/tsn_r50_video_1x1x8_100e_kinetics400_rgb.py#L18

**Comment by kennymckormick** [comment]
> No, it didn't work. It says "could not find a version that satisfies the requirement decord (from versions: none) and "no matching distribution found for decord".

Maybe there's sth wrong with your pip or network condition? ` (from versions: none) ` indicates that you can not find any version of this package. Try a new pip source & check your network condition.

**Comment by kennymckormick** [comment]
> An alternative is to use PYAV and MMCV (same to OpenCV),
> 
> https://github.com/open-mmlab/mmaction2/blob/master/mmaction/datasets/pipelines/loading.py#L726-L865 https://github.com/open-mmlab/mmaction2/blob/master/mmaction/datasets/pipelines/loading.py#L1139-L1239
> 
> change the class name in config files
> 
> https://github.com/open-mmlab/mmaction2/blob/master/configs/recognition/tsn/tsn_r50_video_1x1x8_100e_kinetics400_rgb.py#L16 https://github.com/open-mmlab/mmaction2/blob/master/configs/recognition/tsn/tsn_r50_video_1x1x8_100e_kinetics400_rgb.py#L18

I think opencv may not be a working alternative, it's extremely slow.

**Comment by Grutschus** [comment]
Apparently, this is an issue with `decord` not being properly maintained anymore. See this issue [here](https://github.com/dmlc/decord/issues/213).
Basically, they have stopped releasing wheels for Mac for Python>=3.9. A solution could be to change the dependency of mmaction2 to [eva-decord](https://pypi.org/project/eva-decord/).
I will try that.

**Comment by NilsBaumgartner1994** [comment]
big ouuffff.

**Comment by AnshVM** [comment]
any fix for this?

**Comment by BoomSky0416** [comment]
The essential reason is that decord doesn't support arm64. And decord is used to decode video in this repo. You can comment out this requirement in requirements/build.txt. And replace DecordInit and DecordDecode with OpenCVInit and OpenCVDecode in the pipeline of configs.
