### ISSUE TITLE
Log file doesn't correspond to the performance you report!

### ISSUE THREAD

**Issue by donnyyou** [open-mmlab/mmaction2#145]
https://openmmlab.oss-accelerate.aliyuncs.com/mmaction/recognition/slowfast/slowfast_r50_256p_4x16x1_256e_kinetics400_rgb/20200728_022505.log.json#
Only get 30% top-1 acc.

**Comment by innerlee** [comment]
train acc and val/test acc is different

**Comment by innerlee** [comment]
but yes, 0.3 is too low

**Comment by SuX97** [comment]
This log file has been uploaded by mistake (it's of some slowonly experiment), you can refer to the 320p one. We will fix this soon. Thank you for reminding us!
