### ISSUE TITLE
get error 'Default process group has not been initialized' when running mmaction2's demo tutorial

### ISSUE THREAD

**Issue by poem2018** [open-mmlab/mmaction2#1451]
Hi, when I run the '**Train a new recognizer**' part in mmaction2's demo tutorial (link: [https://github.com/open-mmlab/mmaction2/blob/master/demo/mmaction2_tutorial.ipynb](url)
It stopped at 10 epoch,  and I got an error: `RuntimeError: Default process group has not been initialized, please make sure to call init_process_group.` ,
I wonder what might cause this problem, and how can I fix this problem? 

I use the PyTorch 1.10.0+cu113, Cuda 11.2 (I use the remote GPU platform which initially installed PyTorch itself)
And some other package versions:
![image](https://user-images.githubusercontent.com/40330318/154408866-6d0dbd2b-b49b-4ded-a9eb-aaf6ddcd3cfc.png)

error:
![image](https://user-images.githubusercontent.com/40330318/154407983-1e0c99e8-1ce6-4b5a-b615-9937c6fd7622.png)
![image](https://user-images.githubusercontent.com/40330318/154408220-540d8490-423c-4186-9202-430c4576b532.png)

**Comment by dreamerlin** [comment]
Caused by distribution, you can refer to **https://github.com/open-mmlab/mmaction2/pull/1459**
