### ISSUE TITLE
ERROR: Double requirement given: decord returned while the installation of `pip install -r requirments.txt`

### ISSUE THREAD

**Issue by del-zhenwu** [open-mmlab/mmaction2#1453]
Thanks for your error report and we appreciate it a lot.
If you feel we have help you, give us a STAR! :satisfied:

**Checklist**

**Describe the bug**

```
16:38:32  Step 12/12 : RUN python -m pip install -r requirements.txt && python setup.py check -m -s && python -m pip install .16:38:32   ---> Running in 667d905c0a7b
16:38:34  ERROR: Double requirement given: decord (from -r requirements/runtime.txt (line 1)) (already in decord>=0.4.1 (from -r requirements/optional.txt (line 2)), name='decord')
```
**Reproduction**

```
pip install -r requirments.txt
```

2. Did you make any modifications on the code or config? Did you understand what you have modified?
3. What dataset did you use?

**Environment**

**Error traceback**

If applicable, paste the error traceback here.

```
A placeholder for traceback.
```

**Bug fix**

If you have already identified the reason, you can provide the information here. If you are willing to create a PR to fix it, please also leave a comment here and that would be much appreciated!

**Comment by kennymckormick** [comment]
Would you please try again with the latest master?

**Comment by kennymckormick** [comment]
An offline chat indicates this problem has been resolved.
