### ISSUE TITLE
tsn推理k400测试集指标有差异

### ISSUE THREAD

**Issue by CSammyfd** [open-mmlab/mmaction2#1454]
你好，目前我使用tsn_r50_1x1x3_100e_kinetics400_rgb 340*256这个solution，下载对应pth（tsn_r50_1x1x3_100e_kinetics400_rgb_20200614-e508be42.pth）后，推理k400的测试集，发现指标和readme中写的有差异（更低），top1为70.6->67.9；top5为89.26->87.87

有3处与mma中原版不同：
1）我用1gpu推理，readme中写的是8gpu推理
2）我用的是Videodataset直接读取mp4，pipeline修改为 DecordInit,SampleFrames,DecordDecode,...  cfg中其他地方未作更改
3）我的k400数据集是CvF版，因为mma中提供的下载脚本无法下载。
      其测试集的39806个标定中，有约1200个视频无法找到，同时有10个左右视频corrupted，推理时只能去除。故同时想请问mma中这个指标是推理全集39800个得出的吗？

**Comment by dreamerlin** [comment]
If you use 1 gpu, you should change the `lr` according to the linear rule as the note in README

The gpus indicates the number of gpu we used to get the checkpoint. It is noteworthy that the configs we provide are used for 8 gpus as default. According to the [Linear Scaling Rule](https://arxiv.org/abs/1706.02677), you may set the learning rate proportional to the batch size if you use different GPUs or videos per GPU, e.g., lr=0.01 for 4 GPUs x 2 video/gpu and lr=0.08 for 16 GPUs x 4 video/gpu.

We validate the K400 in validation dataset, which has 19796 val videos 

https://github.com/open-mmlab/mmaction2/tree/master/tools/data/kinetics#introduction

**Comment by CSammyfd** [comment]
> If you use 1 gpu, you should change the `lr` according to the linear rule as the note in README
> 
> The gpus indicates the number of gpu we used to get the checkpoint. It is noteworthy that the configs we provide are used for 8 gpus as default. According to the [Linear Scaling Rule](https://arxiv.org/abs/1706.02677), you may set the learning rate proportional to the batch size if you use different GPUs or videos per GPU, e.g., lr=0.01 for 4 GPUs x 2 video/gpu and lr=0.08 for 16 GPUs x 4 video/gpu.
> 
> We validate the K400 in validation dataset, which has 19796 val videos
> 
> https://github.com/open-mmlab/mmaction2/tree/master/tools/data/kinetics#introduction

感谢回复，我之前在test dataset上推理了;
此次在CvF的val dataset上推理得到的结果相对接近，top1: 69.27 top5: 88.49，可能是数据集下载源不同导致
