### ISSUE TITLE
`test_recognizer3d.py::test_c3d` run failed caused by exceeds 8Gb memory

### ISSUE THREAD

**Issue by del-zhenwu** [open-mmlab/mmaction2#1462]
Thanks for your error report and we appreciate it a lot.
If you feel we have help you, give us a STAR! :satisfied:

**Checklist**

**Describe the bug**
Unit test run failed caused by `OOM(Out Of Memory)`
```
tests/test_models/test_recognizers/test_recognizer3d.py::test_timesformer PASSED
tests/test_models/test_recognizers/test_recognizer3d.py::test_c3d Killed
```
**Reproduction**

**Environment**
master branch with the latest commit.
docker configuration:
image based: `ubuntu_1804_py_37_cuda_101_cudnn_7_torch_160_mmcv_v1.4.4_master`
```
        resources:
          limits:
            cpu: "4"
            memory: 8Gi
```

**Error traceback**

If applicable, paste the error traceback here.

```
A placeholder for traceback.
```

**Bug fix**

If you have already identified the reason, you can provide the information here. If you are willing to create a PR to fix it, please also leave a comment here and that would be much appreciated!

**Comment by dreamerlin** [comment]
1. lower the tensor shape https://github.com/open-mmlab/mmaction2/blob/master/tests/test_models/test_recognizers/test_recognizer3d.py#L295 by decreasing the `N` or `T` dimension ((1, 3, 3, 16, 112, 112) -> [1, 2, 3, 8, 112, 112])
2. You can also try to decrease the usage of memory in other parts of unit-test by the same way to lower the tensor shape or modifying the testing setting (like 'TenCrop' -> 'CenterCrop', etc.)

**Comment by del-zhenwu** [comment]
> 1. lower the tensor shape https://github.com/open-mmlab/mmaction2/blob/master/tests/test_models/test_recognizers/test_recognizer3d.py#L295 by decreasing the `N` or `T` dimension ((1, 3, 3, 16, 112, 112) -> [1, 2, 3, 8, 112, 112])
> 2. You can also try to decrease the usage of memory in other parts of unit-test by the same way to lower the tensor shape or modifying the testing setting (like 'TenCrop' -> 'CenterCrop', etc.)

It would be better if we change the above settings by default, if we want the contributor enable the testing locally (less than 8 Gb cuda memory).

**Comment by dreamerlin** [comment]
According to my previous testing exp, I think the unittest will not cost 8 Gb cuda memory, maybe we can double check it @kennymckormick @gengenkai

**Comment by del-zhenwu** [comment]
ut failed at nightly building:
```
[](http://ci.openmmlab.sensetime.com/blue/organizations/jenkins/mmaction2%2Fbuild-test/detail/build-test/10/pipeline#step-73-log-61)[](http://ci.openmmlab.sensetime.com/blue/organizations/jenkins/mmaction2%2Fbuild-test/detail/build-test/10/pipeline#step-73-log-62)[](http://ci.openmmlab.sensetime.com/blue/organizations/jenkins/mmaction2%2Fbuild-test/detail/build-test/10/pipeline#step-73-log-63)[](http://ci.openmmlab.sensetime.com/blue/organizations/jenkins/mmaction2%2Fbuild-test/detail/build-test/10/pipeline#step-73-log-64)[](http://ci.openmmlab.sensetime.com/blue/organizations/jenkins/mmaction2%2Fbuild-test/detail/build-test/10/pipeline#step-73-log-65)[](http://ci.openmmlab.sensetime.com/blue/organizations/jenkins/mmaction2%2Fbuild-test/detail/build-test/10/pipeline#step-73-log-66)[](http://ci.openmmlab.sensetime.com/blue/organizations/jenkins/mmaction2%2Fbuild-test/detail/build-test/10/pipeline#step-73-log-67)[](http://ci.openmmlab.sensetime.com/blue/organizations/jenkins/mmaction2%2Fbuild-test/detail/build-test/10/pipeline#step-73-log-68)[](http://ci.openmmlab.sensetime.com/blue/organizations/jenkins/mmaction2%2Fbuild-test/detail/build-test/10/pipeline#step-73-log-69)[](http://ci.openmmlab.sensetime.com/blue/organizations/jenkins/mmaction2%2Fbuild-test/detail/build-test/10/pipeline#step-73-log-70)[](http://ci.openmmlab.sensetime.com/blue/organizations/jenkins/mmaction2%2Fbuild-test/detail/build-test/10/pipeline#step-73-log-71)[](http://ci.openmmlab.sensetime.com/blue/organizations/jenkins/mmaction2%2Fbuild-test/detail/build-test/10/pipeline#step-73-log-72)[2022-02-24T18:07:43.692Z] tests/test_models/test_common_modules/test_base_recognizers.py .         [ 77%]

[2022-02-24T18:07:43.692Z] tests/test_models/test_common_modules/test_mobilenet_v2.py F             [ 78%]

[2022-02-24T18:07:43.692Z] tests/test_models/test_common_modules/test_resnet.py .                   [ 78%]

[2022-02-24T18:07:43.692Z] tests/test_models/test_common_modules/test_resnet3d.py ..                [ 79%]

[2022-02-24T18:07:43.692Z] tests/test_models/test_detectors/test_detectors.py .                     [ 80%]

[2022-02-24T18:07:43.692Z] tests/test_models/test_localizers/test_bmn.py .                          [ 80%]

[2022-02-24T18:07:43.692Z] tests/test_models/test_localizers/test_localizers.py .                   [ 81%]

[2022-02-24T18:07:43.692Z] tests/test_models/test_localizers/test_pem.py .                          [ 81%]

[2022-02-24T18:07:43.692Z] tests/test_models/test_localizers/test_ssn.py ..                         [ 82%]

[2022-02-24T18:07:43.692Z] tests/test_models/test_localizers/test_tem.py .                          [ 82%]

[2022-02-24T18:07:43.692Z] tests/test_models/test_recognizers/test_audio_recognizer.py .            [ 83%]

[2022-02-24T18:07:43.693Z] tests/test_models/test_recognizers/test_recognizer2d.py F....            [ 85%]

[2022-02-24T18:07:43.693Z] tests/test_models/test_recognizers/test_recognizer3d.py ......Killed
```
as the above result shows, `tests/test_models/test_recognizers/test_recognizer2d.py` and `tests/test_models/test_common_modules/test_mobilenet_v2.py` run failed, `tests/test_models/test_recognizers/test_recognizer3d.py` still OOM.

**Comment by kennymckormick** [comment]
@del-zhenwu Hi, the memory usage is reduced in PR #1471 , please have another try.

**Comment by del-zhenwu** [comment]
close
