### ISSUE TITLE
Implementation of Semantics Guided Network(SGN)

### ISSUE THREAD

**Issue by jkcg-learning** [open-mmlab/mmaction2#1463]
Thanks for your feature request and we will review and plan for it when necessary.
If you feel we have help you, give us a STAR! :satisfied:

**Semantics Guided Neural Network for Skeleton based Action Recognition**

**Motivation**

SGN has better performance compared to many of the state of the art in skeleton based action recognition including ST-GCN and 2S-AGCN with respect to parameters and accuracy

**Related resources**

https://github.com/microsoft/SGN

https://arxiv.org/pdf/1904.01189.pdf

**Additional context**

![image](https://user-images.githubusercontent.com/47096512/154926535-6614f962-d214-41d5-86f3-0a5237982d8d.png)

![image](https://user-images.githubusercontent.com/47096512/154927355-90626b6a-9ea9-490b-baba-d4798db94e45.png)

![image](https://user-images.githubusercontent.com/47096512/154927433-34461ab9-067c-4d56-92be-627c22f26500.png)

![image](https://user-images.githubusercontent.com/47096512/154927524-edede739-4509-45be-a5ff-901453798b9d.png)

**Comment by kennymckormick** [comment]
Added to the feature request list.
