### ISSUE TITLE
A question of img reshape in Recognizer3D

### ISSUE THREAD

**Issue by jamiechoi1995** [open-mmlab/mmaction2#1465]
In 
https://github.com/open-mmlab/mmaction2/blob/9bb896f3745421378d2cba3662d4ec036175a24b/mmaction/models/recognizers/recognizer3d.py#L17
why img is reshaped here?
This reshape operation results in a extra dimension of the input tensor
For example, when exporting onnx, intuitively, the shape should be N,C,T,H,W
https://github.com/open-mmlab/mmaction2/blob/9bb896f3745421378d2cba3662d4ec036175a24b/tools/deployment/pytorch2onnx.py#L125
However, the actually input is 1,N,C,T,H,W  https://github.com/open-mmlab/mmaction2/issues/1079#issuecomment-894592345

**Comment by dreamerlin** [comment]
1 is the batch_size
N is the num_clip * num_crops

https://github.com/open-mmlab/mmaction2/blob/master/mmaction/datasets/pipelines/formatting.py#L292-L298

**Comment by dreamerlin** [comment]
For pytoech2onnx, maybe we need to check it @kennymckormick 

reference: https://github.com/open-mmlab/mmaction2/blob/master/tests/test_utils/test_onnx.py#L25-L33

**Comment by jamiechoi1995** [comment]
I want to add dynamic_export in pytorch2onnx.py. Thus, I want to determine whether the input dimension is correct
