### ISSUE TITLE
Python file for Detectors

### ISSUE THREAD

**Issue by jkcg-learning** [open-mmlab/mmaction2#1472]
Where can I find the python file for any detectors?

For the skeleton-based action recognition, default one is found under mmaction2/demo/faster_rcnn_r50_fpn_2x_coco.py.

![image](https://user-images.githubusercontent.com/47096512/155735941-767694ef-cb17-43c9-8255-f1cc546acf63.png)

I would like to try a new Detector, say RetinaNet, but I could not find the model architecture in MMaction2 or MMDet repo

![image](https://user-images.githubusercontent.com/47096512/155735309-fbf26093-c233-4d3a-9ac0-5404337241e4.png)

Where can I get the complete architecture for any Detector (python file)?

**Comment by kennymckormick** [comment]
Hi, jkcg

We directly utilize the detectors in [MMDetection](https://github.com/open-mmlab/mmdetection) and only add several custom modules to implement spatio-temporal action detection. You can go check mmdetection codes for the complete architecture of various detectors.

**Comment by kennymckormick** [comment]
For RetinaNet,
the configs are here: https://github.com/open-mmlab/mmdetection/tree/master/configs/retinanet,
while the code is here: https://github.com/open-mmlab/mmdetection/blob/master/mmdet/models/detectors/retinanet.py
