### ISSUE TITLE
Same config file for two models

### ISSUE THREAD

**Issue by hukkai** [open-mmlab/mmaction2#1475]
What is the difference between the two models for AVA(v2.2) detection? I use diff to see the difference of the two files and the only difference is the work_dir

https://github.com/open-mmlab/mmaction2/blob/master/configs/detection/ava/slowfast_temporal_max_kinetics_pretrained_r50_8x8x1_cosine_10e_ava22_rgb.py

https://github.com/open-mmlab/mmaction2/blob/master/configs/detection/ava/slowfast_temporal_max_focal_alpha3_gamma1_kinetics_pretrained_r50_8x8x1_cosine_10e_ava22_rgb.py

**Comment by kennymckormick** [comment]
My bad, I accidentally uploaded a wrong config for https://github.com/open-mmlab/mmaction2/blob/master/configs/detection/ava/slowfast_temporal_max_focal_alpha3_gamma1_kinetics_pretrained_r50_8x8x1_cosine_10e_ava22_rgb.py, now updated.

**Comment by hukkai** [comment]
@kennymckormick Thanks for your clarification. Could I ask how is the values of alpha and gamma selected? Is it from a paper or hyper-parameter tuning experience?

**Comment by kennymckormick** [comment]
> as

The setting is obained via a basic hyper-param search.

**Comment by hukkai** [comment]
@kennymckormick Could I ask one more question. In the focal loss paper, alpha is chosen between 0 and 1 but the config file chose alpha=3. Also I think the self.focal_alpha here seems to be the scalar multiplier to all positions to all classes, and do not  change the direction of the gradients.(https://github.com/open-mmlab/mmaction2/blob/e9f141520bbafaf3cde3f3d35279ee4430bc4d86/mmaction/models/heads/bbox_head.py#L250) Could you check? Thanks!
