### ISSUE TITLE
Posec3D Inference on video.

### ISSUE THREAD

**Issue by BakingBrains** [open-mmlab/mmaction2#1484]
I custom trained posec3d on very small data. And tried to inference it on a video. It is throwing this error

```
load checkpoint from local path: D:/pycharmprojects/skeleton_action_recognition/Runs/slowonly_r50_u48_240e_ntu120_xsub_keypoint/epoch_10.pth
Traceback (most recent call last):
  File "D:/pycharmprojects/skeleton_action_recognition/inference.py", line 19, in <module>
    results = inference_recognizer(model, video, labels)
  File "D:\pycharmprojects\skeleton_action_recognition\mmaction\apis\inference.py", line 171, in inference_recognizer
    data = test_pipeline(data)
  File "D:\pycharmprojects\skeleton_action_recognition\mmaction\datasets\pipelines\compose.py", line 50, in __call__
    data = t(data)
  File "D:\pycharmprojects\skeleton_action_recognition\mmaction\datasets\pipelines\augmentations.py", line 213, in __call__
    kp = results['keypoint']
KeyError: 'keypoint'
```
When I debugged, the result variable does not have that key.
![12](https://user-images.githubusercontent.com/51019420/156316871-9537eaf1-eafa-4f15-99e7-6307d4e4acf3.jpg)

Any suggestions?

**The Inference file:**
```
import torch

from mmaction.apis import init_recognizer, inference_recognizer

config_file = 'configs/skeleton/posec3d/slowonly_r50_u48_240e_ntu120_xsub_keypoint_test.py'
# download the checkpoint from model zoo and put it in `checkpoints/`
checkpoint_file = 'Runs/slowonly_r50_u48_240e_ntu120_xsub_keypoint/epoch_10.pth'

# assign the desired device.
device = 'cuda:0' # or 'cpu'
device = torch.device(device)

 # build the model from a config file and a checkpoint file
model = init_recognizer(config_file, checkpoint_file, device=device)

# test a single video and show the result:
video = 'demo/Correct_vid/S001C001P001R001A001_rgb3.avi'
labels = 'custom_pose_data/labels.txt'
results = inference_recognizer(model, video, labels)

# show the results
# labels = open('tools/data/kinetics/label_map_k400.txt').readlines()
# labels = [x.strip() for x in labels]
lables = [0]
results = [(labels[k[0]], k[1]) for k in results]

# print(f'The top-5 labels with corresponding scores are:')
# for result in results:
#     print(f'{result[0]}: ', result[1])
```

**The Config file**:
```
model = dict(
    type='Recognizer3D',
    backbone=dict(
        type='ResNet3dSlowOnly',
        depth=50,
        pretrained=None,
        in_channels=17,
        base_channels=32,
        num_stages=3,
        out_indices=(2, ),
        stage_blocks=(4, 6, 3),
        conv1_stride_s=1,
        pool1_stride_s=1,
        inflate=(0, 1, 1),
        spatial_strides=(2, 2, 2),
        temporal_strides=(1, 1, 2),
        dilations=(1, 1, 1)),
    cls_head=dict(
        type='I3DHead',
        in_channels=512,
        num_classes=1, # change the class here
        spatial_type='avg',
        dropout_ratio=0.5),
    train_cfg=dict(),
    test_cfg=dict(average_clips='prob'))

dataset_type = 'VideoDataset' # PoseDataset'
ann_file_train = 'custom_pose_data/merge2.pkl'
ann_file_val = 'custom_pose_data/merge2.pkl'
left_kp = [1, 3, 5, 7, 9, 11, 13, 15]
right_kp = [2, 4, 6, 8, 10, 12, 14, 16]

test_pipeline = [
    dict(
        type='UniformSampleFrames', clip_len=48, num_clips=10, test_mode=True), #num_clips=10
    dict(type='PoseDecode'),
    dict(type='PoseCompact', hw_ratio=1., allow_imgpad=True),
    dict(type='Resize', scale=(-1, 64)),
    dict(type='CenterCrop', crop_size=64),
    dict(
        type='GeneratePoseTarget',
        sigma=0.6,
        use_score=True,
        with_kp=True,
        with_limb=False,
        double=True,
        left_kp=left_kp,
        right_kp=right_kp),
    dict(type='FormatShape', input_format='NCTHW'),
    dict(type='Collect', keys=['imgs', 'label'], meta_keys=[]),
    dict(type='ToTensor', keys=['imgs'])
]
data = dict(
    videos_per_gpu=1,
    workers_per_gpu=0,
    test_dataloader=dict(videos_per_gpu=1),
    test=dict(
        type=dataset_type,
        ann_file=None,
        data_prefix=None,
        pipeline=test_pipeline))
``` 
Thank You

**Comment by vasanth4224** [comment]
use demo_skeleton.py file which is located in the demo folder.

**Comment by BakingBrains** [comment]
@vasanth4224 Thanks for reply.
Do we have any reference, so that we can use it in real-time?

**Comment by vasanth4224** [comment]
I did training and testing in poseC3D custom dataset. I tried webcam_demo.py file, but it is not working. The action is not recognized. I need also help from admin or others.

**Comment by BakingBrains** [comment]
@vasanth4224 I modified the scrip and now it can able to read the webcam data, but it's very slow. The model dependencies are high.

**Comment by vasanth4224** [comment]
@BakingBrains Could you please give me your modification code?

**Comment by MikuuGithub** [comment]
Can PoseC3D perform action recognition for each person in the video separately?
Looking forward to your reply. Thank you!

**Comment by kennymckormick** [comment]
Hi, MikuuGithub, 
PoseC3D can perform action recognition for each person in video separately, but now we only support actions defined in AVA for this case. Check our video structuralize demo: https://github.com/open-mmlab/mmaction2/blob/748aca2e2a43ebd23a60c1643b1ff13c5aced79b/demo/README.md?plain=1#L575.

**Comment by MikuuGithub** [comment]
> Hi, MikuuGithub, PoseC3D can perform action recognition for each person in video separately, but now we only support actions defined in AVA for this case. Check our video structuralize demo:
> 
> https://github.com/open-mmlab/mmaction2/blob/748aca2e2a43ebd23a60c1643b1ff13c5aced79b/demo/README.md?plain=1#L575
> 
> .

Thanks a lot for your answer. However, I think this should be spatiotemporal action detection, and PoseC3D cannot perform a similar task. If my understanding is wrong, please let me know.

**Comment by smashfan** [comment]
> > 嗨，MikuuGithub，PoseC3D 可以分别对视频中的每个人进行动作识别，但现在我们只支持在 AVA 中定义的动作。查看我们的视频结构化演示：
> > https://github.com/open-mmlab/mmaction2/blob/748aca2e2a43ebd23a60c1643b1ff13c5aced79b/demo/README.md?plain=1#L575
> > 
> > .
> 
> 非常感谢您的回答。但是，我认为这应该是时空动作检测，而 PoseC3D 无法执行类似的任务。如果我的理解有误，请告诉我。

[MikuuGithub](https://github.com/MikuuGithub)   in the demo_video_structuralize.py ,I think it work in each person..

**Comment by smashfan** [comment]
> > 嗨，MikuuGithub，PoseC3D 可以分别对视频中的每个人进行动作识别，但现在我们只支持在 AVA 中定义的动作。查看我们的视频结构化演示：
> > https://github.com/open-mmlab/mmaction2/blob/748aca2e2a43ebd23a60c1643b1ff13c5aced79b/demo/README.md?plain=1#L575
> > 
> > .
> 
> 非常感谢您的回答。但是，我认为这应该是时空动作检测，而 PoseC3D 无法执行类似的任务。如果我的理解有误，请告诉我。

in the demo_video_structuralize.py ,I think  it work in each person
![image](https://user-images.githubusercontent.com/46563839/158983126-43b3a97f-75c7-4887-a71c-f99b57dcd6e2.png)

**Comment by MikuuGithub** [comment]
> > > 嗨，MikuuGithub，PoseC3D 可以分别对视频中的每个人进行动作识别，但现在我们只支持在 AVA 中定义的动作。查看我们的视频结构化演示：
> > > https://github.com/open-mmlab/mmaction2/blob/748aca2e2a43ebd23a60c1643b1ff13c5aced79b/demo/README.md?plain=1#L575
> > > 
> > > .
> > 
> > 
> > 非常感谢您的回答。但是，我认为这应该是时空动作检测，而 PoseC3D 无法执行类似的任务。如果我的理解有误，请告诉我。
> 
> in the demo_video_structuralize.py ,I think it work in each person ![image](https://user-images.githubusercontent.com/46563839/158983126-43b3a97f-75c7-4887-a71c-f99b57dcd6e2.png)

Thank you so much for your patience, I have it running successfully! But I found that the spatiotemporal action detection part takes a lot of time, and the frame rate is only 4~5 frames. Is there any way to improve its inference speed?

**Comment by kennymckormick** [comment]
> 

There are lots of ways to accelarate the demo. For example, you can use a faster detector or pose estimator, and you can create multiple threads for handling detection, pose estimation and action recognition, respectively. `demo_video_structuralize.py`  is just a working demo, not a fast one.

**Comment by MikuuGithub** [comment]
> > 
> 
> There are lots of ways to accelarate the demo. For example, you can use a faster detector or pose estimator, and you can create multiple threads for handling detection, pose estimation and action recognition, respectively. `demo_video_structuralize.py` is just a working demo, not a fast one.

Thank you very much! I will do as you suggest.

**Comment by shenjiyuan123** [comment]
所以我想确认下：PoseC3D是不能做以下的场景：有一段长的未剪辑的视频，包含几个不同的动作，需要模型判断每段动作的开始和结束并且得出相对应的标签。
这一个场景应该算是时序动作检测吧？和PoseC3D的动作检测不太一样吧？

**Comment by MikuuGithub** [comment]
> 所以我想确认下：PoseC3D是不能做以下的场景：有一段长的未剪辑的视频，包含几个不同的动作，需要模型判断每段动作的开始和结束并且得出相对应的标签。 这一个场景应该算是时序动作检测吧？和PoseC3D的动作检测不太一样吧？ 希望大家能解答下我的疑惑，谢谢大家！

你运行一下demo_video_structuralize.py，看看是不是想要的结果

**Comment by shenjiyuan123** [comment]
> > 所以我想确认下：PoseC3D是不能做以下的场景：有一段长的未剪辑的视频，包含几个不同的动作，需要模型判断每段动作的开始和结束并且得出相对应的标签。 这一个场景应该算是时序动作检测吧？和PoseC3D的动作检测不太一样吧？ 希望大家能解答下我的疑惑，谢谢大家！
> 
> 你运行一下demo_video_structuralize.py，看看是不是想要的结果

好的, 我先去用这个demo试试. (不知道你跑过这个不, 方便直接给我看看跑完的结果吗? 因为下载数据, 模型还挺繁琐的.)
另外, 我看demo_video_structuralize.py里面的例子是需要st-detector, 但我自己只训练了一个PoseC3D as the skeleton-based action recognizer的模型, 现在只能在剪辑好的视频里输出对应的标签. 是不是PoseC3D只能做到这样?

**Comment by MikuuGithub** [comment]
> > > 所以我想确认下：PoseC3D是不能做以下的场景：有一段长的未剪辑的视频，包含几个不同的动作，需要模型判断每段动作的开始和结束并且得出相对应的标签。 这一个场景应该算是时序动作检测吧？和PoseC3D的动作检测不太一样吧？ 希望大家能解答下我的疑惑，谢谢大家！
> > 
> > 
> > 你运行一下demo_video_structuralize.py，看看是不是想要的结果
> 
> 好的, 我先去用这个demo试试. (不知道你跑过这个不, 方便直接给我看看跑完的结果吗? 因为下载数据, 模型还挺繁琐的.) 另外, 我看demo_video_structuralize.py里面的例子是需要st-detector, 但我自己只训练了一个PoseC3D as the skeleton-based action recognizer的模型, 现在只能在剪辑好的视频里输出对应的标签. 是不是PoseC3D只能做到这样?

配好环境可以直接跑，模型是在线加载的。你也可以加我929558605发给你。

**Comment by shenjiyuan123** [comment]
> > > > 所以我想确认下：PoseC3D是不能做以下的场景：有一段长的未剪辑的视频，包含几个不同的动作，需要模型判断每段动作的开始和结束并且得出相对应的标签。 这一个场景应该算是时序动作检测吧？和PoseC3D的动作检测不太一样吧？ 希望大家能解答下我的疑惑，谢谢大家！
> > > 
> > > 
> > > 你运行一下demo_video_structuralize.py，看看是不是想要的结果
> > 
> > 
> > 好的, 我先去用这个demo试试. (不知道你跑过这个不, 方便直接给我看看跑完的结果吗? 因为下载数据, 模型还挺繁琐的.) 另外, 我看demo_video_structuralize.py里面的例子是需要st-detector, 但我自己只训练了一个PoseC3D as the skeleton-based action recognizer的模型, 现在只能在剪辑好的视频里输出对应的标签. 是不是PoseC3D只能做到这样?
> 
> 配好环境可以直接跑，模型是在线加载的。你也可以加我929558605发给你。

已加, 谢谢呀!

**Comment by ShakedDovrat** [comment]
> > Was anyone able to run Posec3D in webcam (online/realtime) mode? If so, please send your modified script & config.
> 
> I finish it by fineturn demo_video_structuralize.py,you also can do it

I can also write the entire mmaction2 library, but it's better to share code :smiley:

**Comment by TRshyam** [comment]
hi guys , i have trained a model using slowfast network in mmaction2 , now i can't get how to make prediction using webcam or any video

**Comment by chrischen0606** [comment]
> > > > > 所以我想确认下：PoseC3D是不能做以下的场景：有一段长的未剪辑的视频，包含几个不同的动作，需要模型判断每段动作的开始和结束并且得出相对应的标签。 这一个场景应该算是时序动作检测吧？和PoseC3D的动作检测不太一样吧？ 希望大家能解答下我的疑惑，谢谢大家！
> > > > 
> > > > 
> > > > 你运行一下demo_video_structuralize.py，看看是不是想要的结果
> > > 
> > > 
> > > 好的, 我先去用这个demo试试. (不知道你跑过这个不, 方便直接给我看看跑完的结果吗? 因为下载数据, 模型还挺繁琐的.) 另外, 我看demo_video_structuralize.py里面的例子是需要st-detector, 但我自己只训练了一个PoseC3D as the skeleton-based action recognizer的模型, 现在只能在剪辑好的视频里输出对应的标签. 是不是PoseC3D只能做到这样?
> > 
> > 
> > 配好环境可以直接跑，模型是在线加载的。你也可以加我929558605发给你。
> 
> 已加, 谢谢呀!

Hello, could you tell me if PoseC3D is able to recognize all the actions in an untrimmed video that contains different actions?
