### ISSUE TITLE
List index out of range

### ISSUE THREAD

**Issue by TIMAX-159** [open-mmlab/mmaction2#1485]
I am trying extracting keypoints by "python mmaction2/tools/data/skeleton/ntu_pose_extraction.py exp.avi out.pkl", but the following error occurred: 
![image](https://user-images.githubusercontent.com/62273225/156471545-afb3d0f5-7b2d-4da7-b51a-5ef1163bfd11.png)
could you tell me what happened? thank you!

**Comment by TIMAX-159** [comment]
by the way, what I actually want is the heatmap of each frame of a video. Could you tell me what I should do after getting this PKL file?

**Comment by vasanth4224** [comment]
change your file name, "exp.avi" to "expA0.avi". A000 ~ A120 refers classes.

**Comment by TIMAX-159** [comment]
I have tried the postfix "A0" and "A000", but they resulted in different errors:
![image](https://user-images.githubusercontent.com/62273225/156487866-5bfe9ce1-c57c-4380-a971-edb07c4d4216.png)
![image](https://user-images.githubusercontent.com/62273225/156487888-bfeb3b88-0a3e-488c-9641-b29e60dceccf.png)
are there any more restrictions?

**Comment by kennymckormick** [comment]
Hi, TIMAX, current script is not robust and we only guarantee it can extract skeleton for NTURGB+D videos. 
I guess the problem you meet is because in some frames the detector failed to detect any human bboxes. You can modify the extraction code to handle this problem.
