### ISSUE TITLE
visual posec3d 

### ISSUE THREAD

**Issue by LZH-94** [open-mmlab/mmaction2#1486]
when i run posec3d Visualization，i have installed mmdet, but the tips tell me not
 
![09334b0e78ef20e4bcf1e288a01eab1](https://user-images.githubusercontent.com/76728474/156480242-92b373e2-d911-450b-8812-916d13bf470e.png)

**Comment by dreamerlin** [comment]
chech if you have install mmcv-full (which is with CUDA ops)

**Comment by LZH-94** [comment]
> chech if you have install mmcv-full (which is with CUDA ops)

yes，I have installed mmcv-full

**Comment by MikuuGithub** [comment]
> > chech if you have install mmcv-full (which is with CUDA ops)
> 
> yes，I have installed mmcv-full

Like this:
