### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by vasanth4224** [open-mmlab/mmaction2#1487]
(open-mmlab) C:\Users\admin\Desktop\mmaction2\mmaction2>python demo/demo_skeleton.py --config /media/a/2TB/MMAction2/mmaction2/work_dirs1/slowonly_r50_u48_240e_ntu120_xsub_keypoint/slowonly_r50_u48_240e_ntu120_xsub_keypoint.py --checkpoint /media/a/2TB/MMAction2/mmaction2/work_dirs1/slowonly_r50_u48_240e_ntu120_xsub_keypoint/best_top1_acc_epoch_80.pth /media/a/2TB/MMAction2/mmaction2/sample.mp4 /media/a/2TB/MMAction2/mmaction2/Output/result3.mp4
Traceback (most recent call last):
  File "demo/demo_skeleton.py", line 270, in <module>
    main()
  File "demo/demo_skeleton.py", line 203, in main
    h, w, _ = original_frames[0].shape
IndexError: list index out of range

Pls anyone can help me to fix this error?

**Comment by hukkai** [comment]
@vasanth4224 From my experience, original_frames is empty and you fail to read the input video.

**Comment by vasanth4224** [comment]
Thank you @hukkai. I found my mistake.
