### ISSUE TITLE
About kinetics400

### ISSUE THREAD

**Issue by weizh588** [open-mmlab/mmaction2#1488]
# dataset settings
dataset_type = 'RawframeDataset'
data_root = 'data/kinetics400/rawframes_train'
data_root_val = 'data/kinetics400/rawframes_val'
ann_file_train = 'data/kinetics400/kinetics400_train_list_rawframes.txt'
ann_file_val = 'data/kinetics400/kinetics400_val_list_rawframes.txt'
ann_file_test = 'data/kinetics400/kinetics400_val_list_rawframes.txt'

你好，我想知道rawframes_train下存的原视频么？比如.mp4 or avi 。 然后ann_file_train(txt）文件下的格式是什么样的？视频地址和类别ID么？

**Comment by hukkai** [comment]
@weizh588 You can find the answers here: https://github.com/open-mmlab/mmaction2/blob/master/tools/data/kinetics/README.md

rawframes_train is the frames of each videos.

**Comment by dreamerlin** [comment]
For The format of annotation file, you can refer to https://github.com/open-mmlab/mmaction2/blob/master/mmaction/datasets/rawframe_dataset.py#L24-L58

**Comment by dreamerlin** [comment]
For The format of annotation file, you can refer to https://github.com/open-mmlab/mmaction2/blob/master/mmaction/datasets/rawframe_dataset.py#L24-L58
