### ISSUE TITLE
PoseC3D (custom data) action recognition is not working in demo_webcam

### ISSUE THREAD

**Issue by vasanth4224** [open-mmlab/mmaction2#1494]
1. PoseC3D (custom data) action recognition is working in demo_skeleton.py, but not working demo_webcam. Could you please help me to solve this issue?
2. How to perform PoseC3D action recognition for each person? how to print action recognition result in each person top of the head with value?
Looking forward for  your reply. Thank you!

**Comment by kennymckormick** [comment]
Hi, vasanth, 
1. This feature is currently not supported.
2. You can achieve this with demo_video_structuralize.py, please read the demo docs and use this script.

**Comment by vasanth4224** [comment]
Thank you @kennymckormick, There are a lot of parse_args in demo_video_structuralize.py file. Could you please help me how to modify parse_args() based on poseC3D (custom data) algorithm?

**Comment by kennymckormick** [comment]
You can just run the example commands we provided here: https://github.com/open-mmlab/mmaction2/blob/748aca2e2a43ebd23a60c1643b1ff13c5aced79b/demo/README.md?plain=1#L575
