### ISSUE TITLE
cannot allocate memory error when inference for several times continuously

### ISSUE THREAD

**Issue by zhufeijuanjuan** [open-mmlab/mmaction2#1500]
i used video swin transformer to inference video action recognition task. i repeat to do the inferenece like:
for i in range(N):
      result = VideoSwinTransformer.predict(video)
the model predicts normally when i=0 but got error of "cannot allocate memory" when i =1.
I thought it's a memory leakage issue.

**Comment by kennymckormick** [comment]
Maybe you got the wrong place, you need to do open an issue under this repo: https://github.com/SwinTransformer/Video-Swin-Transformer
