### ISSUE TITLE
About the SlowFast`s  note.

### ISSUE THREAD

**Issue by weizh588** [open-mmlab/mmaction2#1501]
https://github.com/open-mmlab/mmaction2/blob/master/configs/recognition/slowfast/README.md

:::{note}
   1..
   2..
   3..
![image](https://user-images.githubusercontent.com/43931281/157372525-733619f0-1358-4a97-96f8-6f1e6ecd1910.png)

If I set the  dataset_type = 'VideoDataset'  , then my annotation is still [video_name,classId]?

such as 
![image](https://user-images.githubusercontent.com/43931281/157372755-e14c2a5c-3234-4e09-8ba1-7f41929fd737.png)

**Comment by kennymckormick** [comment]
Yes, ur annotation format is OK.

**Comment by weizh588** [comment]
Thank you very much for your work. But I have run into some problems. @kennymckormick  
1. I am using my own dataset, which is a mix of UFC101 and kinetics. The class_num is 11 and dataset_type = 'VideoDataset. （Is there a problem with modifying it this way? I see that the default dataset_type  is rawframe.）But the training result is very poor. 
2. When I use pre-trained weights, an error occurs: RuntimeError: Recognizer3D: The model and loaded state dict do not match exactly

Here is my config file:(I have bolded the changes）

model = dict(
    type='Recognizer3D',
    backbone=dict(
        type='ResNet3dSlowFast',
        **pretrained**='https://download.openmmlab.com/mmaction/recognition/slowfast/slowfast_r101_8x8x1_256e_kinetics400_rgb/slowfast_r101_8x8x1_256e_kinetics400_rgb_20210218-0dd54025.pth',
        resample_rate=4,  
        speed_ratio=4,  
        channel_ratio=8,  
        slow_pathway=dict(
            type='resnet3d',
            depth=101,
            pretrained=None,
            lateral=True,
            fusion_kernel=7,
            conv1_kernel=(1, 7, 7),
            dilations=(1, 1, 1, 1),
            conv1_stride_t=1,
            pool1_stride_t=1,
            inflate=(0, 0, 1, 1),
            norm_eval=False),
        fast_pathway=dict(
            type='resnet3d',
            depth=101,
            pretrained=None,
            lateral=False,
            base_channels=8,
            conv1_kernel=(5, 7, 7),
            conv1_stride_t=1,
            pool1_stride_t=1,
            norm_eval=False)),
    cls_head=dict(
        type='SlowFastHead',
        in_channels=2304,  
        **num_classes=11,**
        spatial_type='avg',
        dropout_ratio=0.5),
    train_cfg=None,
    test_cfg=dict(average_clips='prob', max_testing_views=10))

**dataset_type = 'VideoDataset'**
data_root = '/home/data1/wzh/rain/clips_v1.5/'
data_root_val = '/home/data1/wzh/test/clips_v1.5/'
ann_file_train = '/home/wzh21/mmaction2-master/tools/data/kinetics/split1_train.txt'
ann_file_val = '/home/wzh21/mmaction2-master/tools/data/kinetics/split1_test.txt'
ann_file_test = '/home/wzh21/mmaction2-master/tools/data/kinetics/split1_test.txt'


img_norm_cfg = dict(
    mean=[123.675, 116.28, 103.53], std=[58.395, 57.12, 57.375], to_bgr=False)
train_pipeline = [
    **dict(type='DecordInit'),**
    dict(type='SampleFrames', clip_len=32, frame_interval=2, num_clips=1),
    **dict(type='DecordDecode'),**
    dict(type='Resize', scale=(-1, 256)),
    dict(type='RandomResizedCrop'),
    dict(type='Resize', scale=(224, 224), keep_ratio=False),
    dict(type='Flip', flip_ratio=0.5),
    dict(type='Normalize', **img_norm_cfg),
    dict(type='FormatShape', input_format='NCTHW'),
    dict(type='Collect', keys=['imgs', 'label'], meta_keys=[]),
    dict(type='ToTensor', keys=['imgs', 'label'])
]
val_pipeline = [
    **dict(type='DecordInit'),**
    dict(
        type='SampleFrames',
        clip_len=32,
        frame_interval=2,
        num_clips=1,
        test_mode=True),
    **dict(type='DecordDecode'),**
    dict(type='Resize', scale=(-1, 256)),
    dict(type='CenterCrop', crop_size=224),
    dict(type='Normalize', **img_norm_cfg),
    dict(type='FormatShape', input_format='NCTHW'),
    dict(type='Collect', keys=['imgs', 'label'], meta_keys=[]),
    dict(type='ToTensor', keys=['imgs'])
]
test_pipeline = [
    **dict(type='DecordInit'),**
    dict(
        type='SampleFrames',
        clip_len=32,
        frame_interval=2,
        num_clips=10,
        test_mode=True),
    **dict(type='DecordDecode'),**
    dict(type='Resize', scale=(-1, 256)),
    dict(type='ThreeCrop', crop_size=256),
    dict(type='Normalize', **img_norm_cfg),
    dict(type='FormatShape', input_format='NCTHW'),
    dict(type='Collect', keys=['imgs', 'label'], meta_keys=[]),
    dict(type='ToTensor', keys=['imgs'])
]
data = dict(
    videos_per_gpu=8,
    workers_per_gpu=2,
    **val_dataloader=dict(videos_per_gpu=1),**
    test_dataloader=dict(videos_per_gpu=1),
    train=dict(
        type=dataset_type,
        ann_file=ann_file_train,
        data_prefix=data_root,
        pipeline=train_pipeline),
    val=dict(
        type=dataset_type,
        ann_file=ann_file_val,
        data_prefix=data_root_val,
        pipeline=val_pipeline),
    test=dict(
        type=dataset_type,
        ann_file=ann_file_test,
        data_prefix=data_root_val,
        pipeline=test_pipeline))

optimizer = dict(
    type='SGD', lr=0.1, momentum=0.9,
    weight_decay=0.0001)  # this lr is used for 8 gpus
optimizer_config = dict(grad_clip=dict(max_norm=40, norm_type=2))

lr_config = dict(
    policy='CosineAnnealing',
    min_lr=0,
    warmup='linear',
    warmup_by_epoch=True,
    warmup_iters=34)
total_epochs = 256
checkpoint_config = dict(interval=4)
workflow = [('train', 1)]
evaluation = dict(
    interval=1, metrics=['top_k_accuracy', 'mean_class_accuracy'])
log_config = dict(
    interval=20,
    hooks=[
        dict(type='TextLoggerHook'),
    ])

dist_params = dict(backend='nccl')
log_level = 'INFO'
work_dir = './work_dirs/slowfast_r101_8x8x1_256e_kinetics400_rgb'
load_from = None
resume_from = None
find_unused_parameters = False

**Comment by dreamerlin** [comment]
The checkpoint 'https://download.openmmlab.com/mmaction/recognition/slowfast/slowfast_r101_8x8x1_256e_kinetics400_rgb/slowfast_r101_8x8x1_256e_kinetics400_rgb_20210218-0dd54025.pth' should be set in `load_from` since it is for the whole network

And checkpoint for the `pretrain` in `backbone` should be for the backbone only (i.e., without any prefix in `state_dict` key)
