### ISSUE TITLE
How to train models with fp16 method

### ISSUE THREAD

**Issue by HuAndrew** [open-mmlab/mmaction2#1510]
Thank you very much for the open source code that has benefited you a lot.

```python
# config fp16 setting
fp16 = dict(loss_scale=512.)

```
I configured the `Mixed Precision Training` according to mmdetection faster rcnn, but the following error message appeared.  

```shell
RuntimeError: Input type (torch.cuda.HalfTensor) and weight type (torch.cuda.FloatTensor) should be the same
```
[`fp16/faster_rcnn_r50_fpn_fp16_1x.py` ](https://github.com/open-mmlab/mmdetection/blob/51df8a9b7ad5f25ebd75cf8e0969c3b728bde08d/configs/fp16/faster_rcnn_r50_fpn_fp16_1x.py#L1-L2)

But I see that there is a mix of precision implementations in the code
```python
    # https://github.com/open-mmlab/mmaction2/blob/master/mmaction/apis/train.py#L146-L154
    # fp16 setting
    fp16_cfg = cfg.get('fp16', None)
    if fp16_cfg is not None:
        optimizer_config = Fp16OptimizerHook(
            **cfg.optimizer_config, **fp16_cfg, distributed=distributed)
    elif distributed and 'type' not in cfg.optimizer_config:
        optimizer_config = OptimizerHook(**cfg.optimizer_config)
    else:
        optimizer_config = cfg.optimizer_config
```

**Comment by kennymckormick** [comment]
Hi, Andrew,
AFAIK, MMAction2 only supports fp16 training for TSN models. 
Is it correct? @dreamerlin

**Comment by HuAndrew** [comment]
Okay, thanks for resolving my confusion.
