### ISSUE TITLE
ImageNet-1K models

### ISSUE THREAD

**Issue by owaisCS** [open-mmlab/mmaction2#1512]
I noticed that in this Github repo you have uploaded the TimeSformer model pre-trained on ImageNet-21K, 
Could you please update/send the TimeSformer model pre-trained on ImageNet-1K?
Or else as mentioned in your repo in point 3,
![image](https://user-images.githubusercontent.com/68268500/158014384-d76e732e-8efa-4917-b4b7-300d2fabd28f.png)
Could you point me to the conversion code which converts the model from (https://github.com/google-research/vision_transformer) to vit_base_patch16_224.pth?
It would be very helpful.

**Comment by kennymckormick** [comment]
Hi, @congee524 , can you find the scripts for converting the model from (https://github.com/google-research/vision_transformer)?

**Comment by congee524** [comment]
Sorry, I cannot find the script. Maybe you can print the keys of the original model and the converted model, and then compare the difference. The key value should not change much (add and change prefix).

**Comment by owaisCS** [comment]
OK Thanks, @congee524, I will look into it.
By any chance do you have the TimeSformer model pre-trained on ImageNet-1K??

**Comment by daitranskku** [comment]
Hi @owaisCS , I have same question. Did you convert other models from [https://github.com/google-research/vision_transformer](https://github.com/google-research/vision_transformer) to mmaction2's type? I tried to convert and read the keys from the original models, but it appears that the keys are distinct and have additional variables. Thank you.
