### ISSUE TITLE
Action recognition to Action detection

### ISSUE THREAD

**Issue by shaffeizc** [open-mmlab/mmaction2#1514]
I am using the video swin transformer pretrained on imagenet 1k and fine-tuned on kinetics 400. I want to perform spatiotemporal action detection using this model, so I plan to fine-tune on ava. Can someone please point out the changes that I need to make to the config file to change the task from action recognition to spatiotemporal action detection?

**Comment by gengenkai** [comment]
> I am using the video swin transformer pretrained on imagenet 1k and fine-tuned on kinetics 400. I want to perform spatiotemporal action detection using this model, so I plan to fine-tune on ava. Can someone please point out the changes that I need to make to the config file to change the task from action recognition to spatiotemporal action detection?

First, you need to set 'load_from' to your pre-trained model path, then modify the dataset path and pipeline according to your fine-tune dataset. And the lr_config usually needs to be adjusted.
