### ISSUE TITLE
How to gather single pkl lists to one file

### ISSUE THREAD

**Issue by nyanmn** [open-mmlab/mmaction2#1515]
For individual video clip, we can extract pose using **`ntu_pose_extraction.py`**  as 

`python ntu_pose_extraction.py S001C001P001R001A001_rgb.avi S001C001P001R001A001.pkl`.
Then it is mentioned as `"After you get pose annotations for all videos in a dataset split, like ntu60_xsub_val. You can gather them into a single list and save the list as ntu60_xsub_val.pkl. You can use those larger pickle files for training and testing."`

How can I gather all into a file?

**Comment by kennymckormick** [comment]
```python
# pkl_names is a list of pickle names
from mmcv import load, dump
data = [load(x) for x in pkl_names]
dump(data, 'gather.pkl')
```
