### ISSUE TITLE
Custom Dataset with Spatio-Temporal Action Recognition AVA

### ISSUE THREAD

**Issue by vasanth4224** [open-mmlab/mmaction2#1517]
Dear Admin, I have custom dataset ( 1 sec video file mp4 format). I want to train and test in spatio-temporal action recognition AVA. The first step, I start build_rawframes.py, the program is working but I did't get any outputs. The video file is not convert to frames, its create only folders. I feel confusing the rest of steps. can you please help me to figure out the step by step process? Please guide me.

**Comment by kennymckormick** [comment]
Hey, vasanth, I think probably you set the `level` arg to a wrong value: https://github.com/open-mmlab/mmaction2/blob/2068e1e7e42d7ea431fd5bd8ba789d104a959a6e/tools/data/build_rawframes.py#L148
