### ISSUE TITLE
Some questions about the slowfast recognition results.

### ISSUE THREAD

**Issue by hukkai** [open-mmlab/mmaction2#1526]
Hello, I have some questions regarding the slowfast recognition results. Thanks for your attention!

1. In the model zoo page for slowfast action recognition (https://github.com/open-mmlab/mmaction2/blob/master/configs/recognition/slowfast/README.md) I saw the results of `slowfast_r50_4x16x1_256e_kinetics400_rgb` with two different resolutions: 1) short-side 256 and 2) short-side 320. But they pointed to the same config file.  

2. In the train pipeline of most models, for example https://github.com/open-mmlab/mmaction2/blob/2068e1e7e42d7ea431fd5bd8ba789d104a959a6e/configs/recognition/slowfast/slowfast_r50_4x16x1_256e_kinetics400_rgb.py#L16-L17 The pipeline first resize the videos so that the short size is 256 and then apply a RandomResizedCrop. If I understand this code correctly, I think we can directly apply the RandomResizedCrop to the videos. Resizing the videos to shorter size 256 will be harmful to videos larger than 256.

3. The method that directly reads videos with `decord` ([slowfast_r50_video_4x16x1_256e_kinetics400_rgb](https://github.com/open-mmlab/mmaction2/blob/master/configs/recognition/slowfast/slowfast_r50_video_4x16x1_256e_kinetics400_rgb.py)) is 0.8% worse than the method that read RGB frames of the videos (https://github.com/open-mmlab/mmaction2/blob/master/configs/recognition/slowfast/slowfast_r50_4x16x1_256e_kinetics400_rgb.py). But the two methods are trained with different number of GPUs. It's hard to tell which leads to the performance drop. Is it possible to do an ablation study that keeps all other configs the same but only difference IO methods (`decord` vs RGB frames)? I think it's kind of weird that using `decord` can lead to performance drop. I will also check the codes of `DecordDecode `.

4. I saw that the pertaining model of slow-only on Kinetics-700 is provided. However slowfast may be more popular. Is it possible to release a slowfast model on Kinetics-700 (or Kinetics-700-2020)? That will be very helpful. I am training `slowfast_r50_8x8x1` on Kinetics 700, but it takes 28 days on my machine...

5. This config file (https://github.com/open-mmlab/mmaction2/blob/master/configs/recognition/slowfast/slowfast_perbn_r50_8x8x1_256e_kinetics400_rgb_steplr.py) is missing.

**Comment by vasanth4224** [comment]
hi @hukkai , I want to try this model with my own dataset. can you please help me for data preprocessing?

**Comment by hukkai** [comment]
Hi @dreamerlin , for question 3, the config of using RGB frames (https://github.com/open-mmlab/mmaction2/blob/master/configs/recognition/slowfast/slowfast_r50_4x16x1_256e_kinetics400_rgb.py) has a top1 accuracy  of 74.75. while the config of using decord (https://github.com/open-mmlab/mmaction2/blob/master/configs/recognition/slowfast/slowfast_r50_video_4x16x1_256e_kinetics400_rgb.py) has a top1 accuracy of 73.95 which is 0.8% lower?
