### ISSUE TITLE
Large additional RAM usage in the testing stage

### ISSUE THREAD

**Issue by SCZwangxiao** [open-mmlab/mmaction2#1528]
Hi, I was training my own dataset using the TSN config: [tsn_r50_320p_1x1x3_110e_kinetics400_flow.py](https://github.com/open-mmlab/mmaction2/blob/master/configs/recognition/tsn/tsn_r50_320p_1x1x3_110e_kinetics400_flow.py). However, in the final testing stage, the RAM usage increased dramatically, causing the OOM error. The detailed CPU & RAM usages information are illustrated below:

<img width="957" alt="image" src="https://user-images.githubusercontent.com/31362395/159157790-eb8ad4cc-39d1-4659-9b68-36da59f23eab.png">

I've tried to lower the testing ``batchsize``, but it does not help. I think there may be some difference on training & testing dataflow, but I have not find out.

**Comment by kennymckormick** [comment]
Hi, @SCZwangxiao . I haven't met this problem before and I think a working walkaround might be setting the `test-last` and `test-best` flag off and manually test the trained model. If you can reproduce this problem with an official config, we will try to debug the problem.

**Comment by SCZwangxiao** [comment]
Problem solved. My testing set is larger than training set due to my experimental settings.
