### ISSUE TITLE
Hello，When I tried to use C3D to train the dataset of UCF101, I got this wrong information,"AttributeError: 'ConfigDict' object has no attribute 'gpu_ids'" 

### ISSUE THREAD

**Issue by zzzyjt** [open-mmlab/mmaction2#1529]
Thanks for your error report and we appreciate it a lot.
If you feel we have help you, give us a STAR! :satisfied:

**Checklist**

1. I have searched related issues but cannot get the expected help.
2. The bug has not been fixed in the latest version.

**Describe the bug**

**Reproduction**

1. What command or script did you run?

```
A placeholder for the command.
```

2. Did you make any modifications on the code or config? Did you understand what you have modified?
3. What dataset did you use?

**Environment**

1. Please run `PYTHONPATH=${PWD}:$PYTHONPATH python mmaction/utils/collect_env.py` to collect necessary environment information and paste it here.
2. You may add addition that may be helpful for locating the problem, such as
    - How you installed PyTorch [e.g., pip, conda, source]
    - Other environment variables that may be related (such as `$PATH`, `$LD_LIBRARY_PATH`, `$PYTHONPATH`, etc.)

**Error traceback**

If applicable, paste the error traceback here.

```
A placeholder for traceback.
```

**Bug fix**

If you have already identified the reason, you can provide the information here. If you are willing to create a PR to fix it, please also leave a comment here and that would be much appreciated!

**Comment by zjorgensenbits** [comment]
just put `gpu_ids = range(1)` in your config file.

**Comment by kennymckormick** [comment]
Yes, for example, you can use the following command to train with 1 gpu:
```shell
bash tools/dist_train.sh {config_name} 1 {other_args (optional)}
```

**Comment by potatowarriors** [comment]
I get the same error as this. Is there any other way other than adding this to the config gpu_ids = range(1)?
@zjorgensenbits @kennymckormick

**Comment by kennymckormick** [comment]
Did you use dist_train? 

> I get the same error as this. Is there any other way other than adding this to the config gpu_ids = range(1)? @zjorgensenbits @kennymckormick

**Comment by zzzyjt** [comment]
sorry， I haven't solved the problem yet.





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "open-mmlab/mmaction2"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年4月19日(星期二) 中午12:06
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [open-mmlab/mmaction2] Hello，When I tried to use C3D to train the dataset of UCF101, I got this wrong information,"AttributeError: 'ConfigDict' object has no attribute 'gpu_ids'"  (Issue #1529)





 
Did you use dist_train?
  
I get the same error as this. Is there any other way other than adding this to the config gpu_ids = range(1)? @zjorgensenbits @kennymckormick
