### ISSUE TITLE
real-time recognition

### ISSUE THREAD

**Issue by IDayday** [open-mmlab/mmaction2#153]
It can be used to recognize real-time videos with webcamera or something else?

**Comment by innerlee** [comment]
not yet. you may raise a feature request here https://github.com/open-mmlab/mmaction2/issues/19

**Comment by innerlee** [comment]
trying to understand the request more clear.

do you want a demo script that can take the webcam as input, and output the action label in real time?

**Comment by IDayday** [comment]
> trying to understand the request more clear.
> 
> do you want a demo script that can take the webcam as input, and output the action label in real time?

yes！it can be uesful. I have trained some models, I want to konw how efficient it works in real-time videos.

**Comment by IDayday** [comment]
for different equipments, I can test their actual operation.

**Comment by dreamerlin** [comment]
[webcam_demo.py](https://github.com/open-mmlab/mmaction2/blob/master/demo/webcam_demo.py) is added.
