### ISSUE TITLE
How to build a new model

### ISSUE THREAD

**Issue by eoozbq** [open-mmlab/mmaction2#1531]
First of all, I searched related issues in FAQ, blogs, etc., but I didn't understand the tutorial on how to build my own model. Maybe the way I searched for the answer was wrong. Looking forward to your reply.
I read tutorials on how to write config files etc but didn't find a way to solve my problem, Like use R(2+1)D  conv in Slowfast or STN.
According to the method of configs/recognition/r2plus1d/xxx.py, I tried to add the setting dictionary conv_cfg=dict(type='Conv2plus1d') to the configuration file, but the program cannot be executed and an error is reported.
I want to know if the above idea of building my own model is correct, and I hope to get more tutorials to build my own model. Can different backone, common and heads in mmaction/models be combined at will?
Thanks !!

**Comment by dreamerlin** [comment]
How about this https://github.com/open-mmlab/mmaction2/blob/master/docs/tutorials/5_new_modules.md

**Comment by eoozbq** [comment]
> 

I've read this one file in the tutorial, but thanks, I'll try more.
