### ISSUE TITLE
What's the recommended config for on-line audio recognition?

### ISSUE THREAD

**Issue by tanchaolei** [open-mmlab/mmaction2#1533]
Here I want to extract audio features from existing .wav files in an on-line way to conduct audio classification. I found the related configurations for audio resnet50 in the config file tsn_r50_64x1x1_100e_kinetics400_audio.py. However, it seems that this config is deprecated, and the 'MelLogSpectrogram' pipeline written in it is lost. 
Because I'm new to the field of audio recognition, I just wonder what config should I use for a audio recognition model? And I also notice there is a 'MelSpectrogram' pipeline available, so can I just replace the  'MelLogSpectrogram' in tsn_r50_64x1x1_100e_kinetics400_audio.py by 'MelSpectrogram' to construct my audio recognition pipelines for resnet? 

It would be appreciated for any help!

**Comment by tanchaolei** [comment]
> It's best to extract the spectrogram features in advance. This will make training much faster.
> 
> You can do this using `mmaction2/tools/data/build_audio_features.py`. Note: there are parameters you can play around with within this script.
> 
> Afterwards you can use any of the config without feature extraction. E.g. `audioonly_r50_64x1x1_100e_kinetics400_audio_feature` or `tsn_r18_64x1x1_100e_kinetics400_audio_feature`.
> 
> Note that the two backbones used here are `ResNetAudio` & plain `ResNet`.

Thanks, and I will try it.

**Comment by suntaiwu** [comment]
It seems that "mmaction2/tools/data/build_audio_features.py" will create error——
Terminating: fork() called from a process already using GNU OpenMP, this is unsafe.
