### ISSUE TITLE
About training graphics card

### ISSUE THREAD

**Issue by wutongshu819274135** [open-mmlab/mmaction2#1534]
Because there are only four graphics cards in the laboratory, cuda0 is used by default. I want to use cuda1 for training. What should I do

**Comment by rlleshi** [comment]
`tools/train.py` has arguments `--gpus` &  `--gpu-ids`

**Comment by wutongshu819274135** [comment]
Thank you ！



发自我的iPhone


------------------ Original ------------------
From: Rejnald Lleshi ***@***.***&gt;
Date: Wed,Mar 23,2022 10:23 PM
To: open-mmlab/mmaction2 ***@***.***&gt;
Cc: wutongshu819274135 ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [open-mmlab/mmaction2] About training graphics card (Issue #1534)

**Comment by kennymckormick** [comment]
Or you can add `CUDA_VISIBLE_DEVICES=1` before your training command.
