### ISSUE TITLE
PoseC3D based on 3D Poses

### ISSUE THREAD

**Issue by rlleshi** [open-mmlab/mmaction2#1535]
One approach that you mention in your paper is dividing a 3D skeleton into three 2D skeletons for training. 

1) So, when doing inference in production, it would be best to feed three 2D skeletons and average the results out, right?

2) Is the approach of feeding the whole 3D skeletons better?

**Comment by kennymckormick** [comment]
Hi, rlleshi,
Actually, this is just a potential solution towards `lossless` skeleton action recognition with PoseC3D and 3D skeletons. For the practices, I think:
1. I think it's reasonable. Or you can train multiple models with different views, and perform late fusion to ensemble the results.
2. Technically you can not directly feed 3D skeletons to PoseC3D.

**Comment by rlleshi** [comment]
for (2) I meant ofc correspondingly modifying the model. So just in general if you think the second approach could be better than the first approach if I wanted to try 3D poses on PoseC3D

**Comment by rlleshi** [comment]
Thanks, Haodong
