### ISSUE TITLE
How to reduce GPU memory  in poseC3D inference

### ISSUE THREAD

**Issue by smashfan** [open-mmlab/mmaction2#1538]
I test   demo/demo_video_structuralize.py   ,in the poseC3D inference part  ,I find it need   7Gb GPU memory, So can reduce it and how?
thanks

**Comment by kennymckormick** [comment]
Hey, smashfan, to reduce PoseC3D inference memory, try to modify the test pipeline like this:
```python
test_pipeline = [
    dict(type='UniformSampleFrames', clip_len=48, num_clips=10, test_mode=True),	# Change `num_clips=10` to `num_clips=1`
    dict(type='PoseDecode'),
    dict(type='PoseCompact', hw_ratio=1., allow_imgpad=True),
    dict(type='Resize', scale=(64, 64), keep_ratio=False),
    dict(type='GeneratePoseTarget', with_kp=True, with_limb=False, double=True, left_kp=left_kp, right_kp=right_kp),	# Change `double=True` to `double=False`
    dict(type='FormatShape', input_format='NCTHW_Heatmap'),
    dict(type='Collect', keys=['imgs', 'label'], meta_keys=[]),
    dict(type='ToTensor', keys=['imgs'])
]
```

**Comment by smashfan** [comment]
> 嘿，smashfan，为了减少 PoseC3D 推理内存，尝试像这样修改测试管道：
> 
> ```python
> test_pipeline  = [
>      dict ( type = 'UniformSampleFrames' , clip_len = 48 , num_clips = 10 , test_mode = True ),	 # 将 `num_clips=10` 更改为 `num_clips=1` 
>     dict ( type = 'PoseDecode' ),
>      dict ( type = 'PoseCompact' , hw_ratio = 1. , allow_imgpad = True ),
>      dict ( type = 'Resize', scale = ( 64 , 64 ), keep_ratio = False ),
>      dict ( type = 'GeneratePoseTarget' , with_kp = True , with_limb = False , double = True , left_kp = left_kp , right_kp = right_kp ),	 # 改变 `double=True`到 `double=False` 
>     dict ( type = 'FormatShape' , input_format ='NCTHW_Heatmap'），
>      dict（type = 'Collect'，keys = [ 'imgs'，'label' ]，meta_keys = []），
>      dict（type = 'ToTensor'，keys = [ 'imgs' ]）
> ]
> ```
ok,and  I want to know Does the fps of the input video affect the test accuracy?  and  How many fps video is suitable for this model?thanks

**Comment by smashfan** [comment]
> > > 嘿，smashfan，为了减少 PoseC3D 推理内存，尝试像这样修改测试管道：
> > > ```python
> > > test_pipeline  = [
> > >      dict ( type = 'UniformSampleFrames' , clip_len = 48 , num_clips = 10 , test_mode = True ),	 # 将 `num_clips=10` 更改为 `num_clips=1` 
> > >     dict ( type = 'PoseDecode' ),
> > >      dict ( type = 'PoseCompact' , hw_ratio = 1. , allow_imgpad = True ),
> > >      dict ( type = 'Resize', scale = ( 64 , 64 ), keep_ratio = False ),
> > >      dict ( type = 'GeneratePoseTarget' , with_kp = True , with_limb = False , double = True , left_kp = left_kp , right_kp = right_kp ),	 # 改变 `double=True`到 `double=False` 
> > >     dict ( type = 'FormatShape' , input_format ='NCTHW_Heatmap'），
> > >      dict（type = 'Collect'，keys = [ 'imgs'，'label' ]，meta_keys = []），
> > >      dict（type = 'ToTensor'，keys = [ 'imgs' ]）
> > > ]
> > > ```
> > 
> > 
> > ok,and I want to know Does the fps of the input video affect the test accuracy? and How many fps video is suitable for this model?thanks
> 
> That depends on your videos. BTW, we do not explicitly set an fps. In PoseC3D, we sample 48 frames uniformly for an arbitrary video (it is sufficient for handling a video ~10 seconds).


that means   if  my vido  is about 5 fps , this model also work well   ?    I  thought  it depends  our dataset'fps   ,if  our  dataset is 30 fps video , low fps will work badly,right?   it make me duzzy.   hope make me clear,thanks

**Comment by kennymckormick** [comment]
> > > > 嘿，smashfan，为了减少 PoseC3D 推理内存，尝试像这样修改测试管道：
> > > > ```python
> > > > test_pipeline  = [
> > > >      dict ( type = 'UniformSampleFrames' , clip_len = 48 , num_clips = 10 , test_mode = True ),	 # 将 `num_clips=10` 更改为 `num_clips=1` 
> > > >     dict ( type = 'PoseDecode' ),
> > > >      dict ( type = 'PoseCompact' , hw_ratio = 1. , allow_imgpad = True ),
> > > >      dict ( type = 'Resize', scale = ( 64 , 64 ), keep_ratio = False ),
> > > >      dict ( type = 'GeneratePoseTarget' , with_kp = True , with_limb = False , double = True , left_kp = left_kp , right_kp = right_kp ),	 # 改变 `double=True`到 `double=False` 
> > > >     dict ( type = 'FormatShape' , input_format ='NCTHW_Heatmap'），
> > > >      dict（type = 'Collect'，keys = [ 'imgs'，'label' ]，meta_keys = []），
> > > >      dict（type = 'ToTensor'，keys = [ 'imgs' ]）
> > > > ]
> > > > ```
> > > 
> > > 
> > > ok,and I want to know Does the fps of the input video affect the test accuracy? and How many fps video is suitable for this model?thanks
> > 
> > 
> > That depends on your videos. BTW, we do not explicitly set an fps. In PoseC3D, we sample 48 frames uniformly for an arbitrary video (it is sufficient for handling a video ~10 seconds).
> 
> that means if my vido is about 5 fps , this model also work well ? I thought it depends our dataset'fps ,if our dataset is 30 fps video , low fps will work badly,right? it make me duzzy. hope make me clear,thanks

It depend on your video length. Since we uniformly sample a certain number of frames from the entire video. It doesn't matter if your video is 5fps or 30fps. I would like to say that if your videos last up to dozens of seconds, PoseC3D will work well.
