### ISSUE TITLE
about kinetics400 acc

### ISSUE THREAD

**Issue by wutongshu819274135** [open-mmlab/mmaction2#1539]
Why are the accuracy of kinetics400 models so low on the data set

**Comment by dreamerlin** [comment]
We haven't reimplemented some SOTA methods owing to the lack of computation resources, especially some methods using additional data pertaining. 

But I think we can add them in the future @gengenkai @kennymckormick

**Comment by kennymckormick** [comment]
The issue is not clear, I guess.
