### ISSUE TITLE
Do you have the plan to add the person detection function

### ISSUE THREAD

**Issue by hyuan1991** [open-mmlab/mmaction2#154]
你好。非常感谢你们的implementation。
请问你们接下去有没有计划实现对动画中出现的不同人都进行独立的行为识别推论的计划？就像slowfast他们的implementation一样，他们对AVA的dataset也能进行学习与推论。
我们现在在做监视摄像头的行为识别，里面出现的人不止一个，所以希望能实现独立的推论。

**Comment by innerlee** [comment]
可以在 roadmap https://github.com/open-mmlab/mmaction2/issues/19 这儿 request feature，我们会审议和安排

**Comment by kennymckormick** [comment]
AVA is supported via PR #351. However,  offline detection results are used (like all the other implementations).
