### ISSUE TITLE
run demo/demo_skeleton.py problem

### ISSUE THREAD

**Issue by fenglihai** [open-mmlab/mmaction2#1543]
When trying to run  demo/demo_skeleton.py  I keep getting this error:

ImportError: Please install mmdet to use init_detector. For OpenMMLAB codebases, you may need to install mmcv-full first before you install the particular codebase. 

I have install mmdet=2.22 and mmcv-full=1.4.7, but still come up with this problem.
I have searched related issues but cannot get the expected help.Thank you very much for your answer

File "/mnt/workspace/skeleton code/mmaction2-master/mmaction/utils/decorators.py", line 13, in new_func
    f'Please install {module_name} to use {func.__name__}. '

**Comment by bykim555** [comment]
I try 
mmcv-full 1.3.17
mmdet  2.21.0
torch 1.6.0
torchvision 0.7.0

**Comment by fenglihai** [comment]
Thank you very much for your answer，I have installed  them  According to the version you said，but still  getting this error:

ImportError: Please install mmdet to use init_detector. For OpenMMLAB codebases, you may need to install mmcv-full first before you install the particular codebase. 

Is there any other reason for this error？This problem has been bothering me for several days. Thanks again for your help

**Comment by djy9809** [comment]
I have the same question with you. 
I have install mmdet=2.22 and mmcv-full=1.4.7
Have you resolved this issue? Can you help me if it has been resolved? 
Thank you so much!
![1](https://user-images.githubusercontent.com/39211687/160555840-2046a5ba-c1ad-46a9-8658-008e69e739ef.png)
![2](https://user-images.githubusercontent.com/39211687/160555847-4ca96c77-ae42-4e1e-b7d7-47a8f0fa66b0.png)
![3](https://user-images.githubusercontent.com/39211687/160555850-a689c7f2-8589-48c6-aa64-97f25f922c7a.png)

> Traceback (most recent call last):
  File "demo/demo_skeleton.py", line 266, in <module>
    main()
  File "demo/demo_skeleton.py", line 215, in main
    det_results = detection_inference(args, frame_paths)
  File "demo/demo_skeleton.py", line 163, in detection_inference
    model = init_detector(args.det_config, args.det_checkpoint, args.device)
  File "/root/mmaction2/mmaction/utils/decorators.py", line 12, in new_func
    raise ImportError(
ImportError: Please install mmdet to use init_detector. For OpenMMLAB codebases, you may need to install mmcv-full first before you install the particular codebase.

**Comment by fenglihai** [comment]
My problem has been solved, thank you

> I have the same question with you. I have install mmdet=2.22 and mmcv-full=1.4.7 Have you resolved this issue? Can you help me if it has been resolved? Thank you so much! ![1](https://user-images.githubusercontent.com/39211687/160555840-2046a5ba-c1ad-46a9-8658-008e69e739ef.png) ![2](https://user-images.githubusercontent.com/39211687/160555847-4ca96c77-ae42-4e1e-b7d7-47a8f0fa66b0.png) ![3](https://user-images.githubusercontent.com/39211687/160555850-a689c7f2-8589-48c6-aa64-97f25f922c7a.png)
> 
> > Traceback (most recent call last):
> > File "demo/demo_skeleton.py", line 266, in 
> > main()
> > File "demo/demo_skeleton.py", line 215, in main
> > det_results = detection_inference(args, frame_paths)
> > File "demo/demo_skeleton.py", line 163, in detection_inference
> > model = init_detector(args.det_config, args.det_checkpoint, args.device)
> > File "/root/mmaction2/mmaction/utils/decorators.py", line 12, in new_func
> > raise ImportError(
> > ImportError: Please install mmdet to use init_detector. For OpenMMLAB codebases, you may need to install mmcv-full first before you install the particular codebase.

You can comment it out：
#try:
#except (ImportError, ModuleNotFoundError):
to #     pass

**Comment by fenglihai** [comment]
> 
Thank you for your answer. Your method is very effective and helpful to me

**Comment by fenglihai** [comment]
> Basically, that's because you can not import some APIs from mmdet / mmpose properly, try this to help you figure out the problem:
> 
> ```python
> try:
>     from mmdet.apis import inference_detector, init_detector
> except (ImportError, ModuleNotFoundError):
>     raise ImportError('Failed to import `inference_detector` and '
>                       '`init_detector` form `mmdet.apis`. These apis are '
>                       'required in this demo! ')
> 
> try:
>     from mmpose.apis import (inference_top_down_pose_model, init_pose_model,
>                              vis_pose_result)
> except (ImportError, ModuleNotFoundError):
>     raise ImportError('Failed to import `inference_top_down_pose_model`, '
>                       '`init_pose_model`, and `vis_pose_result` form '
>                       '`mmpose.apis`. These apis are required in this demo! ')
> ```

Thank you very much for your answer. Your method is very effective and helpful to me

**Comment by djy9809** [comment]
> My problem has been solved, thank you
> 
> > I have the same question with you. I have install mmdet=2.22 and mmcv-full=1.4.7 Have you resolved this issue? Can you help me if it has been resolved? Thank you so much! ![1](https://user-images.githubusercontent.com/39211687/160555840-2046a5ba-c1ad-46a9-8658-008e69e739ef.png) ![2](https://user-images.githubusercontent.com/39211687/160555847-4ca96c77-ae42-4e1e-b7d7-47a8f0fa66b0.png) ![3](https://user-images.githubusercontent.com/39211687/160555850-a689c7f2-8589-48c6-aa64-97f25f922c7a.png)
> > > Traceback (most recent call last):
> > > File "demo/demo_skeleton.py", line 266, in
> > > main()
> > > File "demo/demo_skeleton.py", line 215, in main
> > > det_results = detection_inference(args, frame_paths)
> > > File "demo/demo_skeleton.py", line 163, in detection_inference
> > > model = init_detector(args.det_config, args.det_checkpoint, args.device)
> > > File "/root/mmaction2/mmaction/utils/decorators.py", line 12, in new_func
> > > raise ImportError(
> > > ImportError: Please install mmdet to use init_detector. For OpenMMLAB codebases, you may need to install mmcv-full first before you install the particular codebase.
> 
> You can comment it out： #try: #except (ImportError, ModuleNotFoundError): to # pass



> Basically, that's because you can not import some APIs from mmdet / mmpose properly, try this to help you figure out the problem:
> 
> ```python
> try:
>     from mmdet.apis import inference_detector, init_detector
> except (ImportError, ModuleNotFoundError):
>     raise ImportError('Failed to import `inference_detector` and '
>                       '`init_detector` form `mmdet.apis`. These apis are '
>                       'required in this demo! ')
> 
> try:
>     from mmpose.apis import (inference_top_down_pose_model, init_pose_model,
>                              vis_pose_result)
> except (ImportError, ModuleNotFoundError):
>     raise ImportError('Failed to import `inference_top_down_pose_model`, '
>                       '`init_pose_model`, and `vis_pose_result` form '
>                       '`mmpose.apis`. These apis are required in this demo! ')
> ```

Thank you very much! My problem has been solved.

**Comment by kennymckormick** [comment]
BTW, we have updated the error logs in the master branch.

**Comment by YTHmamba** [comment]
> 基本上，那是因为您无法从 mmdet / mmpose 正确导入某些 API，请尝试以下方法来帮助您解决问题：
> 
> ```python
> try:
>     from mmdet.apis import inference_detector, init_detector
> except (ImportError, ModuleNotFoundError):
>     raise ImportError('Failed to import `inference_detector` and '
>                       '`init_detector` form `mmdet.apis`. These apis are '
>                       'required in this demo! ')
> 
> try:
>     from mmpose.apis import (inference_top_down_pose_model, init_pose_model,
>                              vis_pose_result)
> except (ImportError, ModuleNotFoundError):
>     raise ImportError('Failed to import `inference_top_down_pose_model`, '
>                       '`init_pose_model`, and `vis_pose_result` form '
>                       '`mmpose.apis`. These apis are required in this demo! ')
> ```


Hello, I have this error：
`ImportError: Please install mmdet to use init_detector.`
May I ask where the method you mentioned should be added to the code，

**Comment by YTHmamba** [comment]
> 我的问题已经解决了，谢谢
> 
> > 我和你有同样的问题。我已经安装了 mmdet=2.22 和 mmcv-full=1.4.7 你解决了这个问题吗？如果解决了，你能帮我吗？太感谢了！![1](https://user-images.githubusercontent.com/39211687/160555840-2046a5ba-c1ad-46a9-8658-008e69e739ef.png) ![2](https://user-images.githubusercontent.com/39211687/160555847-4ca96c77-ae42-4e1e-b7d7-47a8f0fa66b0.png) ![3](https://user-images.githubusercontent.com/39211687/160555850-a689c7f2-8589-48c6-aa64-97f25f922c7a.png)
> > > 回溯（最后一次调用）：
> > > 文件“demo/demo_skeleton.py”，第 266 行，在
> > > main()
> > > 文件“demo/demo_skeleton.py”，第 215 行，在 main 
> > > det_results = detection_inference(args, frame_paths)
> > > 文件“demo/ demo_skeleton.py”，第 163 行，在 detection_inference 
> > > model = init_detector(args.det_config, args.det_checkpoint, args.device)
> > > 文件“/root/mmaction2/mmaction/utils/decorators.py”，第 12 行，在 new_func 中
> > > 引发 ImportError( 
> > > ImportError: Please install mmdet to use init_detector. 对于 OpenMMLAB 代码库，您可能需要在安装特定代码库之前先安装 mmcv-full。
> 
> 可以注释掉： #try: #except (ImportError, ModuleNotFoundError): to #pass
Hello, please tell me which code needs comment？

**Comment by YTHmamba** [comment]
> 我的问题已经解决了，谢谢
> 
> > 我和你有同样的问题。我已经安装了 mmdet=2.22 和 mmcv-full=1.4.7 你解决了这个问题吗？如果解决了，你能帮我吗？太感谢了！![1](https://user-images.githubusercontent.com/39211687/160555840-2046a5ba-c1ad-46a9-8658-008e69e739ef.png) ![2](https://user-images.githubusercontent.com/39211687/160555847-4ca96c77-ae42-4e1e-b7d7-47a8f0fa66b0.png) ![3](https://user-images.githubusercontent.com/39211687/160555850-a689c7f2-8589-48c6-aa64-97f25f922c7a.png)
> > > 回溯（最后一次调用）：
> > > 文件“demo/demo_skeleton.py”，第266行，在
> > > main()
> > > 文件“demo/demo_skeleton.py”，第215行，在main 
> > > det_results = detection_inference(args, frame_paths)
> > > 文件“demo /demo_skeleton.py”，第 163 行，在 detection_inference 
> > > model = init_detector(args.det_config, args.det_checkpoint, args.device)
> > > 文件“/root/mmaction2/mmaction/utils/decorators.py”，第12行，在new_func中先安装代码
> > > 导入错误（
> > > ImportError: Please install mmdet to use it in_detector. 对于 OpenMMLAB 库，您可能需要在特定的安装库之前安装 cv-full。
> 
> 可以注释掉： #try: #except (ImportError, ModuleNotFoundError): to #pass



> > 我的问题已经解决了，谢谢
> > > 我和你有同样的问题。我已经安装了 mmdet=2.22 和 mmcv-full=1.4.7 你解决了这个问题吗？如果解决了，你能帮我吗？太感谢了！![1](https://user-images.githubusercontent.com/39211687/160555840-2046a5ba-c1ad-46a9-8658-008e69e739ef.png) ![2](https://user-images.githubusercontent.com/39211687/160555847-4ca96c77-ae42-4e1e-b7d7-47a8f0fa66b0.png) ![3](https://user-images.githubusercontent.com/39211687/160555850-a689c7f2-8589-48c6-aa64-97f25f922c7a.png)
> > > > 回溯（最后一次调用）：
> > > > 文件“demo/demo_skeleton.py”，第 266 行，在
> > > > main()
> > > > 文件“demo/demo_skeleton.py”，第 215 行，在 main 
> > > > det_results = detection_inference(args, frame_paths)
> > > > 文件“demo/ demo_skeleton.py”，第 163 行，在 detection_inference 
> > > > model = init_detector(args.det_config, args.det_checkpoint, args.device)
> > > > 文件“/root/mmaction2/mmaction/utils/decorators.py”，第 12 行，在 new_func 中
> > > > 引发 ImportError( 
> > > > ImportError: Please install mmdet to use init_detector. 对于 OpenMMLAB 代码库，您可能需要在安装特定代码库之前先安装 mmcv-full。
> > 
> > 
> > 可以注释掉： #try: #except (ImportError, ModuleNotFoundError): to #pass
> 
> > 基本上，那是因为您无法正确从 mmdet / mmpose 导入一些 API，请尝试以下方法来帮助您解决问题：
> > ```python
> > try:
> >     from mmdet.apis import inference_detector, init_detector
> > except (ImportError, ModuleNotFoundError):
> >     raise ImportError('Failed to import `inference_detector` and '
> >                       '`init_detector` form `mmdet.apis`. These apis are '
> >                       'required in this demo! ')
> > 
> > try:
> >     from mmpose.apis import (inference_top_down_pose_model, init_pose_model,
> >                              vis_pose_result)
> > except (ImportError, ModuleNotFoundError):
> >     raise ImportError('Failed to import `inference_top_down_pose_model`, '
> >                       '`init_pose_model`, and `vis_pose_result` form '
> >                       '`mmpose.apis`. These apis are required in this demo! ')
> > ```
> 
> 非常感谢！我的问题已经解决了。

Hello, may I ask which code needs to be changed？
