### ISSUE TITLE
How to customize the evaluation metrics?

### ISSUE THREAD

**Issue by PanYZhu** [open-mmlab/mmaction2#1547]
In addiction to the provided metrics ( top_k_accuracy and mean_class_accuracy ) , is there any way to use a customized evaluation metrics?
I'm doing a multi_label classification task and the provided top_k_accuracy does not fit. So I want to write my own evaluation.
Where should I modify to achieve this ? just add the metrics to the _mmaction/core/evaluation/accuracy.py_  and  rewrite the _def evaluate_ in BaseDataset ? How about the EvalHook ?

**Comment by dreamerlin** [comment]
we define metric functions in https://github.com/open-mmlab/mmaction2/tree/master/mmaction/core/evaluation
and if you want to add it in BaseDataset, you should write it to https://github.com/open-mmlab/mmaction2/blob/master/mmaction/datasets/base.py#L139-L243

**Comment by PanYZhu** [comment]
> we define metric functions in https://github.com/open-mmlab/mmaction2/tree/master/mmaction/core/evaluation and if you want to add it in BaseDataset, you should write it to https://github.com/open-mmlab/mmaction2/blob/master/mmaction/datasets/base.py#L139-L243

Thanks for your reply! Apart from what you said above, I also modified the EvalHook to achieve the save_best function during training. Hope this would be helpful to others.
