### ISSUE TITLE
How to add X3d_L checkpoint ported from SlowFast ?

### ISSUE THREAD

**Issue by Learningm** [open-mmlab/mmaction2#1550]
Hi, I wonder how to use x3d_l checkpoint similarly to x3d_s and x3d_m model you provided.
https://github.com/open-mmlab/mmaction2/blob/master/configs/recognition/x3d/README.md
Thanks!

**Comment by kennymckormick** [comment]
Hi, Learningm, 
Basically, you need to modify the key names in state_dict, the checkpoints from PYSlowFast should align well with our implementation after you made proper modifications.

**Comment by Learningm** [comment]
> Hi, Learningm, Basically, you need to modify the key names in state_dict, the checkpoints from PYSlowFast should align well with our implementation after you made proper modifications.

I tried using x3d_m to test the methods you mentioned, but I found the parameters in mmlab models are sightly different from pytorchvideo x3d_m models.

The layer in mmlab model module are 313 and in pytorchvideo model are 311.

Here's the code
``
from mmaction.models.backbones.x3d import X3D as mmaction_x3d
from pytorchvideo.models.x3d import create_x3d

mmaction_model = mmaction_x3d(gamma_b=2.25, gamma_d=2.2) ### m model
facebook_model = create_x3d(input_clip_length=16, input_crop_size=224, depth_factor=2.2)

### name mapping
name_mapping = {}
mmlab_name = {}
facebook_name = {}
params_mmlab = list(mmaction_model.named_parameters())
params_facebook = list(facebook_model.named_parameters())

for name, param in params_mmlab:
    num_element = param.numel()
    mmlab_name[name] = num_element 
print(len(mmlab_name)) # 313

for name, param in params_facebook:
    num_element = param.numel()
    if name == 'blocks.5.pool.post_conv.weight' or name == 'blocks.5.proj.weight' or name == 'blocks.5.proj.bias':
        continue
    facebook_name[name] = num_element 
print(len(facebook_name)) # 311

``
