### ISSUE TITLE
So slow during testing

### ISSUE THREAD

**Issue by weizh588** [open-mmlab/mmaction2#1552]
![image](https://user-images.githubusercontent.com/43931281/161014227-a6f4fb03-a5b0-43bc-935e-638b14f446e4.png)
My computing platform is A100, but the test phase is too slow

**Comment by kennymckormick** [comment]
To supplement, you can modify the test pipeline, set `num_clips` as 1, it should be much faster (~ 10x faster). If testing doesn't get faster after this modification, it might due to some other problems.

**Comment by weizh588** [comment]
> To supplement, you can modify the test pipeline, set `num_clips` as 1, it should be much faster (~ 10x faster). If testing doesn't get faster after this modification, it might due to some other problems.

@kennymckormick Is this ’num_clips‘ linked to ’max_testing_views‘ ? Also, what does max_testing_views do? Thanks!

**Comment by kennymckormick** [comment]
Hi, weizh588,
The meaning of these two args are not the same: 
- `num_clips * num_crops` is the number of testing views per sample, if one reduce num_clips from 10 to 1, it means 10 times less   views are used for testing
- `max_testing_views` means how many views can one single batch contains without getting out-of-memory. For example, if you have 30 views in total and set max_testing_views to 10, the runner will divide the testing of one sample into 3 batches.
