### ISSUE TITLE
PoseC3D (Custom Dataset) error while skipping ntu_det_postproc

### ISSUE THREAD

**Issue by kevinium** [open-mmlab/mmaction2#1559]
As per your comment in [Custom Dataset Training with PoseC3D](https://github.com/open-mmlab/mmaction2/blob/master/configs/skeleton/posec3d/custom_dataset_training.md) I skipped calling the function ntu_det_postproc, but then there is an error `'list' object has no attribute 'shape'` Currently the video files for each class are stored in one folder. There are three classes and hence three folders. Please let me know, how to preprocess the same so that, I can train PoseC3D using my own dataset.

**Comment by kennymckormick** [comment]
Hi, kevinium, 
I will write a new script for extracting skeletons for a custom dataset. I will pin you when the script is ready.

**Comment by kevinium** [comment]
Yes, thank you, would that script be a part of the pipeline to train the PoseC3D model?

**Comment by kennymckormick** [comment]
Hi @kevinium , 
I create a [PR](https://github.com/kennymckormick/pyskl/pull/3) in PYSKL for creating 2D skeleton data for a custom video dataset. You can refer to that PR.

**Comment by kevinium** [comment]
Thank you... I'll check it out

**Comment by kennymckormick** [comment]
OK, please let me know if you have any further questions.

**Comment by BigJoon** [comment]
@kennymckormick 
I can't run this code. Because of 
`Traceback (most recent call last):
  File "tools/data/custom_2d_skeleton.py", line 178, in <module>
    main()
  File "tools/data/custom_2d_skeleton.py", line 125, in main
    init_dist('pytorch', backend='nccl')
  File "/opt/conda/lib/python3.7/site-packages/mmcv/runner/dist_utils.py", line 18, in init_dist
    _init_dist_pytorch(backend, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/mmcv/runner/dist_utils.py", line 29, in _init_dist_pytorch
    rank = int(os.environ['RANK'])
  File "/opt/conda/lib/python3.7/os.py", line 681, in __getitem__
    raise KeyError(key) from None
KeyError: 'RANK'
`
Can you give us the custom_2d_skeleton.py without distributed module?

**Comment by kennymckormick** [comment]
Hi, BigJoon, you mean you can not successfully run this command? 
```shell
bash tools/dist_run.sh tools/data/custom_2d_skeleton.py 8 --video-list examples/extract_diving48_skeleton/diving48.list --out examples/extract_diving48_skeleton/diving48_annos.pkl
```

BTW, you can raise issue in PYSKL if you have some questions about pyskl codes.

**Comment by kevinium** [comment]
HI @kennymckormick,
I was following your notebook and encountered two conflicting errors. 
`bash tools/dist_run.sh tools/data/custom_2d_skeleton.py 1 --video-list /home/kevin/poseC3D/ssbd.list --out /home/kevin/poseC3D/ssbd_annos.pkl
Traceback (most recent call last):
  File "tools/data/custom_2d_skeleton.py", line 16, in <module>
    import mmdet
  File "/home/kevin/anaconda3/lib/python3.7/site-packages/mmdet/__init__.py", line 25, in <module>
    f'MMCV=={mmcv.__version__} is used but incompatible. ' \
AssertionError: MMCV==1.4.8 is used but incompatible. Please install mmcv>=1.1.1, <=1.2.
`

and when I Install mmcv 1.2 I get another error
` bash tools/dist_run.sh tools/data/custom_2d_skeleton.py 1 --video-list /home/kevin/poseC3D/ssbd.list --out /home/kevin/poseC3D/ssbd_annos.pkl
Traceback (most recent call last):
  File "tools/data/custom_2d_skeleton.py", line 13, in <module>
    from pyskl.smp import mrlines
  File "/home/kevin/pyskl/pyskl/__init__.py", line 13, in <module>
    f'MMCV=={mmcv.__version__} is used but incompatible. ' \
AssertionError: MMCV==1.2.0 is used but incompatible. Please install mmcv>=1.3.6, <=1.5.0.
`
