### ISSUE TITLE
Test video from URL

### ISSUE THREAD

**Issue by genausz** [open-mmlab/mmaction2#156]
There lots of videos in webs,  it's common to testing a video directly from video's URL, rather than download the video to disk as a temp file and then run the testing pipeline. 

Would you consider implementing such testing pipeline?

Thanks.

**Comment by innerlee** [comment]
maybe we can wrap opencv as the input, since opencv supports reading from url, cam, etc.

**Comment by dreamerlin** [comment]
Implementing it in https://github.com/open-mmlab/mmaction2/pull/165
