### ISSUE TITLE
i tried to train distributed model with ntu60_xsub_keypoint dataset, but this stopped before it started training without error message

### ISSUE THREAD

**Issue by jeongeun12** [open-mmlab/mmaction2#1560]
Before raising a question, you may need to check the following listed items.

**Checklist**

1. I have searched related issues but cannot get the expected help.
2. I have read the [FAQ documentation](https://mmaction2.readthedocs.io/en/latest/faq.html) but cannot get the expected help.

![image](https://user-images.githubusercontent.com/93428685/161563896-0dd3e767-64f2-4213-a8eb-e074bd0f3cba.png)
this is terminal that stops training without error message

+ there is an warning that gpu (RTX 3080 GPU) and cuda(10.1) can be incompatible

**Comment by kennymckormick** [comment]
Hi, jeongeun,
    You can use following commands for training and testing:

```bash
# Replace string in {} with the actual arguments
# training
bash tools/dist_train.sh {config} {num_gpus} {other_args}
# testing
bash tools/dist_test.sh {config} {ckpt_name} {num_gpus} --out {output_pickle_name} --eval top_k_accuracy
```

If it doesn't work, you can also try another official implementation for PoseC3D: https://github.com/kennymckormick/pyskl
