### ISSUE TITLE
question about AVA and slowfast ‘s principle

### ISSUE THREAD

**Issue by shncg** [open-mmlab/mmaction2#1561]
when i study slowfast , i have a question . Before we train slowfast in AVA, we need to get boxes with faster-rcnn /yolo or any other way. But i  don’t understand how can we discriminate the same box in different frames. like one-to-one correspondence .I don't find any tools like deepsort  . thanks a lot!

**Comment by kennymckormick** [comment]
Hey, shncg,
During AVA training, we do not need to discriminate the same box in different frames. The annotation of AVA is 1fps, in training & testing, we use RoIAlign and the box in the center frame to crop out the feature in a 2-second clip, and determine the action category based on the cropped feature.

**Comment by shncg** [comment]
> Hey, shncg, During AVA training, we do not need to discriminate the same box in different frames. The annotation of AVA is 1fps, in training & testing, we use RoIAlign and the box in the center frame to crop out the feature in a 2-second clip, and determine the action category based on the cropped feature.

Thanks ! I have some new questions ! 
 1 ,does center frame == the img in labelframes ?
 2 , i read the papper and it says "We extract region-of-interest (RoI) features [17] at the last feature map of res5. We first extend each 2D RoI at a frame into a 3D  RoI by replicating it along the temporal axis"  what is the shape of "the last feature map of res5", it is 2D or 3D? it is already conv by 3D，why we should "replicating it"? what is the meaning of "replicating it"
3. what is the shape of on the cropped feature.? it is 2D and do it like faster -rcnn?

sorry for my so many questions ! thanks!

**Comment by kennymckormick** [comment]
Did you left some comments? It's not visible on the issue page, but I received an email.
