### ISSUE TITLE
questions about ava 

### ISSUE THREAD

**Issue by shncg** [open-mmlab/mmaction2#1563]
Hello ！ I have a question！
if clip = 32 ,and frame interval =2,  so the key frame is belong to (   32*2  ,keyframe  ,32*2 )? if a video contains 30fps/s ,we train 32×2×2/30 = 4s a time?
thanks

**Comment by shncg** [comment]
is it train  a time  only in every key frame?

**Comment by hukkai** [comment]
If clip = 32 and frame interval = 2, the program will sample 64 frames (about 2 seconds video clip) centered at the keyframe (with some temporal jitter).

**Comment by shncg** [comment]
> If clip = 32 and frame interval = 2, the program will sample 64 frames (about 2 seconds video clip) centered at the keyframe (with some temporal jitter).

I understand ! thanks !

> If clip = 32 and frame interval = 2, the program will sample 64 frames (about 2 seconds video clip) centered at the keyframe (with some temporal jitter).

I understand ! thanks!
