### ISSUE TITLE
Question about  ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 1634184) of binary:

### ISSUE THREAD

**Issue by shncg** [open-mmlab/mmaction2#1569]
When i use dist_train.sh  to train slowfast ,the error happens sometimes . But it doesn't not always happen. i dont' know why 

ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 1634184) of binary:

**Comment by anvar94** [comment]
hello shnsg do you solve this error?

**Comment by anvar94** [comment]
> When i use dist_train.sh to train slowfast ,the error happens sometimes . But it doesn't not always happen. i dont' know why
> 
> ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 1634184) of binary:

hello shncg do you solve this error?
