### ISSUE TITLE
the results of the experiment

### ISSUE THREAD

**Issue by Weed-eat-meat** [open-mmlab/mmaction2#157]
Hi, I did not find the results of the experiment. I would like to ask how the UCF 101 dataset performs on slowfast in your experiment? And have you achieve the acc in the original paper?

**Comment by SuX97** [comment]
The results are [here](https://github.com/open-mmlab/mmaction2/tree/master/configs/recognition/slowfast). We only released the result of Slowfast on K400. You could conduct your on experiment refering to the [config](https://github.com/open-mmlab/mmaction2/blob/master/configs/recognition/tsn/tsn_r50_1x1x3_80e_ucf101_rgb.py) of TSN on UCF101.
