### ISSUE TITLE
STGCN dropout rate

### ISSUE THREAD

**Issue by rlleshi** [open-mmlab/mmaction2#1573]
I was wondering (just generally) why the dropout rate of stgcn is [set to 0](https://github.com/open-mmlab/mmaction2/blob/f3d4817d781b45fa02447a2181db5c87eccc3335/mmaction/models/backbones/stgcn.py#L59) by default?

For e.g, the paper reports it `0.5` by default. 

(though from my tasks' standpoint a 0.5 dropout rate is disastrous and in general it doesn't help)

**Comment by kennymckormick** [comment]
Hi, rlleshi, 
Cuz in practice, we find that setting a dropout basically not helpful. Thus due to occam's razor, we do not set a dropout.
