### ISSUE TITLE
posec3d train with 3d kps

### ISSUE THREAD

**Issue by jeongeun12** [open-mmlab/mmaction2#1575]
Before raising a question, you may need to check the following listed items.

**Checklist**

1. I have searched related issues but cannot get the expected help.
2. I have read the [FAQ documentation](https://mmaction2.readthedocs.io/en/latest/faq.html) but cannot get the expected help.

i want to train posec3d model with my custom skeleton dataset
after i made my custom dataset with posec3d's dataset format ,i train model with this.
but i got this error 
i think it's because dimensional problem.. because i just changed skeleton 2d to 3d
how can i train posec3d with 3d skeleton? what value i have to change??
![image](https://user-images.githubusercontent.com/93428685/162855450-3122cac2-a021-4d0b-a490-4853f93ba8ab.png)

**Comment by kennymckormick** [comment]
Hi, jeongeun12, 
Currently PoseC3D does not support training with 3d joints directly. To use PoseC3D,  you need to first project 3d keypoints to 2d keypoints (for example, find a project view that reserve the majority of inter-keypoint variance).
If you want to directly use 3d joints for training, I recommend you to move to [PYSKL](https://github.com/kennymckormick/pyskl), where we released an original SOTA gcn model named ST-GCN++

**Comment by jeongeun12** [comment]
if i change shape of scale_factor with (3,)  to be able to broadcast , can it be trained with 3d joints..?
