### ISSUE TITLE
Cannot be reproduced.

### ISSUE THREAD

**Issue by weizh588** [open-mmlab/mmaction2#1579]
Hello, when i train my network,  i cant reproduced the results.

Here is  my command：
/tools/dist_train.sh configs/recognition/csn/ipcsn_ig65m_pretrained_bnfrozen_r152_32x2x1_58e_kinetics400_rgb.py  2 --validate --seed 0 --deterministic

Thanks!

**Comment by kennymckormick** [comment]
Is there any more detailed description about ur problem?

**Comment by weizh588** [comment]
@kennymckormick   I mean if I retrain using the same profile ，GPU and  seed, I will get the same result? Is there still a probability that the same result will not be obtained? Thank you !

**Comment by kennymckormick** [comment]
Hi, weizh588, 
MMAction2 doesn't provide training for this specific config. It just provides the inference of this model, with checkpoint ported from [VMZ](https://github.com/facebookresearch/VMZ) by @dreamerlin .

**Comment by weizh588** [comment]
> Is there any more detailed description about ur problem?

Hi,
I mean I used the same seeds but got two different results .Do you know what could be the cause of the problem? Thanks.

**Comment by weizh588** [comment]
> Is there any more detailed description about ur problem?

Hi, I mean I used the same seeds to train but got two different results .Do you know what could be the cause of the problem? Thanks.

**Comment by kennymckormick** [comment]
Hi, weizh588, I'm not sure the results are exactly reproducible with multi-gpu training. Maybe you can first try to set the number of gpu to 1 and to see if results are exactly the same in different trails with the same seed.
