### ISSUE TITLE
Feature extraction of BMN using TSN

### ISSUE THREAD

**Issue by tangh** [open-mmlab/mmaction2#158]
In the BMN [Model Zoo](https://github.com/open-mmlab/mmaction2/blob/f183c1cb88ff3a863723369366a64d043d4e7743/configs/localization/bmn/README.md) there are results of feature extracted by MMAction but I found on details in [Data Preparation](https://github.com/open-mmlab/mmaction2/blob/f183c1cb88ff3a863723369366a64d043d4e7743/tools/data/activitynet/preparing_activitynet.md) about how to extract the feature using TSN.

After refer to BMN paper and some [issues](https://github.com/wzmsltw/BSN-boundary-sensitive-network.pytorch/issues/14), I am still confusing about the details.

---

assume the video has 16,000 frames

1. Divide all frames into 1000 continuous non-overlap snippets, each has 16 frames. Decode video to raw frames and calculate optical flow.

2. Select the 8-th rgb frame and 6,7,8,9,10-th optical flow frames in each snippet to represent this snippet.

3. For one snippet:

+ RGB: initialize TSN network with ActivityNet RGB corresponding [config](https://github.com/open-mmlab/mmaction2/blob/master/configs/recognition/tsn/tsn_r50_320p_1x1x8_50e_activitynet_video_rgb.py) and [ckpt](https://openmmlab.oss-accelerate.aliyuncs.com/mmaction/recognition/tsn/tsn_r50_320p_1x1x8_50e_activitynet_video_rgb/tsn_r50_320p_1x1x8_50e_activitynet_video_rgb_20200804-9e15687e.pth) in [TSN Model Zoo](https://github.com/open-mmlab/mmaction2/blob/master/configs/recognition/tsn/README.md#activitynet-v13). Input *one* rgb frame (8-th), simply resize to `224x224` without any crop, then `cls_score` return by tsn_head will be a tensor with shape `[1, 200]`.

+ Flow: initialize TSN network with flow config and ckpt, input *five* optical flow frames, then `consensus module` will "average" them, so `cls_score` will also be a tensor with shape `[1, 200]`.

+ concat two tensor above -> get feature of this snippet

4. Same process to all 1000 snippets, so the feature shape of a video is `[1000, 400]`, then use [this script](https://github.com/wzmsltw/BSN-boundary-sensitive-network.pytorch/blob/master/data/activitynet_feature_cuhk/data_process.py) to rescaled to `[100, 400]`

Is above the right step? Or could you add your feature extraction script to this repo.

Thank you!

**Comment by kennymckormick** [comment]
Hi, tangh. The pipeline you proposed is exactly the one that we used for ActivityNet feature extraction. Recently I'm busy with other projects. I will update the doc one or two weeks later.

**Comment by JJBOY** [comment]
I found that you offered the TSN model to extract the  ActivityNet-1.3 feature. But you don not offer the 'anet_train/val_clip.txt'. And I also found that the config files 'tsn_r50_320p_1x1x8_50e_activitynet_video_rgb' and 'tsn_r50_320p_1x1x8_50e_activitynet_clip_rgb' have no difference, so what's the difference about the TSN fine-tuned on clip-level and video-level.

**Comment by kennymckormick** [comment]
> I found that you offered the TSN model to extract the ActivityNet-1.3 feature. But you don not offer the 'anet_train/val_clip.txt' used in config and the document about how to prepare the data for finetuning. And I also found that the config files 'tsn_r50_320p_1x1x8_50e_activitynet_video_rgb' and 'tsn_r50_320p_1x1x8_50e_activitynet_clip_rgb' have no difference, so what's the difference about the TSN fine-tuned on clip-level and video-level.

Hi, video-level is that we use the entire untrimmed video for finetuning, clip-level is that we just use clips that contain action instances for finetuning.

**Comment by kennymckormick** [comment]
We provide detailed instructions for feature extraction in PR #190

**Comment by JJBOY** [comment]
Thanks for your quick reply and awesome works. I just took a quick look at your updated code and I guess that wether use the entire untrimmed video for finetuning or just use clips that contain action instances for finetuning is controled by the 'ann_file_train/val' parameters in the config file,  is that right?
If right, the 'ann_file_train/val' parameters in config file 
'tsn_r50_320p_1x1x8_50e_activitynet_video_rgb/flow' should be 
'data/ActivityNet/anet_train/val_video.txt' rather than 
'data/ActivityNet/anet_train/val_clip.txt'.

**Comment by kennymckormick** [comment]
> Thanks for your quick reply and awesome works. I just took a quick look at your updated code and I guess that wether use the entire untrimmed video for finetuning or just use clips that contain action instances for finetuning is controled by the 'ann_file_train/val' parameters in the config file, is that right?
> If right, the 'ann_file_train/val' parameters in config file
> 'tsn_r50_320p_1x1x8_50e_activitynet_video_rgb/flow' should be
> 'data/ActivityNet/anet_train/val_video.txt' rather than
> 'data/ActivityNet/anet_train/val_clip.txt'.

Yes, u r right.

**Comment by pandababyer** [comment]
Thanks mate ,the pipeline you proposed is really help.

**Comment by shashwatsaini** [comment]
The checkpoint file for TSN trained on activitynet no longer seems to exist, could someone provide an updated link?
