### ISSUE TITLE
Has anyone tried "gen_ntu_rgbd_raw.py" file to process dataset “ntu60_xsub”? 有人成功使用"gen_ntu_rgbd_raw.py"文件处理ntu60_xsub数据集吗？

### ISSUE THREAD

**Issue by xiangwentao666** [open-mmlab/mmaction2#1581]
I wanted to run the test file with the config file named "2sagcn_80e_ntu60_xsub_keypoint_3d.py", but I didn't have the dataset in the correct format because an error was raised like this `running_mean should contain 51 elements not 75 mmlab 2sagcn`. Then I tried the "gen_ntu_rgbd_raw.py" file to process the dataset(temporally named A) downloaded from [this website](https://download.openmmlab.com/mmaction/posec3d/ntu60_xsub_val.pkl), but I stuck in the incorrect filename of the dataset named A. Here are the codes associated with the filename：

我想使用"2sagcn_80e_ntu60_xsub_keypoint_3d.py"这个配置文件去运行2sagcn模型的test.py文件，但是提示了 `running_mean should contain 51 elements not 75 mmlab 2sagcn` 这个错误，是数据集格式不对。然后我尝试使用gen_ntu_rgbd_raw.py脚本文件去处理下载的ntu数据集，但是发现下载的这个数据集的文件名也不正确。与文件名相关的部分代码如下：

`setup_number = int(filename[filename.find('S') + 1:filename.find('S') +4])`
`action_class = int(filename[filename.find('A') + 1:filename.find('A') +4])`
`subject_id = int(filename[filename.find('P') + 1:filename.find('P') +4])`
`camera_id = int(filename[filename.find('C') + 1:filename.find('C') +4])`

Is there anyone could give me some help?
请问有人可以提供一些帮助吗？

**Comment by kennymckormick** [comment]
`gen_ntu_rgbd_raw.py` should process the raw data of NTURGB+D without any failure. If you can not get it work, I recommend you to switch to [PYSKL](https://github.com/kennymckormick/pyskl/), where we provide the processed 3D skeleton annotation files.

**Comment by xiangwentao666** [comment]
> `gen_ntu_rgbd_raw.py` should process the raw data of NTURGB+D without any failure. If you can not get it work, I recommend you to switch to [PYSKL](https://github.com/kennymckormick/pyskl/), where we provide the processed 3D skeleton annotation files.

Well, thank you for your timely reply.
I will try the `.pkl` file you provided for us. However, I have been trying to train a 2s-agcn model using dataset made by myself for a few days, while the input of the network requires data in a specific format. Emm, the problem of processing my own data still exists now.

**Comment by kennymckormick** [comment]
> > `gen_ntu_rgbd_raw.py` should process the raw data of NTURGB+D without any failure. If you can not get it work, I recommend you to switch to [PYSKL](https://github.com/kennymckormick/pyskl/), where we provide the processed 3D skeleton annotation files.
> 
> Well, thank you for your timely reply. I will try the `.pkl` file you provided for us. However, I have been trying to train a 2s-agcn model using dataset made by myself for a few days, while the input of the network requires data in a specific format. Emm, the problem of processing my own data still exists now.

If you are training your own datasets with 17 keypoints, you can refer to configs for 2D skeleton in PYSKL.

**Comment by xiangwentao666** [comment]
> > > `gen_ntu_rgbd_raw.py` should process the raw data of NTURGB+D without any failure. If you can not get it work, I recommend you to switch to [PYSKL](https://github.com/kennymckormick/pyskl/), where we provide the processed 3D skeleton annotation files.
> > 
> > 
> > Well, thank you for your timely reply. I will try the `.pkl` file you provided for us. However, I have been trying to train a 2s-agcn model using dataset made by myself for a few days, while the input of the network requires data in a specific format. Emm, the problem of processing my own data still exists now.
> 
> If you are training your own datasets with 17 keypoints, you can refer to configs for 2D skeleton in PYSKL.


Got it! I'll give it a try. Thank you very much!
