### ISSUE TITLE
question about batchsize

### ISSUE THREAD

**Issue by shncg** [open-mmlab/mmaction2#1586]
Hello ,  how can i change the batchsize in config file ?  I didn't find it . Thanks !
File name : slowfast_kinetics_pretrained_r50_4x16x1_20e_ava_rgb.py"

**Comment by Dai-Wenxun** [comment]
Hi, @shncg,  
the batchsize is `num_gpus * videos_per_gpu` when building dataloader, so you can change the value of `data.videos_per_gpu` in config file to adjust the batchsize.

**Comment by shncg** [comment]
> Hi, @shncg, the batchsize is `num_gpus * videos_per_gpu` when building dataloader, so you can change the value of `data.videos_per_gpu` in config file to adjust the batchsize.

thanks ！
