### ISSUE TITLE
posec3d_ava.pth是如何实现的

### ISSUE THREAD

**Issue by confeather** [open-mmlab/mmaction2#1589]
https://download.openmmlab.com/mmaction/skeleton/posec3d/posec3d_ava.pth
请问demo中的此模型的config文件可以公布吗

**Comment by kennymckormick** [comment]
Hi, confeather, posec3d_ava.pth is a private model now and is only used for skeleton-based spatiotemporal det only.

**Comment by confeather** [comment]
> 

It's a pity 😢
