### ISSUE TITLE
How do I add a "81 class" action  in AVA 😝

### ISSUE THREAD

**Issue by kuangxiaoye** [open-mmlab/mmaction2#1592]
Not sure if it's possible, or if someone has already done it. I searched and found no clues emmo(╥﹏╥)o

**Comment by kuangxiaoye** [comment]
- [[How to Prepare data to train Spatial Temporal Action Detection SlowFast model? #652](https://github.com/open-mmlab/mmaction2/issues/652)](https://github.com/open-mmlab/mmaction2/issues/652)
- [[Custom Training of SpatioTemporal Model SlowaFast giving mAP 0.0 #1140](https://github.com/open-mmlab/mmaction2/issues/1140)](https://github.com/open-mmlab/mmaction2/issues/1140)

**Comment by Deivid-SVG-AI** [comment]
@kuangxiaoye did you find out if it was possible?, I'm also trying to add an extra class to the already existing ones, and, if possible, do i need to train the model with the already existing classes plus my class or only with my class?
Sorry for the inconvenience.
