### ISSUE TITLE
slowfast+fast-rcnn want to know ACC

### ISSUE THREAD

**Issue by 1025378573** [open-mmlab/mmaction2#1594]
**Describe the feature**
I am using **slowfast+fast-rcnn** for AVA datasets. I want to know the **accuracy** in my log file. But the log only have recall and precision.
Or if there any method or tools can help me? I've tried **mmaction2/tools/test.py ----eval top_3_accuracy** but still didn't work.

**Motivation**
for Better analysis model and  dataset,  It is inconvenient when top_k_accuracy can be recorded in the log

**Comment by kennymckormick** [comment]
Acc is not a valid metric for AVA, since it's a multi-label dataset.

**Comment by kumarvasantha552** [comment]
what else should be used to measure ?

**Comment by kennymckormick** [comment]
> what else should be used to measure ?

You should use mAP as the metric, please refer to this evaluation code: https://github.com/activitynet/ActivityNet/tree/master/Evaluation/ava.
