### ISSUE TITLE
inference_recognizer with NDArray got diffrent result with video file as input.

### ISSUE THREAD

**Issue by hubutui** [open-mmlab/mmaction2#1597]
If the input is a video file, the test pipeline is:
1. `OpenCVInit`
2. `SampleFrames`
3. `OpenCVDecode`
If the input is a NDArray, the test pipeline is:
1. `SampleFrames`
2. `ArrayDecode`
For a video input file, the `total_frames` is calculated inaccurately by opencv, but for a NDArray the `total_frames` is accurate. These two `total_frames` are not the same for some video, which leads to different `SampleFrames` results and influences the final model prediction.
Any suggestions to get consistent model prediction?

**Comment by Dai-Wenxun** [comment]
Hi, @hubutui, 
for video dataset, I highly recommend you to use `DecordInit`-`SampleFrames`-`DecordDecode` for decoding instead of `OpenCVInit`-`SampleFrames`-`OpenCVDecode`.

**Comment by hubutui** [comment]
@Dai-Wenxun According to
https://github.com/open-mmlab/mmaction2/blob/255bbc08634c21e6400af7b9d1a470b52285ebcd/mmaction/apis/inference.py#L125-L133
`OpenCVInit`-`SampleFrames`-`OpenCVDecode` is the default pipeline for video file inference.

**Comment by Dai-Wenxun** [comment]
`OpenCVInit` uses `cv2.VideoCapture` as the video loader, so I searched for a lot of materials about it, unfortunately, there is no explanation why this happens. Is the `total_frames` obtained by the two methods very different? If there is only a gap of one or two frames, it should have little effect on the accuracy. Perhaps, as a stopgap, you can modify the code to change `OpenCV` to `Decord`.

**Comment by hubutui** [comment]
https://github.com/opencv/opencv/blob/2b60166e5c65f1caccac11964ad760d847c536e4/modules/videoio/src/cap_ffmpeg_impl.hpp#L1812-L1821
According to the above code, opencv will get `nb_frames` from the stream, but if it's not available, it calculates it from duration and fps inaccurate. I think without reading all the frames of a video, we could not get the accurate total frames just from video file header or metadata, neither with PyAV, opencv, or record.
1. We could simply ignore this gay, as a robust network should not predict a different class due to different sampling frames.
2. Or change the `SampleFrames` and `VideoDecode` to one step, but it changes a lot of codes.

**Comment by Dai-Wenxun** [comment]
Thank you very much for your timely reply. In most cases, the calculation of `total_frames` should be accurate. and if `total_frames` is obtained by reading stream frame by frame,  it is very time-consuming and the meaning of the frame sampling strategy (random access) is lost. As you said, a sufficiently robust model won't be affected by this little problem, we can simply ignore this trivial issue.
