### ISSUE TITLE
How to call the API of pose C3d for result prediction？

### ISSUE THREAD

**Issue by wangrenrui** [open-mmlab/mmaction2#1599]
After bone point training based on pose C3d, how to call API to output the prediction result of a skeleton action segment (I don't want to use test.py script)
![image](https://user-images.githubusercontent.com/68637895/164411661-f0e89fd3-4dbf-4b80-818d-71119d369a91.png)
![image](https://user-images.githubusercontent.com/68637895/164411721-a5b57f54-0aa3-457c-ae3b-e2b3f1d07171.png)

**Comment by nngg11** [comment]
Hi, please use the file found at demo/demo_skeleton.py. From there, just need to add the necessary arguments. Take into account that it is needed to perform human detection and pose estimation.

**Comment by kennymckormick** [comment]
Yes, plz try to refer to demo_skeleton.py.
