### ISSUE TITLE
"size mismatch for roi_head" for testing demo_skeleton.py

### ISSUE THREAD

**Issue by nyanmn** [open-mmlab/mmaction2#1600]
I am testing demo_skeleton.py.
I have trained two classes activities model using posec3d.
cls_head is updated with ` num_classes=2`
```
cls_head=dict(
        type='I3DHead',
        in_channels=512,
        num_classes=2,
        spatial_type='avg',
        dropout_ratio=0.5),
    train_cfg=dict(),
    test_cfg=dict(average_clips='prob'))
```

The whole config file is [here](https://www.dropbox.com/s/f71llczfuinod2g/slowonly_r50_u48_240e_ntu60_xsub_keypoint.py?dl=0).

Training was ok.
Then my label file has only two classes.

```
hitting_and_kicking
loitering
```

When I run demo_skeleton.py, my command is as follow.

`python demo/demo_skeleton.py data/loitering_test/video6265057279867880725.mp4     testout.mp4     --config configs/skeleton/posec3d/slowonly_r50_u48_240e_ntu60_xsub_keypoint.py     --checkpoint work_dirs/slowonly_r50_u48_240e_ntu60_xsub_keypoint/latest.pth     --det-config demo/faster_rcnn_r50_fpn_2x_coco.py     --det-checkpoint tools/data/skeleton/faster_rcnn_r50_fpn_1x_coco-person_20201216_175929-d022e227.pth     --det-score-thr 0.9     --pose-config demo/hrnet_w32_coco_256x192.py     --pose-checkpoint tools/data/skeleton/hrnet_w32_coco_256x192-c78dce93_20200708.pth     --label-map tools/data/skeleton/label_map_ct.txt`

The follow mismatch errors come out during running demo_skeleton.py.

```
The model and loaded state dict do not match exactly

size mismatch for cls_head.fc_cls.weight: copying a param with shape torch.Size([60, 512]) from checkpoint, the shape in current model is torch.Size([2, 512]).
size mismatch for cls_head.fc_cls.bias: copying a param with shape torch.Size([60]) from checkpoint, the shape in current model is torch.Size([2]).
load checkpoint from local path: tools/data/skeleton/faster_rcnn_r50_fpn_1x_coco-person_20201216_175929-d022e227.pth
The model and loaded state dict do not match exactly

size mismatch for roi_head.bbox_head.fc_cls.weight: copying a param with shape torch.Size([2, 1024]) from checkpoint, the shape in current model is torch.Size([81, 1024]).
size mismatch for roi_head.bbox_head.fc_cls.bias: copying a param with shape torch.Size([2]) from checkpoint, the shape in current model is torch.Size([81]).
size mismatch for roi_head.bbox_head.fc_reg.weight: copying a param with shape torch.Size([4, 1024]) from checkpoint, the shape in current model is torch.Size([320, 1024]).
size mismatch for roi_head.bbox_head.fc_reg.bias: copying a param with shape torch.Size([4]) from checkpoint, the shape in current model is torch.Size([320]).
```
What could be wrong?

**Comment by kennymckormick** [comment]
Hi, nyanmn, 
That's due to the mismatch between checkpoint and config.
1. It seems that you skeleton action recognition config is with two classes, but you load a checkpoint with 60 classes (You should load a ckpt trained by yourself). 
2. It seems that you detection config has 81 classes (CoCo), but your checkpoint is trained on person class only (with 1 class). That causes a mismatch.
