### ISSUE TITLE
What does this "4x16x1" mean？ (slowfast_kinetics_pretrained_r50_4x16x1_20e_ava_rgb) 

### ISSUE THREAD

**Issue by Huang-jian-lin** [open-mmlab/mmaction2#1605]
![image](https://user-images.githubusercontent.com/59358930/164966980-2bf8774c-c810-4b39-a752-e4b7c3f38704.png)

**Comment by Novare** [comment]
These refer to the sampling strategy employed when calling SampleFrames in the pipeline. For a detailed explanation you can check this out: https://github.com/open-mmlab/mmaction2/discussions/655

**Comment by Huang-jian-lin** [comment]
你好！我已收到你的邮件--黄建霖

**Comment by Huang-jian-lin** [comment]
But here the Input is "32×2" that refers to "clip_len=32, frame_interval=2" in the source code,  which is inconsistent with "32×2".
![image](https://user-images.githubusercontent.com/59358930/165009681-f0f00a9d-475b-4dd1-a88d-1d5571844154.png)

**Comment by Huang-jian-lin** [comment]
> These refer to the sampling strategy employed when calling SampleFrames in the pipeline. For a detailed explanation you can check this out: #655

**Comment by Huang-jian-lin** [comment]
> These refer to the sampling strategy employed when calling SampleFrames in the pipeline. For a detailed explanation you can check this out: #655

But here the Input is "32×2" that refers to "clip_len=32, frame_interval=2" in the source code, which is inconsistent with "32×2".
image

**Comment by hukkai** [comment]
4x16 means T=4 and $\tau$=16 in the slowfast paper, which means it will cover 4*16=64 frames.
The input size 32x2 also indicated it will cover 64 frames, which is consistent.
$\tau$ is the temporal stride in the slow pathway and the 2 in "32x2" is the temporal stride in the  fast pathway.
You can find more explanations in the slowfast paper.
