### ISSUE TITLE
Spatio-temporal action detection models to ONNX

### ISSUE THREAD

**Issue by MGReyes** [open-mmlab/mmaction2#1609]
Hi! First of all, great job with the repo!

Is possible to add support and documentation for exporting spatio-temporal action detection models?
I am trying to convert the models in [SlowOnly+Fast R-CNN](https://github.com/open-mmlab/mmaction2/blob/master/configs/detection/ava/README.md) to ONNX and after that to OpenVINO, and I have the same problem described on this [issue](https://github.com/open-mmlab/mmaction2/issues/1416).

Thanks!

**Comment by kennymckormick** [comment]
Hi, currently MMAction2 has no plan for supporting ONNX, but you may open an issue under https://github.com/open-mmlab/mmdeploy to see if they have time to help.
