### ISSUE TITLE
Tables in the docs of TIN are not correctly displayed

### ISSUE THREAD

**Issue by xwen99** [open-mmlab/mmaction2#161]
Thanks for your error report and we appreciate it a lot.

**Checklist**
1. I have searched related issues but cannot get the expected help.
2. The bug has not been fixed in the latest version.

**Describe the bug**
In the document of TIN under the Modelzoo section, some tables are not correctly displayed. \[[Link](https://mmaction2.readthedocs.io/en/latest/modelzoo.html#id30)\]
But it seems fine in the README of [TIN](https://github.com/open-mmlab/mmaction2/blob/master/configs/recognition/tin/README.md), therefore a re-compilation of the document may be required.

**Comment by dreamerlin** [comment]
Thanks for your report, it will be fixed in https://github.com/open-mmlab/mmaction2/pull/163
