### ISSUE TITLE
regarding something-somethingv2 dataset

### ISSUE THREAD

**Issue by Jeba-create** [open-mmlab/mmaction2#1612]
I have downloaded the something-somethingv2 dataset from here: https://developer.qualcomm.com/software/ai-datasets/something-something, but I could extract the videos only from the first folder using the command `'cat 20bn-something-something-v2-?? | tar zx`.

Please assist

**Comment by kennymckormick** [comment]
Hi, we don't know how to extract the raw data downloaded from QualComm, if you want to follow our preprocessing instructions, please first extract the downloaded files according to instructions provided by Qualcomm, and then follow our next steps.

**Comment by Jeba-create** [comment]
ok. Thanks for the reply
