### ISSUE TITLE
如何让tsn等动作识别模型在测试模式下输出的outputs为tensor格式，以获得梯度？

### ISSUE THREAD

**Issue by AndssY** [open-mmlab/mmaction2#1613]
Before raising a question, you may need to check the following listed items.
**Checklist**
1. I have searched related issues but cannot get the expected help.
yes
2. I have read the [FAQ documentation](https://mmaction2.readthedocs.io/en/latest/faq.html) but cannot get the expected help.
yes
背景：
我正在做攻击视频分类模型的任务，使用的是tsn模型，数据集为ucf101。
需求：
我有一个损失函数需要更新，这个损失函数和`result`有关。（或许有什么更好的解决方法吗？）我的思路是获得`result`相对于输入的梯度，这样我能够对损失函数进行更新。但是测试模式下预测结果是在`with torch.no_grad()`下进行的，而且`result`是`numpy`格式的。这个问题该如何解决呢？
```
# mmaction2-master\mmaction\apis
def single_gpu_test(model, data_loader):
......
    with torch.no_grad():
        result = model(return_loss=False, **data)
        results.extend(result)
```

**Comment by kennymckormick** [comment]
Hi, AndssY, 
You may manually modify the code of Recognizer2D, for example, you can return tensors in both forward_train and forward_test.

**Comment by AndssY** [comment]
I try to use 
```
 with torch.no_grad():
        result = model(return_loss=False, **data)
# and
  result = model(return_loss=True, **data)
```
at the same time to obtain the grad and cls_score.
