### ISSUE TITLE
How to normalize  box  in  train.csv and  val.csv  of AVA Action datasets ?

### ISSUE THREAD

**Issue by kuangxiaoye** [open-mmlab/mmaction2#1623]
I'm training a new behavior dataset, and after finishing the labeling, I found that the boxes in the ava dataset are normalized.

so the question is that how to normalize the box.

**Comment by kennymckormick** [comment]
The box format used in AVA  is like [x1 / img_width, y1 / img_height, x2 / img_width, y2 / img_height, score]. 
All final numbers are in [0, 1]. (x1, y1) is the up-left corner, (x2, y2) is the bottom-right corner.

**Comment by kuangxiaoye** [comment]
thank you！
