### ISSUE TITLE
Cannot download and process FineGym dataset.

### ISSUE THREAD

**Issue by akira-l** [open-mmlab/mmaction2#1625]
I tried several ways to download the video data, but always missing serveral videos.
As in this database:
`video 1Fdwuy2V9EY has not been downloaded or the event clip 1Fdwuy2V9EY_E_001714_001725 not generated video 1Fdwuy2V9EY has not been downloaded or the event clip 1Fdwuy2V9EY_E_001949_001983 not generated video 8WGrvkd6ZEU has not been downloaded or the event clip 8WGrvkd6ZEU_E_003255_003262 not generated video CkNz9ZIQmZI has not been downloaded or the event clip CkNz9ZIQmZI_E_004748_004827 not generated video Lt0HnPxdzHw has not been downloaded or the event clip Lt0HnPxdzHw_E_002642_002665 not generated video MDxIRDDWw1w has not been downloaded or the event clip MDxIRDDWw1w_E_000213_000221 not generated video PaVNLvldLeI has not been downloaded or the event clip PaVNLvldLeI_E_004849_004962 not generated video RLDjrhjikT4 has not been downloaded or the event clip RLDjrhjikT4_E_004334_004373 not generated video WCcSXjsCVMA has not been downloaded or the event clip WCcSXjsCVMA_E_001617_001624 not generated video bCDJ9CUBvqs has not been downloaded or the event clip bCDJ9CUBvqs_E_008147_008155 not generated video bCDJ9CUBvqs has not been downloaded or the event clip bCDJ9CUBvqs_E_008227_008235 not generated video mQ59PLtU4QA has not been downloaded or the event clip mQ59PLtU4QA_E_002522_002566 not generated video mQ59PLtU4QA has not been downloaded or the event clip mQ59PLtU4QA_E_002650_002678 not generated video om-qKQXxnH4 has not been downloaded or the event clip om-qKQXxnH4_E_000865_000903 not generated video qBlozVQ7NOc has not been downloaded or the event clip qBlozVQ7NOc_E_005112_005218 not generated video uDZVn-K4GE4 has not been downloaded or the event clip uDZVn-K4GE4_E_003068_003076 not generated video upaJ16I0zmQ has not been downloaded or the event clip upaJ16I0zmQ_E_001911_001917 not generated video wWwc2BbO598 has not been downloaded or the event clip wWwc2BbO598_E_000332_000340 not generated video wYbfwx93VXk has not been downloaded or the event clip wYbfwx93VXk_E_001326_001333 not generated`

I rerun the download shell in this repo serveral times and can not get the full video data in any available network environments. 

I also submitted the google form but did not achieve any responses.

**Comment by kennymckormick** [comment]
Please send an email to [sd017@ie.cuhk.edu.hk](mailto:sd017@ie.cuhk.edu.hk) for dataset request. 
![image](https://user-images.githubusercontent.com/34324155/167344516-60ec7fac-b538-417f-b330-5dfb483b492f.png)

**Comment by akira-l** [comment]
send email but be rejected ... 
![image](https://user-images.githubusercontent.com/9478838/167404898-cc8d58ba-7b36-4c6b-8139-67904962ceb1.png)
![image](https://user-images.githubusercontent.com/9478838/167404981-3ece6c56-c1fd-4a96-973e-0297ae0df98e.png)
![image](https://user-images.githubusercontent.com/9478838/167405026-62cb4877-c5cb-49c3-9721-840e6df3cca8.png)

**Comment by kennymckormick** [comment]
Hi Dr. Shao @sdolivia, there are some users who would like to access the full FineGYM Dataset but seems can not reach you via the old email, would you like to provide some supports if available? 

> send email but be rejected ... ![image](https://user-images.githubusercontent.com/9478838/167404898-cc8d58ba-7b36-4c6b-8139-67904962ceb1.png) ![image](https://user-images.githubusercontent.com/9478838/167404981-3ece6c56-c1fd-4a96-973e-0297ae0df98e.png) ![image](https://user-images.githubusercontent.com/9478838/167405026-62cb4877-c5cb-49c3-9721-840e6df3cca8.png)
