### ISSUE TITLE
ValueError: could not convert string to float: 'test'

### ISSUE THREAD

**Issue by mbilalshaikh** [open-mmlab/mmaction2#1626]
1. I have searched related issues but cannot get the expected help.
2. The bug has not been fixed in the latest version.

I have just downloaded the kinetics 400 dataset and now trying to generate the video files list using the provided script. It is not generating the file and throwing this error.

**Reproduction**

1. What command or script did you run?

```
bash generate_videos_filelist.sh kinetics400
```

2. Did you make any modifications on the code or config? Did you understand what you have modified?

No modification. I have not downloaded the test dataset only the train and validation set.

4. What dataset did you use?
kinetics400 downloaded via cvf
**Environment**

1. Please run `PYTHONPATH=${PWD}:$PYTHONPATH python mmaction/utils/collect_env.py` to collect necessary environment information and paste it here.

sys.platform: linux
Python: 3.7.11 (default, Jul 27 2021, 14:32:16) [GCC 7.5.0]
CUDA available: True
GPU 0,1,2,3,4,5,6,7: GeForce GTX 1080 Ti
CUDA_HOME: /usr
NVCC: Cuda compilation tools, release 10.0, V10.0.130
GCC: gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
PyTorch: 1.4.0+cu100
PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - Intel(R) Math Kernel Library Version 2019.0.4 Product Build 20190411 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v0.21.1 (Git Hash 7d2fd500bc78936d1d648ca713b901012f470dbc)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CUDA Runtime 10.0
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_37,code=compute_37
  - CuDNN 7.6.3
  - Magma 2.5.1
  - Build settings: BLAS=MKL, BUILD_NAMEDTENSOR=OFF, BUILD_TYPE=Release, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -fopenmp -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -O2 -fPIC -Wno-narrowing -Wall -Wextra -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Wno-stringop-overflow, DISABLE_NUMA=1, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, USE_CUDA=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_STATIC_DISPATCH=OFF, 

TorchVision: 0.5.0+cu100
OpenCV: 4.5.3
MMCV: 1.3.11
MMCV Compiler: GCC 7.5
MMCV CUDA Compiler: 10.0
MMAction2: 0.18.0+fe9fea0

3. You may add addition that may be helpful for locating the problem, such as
    - How you installed PyTorch [e.g., pip, conda, source]
    - Other environment variables that may be related (such as `$PATH`, `$LD_LIBRARY_PATH`, `$PYTHONPATH`, etc.)

**Error traceback**

If applicable, paste the error traceback here.

```
We are processing kinetics400
Traceback (most recent call last):
  File "tools/data/build_file_list.py", line 268, in <module>
    main()
  File "tools/data/build_file_list.py", line 206, in main
    splits = parse_kinetics_splits(args.level, args.dataset)
  File "/home/muhammadbsheikh/workspace/projects/mmaction/mmaction2/tools/data/parse_file_list.py", line 385, in parse_kinetics_splits
    test_list = [line_to_map(x, test=True) for x in csv_reader]
  File "/home/muhammadbsheikh/workspace/projects/mmaction/mmaction2/tools/data/parse_file_list.py", line 385, in <listcomp>
    test_list = [line_to_map(x, test=True) for x in csv_reader]
  File "/home/muhammadbsheikh/workspace/projects/mmaction/mmaction2/tools/data/parse_file_list.py", line 352, in line_to_map
    video = f'{x[1]}_{int(float(x[2])):06d}_{int(float(x[3])):06d}'
ValueError: could not convert string to float: 'test'
Train filelist for video generated.
Traceback (most recent call last):
  File "tools/data/build_file_list.py", line 268, in <module>
    main()
  File "tools/data/build_file_list.py", line 206, in main
    splits = parse_kinetics_splits(args.level, args.dataset)
  File "/home/muhammadbsheikh/workspace/projects/mmaction/mmaction2/tools/data/parse_file_list.py", line 385, in parse_kinetics_splits
    test_list = [line_to_map(x, test=True) for x in csv_reader]
  File "/home/muhammadbsheikh/workspace/projects/mmaction/mmaction2/tools/data/parse_file_list.py", line 385, in <listcomp>
    test_list = [line_to_map(x, test=True) for x in csv_reader]
  File "/home/muhammadbsheikh/workspace/projects/mmaction/mmaction2/tools/data/parse_file_list.py", line 352, in line_to_map
    video = f'{x[1]}_{int(float(x[2])):06d}_{int(float(x[3])):06d}'
ValueError: could not convert string to float: 'test'
Val filelist for video generated.
```

**Comment by mbilalshaikh** [comment]
I fixed this issue.

**Comment by Bovey0809** [comment]
@mbilalshaikh how did you fix the issue? Could you please share the solution.

**Comment by Bovey0809** [comment]
for people who came across this issue, we can change such line in tools/data/parse_file_list.py:line_to_map
`video = f'{x[1]}_{int(float(x[2])):06d}_{int(float(x[3])):06d}'`
to 
` video = f'{x[0]}_{int(x[1]):06d}_{int(x[2]):06d}`

**Comment by qingtong33** [comment]
wolf-bailang's method works

**Comment by Parseargs** [comment]
> @mbilalshaikh This problem is because there is only the original video data of **train and val** in the kinetics400 dataset, and there is **no test video data**. But there is a separate test annotation file in the annotation file.
> 
> Run "bash generate_videos_filelist.sh kinetics400" you can see in "**parse_file_list.py**" **line 343-345**, "**test_file = f'data/{dataset}/annotations/kinetics_test.csv'**".
> 
> But didn't test the video data, so it went wrong. In fact, for the kinetics400 data set, the test data is the validation set data, as you can see from the code.
> 
> **So you can copy a validation set data and validation set annotation file, and change val to test. This method does not need to modify mmaction2 code.**

This guy's reply can figure problem. But still need some modification in `tools/data/parse_file_list.py: def parse_kinetics_splits def line_to_map`. In this snippet, comment out lines related to test_csv.
