### ISSUE TITLE
[Bug] Filepath matching with glob in tools/data/build_audio_features.py

### ISSUE THREAD

**Issue by yyccli** [open-mmlab/mmaction2#1628]
In file `tools/data/build_audio_features.py` line 300-302, we need to first find all audio files. 
```
files = glob.glob(
    osp.join(args.audio_home_path, '*/' * args.level, '*' + args.ext))
print(f'found {len(files)} files.')
```

However, the args in glob() are wrong.
For example, let's take `audio_home_path = /mmaction2/data/dataset_one/audios/train`, `level = 1`, `ext = '.wav'` 
then we will get the following path if we use osp.join():

![image](https://user-images.githubusercontent.com/25741435/167795003-8bc8fc1b-e730-407a-9d9c-ba992bbbe285.png)

Actually, the right path for above options should be:
`
/mmaction2/data/dataset_one/audios/train/*.wav
`

Well, when building rawframes(`tools/data/build_rawframes.py` line 245-246) or building audios(`tools/data/extract_audio.py` line 54), the src code all use the following style:

```
path_list = glob.glob( args.root + '/*' * args.level + '.' + args.ext)
```

Using this style, when encountering above options, we will get:
![image](https://user-images.githubusercontent.com/25741435/167796814-93d53327-89a2-4bdd-b9aa-41743f92375b.png)

That's a right path.

Finally:

1. in `tools/data/build_audio_features.py`, the usage of `osp.join()` is wrong and is not consist with other building or extracing files.
2. the `args.ext` in `tools/data/build_audio_features.py` is also not consist with other files. In this file it's `.wav` or others, but in other files, they are `wav`
3. if we want the `osp.join()` func works, it should be:
```
os.path.join(args.audio_home_path, '*/' * (args.level-1), '*' + args.ext)
```
![image](https://user-images.githubusercontent.com/25741435/167798172-9d585c64-2184-427c-a1cc-c9f424dd6660.png)

4. the way using:
```
path_list = glob.glob( args.root + '/*' * args.level + '.' + args.ext)
```
always works whether you give a path like `/xxx/xxx` or `/xxx/xxx/`. When given `/xxx/xxx/`, you may get a path like `xxx/xxx//*.wav`, this path works in glob(), but i'm not sure if it's elegant XD.
5. btw, the tutorial of data_preparation in audio module about prepare audio part: the `args: num-worker` in file `tools/data/extract_audio.py` is `args.num-worker`, in file `tools/data/build_audio_features.py` is `args.num-workers`. However in tutorial.md they both says `args.num-workers`. The `args: ext` in the former is e.g. `xxx`, in the later is e.g. `.xxx`. In tutorial.md, they are both `.xxx` (LOL)

**Comment by kennymckormick** [comment]
OK, we will try to fix this problem in these days. You are also encouraged to raise a fix PR if interested.
