### ISSUE TITLE
Help! RuntimeError: Given input size: (512x8x1x14). Calculated output size: (512x4x0x7). Output size is too small

### ISSUE THREAD

**Issue by xiangwentao666** [open-mmlab/mmaction2#1629]
Thank you for this toolkit!
I'm new to it and when I tried to run "test.py" with the C3D model you provided, the error occurred:
`RuntimeError: Given input size: (512x8x1x14). Calculated output size: (512x4x0x7). Output size is too small`
The rawframes(rgb frames and flow data) is extracted from a video not in the ucf101 dataset.
Actually, I've searched online for some resolutions, and I guess the reason why this error occurred is that **the size of my image is so small that when the output size of the 4th layer of the C3D model is (512x4x0x7).**
However, I don't know how to fix this problem.....Could you please give me some help?

**Comment by kennymckormick** [comment]
Hi, to use C3D model, the size of your input clip must be 16 x 112 x 112.
