### ISSUE TITLE
Where should I adjust the batch size of training

### ISSUE THREAD

**Issue by jhygithub123** [open-mmlab/mmaction2#1631]
Before raising a question, you may need to check the following listed items.

**Checklist**

1. I have searched related issues but cannot get the expected help.
2. I have read the [FAQ documentation](https://mmaction2.readthedocs.io/en/latest/faq.html) but cannot get the expected help.

**Comment by alitirmizi23** [comment]
Can I ask where? Does it depend on clip_len or num_clips?
