### ISSUE TITLE
long_video_demo.py weird output

### ISSUE THREAD

**Issue by soltkreig** [open-mmlab/mmaction2#1633]
Hi! I run long_video_demo.py on video contains any actions but see only "Preparing action recognition" and recognition starts working somewhere in the middle of the video.

**Comment by kennymckormick** [comment]
Would you please upload your result video? Perhaps the reason is we can only do recognition when we have got enough inputs, so that the script may not make predictions for the first 1 / 2 seconds.

**Comment by soltkreig** [comment]
In the short video recognition doesn't work at all. Sounds weird but about week ago everything worked well.
https://user-images.githubusercontent.com/69303309/168488032-c76152b7-8000-4df6-81c3-19abef6de24e.mp4

**Comment by soltkreig** [comment]
It looks like I found the solution - I should set num_clips=1 in the test pipeline in the config
