### ISSUE TITLE
Is there fusion config for PoseC3D?

### ISSUE THREAD

**Issue by XYZ-916** [open-mmlab/mmaction2#1642]
I can only find the keypoint config and limb config in https://github.com/open-mmlab/mmaction2/blob/master/configs/skeleton/posec3d/README.md
 
Where can I find the fusion config for PoseC3D?

Thank you!

**Comment by wangbo-zhao** [comment]
Hello！Thanks for your interest. The meaning of "fusion" is to simply adopt the softmax function to process the predictions from "keypoint" and "limb", generating the final fusion prediction. Hence, we do not provide the config.

**Comment by Xinxinatg** [comment]
> I can only find the keypoint config and limb config in https://github.com/open-mmlab/mmaction2/blob/master/configs/skeleton/posec3d/README.md
> 
> Where can I find the fusion config for PoseC3D?
> 
> Thank you!

Hi have you been able to fuse the rgb and pose features?
