### ISSUE TITLE
Suitable model for detecting multiple activities in untrimmed videos

### ISSUE THREAD

**Issue by khalidcawl** [open-mmlab/mmaction2#1645]
Before raising a question, you may need to check the following listed items.

**Checklist**

- [x] I have searched related issues but cannot get the expected help. 
- [x] I have read the [FAQ documentation](https://mmaction2.readthedocs.io/en/latest/faq.html) but cannot get the expected help.

Question:

Hi. Thank you for this cool library. I have a set of videos of NFL games. I have labels for player helmets (to train a detector) and I also have labels for when two players hit each other head to head. I would like to detect this activity (head to head collision) given an video input. Each frame in the video could have zero, one, or more impacts occuring at the same time, so it's not about classifying one single activity in an entire video (many of them could be happening and spread out). The detection part is done (I used MMDetection).

What model or approach would you suggest me to use in order to solve this? Any help would be very much appreciated. Thank you.

**Comment by yyccli** [comment]
Hi, i think this is a kind of Temporal Action Detection task? In mmAction2, they are called Action Detection Models. However, in mmAction2 there are not many SOTA models in this task. For Temporal Action Detection Task, you can refer to this https://github.com/Alvin-Zeng/Awesome-Temporal-Action-Localization may help.

**Comment by khalidcawl** [comment]
Thanks for the response. I am trying out C3D now. I will checkout the repo you linked.

**Comment by kennymckormick** [comment]
I think you can use object detection to solve this problem. For example, you can define "two helmet collision“ as an object and try to detect this object, which would be much simpler.
