### ISSUE TITLE
Error on demo_skeleton.py

### ISSUE THREAD

**Issue by zambranohally** [open-mmlab/mmaction2#1646]
Hi guys, I have issue when running demo_skeleton.py. See attached image..
Please help. Thank you
![Screenshot_5](https://user-images.githubusercontent.com/63218980/170178436-55173310-4604-46e1-b081-6e4a8811767e.png)

**Comment by zambranohally** [comment]
It's working on previous version v0.25.0

**Comment by kennymckormick** [comment]
Yes, probably that's due to an update about config in MMPose. 
We have updated our config to be compatible with the new MMPose, now it works with MMPose v0.26.0
