### ISSUE TITLE
Problems with different number of keypoints (custom dataset and ntu-120)

### ISSUE THREAD

**Issue by cspk17** [open-mmlab/mmaction2#1648]
Before raising a question, you may need to check the following listed items.

**Checklist**

1. I have searched related issues but cannot get the expected help.
2. I have read the [FAQ documentation](https://mmaction2.readthedocs.io/en/latest/faq.html) but cannot get the expected help.

Thank you for this excellent library!!

I am trying to train the PoseC3D model using both a custom dataset and a part of ntu-120 dataset.
But, i found that the number of keypoints are different from each other.

The ntu_pose_extraction.py extracts 17 keypoints, but the SxxxCxxxPxxxRxxxAxxx.skeleton has 25 keypoints for each person detection.
How can I use the output of ntu_pose_extraction.py and SxxxCxxxPxxxRxxxAxxx.skeleton together??

**Comment by kennymckormick** [comment]
Given a video, ntu_pose_extraction.py predicts the 2D skeleton sequences, while the *.skeleton files contain the 3D skeleton annotations. I'm afraid you can not use them jointly.
If you want to use NTURGB+D data jointly with your custom dataset to train a model, please use the 2D skeleton annotations for NTURGB+D instead, you can find the download links in [MMAction2](https://github.com/open-mmlab/mmaction2/tree/master/tools/data/skeleton) or [PYSKL](https://github.com/kennymckormick/pyskl/blob/main/tools/data/data_doc.md)

**Comment by cspk17** [comment]
@kennymckormick Thank you for your reply.
I will try to use the 2D skeleton annotations you mentioned!!
