### ISSUE TITLE
Model parameter dimension mismatch for TSN on HVU dataset

### ISSUE THREAD

**Issue by zhtmike** [open-mmlab/mmaction2#1649]
Thanks for your error report and we appreciate it a lot.
If you feel we have help you, give us a STAR! :satisfied:

**Checklist**

1. I have searched related issues but cannot get the expected help.
2. The bug has not been fixed in the latest version.

**Describe the bug**

When loading the pretrained model [tsn_r18_1x1x8_100e_hvu_concept_rgb_20201027-fc1dd8e3.pth](https://download.openmmlab.com/mmaction/recognition/tsn/hvu/concept/tsn_r18_1x1x8_100e_hvu_concept_rgb_20201027-fc1dd8e3.pth) using the corresponding [config](https://github.com/open-mmlab/mmaction2/blob/master/configs/recognition/tsn/hvu/tsn_r18_1x1x8_100e_hvu_concept_rgb.py), it raised the error

```
The model and loaded state dict do not match exactly

size mismatch for cls_head.fc_cls.weight: copying a param with shape torch.Size([291, 512]) from checkpoint, the shape in current model is torch.Size([1678, 512]).
size mismatch for cls_head.fc_cls.bias: copying a param with shape torch.Size([291]) from checkpoint, the shape in current model is torch.Size([1678]).
```
Seems the pretrained model above is for object category instead of concept category. 

**Reproduction**

1. What command or script did you run?

```
model = init_recognizer(config_file, checkpoint_file, device=device)
```

2. Did you make any modifications on the code or config? Did you understand what you have modified?
NO.
4. What dataset did you use?
HVU.

**Comment by zhtmike** [comment]
Just figure out it is due to wrong name in the [config](https://github.com/open-mmlab/mmaction2/blob/master/configs/recognition/tsn/hvu/tsn_r18_1x1x8_100e_hvu_concept_rgb.py) #10

**Comment by kennymckormick** [comment]
Thanks a lot for pointing this out, now we have fixed this problem.
