### ISSUE TITLE
How to extract perframe features using mmaction2?

### ISSUE THREAD

**Issue by Prot-debug** [open-mmlab/mmaction2#1651]
Hi,

I'm a beginner of video understanding. I have installed mmaction2 and denseflow, and it works well. But I'm not sure how to extract perframe features using it.

1. Is there any ready-made apis to solve the above problem? I've taken much time to search the solutions, but I didn't find.
2. If no ready-made apis, could you plz share related codes with us? It's important for beginners.
3. What is the difference between the config files eg. `tsn_r50_320p_1x1x8_50e_activitynet_clip_rgb.py`, `tsn_r50_320p_1x1x8_50e_activitynet_video_rgb.py` , specifically between video and clip?

Thank you for your awesome repo. And hope your reply.

**Comment by makecent** [comment]
By stating **extrat perframe features**, I am not sure what is the real case. But you may refer to this python file.
https://github.com/open-mmlab/mmaction2/blob/fda023269e0fd9ed7ac36d48c67d2b86d422d602/tools/data/activitynet/tsn_feature_extraction.py#L1

**Comment by kennymckormick** [comment]
Yes, you can refer to [mmaction2/tools/data/activitynet/tsn_feature_extraction.py](https://github.com/open-mmlab/mmaction2/blob/fda023269e0fd9ed7ac36d48c67d2b86d422d602/tools/data/activitynet/tsn_feature_extraction.py#L1) for frame-level feature extraction. 
The difference between two configs is: `clip_rgb` uses clip-level annotations to train the recognizer (only use the groundtruth segments), while `video_rgb` uses video-level annotations (the whole untrimmed video).

**Comment by Prot-debug** [comment]
@makecent Thanks a lot for your answer. It basically solved my problem. It works well now.

**Comment by Prot-debug** [comment]
@kennymckormick Thanks for your reply. So appreciate for your answer.

**Comment by Prot-debug** [comment]
@kennymckormick 

Another question that I met puzzled me for much time. 

When I use the `code` [mmaction2/tools/data/activitynet/tsn_feature_extraction.py](url) you mentioned above, it works well based on `rgb` modality to extract frame-level features. But when it comes to `flow` modality, I don't know how to extract chunk-level features. 

For example, if I set the size of chunk is 6, that is, the num of rgb frames is 6, accordingly num of flow frames is 5 ( 5x and 5y, total 10 frames). My question is that how to set these parameters to achive my goal, eg `clip_len`, `frame_interval`, `num_frames`, etc. Thank you.

**Comment by kennymckormick** [comment]
Hi, Prot-debug,
For flow, I think nothing is different. For example, if a video consists of 300 frames, you can still get 300 flow features. You can set each frame as the center frame in 5x, 5y and find two frames before and after the current frame respectively. If the neighboring frames are not available, you can use zero-flow (all pixels are 128) instead.
