### ISSUE TITLE
2D骨骼图的行为识别算法

### ISSUE THREAD

**Issue by QueenW1998** [open-mmlab/mmaction2#1655]
请问支持2D状态下对骨骼图的行为识别算法吗？是否可以采用自己的数据集或者数据集格式是哪种？
望回复，感谢！

**Comment by Dai-Wenxun** [comment]
Hi, @QueenW1998 
You can refer to this [config](https://github.com/open-mmlab/mmaction2/blob/master/configs/skeleton/stgcn/stgcn_80e_ntu60_xsub_keypoint.py) for 2d skeleton recognition, the dataset format can refer to [ntu60_xsub_train.pkl](https://download.openmmlab.com/mmaction/posec3d/ntu60_xsub_train.pkl).

**Comment by QueenW1998** [comment]
请问这个模型里面使用到的特征提取的方法是什么呢，骨骼关键点的识别有没有采用openpose的方法的，GCN主要是用来对已经提取到的骨骼图进行的行为识别吗。有关于这个模型网络框架介绍的文档或者论文吗，或者是有没有相关视频的讲解呢？感谢！

**Comment by Dai-Wenxun** [comment]
- The 2d keypoints of [ntu60_xsub_train.pkl](https://download.openmmlab.com/mmaction/posec3d/ntu60_xsub_train.pkl) are obtained from this paper ([poseconv3d](https://arxiv.org/abs/2104.13586)), it adopts 2D Top-Down pose
estimators for pose extraction, of course, you can also use openpose to extract skeleton keypoint coordinates. 
- GCN-based methods for action recognition are applied on extracted skeleton keypoints. You can refer to this [stgcn](https://ojs.aaai.org/index.php/AAAI/article/view/12328) for more details.

**Comment by QueenW1998** [comment]
你能告诉我“(2021-10-29) 支持基于 skeleton 模态和 rgb 模态的时空动作检测和行为识别 demo (demo/demo_video_structuralize.py)。”这个脚本和采用poseconv3d的区别吗？分别是采用的什么数据集呢？我可以采用自己的数据集进行训练吗，请问有对这个模型的数据集制作的讲解吗？
