### ISSUE TITLE
Posec3d datasets

### ISSUE THREAD

**Issue by zambranohally** [open-mmlab/mmaction2#1656]
Hi Good day, I just want to ask what video resolution is best for training action detection.? Thank you in advance...

**Comment by hukkai** [comment]
If you mean spatial-temporal action detection, you can have a look at [AVA dataset](https://github.com/open-mmlab/mmaction2/blob/master/tools/data/ava/README.md).

**Comment by zambranohally** [comment]
@hukkai Im using skeleton action detection..

**Comment by kennymckormick** [comment]
Hi, zambranohally, 
If you mean the pose extraction part, I think it depends on the human scale in your video. Generally, I think a >= 256 pixel short edge is good enough for pose extraction.

**Comment by zambranohally** [comment]
@kennymckormick Thank you so much...
