### ISSUE TITLE
demo_skeleton.py报错

### ISSUE THREAD

**Issue by QueenW1998** [open-mmlab/mmaction2#1657]
在运行demo_skeleton.py时报错，麻烦帮忙解决，谢谢。
E:\Anaconda\envs\mmact2_skeleton\python.exe H:/WH/MM/mmaction2-0.22.0/demo/demo_skeleton.py
load checkpoint from local path: H:/WH/MM/mmaction2-0.22.0/weights/stgcn_80e_ntu60_xsub_keypoint-e7bb9653.pth
Traceback (most recent call last):
  File "H:/WH/MM/mmaction2-0.22.0/demo/demo_skeleton.py", line 259, in <module>
    main()
  File "H:/WH/MM/mmaction2-0.22.0/demo/demo_skeleton.py", line 208, in main
    det_results = detection_inference(args, frame_paths)
  File "H:/WH/MM/mmaction2-0.22.0/demo/demo_skeleton.py", line 156, in detection_inference
    model = init_detector(args.det_config, args.det_checkpoint, args.device)
  File "H:\WH\MM\mmaction2-0.22.0\mmaction\utils\decorators.py", line 12, in new_func
    raise ImportError(
ImportError: Please install mmdet to use init_detector. For OpenMMLAB codebases, you may need to install mmcv-full first before you install the particular codebase. 

Process finished with exit code 1

**Comment by hukkai** [comment]
As the error suggested, you need to install [MMDetection](https://github.com/open-mmlab/mmdetection) first for skeleton demo.

**Comment by kennymckormick** [comment]
Please follow the instruction in our error message:
```
Please install mmdet to use init_detector. For OpenMMLAB codebases, you may need to install mmcv-full first before you install the particular codebase.
```

**Comment by QueenW1998** [comment]
Fine，thank you very much!
