### ISSUE TITLE
Test C3D wiht UCF101 .No Errors but the reported top_k_accuracy is too low 

### ISSUE THREAD

**Issue by kblittle** [open-mmlab/mmaction2#1664]
Thanks for your toolkit!

**Checklist**

1. I have searched related issues but cannot get the expected help.
2. The bug has not been fixed in the latest version.

**Describe the bug**

  I'm new to it and when I tried to run "test.py" with the C3D model you provided.
  There is **No Errors** but the reported top_k_accuracy is too low ,seems something wrong.
   I have carefully followed getting_started.md.

**Reproduction**

1. What command or script did you run?

```
python tools/test.py configs/recognition/c3d/c3d_sports1m_16x1x1_45e_ucf101_rgb.py     checkpoints/c3d_sports1m_16x1x1_45e_ucf101_rgb_20201021-26655025.pth --eval top_k_accuracy
```

2. Did you make any modifications on the code or config? Did you understand what you have modified?
   I have changed the config with this https://github.com/open-mmlab/mmaction2/issues/1495
   
        _base_ = '../../_base_/models/c3d_sports1m_pretrained.py'
        dataset_type = 'VideoDataset'
        data_root = 'data/ucf101/video_train'
        data_root_val = 'data/ucf101/video_val'
        split = 1  # official train/test splits. valid numbers: 1, 2, 3
        ann_file_train = f'data/ucf101/ucf101_train_split_{split}_video.txt'
        ann_file_val = f'data/ucf101/ucf101_val_split_{split}_video.txt'
        ann_file_test = f'data/ucf101/ucf101_val_split_{split}_video.txt'
        img_norm_cfg = dict(mean=[104, 117, 128], std=[1, 1, 1], to_bgr=False)
        train_pipeline = [
            dict(type='DecordInit'),
            dict(type='SampleFrames', clip_len=32, frame_interval=2, num_clips=1),
            dict(type='DecordDecode'),
        ]
        val_pipeline = [
            dict(type='DecordInit'),
            dict(
                type='SampleFrames',
                clip_len=16,
                frame_interval=1,
                num_clips=1,
                test_mode=True),
            dict(type='DecordDecode'),
        ]
        test_pipeline = [
            dict(type='DecordInit'),
            dict(
                type='SampleFrames',
                clip_len=16,
                frame_interval=1,
                num_clips=10,
                test_mode=True),
            dict(type='DecordDecode'),
        ]
4. What dataset did you use?
UCF-101 video dataset  not rawframe

**Comment by kblittle** [comment]
I have fixed it by convert video to rawframes ,follow this https://github.com/open-mmlab/mmaction2/blob/master/docs/data_preparation.md . But the issue still exist.Hope someone can provide cues.

**Comment by hukkai** [comment]
@kblittle  could you check again that there is no error? I tried to use *decord* to read videos but I found this video cannot be decoded by *decord* but pyav could:

ApplyEyeMakeup/v_ApplyEyeMakeup_g01_c02.avi

md5sum: 95c3482868de6e62d8925aaa2bb72f2e

**Comment by kblittle** [comment]
Actually,i extract videos to rawframes,follow this https://github.com/open-mmlab/mmaction2/blob/master/docs/data_preparation.md ,which means the type of data is rawframes,not videos @hukkai
