### ISSUE TITLE
RuntimeError: ONNX export failed: Couldn't export Python operator TINShiftFunction

### ISSUE THREAD

**Issue by wojiaohumaocheng** [open-mmlab/mmaction2#1665]
when convert tin to onnx meet this issue:

RuntimeError: tin_shift_forward_impl: implementation for device cpu not found.

env:
sys.platform: linux
Python: 3.8.10 (default, Jun  2 2021, 10:49:15) [GCC 9.4.0]
CUDA available: True
GPU 0,1: Tesla T4
CUDA_HOME: /usr/local/cuda
NVCC: Cuda compilation tools, release 11.4, V11.4.120
GCC: x86_64-linux-gnu-gcc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
PyTorch: 1.9.1+cu111
PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2020.0.0 Product Build 20191122 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.1.2 (Git Hash 98be7e8afa711dc9b66c8ff3504129cb82013cdb)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 11.1
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86
  - CuDNN 8.0.5
  - Magma 2.5.2
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.1, CUDNN_VERSION=8.0.5, CXX_COMPILER=/opt/rh/devtoolset-7/root/usr/bin/c++, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.9.1, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, 

TorchVision: 0.10.1+cu111
OpenCV: 4.6.0
MMCV: 1.5.2
MMCV Compiler: GCC 7.3
MMCV CUDA Compiler: 11.1
MMAction2: 0.24.0+758ddc2

**Comment by kennymckormick** [comment]
Hi,
TIN_SHIFT OP has no CPU implementation, please use GPU for training and testing of TIN.

**Comment by wojiaohumaocheng** [comment]
> Hi, TIN_SHIFT OP has no CPU implementation, please use GPU for training and testing of TIN.
I run this command in gpu environment. I have tried tin mode with gpu, then I want to convert latest.pth to onnx, when i use this commad
"python tools/development/pytorch2onnx.py xxx.py xxx.pth --shape 1 8 3 224 224 --verify", 
i will meet this problem
  could u help me sovlce this problem thx

**Comment by wojiaohumaocheng** [comment]
> Hi, TIN_SHIFT OP has no CPU implementation, please use GPU for training and testing of TIN.



I have channged   one part in pytorch2onnx.py
#model.cpu().eval()
model.cuda().eval()
#input_tensor = torch.randn(input_shape)
 nput_tensor = torch.randn(input_shape).cuda() 

but now new issue  generate"RuntimeError: ONNX export failed: Couldn't export Python operator TINShiftFunction"

**Comment by kennymckormick** [comment]
Perhaps this model doesn't support onnx since it contains a custom OP. Maybe you can try some other alternatives. AFAIK, TIN doesn't not have any unique advantages.
