### ISSUE TITLE
train a recognizer on cpu for debug

### ISSUE THREAD

**Issue by Bruce-Si** [open-mmlab/mmaction2#1675]
MMaction2 supports training with CPU for debug, I want to know how to set the data.videos_per_gpu in the config file since there is no gpu...

**Comment by makecent** [comment]
You should get no error without modification. When training with the CPU, the `videos_per_gpu` becomes the `batch_size`. (`batch_size` = `num_gpus` x `videos_per_gpu` when training with multiple GPUs)

**Comment by Bruce-Si** [comment]
> You should get no error without modification. When training with the CPU, the `videos_per_gpu` becomes the `batch_size`. (`batch_size` = `num_gpus` x `videos_per_gpu` when training with multiple GPUs)

Thank you for reply, but I got `AttributeError: 'ConfigDict' object has no attribute 'gpu_ids'` with CPU train.

**Comment by Bruce-Si** [comment]
The command is `python ./tools/train.py configs/detection/ava/slowfast_kinetics_pretrained_r50_8x8x1_20e_ava_rgb.py`

**Comment by makecent** [comment]
> > You should get no error without modification. When training with the CPU, the `videos_per_gpu` becomes the `batch_size`. (`batch_size` = `num_gpus` x `videos_per_gpu` when training with multiple GPUs)
> 
> Thank you for reply, but I got `AttributeError: 'ConfigDict' object has no attribute 'gpu_ids'` with CPU train.

The problem should not come from the setting of `videos_per_gpu`. How do you make the training working on the CPU?

**Comment by makecent** [comment]
Could u pls try adding `--gpus 2` after your command? i.e., excute the command `python ./tools/train.py configs/detection/ava/slowfast_kinetics_pretrained_r50_8x8x1_20e_ava_rgb.py --gpus 2`

**Comment by Bruce-Si** [comment]
> Could u pls try adding `--gpus 2` after your command? i.e., excute the command `python ./tools/train.py configs/detection/ava/slowfast_kinetics_pretrained_r50_8x8x1_20e_ava_rgb.py --gpus 2`

It works! Thank you! But why we have to set `--gpus 2`

**Comment by makecent** [comment]
> > Could u pls try adding `--gpus 2` after your command? i.e., excute the command `python ./tools/train.py configs/detection/ava/slowfast_kinetics_pretrained_r50_8x8x1_20e_ava_rgb.py --gpus 2`
> 
> It works! Thank you! But why we have to set `--gpus 2`

You can take it as a bug. `mmaction2` does not handle the arguments `gpu_ids` and `num_gpus` well.
