### ISSUE TITLE
custom dataset

### ISSUE THREAD

**Issue by QueenW1998** [open-mmlab/mmaction2#1677]
How to make the format of data sets if you use custom data sets for training in configs\skeleton\2s-agcn,posec3d  and stgcn。

**Comment by makecent** [comment]
You may need to decribe your issue more clearly. 

- About the registry, you may refer to this [tutorial](https://github.com/open-mmlab/mmaction2/blob/master/docs/tutorials/3_new_dataset.md). 
- About the format, you may follow the orginal dataset class used in the configs. 
- As for the customization, you are the only one that know how to customize the class to meet your requirement.

**Comment by kennymckormick** [comment]
For skeleton action recognition, it's a good idea to move to our new repo [PYSKL](https://github.com/kennymckormick/pyskl), where we provide a [comprehensive tutorial](https://github.com/kennymckormick/pyskl/blob/main/examples/extract_diving48_skeleton/diving48_example.ipynb) about how to train your custom dataset for skeleton action recognition.
