### ISSUE TITLE
转为onnx后做验证，显存暴增

### ISSUE THREAD

**Issue by yanyide123** [open-mmlab/mmaction2#1681]
为什么将模型转为onnx后做验证，显存暴增

**Comment by hukkai** [comment]
@yanyide123 Could you show more details for example how you converted your model to onnx format? Thanks.

**Comment by yanyide123** [comment]
> 
MMAction2提供了一个python脚本，就是按照它提供的脚本导出的，但会报一些警告，然后再将一些无用的删除就可以了

**Comment by yanyide123** [comment]
> @yanyide123 Could you show more details for example how you converted your model to onnx format? Thanks.

![image](https://user-images.githubusercontent.com/72483328/174996808-ca4dcf7a-14cf-4e13-a9f0-52279032b05f.png)

**Comment by hukkai** [comment]
@ yanyide123 I mean which model and what exact script did you use. Otherwise we cannot reproduce your problem.

**Comment by hukkai** [comment]
@yanyide123 If you have any questions, feel free to re-open the issue. Thanks!
