### ISSUE TITLE
Can you increase the video output of mmaction2 on the web side?

### ISSUE THREAD

**Issue by MintonLee** [open-mmlab/mmaction2#1691]
Thanks for your feature request and we will review and plan for it when necessary.
If you feel we have help you, give us a STAR! :satisfied:

**Describe the feature**
I have already done related work. The first method is to push the stream, which is to use ffmpeg to push the rtmp video stream through microservices such as srs/nginx. The second method is to display the processed video stream on the web side through flask.

**Motivation*.

A clear and concise description of the motivation of the feature.
Ex1. It is inconvenient when \[....\].
Ex2. There is a recent paper \[....\], which is very helpful for \[....\].

**Related resources**

If there is an official code released or third-party implementations, please also provide the information here, which would be very helpful.

**Additional context**

If you would like to implement the feature and create a PR, please leave a comment here and that would be much appreciated.

**Comment by hukkai** [comment]
@MintonLee Not very familiar with this. Could you submit a PR?
