### ISSUE TITLE
APIs for Action Detection models similar to Action Recognition (e.g init_recognizer, inference_recognizer etc) 

### ISSUE THREAD

**Issue by alitirmizi23** [open-mmlab/mmaction2#1692]
**Checklist**

1. I have searched related issues but cannot get the expected help.
2. I have read the [FAQ documentation](https://mmaction2.readthedocs.io/en/latest/faq.html) but cannot get the expected help.

I have tried to look for something similar to init_recognizer and inference_recognizer in mmaction apis, but couldn't find anything that would help with "Action detection" models like slowonly_omnisource_pretrained_r101_8x8x1_20e_ava_rgb etc. It seems only recognizer models have such an api and i'd have to somehow use the webcam spatiotemporal action detection demo to create my own api for just inference (not necessarily showing results on webcam etc). 

Any help here would be appreciated. I'm trying to have just a basic api to call inference on, lets say, a 10 sec video and have the output results dictionary available, just like with init_recognizer and inference_recognizer.

**Comment by hukkai** [comment]
Maybe these codes can help you? 
https://github.com/open-mmlab/mmaction2/blob/12f16c15b02681a596323bafeac5b2e97cae7f3b/demo/demo_spatiotemporal_det.py#L345-L350

**Comment by hukkai** [comment]
@alitirmizi23  If you have any questions, feel free to re-open the issue. Thanks!
