### ISSUE TITLE
training slowonly on custom AVA-alike dataset with multiple objects(human) and multiple type of actions

### ISSUE THREAD

**Issue by Xinxinatg** [open-mmlab/mmaction2#1693]
Before raising a question, you may need to check the following listed items.

**Checklist**

1. I have searched related issues but cannot get the expected help.
2. I have read the [FAQ documentation](https://mmaction2.readthedocs.io/en/latest/faq.html) but cannot get the expected help.

Thanks for the wonderful work! I am planning to deploly the slowonly action recognition model for real time inference. While looking through the instruction for training slowonly, there are only examples for kinetics and sthv1 dataset, in which for each footage there is only one action type and one human. I am wondering whether there would be instruction on how to train model on custom AVA-alike dataset? I am assuming that Faster-RCNN will be used to generate a bbox for pre-processing?

**Comment by hukkai** [comment]
@Xinxinatg Do you want to train detection(e.g., https://github.com/open-mmlab/mmaction2/blob/master/configs/detection/ava/README.md) models or just multi-class multi label recognition models?

**Comment by Xinxinatg** [comment]
@hukkai Thanks for your promt reply! Can I know the difference between detection and recognition models? I was look at this page just now https://github.com/open-mmlab/mmaction2/tree/master/configs/recognition/slowonly

**Comment by hukkai** [comment]
@Xinxinatg  Recognition models are to predict the categories (one or more) of the video clip, for example Kinetics and Something-something. Charades dataset is another example while each video in this dataset can have more than one label. Detection models are to predict the bounding boxes together with the categories of the bounding boxes. for example AVA dataset.

**Comment by Xinxinatg** [comment]
@hukkai Sure got it! I would like to train the detection model in this regard. Will there be any instructions on how to process custom dataset for the detection model?

**Comment by hukkai** [comment]
@Xinxinatg You can refer to this example: https://github.com/open-mmlab/mmaction2/blob/master/tools/data/ava/README.md. But you may need to generate the human proposals for your dataset.

**Comment by Xinxinatg** [comment]
@hukkai Sure thanks! will try this
