### ISSUE TITLE
Any plan to support multiview transformer?

### ISSUE THREAD

**Issue by realgump** [open-mmlab/mmaction2#1696]
As the multiview transformer _Multiview Transformers for Video Recognition_ gets SOTA in Kinetics-400, Kinetics-700, and performs great in most of action recognition tasks, is there a plan to support multiview transformer in _mmaction2_?

**Comment by hukkai** [comment]
@realgump Several SOTA (transformer based) video models will be supported in the next several months such as MViT, Video Swin, etc. However, I am not sure about the timeline of the Multiview Transformer model. If you can contribute, it will be very appreciated, thanks!

**Comment by hukkai** [comment]
@realgump If you have any questions, feel free to re-open the issue. Once the model is supported, I will also pin you. Thanks!
