### ISSUE TITLE
Memory usage

### ISSUE THREAD

**Issue by TalBarami** [open-mmlab/mmaction2#1700]
Hello,
I'm training the PoseC3D model on my custom dataset.
My dataset file weighs 30GB, yet I noticed that the training code takes almost all of my 64GB RAM. So I wondered why and if I could do something to ease the memory usage.
For instance, I thought to implement my dataset, which loads the requested data samples from the disk on demand rather than on start up. Do you think it'd be a better solution for such a case?
I appreciate any help you can provide.
Thanks!

**Comment by hukkai** [comment]
@TalBarami Do you mean CPU memory?

**Comment by TalBarami** [comment]
I mean RAM - here's an example from the current usage:
![image](https://user-images.githubusercontent.com/18405843/178159105-4a4d55d2-3e3b-4260-985a-b3e1b1f98012.png)

**Comment by hukkai** [comment]
As I understand it, the dataset is stored on the disk and will not be loaded into RAM completely.

**Comment by hukkai** [comment]
If you need further discussion, feel free to re-open this issue. Thanks!
