### ISSUE TITLE
some questions about the pretrained2d model in resnet3d

### ISSUE THREAD

**Issue by Caicaizi-cdy** [open-mmlab/mmaction2#1701]
Thank you for sharing such excellent work.

I feel confused about the parameter pretrained2d(bool): Whether to load pretrained 2D model. Default: True, In class ResNet3d in /mmaction/models/backbones/resnet3d.py.

1. In the original code, self.pretrained2d = True, I think it means you use the pretrained 2D model. However I can't find the loaded pretrained 2D model and I don't know where the pretrained 
model is loaded(torchvision?or other places? I can't find the relative code to appoint it).
在原始代码中，我找不到pretrained2d=True的时候预训练模型到底是从哪个地方加载的以及加载的是什么预训练模型，也不太清楚要在具体的哪段代码中进行什么样的设置才能加载/不加载这个2维的预训练模型

2. If I set pretrained2d = False, Can I still train normally? Will the final result be much worse than when loading the pretrained 2D model?
如果我设置pretrained2d = False，那么代码还能正常运行吗？此时的效果会不会变差呢？

Sincerely hope to get your reply!
希望能够得到您的回复！谢谢！

**Comment by hukkai** [comment]
@Caicaizi-cdy The weights are loaded here: https://github.com/open-mmlab/mmaction2/blob/12f16c15b02681a596323bafeac5b2e97cae7f3b/mmaction/models/backbones/resnet3d.py#L835 and eventually here https://github.com/open-mmlab/mmaction2/blob/12f16c15b02681a596323bafeac5b2e97cae7f3b/mmaction/models/backbones/resnet3d.py#L690

You can specify this in the config file, for example here:
https://github.com/open-mmlab/mmaction2/blob/12f16c15b02681a596323bafeac5b2e97cae7f3b/configs/_base_/models/i3d_r50.py#L6-L7

You can use **pretrained=None** to train the model from scratch, but requires much more epochs to make the model converge. Please let me you if you have more questions, thanks!

**Comment by Caicaizi-cdy** [comment]
> 
Thank you for your answer. I understand

**Comment by Caicaizi-cdy** [comment]
@hukkai Thank you for your answer. I understand!

**Comment by hukkai** [comment]
@Caicaizi-cdy If you have any questions, feel free to re-open the issue. Thanks!
