### ISSUE TITLE
Custom Dataset Training for Activity Recognition

### ISSUE THREAD

**Issue by ashmalvayani** [open-mmlab/mmaction2#1704]
I have first tried the custom dataset training and inference model for i3d which is for action recognition (single class per video)

Now I want to train the same model for Activity Recognition (Multiple classes per video, or series of steps through frames)

I've checked the tutorial for adding a new custom class as shown below for multi class
https://mmaction2.readthedocs.io/en/latest/tutorials/3_new_dataset.html#an-example-of-a-custom-dataset

.. code-block:: txt
        some/directory-1 163 1 3 5
        some/directory-2 122 1 2
        some/directory-3 258 2
        some/directory-4 234 2 4 6 8
        some/directory-5 295 3
        some/directory-6 121 3

I just wanted to ask that how can I label or provide annotations (preferably per frame wise) in a way that while training and testing my model can detect series of actions in the video and not just one class in the video like kinetics (one class per video)

**Comment by hukkai** [comment]
As I understand it, the actions happen in a duration of video clips. So when you label the actions per frame wise, the action label represents the action of the video clip (several frames) centered at that frame? Maybe you can create a new dataset where a video is a video clip of the original video. You can use softlink to avoid using too much disk.

**Comment by ashmalvayani** [comment]
that might work till the training part where I make subset of video clips from the original video and call it a one separate video. then what about the testing part? I want my model to detect all the series of activities in the output and not just one class. I can't clip that because annotations for that won't be known to me prior.

**Comment by hukkai** [comment]
Sorry I close the issue by mistake. I think it still works for testing. Since every frames may have labels. You also need to generate the fake video clip for the test videos and do inference for every video clip. So the only problem is how to handle multi-label multi-class classification -- did you know how to solve this issue?

**Comment by ashmalvayani** [comment]
If I do what you're saying, then the results won't be comparable, intuitional knowledge will have high variational and wouldn't be directly comparable. Model would not work in a case where one action is transitioning to another and or if some occlusions are occurring. 
If there's a way to cater annotations per frame wise instead of video vise then yes the problem can be solved.

**Comment by hukkai** [comment]
You can have a look at the AVA dataset where the action annotations are at every second and some related models implemented in mmaction2. However, I do not think the *transition* between actions can provide significant improvements since the SOTA method on AVA did not make use of it.

**Comment by ashmalvayani** [comment]
How do I label each frame in the annotations then? 

some/directory-1 163 1
some/directory-2 122 1
some/directory-3 258 2
some/directory-4 234 2
some/directory-5 295 3
some/directory-6 121 3

this is the normal annotation.txt file which is for video classifier (action recognition), now in my case I have to classify multiple classes in a video based on their timestamp so that my model know which task is done when/
