### ISSUE TITLE
Fail to extract features of Thumos14

### ISSUE THREAD

**Issue by qingtong33** [open-mmlab/mmaction2#1705]
Before raising a question, you may need to check the following listed items.

**Checklist**

1. I have searched related issues but cannot get the expected help.
2. I have read the [FAQ documentation](https://mmaction2.readthedocs.io/en/latest/faq.html) but cannot get the expected help.

I want to extract features of the thumos14 dataset with a pre-trained x3d model.
Then I read https://github.com/open-mmlab/mmaction2/tree/master/docs_zh_CN)/feature_extraction.md and used its format. 

This is my command:
python tools/misc/clip_feature_extraction.py 
configs/recognition/x3d/x3d_m_16x5x1_facebook_kinetics400_rgb.py 
https://download.openmmlab.com/mmaction/recognition/x3d/facebook/x3d_m_facebook_16x5x1_kinetics400_rgb_20201027-3f42382a.pth
--video-list thumos14test.txt 
--video-root data/thumos14/videos/test
--out TH14_test_feature.pkl

Those are some example of my video list
video_test_0000001.mp4
video_test_0000002.mp4
video_test_0000003.mp4
video_test_0000004.mp4
video_test_0000005.mp4
video_test_0000006.mp4
video_test_0000007.mp4
video_test_0000008.mp4
video_test_0000009.mp4
video_test_0000010.mp4
video_test_0000011.mp4
video_test_0000012.mp4

The error is:
Traceback (most recent call last):
  File "tools/misc/clip_feature_extraction.py", line 229, in <module>
    main()
  File "tools/misc/clip_feature_extraction.py", line 162, in main
    assert dataset_type == 'VideoDataset'
AssertionError

I test the given example of UCF101 dataset. It works well. I dont know what's the problem. Is it because of the different video format between avi and mp4? 

Thanks for help.

**Comment by hukkai** [comment]
@qingtong33 The config you're using is a *RawframeDataset* type dataset:
https://github.com/open-mmlab/mmaction2/blob/12f16c15b02681a596323bafeac5b2e97cae7f3b/configs/recognition/x3d/x3d_m_16x5x1_facebook_kinetics400_rgb.py#L4

You need to adjust the config file to extract features from your dataset

**Comment by qingtong33** [comment]
@hukkai Thank you. I wrote a new config file of X3D and solved this problem.
