### ISSUE TITLE
can't run the demo in action2

### ISSUE THREAD

**Issue by Juliaququ** [open-mmlab/mmaction2#1731]
Here is the demo:
`from mmaction.apis import init_recognizer, inference_recognizer

model_path = "../ModelPTH/models--mmlab--action-recognition"
config_file = model_path + '/tsn_r50_video_inference_1x1x3_100e_kinetics400_rgb.py'
                            
checkpoint_file = model_path + '/tsn_r50_1x1x3_100e_kinetics400_rgb_20200614-e508be42.pth'

label = model_path + '/label_map_k400.txt'

model = init_recognizer(config_file, checkpoint_file, device='cuda:0')

video = 'C2rDp6FnbP0_10_17.avi'

results = inference_recognizer(model, video)

labels = open(label).readlines()
labels = [x.strip() for x in labels]
results = [(labels[k[0]], k[1]) for k in results]

for result in results:
    print(f'{result[0]}: ', result[1])`

And the program can not find a file:
`FileNotFoundError: file "/models/tsn_r50.py" does not exist`

**Comment by hukkai** [comment]
@Juliaququ this is not an office demo from mmaction2? I do not think there is a `tsn_r50.py` in the mmaction2 repo. Which line of the codes raised the FileNotFoundError?

**Comment by hukkai** [comment]
@Juliaququ If you need further discussion, feel free to re-open this issue. Thanks!

**Comment by ch3njust1n** [comment]
I'm also getting this issue. The library references model `tsn_r50.py`. I'm just running the demo straight from the docs. Could someone update the docs for temporal action detection?

![Screenshot 2023-01-25 at 8 53 10 AM](https://user-images.githubusercontent.com/3211697/214584839-1922a1f2-bbd5-4703-80cc-d2452a5c67a6.png)
