### ISSUE TITLE
ckpt missed

### ISSUE THREAD

**Issue by YuyanXu0329** [open-mmlab/mmaction2#1737]
In mmaction2/configs/recognition/slowonly has same ckpt file in two different config
one is Kinetics-400 OmniSource Experiments （slowonly_r50_4x16x1_256e_kinetics400_rgb）and another is Kinetics-400 Data Benchmark(slowonly_r50_randomresizedcrop_320p_4x16x1_256e_kinetics400_rgb), please check it~

**Comment by kennymckormick** [comment]
Hi, YuyanXu,
Actually, they are the same experiments, I just refer the same experiment in two different comparisons.

**Comment by hukkai** [comment]
@YuyanXu0329 If you have any other questions, feel free to re-open. Thanks!
