### ISSUE TITLE
Multi-Label Action Recognition 

### ISSUE THREAD

**Issue by theravadaz** [open-mmlab/mmaction2#1746]
Hi :) Is it possible to create a multi-label action recognition task where some of the examples do not belong to any class? Currently, doing this leads to an invalid annotation file.

Thanks!

**Comment by hukkai** [comment]
@theravadaz  You can add one extra class like `background`.

**Comment by hukkai** [comment]
@theravadaz If you need further discussion, feel free to re-open the issue. Thanks!

**Comment by HermannStettin** [comment]
@hukkai Hello  I'm currently facing the same problem. I have a class called "no_action" which indicates that there is no action in the video. There is no data for this class and I can't create any additional data. So I decided to use background class  to solve this problem.  How can I create a background class "no_action" and  give it a particular number, like 25, if I have 24 "action" classes? I'm using MViTv2.
