### ISSUE TITLE
the difference between load_from and pretrained

### ISSUE THREAD

**Issue by JIM3766** [open-mmlab/mmaction2#1747]
What is the difference between load_from and pretrained?

**Comment by ly015** [comment]
`load_from` means loading all model weights, while `pretrained` means only loading the weights of the backbone.

**Comment by JIM3766** [comment]
Thanks!

**Comment by alitirmizi23** [comment]
So if we set load_from to some checkpoint, it will load all the model weights (including the backbone) even if we set the "pretrained" to None? 
Also, if I set pretrained = None and load_from = some_checkpoint, would all the model weights be trained or just the part after the backbone/feature extractor?
