### ISSUE TITLE
This warning appears when loading the pre training model. Does this mean that the pre training model failed to load? How can I eliminate this warning? What I'm doing now is training a slowfast RCNN model with five action categories

### ISSUE THREAD

**Issue by ysy070100** [open-mmlab/mmaction2#1757]
`2022-08-03 00:06:15,495 - mmaction - WARNING - The model and loaded state dict do not match exactly

unexpected key in source state_dict: cls_head.fc_cls.weight, cls_head.fc_cls.bias

missing keys in source state_dict: roi_head.bbox_head.fc_cls.weight, roi_head.bbox_head.fc_cls.bias`

**Comment by hukkai** [comment]
@ysy070100 It seems that you use a recognition model to initialize a spatial temporal detection model? In this case, the warning is expected and do not need to worry.

**Comment by ysy070100** [comment]
> @ysy070100好像是用识别模型来初始化时空检测模型？在这种情况下，警告是预期的，不需要担心。

@hukkai 
thanks for your answer.
load_from = 'https://download.openmmlab.com/mmaction/recognition/slowfast/slowfast_r50_4x16x1_256e_kinetics400_rgb/slowfast_r50_4x16x1_256e_kinetics400_rgb_20200704-bcde7ed7.pth' This is load_ From model
‘mmaction2/configs/detection/ava’ Config file from here 
So does this warning not affect the actual training effect？

**Comment by hukkai** [comment]
@ysy070100  yes
