### ISSUE TITLE
How to run posc3d model on Kinetics400 with keypoint pkl file?

### ISSUE THREAD

**Issue by a-github-learner** [open-mmlab/mmaction2#1762]
I copy slowonly_r50_346_k400.py file and corresponding pkl file from pyskl to mmaction2,but I got error as follows. How to solve the problem.

![1659612444244](https://user-images.githubusercontent.com/78460513/182836119-f0553190-924b-42af-b886-f40b3cb8bc8e.jpg)

**Comment by kennymckormick** [comment]
Hi, you are trying to use MMAction2 to train PoseC3D-K400, but it is only supported in PYSKL.

**Comment by a-github-learner** [comment]
all right.... What a pity:(
