### ISSUE TITLE
Light weight model for skeleton based action detection 

### ISSUE THREAD

**Issue by Xinxinatg** [open-mmlab/mmaction2#1766]
Will light weight model for skeleton based action detection be provided so that real-time inference could be possible on edge devices? I saw such feature in [Paddle detection](https://github.com/PaddlePaddle/PaddleDetection/tree/release/2.4/configs/keypoint/tiny_pose). I think skeleton based action detection model will be more desired for real time detection of fall/slip.

**Comment by hukkai** [comment]
The mode on the page is for pose estimation without action recognition. Our current skeleton based action detection simply take the pose results as the input. Maybe you can submit an issue or PR to impose.

**Comment by Xinxinatg** [comment]
@hukkai Thanks for your prompt reply! Just to clarify, are there light weight pose estimation model provided in mmlab? I saw  HRNetw32 and HRNetw32 are available in model zoo. From my understanding, the most processor intensive part for skeleton based action detecion is the pose estimation, so if I will be able to replace the pose estimator here with light weight one, I think the real-time inference will be achievable. 
![image](https://user-images.githubusercontent.com/72983482/183321230-84c7d1e1-eaa7-488d-8d99-9d530ca95130.png)

**Comment by hukkai** [comment]
@Xinxinatg Sorry I made a typo. I think you can look at [mmpose](https://github.com/open-mmlab/mmpose) to see if there are any lightweight models.

**Comment by hukkai** [comment]
In our next version of release, we will consider use some lighter models for the demo.

**Comment by Xinxinatg** [comment]
@hukkai thanks a lot! will have a look at mmpose repo

**Comment by Xinxinatg** [comment]
> In our next version of release, we will consider use some lighter models for the demo.

has the date for releasing the new version been decided yet?

**Comment by hukkai** [comment]
It depends on the date when mmpose will support light weight pose models.
