### ISSUE TITLE
How to use vit_small in timesformer as backbone  with pretrained model ?

### ISSUE THREAD

**Issue by jiarenyf** [open-mmlab/mmaction2#1772]
How to use vit_small in timesformer as backbone  with pretrained model ?

**Comment by hukkai** [comment]
Will be supported in the next month's release.

**Comment by hukkai** [comment]
@jiarenyf  If you need any further discussion, feel free to re-open the issue. Thanks!

**Comment by EaaloZ** [comment]
> @jiarenyf If you need any further discussion, feel free to re-open the issue. Thanks!



> Will be supported in the next month's release.

Are there any updates?
