### ISSUE TITLE
validation by iteration causes model.training=False to continue until the end of an epoch

### ISSUE THREAD

**Issue by makecent** [open-mmlab/mmaction2#1781]
**Describe the bug**

During the validation, the state of `model.training` will be trun to `False`:
https://github.com/open-mmlab/mmaction2/blob/5fa8faa6a7cb2adf9b5eaf9f8a7473b65bb8228d/mmaction/apis/test.py#L76

While if validation by iteration, e.g., `evaluation = dict(by_epoch=False, interval=1000, metrics=['top_k_accuracy'])`, then the state `model.training=False` will continue [until the next epoch](https://github.com/open-mmlab/mmcv/blob/f527e43c1a1e52e5903410255aea1f71f005a161/mmcv/runner/epoch_based_runner.py#L43) when  `EpochBasedRunner` was adopted. This makes the remaining iterations in the epoch where the evaluation happens to be excuted under `eval` state.

**Comment by hukkai** [comment]
Thanks @makecent ! So we just need to switch to model.train() before the end of this function? Could you submit a PR?

**Comment by makecent** [comment]
> Thanks @makecent ! So we just need to switch to model.train() before the end of this function? Could you submit a PR?

I am not sure if this should be a kind of BUG of the `mmcv` because `IterBasedRunner` should work well with validation by iterations. 

Since mmaction2 only uses `EpochBasedRunner`, we may **either** 

- adopt `IterBasedRunner` when some conditions are met, e.g. `evalution.by_epoch=False`
- propose this as a BUG in an issue of `mmcv`.

The choice depends on how you `mmlab` expects the user to use the `Runner`: Should the evaluation by **iteration** be allowed when `EpochBasedRunner` is used?

**Comment by hukkai** [comment]
In the next release mmlab repo series will use a new engine. Will discuss this with the related developers.

**Comment by hukkai** [comment]
The new release is at dev-1.x branch. If you have any further questions, feel free to re-open the issue. Thanks!
