### ISSUE TITLE
collecting pickle files Custom Dataset Training with PoseC3D

### ISSUE THREAD

**Issue by mahdiabdollahpour** [open-mmlab/mmaction2#1785]
Hi

In [Custom Dataset Training with PoseC3D](https://github.com/open-mmlab/mmaction2/blob/master/configs/skeleton/posec3d/custom_dataset_training.md), in step 2 it says:

You will collect all the pickle files into one list for training and save them as a single file.

What is the command/code to do that? how to collect multiple pickle files into one file so that is compatible with the library

Thanks

**Comment by xxxnhb** [comment]
You can try the following code to collect multiple pickle files into one file.
```
import os
import pickle
list = []
path = "./keypoint/"  # The path for storing pickle files
files = os.listdir(path) 
for i, file in enumerate(files):
    with open(path + file, 'rb+') as f:
        a = pickle.load(f)
        list.append(a)
pickle_file = open('./train.pkl', 'wb')   #
pickle.dump(list, pickle_file)
```
