### ISSUE TITLE
how to set custom lr updater?

### ISSUE THREAD

**Issue by sijun-zhou** [open-mmlab/mmaction2#179]
Hi, 
I want to use 'StepLrUpdaterHook', but I do not want it decrease to 0.1 * lr at the step I specified. What I want is base_lr = 0.1, and then the flowing decreased lr is 0.5 * base_lr, 0.1 * base_lr, 0.05 * base_lr, 0.001 * base_lr. 
How can i do it?

Thanks in advance!

**Comment by innerlee** [comment]
@dreamerlin we can add this howto to our doc near https://mmaction2.readthedocs.io/en/latest/tutorials.html#add-new-heads

**Comment by SuX97** [comment]
Maybe refer to [RelativeStepLrUpdaterHook](https://github.com/open-mmlab/mmaction2/pull/29/files#diff-405b5833c2fe0e034a9cf54842262eafR57)? @innerlee

**Comment by innerlee** [comment]
True. I believe it's worth a tutorial section. @SuX97 Could you add this `RelativeStepLrUpdaterHook` to the doc (in a new doc pr)?

**Comment by SuX97** [comment]
> True. I believe it's worth a tutorial section. @SuX97 Could you add this `RelativeStepLrUpdaterHook` to the doc (in a new doc pr)?

No problem.
