### ISSUE TITLE
PoseC3D RGBPose-SlowFast

### ISSUE THREAD

**Issue by Haoran-Qi** [open-mmlab/mmaction2#1793]
Greetings

I notice that there are only slow-only configurations under the PoseC3D network, rather than the RGBPose-SlowFast fusion design described in the paper.

Wondering if that will be added in the near future?

**Comment by hukkai** [comment]
I do not think it will be supported. @kennymckormick how do you think?

**Comment by Haoran-Qi** [comment]
I am trying to implement a mmaction dataset for loading skeleton and rgb videos in same time.

I would really appreciate it if the part of loading the two modalities could be shared in this project, since RGBPose-SlowFast does the same thing.

**Comment by hukkai** [comment]
@Haoran-Qi If you have implemented this, you are very welcome to submit a PR! Thanks!

**Comment by Haoran-Qi** [comment]
Yes I can do that

**Comment by kennymckormick** [comment]
Hi, Haoran, 
This is not officially implemented now, however, you can refer to my original codes at the `research` branch of my MMAction2 fork: https://github.com/kennymckormick/mmaction2/tree/research. For loading, you can mainly refer to codes with `MM` prefix, like `MM` pipeline components for multi-modality loading or the https://github.com/kennymckormick/mmaction2/blob/research/mmaction/models/recognizers/mm_recognizer3d.py for multi-modality recognition.

**Comment by Xinxinatg** [comment]
> I am trying to implement a mmaction dataset for loading skeleton and rgb videos in same time.
> 
> I would really appreciate it if the part of loading the two modalities could be shared in this project, since RGBPose-SlowFast does the same thing.

Hi Haoran just wondering have you been able to implement the rgb-pose fusion?

**Comment by hukkai** [comment]
If you have any further questions, feel free to re-open the issue.

**Comment by Better369** [comment]
> I'm trying to implement a mmaction dataset for loading both the skeleton and the RGB video.
> 
> I would appreciate it if the part loading both modes could be shared in this project, as RGBPose-SlowFast does the same.

I would like to ask if you have achieved multimodal fusion, I also noticed that the platform only provides programs about bones.
