### ISSUE TITLE
Ajust keyframe ID in training slowfast model with custom data

### ISSUE THREAD

**Issue by Xinxinatg** [open-mmlab/mmaction2#1795]
I noticed that in the [webcam_demo_spatiotemporal_det.py](https://github.com/open-mmlab/mmaction2/blob/5fa8faa6a7cb2adf9b5eaf9f8a7473b65bb8228d/demo/webcam_demo_spatiotemporal_det.py#L226) the keyframe id can be modified. Because I integrated this demo file into my framework for real-time inference, I set the keyframe id to be len(task.frames)-4. I am wondering whether there is any place in the training.py that I can ajust the keyframe ID accordingly so that the inference scenerio can be matched up with the trained model.

**Comment by hukkai** [comment]
You need to modify the annotation files.

**Comment by hukkai** [comment]
@Xinxinatg If you need any further discussion, feel free to re-open the issue. Thanks!
