### ISSUE TITLE
How to visualize heatmap in posec3d

### ISSUE THREAD

**Issue by LaflameIsLit** [open-mmlab/mmaction2#1798]
谢谢作者们详实的工作。请问我想像文章中那样提取并可视化posec3d中的热力图，该以何种方式实现呢。tensor或image的形式都可以。

Thanks to the authors for their detailed work. I would like to extract and visualize the heatmap in posec3d like in the article, how can I do it, either in the form of tensor or image?

**Comment by kennymckormick** [comment]
Hi, LaflameIsLit,
You can use in visualize_heatmap_volume.ipynb in [MMAction2](https://github.com/open-mmlab/mmaction2/blob/master/demo/visualize_heatmap_volume.ipynb) or [PYSKL](https://github.com/kennymckormick/pyskl/blob/main/demo/visualize_heatmap_volume.ipynb) for visualization (clicking the link leads you to the ipynb file).
