### ISSUE TITLE
mmcv error when extracting frames

### ISSUE THREAD

**Issue by youngwanLEE** [open-mmlab/mmaction2#180]
**Describe the bug**

When I extracting rgb frames using `tools/data/sthv2/extract_rgb_frames_opencv.sh`, opencv resize error happened.

From the error trackback, it may be caused by mmcv.

**Reproduction**
1. What command or script did you run?

```  sh extract_rgb_frames_opencv.sh```  in tools/data/sthv2

2. Did you make any modifications on the code or config? Did you understand what you have modified?
--> No

3. What dataset did you use?
--> sthv2

**Environment**

> sys.platform: linux
> Python: 3.7.9 (default, Aug 31 2020, 12:42:55) [GCC 7.3.0]
> CUDA available: True
> GPU 0,1,2,3,4,5,6,7: TITAN Xp
> CUDA_HOME: /usr/local/cuda
> NVCC:
> GCC: gcc (Ubuntu 5.4.0-6ubuntu1~16.04.12) 5.4.0 20160609
> PyTorch: 1.6.0
> PyTorch compiling details: PyTorch built with:
>   - GCC 7.3
>   - C++ Version: 201402
>   - Intel(R) Math Kernel Library Version 2020.0.2 Product Build 20200624 for Intel(R) 64 architecture applications
>   - Intel(R) MKL-DNN v1.5.0 (Git Hash e2ac1fac44c5078ca927cb9b90e1b3066a0b2ed0)
>   - OpenMP 201511 (a.k.a. OpenMP 4.5)
>   - NNPACK is enabled
>   - CPU capability usage: AVX2
>   - CUDA Runtime 10.2
>   - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_37,code=compute_37
>   - CuDNN 7.6.5
>   - Magma 2.5.2
>   - Build settings: BLAS=MKL, BUILD_TYPE=Release, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DUSE_VULKAN_WRAPPER -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, USE_CUDA=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_STATIC_DISPATCH=OFF,
> 
> TorchVision: 0.7.0
> OpenCV: 4.4.0
> MMCV: 1.1.2
> MMCV Compiler: GCC 7.3
> MMCV CUDA Compiler: 10.2
> MMAction2: 0.6.0+7dc58b3
> 

2. You may add addition that may be helpful for locating the problem, such as
--> pytorch installed by conda

**Error traceback**
If applicable, paste the error traceback here.
```

Traceback (most recent call last):
  File "build_rawframes.py", line 226, in <module>
    len(vid_list) * [args.task]))
  File "/home/lsrock1/anaconda3/envs/pytorch1.6/lib/python3.7/multiprocessing/pool.py", line 268, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/home/lsrock1/anaconda3/envs/pytorch1.6/lib/python3.7/multiprocessing/pool.py", line 657, in get
    raise self._value
cv2.error: OpenCV(4.4.0) /tmp/pip-req-build-nzyrw1vf/opencv/modules/imgproc/src/resize.cpp:3932: error: (-215:Assertion failed) inv_scale_x > 0 in function 'resize'

Genearte raw frames (RGB only)


```

**Comment by dreamerlin** [comment]
Fix it in https://github.com/open-mmlab/mmaction2/pull/187
