### ISSUE TITLE
About MMAction2 Tutorial.ipynb

### ISSUE THREAD

**Issue by Leonard-Bernstein** [open-mmlab/mmaction2#1809]
Hello.

I have a question about MMAction2 Tutorial.ipynb"https://colab.research.google.com/github/open-mmlab/mmaction2/blob/master/demo/mmaction2_tutorial.ipynb".
I want to infer 1j20qq1JyX4.mp4 using a model trained on Colab.
In this program"!python demo/demo_spatiotemporal_det.py --video demo/1j20qq1JyX4.mp4", it seemed that the learned model was not used in inference.
How can the learned model be used for inference?

Best Regard

**Comment by hukkai** [comment]
@Leonard-Bernstein Please check the explanations here: https://github.com/open-mmlab/mmaction2/tree/master/demo#spatiotemporal-action-detection-video-demo You need to specify the `--config` and `--checkpoint` options.

**Comment by Leonard-Bernstein** [comment]
Hi Hukkai

Thanks for your advice.
I specified the --config and --checkpoint options, but I get an error.
Do you know how to deal with this error?

The program I ran
!python demo/demo_spatiotemporal_det.py --video kinetics400_tiny/train/27_CSXByd3s.mp4 --checkpoint tutorial_exps/best_top1_acc_epoch_10.pth --config configs/recognition/tsn/tsn_r50_video_inference_1x1x3_100e_kinetics400_rgb.py --label-map tools/data/kinetics/label_map_k400.txt

Error
Traceback (most recent call last):
  File "demo/demo_spatiotemporal_det.py", line 421, in <module>
    main()
  File "demo/demo_spatiotemporal_det.py", line 298, in main
    val_pipeline = config.data.val.pipeline
  File "/usr/local/lib/python3.7/dist-packages/mmcv/utils/config.py", line 50, in __getattr__
    raise ex
AttributeError: 'ConfigDict' object has no attribute 'val'

Or did I specify the wrong --config?
Could you please tell me?

Best Regard

**Comment by hukkai** [comment]
@Leonard-Bernstein you need to use a config file from configs/detection instead of configs/recognition. I believe it is mentioned in the doc above. Please do read it.

**Comment by hukkai** [comment]
@Leonard-Bernstein  If you need any further discussion, feel free to re-open the issue. Thanks!
