### ISSUE TITLE
Error regarding distributed training

### ISSUE THREAD

**Issue by ahmed-nady** [open-mmlab/mmaction2#1810]
When i run this file (dist_train.sh), the following error message appears "AttributeError: 'MMDistributedDataParallel' object has no attribute '_sync_params' ". So, i need to know what is the reason caused this issue and how to solve it? Thanks in advance.

**Comment by hukkai** [comment]
@ahmed-nady Could you show your complete script? Or you simply run `bash dist_train.sh`?

**Comment by ahmed-nady** [comment]
The script @hukkai : CUDA_VISIBLE_DEVICES=0,1 tools/dist_train.sh configs/skeleton/posec3d/slowonly_r50_u48_240e_ntu120_xsub_keypoint.py 2

**Comment by hukkai** [comment]
@ahmed-nady Please check this issue: https://github.com/open-mmlab/mmcv/issues/1754. The reason might be that your mmcv version is old while pytorch version is new.

**Comment by hukkai** [comment]
If you have any questions, feel free to re-open the issue, thanks!
