### ISSUE TITLE
How do you handle the total_frames of optical flow dataset?

### ISSUE THREAD

**Issue by makecent** [open-mmlab/mmaction2#1812]
I am generating the rawframes filelist for a video dataset. I am wondering if I should modify the annotation files manually to minus the total frames (of RGB) with 1 for training with optical flows?

Because the number of optical flows equal the number of RGB frames **minus 1**. But I cannot find any of your code to handle this. 

For example, the `RawframeDataset` directly use the `total_frames` from the annotation file:
https://github.com/open-mmlab/mmaction2/blob/5fa8faa6a7cb2adf9b5eaf9f8a7473b65bb8228d/mmaction/datasets/rawframe_dataset.py#L145-L146

I was expecting the `video_info['total_frames']` will be minused with 1 if `modality=='Flow'` but I found no clue for it.

Woundn't this cause `index out of range` error?

**Comment by makecent** [comment]
I have done some testing, and there is a `index out of range` error when training on optical flows using `RawframeDataset` with original annotation files that designed for RGB frames.

**Comment by hukkai** [comment]
@makecent Not sure how mmaction2 handled optical flows -- people who worked on this left mmaction2.  But I just check the annotation files and guess that the annotation files for optical flows are generated independently. 

For many videos, the number of frames for optical flows equals to the number of frames for the RGB frames minus 1. But there are also some videos whose number of frames for optical flows are larger and other some videos that have much more RGB frames than optical flows frames.

**Comment by makecent** [comment]
@hukkai Interesting. Since the optical flows are computed from adjacent RGB frames, I am curious about how this could happen, i.e. `num_flows != num_rgb - 1`, if nothing was wrong.

**Comment by kennymckormick** [comment]
Hi, @makecent ,
The answer is **Yes**, you need to manually modify the data list and decrease "total_frames" by 1 for the optical flow training & testing.

**Comment by makecent** [comment]
@kennymckormick Thanks. What about updating the `RawFrameDataset` to include this operation? e.g.,:

```python
if modality == 'Flow':
    video_info['total_frames'] += -1
```
Willing to create a PR for this

**Comment by kennymckormick** [comment]
> @kennymckormick Thanks. What about updating the `RawFrameDataset` to include this operation? e.g.,:
> 
> ```python
> if modality == 'Flow':
>     video_info['total_frames'] += -1
> ```
> 
> Willing to create a PR for this

I'm OK with that, @hukkai what do you think about it?
