### ISSUE TITLE
save model

### ISSUE THREAD

**Issue by JIM3766** [open-mmlab/mmaction2#1814]
How to save the best mean class accuracy model?

**Comment by hukkai** [comment]
Add this to the config:
`evaluation=dict(interval=1, save_best='mean_class_accuracy', metrics=['top_k_accuracy', 'mean_class_accuracy'])`

**Comment by JIM3766** [comment]
Thanks！

**Comment by hukkai** [comment]
If you have any questions, feel free to re-open the issue, thanks!
