### ISSUE TITLE
AttributeError: 'ConfigDict' object has no attribute 'load_from'

### ISSUE THREAD

**Issue by waowu** [open-mmlab/mmaction2#1817]
In the mmaction2-0.22.0 version, 
I encountered such a problem during training. 
How to solve AttributeError: 'ConfigDict' object has no attribute 'load_from'?

**Comment by hukkai** [comment]
Please let us know what common you run.

**Comment by hukkai** [comment]
If you have any further questions, feel free to re-open the issue. Thanks!
