### ISSUE TITLE
Set Random Seed

### ISSUE THREAD

**Issue by JIM3766** [open-mmlab/mmaction2#1820]
What parameters are set in the command for training of the sota result made by posec3d on the Finegym dataset? What is the random seed?

**Comment by kennymckormick** [comment]
Hi, @JIM3766 , all hyper parameters are set in our config files. We don't use a specific random seed when conducting PoseC3D experiments. However, different random seeds should lead to similar results. You can report to us if not.

**Comment by JIM3766** [comment]
Thanks！
