### ISSUE TITLE
The usage of aux_info is complex. Why using it?

### ISSUE THREAD

**Issue by makecent** [open-mmlab/mmaction2#1830]
I find it's quite annoying to use the `aux_info` because we have to declare the variable names in **BOTH** the `train_cfg` of the model and the pipeline `Collect`, e.g., 
```python
model = dict(..., train_cfg=dict(aux_info=['my_aux1', 'my_aux2']))
train_pipeline = [..., dict(type='Collect', keys=['imgs', 'label', 'my_aux1', 'my_aux2'], meta_keys=())]
```
From the pespective of the codes, it's because the we only input the `imgs`, `lables` and the variables defined `aux_info` into the model:
https://github.com/open-mmlab/mmaction2/blob/5fa8faa6a7cb2adf9b5eaf9f8a7473b65bb8228d/mmaction/models/recognizers/base.py#L293-L301

However, I don't see the meaning of this `aux_info`,

- It's redundant because we can declare variables to be colleted in the pipeline `Collect`.
- It makes the `meta_keys` in the pipeline `Collect` not working as designed.
- It's complex to use.

So why we don't just simply input the whole `data_batch` into the model directly? like what `mmdetection` [does](https://github.com/open-mmlab/mmdetection/blob/3b72b12fe9b14de906d1363982b9fba05e7d47c1/mmdet/models/detectors/base.py#L248-L254)

**Comment by hukkai** [comment]
@makecent We will have a new release and this part will be refactored. Please stay tuned and review the new version, thanks!

**Comment by makecent** [comment]
@hukkai Looking forward to it.
