### ISSUE TITLE
How to get the original bounding box for the AVA dataset

### ISSUE THREAD

**Issue by anjaeju** [open-mmlab/mmaction2#1833]
Thanks for this awesome tool box, MMACTION2.
I am currently working on spatio temporal deteciton with AVA dataset, and I encounter non-tirival problems.

**Events**
I want to visualize the AVA dataset with annotations (bounding box and action label) to check the label quality.
- I prepraed all the reqired directory and files as following
```AVA/
    annotations/
    rawframes/
        Video-id 1/
            img_00001.jpg
            img_00002.jpg
            . . . 
            img_0000N.jpg
        Video-id 2/
        . . . 
        Video-id N/
```
- I checked the mmaction2 working well with my settings

**Error**
I visualized with the first frame of the video ( -5KQ66BBWC4) with the first annotation in csv file (ava_train_v2.2.csv).
- The coordinates are : 
| ts | x1  | y1    | x2    | y2    |       |
|----|-----|-------|-------|-------|-------|
| 0  | 902 | 0.077 | 0.151 | 0.283 | 0.811 |
| 1  | 902 | 0.077 | 0.151 | 0.283 | 0.811 |
| 2  | 902 | 0.226 | 0.032 | 0.366 | 0.497 |
| 3  | 902 | 0.226 | 0.032 | 0.366 | 0.497 |
| 4  | 902 | 0.226 | 0.032 | 0.366 | 0.497 |
| 5  | 902 | 0.332 | 0.194 | 0.481 | 0.891 |
| 6  | 902 | 0.332 | 0.194 | 0.481 | 0.891 |
| 7  | 902 | 0.505 | 0.105 | 0.653 | 0.780 |
| 8  | 902 | 0.626 | 0.146 | 0.805 | 0.818 |
| 9  | 902 | 0.805 | 0.222 | 0.997 | 1.000 |
| 10 | 902 | 0.805 | 0.222 | 0.997 | 1.000 |
- I resize the box with width (256) and height (320) (here, might be wrong, but I donno what to do)
- The result is not satisfactory as following:
here ->https://drive.google.com/file/d/1SE04bZ64Tan6j6i7Gfb98ZNhZChKJ7rZ/view?usp=sharing

How can I get the original bounding box size and coordinates?

**Comment by hukkai** [comment]
The bounding box is the ratio with respect to the height/width, which is not changed with any resize. Maybe you mixed  up height and width?

**Comment by anjaeju** [comment]
@hukkai 
Thanks for ur response.
I have already dealt with this problem like you mentioned above.

I resized each video with the respective height & width with 25 FPS rate, starting after 2 seconds
