### ISSUE TITLE
关于NTU RGB+D

### ISSUE THREAD

**Issue by zhengxindi1231** [open-mmlab/mmaction2#1834]
MMaction2上st-gcn在NTU RGB+D 60 给了一个stgcn_80e_ntu60_xsub_keypoint还有一个stgcn_80e_ntu60_xsub_keypoint_3d，我想自己训练试试。我用mmaction2给的ntu60_xsub_train和ntu60_xsub_val成功训练stgcn_80e_ntu60_xsub_keypoint，但在stgcn_80e_ntu60_xsub_keypoint_3d上官网给的不行，想问下如何得到stgcn_80e_ntu60_xsub_keypoint_3d中的ann_file_train文件

**Comment by cir7** [comment]
You could refer to the [link](https://github.com/kennymckormick/pyskl/blob/main/tools/data/data_doc.md#download-the-pre-processed-skeletons)
