### ISSUE TITLE
Why SlowFast configure set "pretrained=None" ?

### ISSUE THREAD

**Issue by kuangxiaoye** [open-mmlab/mmaction2#1840]
But I3D,TimeSformer all  have pretrained model in configure.

**Comment by kuangxiaoye** [comment]
model = dict(
    type='Recognizer3D',
    backbone=dict(
        type='ResNet3dSlowFast',
        pretrained=None,
        resample_rate=8,  # tau
        speed_ratio=8,  # alpha
        channel_ratio=8,  # beta_inv
        slow_pathway=dict(····

**Comment by hukkai** [comment]
@kuangxiaoye The settings are from the original paper. The Slowfast paper mentioned their models are trained from scratch.

**Comment by kuangxiaoye** [comment]
> @kuangxiaoye The settings are from the original paper. The Slowfast paper mentioned their models are trained from scratch.

Thanks
