### ISSUE TITLE
"missing keys in source state_dict" 

### ISSUE THREAD

**Issue by kuangxiaoye** [open-mmlab/mmaction2#1843]
When I using the pre-model to train in TimeSformer,the process stop in the "missing keys in source state_dict" and can not  be stop by Ctrl + C.

<img width="708" alt="image" src="https://user-images.githubusercontent.com/43713316/187116241-bb490747-b45b-4e2e-96fb-af1b0390d150.png">

This is a error ? or just my GPU computing power too low..?

**Comment by kuangxiaoye** [comment]
OK,i find answer in mmdetection...

https://github.com/open-mmlab/mmdetection/issues/644

"You can just ignore these warnings. It's expected."

But I'm still wondering why the model loads so slowly and can't exit···

**Comment by xsssse** [comment]
I have the same question. Have you found a solution?
