### ISSUE TITLE
MEVA or Virat dataset

### ISSUE THREAD

**Issue by nikky4D** [open-mmlab/mmaction2#185]
This is probably a silly question. I am interested in aerial and surveillance action recognition. Like for the recently completed ActivityNet at CVPR, there was a surveillance challenge with MEVA/Virat data. As the actions there are not as nuanced as in Kinectics/Ava, and some are also taken from aerial perspective, can we still apply mmaction2 for that type of data?

**Comment by innerlee** [comment]
If the dataset format is similar to Kinetics, then you can apply mmaction2 to train new models on the new dataset. Checkout this tutorial https://mmaction2.readthedocs.io/en/latest/tutorials.html#tutorial-1-finetuning-models

**Comment by nikky4D** [comment]
Thanks for the fast response and the link. I'll take a look.
