### ISSUE TITLE
fail to run webcam demo with r2plus1d

### ISSUE THREAD

**Issue by PoroWang** [open-mmlab/mmaction2#188]
Hi, thanks for providing this awesome tool first.

I trained on my own datasets and it works on the webcam demo with TSN.

I tried to run the webcam demo with r2plus1d but it failed.

Here is the error messages:

Traceback (most recent call last):
  File "demo/webcam_demo.py", line 161, in <module>
    main()
  File "demo/webcam_demo.py", line 157, in main
    predict_webcam_video()
  File "demo/webcam_demo.py", line 83, in predict_webcam_video
    cur_data = test_pipeline(cur_data)
  File "/home/ubuntu/Desktop/YHWang/mmaction2/mmaction/datasets/pipelines/compose.py", line 41, in __call__
    data = t(data)
  File "/home/ubuntu/Desktop/YHWang/mmaction2/mmaction/datasets/pipelines/formating.py", line 248, in __call__
    num_clips = results['num_clips']
KeyError: 'num_clips'

The config i modified is num_classes(in r2plus1d_r34_video_inference_8x8x1_180e_kinetics400_rgb.py). I changed it from 400 to 12 (my datasets class numbers).
After a little test, i found that it fail to get the clip_len and num_clips in the test_pipeline dict.
I tried to comment some code in formating.py:
"
if self.input_format == 'NCTHW':
            #num_clips = results['num_clips']
            #clip_len = results['clip_len']

            imgs = imgs.reshape((-1, num_clips, clip_len) + imgs.shape[1:])
"
and i change num_clips, clip_len to some number then it works.
But the predictied label doesn't change by time, maybe the result is wrong.  

Sorry for my poor english.
Could you give me some idea? Thanks for you help!

**Comment by dreamerlin** [comment]
A better asynchronous webcam_demo is provided [here](https://github.com/open-mmlab/mmaction2/pull/191)
