### ISSUE TITLE
Set multiple losses

### ISSUE THREAD

**Issue by JIM3766** [open-mmlab/mmaction2#1881]
How to set multiple losses for training?

**Comment by cir7** [comment]
Hi, @JIM3766 , you can build a custom loss class, follow the [guide](https://github.com/open-mmlab/mmaction2/blob/master/docs/tutorials/5_new_modules.md#add-new-loss), and take [HUVLoss](https://github.com/open-mmlab/mmaction2/blob/master/mmaction/models/losses/hvu_loss.py) as an example

**Comment by JIM3766** [comment]
Thanks!
