### ISSUE TITLE
Could you provide export as pdf for documentation?

### ISSUE THREAD

**Issue by JihwanEom** [open-mmlab/mmaction2#1893]
Thanks for your feature request and we will review and plan for it when necessary.
If you feel we have help you, give us a STAR! :satisfied:

**Describe the feature**
Export documentation as pdf.

**Motivation**
Latest MMaction2 documentation does not support pdf export.

**Comment by cir7** [comment]
@JihwanEom We modified the config file and now supports exporting pdf from documents

**Comment by JihwanEom** [comment]
Thank you for quick reply! It works very well, I'll study hard :) thank you!
