### ISSUE TITLE
Output the feature maps

### ISSUE THREAD

**Issue by JIM3766** [open-mmlab/mmaction2#1902]
How to output the feature maps of the network when testing?

**Comment by cir7** [comment]
Hi, @JIM3766 you can assign `feature_extraction=True` in testing, follow this [config](https://github.com/open-mmlab/mmaction2/blob/master/configs/recognition/slowonly/slowonly_r50_clip_feature_extraction_4x16x1_rgb.py)

**Comment by hukkai** [comment]
If you have any further questions, feel free to re-open the issue. Thanks!

**Comment by JIM3766** [comment]
How use the OutputHook to output the feature maps?
![微信图片_20220913214621](https://user-images.githubusercontent.com/78255188/189919372-76e51531-b021-4ba2-85d8-0ecbd07e2711.png)

**Comment by JIM3766** [comment]
> Hi, @JIM3766 you can assign `feature_extraction=True` in testing, follow this [config](https://github.com/open-mmlab/mmaction2/blob/master/configs/recognition/slowonly/slowonly_r50_clip_feature_extraction_4x16x1_rgb.py)

And how to use the OutputHook to output the feature maps?
![微信图片_20220913214621](https://user-images.githubusercontent.com/78255188/189920311-1e86ea3e-ac2b-4fb4-946c-17110e26e012.png)

**Comment by cir7** [comment]
Hi， @JIM3766 you can search globally in the whole project and will find an example in `mmaction/apis/inference.py`

**Comment by qjin7796** [comment]
> Hi， @JIM3766 you can search globally in the whole project and will find an example in `mmaction/apis/inference.py`

Hi, 'feature_extraction' seems removed from the latest 1.x version. The links you provided are outdated. I can't find any guidance on extracting layer output in the latest documentation either. Could you give a hint please?
