### ISSUE TITLE
Converting ava action detection model to onnx

### ISSUE THREAD

**Issue by nyanmn** [open-mmlab/mmaction2#1906]
I am using [ava action detection for my application](https://mmaction2.readthedocs.io/en/latest/detection_models.html#ava).
slowfast is support to convert to onnx.
How about ava head, can I converty to onnx as well?
After conversion in onnx format, is there sample command for running app?

**Comment by hukkai** [comment]
It is not supported currently, but the [mmdeploy](https://github.com/open-mmlab/mmdeploy) team will look into this soon.

**Comment by nyanmn** [comment]
If I do myself, what are the steps I need to implement? Is there any reference or discussion?

**Comment by hukkai** [comment]
Maybe https://github.com/open-mmlab/mmdeploy is the better place for this question. We are not familiar with deployment.

**Comment by 1005452649** [comment]
I have encountered the same problem, may I ask you?
