### ISSUE TITLE
about ava dataset ava2.2，about Use personid

### ISSUE THREAD

**Issue by P-jiahui** [open-mmlab/mmaction2#1907]
First of all, thank you very much for your open source.
At present, the slow-fast in the repository does not use personid, I checked the dataloader， and the dataloader package the entity_ids into the meat (DataContainer type) but I did not find it used in the model.

**Comment by hukkai** [comment]
As far as I know, the persion ID is only collected into the meta but not used.

**Comment by P-jiahui** [comment]
> 据我所知，persion ID 只收集到元数据中，但没有使用。

ok， thank you，In fact, I found that the official slowfast does not use personid either
