### ISSUE TITLE
Training TSN Video model on custom dataset with new classes and issue on following inference

### ISSUE THREAD

**Issue by SandyLi2017** [open-mmlab/mmaction2#1917]
I am also following the colab tutorial for training custom dataset with new classes(which might be sub classes of a class in k400 like gymactivity1, gymactivity2 and gymactivity3 of gymactivity) and did change the num_classes as 3 and new label_map.txt(list in 3 lines, suppose this be using on inference only?). I also prepared the training/val video dataset annotation txt file and tried below on way A and B:
A: class id as
gymactivity1 0
gymactivity2 1
gymactivity3 2
and pointing to custom dataset followed by model training. After training done to get best top1 acc epoch pth file and use configs/recognition/tsn/tsn_r50_video_inference_1x1x3_100e_kinetics400_rgb.py with minor change based on test portion of training config dict as below:
base = ['../../base/models/tsn_r50.py']

dataset settings
dataset_type = 'VideoDataset'
img_norm_cfg = dict(
mean=[123.675, 116.28, 103.53], std=[58.395, 57.12, 57.375], to_bgr=False)
test_pipeline = [
dict(type='DecordInit'),
dict(
type='SampleFrames',
clip_len=1,
frame_interval=1,
num_clips=25,
test_mode=True),
dict(type='DecordDecode'),
dict(type='Resize', scale=(-1, 256)),
dict(type='TenCrop', crop_size=224),
dict(type='Normalize', **img_norm_cfg),
dict(type='FormatShape', input_format='NCHW'),
dict(type='Collect', keys=['imgs','label'], meta_keys=[]),
dict(type='ToTensor', keys=['imgs'])
]
data = dict(
videos_per_gpu=1,
workers_per_gpu=2,
test=dict(
type=dataset_type,
ann_file=None,
data_prefix=None,
pipeline=test_pipeline))
But still after inference, i am still getting the orig ground truth class id in k400 but not my own custom class to be recognized(which might be my custom dataset volume too small or class id wrongly place in ann file?).
A: to use class id not in ground truth class id in k400 as
gymactivity1 400
gymactivity2 401
gymactivity3 402
But this can not be trained to success with below error:
/usr/local/lib/python3.7/dist-packages/mmcv/utils/registry.py in build_from_cfg(cfg, registry, default_args)
70 except Exception as e:
71 # Normal TypeError does not print class name.
---> 72 raise type(e)(f'{obj_cls.name}: {e}')
73
74

ValueError: VideoDataset: not enough values to unpack (expected 2, got 0)

Much appreciate if any guide me thru on the issue.

**Comment by SandyLi2017** [comment]
#826

**Comment by hukkai** [comment]
@SandyLi2017

**Comment by hukkai** [comment]
@SandyLi2017 Since the question is not very clear, I am closing it now. If you need any further discussion, feel free to re-open the issue. Thanks!
