### ISSUE TITLE
How to correctly read the jpg images of optical flow for JHMDB/UCF101-24?

### ISSUE THREAD

**Issue by r09921135** [open-mmlab/mmaction2#1933]
The optical flow these two datasets provide is jpg image.
But, I want to use a flow stream ResNeXt-101 pre-trained weights from [here](https://github.com/craston/MARS#models), where the input shape of flow needs to be 2-channel.
Besides, I assume the 2-channel optical flow is more of a standard format?
So, my question is how to convert a jpg image of optical flow into a 2-channel one or what's the correct way to read such optical flow images? 
Thank you!!

**Comment by hukkai** [comment]
@r09921135 The data is provided from https://github.com/MCG-NJU/MOC-Detector/blob/master/readme/Dataset.md. Maybe you can ask them, since I do not have the optical flow data at hand. I guess one optical flow is stored in two gray images, namely x.jpeg and y.jpeg.

**Comment by hukkai** [comment]
Closed since no response for a long time. If you need further discussion, feel free to re-open the issue. Thanks!
