### ISSUE TITLE
init_detector [python3 demo/demo_video_structuralize.py]

### ISSUE THREAD

**Issue by jingruhou** [open-mmlab/mmaction2#1936]
Before raising a question, you may need to check the following listed items.

`NameError: name 'init_detector' is not defined`

`demo/demo_video_structuralize.py:23: UserWarning: Failed to import `inference_detector` and `init_detector` form `mmdet.apis`. These apis are required in skeleton-based applications! 
  warnings.warn('Failed to import `inference_detector` and `init_detector` '
Traceback (most recent call last):
  File "demo/demo_video_structuralize.py", line 786, in <module>
    main()
  File "demo/demo_video_structuralize.py", line 684, in main
    human_detections = detection_inference(args, frame_paths)
  File "demo/demo_video_structuralize.py", line 306, in detection_inference
    model = init_detector(args.det_config, args.det_checkpoint, args.device)
NameError: name 'init_detector' is not defined`

**Comment by hukkai** [comment]
@jingruhou did you install mmdet?

**Comment by hukkai** [comment]
Closed since no response for a long time. If you need further discussion, feel free to re-open the issue. Thanks!
