### ISSUE TITLE
Error in mmaction2_tutorial notebook

### ISSUE THREAD

**Issue by amrzv** [open-mmlab/mmaction2#1943]
**Checklist**

1. I have searched related issues but cannot get the expected help.
2. The bug has not been fixed in the latest version.

**Describe the bug**

When running `demo/mmaction2_tutorial.ipynb` notebook there raised a `FileNotFoundError` because .mp4 file can't be downloaded. This is because the version of `imageio` has been changed:
`RuntimeError: imageio.ffmpeg.download() has been deprecated. Use 'pip install imageio-ffmpeg' instead.'`

**Reproduction**

1. What command or script did you run?
Open notebook in colab and click "Kernel" -> "Run all"

**Environment**
Google colab env.

**Error traceback**
<img width="536" alt="image" src="https://user-images.githubusercontent.com/36787333/191482967-d22aaba8-3145-4965-bf85-478aba661f6a.png">

**Bug fix**

[Solution](https://stackoverflow.com/a/55969838): add imageio==2.4.1 to requirements or add !pip install imageio==2.4.1 to Install MMAction2 cell at the beginning of notebook.

**Comment by cir7** [comment]
Hi, @amrzv, thanks for your feedback, this is indeed a bug, and i found that it is caused by the `moviepy` veision is too low in colab environment. so we specify a higher version in requirments now, you can check it in this [pr](https://github.com/open-mmlab/mmaction2/pull/1949)
