### ISSUE TITLE
Questions about the code training process

### ISSUE THREAD

**Issue by hzxie99** [open-mmlab/mmaction2#1950]
在模型训练完成之后，我们想画ROC曲线和混淆矩阵来补充实验数据，其中模型输出的label和predict probability 需要我们手动保存到一个文件中。在之前看到过的代码中，训练过程中有train_one_epoch这个函数，我可以直接在这个函数中添加我需要的代码。但是在这个工具箱中，由于我的粗心暂时未能找到类似于train_one_epoch函数功能的函数，train.py内的train_model()似乎也不是我们的目标。对于训练过程，我们不够了解以至于不知道在哪修改。希望能得到一些建议。
After the model training was completed, we wanted to draw ROC curve and confusion matrix to supplement the experimental data. The Label and predict probability output of the model needed to be manually saved into a file. In the code I saw earlier, I have a function (train_ONE_epoch) in the training process, and I can directly add the code I need to this function. But in this toolbox, I haven't been able to find a function like train_one_epoch because of my carelessness, and train_model() in train.py doesn't seem to be the goal either. We don't know enough about the training process to know where to modify it. Hope to get some advice.

**Comment by hzxie99** [comment]
Thanks a lot！I'll go to custom our Hook later.Have a nice life!

**Comment by hukkai** [comment]
@hzxie99 If you have any further questions, feel free to re-open the issue, thanks!
