### ISSUE TITLE
[PoseC3D] Why result in document (also paper) is different from the result in the log file of the provided checkpoint

### ISSUE THREAD

**Issue by hahv** [open-mmlab/mmaction2#1952]
This question is related to [this document](https://github.com/open-mmlab/mmaction2/blob/master/configs/skeleton/posec3d/README.md).
More specifically, the PoseC3D model on the data set NTU120_XSub.
In that document, the Top1 Acc of PoseC3D (keypoint heatmat) is  **86.3** (in [paper ](https://arxiv.org/abs/2104.13586) is **86.0**)
![Capture](https://user-images.githubusercontent.com/8085290/192174624-0a8133cf-61c6-4b28-9975-2fab665b6de0.PNG)

However, in the corresponding [log ](https://download.openmmlab.com/mmaction/skeleton/posec3d/slowonly_r50_u48_240e_ntu120_xsub_keypoint/slowonly_r50_u48_240e_ntu120_xsub_keypoint.log)file, the final val Top-1 Acc is 0.8596, which is lower the value reported in docs (and the paper also).
`2021-04-07 12:30:34,461 - mmaction - INFO - Epoch(val) [24][2910]	top1_acc: 0.8596, top5_acc: 0.9814, mean_class_accuracy: 0.8732`

What makes this difference? And is that the provided checkpoint in this repos  is different from the checkpoint presented in the paper?

**Comment by kennymckormick** [comment]
Hi, hahv,
1. The PoseC3D model released in this codebase has Top-1 Acc 86.3, which is better than the accuracy reported in the original paper.
2. The validation accuracy is inferior to the test accuracy, since during testing we use stronger test time augmentations, like sampling 10 clips from each video, etc.

**Comment by hukkai** [comment]
@hahv  If you have any further questions, feel free to re-open the issue. Thanks!
