### ISSUE TITLE
Trying to run inference with detection models but FastRCNN is not in the models registry

### ISSUE THREAD

**Issue by ivanovasimonawf** [open-mmlab/mmaction2#1955]
What I try to do is given below.

```
from mmaction.apis import inference_recognizer, init_recognizer

config = 'configs/detection/acrn/slowfast_acrn_kinetics_pretrained_r50_8x8x1_cosine_10e_ava22_rgb.py'
checkpoint = 'checkpoints/slowfast_acrn_kinetics_pretrained_r50_8x8x1_cosine_10e_ava22_rgb-2be32625.pth'
model = init_recognizer(config, checkpoint, device='cuda:0')
```

This fails with FastRCNN is not found in the models registry. 

I was searching through the source code to find the class representing the FastRCNN but I couldn't find it. 

My question is how to use detection models since FastRCNN is not defined anywhere.

**Comment by ElonZhou99** [comment]
i have the same problam

**Comment by ivanovasimonawf** [comment]
I think I found a solution. There is something called [Hierarchy Registry](https://mmcv.readthedocs.io/en/latest/understand_mmcv/registry.html#hierarchy-registry) in mmcv , which is a way of using modules from different repos. For my problem, I found that FastRCNN is defined in mmdet so I imported it from there and then registered it in mmaction2 as a recognizer.

The code is given below.
```

from mmdet.models.detectors.fast_rcnn import FastRCNN as MMDetFastRCNN
from mmaction.models.builder import RECOGNIZERS

@RECOGNIZERS.register_module()
class FastRCNN(MMDetFastRCNN):
    pass
```

Keep in mind the RECOGNIZERS module is specific for mmaction2, for different module you may need to use a different keyword. The modules for example in mmdet are defined as DETECTORS.
