### ISSUE TITLE
 Honda driving dataset has images (3fps)

### ISSUE THREAD

**Issue by pgupta119** [open-mmlab/mmaction2#1961]
Hi Team,

I am using the honda driving dataset which consists of images of the videos  (3fps).  I am using [repo](https://arxiv.org/pdf/2106.11149.pdf) (online action detection with transformer and they have used RGB  and optical flow feature for the input to the transformer.

I have some questions related to  honda driving data
1. How could I get the RGB and optical flow feature for the honda driving data set (images(3fps)?
2. How could I use a different backbone for the same process ( such as denset121 )

Thanks

**Comment by hukkai** [comment]
We are not familiar with this dataset. Maybe you can open an issue in their repo.

**Comment by pgupta119** [comment]
Thanks for the reply,   I raised the issue there and they have mentioned that I could use this repo for [repo](https://github.com/yjxiong/anet2016-cuhk) to extract the features
