### ISSUE TITLE
Is there a release date for the option to train X3D? 

### ISSUE THREAD

**Issue by aendrs** [open-mmlab/mmaction2#1964]
I was wondering if there is an estimated release date for the ability to train X3D?  Currently it only supports testing.
Thanks

**Comment by hukkai** [comment]
@aendrs If is planned in the next two months, before 2023. Please stay tuned, thanks.

**Comment by anilkunchalaece** [comment]
Hi,
Is there any update on this ?

**Comment by zxin4506** [comment]
> 敬

Hello,When c3d can be released?
