### ISSUE TITLE
Somthing about TSN

### ISSUE THREAD

**Issue by Blueyao17** [open-mmlab/mmaction2#1977]
1.How to train UCF-101 with both optical flow and RGB on TSN，and is there a TSN two stream configuration file?
2.Why does the two-stream series model only use RGB or optical flow alone and not both together?

**Comment by hukkai** [comment]
@Blueyao17 the original paper trains the spatial and temporal nets separately and do a late fusion on the scores of the two network. So our setting follows the paper. You can of course train them together and (maybe) get better results. However, since most SOTA methods no longer use optical flow, we do not further explore about this.

**Comment by Blueyao17** [comment]
> @Blueyao17 the original paper trains the spatial and temporal nets separately and do a late fusion on the scores of the two network. So our setting follows the paper. You can of course train them together and (maybe) get better results. However, since most SOTA methods no longer use optical flow, we do not further explore about this.

What I mean is that there is only rgb or optical flow in the profile. Is there a profile that uses both rgb network and optical flow network?
If not, how can I use both rgb and optical flow networks? 
Thanks for your reply.

**Comment by hukkai** [comment]
I am afraid there is no such a config and you need to write extra codes to register a new model and data pipeline for this.

**Comment by hukkai** [comment]
@Blueyao17 If you have any further questions, feel free to re-open the issue.

**Comment by Blueyao17** [comment]
> I am afraid there is no such a config and you need to write extra codes to register a new model and data pipeline for this.
Thanks. And  Is there an optical flow config for UCF-101? I only see the configuration file in RGB format about UCF-101.
