### ISSUE TITLE
用时空动作识别ava模型测试自己的视频报错

### ISSUE THREAD

**Issue by XiaoJian923** [open-mmlab/mmaction2#1983]
使用这里的高级API
https://github.com/open-mmlab/mmaction2/blob/master/docs/getting_started.md#high-level-apis-for-testing-a-video-and-rawframes
使用在ava数据集上训练好的模型拿自己的模型进行测试时，会报错，比如FastRCNN不在registry，还有就是results['fps']等键值找不到。
这里应该是有bug

**Comment by irvingzhang0512** [comment]
这个链接是给行为识别模型的，不是时空行为检测模型。ava数据集的建议参考demo里 SpatioTemporal 相关的。

**Comment by hukkai** [comment]
@XiaoJian923 If you have any further questions, feel free to re-open the issue. Thanks!
