### ISSUE TITLE
ImportError: undefined symbol

### ISSUE THREAD

**Issue by jg0014** [open-mmlab/mmaction2#1985]
**Checklist**

1. I have installed the dependences fallowed with introduction

**Describe the bug**

**When I run an time-temporal action detecte demo**: python demo/demo_spatiotemporal_det.py --video demo/demo.mp4 \ .......
**I got an error:** ImportError: /home/jianghanyu/miniconda3/envs/open-mmlab/lib/python3.8/site-packages/mmcv/_ext.cpython-38-x86_64-linux-gnu.so: undefined symbol: _ZN3c105ErrorC2ENS_14SourceLocationESs

**Reproduction**

1. When I first run this demo, I got another error. Can not import PILLOW_VERSION from pillow. Then I edit the 'PILLOW_VERSION' to '__version__'

```
python demo/demo_spatiotemporal_det.py --video demo/demo.mp4 \
    --config configs/detection/ava/slowonly_omnisource_pretrained_r101_8x8x1_20e_ava_rgb.py \
    --checkpoint https://download.openmmlab.com/mmaction/detection/ava/slowonly_omnisource_pretrained_r101_8x8x1_20e_ava_rgb/slowonly_omnisource_pretrained_r101_8x8x1_20e_ava_rgb_20201217-16378594.pth \
    --det-config demo/faster_rcnn_r50_fpn_2x_coco.py \
    --det-checkpoint http://download.openmmlab.com/mmdetection/v2.0/faster_rcnn/faster_rcnn_r50_fpn_2x_coco/faster_rcnn_r50_fpn_2x_coco_bbox_mAP-0.384_20200504_210434-a5d8aa15.pth \
    --det-score-thr 0.9 \
    --action-score-thr 0.5 \
    --label-map tools/data/ava/label_map.txt \
    --predict-stepsize 8 \
    --output-stepsize 4 \
    --output-fps 6
```

**Environment**

1. When I run `PYTHONPATH=${PWD}:$PYTHONPATH python mmaction/utils/collect_env.py` to collect necessary environment information.
I got the same error as above

all other dependences installed by fallowing with the introduction

**Error traceback**

```
Traceback (most recent call last):
  File "demo/demo_spatiotemporal_det.py", line 18, in <module>
    from mmdet.apis import inference_detector, init_detector
  File "/home/jianghanyu/miniconda3/envs/open-mmlab/lib/python3.8/site-packages/mmdet/apis/__init__.py", line 2, in <module>
    from .inference import (async_inference_detector, inference_detector,
  File "/home/jianghanyu/miniconda3/envs/open-mmlab/lib/python3.8/site-packages/mmdet/apis/inference.py", line 8, in <module>
    from mmcv.ops import RoIPool
  File "/home/jianghanyu/miniconda3/envs/open-mmlab/lib/python3.8/site-packages/mmcv/ops/__init__.py", line 2, in <module>
    from .active_rotated_filter import active_rotated_filter
  File "/home/jianghanyu/miniconda3/envs/open-mmlab/lib/python3.8/site-packages/mmcv/ops/active_rotated_filter.py", line 10, in <module>
    ext_module = ext_loader.load_ext(
  File "/home/jianghanyu/miniconda3/envs/open-mmlab/lib/python3.8/site-packages/mmcv/utils/ext_loader.py", line 13, in load_ext
    ext = importlib.import_module('mmcv.' + name)
  File "/home/jianghanyu/miniconda3/envs/open-mmlab/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
```

**Comment by hukkai** [comment]
@jg0014 Can you try `import mmcv` in python and see what happens?

**Comment by jg0014** [comment]
> @jg0014 Can you try `import mmcv` in python and see what happens?

I have solved this problem，I just reinstall the mmcv and choice a lower version==1.6.0(Originally 1.6.2)

my env(for reference): 3090gpu , 
                                     NVIDIA Driver Version: 510.60.02,
                                     pytorch: 1.12.1+cu113
                                     mmdet: 2.25.2
