### ISSUE TITLE
experiment results on UCF-101 and HMDB-51 for R(2+1)D and I3D backbone.

### ISSUE THREAD

**Issue by wqtwjt1996** [open-mmlab/mmaction2#199]
Hi,

For experiments using R(2+1)D and I3D backbone 
(https://github.com/open-mmlab/mmaction2/blob/master/configs/recognition/r2plus1d/README.md), 
(https://github.com/open-mmlab/mmaction2/blob/master/configs/recognition/i3d/README.md),
did you have experiment results on UCF-101 and HMDB-51? If yes, would you mind share with me your experimental results and give me more information about model initialization (random init or ImageNet pre-trained)

Thanks!

**Comment by innerlee** [comment]
Currently we offer ckpts for kinetics400, sth-v2, etc.

UCF101 and HMDB51 are very small datasets, they are not large enough to drive big models. People usually use pretrained models on kinetics and fine-tune on them. This is relatively low cost and can be done on a single card in a relatively short time.

We are not including them for the above reasons. You may request them here https://github.com/open-mmlab/mmaction2/issues/19 and let's see the upvotes
