### ISSUE TITLE
Something wrong with training TSN through FP16=dict(loss_scale='dynamic')

### ISSUE THREAD

**Issue by Wastoon** [open-mmlab/mmaction2#1993]
Hello, thanks for the solid project you guys contribute. I have some question when I train TSN model through FP16=dict(loss_scale='dynamic'). The error like:

   return F.linear(input, self.weight, self.bias)
RuntimeError: expected scalar type Float but found Half

I try to cast input by x.float() to solve this problem, and whole project can run well, but the training cost time is extremely longer than training through fp32. Is there anything wrong with my operation? Looking forward to your reply, and i will very appreciate it!

**Comment by hukkai** [comment]
What is the version of `pytorch`, `mmaction`, `mmcv` and GPU you are using?

**Comment by Wastoon** [comment]
> What is the version of `pytorch`, `mmaction`, `mmcv` and GPU you are using?

Sorry for the late reply. Environment consists of Pytorch==1.11.0, mmaction==0.24.1, mmcv=1.6.2. Whole information is :
<img width="1913" alt="image" src="https://user-images.githubusercontent.com/31173581/196938390-deebf023-9dd6-4341-a8c6-49ee4be23855.png">

**Comment by hukkai** [comment]
@Wastoon I just talked with the colleague who worked on FP16. FP16 is not supported.

**Comment by Wastoon** [comment]
> @Wastoon I just talked with the colleague who worked on FP16. FP16 is not supported.

Thanks for your reply. :) And I will close this issue.
