### ISSUE TITLE
2D skeletons data pre-processing

### ISSUE THREAD

**Issue by RCpengnan** [open-mmlab/mmaction2#1994]
Hello, there are spectators and gymnasts in the gym datastes. The skeleton of spectators and gymnasts can be obtained by using the pose estimation method. Can you tell me how to extract only the skeleton of gymnastics? Thank you~

**Comment by cir7** [comment]
Hi, @RCpengnan , PoseC3D use human poses extracted with GT bounding boxes of athlete, you can download gym skeleton dataset here, for [train](https://download.openmmlab.com/mmaction/posec3d/gym_train.pkl), and for [val](https://download.openmmlab.com/mmaction/posec3d/gym_val.pkl), we will update the link in [Preparing Skeleton Dataset](https://github.com/open-mmlab/mmaction2/tree/master/tools/data/skeleton) soon.

**Comment by hukkai** [comment]
@RCpengnan If you have any further questions, feel free to re-open the issue. Thanks!
