### ISSUE TITLE
Give training dataset resolution info in modelzoo

### ISSUE THREAD

**Issue by innerlee** [open-mmlab/mmaction2#20]
Currently some typical used resolutions for action recognition include:

* 340x256 (i guess it is the legacy of ucf101)
* short-side 256
* height 256
* short-side 320
* height 320
* height 331

Obviously different resolution might or might not influence the accuracy. So it is good to mark the resolution of the training data

Edit:

Forgot about the video format.

**Comment by dreamerlin** [comment]
Fix it in https://github.com/open-mmlab/mmaction2/pull/24.
