### ISSUE TITLE
How to get the accuracy of each class

### ISSUE THREAD

**Issue by taoyang1122** [open-mmlab/mmaction2#2001]
Before raising a question, you may need to check the following listed items.

**Checklist**

1. I have searched related issues but cannot get the expected help.
2. I have read the [FAQ documentation](https://mmaction2.readthedocs.io/en/latest/faq.html) but cannot get the expected help.

Hi, in action recognition tasks, is there a way that I can get the accuracy of each class? Or get the name and accuracy of the top-k and bottom-k classes? Thanks for your help.

**Comment by cir7** [comment]
hi @taoyang1122 , we provide a func `top_k_classes`  in `mmaction/core/evaluation/accuracy.py`, you can try it.

**Comment by taoyang1122** [comment]
Hi, is it possible to give an example to show how to incorporate this function into the test pipeline? Thanks for your help.

**Comment by cir7** [comment]
Hi, @taoyang1122 , for test stage,  I recommend offline evaluate as a easy implement, dump the test results first, and then call `top_k_classes` to get top-k classes.
If you want to support a evaluation metric in training process, it's a little more complicated. We implement evaluation in `BaseDataset`, and support 4 metrics , you can refer it to support `top_k_classes `. Specifically, you need to build a custom dataset, inherit the `VideoDataset`, and overwrite the `evaluate` method, support `top_k_classes` metric, and add it to you config as `evaluation = dict(metrics=['top_k_accuracy', 'top_k_classes']).
btw, for 1.x branch, we optimize this mechanism, split dataset and evaluation metric, you only need to custom a metric and specify it in config, welcome to try 1.x branch.

**Comment by Dai-Wenxun** [comment]
You can add your code [here](https://github.com/open-mmlab/mmaction2/blob/master/mmaction/datasets/base.py#L192).

**Comment by hukkai** [comment]
@taoyang1122 If you have any further questions, feel free to re-open the issue. Thanks!
