### ISSUE TITLE
Question about finetune with pretrained partial model

### ISSUE THREAD

**Issue by xxxxhh** [open-mmlab/mmaction2#2013]
Before raising a question, you may need to check the following listed items.

**Checklist**

1. I have searched related issues but cannot get the expected help.
2. I have read the [FAQ documentation](https://mmaction2.readthedocs.io/en/latest/faq.html) but cannot get the expected help.

Hi there, my question is:
1. In the pretraining stage, I pretrain a model A. And the model A is partial of model B. In the finetuning stage, I would like to finetune model B . Then if I directly using the "load_from" function of runner, is it a right operation?
2. In the pretraining stage, I pretrain a model A. And the model A is partial of model B. In the finetuning stage, I would like to finetune model B . And the model B has an additional new backbone module  C    Then if I directly using the "load_from" function of runner and set the pretrained parameter for the backbone module C, is it a right operation?
3. 1. In the pretraining stage, I pretrain a model A. And there is some non-overlapping params between the finetuned model B and model A. In the finetuning stage, I would like to finetune model B . Then if I directly using the "load_from" function of runner, is it a right operation? And will that incur some errors or simply load the overlapped params instead?

Hi, I've searched the ISSUES and read the DOCS related to model finetuning.
However, I still can not find a good solution.

Hopefully for your help! Thanks!

**Comment by hukkai** [comment]
I think it should be alright to do so since we use `strict=False` when using `load_state_dict`. You can simply try this, and the missing or unexpected_keys keys will be shown on the log. You can check the log to see if this is the desired loading.

**Comment by hukkai** [comment]
@xxxxhh does this solve your question?

**Comment by hukkai** [comment]
@xxxxhh If you have any further questions, feel free to re-open the issue. Thanks!
