### ISSUE TITLE
Questions on video length and model output during inference

### ISSUE THREAD

**Issue by wsong1106** [open-mmlab/mmaction2#2018]
Hi team - I am using the activity recognition models for inferencing on my own video dataset. And have two general questions on the usage.

1. I am wondering if there is any constraint on the video length, or what is the shortest duration of a video that your models can support? 
2. Is it possible to output the timestamp information of the activities detected during inference? I am now using CSN, TSN and TimeSformer models, and it would be useful if the timestamps can be made available in the model output. 

Thanks!

**Comment by hukkai** [comment]
@wsong1106 
1. There is not constraints. For a fixed model, say TimeSformer, the input to the model is 8 frames with interval 32, so it covers 8 * 32 frames. If your video clip is shorter than this, the data processing pipeline will pad the last frame to the model.
2. If your video is supper long, say several minutes, you might need action localization tasks to do this, like BSN?BMN. If your video is short, say 10 seconds, the action recognition task generally regards the action covers the entire video. It's like image recognition v.s. object detection. If you want to achieve this, extra labelling is required.

**Comment by wsong1106** [comment]
Hey Kai -  
Thanks for your response. 
> 1. If your video clip is shorter than this, the data processing pipeline will pad the last frame to the model.
Just want to double check on this: if the clip is shorter than 8*32 frames, will the pipeline pad the last frame of the video, or will pad the clip to 8*32 frames?

**Comment by hukkai** [comment]
We have two options in `SampleFrames `, the first one is to repeat the entire video clip until 8*32 frames. the second is to repeat the last frame as defined here with the `out_of_bound_opt ` option:
https://github.com/open-mmlab/mmaction2/blob/6687bf138449c456200f6cbbf60c338c7703d986/mmaction/datasets/pipelines/loading.py#L99

The default option is `loop`, i.e., repeat the the entire video clip. You can specify your desired option in the config file: https://github.com/open-mmlab/mmaction2/blob/6687bf138449c456200f6cbbf60c338c7703d986/configs/recognition/timesformer/timesformer_divST_8x32x1_15e_kinetics400_rgb.py#L36

**Comment by wsong1106** [comment]
Thanks a lot Kai! This really helps!
