### ISSUE TITLE
AttributeError: FasterRCNN: 'ConfigDict' object has no attribute 'rpn'

### ISSUE THREAD

**Issue by adao777** [open-mmlab/mmaction2#2020]
Hi.
config file: slowonly_omnisource_pretrained_r50_4x16x1_20e_ava_rgb.py
I tried to use FasterRCNN for FastRCNN.
model = dict(
    type='FasterRCNN',

I also added the following content to the config file but got error.
`rpn_head=dict(
        type='RPNHead',
        in_channels=256,
        feat_channels=256,
        anchor_generator=dict(
            type='AnchorGenerator',
            scales=[8],
            ratios=[0.5, 1.0, 2.0],
            strides=[4, 8, 16, 32, 64]),
        bbox_coder=dict(
            type='DeltaXYWHBBoxCoder',
            target_means=[.0, .0, .0, .0],
            target_stds=[1.0, 1.0, 1.0, 1.0]),
        loss_cls=dict(
            type='CrossEntropyLoss', use_sigmoid=True, loss_weight=1.0),
        loss_bbox=dict(type='L1Loss', loss_weight=1.0)),`

**Comment by hukkai** [comment]
`FasterRCNN` is not supported now.

**Comment by adao777** [comment]
@Kai Hu&nbsp; Thank you.
&nbsp;


王俊
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Kai ***@***.***&gt;; 
发送时间: 2022年10月26日(星期三) 上午6:15
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [open-mmlab/mmaction2] AttributeError: FasterRCNN: &#39;ConfigDict&#39; object has no attribute &#39;rpn&#39; (Issue #2020)





 
FasterRCNN is not supported now.
