### ISSUE TITLE
Fail to import ``MultiScaleDeformableAttention

### ISSUE THREAD

**Issue by xudadi001** [open-mmlab/mmaction2#2030]
How to resolve the following errors:
When I run:
python demo/demo.py configs/recognition/tsn/tsn_r50_video_inference_1x1x3_100e_kinetics400_rgb.py https://download.openmmlab.com/mmaction/recognition/tsn/tsn_r50_1x1x3_100e_kinetics400_rgb/tsn_r50_1x1x3_100e_kinetics400_rgb_20200614-e508be42.pth demo/demo.mp4 tools/data/kinetics/label_map_k400.txt

Error prompt：
 warnings.warn('Fail to import ``MultiScaleDeformableAttention`` from '
load checkpoint from http path: https://download.openmmlab.com/mmaction/recognition/tsn/tsn_r50_1x1x3_100e_kinetics400_rgb/tsn_r50_1x1x3_100e_kinetics400_rgb_20200614-e508be42.pth

**Comment by hukkai** [comment]
@xudadi001 Which version of `mmcv` are you using? The error often occurs when you installed the cpu version instead of cuda version `mmcv-full`.

**Comment by xudadi001** [comment]
> @xudadi001 Which version of are you using? The error often occurs when you installed the cpu version instead of cuda version .`mmcv``mmcv-full`
Thank you very much for your tips.
I have solved this problem. The general reason is the conflict between mmcv-full, mmdet, pytorch and cuda versions. But I don't know the specific conflict points. The code can already run.

**Comment by hukkai** [comment]
@xudadi001 Seems you solve the problem. If you need further discussion, feel free to re-open the issue. Thanks!
