### ISSUE TITLE
_pickle.UnpicklingError: invalid load key, '#'

### ISSUE THREAD

**Issue by antonio2600** [open-mmlab/mmaction2#2031]
Hi all!
while running a basic code to test mmaction, this error comes up:

Traceback (most recent call last):
  File "/home/aperez/mmaction2/prueba2.py", line 24, in <module>
    model = init_recognizer(config, checkpoint, device=dev)
  File "/home/aperez/mmaction2/mmaction/apis/inference.py", line 49, in init_recognizer
    load_checkpoint(model, checkpoint, map_location='cpu')
  File "/home/aperez/anaconda3/lib/python3.9/site-packages/mmcv/runner/checkpoint.py", line 638, in load_checkpoint
    checkpoint = _load_checkpoint(filename, map_location, logger)
  File "/home/aperez/anaconda3/lib/python3.9/site-packages/mmcv/runner/checkpoint.py", line 572, in _load_checkpoint
    return CheckpointLoader.load_checkpoint(filename, map_location, logger)
  File "/home/aperez/anaconda3/lib/python3.9/site-packages/mmcv/runner/checkpoint.py", line 314, in load_checkpoint
    return checkpoint_loader(filename, map_location)  # type: ignore
  File "/home/aperez/anaconda3/lib/python3.9/site-packages/mmcv/runner/checkpoint.py", line 334, in load_from_local
    checkpoint = torch.load(filename, map_location=map_location)
  File "/home/aperez/anaconda3/lib/python3.9/site-packages/torch/serialization.py", line 593, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/home/aperez/anaconda3/lib/python3.9/site-packages/torch/serialization.py", line 762, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, '#'.

Any solution? Thnks!

**Comment by hukkai** [comment]
This is likely that your loaded weights are broken.

**Comment by antonio2600** [comment]
It's the first time I try it, I'm doing the colab tutorial. What can I do?

**Comment by antonio2600** [comment]
I'm using this checkpoint:

!wget -c https://download.openmmlab.com/mmaction/recognition/tsn/tsn_r50_1x1x3_100e_kinetics400_rgb/tsn_r50_1x1x3_100e_kinetics400_rgb_20200614-e508be42.pth \ -O checkpoints/tsn_r50_1x1x3_100e_kinetics400_rgb_20200614-e508be42.pth

It's the checkpoint that provides APIs

**Comment by hukkai** [comment]
@antonio2600 Did you try to delete that file, download and load it again?

**Comment by antonio2600** [comment]
Ok, I will try it.

**Comment by antonio2600** [comment]
Thanks for the help. From the terminal it 's seen that it was downloaded with errors. I have downloaded it from the link and everything is correct.

**Comment by hukkai** [comment]
If you need any further discussion, feel free to re-open the issue.

**Comment by antonio2600** [comment]
Hi, I have a question about adding new dataset.
I'm working in Google Colab and I have downloaded the kinetics400 dataset from the official page. Once the tar file is downloaded, inside there are 6 files, 3 csv (train, test and evaluate) and 3 json (train, test and evaluate). Once the dataset was added to the colab session, I checked if the dataset was correct and the result is this:

**Comment by antonio2600** [comment]
youtube_id	time_start	time_end	split
label				
testifying	             ---QUuC4vJs	     84	             94	train
eating spaghetti    --3ouPhoy2A	     20	             30	train
dribbling basketball	--4-0ihtnBU	     58	             68	train

**Comment by antonio2600** [comment]
This is the output of trainDataset.head(5). 
My question is, how do I create a model that fits this dataset and be able to train it?
Thnks!
