### ISSUE TITLE
What is the best practice for me to add mixed precision training in mmaction2

### ISSUE THREAD

**Issue by weiaicunzai** [open-mmlab/mmaction2#2033]
Hi, guys. thanks for your great work.
I am new to mmaction2, and I have noticed that FP16 training is not fully  supported (e.g. https://github.com/open-mmlab/mmaction2/issues/1993, https://github.com/open-mmlab/mmaction2/issues/1510 ,  https://github.com/open-mmlab/mmaction2/issues/1769) as  other  open-mmlab libraries (e.g. mmsegmentation). 

So, could you please tell me what is the best practice for me to use FP16 training in my own project ? 
Thanks in advance.

**Comment by hukkai** [comment]
@weiaicunzai My suggestion is not use mixed precision for 3d networks as there can be an unknown performance drop: https://github.com/pytorch/pytorch/issues/63313

**Comment by weiaicunzai** [comment]
> @weiaicunzai My suggestion is not to use mixed precision for 3d networks as there can be a performance drop with unknown reasons: [pytorch/pytorch#63313](https://github.com/pytorch/pytorch/issues/63313). I have also experienced related issues.

Thanks for your reply, Does  "3D networks"  include 3D Transformers?   Or simply 3D CNNs? Thanks.

**Comment by hukkai** [comment]
3D CNNs. Not sure for the 3D transformer case.

**Comment by weiaicunzai** [comment]
> 3D CNNs. Not sure for the 3D transformer case.

Thanks.
