### ISSUE TITLE
ConfigDict' object has no attribute 'gpu_id

### ISSUE THREAD

**Issue by MooresS** [open-mmlab/mmaction2#2037]
I see such a problem in issue, but it is training rather than testing.

```
python tools/test.py configs/recognition/slowonly/slowonly_r50_4x16x1_256e_kinetics400_rgb.py 
    checkpoints/SOME_CHECKPOINT.pth --eval top_k_accuracy mean_class_accuracy \
    --out result.json --average-clips=prob
```
Attribute Error:ConfigDict' object has no attribute 'gpu_id.
```mmcv-full==1.4.7 pytorch==1.10.1 mmaction2==0.24.1```

**Comment by cir7** [comment]
Hi, @MooresS , the solution is same, add gpu_id in your config file

**Comment by MooresS** [comment]
Do you mean to add additional parameters after the command line, such as -- gpu_ids [0]?
It will report an error
```error:unrecognized arguments: --gpu_ids [0]```

**Comment by cir7** [comment]
Hi, @MooresS , `gpu-ids` is not a argument for `test.py`, you can add it in your config file `configs/recognition/slowonly/slowonly_r50_4x16x1_256e_kinetics400_rgb.py`.
or add additional parameters after command line as `--cfg-options gpu_ids=[0]`

**Comment by MooresS** [comment]
Thank you very much for your reply. The problem has been solved.
I'm very sorry that I have another problem. Would you mind helping me solve it?
I can verify on the verification set during training. But during the test, I found that it gets the same data from data_loader every time.But the information of all videos in the data_loader.dataset.video_infos is correct.

**Comment by cir7** [comment]
hi, @MooresS , could you provide more detailed information, about your specific config, and are you using a custom dataset, or a common dataset?

**Comment by MooresS** [comment]
My config file is 
```configs/recognition/slowonly/slowonly_r50_4x16x1_256e_kinetics400_rgb.py```
And additional parameters after command line as --cfg-options gpu_ids=[0].
I extract one tenth of the kinetics400 data as my dataset and prepare my dataset according to official documents.
I can verify on the verification set during training. 
![222](https://user-images.githubusercontent.com/56434431/201244041-6ef22921-dd47-44cb-9c71-f5e0ec63ea17.png)
But during the test, I found that it gets the same data from data_loader every time.
![image](https://user-images.githubusercontent.com/56434431/201243682-f0f1ec15-1269-4b42-94b8-b45df94e196f.png)

**Comment by cir7** [comment]
Hi, @MooresS , it seems that the test annotation file has some problems, you can try the original k400 or other dataset to make sure that the code is correct. Another possibility is that you accidentally modified test related code, in that case you can install a new mmaction2 repo and try your custom dataset. Hope this helps you.

**Comment by MooresS** [comment]
Thanks for your advice and I'll try it.Thank you very much for your help.
