### ISSUE TITLE
Does 2s-AGCN have weights for 2D bone points?

### ISSUE THREAD

**Issue by Better369** [open-mmlab/mmaction2#2041]
I see that the weights provided are only 3D. Only ST-GCN has 2D weights, so I wonder if 2S-AGCN has 2D bone weights.

**Comment by Dai-Wenxun** [comment]
We will refactor out skeleton-based pipeline to support joint, bone, joint-motion and bone-motion and provide these weights in [1.x branch](https://github.com/open-mmlab/mmaction2/tree/1.x).

**Comment by Better369** [comment]
Do the master version and the 1.x version use different project files? I copied some programs and weights from version 1.x to the master project file, and the result would be an error.
