### ISSUE TITLE
about  mmaction2/demo/visualize_heatmap_volume.ipynb

### ISSUE THREAD

**Issue by shadowtears** [open-mmlab/mmaction2#2043]
I replaced the ucf dataset (the download address is ucf101: https://download.openmmlab.com/mmaction/posec3d/ucf101.pkl ）But in the demo, I found that the number of frames did not match. For example, I found that the first video were one frame away. Then I adjusted the frame number, but still reported an error.

code as list:

```
import os
import cv2
import os.path as osp
import decord
import numpy as np
import matplotlib.pyplot as plt
import urllib
import moviepy.editor as mpy
import random as rd
from mmpose.apis import vis_pose_result
from mmpose.models import TopDown
from mmcv import load, dump

ucf101_ann_file = '/tanglg/mhd/source/mmaction2/data/posec3d/ucf101.pkl
FONTFACE = cv2.FONT_HERSHEY_DUPLEX
FONTSCALE = 0.6
FONTCOLOR = (255, 255, 255)
BGBLUE = (0, 119, 182)
THICKNESS = 1
LINETYPE = 1
def add_label(frame, label, BGCOLOR=BGBLUE):
    threshold = 30
    def split_label(label):
        label = label.split()
        lines, cline = [], ''
        for word in label:
            if len(cline) + len(word) < threshold:
                cline = cline + ' ' + word
            else:
                lines.append(cline)
                cline = word
        if cline != '':
            lines += [cline]
        return lines
    
    if len(label) > 30:
        label = split_label(label)
    else:
        label = [label]
    label = ['Action: '] + label
    
    sizes = []
    for line in label:
        sizes.append(cv2.getTextSize(line, FONTFACE, FONTSCALE, THICKNESS)[0])
    box_width = max([x[0] for x in sizes]) + 10
    text_height = sizes[0][1]
    box_height = len(sizes) * (text_height + 6)
    
    cv2.rectangle(frame, (0, 0), (box_width, box_height), BGCOLOR, -1)
    for i, line in enumerate(label):
        location = (5, (text_height + 6) * i + text_height + 3)
        cv2.putText(frame, line, location, FONTFACE, FONTSCALE, FONTCOLOR, THICKNESS, LINETYPE)
    return frame
    

def vis_skeleton(vid_path, anno, category_name=None, ratio=0.5):
    vid = decord.VideoReader(vid_path)
    # frames = [x.asnumpy() for x in vid]
    frames = [x.asnumpy() for x in vid][:-1]

    h, w, _ = frames[0].shape
    new_shape = (int(w * ratio), int(h * ratio))
    frames = [cv2.resize(f, new_shape) for f in frames]

    assert len(frames) == anno['total_frames']
    # The shape is N x T x K x 3
    kps = np.concatenate([anno['keypoint'], anno['keypoint_score'][..., None]], axis=-1)
    kps[..., :2] *= ratio
    # Convert to T x N x K x 3
    kps = kps.transpose([1, 0, 2, 3])
    vis_frames = []

    # we need an instance of TopDown model, so build a minimal one
    model = TopDown(backbone=dict(type='ShuffleNetV1'))

    for f, kp in zip(frames, kps):
        bbox = np.zeros([0, 4], dtype=np.float32)
        result = [dict(bbox=bbox, keypoints=k) for k in kp]
        vis_frame = vis_pose_result(model, f, result)
        
        if category_name is not None:
            vis_frame = add_label(vis_frame, category_name)
        
        vis_frames.append(vis_frame)
    return vis_frames
keypoint_pipeline = [
    dict(type='PoseDecode'),
    dict(type='PoseCompact', hw_ratio=1., allow_imgpad=True),
    dict(type='Resize', scale=(-1, 64)),
    dict(type='CenterCrop', crop_size=64),
    dict(type='GeneratePoseTarget', sigma=0.6, use_score=True, with_kp=True, with_limb=False)
]

limb_pipeline = [
    dict(type='PoseDecode'),
    dict(type='PoseCompact', hw_ratio=1., allow_imgpad=True),
    dict(type='Resize', scale=(-1, 64)),
    dict(type='CenterCrop', crop_size=64),
    dict(type='GeneratePoseTarget', sigma=0.6, use_score=True, with_kp=False, with_limb=True)
]

from mmaction.datasets.pipelines import Compose
def get_pseudo_heatmap(anno, flag='keypoint'):
    assert flag in ['keypoint', 'limb']
    pipeline = Compose(keypoint_pipeline if flag == 'keypoint' else limb_pipeline)
    return pipeline(anno)['imgs']

def vis_heatmaps(heatmaps, channel=-1, ratio=8):
    # if channel is -1, draw all keypoints / limbs on the same map
    import matplotlib.cm as cm
    h, w, _ = heatmaps[0].shape
    newh, neww = int(h * ratio), int(w * ratio)
    
    if channel == -1:
        heatmaps = [np.max(x, axis=-1) for x in heatmaps]
    cmap = cm.viridis
    heatmaps = [(cmap(x)[..., :3] * 255).astype(np.uint8) for x in heatmaps]
    heatmaps = [cv2.resize(x, (neww, newh)) for x in heatmaps]
    return heatmaps
ucf_categories = list()
ucf_lines = open('/tanglg/mhd/source/mmaction2/data/ucf101/annotations/classInd.txt','r')
for line in ucf_lines.readlines():
  ucf_categories.append(line.split(' ')[1])
ucf_annos = load(ucf101_ann_file)
ucf_root = '/tanglg/mhd/source/mmaction2/data/ucf101/test/'
ucf_vids = os.listdir(ucf_root)
idx = 0
vid = ucf_vids[idx]
frame_dir = vid.split('.')[0]
vid_path = osp.join(ucf_root, vid)
anno = [x for x in ucf_annos['annotations'] if x['frame_dir'] == frame_dir][0]
vis_frames = vis_skeleton(vid_path, anno, ucf_categories[anno['label']])
vid = mpy.ImageSequenceClip(vis_frames, fps=24)
vid.ipython_display()
```

error as follow:
Output exceeds the [size limit](command:workbench.action.openSettings?[). Open the full output data [in a text editor](command:workbench.action.openLargeOutput?31a4ff8b-2453-4a2a-9198-b5948352a9d3)
---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
/tmp/ipykernel_53487/4164506019.py in <module>
      1 # Visualize Skeleton
      2 # vis_frames = vis_skeleton(vid_path, anno, gym_categories[anno['label']])
----> 3 vis_frames = vis_skeleton(vid_path, anno, ucf_categories[anno['label']])
      4 vid = mpy.ImageSequenceClip(vis_frames, fps=24)
      5 vid.ipython_display()

/tmp/ipykernel_53487/1939905896.py in vis_skeleton(vid_path, anno, category_name, ratio)
     57         bbox = np.zeros([0, 4], dtype=np.float32)
     58         result = [dict(bbox=bbox, keypoints=k) for k in kp]
---> 59         vis_frame = vis_pose_result(model, f, result)
     60 
     61         if category_name is not None:

/tanglg/mhd/source/mmpose/mmpose/apis/inference.py in vis_pose_result(model, img, result, radius, thickness, kpt_score_thr, bbox_color, dataset, dataset_info, show, out_file)
    801         bbox_color=bbox_color,
    802         show=show,
--> 803         out_file=out_file)
    804 
    805     return img

/tanglg/commonsoft/miniconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/utils/misc.py in new_func(*args, **kwargs)
    338 
...
---> 79         assert len(labels) == len(bboxes)
     80 
     81         for bbox, label, color in zip(bboxes, labels, colors):

AssertionError:

**Comment by jmpipina** [comment]
Hi, just to say I was having the same issue and fixed it by replacing this line in vis_skeleton:
`result = [dict(bbox=bbox, keypoints=k) for k in kp]`
for
`result = [dict(keypoints=k) for k in kp]`

This is how it's written in the current [pyskl](https://github.com/kennymckormick/pyskl/blob/main/demo/visualize_heatmap_volume.ipynb) version (I guess this doesn't use `bbox` anymore?)
Hopefully this is helpful for anyone running into this problem.

**Comment by shadowtears** [comment]
> 



> Hi, just to say I was having the same issue and fixed it by replacing this line in vis_skeleton: `result = [dict(bbox=bbox, keypoints=k) for k in kp]` for `result = [dict(keypoints=k) for k in kp]`
> 
> This is how it's written in the current [pyskl](https://github.com/kennymckormick/pyskl/blob/main/demo/visualize_heatmap_volume.ipynb) version (I guess this doesn't use `bbox` anymore?) Hopefully this is helpful for anyone running into this problem.

thanks guys!!you help me so much.
