### ISSUE TITLE
Errors when downloading ActivityNet

### ISSUE THREAD

**Issue by weirukai** [open-mmlab/mmaction2#2054]
Hello! I meet the error "gzip: stdin: invalid compressed data--format violated" when dealing with the file Anet_v1-3_train_val.tar. I downloaded the split128 from Baidu Drive and conducted the "cat" to generate the file Anet_v1-3_train_val.tar. How can I solve this problem?

**Comment by hukkai** [comment]
@weirukai which command and url did you use to download activitynet?

**Comment by weirukai** [comment]
@hukkai I downloaded ActivityNet from the official URL. The official website provides two sources for download; I downloaded from Baidu Drive.

**Comment by hukkai** [comment]
Maybe you can try this method to download the dataset https://github.com/open-mmlab/mmaction2/blob/master/tools/data/activitynet/README.md

**Comment by hukkai** [comment]
@weirukai If you need further discussion, please feel free to re-open the issue.
