### ISSUE TITLE
Adding new dataset mmaction2

### ISSUE THREAD

**Issue by antonio2600** [open-mmlab/mmaction2#2056]
Hi all!
I have a question about adding new dataset.
I'm working in Google Colab and I have downloaded the kinetics400 dataset from the official page. Once the tar file is downloaded, inside there are 6 files, 3 csv (train, test and evaluate) and 3 json (train, test and evaluate). Once the dataset was added to the colab session, I checked if the dataset was correct and the result is this:

                      youtube_id	time_start	time_end	split
label
testifying           ---QUuC4vJs         84              94         train
eating spaghetti     --3ouPhoy2A         20              30         train
dribbling basketball --4-0ihtnBU         58              68         train

This is the output of trainDataset.head(3).
My question is, how do I create a model that fits this dataset and be able to train it?
Thnks!

**Comment by hukkai** [comment]
@antonio2600 You can follow this page https://github.com/open-mmlab/mmaction2/tree/master/tools/data/kinetics to prepare kinetics400 dataset.

**Comment by hukkai** [comment]
@antonio2600 That is the problem of Colab. Kinetics500 is a large dataset, and not very suitable to be trained on Colab. Maybe you can process the data locally and then upload to Colab.

**Comment by antonio2600** [comment]
But having the dataset as indicated above, I have the idYoutube, would there be any way to access the videos by adjusting the model?

**Comment by antonio2600** [comment]
![Captura desde 2022-11-15 16-05-30](https://user-images.githubusercontent.com/42941507/201953379-c18be746-d3c7-4124-97a8-4784e73755d9.png)

**Comment by hukkai** [comment]
This is the fastest way to get the dataset: https://github.com/cvdfoundation/kinetics-dataset.
If you still get time out then there is no other ways.

**Comment by antonio2600** [comment]
On this page https://github.com/cvdfoundation/kinetics-dataset, the dataset that you get when you download it is in csv format too. That's as I have it, it appears in the photo. My question is, how do I access the videos and adapt everything to the model to train it?

**Comment by hukkai** [comment]
Please read that page carefully. There are AWS tar file downloading formats.

**Comment by antonio2600** [comment]
Hello.
This dataset is too big and I think that I don't need so much information. Do you know another dataset that isn't so big and is more oriented to common or household activities?

**Comment by hukkai** [comment]
You can look at this page to see if any supported dataset fits for you https://github.com/open-mmlab/mmaction2#supported-datasets
