### ISSUE TITLE
configs\skeleton\stgcn\stgcn_80e_ntu60_xsub_keypoint.py

### ISSUE THREAD

**Issue by hsp2454** [open-mmlab/mmaction2#2059]
Hello, when I run "python tools\train.py configs\skeleton\stgcn\stgcn_80e_ntu60_xsub_keypoint.py", I report"
RuntimeError: running_mean should contain 63 elements not 51 ", the search answer is the number of channels is not consistent, what is the problem?
![image](https://user-images.githubusercontent.com/115400289/202100548-86e1a528-4e03-4eb8-b417-cf6dee89efcc.png)

**Comment by hukkai** [comment]
@hsp2454 Did you modify the config? What is the full command you ran?

**Comment by hsp2454** [comment]
I just changed the data path in 'configs\skeleton\stgcn\stgcn_80e_ntu60_xsub_keypoint.py', nothing else. Then I ran 'python tools\train.py configs\skeleton\stgcn\stgcn_80e_ntu60_xsub_keypoint.py' to train my data.
















At 2022-11-16 14:33:35, "Kai Hu" ***@***.***> wrote:

@hsp2454 Did you modify the config? What is the full command you ran?

**Comment by Dai-Wenxun** [comment]
![image](https://user-images.githubusercontent.com/58767402/202105956-3a35a217-ae3c-4040-bf5a-7b6e37ee3a3e.png)
please check your 2d keypoint data format.

**Comment by cir7** [comment]
@hsp2454 Are you using a custom dataset, it seems that `num_node` of your dataset is different from our version, which contains 17 node. for a custom dataset, you should support a new graph layout in `mmaction/models/skeleton_gcn/utils/graph.py`

**Comment by hsp2454** [comment]
Ok, thank you for your answers. I'll try

**Comment by cir7** [comment]
futher disscussion in #2060
