### ISSUE TITLE
Some Errors while Installing from Dockerfile in docker/Dockerfile

### ISSUE THREAD

**Issue by MasoudKaviani** [open-mmlab/mmaction2#2061]
Thanks for your error report and we appreciate it a lot.
If you feel we have help you, give us a STAR! :satisfied:

**Checklist**

1. I have searched related issues but cannot get the expected help.
2. The bug has not been fixed in the latest version.

**Describe the bug**

**Reproduction**

1. What command or script did you run?

```
cd docker
docker build -t mmlabmmaction --file Dockerfile .
```

2. Did you make any modifications on the code or config? Did you understand what you have modified?
3. What dataset did you use?

**Environment**

1. Please run `PYTHONPATH=${PWD}:$PYTHONPATH python mmaction/utils/collect_env.py` to collect necessary environment information and paste it here.
2. You may add addition that may be helpful for locating the problem, such as
   - How you installed PyTorch \[e.g., pip, conda, source\]
   - Other environment variables that may be related (such as `$PATH`, `$LD_LIBRARY_PATH`, `$PYTHONPATH`, etc.)

**Error traceback**

If applicable, paste the error traceback here.

```
Some Nvidia repositories keys are deprecated and Nvidia offers a new key on ubuntu18.08 refer to [this link](https://developer.nvidia.com/blog/updating-the-cuda-linux-gpg-repository-key/)
```

**Bug fix**

I'll be fixed it and make a PR for this

**Comment by cir7** [comment]
@MasoudKaviani Thanks for you feedback, the issue has been fixed in pr #1957 . If you have any further questions, feel free to reopen the issue
