### ISSUE TITLE
ImportError: cannot import name 'digit_version' from 'mmcv'

### ISSUE THREAD

**Issue by xudadi001** [open-mmlab/mmaction2#2065]
![5LUGMQV) H I$VMSB$NP8 X](https://user-images.githubusercontent.com/65487336/202442696-25d61137-e502-4807-8c1d-8ec7354b7394.png)
how to deal with it

**Comment by USTBhyh** [comment]
hello, I meet the same problem, may you share your solution with me?

**Comment by xudadi001** [comment]
> hello, I meet the same problem, may you share your solution with me?

rebuild a new environment and mmcv

**Comment by yemboi** [comment]
Hello, has anyone found a resolution to this? Ive gone through the installation steps but keep on getting this error message -  cannot import name 'digit_version'
