### ISSUE TITLE
ImportError: cannot import name 'register_all_modules' from 'mmaction.utils' 

### ISSUE THREAD

**Issue by xudadi001** [open-mmlab/mmaction2#2066]
![XPUNB HCIS_ 537WZJ(SJCB](https://user-images.githubusercontent.com/65487336/202446252-fc7cc29d-b21d-4a2f-b9ad-9954714248c6.png)

**Comment by hukkai** [comment]
@xudadi001 did you successfully installed `mmaction2`? Can you try `import mmaction` in python. I tried this locally and it can be imported.

**Comment by xudadi001** [comment]
Thank you very much. It was a version problem. I solved a problem.
