### ISSUE TITLE
Classification issues

### ISSUE THREAD

**Issue by 1Smallwhite2** [open-mmlab/mmaction2#2067]
ucf101_{train,val}_split_{1,2,3}_rawframes.txt and ucf101_{train,val}_split_{1,2,3_videos.txt} file The category number is not classified correctly, and the true classification number is minus one.
![image](https://user-images.githubusercontent.com/118441279/202681207-798b2cff-8d69-41d7-a576-d4b355ae3be0.png)

**Comment by cir7** [comment]
Hi, @1Smallwhite2 , The label is just a index, which only need to one-to-one map the original class index, and for programming conventions, the index start from 0, not 1.

**Comment by 1Smallwhite2** [comment]
> 

Ok, thank you very much
