### ISSUE TITLE
Training on raw videos vs. extracted frame images

### ISSUE THREAD

**Issue by yossibiton** [open-mmlab/mmaction2#2069]
I wonder if you compared the training speed when using raw videos vs. raw frame images (in the 2nd option I mean that frames are saved as images to disk as preprocessing stage).
I see that most configs use the raw frames option despite the fact that the original datasets format is video files.
However, in other code packages (e.g. [SlowFast](https://github.com/facebookresearch/SlowFast/blob/main/slowfast/datasets/kinetics.py)) I see that usually the raw video is used in the dataset class.

**Comment by cir7** [comment]
@yossibiton We have a description about use raw frames or video in our [doc](https://mmaction2.readthedocs.io/en/latest/data_preparation.html#notes-on-video-data-format), personally, I prefer video input, and the training speed is almost same if you have enough CPU to decode video

**Comment by yossibiton** [comment]
Thanks ! that's the part in the documentation I missed
