### ISSUE TITLE
About the testing accuracy of the model

### ISSUE THREAD

**Issue by WEIZHIHONG720** [open-mmlab/mmaction2#2073]
Hi, thank you for your work.
I see that the ucf-101 dataset is divided into three folds, corresponding to train and test.
Is the final test accuracy obtained by averaging the three folds dataset at the end?

**Comment by hukkai** [comment]
It is the test accuracy on split 1.

**Comment by hukkai** [comment]
@WEIZHIHONG720  If you need further discussion, please feel free to re-open the issue. Thanks!
