### ISSUE TITLE
Using PySKL on OpenPose Body25 configuration

### ISSUE THREAD

**Issue by IlyesTal** [open-mmlab/mmaction2#2086]
Hi,

I am trying to use PySKL 3D with Body25 configuration (the one from OpenPose), is it possible to do it ?

<img width="795" alt="Capture d’écran 2022-11-21 à 12 13 25" src="https://user-images.githubusercontent.com/62403360/203358533-5e31685c-23e6-4dea-becc-639d0f15d83c.png">

**Comment by IlyesTal** [comment]
Thank you for your reply @Dai-Wenxun 
I'll try this and update you :)

**Comment by 15762260991** [comment]
@Dai-Wenxun 大佬，请问是否可以使用openpose提取的关键点训练posec3d呢？您可以给出一些指导吗？

**Comment by Dai-Wenxun** [comment]
If you have already prepared your skeleton data according to our standard format (download the [ucf101 skeleton data](https://download.openmmlab.com/mmaction/posec3d/ucf101.pkl) for more details), then you need to modify three args of ` GeneratePoseTarget` (i.e., [`skeletons` ](https://github.com/open-mmlab/mmaction2/blob/master/mmaction/datasets/pipelines/pose_loading.py#L382), [`left_kp`](https://github.com/open-mmlab/mmaction2/blob/1af84d024420c2887208e48b031aa6519a0fdd18/mmaction/datasets/pipelines/pose_loading.py#L386), and [`right_kp`](https://github.com/open-mmlab/mmaction2/blob/master/mmaction/datasets/pipelines/pose_loading.py#L387)), which defines the graph to draw the skeleton on the 3D heatmap. At the same time, you need to modify the [in_channels](https://github.com/open-mmlab/mmaction2/blob/master/configs/skeleton/posec3d/slowonly_r50_u48_240e_ntu60_xsub_keypoint.py#L7) of the model, which is the number of joints of your openpose estimation results. 

I'm not sure whether there are any bugs. Anyway, have a try! Good luck! @15762260991
