### ISSUE TITLE
action recogniton of multiple targets 

### ISSUE THREAD

**Issue by LlemoningL** [open-mmlab/mmaction2#2090]
Before raising a question, you may need to check the following listed items.

**Checklist**

1. I have searched related issues but cannot get the expected help.
2. I have read the [FAQ documentation](https://mmaction2.readthedocs.io/en/latest/faq.html) but cannot get the expected help.

### > Can posec3d recognize action from multiple targets respectively in one video at the same time?
paper says it can represent all people with a single heatmap volume to do the recognition, how about every single target action recogniton in one screen（different action）? If it can do this, what should I suppose to do？
Thank you for your reply and hope you have good days.

**Comment by Dai-Wenxun** [comment]
Currently, posec3d only supports recognizing the entire video instead of the atom actions of different people. What you said should be using posec3d for spatio-temporal action detection, which is not supported yet.

**Comment by LlemoningL** [comment]
> Currently, posec3d only supports recognizing the entire video instead of the atom actions of different people. What you said should be using posec3d for spatio-temporal action detection, which is not supported yet.

你好，我看mmaction2的主界面有个动图，里面有三个人在同一画面里，每个人分别识别了站立的动作，还能整体判断为吹风笛，这是通过什么途径实现的呢？
