### ISSUE TITLE
 Training with a dataset that does not provide mmaction

### ISSUE THREAD

**Issue by antonio2600** [open-mmlab/mmaction2#2091]
Hello, I have a question about using a new dataset that isn't in supported datasets.
I have download toyota smarthome dataset and I want to create a new model and I want to train from 0.
My question is, the file that uses the example of 'Train a recognizer on customized dataset', './checkpoints/tsn_r50_1x1x3_100e_kinetics400_rgb_20200614-e508be42.pth' I don't know how I have to do it for my new dataset.
And the file './configs/recognition/tsn/tsn_r50_video_1x1x8_100e_kinetics400_rgb.py' I don't know if I have to create a new one or modify that one for example.
Thanks!

**Comment by Dai-Wenxun** [comment]
First, you need to change the `data_root` and `data_root_val`, which are the root path of your videos for training and testing. Next, prepare your annotation files, and then modify the `ann_file_train`, `ann_file_val`, and `ann_file_test` respectively.  An example of an annotation file looks like [this](https://github.com/open-mmlab/mmaction2/blob/master/mmaction/datasets/video_dataset.py#L21-L26).

**Comment by antonio2600** [comment]
Ok. But the annotation files aren't the .txt files which have the name of the video and a label?

**Comment by Dai-Wenxun** [comment]
That's right.
