### ISSUE TITLE
Why is it inconsistent between the number of GPUs used for training in the log file and the README?

### ISSUE THREAD

**Issue by leexinhao** [open-mmlab/mmaction2#2095]
For example, I notice that the number of GPUs used for [slowfast_r50_4x16x1_256e_kinetics400_rgb](https://vscode-remote+wsl-002bubuntu-002d18-002e04.vscode-resource.vscode-cdn.net/configs/recognition/slowfast/slowfast_r50_4x16x1_256e_kinetics400_rgb.py) in configs/recognition/slowfast/README.md is 8x4:

![image](https://user-images.githubusercontent.com/48858574/204071519-71685377-4815-4882-9ab3-d6cdefae8a6c.png)

But when I glance over the [log](https://download.openmmlab.com/mmaction/recognition/slowfast/slowfast_r50_256p_4x16x1_256e_kinetics400_rgb/20200731_151706.log) I notice that the number of GPUs seem to be 8:
![image](https://user-images.githubusercontent.com/48858574/204071685-e75a813f-e9d9-4c6a-85e2-cd11685d602c.png)
 
Is there something wrong with my understanding?

**Comment by hukkai** [comment]
@leexinhao This is the log on one GPU machine. We only released the log on one machine. It is expected.
