### ISSUE TITLE
How config to get result like example gif

### ISSUE THREAD

**Issue by lehoangh** [open-mmlab/mmaction2#2098]
Before raising a question, you may need to check the following listed items.

**Checklist**

1. I have searched related issues but cannot get the expected help.
2. I have read the [FAQ documentation](https://mmaction2.readthedocs.io/en/latest/faq.html) but cannot get the expected help.
3. 

I have a question, that how can I config some parameters or which models to get same result of this example gif: 
![Uploading 3FFD7C68-CC85-4D0D-B1C0-607951ACF26C.jpeg…]()

**Comment by hukkai** [comment]
@lehoangh Can you upload the gif again? It seems uploading is failed.

**Comment by lehoangh** [comment]
![FA3573CA-8061-4957-B9F7-B2D828CCCD02](https://user-images.githubusercontent.com/23434461/204417194-4be0c139-7a82-4c6d-98de-6b7ee4df068d.jpeg)

**Comment by hukkai** [comment]
You can refer to this demo: https://github.com/open-mmlab/mmaction2/tree/master/demo#video-structuralize-demo

**Comment by lehoangh** [comment]
Thank you. I will try it
