### ISSUE TITLE
Confusion about TSN performance on activitynet

### ISSUE THREAD

**Issue by zeyu-liu** [open-mmlab/mmaction2#210]
What's the difference between tsn_r50_320p_1x1x8_50e_activitynet_video_rgb and tsn_r50_320p_1x1x8_50e_activitynet_clip_rgb? The config files are exactly same but top1 acc have a gap ~2%.

**Comment by kennymckormick** [comment]
Video_rgb uses untrimmed videos for training; clip_rgb uses trimmed clips for training. All of them use trimmed clips for testing.

**Comment by innerlee** [comment]
we can put this info as a note in the readme
