### ISSUE TITLE
KeyError: 'FastRCNN is not in the models registry'

### ISSUE THREAD

**Issue by asd8095075** [open-mmlab/mmaction2#2102]
import torch
from mmaction.apis import init_recognizer, inference_recognizer

config_file = 'D:/python数据分析/计算机视觉/mmaction2-0.24.1/configs/detection/ava/slowfast_kinetics_pretrained_r50_8x8x1_20e_ava_rgb.py'
# 从模型库中下载检测点，并把它放到 `checkpoints/` 文件夹下
checkpoint_file = 'D:/python数据分析/计算机视觉/mmaction2-0.24.1/slowfast_kinetics_pretrained_r50_8x8x1_20e_ava_rgb_20201217-ae225e97.pth'

# 指定设备
device = 'cuda:0' # or 'cpu'
device = torch.device(device)

 # 根据配置文件和检查点来建立模型
model = init_recognizer(config_file, checkpoint_file, device=device)

# 测试单个视频并显示其结果
video = 'http://vfx.mtime.cn/Video/2019/02/04/mp4/190204084208765161.mp4'
labels = 'D:/python数据分析/计算机视觉/mmaction2/tools/data/ava/label_map.txt'
results = inference_recognizer(model, video)

# 显示结果
labels = open('D:/python数据分析/计算机视觉/mmaction2/tools/data/ava/label_map.txt').readlines()
labels = [x.strip() for x in labels]
results = [(labels[k[0]], k[1]) for k in results]

print(f'The top-5 labels with corresponding scores are:')
for result in results:
    print(f'{result[0]}: ', result[1])

---------------------------------------------------------------------------------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
Cell In[2], line 10
      7 device = torch.device(device)
      9  # 根据配置文件和检查点来建立模型
---> 10 model = init_recognizer(config_file, checkpoint_file, device=device)
     12 # 测试单个视频并显示其结果
     13 video = 'http://vfx.mtime.cn/Video/2019/02/04/mp4/190204084208765161.mp4'

File D:\python数据分析\计算机视觉\mmaction2-0.24.1\mmaction\apis\inference.py:46, in init_recognizer(config, checkpoint, device, **kwargs)
     44 # pretrained model is unnecessary since we directly load checkpoint later
     45 config.model.backbone.pretrained = None
---> 46 model = build_recognizer(config.model, test_cfg=config.get('test_cfg'))
     48 if checkpoint is not None:
     49     load_checkpoint(model, checkpoint, map_location='cpu')

File D:\python数据分析\计算机视觉\mmaction2-0.24.1\mmaction\models\builder.py:52, in build_recognizer(cfg, train_cfg, test_cfg)
     46 assert cfg.get(
     47     'train_cfg'
     48 ) is None or train_cfg is None, 'train_cfg specified in both outer field and model field'  # noqa: E501
     49 assert cfg.get(
     50     'test_cfg'
     51 ) is None or test_cfg is None, 'test_cfg specified in both outer field and model field '  # noqa: E501
---> 52 return RECOGNIZERS.build(
     53     cfg, default_args=dict(train_cfg=train_cfg, test_cfg=test_cfg))

File ~\Envs\mmaction\lib\site-packages\mmcv\utils\registry.py:237, in Registry.build(self, *args, **kwargs)
    236 def build(self, *args, **kwargs):
--> 237     return self.build_func(*args, **kwargs, registry=self)

File ~\Envs\mmaction\lib\site-packages\mmcv\cnn\builder.py:27, in build_model_from_cfg(cfg, registry, default_args)
     25     return Sequential(*modules)
     26 else:
---> 27     return build_from_cfg(cfg, registry, default_args)

File ~\Envs\mmaction\lib\site-packages\mmcv\utils\registry.py:61, in build_from_cfg(cfg, registry, default_args)
     59     obj_cls = registry.get(obj_type)
     60     if obj_cls is None:
---> 61         raise KeyError(
     62             f'{obj_type} is not in the {registry.name} registry')
     63 elif inspect.isclass(obj_type) or inspect.isfunction(obj_type):
     64     obj_cls = obj_type

KeyError: 'FastRCNN is not in the models registry'

**Comment by Dai-Wenxun** [comment]
The config file you used is for spatio-temporal action detection, but the inference API you used is for action recognition. For spatio-temporal action detection, you should use [demo_spatiotemporal_det.py](https://github.com/open-mmlab/mmaction2/blob/master/demo/demo_spatiotemporal_det.py). Here is the [tutorial](https://github.com/open-mmlab/mmaction2/tree/master/demo#spatiotemporal-action-detection-video-demo) for this demo. Good luck! @asd8095075.
