### ISSUE TITLE
IndexError: invalid index to scalar variable.

### ISSUE THREAD

**Issue by hsp2454** [open-mmlab/mmaction2#2114]
When I run 'python ntu_pose_extractivity.py S001C001P001R001A001_rgb.avi S001C001P001R001A001.pkl' in tools\data\skeleton, It made this mistake.
![image](https://user-images.githubusercontent.com/115400289/205798661-06ff231b-c055-4a3a-8eed-849526ecaf28.png)
The above attitude estimation model and target detection model have been trained in mmpose and mmdt.
![image](https://user-images.githubusercontent.com/115400289/205798839-0577a2a7-5cbd-4850-bb6a-4fab80c91f53.png)

**Comment by hsp2454** [comment]
Can anyone answer this question

**Comment by hsp2454** [comment]
mmpose 0.29.0; mmdt 2.25.3; mmaction2 0.24.1

**Comment by HSPDuncan** [comment]
Can anyone answer this question

**Comment by HSPDuncan** [comment]
Can anyone answer this question

**Comment by Dai-Wenxun** [comment]
Could you please debug this code to see what exactly the variable  `det_results` looks like?

**Comment by Better369** [comment]
Hello, I also encountered the same problem, did you solve it?
