### ISSUE TITLE
How to use 2S-AGCN to train and test 2D bones and key points?

### ISSUE THREAD

**Issue by Better369** [open-mmlab/mmaction2#2119]
How to use 2S-AGCN to train and test 2D bones and key points? I didn't find it in the master branch, and the weight and python files of the 1.x branch cm are also 3D.
![34a338ddc9d1903bff4e02ee898538d](https://user-images.githubusercontent.com/109217396/205945345-c360c213-c2af-4d27-b5f5-e6b0aee9b9ad.png)

**Comment by Dai-Wenxun** [comment]
A few days ago, we support testing 2D bones in the dev-1.x branch, but we only give the full configs of STGCN. We will support  AAGCN and give its configs this month. You can refer to this [config](https://github.com/open-mmlab/mmaction2/blob/dev-1.x/configs/skeleton/stgcn/stgcn_8xb16-bone-u100-80e_ntu60-xsub-keypoint-2d.py) first.

**Comment by Better369** [comment]
Ok, thanks, which branch is the updated configuration in? When will it be updated this month? How can I quickly receive the updated information?

**Comment by Dai-Wenxun** [comment]
1. dev-1.x first, then 1.x 
2. The next two weeks, hopefully.
3. I will notify you in this issue. Keep in touch.

**Comment by Dai-Wenxun** [comment]
Hi, @Better369! We now support testing 2D bones using 2s-AGCN, and you can refer to this [config](https://github.com/open-mmlab/mmaction2/blob/dev-1.x/configs/skeleton/2s-agcn/2s-agcn_8xb16-bone-u100-80e_ntu60-xsub-keypoint-2d.py). By the way, the 2D skeleton data of NTU60 can be downloaded from [here](https://download.openmmlab.com/mmaction/v1.0/skeleton/data/ntu60_2d.pkl).

**Comment by Better369** [comment]
Okay, thank you very much, by the way, do you support AAGCN now?

**Comment by Dai-Wenxun** [comment]
Yes, you can set `gcn_attention = True` at this [line](https://github.com/open-mmlab/mmaction2/blob/dev-1.x/configs/skeleton/2s-agcn/2s-agcn_8xb16-joint-u100-80e_ntu60-xsub-keypoint-2d.py#L8).

**Comment by Better369** [comment]
Ok, thank you very much.
