### ISSUE TITLE
RuntimeError: CUDA error: device-side assert triggered

### ISSUE THREAD

**Issue by HSPDuncan** [open-mmlab/mmaction2#2120]
When I run this command, it makes an error
![37c6e48ab19ef3752074eb70c4229da](https://user-images.githubusercontent.com/52354435/206068730-8de1d527-2a54-4e4d-8ff3-27ef840e0d80.png)

**Comment by cir7** [comment]
Hi, @HSPDuncan It seems that the `num_classes` is incorrect, please check it

**Comment by HSPDuncan** [comment]
@cir7 ok,thank you, you are right.
