### ISSUE TITLE
我想请教一下如何使用openpose提取的2D关键点构成的json文件来训练posec3d？

### ISSUE THREAD

**Issue by 15762260991** [open-mmlab/mmaction2#2127]

**Comment by cir7** [comment]
Hi, @15762260991 we provide a [tutorial](https://github.com/open-mmlab/mmaction2/blob/master/tools/data/skeleton/README_zh-CN.md) to prepare skeleton dataset, you can extract keypoint follow the tutorial or convert your json file to our standard format

**Comment by 15762260991** [comment]
@cir7 非常感谢您的回复！但是我没有找到关于将json文件转换成您所提供标准格式的指南，您能详细讲解下吗？

**Comment by cir7** [comment]
@15762260991 We currently dont provide a convert tool. The standard fomat is described [here](https://github.com/open-mmlab/mmaction2/blob/master/tools/data/skeleton/README_zh-CN.md#posec3d-%E7%9A%84%E6%A0%87%E6%B3%A8%E6%96%87%E4%BB%B6%E6%A0%BC%E5%BC%8F), and you can take the provided json file as an example, convert your own json.

**Comment by cir7** [comment]
If you have any further questions, feel free to reopen the issue
