### ISSUE TITLE
replacing np.int and similar aliases

### ISSUE THREAD

**Issue by rlleshi** [open-mmlab/mmaction2#2145]
`numpy.int`, `numpy.float`, and similar aliases are deprecated since numpy 1.20. As of v1.24, they raise an error. 

Was just wondering when is it planned to replace the aliases with the alternatives mentioned in the [release notes 1.20](https://numpy.org/doc/stable/release/1.20.0-notes.html#deprecations)?

**Comment by Dai-Wenxun** [comment]
Thanks! We‘ll consider it.

**Comment by amathews-amd** [comment]
This is not fixed. See https://github.com/open-mmlab/mmaction2/blob/master/mmaction/datasets/pipelines/loading.py for example. 

Please reopen the issue.

**Comment by Dai-Wenxun** [comment]
Sorry, I will fix this issue in the next week.
