### ISSUE TITLE
Error trying code visualize_heatmap_volume

### ISSUE THREAD

**Issue by antonio2600** [open-mmlab/mmaction2#2147]
Hello, I've tryed the code of https://github.com/open-mmlab/mmaction2/blob/master/demo/visualize_heatmap_volume.ipynb and I've got this error:
![Captura desde 2022-12-21 14-11-55](https://user-images.githubusercontent.com/42941507/208913313-dcd82d65-eb8a-42ac-b743-d05059ab61d5.png)

**Comment by cir7** [comment]
Hi, @antonio2600 , I already fix it [here](https://github.com/open-mmlab/mmaction2/blob/fc71c61ad8062f653d5b422a2991bbadc83d92da/demo/visualize_heatmap_volume.ipynb), the main difference is remove  key `bbox` in `result` when call `vis_pose_result()`

**Comment by antonio2600** [comment]
Ok, and is there any code like [this](https://github.com/open-mmlab/mmaction2/blob/fc71c61ad8062f653d5b422a2991bbadc83d92da/demo/visualize_heatmap_volume.ipynb) to try own videos instead of ntu_samples?

**Comment by cir7** [comment]
@antonio2600 , you can try this [demo](https://github.com/open-mmlab/mmaction2/tree/master/demo#skeleton-based-action-recognition-demo), which provides detection, skeleton, and action recognition results for test video. note that the default predict action is based on ntu-120, maybe not correct.

**Comment by antonio2600** [comment]
Ok. If I want to try predict action based in kinetics-600 instead of ntu-120, is it compatible? Because the predict of tha action is not correct and I want to try with another model.

**Comment by cir7** [comment]
@antonio2600, if you have pretrained model on kinetics-600, the demo is compatible.

**Comment by antonio2600** [comment]
I have tryed with kinetics-600 and I have got this error:

![Captura desde 2022-12-29 14-43-34](https://user-images.githubusercontent.com/42941507/209962266-6440d922-0415-4185-ace2-a9c410d03559.png)

**Comment by cir7** [comment]
@antonio2600 , the demo only supports skeleton-based action recognition model, while `TSN` is a action recognition model for RGB input. Please refer to the [doc](https://github.com/open-mmlab/mmaction2/blob/master/demo/README.md#skeleton-based-action-recognition-demo) to learn how to use it.
