### ISSUE TITLE
Skeleton-based model (PoseC3D) for Real-Time Webcam Inference

### ISSUE THREAD

**Issue by juliussin** [open-mmlab/mmaction2#2155]
Hi! I tried to do real-time webcam inference with PoseC3D model. However, using high-level API of mmdetection and mmpose, I had a bottleneck in their inference time. Processing time for each inference is taking too long even with multi-thread and without the PoseC3D model.

After I saw the Webcam API from mmpose, I realized it could achieve the speed I desire. I wonder if I can implement or register the PoseC3D model as a node in that API so it could be run as an independent thread.

Is there any way to:
1. Speed up the detection and pose inferences for every frame (referring to this [skeleton demo](https://github.com/open-mmlab/mmaction2/blob/master/demo/demo_skeleton.py) code) so that I can visualize the pose estimation while stacking the pose inference result for further action recognition (using PoseC3D)
2. Register PoseC3D inference to [Webcam API](https://github.com/open-mmlab/mmpose/tree/master/mmpose/apis) in mmpose as a node so that it could be run there (I tried to manually add the node but it is too complicated and I failed to do so)

Thank you!

**Comment by hukkai** [comment]
We have no plans to optimize inference speed unfortunately.
