### ISSUE TITLE
Skeleton-based Action Recognition Demo

### ISSUE THREAD

**Issue by antonio2600** [open-mmlab/mmaction2#2158]
Hello, I'm testing the demo script to predict the skeleton-based action recognition result using a single video.
I have 2 doubts about this demo.

python demo/demo_skeleton.py demo/ntu_sample.avi demo/skeleton_demo.mp4 \
    --config configs/skeleton/posec3d/slowonly_r50_u48_240e_ntu120_xsub_keypoint.py \
    --checkpoint https://download.openmmlab.com/mmaction/skeleton/posec3d/slowonly_r50_u48_240e_ntu120_xsub_keypoint/slowonly_r50_u48_240e_ntu120_xsub_keypoint-6736b03f.pth \
    --det-config demo/faster_rcnn_r50_fpn_2x_coco.py \
    --det-checkpoint http://download.openmmlab.com/mmdetection/v2.0/faster_rcnn/faster_rcnn_r50_fpn_2x_coco/faster_rcnn_r50_fpn_2x_coco_bbox_mAP-0.384_20200504_210434-a5d8aa15.pth \
    --det-score-thr 0.9 \
    --pose-config demo/hrnet_w32_coco_256x192.py \
    --pose-checkpoint https://download.openmmlab.com/mmpose/top_down/hrnet/hrnet_w32_coco_256x192-c78dce93_20200708.pth \
    --label-map tools/data/skeleton/label_map_ntu120.txt

First, the recognition of the action does not match any of my own videos, I have tried to change the config file and checkpoint but nothing and I don't know what to try now.

The second question I have is that I need to be able to extract information from the resulting video, that is, with the skeleton. I need to get metrics of the time a person is standing or not moving, is there a method that does this?

Thanks.

**Comment by Dai-Wenxun** [comment]
Could you please show me your recognition result? If you use our provided `demo/ntu_sample.avi`, the result should be `hugging other people` as follows: 
![image](https://user-images.githubusercontent.com/58767402/210327462-761f6143-c4d6-4525-a8f1-263edfbd100c.png)

The extracted skeleton is stored in a dict at [here](https://github.com/open-mmlab/mmaction2/blob/master/demo/demo_skeleton.py#L228-L229).

**Comment by antonio2600** [comment]
This is the result of my own video. The result is 'drink water' but the action is 'salute':
![Captura desde 2023-01-03 17-09-59](https://user-images.githubusercontent.com/42941507/210396047-8e4a15da-e2ea-4a0d-ba75-7ca82515faef.png)
And the same with this prediction:
![Captura desde 2023-01-03 17-12-03](https://user-images.githubusercontent.com/42941507/210396372-5acee365-26af-4a62-b578-64b9d82480f2.png)

**Comment by Dai-Wenxun** [comment]
The model you used is trained on NTU120, so it's normal for the model unable to recognize your custom video. Please check this link for more details about the categories the model recognizes. The action `salute` is not included in all 120 classes.

**Comment by Dai-Wenxun** [comment]
https://rose1.ntu.edu.sg/dataset/actionRecognition/

**Comment by antonio2600** [comment]
But in the label_map_ntu120.txt is the action salute, you can see it in the link:

![Captura desde 2023-01-04 21-05-15](https://user-images.githubusercontent.com/42941507/210639991-b849fbab-24f3-40e1-8782-69d390882c57.png)

**Comment by Dai-Wenxun** [comment]
Oh, I see. Perhaps the action `salute` is in the top-5 classes.

**Comment by antonio2600** [comment]
Okay, and is there any value that indicates the position or coordinates of each node of skeleton?
And other thing, I want to have a directory like ntu_samples to see what kind of positions accepts the network so as not to make the mistake of the salute. Is there any directory like that?

**Comment by antonio2600** [comment]
I don't understand how I have to use the information stored in the dict, I have tryed it and I get this:

![Captura desde 2023-01-07 14-40-48](https://user-images.githubusercontent.com/42941507/211153743-8359bbd8-785b-4ed2-ae38-6e1f622e8b20.png)

**Comment by antonio2600** [comment]
That is when I loop through the values ​​of each dictionary key:

![Captura desde 2023-01-08 15-22-39](https://user-images.githubusercontent.com/42941507/211201431-1c8f9091-0f14-483a-8fe6-abacb81b1943.png)
