### ISSUE TITLE
How can I plot the ROC curve or confusion matrix. Do you know how to modify it?

### ISSUE THREAD

**Issue by Jinji97** [open-mmlab/mmaction2#2163]
How can I plot the ROC curve or confusion matrix. Do you know how to modify it?

**Comment by Dai-Wenxun** [comment]
Currently, we only support calculating the mean class acc directly. If you want to draw the ROC curve, you can add your code at [here](https://github.com/open-mmlab/mmaction2/blob/master/mmaction/core/evaluation/accuracy.py#L84).

**Comment by Jinji97** [comment]
By the way, where do you provide the average accuracy of direct category calculation for use?

**Comment by Dai-Wenxun** [comment]
We only use this function when evaluating the acc of our dataset. [link](https://github.com/open-mmlab/mmaction2/blob/master/mmaction/datasets/base.py#L218).
