### ISSUE TITLE
Demo on custom video(.mp4) dataset 

### ISSUE THREAD

**Issue by Dev-ori** [open-mmlab/mmaction2#2171]
Hi, 

Might I've missed this on tutorial. But as i see,
there is only  demo examples for single "video file" 
not for the whole "dataset" which included with multiple videos.

Is there any examples or guide line to perform "Demo on Video Dataset"? 
The Dataset's structure is like below.

Custom_dataset (Directory)
------------------------Class A (Directory)
-----------------------------------A001.mp4 (Files)
-----------------------------------A002.mp4
-----------------------------------A003.mp4
                            --Class B
                            --Class C

thanks.

============================Tutorial I've checked, ============================

Video demo

We provide a demo script to predict the recognition result using **a single video**. In order to get predict results in range [0, 1], make sure to set model['test_cfg'] = dict(average_clips='prob') in config file.

python demo/demo.py ${CONFIG_FILE} ${CHECKPOINT_FILE} $**{VIDEO_FILE}** {LABEL_FILE} [--use-frames] \
    [--device ${DEVICE_TYPE}] [--fps {FPS}] [--font-scale {FONT_SCALE}] [--font-color {FONT_COLOR}] \
    [--target-resolution ${TARGET_RESOLUTION}] [--resize-algorithm {RESIZE_ALGORITHM}] [--out-filename {OUT_FILE}]

===========================================================================
**I want to change this to perform on dataset which included with multiple videos** 

python demo/demo.py ${CONFIG_FILE} ${CHECKPOINT_FILE} $**{VIDEO_Folder}** {LABEL_FILE} [--use-frames] \
    [--device ${DEVICE_TYPE}] [--fps {FPS}] [--font-scale {FONT_SCALE}] [--font-color {FONT_COLOR}] \
    [--target-resolution ${TARGET_RESOLUTION}] [--resize-algorithm {RESIZE_ALGORITHM}] [--out-filename {OUT_FILE}]

**Comment by Dai-Wenxun** [comment]
Sorry, there is no demo for the whole video dataset (maybe you could modify the code in `demo.py` to loop your videos to perform the demo).
