### ISSUE TITLE
Information of demo_skeleton.py

### ISSUE THREAD

**Issue by antonio2600** [open-mmlab/mmaction2#2174]
Hello, I want to know what is the difference between keypoint and keypoint_score.
![image](https://user-images.githubusercontent.com/42941507/211601071-988ae9a2-4bf8-439e-add1-1773c9477959.png)
 
And I want to knwo what represent the values ​​contained in the dictionaries, is it possible that they are the coordinates of the skeleton nodes?
![Captura desde 2023-01-08 15-22-39](https://user-images.githubusercontent.com/42941507/211601589-61f9d58c-3710-4f08-b5b1-d266fff83e0a.png)

Thanks!

**Comment by antonio2600** [comment]
Okay, thanks!

**Comment by antonio2600** [comment]
When I test it with my own videos, there are times when I access the coordinates of the nodes, appear arrays with 0, as if the position of the nodes was not detected. Why is this happening?

![Captura desde 2023-01-11 18-06-36](https://user-images.githubusercontent.com/42941507/211870600-3a584939-0704-4fa2-bbd5-eb9a307d63cd.png)

**Comment by antonio2600** [comment]
I have another question.
If the video is 100 frames, presumably, why are 200 matrices saved in keypoint?

**Comment by Dai-Wenxun** [comment]
> I have another question. If the video is 100 frames, presumably, why are 200 matrices saved in keypoint?

The first dimension is the number of [persons](https://github.com/open-mmlab/mmaction2/blob/master/demo/demo_skeleton.py#L216). Maybe two persons were detected in your video.

**Comment by Dai-Wenxun** [comment]
> When I test it with my own videos, there are times when I access the coordinates of the nodes, appear arrays with 0, as if the position of the nodes was not detected. Why is this happening?
> 
> ![Captura desde 2023-01-11 18-06-36](https://user-images.githubusercontent.com/42941507/211870600-3a584939-0704-4fa2-bbd5-eb9a307d63cd.png)

I suggest you'd better check the visualization result first.
