### ISSUE TITLE
RuntimeError: unable to open shared memory object </torch_16550_876314950> in read-write mode

### ISSUE THREAD

**Issue by simobupt** [open-mmlab/mmaction2#218]
When I use dist_train.sh, I meet this question.

`RuntimeError: unable to open shared memory object </torch_16550_876314950> in read-write mode`

Could anyone help me? Thanks.

**Comment by SuX97** [comment]
That's most likely because of wrong syntax in config file. Please scroll up the error log and check the syntax of your config file.

**Comment by simobupt** [comment]
> That's most likely because of wrong syntax in config file. Please scroll up the error log and check the syntax of your config file.

I check my config file. However I find when I train a lager data, it will raise this error. If a small data here, it will be ok.

**Comment by SuX97** [comment]
> I check my config file. However I find when I train a lager data, it will raise this error. If a small data here, it will be ok.

Please check this issue, https://github.com/facebookresearch/maskrcnn-benchmark/issues/103, in which it suggests a memory deadlock because of multi-thread, try to set num_workers=0 in your config?

**Comment by simobupt** [comment]
> > I check my config file. However I find when I train a lager data, it will raise this error. If a small data here, it will be ok.
> 
> Please check this issue, [facebookresearch/maskrcnn-benchmark#103](https://github.com/facebookresearch/maskrcnn-benchmark/issues/103), in which it suggests a memory deadlock because of multi-thread, try to set num_workers=0 in your config?

Yeah, I have set num_workers=0 and it workes, but the speed is too slow. Maybe the large dataset is not match this.

**Comment by dreamerlin** [comment]
Yeah, It seems more likely related with your hardware environment to support heavy dataset burden.

> > > I check my config file. However I find when I train a lager data, it will raise this error. If a small data here, it will be ok.
> > 
> > 
> > Please check this issue, [facebookresearch/maskrcnn-benchmark#103](https://github.com/facebookresearch/maskrcnn-benchmark/issues/103), in which it suggests a memory deadlock because of multi-thread, try to set num_workers=0 in your config?
> 
> Yeah, I have set num_workers=0 and it workes, but the speed is too slow. Maybe the large dataset is not match this.

**Comment by innerlee** [comment]
use `df -h` to see the space of `/dev/shm`, if it is small, say 8GB, then you may need to make it larger or try to use hard disk as the buffer.
