### ISSUE TITLE
RuntimeError: Input and output sizes should be greater than 0, but got input (D: 4, H: 256, W: 256) output (D: 0, H: 256, W: 256)

### ISSUE THREAD

**Issue by Dev-ori** [open-mmlab/mmaction2#2185]
Hi, 

Now, I'm trying to get a feature from "Slowfast" model 
But, Since there is no "Config" file for the "clip_feature_extraction.py" in the existing /configs/recognition/slowfast /, I made it by myself. 

When I ran the code with following scripts, there comes an error according "Input/Ouput Size" 

Would you guess or give me some guide lines to get over from this?

**Scripts I used.** 
> python /home/hello/PycharmProjects/mmaction/mmaction2/tools/misc/clip_feature_extraction.py \
configs/recognition/slowfast/slowfast_r50_clip_feature_extraction_8x8x1_rgb.py \
https://download.openmmlab.com/mmaction/recognition/slowfast/slowfast_r50_8x8x1_256e_kinetics400_rgb/slowfast_r50_8x8x1_256e_kinetics400_rgb_20200716-73547d2b.pth  \
--video-list /home/hello/PycharmProjects/mmaction/mmaction2/UCF-Crime/new_video_paths.txt \
--video-root /mnt/ped_db/UCF_Crime/ \
--out ucf-crime_feature.pkl

**Appeared Error:**
>RuntimeError: Input and output sizes should be greater than 0, but got input (D: 4, H: 256, W: 256) output (D: 0, H: 256, W: 256)

**Traceback error:**
>load checkpoint from http path: https://download.openmmlab.com/mmaction/recognition/slowfast/slowfast_r50_8x8x1_256e_kinetics400_rgb/slowfast_r50_8x8x1_256e_kinetics400_rgb_20200716-73547d2b.pth
Downloading: "https://download.openmmlab.com/mmaction/recognition/slowfast/slowfast_r50_8x8x1_256e_kinetics400_rgb/slowfast_r50_8x8x1_256e_kinetics400_rgb_20200716-73547d2b.pth" to /home/dhan/.cache/torch/hub/checkpoints/slowfast_r50_8x8x1_256e_kinetics400_rgb_20200716-73547d2b.pth
100%|

> >The model and loaded state dict do not match exactly
> 
> size mismatch for backbone.slow_path.conv1_lateral.conv.weight: copying a param with shape torch.Size([16, 8, 7, 1, 1]) from checkpoint, the shape in current model is torch.Size([16, 8, 5, 1, 1]).
> size mismatch for backbone.slow_path.layer1_lateral.conv.weight: copying a param with shape torch.Size([64, 32, 7, 1, 1]) from checkpoint, the shape in current model is torch.Size([64, 32, 5, 1, 1]).
> size mismatch for backbone.slow_path.layer2_lateral.conv.weight: copying a param with shape torch.Size([128, 64, 7, 1, 1]) from checkpoint, the shape in current model is torch.Size([128, 64, 5, 1, 1]).
> size mismatch for backbone.slow_path.layer3_lateral.conv.weight: copying a param with shape torch.Size([256, 128, 7, 1, 1]) from checkpoint, the shape in current model is torch.Size([256, 128, 5, 1, 1]).
> unexpected key in source state_dict: cls_head.fc_cls.weight, cls_head.fc_cls.bias
> 
> [                                                  ] 0/1950, elapsed: 0s, ETA:Traceback (most recent call last):
>   File "/home/helloarmProjects/mmaction/mmaction2/tools/misc/clip_feature_extraction.py", line 254, in <module>
>     main()
>   File "/home/helloarmProjects/mmaction/mmaction2/tools/misc/clip_feature_extraction.py", line 223, in main
>     outputs = inference_pytorch(args, cfg, distributed, data_loader)
>   File "/home/helloarmProjects/mmaction/mmaction2/tools/misc/clip_feature_extraction.py", line 119, in inference_pytorch
>     outputs = single_gpu_test(model, data_loader)
>   File "/mnt/hoky/anaconda3/envs/Slowfast/lib/python3.10/site-packages/mmcv/engine/test.py", line 36, in single_gpu_test
>     result = model(return_loss=False, **data)
>   File "/mnt/hoky/anaconda3/envs/Slowfast/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
>     return forward_call(*input, **kwargs)
>   File "/mnt/hoky/anaconda3/envs/Slowfast/lib/python3.10/site-packages/mmcv/parallel/data_parallel.py", line 51, in forward
>     return super().forward(*inputs, **kwargs)
>   File "/mnt/hoky/anaconda3/envs/Slowfast/lib/python3.10/site-packages/torch/nn/parallel/data_parallel.py", line 166, in forward
>     return self.module(*inputs[0], **kwargs[0])
>   File "/mnt/hoky/anaconda3/envs/Slowfast/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
>     return forward_call(*input, **kwargs)
>   File "/home/hello/PycharmProjects/mmaction/mmaction2/mmaction/models/recognizers/base.py", line 271, in forward
>     return self.forward_test(imgs, **kwargs)
>   File "/home/hello/PycharmProjects/mmaction/mmaction2/mmaction/models/recognizers/recognizer3d.py", line 99, in forward_test
>     return self._do_test(imgs).cpu().numpy()
>   File "/home/hello/PycharmProjects/mmaction/mmaction2/mmaction/models/recognizers/recognizer3d.py", line 63, in _do_test
>     feat = self.extract_feat(imgs)
>   File "/mnt/hoky/anaconda3/envs/Slowfast/lib/python3.10/site-packages/mmcv/runner/fp16_utils.py", line 119, in new_func
>     return old_func(*args, **kwargs)
>   File "/home/hello/PycharmProjects/mmaction/mmaction2/mmaction/models/recognizers/base.py", line 170, in extract_feat
>     x = self.backbone(imgs)
>   File "/mnt/hoky/anaconda3/envs/Slowfast/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
>     return forward_call(*input, **kwargs)
>   File "/home/hello/PycharmProjects/mmaction/mmaction2/mmaction/models/backbones/resnet3d_slowfast.py", line 493, in forward
>     x_slow = nn.functional.interpolate(
>   File "/mnt/hoky/anaconda3/envs/Slowfast/lib/python3.10/site-packages/torch/nn/functional.py", line 3912, in interpolate
>     return torch._C._nn.upsample_nearest3d(input, output_size, scale_factors)
> 	
> RuntimeError: Input and output sizes should be greater than 0, but got input (D: 4, H: 256, W: 256) output (D: 0, H: 256, W: 256)
> 
> 

**Config file that I've modified** 

> model = dict(
>     type='Recognizer3D',
>     backbone=dict(
>         type='ResNet3dSlowFast',
>         pretrained=None,
>         resample_rate=8,  # tau
>         speed_ratio=8,  # alpha
>         channel_ratio=8,  # beta_inv
>         slow_pathway=dict(
>             type='resnet3d',
>             depth=50,
>             pretrained=None,
>             lateral=True,
>             conv1_kernel=(1, 7, 7),
>             dilations=(1, 1, 1, 1),
>             conv1_stride_t=1,
>             pool1_stride_t=1,
>             inflate=(0, 0, 1, 1),
>             norm_eval=False),
>         fast_pathway=dict(
>             type='resnet3d',
>             depth=50,
>             pretrained=None,
>             lateral=False,
>             base_channels=8,
>             conv1_kernel=(5, 7, 7),
>             conv1_stride_t=1,
>             pool1_stride_t=1,
>             norm_eval=False)),
>     train_cfg=None,
>     test_cfg=dict(feature_extraction=True))
> 
> # dataset settings
> dataset_type = 'VideoDataset'
> img_norm_cfg = dict(
>     mean=[123.675, 116.28, 103.53], std=[58.395, 57.12, 57.375], to_bgr=False)
> test_pipeline = [
>     dict(type='DecordInit'),
>     dict(
>         type='SampleFrames',
>         clip_len=4,
>         frame_interval=16,
>         num_clips=10,
>         test_mode=True),
>     dict(type='DecordDecode'),
>     dict(type='Resize', scale=(-1, 256)),
>     dict(type='CenterCrop', crop_size=256),
>     dict(type='Normalize', **img_norm_cfg),
>     dict(type='FormatShape', input_format='NCTHW'),
>     dict(type='Collect', keys=['imgs'], meta_keys=[]),
>     dict(type='ToTensor', keys=['imgs'])
> ]
> data = dict(
>     videos_per_gpu=1,
>     workers_per_gpu=2,
>     test=dict(
>         type=dataset_type,
>         ann_file=None,
>         data_prefix=None,
>         pipeline=test_pipeline))
> 
> dist_params = dict(backend='nccl')
> 
>

**Comment by fjptscottliu** [comment]
更改什么参数呢?
