### ISSUE TITLE
How to generate ".pkl" file by using "ntu_pose_extraction.py" script?

### ISSUE THREAD

**Issue by SileiZhao** [open-mmlab/mmaction2#2187]
Dear all, I had a problem training my data set using mmaction2's posec3d model, how to use ntu_pose_extraction.py script to extract video skeleton information? How do I label each video? Must the video name be in the form of "A0001.mp4"? How to label a video with multiple people?
Script is here.
[https://github.com/open-mmlab/mmaction2/blob/master/tools/data/skeleton/ntu_pose_extraction.py](url)
I can not understand this function, I will be appreciated if someone who can give me hint about this.
<img width="613" alt="image" src="https://user-images.githubusercontent.com/72799040/212953618-97021223-e972-41ba-8488-7332252ed26c.png">

**Comment by SileiZhao** [comment]
Why are the "img_shape" and "original_shape" values in this function fixed? Do I need to change them to the size of my actual image? Another question is does the "label" of the video come from the name of the video? How should I name each video?

**Comment by SileiZhao** [comment]
Does having only one label per video mean there can only be one person's skeletal information per video? How do you determine the label of a video when there are more than one person?

**Comment by Dai-Wenxun** [comment]
Sorry for not getting back to you sooner! The label is obtained from the file name of the video. Under the current setting, we only perform classification on the video level. A multi-person example in NTU60 is as follows:
![image](https://user-images.githubusercontent.com/58767402/218055691-eb64a455-3e58-42f1-8fdd-2b541f3e46d8.png)

**Comment by Dai-Wenxun** [comment]
The "img_shape" and "original_shape" are the original resolution of the video.
