### ISSUE TITLE
ImportError: Failed to import `inference_detector` and `init_detector` from `mmdet.apis`. These apis are required in this inference api!

### ISSUE THREAD

**Issue by Better369** [open-mmlab/mmaction2#2194]
I downloaded the dev-1.x version of mmaction2 and the 3.x version of mmdetection, and ran demo_skeleton.py and reported Failed to import `inference_detector` and `init_detector` from `mmdet.apis`. These apis are required in this inference api!
![25 D0LF6_DNBY$W581AGO}5](https://user-images.githubusercontent.com/109217396/214548627-efb9aeb3-eac6-4ae1-8062-a862ae6bcdfb.png)

environment：
mmcv: 2.0.0rc3   (the dev-1.x version of mmaction2 requires mmcv version 2.0 or above. )
mmdet: 3.0.0rc3 
cuda：11.3
torch：1.10.1
![W 53TK@9GWSALL5747(28ZB](https://user-images.githubusercontent.com/109217396/214548891-32b7f2d1-4156-4d6a-928f-a8f1a9009a41.png)

**Comment by mzhadigerov** [comment]
were you be able to solve this?
