### ISSUE TITLE
What is the batcch_size in I3D and TimeSformer

### ISSUE THREAD

**Issue by suzana-rita** [open-mmlab/mmaction2#2199]
Hi guys,

Can you tell me what is the batch_size used on the fine-tuning of I3D and TimeSformer? 
If not, can you tell me where to find this information?
The batch sizes of both models might still be default since I did not change it.

**Comment by cir7** [comment]
Hi, @suzana-rita , in the master branch, we specify batch_size with `data.videos_per_gpu` in config file, the total batch size is `num_gpus * data.videos_per_gpu`, and we provide the gpu num of our experiment in the readme of model config directory

**Comment by suzana-rita** [comment]
I understand, thanks for the answer.
Another question, does anything change on the feature extraction when I use the `test_dataloader=dict(videos_per_gpu=1)` ?
For example, in this code, I use `videos_per_gpu=10` for the training, but in the test I use `videos_per_gpu=1`.
```
data = dict(
    videos_per_gpu=10,
    workers_per_gpu=5,
    test_dataloader=dict(videos_per_gpu=1),
...
)
```

**Comment by cir7** [comment]
@suzana-rita , it doesn't matter to modify batchsize in inference stage

**Comment by suzana-rita** [comment]
ok, I just got confused by the dataloader line.

Thank you very much for your answers!
