### ISSUE TITLE
ImportError: cannot import name 'Dict' from partially initialized module 'typing' (most likely due to a circular import)

### ISSUE THREAD

**Issue by leexinhao** [open-mmlab/mmaction2#2201]
Thanks for your error report and we appreciate it a lot.
If you feel we have help you, give us a STAR! :satisfied:

**Checklist**

1. I have searched related issues but cannot get the expected help.
2. The bug has not been fixed in the latest version.

**Describe the bug**

In the `mmaction/utils/typing.py` of mmaction2 1.x, the code is:
```python
# Copyright (c) OpenMMLab. All rights reserved.
"""Collecting some commonly used type hint in mmaction."""
from typing import Dict, List, Optional, Tuple, Union
....
```

The file name `typing.py` is the same as the referenced library name `typing`，so we will encounter the circular umport error.

![image](https://user-images.githubusercontent.com/48858574/216775191-13c1ff39-61f0-455f-9738-76f733cfbc11.png)

**Reproduction**

1. What command or script did you run?

```
PYTHONPATH=${PWD}:$PYTHONPATH python mmaction/utils/collect_env.py
```

2. Did you make any modifications on the code or config? Did you understand what you have modified?

Not at all.
4. What dataset did you use?

**Environment**

1. Please run `PYTHONPATH=${PWD}:$PYTHONPATH python mmaction/utils/collect_env.py` to collect necessary environment information and paste it here.
2. You may add addition that may be helpful for locating the problem, such as
   - How you installed PyTorch \[e.g., pip, conda, source\]
   - Other environment variables that may be related (such as `$PATH`, `$LD_LIBRARY_PATH`, `$PYTHONPATH`, etc.)
```
sys.platform: linux
Python: 3.8.0 (default, Nov  6 2019, 21:49:08) [GCC 7.3.0]
CUDA available: False
numpy_random_seed: 2147483648
GCC: gcc (GCC) 5.4.0
PyTorch: 1.8.1+cu101
PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2020.0.0 Product Build 20191122 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v1.7.0 (Git Hash 7aed236906b1f7a05c0917e5257a1af05e9ff683)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=10.1, CUDNN_VERSION=7.6.3, CXX_COMPILER=/opt/rh/devtoolset-7/root/usr/bin/c++, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.8.1, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, 

TorchVision: 0.9.1+cu101
OpenCV: 4.7.0
MMEngine: 0.5.0
MMAction2: 1.0.0rc2+8f96223
```

**Error traceback**

If applicable, paste the error traceback here.

```
A placeholder for traceback.
```

**Bug fix**

Just rename the `mmaction/utils/typing.py` to `mmaction/utils/my_typing.py`.

**Comment by ly015** [comment]
Hi, thanks for using MMAction2. We can not reproduce this issue. Usually, in MMEnghine it will import the typing lib instead of the typing module in MMAction2. Could you please provide detailed information as follows:

```
$ echo $PYTHONPATH
$ echo $PATH
$ python -c "import typing; print(typing)"
```

**Comment by leexinhao** [comment]
> Hi, thanks for using MMAction2. We can not reproduce this error. Usually, in MMEnghine it will import the typing lib instead of the typing module in MMAction2. Could you please provide detailed information as follows:
> 
> ```
> $ echo $PYTHONPATH
> $ echo $PATH
> $ python -c "import typing; print(typing)"
> ```

No problem.
```
(lxh_next) [lixinhao@SH-IDC1-10-142-4-30 mmaction2-lxh]$ echo $PYTHONPATH
:/mnt/cache/lixinhao/bestmoment:/mnt/lustre/lixinhao/awscli:/mnt/cache/lixinhao/bestmoment:/mnt/lustre/lixinhao/awscli
(lxh_next) [lixinhao@SH-IDC1-10-142-4-30 mmaction2-lxh]$ echo $PATH
/mnt/cache/lixinhao/q/envs/lxh_next/bin:/mnt/cache/lixinhao/q/envs/lxh_torch/bin:/mnt/cache/lixinhao/git/bin:/mnt/lustre/share/ffmpeg-4.2.1/bin:/mnt/lustre/share/platform/env:/mnt/cache/lixinhao/bin:/mnt/lustre/share/cuda-10.1/bin:/mnt/lustre/share/gcc/gcc-5.4/bin:/mnt/cache/lixinhao/q/bin:/mnt/cache/lixinhao/.vscode-server/bin/e2816fe719a4026ffa1ee0189dc89bdfdbafb164/bin/remote-cli:/mnt/cache/lixinhao/git/bin:/mnt/lustre/share/ffmpeg-4.2.1/bin:/mnt/lustre/share/platform/env:/mnt/cache/lixinhao/bin:/mnt/lustre/share/cuda-10.1/bin:/mnt/lustre/share/gcc/gcc-5.4/bin:/mnt/cache/lixinhao/q/bin:/mnt/cache/share/spring/:/mnt/lustre/share/platform:/usr/local/cuda/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/mnt/lustre/lixinhao/bin
(lxh_next) [lixinhao@SH-IDC1-10-142-4-30 mmaction2-lxh]$ python -c "import typing; print(typing)"
<module 'typing' from '/mnt/cache/lixinhao/q/envs/lxh_next/lib/python3.8/typing.py'>
```
And I create a new file named `typing.py`：
```python
from typing import Dict, List
print('anything!')
```
Run it could get the same error:
![image](https://user-images.githubusercontent.com/48858574/217137441-1699649b-d733-4e49-ba0d-f4b95c71f16d.png)

The version of my Python is **3.8.0**，I can reproduce it in 3.9.12 with linux:
![image](https://user-images.githubusercontent.com/48858574/217138407-5f079fe1-cd1a-44c7-be1c-08206e71c7a1.png)
 **but not in windows with same version of python:**
![image](https://user-images.githubusercontent.com/48858574/217138685-63385ba0-0fa3-4932-98c6-05c985ea2de9.png)

So I think it depends on the development environment, renaming may be a safer bet
