### ISSUE TITLE
AssertionError: Invalid arguments: {'pretrained': None}

### ISSUE THREAD

**Issue by Better369** [open-mmlab/mmaction2#2202]
**Environment**
mmaction2:     1.0.0rc2
mmcv:     2.0.0rc4
mmdet:    3.0.0rc5
mmengine:    0.5.0
mmpose:    1.0.0rc0
cuda:    11.0
torch:   1.8.0

**Error**
I ran demo_skeleton.py and changed the content as follows:
config： stgcn_8xb16-joint-u100-80e_ntu60-xsub-keypoint-2d.py
checkpoint： stgcn_8xb16-joint-u100-80e_ntu60-xsub-keypoint-2d_20221129-484a394a.pth
det-config： faster-rcnn_r50_fpn_2x_coco_infer.py
det-checkpoint： faster_rcnn_r50_fpn_2x_coco_bbox_mAP-0.384_20200504_210434-a5d8aa15.pth
pose-config： td-hm_hrnet-w32_8xb64-210e_coco-256x192_infer.py
pose-checkpoint： hrnet_w32_coco_256x192-c78dce93_20200708.pth

But when I run it, I get an error like this: 
![a6cc16c4b99f3aa56f8096e2ff9467a](https://user-images.githubusercontent.com/109217396/217131875-17d8c5e1-060f-4884-a1a3-ad597d3e0c8e.png)
![9b00da6cdfb3874500ac9de18afcbfa](https://user-images.githubusercontent.com/109217396/217131935-7e08a3aa-9af0-4222-9411-a9352d41024b.png)

The following is where the first error message is displayed:
![9bd86f9e8b13cb8c1d465c40639c6b3](https://user-images.githubusercontent.com/109217396/217132232-1844e822-b3dd-497a-bb71-9d7c11fe3e85.png)

If you know how to solve it, please answer me a bit, thank you very much.

**Comment by Better369** [comment]
@Dai-Wenxun Can you answer the question? Thank you so much

**Comment by Dai-Wenxun** [comment]
I'm sorry for not getting back to you sooner. Could you please show me the full config?

**Comment by Better369** [comment]
def parse_args():
    parser = argparse.ArgumentParser(description='MMAction2 demo')
    parser.add_argument('--video', default=("D:\Engineer\mmaction2-1.x\mmaction2-1.x\data\guge\S083C001P001R001A002.avi"), help='video file/url')
    parser.add_argument('--out_filename', default=("D:\Engineer\mmaction2-1.x\mmaction2-1.x\data\demoout\\123456.avi"), help='output filename')
    parser.add_argument(
        '--config',
        #default=('configs/skeleton/posec3d/'
        #         'slowonly_r50_8xb16-u48-240e_ntu60-xsub-keypoint.py'),

        default=('D:\Engineer\mmaction2-1.x\mmaction2-1.x\configs\skeleton\stgcn\stgcn_8xb16-joint-u100-80e_ntu60-xsub-keypoint-2d.py'),
        help='skeleton model config file path')
    parser.add_argument(
        '--checkpoint',
        #default=('https://download.openmmlab.com/mmaction/skeleton/posec3d/'
        #         'slowonly_r50_u48_240e_ntu60_xsub_keypoint/'
        #         'slowonly_r50_u48_240e_ntu60_xsub_keypoint-f3adabf1.pth'),
        #default=('D:\Engineer\mmaction2-1.x\mmaction2-1.x\data\\xunlian\\epoch_50.pth'),
        default=('D:\Engineer\mmaction2-1.x\mmaction2-1.x\weight\stgcn_8xb16-joint-u100-80e_ntu60-xsub-keypoint-2d_20221129-484a394a.pth'),
        help='skeleton model checkpoint file/url')
    parser.add_argument(
        '--det-config',
        #default='demo/demo_configs/faster-rcnn_r50_fpn_2x_coco_infer.py',
        default='D:/Engineer/mmaction2-1.x/mmaction2-1.x/demo/demo_configs/faster-rcnn_r50_fpn_2x_coco_infer.py',
        help='human detection config file path (from mmdet)')
    parser.add_argument(
        '--det-checkpoint',
        #default=('http://download.openmmlab.com/mmdetection/v2.0/faster_rcnn/'
        #         'faster_rcnn_r50_fpn_2x_coco/'
        #         'faster_rcnn_r50_fpn_2x_coco_'
        #         'bbox_mAP-0.384_20200504_210434-a5d8aa15.pth'),
        default=('D:\\Engineer\\mmaction2-1.x\\mmaction2-1.x\\weight\\faster_rcnn_r50_fpn_2x_coco_bbox_mAP-0.384_20200504_210434-a5d8aa15.pth'),
        help='human detection checkpoint file/url')
    parser.add_argument(
        '--det-score-thr',
        type=float,
        default=0.9,
        help='the threshold of human detection score')
    parser.add_argument(
        '--det-cat-id',
        type=int,
        default=0,
        help='the category id for human detection')
    parser.add_argument(
        '--pose-config',
        #default='demo/demo_configs/'
        #'td-hm_hrnet-w32_8xb64-210e_coco-256x192_infer.py',
        #default='D:/Engineer/mmaction2-dev/mmaction2-dev/demo/hrnet_w32_coco_256x192.py',
        default='D:/Engineer/mmaction2-1.x/mmaction2-1.x/demo/demo_configs/td-hm_hrnet-w32_8xb64-210e_coco-256x192_infer.py',

        help='human pose estimation config file path (from mmpose)')
    parser.add_argument(
        '--pose-checkpoint',
        #default=('https://download.openmmlab.com/mmpose/top_down/hrnet/'
        #         'hrnet_w32_coco_256x192-c78dce93_20200708.pth'),
        default=('D:\\Engineer\\mmaction2-1.x\\mmaction2-1.x\\weight\\hrnet_w32_coco_256x192-c78dce93_20200708.pth'),
        help='human pose estimation checkpoint file/url')
    parser.add_argument(
        '--label-map',
        default='tools/data/skeleton/label_map_ntu60.txt',
        help='label map file')
    parser.add_argument(
        '--device', type=str, default='cuda:0', help='CPU/CUDA device option')
    parser.add_argument(
        '--short-side',
        type=int,
        default=480,
        help='specify the short-side length of the image')
    parser.add_argument(
        '--cfg-options',
        nargs='+',
        action=DictAction,
        default={},
        help='override some settings in the used config, the key-value pair '
        'in xxx=yyy format will be merged into config file. For example, '
        "'--cfg-options model.backbone.depth=18 model.backbone.with_cp=True'")
    args = parser.parse_args()
    return args

**Comment by Better369** [comment]
![SMTZEI3MD}~G~U$5${Z%F1F](https://user-images.githubusercontent.com/109217396/217828805-f1ea17f2-5b42-427c-bd21-d839d439f982.png)
![71VHEOH}%I3C{3BHW _LE9Q](https://user-images.githubusercontent.com/109217396/217828847-d17b2f5b-d784-45bd-a82e-a6546c120284.png)
![V7ODHHP`FIA2SUA2PHU`}_9](https://user-images.githubusercontent.com/109217396/217828881-7983aa29-9d1d-4418-921e-6f63e7d6d2b5.png)

**Comment by Better369** [comment]
@Dai-Wenxun  Is this okay? Thank you very much for your answer.

**Comment by Better369** [comment]
https://github.com/open-mmlab/mmaction2/blob/1.x/configs/skeleton/stgcn/stgcn_8xb16-joint-u100-80e_ntu60-xsub-keypoint-2d.py


I remember that I did not modify the content inside, the above link is where I downloaded it, please take a look, tomorrow I will confirm whether there are any modifications.

**Comment by Better369** [comment]
@Dai-Wenxun I didn't modify the code, please take a look. Thank you so much.

_base_ = '../../_base_/default_runtime.py'

model = dict(
    type='RecognizerGCN',
    backbone=dict(
        type='STGCN', graph_cfg=dict(layout='coco', mode='stgcn_spatial')),
    cls_head=dict(type='GCNHead', num_classes=60, in_channels=256))

dataset_type = 'PoseDataset'
ann_file = 'data/skeleton/ntu60_2d.pkl'
train_pipeline = [
    dict(type='PreNormalize2D'),
    dict(type='GenSkeFeat', dataset='coco', feats=['j']),
    dict(type='UniformSampleFrames', clip_len=100),
    dict(type='PoseDecode'),
    dict(type='FormatGCNInput', num_person=2),
    dict(type='PackActionInputs')
]
val_pipeline = [
    dict(type='PreNormalize2D'),
    dict(type='GenSkeFeat', dataset='coco', feats=['j']),
    dict(
        type='UniformSampleFrames', clip_len=100, num_clips=1, test_mode=True),
    dict(type='PoseDecode'),
    dict(type='FormatGCNInput', num_person=2),
    dict(type='PackActionInputs')
]
test_pipeline = [
    dict(type='PreNormalize2D'),
    dict(type='GenSkeFeat', dataset='coco', feats=['j']),
    dict(
        type='UniformSampleFrames', clip_len=100, num_clips=10,
        test_mode=True),
    dict(type='PoseDecode'),
    dict(type='FormatGCNInput', num_person=2),
    dict(type='PackActionInputs')
]

train_dataloader = dict(
    batch_size=16,
    num_workers=2,
    persistent_workers=True,
    sampler=dict(type='DefaultSampler', shuffle=True),
    dataset=dict(
        type='RepeatDataset',
        times=5,
        dataset=dict(
            type=dataset_type,
            ann_file=ann_file,
            pipeline=train_pipeline,
            split='xsub_train')))
val_dataloader = dict(
    batch_size=16,
    num_workers=2,
    persistent_workers=True,
    sampler=dict(type='DefaultSampler', shuffle=False),
    dataset=dict(
        type=dataset_type,
        ann_file=ann_file,
        pipeline=val_pipeline,
        split='xsub_val',
        test_mode=True))
test_dataloader = dict(
    batch_size=1,
    num_workers=2,
    persistent_workers=True,
    sampler=dict(type='DefaultSampler', shuffle=False),
    dataset=dict(
        type=dataset_type,
        ann_file=ann_file,
        pipeline=test_pipeline,
        split='xsub_val',
        test_mode=True))

val_evaluator = [dict(type='AccMetric')]
test_evaluator = val_evaluator

train_cfg = dict(
    type='EpochBasedTrainLoop', max_epochs=16, val_begin=1, val_interval=1)
val_cfg = dict(type='ValLoop')
test_cfg = dict(type='TestLoop')

param_scheduler = [
    dict(
        type='CosineAnnealingLR',
        eta_min=0,
        T_max=16,
        by_epoch=True,
        convert_to_iter_based=True)
]

optim_wrapper = dict(
    optimizer=dict(
        type='SGD', lr=0.1, momentum=0.9, weight_decay=0.0005, nesterov=True))

default_hooks = dict(checkpoint=dict(interval=1), logger=dict(interval=100))

# Default setting for scaling LR automatically
#   - `enable` means enable scaling LR automatically
#       or not by default.
#   - `base_batch_size` = (8 GPUs) x (16 samples per GPU).
auto_scale_lr = dict(enable=False, base_batch_size=128)

**Comment by Better369** [comment]
@Dai-Wenxun   I didn't modify the code, please take a look. Thank you so much.

**Comment by Dai-Wenxun** [comment]
I'm working on it, perhaps there is a bug in the demo scripts.

**Comment by Better369** [comment]
Ok, thank you very much, look forward to your reply.

**Comment by Dai-Wenxun** [comment]
delete this line. https://github.com/open-mmlab/mmaction2/blob/1.x/mmaction/apis/inference.py#L39

**Comment by Dai-Wenxun** [comment]
We will fix this bug in version 1.0.0rc3 https://github.com/open-mmlab/mmaction2/pull/2214.

**Comment by Better369** [comment]
Thank you very much for your help, but I get a new error message:

![G1(NU2%QQAD )MJ08MY6S4R](https://user-images.githubusercontent.com/109217396/218058385-b39c42a2-72a4-49b0-b808-076932a37b76.png)

**Comment by Dai-Wenxun** [comment]
I have seen your deleted comment. Someone proposed this issue before. https://github.com/open-mmlab/mmaction2/issues/2145. I will fix this issue in the next week.

**Comment by Better369** [comment]
Thank you, thanks for your reply.
