### ISSUE TITLE
How to apply transforms to individual samples?

### ISSUE THREAD

**Issue by nngg11** [open-mmlab/mmaction2#2203]
While on the test script (https://github.com/open-mmlab/mmaction2/blob/master/tools/test.py) transforms from the configuration file are implemented and applied internally to the dataset,I would like to ask if there is a defined workaround to apply the transforms defined in the configuration file to a single sample just like how transforms to data loaders/datasets are applied.

----------------------------------

**Checklist**

1. I have searched related issues but cannot get the expected help.
2. I have read the [FAQ documentation](https://mmaction2.readthedocs.io/en/latest/faq.html) but cannot get the expected help.

**Comment by Dai-Wenxun** [comment]
Do you mean you only need the pipeline to transform your data sample?

**Comment by nngg11** [comment]
> Do you mean you only need the pipeline to transform your data sample?
> 
> 

Yes, exactly! Thank you.

**Comment by Dai-Wenxun** [comment]
The pipelines in MMAciton2 are composed in [Compose](https://github.com/open-mmlab/mmaction2/blob/54bc294bff7f742777f5cbb195705c1040a72ebe/mmaction/datasets/pipelines/compose.py#L11).

```python

from mmaction.datasets.pipelines import Compose
config = mmcv.Config.from_file('/path/to/the/config')
transforms = Compose(config.test_pipieline)
video_results = dict(
    filename='x.mp4',
    label=1,
    total_frames=300,
    start_index=0)
results = transforms(video_results)
```
You can debug to see the process of transforms.

**Comment by nngg11** [comment]
Absolutely perfect, thank you very much for your fast response! Closing the issue.
