### ISSUE TITLE
Question about the action detection with mmaction

### ISSUE THREAD

**Issue by antonio2600** [open-mmlab/mmaction2#2204]
Hello, I have a question about the action detection.
If the video that I'm procesing has 100 frames for example, I want to know in which frame the action is detected for first time. 
That is, with an action detection model, you insert a video and then you know the top 5 actions that have the highest percentage, what I want is to be able to take the time that the person is doing that action in the video and I have thought of taking the first frame in which the action begins to be detected to be able to take the time it takes. 
Any help or advice about I want to do?
Thanks!

**Comment by Dai-Wenxun** [comment]
The task of action detection must be done in a 3D manner, i.e., classify the action from multiple consecutive frames, so we can't classify the action from a single frame.

**Comment by antonio2600** [comment]
Ok, thanks.
