### ISSUE TITLE
Variable frame interval

### ISSUE THREAD

**Issue by soltkreig** [open-mmlab/mmaction2#2208]
Hi.
Usual config looks like:
```
dict(
        type='SampleFrames',
        clip_len=64,
        frame_interval=1,
        num_clips=1,
        test_mode=True),
```
I'd like to implement frame_interval could randomly change 1-3 for every video.
How I could implement variable frame interval?

**Comment by Dai-Wenxun** [comment]
https://github.com/open-mmlab/mmaction2/blob/master/mmaction/datasets/pipelines/loading.py#L232-L233

Maybe you can replace the `self.frame_interval` with `random.randint(1, 3)`.

**Comment by Dai-Wenxun** [comment]
> https://github.com/open-mmlab/mmaction2/blob/master/mmaction/datasets/pipelines/loading.py#L232-L233
> 
> Maybe you can replace the `self.frame_interval` with `random.randint(1, 3)`.

What I say is replacing the `self.frame_interval` in the `__call__`, i.e., discarding this arg totally.

**Comment by soltkreig** [comment]
Oh I'm sorry I confused, I use 1.x branch

**Comment by Dai-Wenxun** [comment]
For 1.x branch, you can modify it here. 
https://github.com/open-mmlab/mmaction2/blob/1.x/mmaction/datasets/transforms/loading.py#L372

**Comment by soltkreig** [comment]
It works, thank you.
I have a second question:
If I have 30 fps vide and use `clip_len = 64` (about 2 secionds) in config and use `frame_interval > 1`, how can I dynamically change the` clip_len` so that it is always the equivalent of 2 seconds?

**Comment by Dai-Wenxun** [comment]
replace the `self.clip_len` with `self.clip_len // frame_interval`. https://github.com/open-mmlab/mmaction2/blob/1.x/mmaction/datasets/transforms/loading.py#L372
