### ISSUE TITLE
RuntimeError: CUDA out of memory.

### ISSUE THREAD

**Issue by Yu-0920** [open-mmlab/mmaction2#2209]
My running cmd is:
python tools/train.py configs/skeleton/posec3d/slowonly_r50_u48_240e_ntu120_xsub_limb.py --cfg-options gpu_ids=[0]
And,
TorchVision: 0.10.0+cu111
OpenCV: 4.6.0
MMCV: 1.6.2
MMCV Compiler: MSVC 192930137
MMCV CUDA Compiler: 11.1
MMAction2: 0.24.1+769004c
![error](https://user-images.githubusercontent.com/59983717/217819410-72663b0b-7b9a-4e59-b741-e1fe56911902.jpg)

I reduce batch size, but still get this error. I'm using RTX 3070.

**Comment by Dai-Wenxun** [comment]
Try to set `videos_per_gpu=1` and check the GPU memory. It seems just because of the CUDA out of memory.

**Comment by Yu-0920** [comment]
oh thanks, it's run.

**Comment by T-wow** [comment]
Hello, how to specify gpu when doing training in mmaction2 version 1.2. thanks.
