### ISSUE TITLE
How can i add more metrics for recognition 

### ISSUE THREAD

**Issue by YancyGuo** [open-mmlab/mmaction2#2232]
1. I have searched related issues but cannot get the expected help.——I did try, but i have no idea which word i choosing to search.

2. I have read the [FAQ documentation](https://mmaction2.readthedocs.io/en/latest/faq.html) but cannot get the expected help.——yes i did, due to my litter coding ability, i cant understand a lot.
```php
How to show test results?

During testing, we can use the command --out xxx.json/pkl/yaml to output result files for checking. The testing output has exactly the same order as the test dataset. Besides, we provide an analysis tool for evaluating a model using the output result files in tools/analysis/eval_metric.py
```
Q: I expect to add more metrics for recognition mission because i found only `top-k metrics & mean_class_accuracy` for recognition, I eager to learn more about how can i add metrics like `recall \ Sensitivity\ Specificity \ Precision` and so on .I knew there are some of them in the core/eval，and i begging you to let me know. It is quite important for me,thank you!!

**Comment by Dai-Wenxun** [comment]
You can add custom metrics here. https://github.com/open-mmlab/mmaction2/blob/master/mmaction/datasets/base.py#L139-L243.
The arg `results` is a list of vectors of cls_scores for each testing sample, and the metric is saved as dict in the `eval_results`, such as  https://github.com/open-mmlab/mmaction2/blob/master/mmaction/datasets/base.py#L211.

**Comment by YancyGuo** [comment]
Thank U!! I did it !!😆
