### ISSUE TITLE
Question about recognition of skeleton-based action

### ISSUE THREAD

**Issue by antonio2600** [open-mmlab/mmaction2#2234]
Hello, I'm using the demo_skeleton.py for a study about the recognition of actions related to degenerative diseases.
I'm a little confused about the architecture of the model. I want to know the exact moment in the person begins to do the action that I've recognized before. For that, I'm going to part the video in x frames, and I'm going to do the inference recognition with those frames and if the action isn't the same I'm going to try with 2x frames, and so on until the action coincides, so I can calculate through video the duration of the action (total time - frames) that it took me to get the action, when the person begins to perform the action.

This is the idea i have. Now the question is, I want to know the moment in which the threshold of the correct action begins to grow, for that I will have to do what I have explained before but with a specific number of frames, that is the question I have. The architecture of the model takes batches of the total number of frames to obtain recognition I suppose, and I can't find how many frames these batches are made up of.
I hope I have explained myself decently because my english is not very good. Thanks and regards.

**Comment by Dai-Wenxun** [comment]
what's your MMAction2 version?

**Comment by antonio2600** [comment]
Another doubt. How can I change the number of k_top? Because it's 5 but I want to see more results. Thanks.

**Comment by Dai-Wenxun** [comment]
Ok, there are two branches in MMAction2: master and 1.x. You could check this https://github.com/open-mmlab/mmaction2/blob/master/mmaction/version.py#L3, and tell me the version you use so that I can give you my advice according to your version.

**Comment by antonio2600** [comment]
![Captura desde 2023-02-20 18-16-39](https://user-images.githubusercontent.com/42941507/220168095-e1de152e-714d-43bb-b5af-47314a801def.png)

**Comment by antonio2600** [comment]
And if you can, answer me the question of the k_top please.

**Comment by antonio2600** [comment]
Okay, I have fount out about the k_top already.

**Comment by antonio2600** [comment]
Please, can you tell me if the architecture of the skeleton model takes batches of the total number of frames? I want to know this to use an specific number of frames for the recognition.

**Comment by Dai-Wenxun** [comment]
If there is PaddingWithLoop in your test_pipeline, the number of the total frames will be zero-padded to 300. https://github.com/open-mmlab/mmaction2/blob/master/configs/skeleton/stgcn/stgcn_80e_ntu60_xsub_keypoint.py#L36
