### ISSUE TITLE
Question about inference with the flow of video

### ISSUE THREAD

**Issue by coder0390** [open-mmlab/mmaction2#2235]
I try to use MMAction2 to make an inference, and the type of my dataset is video. But I found that when the function "inference_recognizer" read the video, it can only read it in the modality of "RGB". So how can I read my video in the modality of "Flow"? Because I use a checkpoint trained by flow of video.

This is the screenshot of the code I found in the "inference.py", which is between 126 and 127 lines.
![image](https://user-images.githubusercontent.com/52817189/219546420-97202e1b-accc-4280-9776-070d519c0e26.png)

**Comment by cir7** [comment]
Hi, @coder0390 , the flow modality we supported is composed of 2 images: horizontal direction and vertical direction, I am confused that how could a video frame composed of 2 channels, or your flow video is a visualization of optical flow in RGB,
if so, just take it as a RGB modality video.

**Comment by coder0390** [comment]
Thanks a lot, I find that I made a mistake. I just think that if I set the modality to the flow, the MMAction2 can extract flows from the video automatically.

So it means that when I use MMAction2, if I want to use the flows of a video, I must extract the flows from it first by myself(Maybe use denseflow)? And when I use the trained model to recognize some videos, I also must do the same thing?

**Comment by cir7** [comment]
@coder0390  yes, extract flow is a offline operation for MMAction2, you can refer [here](https://github.com/open-mmlab/mmaction2/tree/master/tools/data/kinetics#step-3-extract-rgb-and-flow) to extract flow

**Comment by coder0390** [comment]
Thanks!
