### ISSUE TITLE
Is POSEC3D suitable for activity recognition in context of multi-person with different actions

### ISSUE THREAD

**Issue by hoangkhoiLE** [open-mmlab/mmaction2#2238]
Hello,

Now i want to use one model to recognize if a person falling in public. I see that you have  model poseC3D which trained in NTU-RGB+D-120 dataset having annotation of activity "falling".
I see in this article  (https://kennymckormick.github.io/files/cvpr22_tutorial.pdf  - page 20)
<img width="937" alt="image" src="https://user-images.githubusercontent.com/57557628/219699944-4416c4ba-99e3-4b0a-acf3-922cf8758ea9.png">
and in original article  https://arxiv.org/pdf/2104.13586.pdf
That's PoseConv3D can handle multiple-person scenarios without additional computation costs.
But I see that we have this issue https://github.com/open-mmlab/mmaction2/issues/1319 which mentioned that it's not compatible in my case without modification. So it's not compatible in the case when each one doing separate actions (no interactions) in the scene.
 
So to detect a person who falls in public (all other people doing another things), I must do inference for each individual in the scene instead of using configuration by default ?  

Thank for your support,

Best regard

**Comment by cir7** [comment]
@hoangkhoiLE , yes, you are right. In my understanding and in the default config, PoseC3D considers multi-person as a group and infers a group activity category. As shown in pic, the volleyball dataset is also labeled with group activity, instead of each player. And the scalability of PoseC3D is compared to other skeleton models under such a scenario.
For your task, spatiotemporal action detection is more appropriate as mentioned in #1319

**Comment by hoangkhoiLE** [comment]
@cir7 Thank you for your confirmation !

**Comment by paleomoon** [comment]
@cir7 
I want to recognize different people in different actions, better with skeleton, any suggestion? Can we modify PoseC3D pipline with seperate skeleton input? that is add tracker after person detection.

You metioned spatio-temporal action detection,  that is ACRN etc., what about the general accuracy and speed(about 30 people) compared with PoseC3D with tracking, as well as ST-GCN family with tracking?

Thank you!

**Comment by cir7** [comment]
@hukkai 
Do you have any suggestions?
