### ISSUE TITLE
Unable to run mmaction2 on Mac M1 chip

### ISSUE THREAD

**Issue by datascientistlin** [open-mmlab/mmaction2#2243]
**Describe the bug**

I had installed mmaction2 on my macbook with M1 chip. However, as I'm testing the example code for video recogniztion, the code could not run as `mps` device.

**Reproduction**

Here is the code block that I ran:

```
import torch

from mmaction.apis import init_recognizer, inference_recognizer

config_file = 'configs/recognition/tsn/tsn_r50_video_inference_1x1x3_100e_kinetics400_rgb.py'
# download the checkpoint from model zoo and put it in `checkpoints/`
checkpoint_file = 'checkpoints/tsn_r50_1x1x3_100e_kinetics400_rgb_20200614-e508be42.pth'

# assign the desired device.
device = 'mps'
device = torch.device(device)

 # build the model from a config file and a checkpoint file
model = init_recognizer(config_file, checkpoint_file, device=device)

# test a single video and show the result:
video = 'demo/demo.mp4'
labels = 'tools/data/kinetics/label_map_k400.txt'
results = inference_recognizer(model, video)

```

The last step gave me following error.

> RuntimeError: Input type (torch.FloatTensor) and weight type (MPSFloatType) should be the same or input should be a MKLDNN tensor and weight is a dense tensor

**Environment**

Below is the conda environment I had set up, following the instruction here: https://mmaction2.readthedocs.io/en/latest/install.html
 
Python: 3.8.16 (default, Jan 17 2023, 16:42:09) [Clang 14.0.6 ]
CUDA available: False
GCC: Apple clang version 14.0.0 (clang-1400.0.29.202)
PyTorch: 1.13.1
PyTorch compiling details: PyTorch built with:
  - GCC 4.2
  - C++ Version: 201402
  - clang 14.0.0
  - Intel(R) oneAPI Math Kernel Library Version 2021.4-Product Build 20210904 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.6.0 (Git Hash 52b5f107dd9cf10910aaa19cb47f3abf9b349815)
  - OpenMP 201811
  - LAPACK is enabled (usually provided by MKL)
  - NNPACK is enabled
  - CPU capability usage: NO AVX
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CXX_COMPILER=/Applications/Xcode_14.0.1.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -Wno-deprecated-declarations -DUSE_PTHREADPOOL -Xpreprocessor -fopenmp -I/Users/runner/work/_temp/anaconda/conda-bld/pytorch_1670525474122/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl/include -DNDEBUG -DUSE_KINETO -DLIBKINETO_NOCUPTI -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DUSE_PYTORCH_METAL_EXPORT -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -DEDGE_PROFILER_USE_KINETO -DUSE_COREML_DELEGATE -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Werror=non-virtual-dtor -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wunused-local-typedefs -Wno-unused-parameter -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wvla-extension -Wno-range-loop-analysis -Wno-pass-failed -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -Wconstant-conversion -Wno-invalid-partial-specialization -Wno-typedef-redefinition -Wno-unused-private-field -Wno-inconsistent-missing-override -Wno-c++14-extensions -Wno-constexpr-not-const -Wno-missing-braces -Wunused-lambda-capture -Wunused-local-typedef -Qunused-arguments -fcolor-diagnostics -fdiagnostics-color=always -fno-math-errno -fno-trapping-math -Werror=format -Werror=cast-function-type -DUSE_MPS -fno-objc-arc -Wno-unguarded-availability-new -Wno-unused-private-field -Wno-missing-braces -Wno-c++14-extensions -Wno-constexpr-not-const, LAPACK_INFO=mkl, PERF_WITH_AVX512=1, TORCH_VERSION=1.13.1, USE_CUDA=0, USE_CUDNN=OFF, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=OFF, USE_NNPACK=ON, USE_OPENMP=ON, USE_ROCM=OFF, 

TorchVision: 0.14.1
OpenCV: 4.7.0
MMCV: 1.7.1
MMCV Compiler: clang 12.0.0
MMCV CUDA Compiler: not available
MMAction2: 0.24.1+54bc294

Thanks in advance for any help.

**Comment by cir7** [comment]
@datascientistlin 
It looks like that older version mmcv don't support mps device, how about try the 1.x branch, following the [doc](https://mmaction2.readthedocs.io/en/1.x/get_started.html)

**Comment by datascientistlin** [comment]
Thanks @cir7 . Yes, 1.x branch works with M1 chip now!

However, the model output with `mps` as device is not very reliable. Please refer to below output for predicting the demo video.
<img width="623" alt="image" src="https://user-images.githubusercontent.com/44249807/220267770-6d096eab-974c-453f-b212-714481de27b0.png">

While predicting with `cpu` as device seems to give a better result.
<img width="625" alt="image" src="https://user-images.githubusercontent.com/44249807/220267875-a3f0ea51-9619-4d81-a375-9d857389d50c.png">

**Comment by cir7** [comment]
@datascientistlin It looks like a `mps` bug, as I can easily find some related [issue](https://discuss.pytorch.org/t/incorrect-mean-of-slice-of-tensor-on-mps/172355)

**Comment by datascientistlin** [comment]
Thanks @cir7 . It's sad to know that `mps` still has so many bugs when running pytorch model, but I guess we could only wait for Apple/Nvidia to resolve them
