### ISSUE TITLE
TSM，onnx infer error

### ISSUE THREAD

**Issue by simplew2011** [open-mmlab/mmaction2#2255]
- use TSM default model，convert to onnx ok：
```python tools/deployment/pytorch2onnx.py configs/recognition/tsm/tsm_r50_1x1x8_50e_sthv2_rgb.py checkpoints/tsm_r50_256h_1x1x8_50e_sthv2_rgb_20210816-032aa4da.pth --shape 1 8 3 256 256 --verify --softmax --show --output-file checkpoints/tsm_r50_256h_1x1x8_50e_sthv2_rgb_20210816-032aa4da.onnx```

- infer onnx error：
```
python tools/test.py configs/recognition/tsm/tsm_r50_1x1x8_50e_sthv2_rgb.py --onnx \
checkpoints/tsm_r50_256h_1x1x8_50e_sthv2_rgb_20210816-032aa4da.onnx --eval top_k_accuracy mean_class_accuracy \
--out result.json
```

```
  File "/home/wzp/code/model_check/0228_vacc_tsm/mmaction2/tools/test.py", line 373, in <module>
    main()
  File "/home/wzp/code/model_check/0228_vacc_tsm/mmaction2/tools/test.py", line 356, in main
    dataloader_setting['videos_per_gpu'])
  File "/home/wzp/code/model_check/0228_vacc_tsm/mmaction2/tools/test.py", line 263, in inference_onnx
    onnx_result = sess.run(None, {net_feed_input[0]: imgs})[0]
  File "/home/wzp/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 200, in run
    return self._sess.run(output_names, input_feed, run_options)
onnxruntime.capi.onnxruntime_pybind11_state.InvalidArgument: [ONNXRuntimeError] : 2 : INVALID_ARGUMENT : Got invalid dimensions for input: 0 for the following indices
 index: 1 Got: 48 Expected: 8
 Please fix either the inputs or the model.
```

![image](https://user-images.githubusercontent.com/66729924/222052746-9bcd9c53-d267-4908-8024-72ba534a3b26.png)

**Comment by simplew2011** [comment]
using default config：https://github.com/open-mmlab/mmaction2/blob/master/configs/recognition/tsm/tsm_r50_1x1x8_50e_sthv2_rgb.py

**Comment by irvingzhang0512** [comment]
remove all test-time augmentation methods in test_pipeline(ThreeCrop, TenCrop, twice_sample, etc.)

**Comment by irvingzhang0512** [comment]
Or you can just use val_pipeline, not test_pipeline

**Comment by simplew2011** [comment]
it work，thank you.
![image](https://user-images.githubusercontent.com/66729924/222315753-15b521ba-70cd-456a-ad07-e96f0d703214.png)

**Comment by simplew2011** [comment]
![image](https://user-images.githubusercontent.com/66729924/222759219-0ebd48b6-ec40-4340-9df6-526f7061ec41.png)
