### ISSUE TITLE
Can MMAction2 be installed and used on colab?

### ISSUE THREAD

**Issue by sweenmm** [open-mmlab/mmaction2#2264]
Before raising a question, you may need to check the following listed items.

**Checklist**

1. I have searched related issues but cannot get the expected help.
2. I have read the [FAQ documentation](https://mmaction2.readthedocs.io/en/latest/faq.html) but cannot get the expected help.

**Comment by hukkai** [comment]
Yes https://github.com/open-mmlab/mmaction2#get-started
