### ISSUE TITLE
How can I use the inference recogize to process a batch during inferecing. 

### ISSUE THREAD

**Issue by Shantanu-repo** [open-mmlab/mmaction2#2286]
images = glob(d + '/**')
    # print('images',images)
    img = []
    for i in images:
        img.append(cv2.imread(i))
    print(len(img))
    # print(img)
    img = np.stack(img)
    img = np.expand_dims(img,axis=0)
    print(img.shape)
    results = inference_recognizer(model, img)

**Comment by cir7** [comment]
@Shantanu-repo 
we specify the input tensor shape [here](https://github.com/open-mmlab/mmaction2/commit/65a6d1e5bcb472f463ce93342c8596cd3a875721), please make sure input tensor has a shape of ` T x H x W x C`

**Comment by Shantanu-repo** [comment]
But I want to process a batch, how do I do that? THWC is for single batch how about BTHWC? is there a work around or will I need to export the model to onnx or tensorrt runtimes?

**Comment by cir7** [comment]
@Shantanu-repo 
this api can only process a single video each time, for a batch of videos, I suggest just calling the api iteratively for each video.
If you want to infer a large number of samples, I suggest you try to organize them as a test dataset, and use `tools/test.py` to infer samples more efficiently.
