### ISSUE TITLE
Hello, the model test problem

### ISSUE THREAD

**Issue by 2110310010** [open-mmlab/mmaction2#2296]
I'm in version v0.1. I run the test.py 
python tools/test.py configs/recognition/timesformer/timesformer.py /hy-tmp/timesformer1/epoch_4.pth --eval top_k_accuracy mean_class_accuracy  --out result.json --average-clips=prob   --cfg-options gpu_ids=[0]

But in version V1.0. How can I run this test.py to see this top_k_accuracy mean_class_accuracy?

looking forward to your answer? Thanks!

**Comment by hukkai** [comment]
@2110310010 Please check this doc: https://github.com/open-mmlab/mmaction2/blob/1.x/docs/en/user_guides/4_train_test.md

**Comment by 2110310010** [comment]
Thanks your help! But I don't find the suitable  ARGS in the https://github.com/open-mmlab/mmaction2/blob/1.x/docs/en/user_guides/4_train_test.md  to obtain the  top_k_accuracy mean_class_accuracy index.
 Can you provide some detailed information?

**Comment by Dai-Wenxun** [comment]
Could you please show me your full config file?

**Comment by Dai-Wenxun** [comment]
https://github.com/open-mmlab/mmaction2/blob/main/configs/recognition/tsn/tsn_imagenet-pretrained-r50_8xb32-1x1x3-100e_kinetics400-rgb.py#L93
The `AccMetric` calculate the top5, top1, and mean1 acc by default. If you want to calculate top3 instead top5, you can set your config as follows:
```
val_evaluator = dict(type='AccMetric', metric_options=dict(top_k_accuracy=dict(topk=(1, 3)))
```
You can check [this doc](https://mmaction2.readthedocs.io/en/latest/api.html#mmaction.evaluation.metrics.AccMetric) for API usage.
