### ISSUE TITLE
Output video error

### ISSUE THREAD

**Issue by Yu-0920** [open-mmlab/mmaction2#2304]
When I run python demo/demo skeleton.py, the output video cannot be opened. How do I know what is wrong?

**Comment by Kempeter** [comment]
@Yu-0920 What is your error code?

**Comment by Yu-0920** [comment]
![image](https://user-images.githubusercontent.com/59983717/226172449-bf7d9255-6a32-46d9-9613-72075107c975.png)
![image](https://user-images.githubusercontent.com/59983717/226172464-2af21e7f-9395-42d0-aa60-aaa2ba810f7b.png)
no error but video can't show

**Comment by sunfeiran0228** [comment]
I'm also having the same issue. My video cannot play, either.  Could please tell me how you solve this problem? Thx !

**Comment by sunfeiran0228** [comment]
I'm also having the same issue. My video cannot play, either. Could you please tell me how you solve this problem? Thx !
