### ISSUE TITLE
Each video has a different total number of frames. When the product of the sampling interval and the sampling length is greater than the total number of frames in a video, how does mmaction2 handle this situation internally?

### ISSUE THREAD

**Issue by h030162** [open-mmlab/mmaction2#2305]
Before raising a question, you may need to check the following listed items.

**Checklist**

1. I have searched related issues but cannot get the expected help.
2. I have read the [FAQ documentation](https://mmaction2.readthedocs.io/en/latest/faq.html) but cannot get the expected help.

**Comment by hukkai** [comment]
@h030162 We do a padding: https://github.com/open-mmlab/mmaction2/blob/b83ad4f4efdaf5b06a7fd2af6d789dd6cdb91bed/mmaction/datasets/pipelines/loading.py#L99.

There are two options to do padding, one is to loop the video and the other is to repeat the last frame. By default we use the loop option.

**Comment by h030162** [comment]
thanks
