### ISSUE TITLE
test has some bugs

### ISSUE THREAD

**Issue by pokameng** [open-mmlab/mmaction2#2318]
@lindahua @usernameandme @yuta1125tp @datumbox @jenhaoyang 
When i run test.py something is wrong:
test.py: error: unrecognized arguments: checkpoints/ACRN_GT.pth --eval mAP --out resultacrn.csv
How can i solve it?

**Comment by Dai-Wenxun** [comment]
What is your command line input? BTW, you can refer to this [page](https://github.com/open-mmlab/mmaction2/tree/master/configs/detection/acrn#test) for more details about testing.
