### ISSUE TITLE
After convert CSN model to trt format, the inference time is much slower than origin pytorch format.

### ISSUE THREAD

**Issue by aixiaodewugege** [open-mmlab/mmaction2#2331]
I tried to convert the CSM model to trt format with follow deplo config,

_base_ = ['./video-recognition_static.py']

onnx_config = dict(
    type='onnx',
    export_params=True,
    keep_initializers_as_inputs=False,
    opset_version=11,
    save_file='end2end.onnx',
    input_names=['input'],
    output_names=['output'],
    input_shape=[256, 256],
    optimize=True,
    dynamic_axes=dict(
        input=dict({
            1: 'num_crops * num_segs',
        }),
       ))
codebase_config = dict(type='mmaction', task='VideoRecognition')
backend_config = dict(
    type='tensorrt',
    common_config=dict(fp16_mode=False, max_workspace_size=99073741824),
    model_inputs=[
        dict(
            input_shapes=dict(
                input=dict(
                    min_shape=[1, 1, 3, 32, 256, 256],
                    opt_shape=[1, 6, 3, 32, 256, 256],
                    max_shape=[1, 30, 3, 32, 256, 256])))
    ])

I think the convert was successful, for it didn't report any issue. But the speed is very slow. How can I location the problem? Is the problem able to be solved?

**Comment by hukkai** [comment]
You may need to submit an issue to mmdeploy.
