### ISSUE TITLE
[Bug] MMACTION's support algorithm links all 404

### ISSUE THREAD

**Issue by Fanthers** [open-mmlab/mmaction2#2369]
### Branch

1.x branch (1.x version, such as `v1.0.0rc2`, or `dev-1.x` branch)

### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmaction2/issues) and [Discussions](https://github.com/open-mmlab/mmaction2/discussions) but cannot get the expected help.
- [X] I have read the [documentation](https://mmaction2.readthedocs.io/en/latest/) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version](https://github.com/open-mmlab/mmaction2).

### Environment

MMACTION's support algorithm links all 404

### Describe the bug

MMACTION's support algorithm links all 404

**Comment by cir7** [comment]
Thanks for your reminder, the bug has been fixed.

**Comment by vasanth4224** [comment]
> Thanks for your reminder, the bug has been fixed.

Still error: The 'open-mmlab/mmaction2' repository doesn't contain the 'configs/detection/ava/README.md' path in 'main'.

**Comment by cir7** [comment]
We fix the issue in the `main` branch. The `1.x` branch has been renamed to `main`, which is the default branch now, and `dev-1.x` is still the development branch.

**Comment by cir7** [comment]
@vasanth4224 
sorry for the mistake, the ava link has been updated.
