### ISSUE TITLE
[Bug] Recognizer3D

### ISSUE THREAD

**Issue by Nagaloop** [open-mmlab/mmaction2#2398]
### Branch

1.x branch (1.x version, such as `v1.0.0rc2`, or `dev-1.x` branch)

### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmaction2/issues) and [Discussions](https://github.com/open-mmlab/mmaction2/discussions) but cannot get the expected help.
- [X] I have read the [documentation](https://mmaction2.readthedocs.io/en/latest/) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version](https://github.com/open-mmlab/mmaction2).

### Environment

pip install -U openmim
mim install mmengine 'mmcv>=2.0.0rc1'
mim install "mmdet>=3.0.0rc5"  # optional
mim install "mmpose>=1.0.0rc0"  # optional
git clone https://github.com/open-mmlab/mmaction2.git
cd mmaction2
git checkout 1.x
pip3 install -e .

### Describe the bug

on 6cc912ba414c1f3b6cdc8cb3ea310ac3bf44d004/configs/recognition/i3d
when I try export onnx ，it refer AttributeError: 'Recognizer3D' object has no attribute 'roi_head' . how can I fix  it ?

### Reproduces the problem - command or script

python3 tools/deployment/export_onnx_stdet.py configs/recognition/i3d/i3d_imagenet-pretrained-r50_8xb8-32x2x1-100e_kinetics400-rgb.py checkpoints/i3d_imagenet-pretrained-r50_8xb8-32x2x1-100e_kinetics400-rgb_20220812-e213c223.pth --shape 256 256  --output_file i3d.onnx --num_frames 10

### Reproduces the problem - error message

File "tools/deployment/export_onnx_stdet.py", line 153, in main
    model = STDet(base_model, input_tensor).to(args.device)
  File "tools/deployment/export_onnx_stdet.py", line 102, in __init__
    self.bbox_roi_extractor = base_model.roi_head.bbox_roi_extractor
  File "/usr/local/bin/miniconda3/envs/openmmlab/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1614, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'Recognizer3D' object has no attribute 'roi_head'

**Comment by hukkai** [comment]
@Nagaloop This python file is only used to convert spatial temporal detection models and you need to use configs under `configs/detection` folder. If you want to covert classification models, you can refer to `mmdeploy`: https://github.com/open-mmlab/mmdeploy/tree/main/configs/mmaction/video-recognition

**Comment by hukkai** [comment]
@Nagaloop If you have any questions, feel free to reopen the issue. Thanks!
