### ISSUE TITLE
Bug of ntu_pose_extraction.py

### ISSUE THREAD

**Issue by Better369** [open-mmlab/mmaction2#2400]
### Branch

1.x branch (1.x version, such as `v1.0.0rc2`, or `dev-1.x` branch)

### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmaction2/issues) and [Discussions](https://github.com/open-mmlab/mmaction2/discussions) but cannot get the expected help.
- [X] I have read the [documentation](https://mmaction2.readthedocs.io/en/latest/) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version](https://github.com/open-mmlab/mmaction2).

### Environment

mmaction2             1.0.0       
mmcv                  2.0.0rc4
mmdet                 3.0.0  
mmengine              0.7.2
mmpose                1.0.0      
numpy                 1.24.1
torch                 1.8.0
torchaudio            0.8.0
torchvision           0.9.0

### Describe the bug

When I use the ntu_pose_extraction.py in mmactiondev-1.x to extract bones, I set the skip-postproc hyperparameter to Ture and will report an error, but it will not report an error in the master version, what is the reason?
It should also be noted that when I do not set the value of skip-postproc in the master version, not all videos can generate PKL files, but when I set the value of skip-postproc to Ture, I can generate all PKL files. (I use a custom dataset)
![19a781ce5e39de954ff0ba88048c25d](https://user-images.githubusercontent.com/109217396/232080360-b7b3aaac-b0ed-465a-bf29-f7e635d15d2c.png)
![1681484402254](https://user-images.githubusercontent.com/109217396/232080471-a227c07f-a0e4-4fd2-9f06-0812f0c6d014.png)

### Reproduces the problem - code sample

![1681484479345](https://user-images.githubusercontent.com/109217396/232080703-6871f873-3935-4277-bca8-0bf2e0bdc153.png)

**Comment by cir7** [comment]
Thanks for your feedback, the bug has been fixed in #2402
