### ISSUE TITLE
[Feature] Colab file is missing now, which was available earlier for mmaction2.

### ISSUE THREAD

**Issue by commandermsv** [open-mmlab/mmaction2#2401]
### What is the problem this feature will solve?

Colab file is missing now, which was available earlier for mmaction2.

### What is the feature?

Colab file of mmaction2

**Comment by cir7** [comment]
Which file exactly are you referring to?

**Comment by commandermsv** [comment]
Thank you for your response,
Earlier colab link was visible on the main page of mmaction2, but now i can see its shifted to [mmaction2](https://github.com/open-mmlab/mmaction2)/[demo](https://github.com/open-mmlab/mmaction2/tree/main/demo)/mmaction2_tutorial.ipynb

I have another concern now, im unable to train mvit model using colab demo file, its showing cuda out of memory when i try to train. My system is having 15GB GPU. Can you please tell how much gpu memory required for mvit? I have also tried to reduce batch size to 2, but still same cuda out of memory issue exists.

**Comment by cir7** [comment]
I am not sure how much GPU memory the model takes. maybe turning off the repeat augment could be helpful, you could set the [arg](https://github.com/open-mmlab/mmaction2/blob/main/configs/recognition/mvit/mvit-small-p244_k400-maskfeat-pre_8xb32-16x4x1-100e_kinetics400-rgb.py#L77) to 1 or use [sthv2 config](https://github.com/open-mmlab/mmaction2/blob/main/configs/recognition/mvit/mvit-small-p244_k400-pre_16xb16-u16-100e_sthv2-rgb.py)

**Comment by commandermsv** [comment]
OK thanks.
