### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by Ishihara-Masabumi** [open-mmlab/mmaction2#2412]
### The doc issue

The following installation error occurred.
```
$ conda create --name openmmlab2 python=3.8 -y
$ conda activate openmmlab2
$ conda install pytorch torchvision cpuonly -c pytorch
$ pip install -U openmim
$ mim install mmengine
$ mim install mmcv
$ mim install mmdet
$ mim install mmpose
$ git clone https://github.com/open-mmlab/mmaction2.git
Cloning into 'mmaction2'...
/usr/lib/git-core/git-remote-https: symbol lookup error: /lib/x86_64-linux-gnu/libp11-kit.so.0: undefined symbol: ffi_type_pointer, version LIBFFI_BASE_7.0
```
Please let me know how to fix it.

**Comment by cir7** [comment]
The issue has no relationship with mmaction2, looks like something is wrong with your git, [here](https://stackoverflow.com/questions/75973072/unable-to-git-clone-by-symbol-lookup-error-lib-x86-64-linux-gnu-libp11-kit-so) is a solution from google.
