### ISSUE TITLE
Slowonly Questions

### ISSUE THREAD

**Issue by Yu-0920** [open-mmlab/mmaction2#2423]
### The doc issue

Can I change the parameters or the  layers in SlowOnly for training? If so, which file can I go to to change the code.

**Comment by cir7** [comment]
Hi, @Yu-0920 , we define SlowOnly backbone [here](https://github.com/open-mmlab/mmaction2/blob/main/mmaction/models/backbones/resnet3d_slowonly.py), and specify the model by the config file, you can refer to the [doc](https://mmaction2.readthedocs.io/en/latest/user_guides/config.html) for details.  
you can tune the structure of model as you want and specify the modified model in the config file.
