### ISSUE TITLE
Train SlowFast with different inputs for slow pathway & fast pathway

### ISSUE THREAD

**Issue by JasseurHadded1** [open-mmlab/mmaction2#2438]
### What is the problem this feature will solve?

Hello,

I want to train a slowfast model but with different input for the fast pathway and the slow pathway, the slow pathway will contain only the object that I want to track and predict its action,

I have tried to play with the config to do it but I couldn't, 

Any help? Thanks,

### What is the feature?

!

**Comment by Dai-Wenxun** [comment]
Sorry, currently we don't support doing so, but we have implemented  [`RGBPoseConv3D`](https://github.com/open-mmlab/mmaction2/tree/main/configs/skeleton/posec3d/rgbpose_conv3d), which adapt the slowfast to process `skeleton` and `image` simultaneously. Maye you can refer to this to fulfill your needs.
