### ISSUE TITLE
confused about the short-side.

### ISSUE THREAD

**Issue by donnyyou** [open-mmlab/mmaction2#244]
https://github.com/open-mmlab/mmaction2/blob/master/configs/recognition/slowfast/README.md
The RandomResizedCrop has nothing to do with the short-side of the Resize. I wonder how to set the short-side during training, or you only set different short-sides for testing?

**Comment by innerlee** [comment]
`short-side  256` and `short-side 320` are labels of the original resolution of data used for training. They are not related to pre-processing or augmentation.

**Comment by SuX97** [comment]
> short-side 256 and short-side 320 are labels of the original resolution of data used for training. They are not related to pre-processing or augmentation.

Yeah, all slowfast model are using 224*224 images as input, the resolution only indicate the size of the rawframes we read from extracted by this [script](https://github.com/open-mmlab/mmaction2/blob/master/tools/data/build_rawframes.py#L159).

The reason behind it is that reading a smaller image (short-side 256) is faster when training but somehow loss some tiny accuracy compares to a bigger image(short-side 320).@donnyyou

**Comment by donnyyou** [comment]
Training with raw videos seemly achieve lower performance than training with pre-build frames. Have you tested the difference?

**Comment by innerlee** [comment]
see https://mmaction2.readthedocs.io/en/latest/recognition_models.html#kinetics-400-data-benchmark

**Comment by donnyyou** [comment]
https://github.com/open-mmlab/mmaction2/blob/master/configs/recognition/slowonly/README.md#kinetics-400
slowfast_r50_video_4x16x1_256e_kinetics400_rgb vs. slowonly_r50_4x16x1_256e_kinetics400_rgb

https://github.com/open-mmlab/mmaction2/blob/master/configs/recognition/slowfast/README.md#kinetics-400
slowfast_r50_video_4x16x1_256e_kinetics400_rgb vs. slowfast_r50_4x16x1_256e_kinetics400_rgb

The performance with raw video seemingly has a performance drop.

**Comment by innerlee** [comment]
They are slightly different, but I do not agree that there are major differences. Actually in some cases, video data is slightly better.
