### ISSUE TITLE
[Docs] Could you please add a guide to show how to finetune UniFormerV2 on my own dataset? 

### ISSUE THREAD

**Issue by aixiaodewugege** [open-mmlab/mmaction2#2448]
### The doc issue

My classification number is less than the pretrained model Kinetics-400. How should I change the config file?

Looking forward to your reply.

**Comment by Dai-Wenxun** [comment]
Could you please show me your full config?

**Comment by Dai-Wenxun** [comment]
Take this [config file](https://github.com/open-mmlab/mmaction2/blob/main/configs/recognition/uniformerv2/uniformerv2-base-p16-res224_clip-kinetics710-kinetics-k400-pre_u8_mitv1-rgb.py) as an example, you only need to modify [the number of classes](https://github.com/open-mmlab/mmaction2/blob/main/configs/recognition/uniformerv2/uniformerv2-base-p16-res224_clip-kinetics710-kinetics-k400-pre_u8_mitv1-rgb.py#L36) of the classification head and [the paths to your annotation files](https://github.com/open-mmlab/mmaction2/blob/main/configs/recognition/uniformerv2/uniformerv2-base-p16-res224_clip-kinetics710-kinetics-k400-pre_u8_mitv1-rgb.py#L47-L51). You can follow this [tutorial](https://mmaction2.readthedocs.io/en/latest/get_started/guide_to_framework.html#step0-prepare-data) to prepare your dataset.

**Comment by aixiaodewugege** [comment]
Hi, I have change the config file as you suggested. I want to fintune the model on my dataset which add one class to kinitct 400, so it has 401 labels.


Here is my config content.

_base_ = ['../../_base_/default_runtime.py']

# model settings
num_frames = 8
model = dict(
    type='Recognizer3D',
    backbone=dict(
        type='UniFormerV2',
        input_resolution=224,
        patch_size=16,
        width=768,
        layers=12,
        heads=12,
        t_size=num_frames,
        dw_reduction=1.5,
        backbone_drop_path_rate=0.,
        temporal_downsample=False,
        no_lmhra=True,
        double_lmhra=True,
        return_list=[8, 9, 10, 11],
        n_layers=4,
        n_dim=768,
        n_head=12,
        mlp_factor=4.,
        drop_path_rate=0.,
        mlp_dropout=[0.5, 0.5, 0.5, 0.5],
        clip_pretrained=False,
        init_cfg=dict(
            type='Pretrained',
            checkpoint=  # noqa: E251
            'https://download.openmmlab.com/mmaction/v1.0/recognition/uniformerv2/kinetics710/uniformerv2-base-p16-res224_clip-pre_u8_kinetics710-rgb_20221219-77d34f81.pth',  # noqa: E501
            prefix='backbone.')),
    cls_head=dict(
        type='UniFormerHead',
        dropout_ratio=0.5,
        num_classes=401,
        in_channels=768,
        average_clips='prob',
        channel_map=  # noqa: E251
        'configs/recognition/uniformerv2/k710_channel_map/map_k400.json',
        init_cfg=dict(
            type='Pretrained',
            checkpoint=  # noqa: E251
            'https://download.openmmlab.com/mmaction/v1.0/recognition/uniformerv2/kinetics710/uniformerv2-base-p16-res224_clip-pre_u8_kinetics710-rgb_20221219-77d34f81.pth',  # noqa: E501
            prefix='cls_head.')),
    data_preprocessor=dict(
        type='ActionDataPreprocessor',
        mean=[114.75, 114.75, 114.75],
        std=[57.375, 57.375, 57.375],
        format_shape='NCTHW'))

# dataset settings
dataset_type = 'VideoDataset'
data_root = ''
data_root_val = ''
ann_file_train = '/data/mmaciotn2_finetune_dataset/fintune.txt'
ann_file_val = '/data/mmaciotn2_finetune_dataset/fintune.txt'
ann_file_test = '/data/mmaciotn2_finetune_dataset/fintune.txt'

file_client_args = dict(io_backend='disk')
train_pipeline = [
    dict(type='DecordInit', **file_client_args),
    dict(type='UniformSample', clip_len=num_frames, num_clips=1),
    dict(type='DecordDecode'),
    dict(type='Resize', scale=(-1, 256)),
    dict(
        type='PytorchVideoWrapper',
        op='RandAugment',
        magnitude=7,
        num_layers=4),
    dict(type='RandomResizedCrop'),
    dict(type='Resize', scale=(224, 224), keep_ratio=False),
    dict(type='Flip', flip_ratio=0.5),
    dict(type='FormatShape', input_format='NCTHW'),
    dict(type='PackActionInputs')
]

val_pipeline = [
    dict(type='DecordInit', **file_client_args),
    dict(
        type='UniformSample', clip_len=num_frames, num_clips=1,
        test_mode=True),
    dict(type='DecordDecode'),
    dict(type='Resize', scale=(-1, 224)),
    dict(type='CenterCrop', crop_size=224),
    dict(type='FormatShape', input_format='NCTHW'),
    dict(type='PackActionInputs')
]

test_pipeline = [
    dict(type='DecordInit', **file_client_args),
    dict(
        type='UniformSample', clip_len=num_frames, num_clips=4,
        test_mode=True),
    dict(type='DecordDecode'),
    dict(type='Resize', scale=(-1, 224)),
    dict(type='ThreeCrop', crop_size=224),
    dict(type='FormatShape', input_format='NCTHW'),
    dict(type='PackActionInputs')
]

train_dataloader = dict(
    batch_size=8,
    num_workers=8,
    persistent_workers=True,
    sampler=dict(type='DefaultSampler', shuffle=True),
    dataset=dict(
        type=dataset_type,
        ann_file=ann_file_train,
        data_prefix=dict(video=data_root),
        pipeline=train_pipeline))
val_dataloader = dict(
    batch_size=8,
    num_workers=8,
    persistent_workers=True,
    sampler=dict(type='DefaultSampler', shuffle=False),
    dataset=dict(
        type=dataset_type,
        ann_file=ann_file_val,
        data_prefix=dict(video=data_root_val),
        pipeline=val_pipeline,
        test_mode=True))
test_dataloader = dict(
    batch_size=8,
    num_workers=8,
    persistent_workers=True,
    sampler=dict(type='DefaultSampler', shuffle=False),
    dataset=dict(
        type=dataset_type,
        ann_file=ann_file_test,
        data_prefix=dict(video=data_root_val),
        pipeline=test_pipeline,
        test_mode=True))

val_evaluator = dict(type='AccMetric')
test_evaluator = dict(type='AccMetric')
train_cfg = dict(
    type='EpochBasedTrainLoop', max_epochs=5, val_begin=1, val_interval=1)
val_cfg = dict(type='ValLoop')
test_cfg = dict(type='TestLoop')

base_lr = 2e-6
optim_wrapper = dict(
    optimizer=dict(
        type='AdamW', lr=base_lr, betas=(0.9, 0.999), weight_decay=0.05),
    paramwise_cfg=dict(norm_decay_mult=0.0, bias_decay_mult=0.0),
    clip_grad=dict(max_norm=20, norm_type=2))

param_scheduler = [
    dict(
        type='LinearLR',
        start_factor=0.5,
        by_epoch=True,
        begin=0,
        end=1,
        convert_to_iter_based=True),
    dict(
        type='CosineAnnealingLR',
        T_max=4,
        eta_min_ratio=0.5,
        by_epoch=True,
        begin=1,
        end=5,
        convert_to_iter_based=True)
]

default_hooks = dict(
    checkpoint=dict(interval=3, max_keep_ckpts=5), logger=dict(interval=100))

# Default setting for scaling LR automatically
#   - `enable` means enable scaling LR automatically
#       or not by default.
#   - `base_batch_size` = (8 GPUs) x (8 samples per GPU).
auto_scale_lr = dict(enable=True, base_batch_size=256)

How ever it report some error :

Traceback (most recent call last):
  File "tools/train.py", line 135, in <module>
    main()
  File "tools/train.py", line 131, in main
    runner.train()
  File "/home/wushuchen/anaconda3/envs/open-mmyolo/lib/python3.7/site-packages/mmengine/runner/runner.py", line 1692, in train
    self._init_model_weights()
  File "/home/wushuchen/anaconda3/envs/open-mmyolo/lib/python3.7/site-packages/mmengine/runner/runner.py", line 899, in _init_model_weights
    model.init_weights()
  File "/home/wushuchen/projects/mmyolo/mmaction2/mmaction/models/recognizers/base.py", line 110, in init_weights
    super().init_weights()
  File "/home/wushuchen/anaconda3/envs/open-mmyolo/lib/python3.7/site-packages/mmengine/model/base_module.py", line 127, in init_weights
    m.init_weights()
  File "/home/wushuchen/projects/mmyolo/mmaction2/mmaction/models/heads/uniformer_head.py", line 78, in init_weights
    msg = self.load_state_dict(state_dict, strict=False)
  File "/home/wushuchen/anaconda3/envs/open-mmyolo/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1672, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for UniFormerHead:
        size mismatch for fc_cls.weight: copying a param with shape torch.Size([400, 768]) from checkpoint, the shape in current model is torch.Size([401, 768]).
        size mismatch for fc_cls.bias: copying a param with shape torch.Size([400]) from checkpoint, the shape in current model is torch.Size([401]).

**Comment by aixiaodewugege** [comment]
按照微信群大佬的指点去掉这段

`          init_cfg=dict(
           type='Pretrained',
           checkpoint=  # noqa: E251
            'https://download.openmmlab.com/mmaction/v1.0/recognition/uniformerv2/kinetics710/uniformerv2-base-p16-res224_clip-pre_u8_kinetics710-rgb_20221219-77d34f81.pth',  # noqa: E501
           prefix='cls_head.')),`

还是不ok啊

Traceback (most recent call last):
  File "/home/wushuchen/anaconda3/envs/open-mmyolo/lib/python3.7/site-packages/mmengine/config/config.py", line 236, in _validate_py_syntax
    ast.parse(content)
  File "/home/wushuchen/anaconda3/envs/open-mmyolo/lib/python3.7/ast.py", line 35, in parse
    return compile(source, filename, mode, PyCF_ONLY_AST)
  File "<unknown>", line 53
    dataset_type = 'VideoDataset'
               ^
SyntaxError: invalid syntax

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tools/train.py", line 135, in <module>
    main()
  File "tools/train.py", line 122, in main
    cfg = Config.fromfile(args.config)
  File "/home/wushuchen/anaconda3/envs/open-mmyolo/lib/python3.7/site-packages/mmengine/config/config.py", line 178, in fromfile
    filename, use_predefined_variables, use_environment_variables)
  File "/home/wushuchen/anaconda3/envs/open-mmyolo/lib/python3.7/site-packages/mmengine/config/config.py", line 478, in _file2dict
    for base_cfg_path in Config._get_base_files(temp_config_file.name):
  File "/home/wushuchen/anaconda3/envs/open-mmyolo/lib/python3.7/site-packages/mmengine/config/config.py", line 636, in _get_base_files
    Config._validate_py_syntax(filename)
  File "/home/wushuchen/anaconda3/envs/open-mmyolo/lib/python3.7/site-packages/mmengine/config/config.py", line 238, in _validate_py_syntax
    raise SyntaxError('There are syntax errors in config '
SyntaxError: There are syntax errors in config file /tmp/tmpf_r4z3a7/tmp80_r4r28.py: invalid syntax (<unknown>, line 53)
Exception ignored in: <function _TemporaryFileCloser.__del__ at 0x7f6447a899e0>
Traceback (most recent call last):
  File "/home/wushuchen/anaconda3/envs/open-mmyolo/lib/python3.7/tempfile.py", line 448, in __del__
    self.close()
  File "/home/wushuchen/anaconda3/envs/open-mmyolo/lib/python3.7/tempfile.py", line 444, in close
    unlink(self.name)
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmpf_r4z3a7/tmp80_r4r28.py'
