### ISSUE TITLE
[Feature] What should I do to Implement others' work and contribute to mmaction2

### ISSUE THREAD

**Issue by makecent** [open-mmlab/mmaction2#2454]
### What is the problem this feature will solve?

I am interested in implementing an existing work (BasicTAD, not authored by me) as a new project within the MMAction2 framework, and I am wondering if you could provide some guidance on the necessary steps to do so. Your expertise would be invaluable in helping me to enhance the repository.

### What is the feature?

 a step-by-step guidance on implementing a project within the MMAction2 framework, especially if we are not the author. For example, do we need to obtain permission from the original authors before implementing their work in MMAction2?

**Comment by cir7** [comment]
Thanks for your interest in contributing to MMAction2. There is a step-by-step contribution [guide](https://github.com/open-mmlab/mmaction2#-contributing-) and an outline guide(https://mmaction2.readthedocs.io/en/latest/get_started/contribution_guide.html).  
I have contacted you by email, which is more convenient for communication.
