### ISSUE TITLE
Unable to start the Tutorial on Google Colab

### ISSUE THREAD

**Issue by kd610** [open-mmlab/mmaction2#2474]
### Branch

main branch (1.x version, such as `v1.0.0`, or `dev-1.x` branch)

### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmaction2/issues) and [Discussions](https://github.com/open-mmlab/mmaction2/discussions) but cannot get the expected help.
- [X] I have read the [documentation](https://mmaction2.readthedocs.io/en/latest/) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version](https://github.com/open-mmlab/mmaction2).

### Environment

Google Colab GPU T4 (accessed 14 May 2023).

Output of `nvidia-smi` is below:

```
Sun May 14 21:45:43 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.85.12    Driver Version: 525.85.12    CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   68C    P8    11W /  70W |      0MiB / 15360MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
```

### Describe the bug

Although the tutorial notebook (https://github.com/open-mmlab/mmaction2/blob/main/demo/mmaction2_tutorial.ipynb) was modified in May, it doesn't work on Google Colab currently because the CUDA version has been updated from 11 to 12. Especially, I have been facing the installation part, so I can't import all required modules without having an error. 

I appreciate if someone could fix this issue, so that everyone can play around mmaction2 on the new Google Colab :)

**Comment by hukkai** [comment]
@kd610 What is the error log you faced when run on Colab?

**Comment by cir7** [comment]
The notebook has been updated in #2475 , welcome to try the latest version in the main branch

**Comment by kd610** [comment]
Thank you for both responding super quickly. And I appreciate your commit @cir7 . I just ran the notebook, and I can see that there is no problem starting training the model!!! Many thanks.
