### ISSUE TITLE
KeyError: 'message_hub'

### ISSUE THREAD

**Issue by ORainn** [open-mmlab/mmaction2#2478]
### Branch

main branch (1.x version, such as `v1.0.0`, or `dev-1.x` branch)

### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmaction2/issues) and [Discussions](https://github.com/open-mmlab/mmaction2/discussions) but cannot get the expected help.
- [X] I have read the [documentation](https://mmaction2.readthedocs.io/en/latest/) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version](https://github.com/open-mmlab/mmaction2).

### Environment

mmaction2                 1.0.0rc3                  dev_0    <develop>
mmcv                      2.0.0                    pypi_0    pypi
mmcv-full                 1.7.1                    pypi_0    pypi
mmengine                  0.7.2                    pypi_0    pypi

### Describe the bug

Hi, I want to fine-tune the pre trained timesformer model, but there seems to be some issues with 'resume'.
The pre-trained model used here is downloaded from here: https://download.openmmlab.com/mmaction/v1.0/recognition/timesformer/timesformer_divST_8xb8-8x32x1-15e_kinetics400-rgb/timesformer_divST_8xb8-8x32x1-15e_kinetics400-rgb_20220815-a4d0d01f.pth

### Reproduces the problem - command or script

python tools/train.py configs/recognition/timesformer/timesformer_divST_1.py --work-dir work_dirs/timesformer_divST_0515 --resume checkpoints/timesformer_divST_8xb8-8x32x1-15e_kinetics400-rgb_20220815-a4d0d01f.pth --seed 3407 --cfg-options gpu_ids=[0]

_No response_

### Reproduces the problem - error message

Loads checkpoint by local backend from path: checkpoints/timesformer_divST_8x32x1_15e_kinetics400_rgb-3f8e5d03.pth
The model and loaded state dict do not match exactly

size mismatch for backbone.time_embed: copying a param with shape torch.Size([1, 8, 768]) from checkpoint, the shape in current model is torch.Size([1, 32, 768]).
size mismatch for cls_head.fc_cls.weight: copying a param with shape torch.Size([400, 768]) from checkpoint, the shape in current model is torch.Size([11, 768]).
size mismatch for cls_head.fc_cls.bias: copying a param with shape torch.Size([400]) from checkpoint, the shape in current model is torch.Size([11]).
05/15 11:47:39 - mmengine - INFO - Load checkpoint from checkpoints/timesformer_divST_8x32x1_15e_kinetics400_rgb-3f8e5d03.pth
05/15 11:47:39 - mmengine - WARNING - The value of random seed in the checkpoint "0" is different from the value in `randomness` config "3407"
05/15 11:47:39 - mmengine - WARNING - The dataset metainfo from the resumed checkpoint is different from the current training dataset, please check the correctness of the checkpoint or the training dataset.
Traceback (most recent call last):
  File "tools/train.py", line 135, in <module>
    main()
  File "tools/train.py", line 131, in main
    runner.train()
  File "/home/lcg/.conda/envs/mmlab/lib/python3.8/site-packages/mmengine/runner/runner.py", line 1694, in train
    self.load_or_resume()
  File "/home/lcg/.conda/envs/mmlab/lib/python3.8/site-packages/mmengine/runner/runner.py", line 1640, in load_or_resume
    self.resume(resume_from)
  File "/home/lcg/.conda/envs/mmlab/lib/python3.8/site-packages/mmengine/runner/runner.py", line 1999, in resume
    self.message_hub.load_state_dict(checkpoint['message_hub'])
KeyError: 'message_hub'

**Comment by ElviraLL** [comment]
Hey, I saw that you closed this issue on May16, did you solve the issue?
