### ISSUE TITLE
[Feature] Regarding I3D with resnet 152

### ISSUE THREAD

**Issue by commandermsv** [open-mmlab/mmaction2#2488]
### What is the problem this feature will solve?

Hi all,
Hope you all are doing great,
I have a query that existing I3d codes provided in "i3d_imagenet-pretrained-r50_8xb8-32x2x1-100e_kinetics400-rgb.py" is using resnet-50. I want to use resnet-152 in place of resnet-50. I have tried to change depth=152, but getting below error:

AssertionError Traceback (most recent call last)
[/usr/local/lib/python3.10/dist-packages/mmengine/registry/build_functions.py](https://localhost:8080/#) in build_from_cfg(cfg, registry, default_args)
121 else:
--> 122 obj = obj_cls(**args) # type: ignore
123

13 frames
[/content/mmaction2/mmaction/models/backbones/resnet3d.py](https://localhost:8080/#) in init(self, depth, pretrained, stage_blocks, pretrained2d, in_channels, num_stages, base_channels, out_indices, spatial_strides, temporal_strides, dilations, conv1_kernel, conv1_stride_s, conv1_stride_t, pool1_stride_s, pool1_stride_t, with_pool1, with_pool2, style, frozen_stages, inflate, inflate_style, conv_cfg, norm_cfg, act_cfg, norm_eval, with_cp, non_local, non_local_cfg, zero_init_residual, init_cfg, kwargs)
505 planes = self.base_channels * 2i
--> 506 res_layer = self.make_res_layer(
507 self.block,

[/content/mmaction2/mmaction/models/backbones/resnet3d.py](https://localhost:8080/#) in make_res_layer(block, inplanes, planes, blocks, spatial_stride, temporal_stride, dilation, style, inflate, inflate_style, non_local, non_local_cfg, norm_cfg, act_cfg, conv_cfg, with_cp, **kwargs)
594 else (non_local,) * blocks
--> 595 assert len(inflate) == blocks and len(non_local) == blocks
596 downsample = None

AssertionError:

During handling of the above exception, another exception occurred:

AssertionError Traceback (most recent call last)
[/usr/local/lib/python3.10/dist-packages/mmengine/registry/build_functions.py](https://localhost:8080/#) in build_from_cfg(cfg, registry, default_args)
121 else:
--> 122 obj = obj_cls(**args) # type: ignore
123

[/content/mmaction2/mmaction/models/recognizers/base.py](https://localhost:8080/#) in init(self, backbone, cls_head, neck, train_cfg, test_cfg, data_preprocessor)
82 else:
---> 83 self.backbone = MODELS.build(backbone)
84

[/usr/local/lib/python3.10/dist-packages/mmengine/registry/registry.py](https://localhost:8080/#) in build(self, cfg, *args, **kwargs)
547 """
--> 548 return self.build_func(cfg, *args, **kwargs, registry=self)
549

[/usr/local/lib/python3.10/dist-packages/mmengine/registry/build_functions.py](https://localhost:8080/#) in build_model_from_cfg(cfg, registry, default_args)
249 else:
--> 250 return build_from_cfg(cfg, registry, default_args)
251

[/usr/local/lib/python3.10/dist-packages/mmengine/registry/build_functions.py](https://localhost:8080/#) in build_from_cfg(cfg, registry, default_args)
143 obj_cls.module.split('.')) # type: ignore
--> 144 raise type(e)(
145 f'class {obj_cls.__name__} in ' # type: ignore

AssertionError: class ResNet3d in mmaction/models/backbones/resnet3d.py:

During handling of the above exception, another exception occurred:

AssertionError Traceback (most recent call last)
in <cell line: 9>()
7
8 # build the runner from config
----> 9 runner = Runner.from_cfg(cfg)
10
11 # start training

[/usr/local/lib/python3.10/dist-packages/mmengine/runner/runner.py](https://localhost:8080/#) in from_cfg(cls, cfg)
437 """
438 cfg = copy.deepcopy(cfg)
--> 439 runner = cls(
440 model=cfg['model'],
441 work_dir=cfg['work_dir'],

[/usr/local/lib/python3.10/dist-packages/mmengine/runner/runner.py](https://localhost:8080/#) in init(self, model, work_dir, train_dataloader, val_dataloader, test_dataloader, train_cfg, val_cfg, test_cfg, auto_scale_lr, optim_wrapper, param_scheduler, val_evaluator, test_evaluator, default_hooks, custom_hooks, data_preprocessor, load_from, resume, launcher, env_cfg, log_processor, log_level, visualizer, default_scope, randomness, experiment_name, cfg)
404 # Merge the data_preprocessor to model config.
405 model.setdefault('data_preprocessor', data_preprocessor)
--> 406 self.model = self.build_model(model)
407 # wrap model
408 self.model = self.wrap_model(

[/usr/local/lib/python3.10/dist-packages/mmengine/runner/runner.py](https://localhost:8080/#) in build_model(self, model)
811 return model
812 elif isinstance(model, dict):
--> 813 model = MODELS.build(model)
814 return model # type: ignore
815 else:

[/usr/local/lib/python3.10/dist-packages/mmengine/registry/registry.py](https://localhost:8080/#) in build(self, cfg, *args, **kwargs)
546 >>> model = MODELS.build(cfg)
547 """
--> 548 return self.build_func(cfg, *args, **kwargs, registry=self)
549
550 def _add_child(self, registry: 'Registry') -> None:

[/usr/local/lib/python3.10/dist-packages/mmengine/registry/build_functions.py](https://localhost:8080/#) in build_model_from_cfg(cfg, registry, default_args)
248 return Sequential(*modules)
249 else:
--> 250 return build_from_cfg(cfg, registry, default_args)
251
252

[/usr/local/lib/python3.10/dist-packages/mmengine/registry/build_functions.py](https://localhost:8080/#) in build_from_cfg(cfg, registry, default_args)
142 cls_location = '/'.join(
143 obj_cls.module.split('.')) # type: ignore
--> 144 raise type(e)(
145 f'class {obj_cls.__name__} in ' # type: ignore
146 f'{cls_location}.py: {e}')

AssertionError: class Recognizer3D in mmaction/models/recognizers/recognizer3d.py: class ResNet3d in mmaction/models/backbones/resnet3d.py:

Please help in this regards,
Thanks in advance

### What is the feature?

Will able I3D use with resnet152.

**Comment by commandermsv** [comment]
Still same issue after modifying,







05/22 09:23:25 - mmengine - INFO - 
------------------------------------------------------------
System environment:
    sys.platform: linux
    Python: 3.10.11 (main, Apr  5 2023, 14:15:10) [GCC 9.4.0]
    CUDA available: True
    numpy_random_seed: 739924279
    GPU 0: Tesla T4
    CUDA_HOME: /usr/local/cuda
    NVCC: Cuda compilation tools, release 11.8, V11.8.89
    GCC: x86_64-linux-gnu-gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
    PyTorch: 2.0.1+cu118
    PyTorch compiling details: PyTorch built with:
  - GCC 9.3
  - C++ Version: 201703
  - Intel(R) oneAPI Math Kernel Library Version 2022.2-Product Build 20220804 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.7.3 (Git Hash 6dbeffbae1f23cbbeae17adb7b5b13f1f37c080e)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - LAPACK is enabled (usually provided by MKL)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 11.8
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86;-gencode;arch=compute_90,code=sm_90
  - CuDNN 8.7
  - Magma 2.6.1
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.8, CUDNN_VERSION=8.7.0, CXX_COMPILER=/opt/rh/devtoolset-9/root/usr/bin/c++, CXX_FLAGS= -D_GLIBCXX_USE_CXX11_ABI=0 -fabi-version=11 -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -DNDEBUG -DUSE_KINETO -DLIBKINETO_NOROCTRACER -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -O2 -fPIC -Wall -Wextra -Werror=return-type -Werror=non-virtual-dtor -Werror=bool-operation -Wnarrowing -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wunused-local-typedefs -Wno-unused-parameter -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Werror=cast-function-type -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_DISABLE_GPU_ASSERTS=ON, TORCH_VERSION=2.0.1, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=1, USE_NNPACK=ON, USE_OPENMP=ON, USE_ROCM=OFF, 

    TorchVision: 0.15.2+cu118
    OpenCV: 4.7.0
    MMEngine: 0.7.3

Runtime environment:
    cudnn_benchmark: False
    mp_cfg: {'mp_start_method': 'fork', 'opencv_num_threads': 0}
    dist_cfg: {'backend': 'nccl'}
    seed: None
    Distributed launcher: none
    Distributed training: False
    GPU number: 1
------------------------------------------------------------

05/22 09:23:26 - mmengine - INFO - Config:
model = dict(
    type='Recognizer3D',
    backbone=dict(
        type='ResNet3d',
        pretrained2d=True,
        pretrained='torchvision://resnet50',
        depth=152,
        conv1_kernel=(5, 7, 7),
        conv1_stride_t=2,
        pool1_stride_t=2,
        conv_cfg=dict(type='Conv3d'),
        norm_eval=False,
        inflate=((1, 1, 1), (1, 0, 1, 0), (1, 0, 1, 0, 1, 0), (0, 1, 0)),
        zero_init_residual=False,
        non_local=((0, 0, 0), (0, 0, 0, 0, 0, 1, 0, 1),
                   (0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1), (0, 0,
                                                                      0)),
        non_local_cfg=dict(
            sub_sample=True,
            use_scale=False,
            norm_cfg=dict(type='BN3d', requires_grad=True),
            mode='dot_product')),
    cls_head=dict(
        type='I3DHead',
        num_classes=2,
        in_channels=2048,
        spatial_type='avg',
        dropout_ratio=0.5,
        init_std=0.01,
        average_clips='prob'),
    data_preprocessor=dict(
        type='ActionDataPreprocessor',
        mean=[123.675, 116.28, 103.53],
        std=[58.395, 57.12, 57.375],
        format_shape='NCTHW'))
train_cfg = dict(
    type='EpochBasedTrainLoop', max_epochs=10, val_begin=1, val_interval=1)
val_cfg = dict(type='ValLoop')
test_cfg = dict(type='TestLoop')
param_scheduler = [
    dict(
        type='MultiStepLR',
        begin=0,
        end=100,
        by_epoch=True,
        milestones=[40, 80],
        gamma=0.1)
]
optim_wrapper = dict(
    optimizer=dict(
        type='SGD', lr=7.8125e-05, momentum=0.9, weight_decay=0.0001),
    clip_grad=dict(max_norm=40, norm_type=2))
default_scope = 'mmaction'
default_hooks = dict(
    runtime_info=dict(type='RuntimeInfoHook'),
    timer=dict(type='IterTimerHook'),
    logger=dict(type='LoggerHook', interval=20, ignore_last=False),
    param_scheduler=dict(type='ParamSchedulerHook'),
    checkpoint=dict(
        type='CheckpointHook', interval=5, save_best='auto', max_keep_ckpts=5),
    sampler_seed=dict(type='DistSamplerSeedHook'),
    sync_buffers=dict(type='SyncBuffersHook'))
env_cfg = dict(
    cudnn_benchmark=False,
    mp_cfg=dict(mp_start_method='fork', opencv_num_threads=0),
    dist_cfg=dict(backend='nccl'))
log_processor = dict(type='LogProcessor', window_size=20, by_epoch=True)
vis_backends = [dict(type='LocalVisBackend')]
visualizer = dict(
    type='ActionVisualizer', vis_backends=[dict(type='LocalVisBackend')])
log_level = 'INFO'
load_from = './checkpoints/tsn_r50_1x1x3_100e_kinetics400_rgb_20200614-e508be42.pth'
resume = False
dataset_type = 'VideoDataset'
data_root = 'kinetics400_tiny/train/'
data_root_val = 'kinetics400_tiny/val/'
ann_file_train = 'kinetics400_tiny/kinetics_tiny_train_video.txt'
ann_file_val = 'kinetics400_tiny/kinetics_tiny_val_video.txt'
ann_file_test = 'data/kinetics400/kinetics400_val_list_videos.txt'
file_client_args = dict(io_backend='disk')
train_pipeline = [
    dict(type='DecordInit', io_backend='disk'),
    dict(type='SampleFrames', clip_len=32, frame_interval=2, num_clips=1),
    dict(type='DecordDecode'),
    dict(type='Resize', scale=(-1, 256)),
    dict(
        type='MultiScaleCrop',
        input_size=224,
        scales=(1, 0.8),
        random_crop=False,
        max_wh_scale_gap=0),
    dict(type='Resize', scale=(224, 224), keep_ratio=False),
    dict(type='Flip', flip_ratio=0.5),
    dict(type='FormatShape', input_format='NCTHW'),
    dict(type='PackActionInputs')
]
val_pipeline = [
    dict(type='DecordInit', io_backend='disk'),
    dict(
        type='SampleFrames',
        clip_len=32,
        frame_interval=2,
        num_clips=1,
        test_mode=True),
    dict(type='DecordDecode'),
    dict(type='Resize', scale=(-1, 256)),
    dict(type='CenterCrop', crop_size=224),
    dict(type='FormatShape', input_format='NCTHW'),
    dict(type='PackActionInputs')
]
test_pipeline = [
    dict(type='DecordInit', io_backend='disk'),
    dict(
        type='SampleFrames',
        clip_len=32,
        frame_interval=2,
        num_clips=10,
        test_mode=True),
    dict(type='DecordDecode'),
    dict(type='Resize', scale=(-1, 256)),
    dict(type='ThreeCrop', crop_size=256),
    dict(type='FormatShape', input_format='NCTHW'),
    dict(type='PackActionInputs')
]
train_dataloader = dict(
    batch_size=2,
    num_workers=2,
    persistent_workers=True,
    sampler=dict(type='DefaultSampler', shuffle=True),
    dataset=dict(
        type='VideoDataset',
        ann_file='kinetics400_tiny/kinetics_tiny_train_video.txt',
        data_prefix=dict(video='kinetics400_tiny/train/'),
        pipeline=[
            dict(type='DecordInit', io_backend='disk'),
            dict(
                type='SampleFrames',
                clip_len=32,
                frame_interval=2,
                num_clips=1),
            dict(type='DecordDecode'),
            dict(type='Resize', scale=(-1, 256)),
            dict(
                type='MultiScaleCrop',
                input_size=224,
                scales=(1, 0.8),
                random_crop=False,
                max_wh_scale_gap=0),
            dict(type='Resize', scale=(224, 224), keep_ratio=False),
            dict(type='Flip', flip_ratio=0.5),
            dict(type='FormatShape', input_format='NCTHW'),
            dict(type='PackActionInputs')
        ]))
val_dataloader = dict(
    batch_size=2,
    num_workers=2,
    persistent_workers=True,
    sampler=dict(type='DefaultSampler', shuffle=False),
    dataset=dict(
        type='VideoDataset',
        ann_file='kinetics400_tiny/kinetics_tiny_val_video.txt',
        data_prefix=dict(video='kinetics400_tiny/val/'),
        pipeline=[
            dict(type='DecordInit', io_backend='disk'),
            dict(
                type='SampleFrames',
                clip_len=32,
                frame_interval=2,
                num_clips=1,
                test_mode=True),
            dict(type='DecordDecode'),
            dict(type='Resize', scale=(-1, 256)),
            dict(type='CenterCrop', crop_size=224),
            dict(type='FormatShape', input_format='NCTHW'),
            dict(type='PackActionInputs')
        ],
        test_mode=True))
test_dataloader = dict(
    batch_size=1,
    num_workers=2,
    persistent_workers=True,
    sampler=dict(type='DefaultSampler', shuffle=False),
    dataset=dict(
        type='VideoDataset',
        ann_file='kinetics400_tiny/kinetics_tiny_val_video.txt',
        data_prefix=dict(video='kinetics400_tiny/val/'),
        pipeline=[
            dict(type='DecordInit', io_backend='disk'),
            dict(
                type='SampleFrames',
                clip_len=32,
                frame_interval=2,
                num_clips=10,
                test_mode=True),
            dict(type='DecordDecode'),
            dict(type='Resize', scale=(-1, 256)),
            dict(type='ThreeCrop', crop_size=256),
            dict(type='FormatShape', input_format='NCTHW'),
            dict(type='PackActionInputs')
        ],
        test_mode=True))
val_evaluator = dict(type='AccMetric')
test_evaluator = dict(type='AccMetric')
auto_scale_lr = dict(enable=False, base_batch_size=64)
work_dir = './tutorial_exps'

---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
[/usr/local/lib/python3.10/dist-packages/mmengine/registry/build_functions.py](https://localhost:8080/#) in build_from_cfg(cfg, registry, default_args)
    121             else:
--> 122                 obj = obj_cls(**args)  # type: ignore
    123 

13 frames
[/content/mmaction2/mmaction/models/backbones/resnet3d.py](https://localhost:8080/#) in __init__(self, depth, pretrained, stage_blocks, pretrained2d, in_channels, num_stages, base_channels, out_indices, spatial_strides, temporal_strides, dilations, conv1_kernel, conv1_stride_s, conv1_stride_t, pool1_stride_s, pool1_stride_t, with_pool1, with_pool2, style, frozen_stages, inflate, inflate_style, conv_cfg, norm_cfg, act_cfg, norm_eval, with_cp, non_local, non_local_cfg, zero_init_residual, init_cfg, **kwargs)
    505             planes = self.base_channels * 2**i
--> 506             res_layer = self.make_res_layer(
    507                 self.block,

[/content/mmaction2/mmaction/models/backbones/resnet3d.py](https://localhost:8080/#) in make_res_layer(block, inplanes, planes, blocks, spatial_stride, temporal_stride, dilation, style, inflate, inflate_style, non_local, non_local_cfg, norm_cfg, act_cfg, conv_cfg, with_cp, **kwargs)
    594             else (non_local,) * blocks
--> 595         assert len(inflate) == blocks and len(non_local) == blocks
    596         downsample = None

AssertionError: 

During handling of the above exception, another exception occurred:

AssertionError                            Traceback (most recent call last)
[/usr/local/lib/python3.10/dist-packages/mmengine/registry/build_functions.py](https://localhost:8080/#) in build_from_cfg(cfg, registry, default_args)
    121             else:
--> 122                 obj = obj_cls(**args)  # type: ignore
    123 

[/content/mmaction2/mmaction/models/recognizers/base.py](https://localhost:8080/#) in __init__(self, backbone, cls_head, neck, train_cfg, test_cfg, data_preprocessor)
     82         else:
---> 83             self.backbone = MODELS.build(backbone)
     84 

[/usr/local/lib/python3.10/dist-packages/mmengine/registry/registry.py](https://localhost:8080/#) in build(self, cfg, *args, **kwargs)
    547         """
--> 548         return self.build_func(cfg, *args, **kwargs, registry=self)
    549 

[/usr/local/lib/python3.10/dist-packages/mmengine/registry/build_functions.py](https://localhost:8080/#) in build_model_from_cfg(cfg, registry, default_args)
    249     else:
--> 250         return build_from_cfg(cfg, registry, default_args)
    251 

[/usr/local/lib/python3.10/dist-packages/mmengine/registry/build_functions.py](https://localhost:8080/#) in build_from_cfg(cfg, registry, default_args)
    143                 obj_cls.__module__.split('.'))  # type: ignore
--> 144             raise type(e)(
    145                 f'class `{obj_cls.__name__}` in '  # type: ignore

AssertionError: class `ResNet3d` in mmaction/models/backbones/resnet3d.py: 

During handling of the above exception, another exception occurred:

AssertionError                            Traceback (most recent call last)
[<ipython-input-25-470ae90dd31e>](https://localhost:8080/#) in <cell line: 9>()
      7 
      8 # build the runner from config
----> 9 runner = Runner.from_cfg(cfg)
     10 
     11 # start training

[/usr/local/lib/python3.10/dist-packages/mmengine/runner/runner.py](https://localhost:8080/#) in from_cfg(cls, cfg)
    437         """
    438         cfg = copy.deepcopy(cfg)
--> 439         runner = cls(
    440             model=cfg['model'],
    441             work_dir=cfg['work_dir'],

[/usr/local/lib/python3.10/dist-packages/mmengine/runner/runner.py](https://localhost:8080/#) in __init__(self, model, work_dir, train_dataloader, val_dataloader, test_dataloader, train_cfg, val_cfg, test_cfg, auto_scale_lr, optim_wrapper, param_scheduler, val_evaluator, test_evaluator, default_hooks, custom_hooks, data_preprocessor, load_from, resume, launcher, env_cfg, log_processor, log_level, visualizer, default_scope, randomness, experiment_name, cfg)
    404             # Merge the data_preprocessor to model config.
    405             model.setdefault('data_preprocessor', data_preprocessor)
--> 406         self.model = self.build_model(model)
    407         # wrap model
    408         self.model = self.wrap_model(

[/usr/local/lib/python3.10/dist-packages/mmengine/runner/runner.py](https://localhost:8080/#) in build_model(self, model)
    811             return model
    812         elif isinstance(model, dict):
--> 813             model = MODELS.build(model)
    814             return model  # type: ignore
    815         else:

[/usr/local/lib/python3.10/dist-packages/mmengine/registry/registry.py](https://localhost:8080/#) in build(self, cfg, *args, **kwargs)
    546             >>> model = MODELS.build(cfg)
    547         """
--> 548         return self.build_func(cfg, *args, **kwargs, registry=self)
    549 
    550     def _add_child(self, registry: 'Registry') -> None:

[/usr/local/lib/python3.10/dist-packages/mmengine/registry/build_functions.py](https://localhost:8080/#) in build_model_from_cfg(cfg, registry, default_args)
    248         return Sequential(*modules)
    249     else:
--> 250         return build_from_cfg(cfg, registry, default_args)
    251 
    252 

[/usr/local/lib/python3.10/dist-packages/mmengine/registry/build_functions.py](https://localhost:8080/#) in build_from_cfg(cfg, registry, default_args)
    142             cls_location = '/'.join(
    143                 obj_cls.__module__.split('.'))  # type: ignore
--> 144             raise type(e)(
    145                 f'class `{obj_cls.__name__}` in '  # type: ignore
    146                 f'{cls_location}.py: {e}')

AssertionError: class `Recognizer3D` in mmaction/models/recognizers/recognizer3d.py: class `ResNet3d` in mmaction/models/backbones/resnet3d.py:

**Comment by hukkai** [comment]
@commandermsv The reason is that you need the same modification for `inflate`

**Comment by commandermsv** [comment]
Ohhh,
I missed that
Thank you for your help!!!

**Comment by commandermsv** [comment]
Hi,
Can you please provide inflate argument for Resnet101?
like for Resnet50 its inflate=((1, 1, 1), (1, 0, 1, 0), (1, 0, 1, 0, 1, 0), (0, 1, 0)),

It will be helpful if you can provide me any link or doc, so i can check with other configs also.

Thanks...

**Comment by hukkai** [comment]
@commandermsv I am sorry there is no doc to describe the inflate argument for a specific arch, since it is your choice to decide that.
If you want the meaning of `inflate`, it is whether to use temporal kernels for each residual blocks. For resnet101, there are 3, 4, 23, 3 blocks in each residual stages. So you need a tuple of 4 tuples, and the lengths of the 4 tuples are 3, 4, 23, 3. You can also use inflate=(1, 1, 1, 1), which means using temporal kernels for all blocks in each residual stage.
