### ISSUE TITLE
Label Map

### ISSUE THREAD

**Issue by edanherrera** [open-mmlab/mmaction2#2492]
Hi, i have a question.
I tried to train MMaction to recognize only one action, but when running it recognizes more than action.
So I don't know if it could be training that was not correct or it could be something related to the labelmap and if  it is that i would like to know if is possible create a custom label map for the recognition.

I used the following command for training
`!python tools/train.py configs/task/method/my_custom_config.py --validate --gpus 0`
Output:
![image](https://github.com/open-mmlab/mmaction2/assets/91446757/965ff91b-c347-4aa6-95db-d2d9f31be97b)
Command for Test
`!python tools/test.py configs/task/method/my_custom_config.py  work_dirs/tsn_r50_video_dense_1x1x8_100e_kinetics400_rgb/best_top1_acc_epoch_5.pth --out resultonnx2.json --cfg-options gpu_ids=[0]`
Output:
![image](https://github.com/open-mmlab/mmaction2/assets/91446757/843b204d-2d06-4c0e-acd1-8f875825dfd8)
And test with the demo
`!python demo/demo.py configs/task/method/my_custom_config.py \
    work_dirs/tsn_r50_video_dense_1x1x8_100e_kinetics400_rgb/best_top1_acc_epoch_5.pth \
    tools/data/custom/video69.avi tools/data/kinetics/label_map_k400.txt --out-filename demo/demo_out.mp4`
Output:
![image](https://github.com/open-mmlab/mmaction2/assets/91446757/3a3bf7df-99fb-4d59-8731-a4e927bf0266)

**Comment by hukkai** [comment]
@edanherrera Can you put your config file?

**Comment by edanherrera** [comment]
Course, this is my config file
![image](https://github.com/open-mmlab/mmaction2/assets/91446757/9933a636-f774-4ad2-b50d-12a5ac87730f)
![image](https://github.com/open-mmlab/mmaction2/assets/91446757/be7c7c2d-994e-4d5f-a976-c52e007de51a)
`_base_ = [
    '../../_base_/models/tsn_r50.py', '../../_base_/schedules/sgd_100e.py',
    '../../_base_/default_runtime.py'
]


# dataset settings
dataset_type = 'VideoDataset'
data_root = 'tools/data/custom'
data_root_val = 'tools/data/custom'
ann_file_train = 'tools/data/custom/test.txt'
ann_file_val = 'tools/data/custom/test.txt'
ann_file_test = 'tools/data/custom/test.txt'
img_norm_cfg = dict(
    mean=[123.675, 116.28, 103.53], std=[58.395, 57.12, 57.375], to_bgr=False)
train_pipeline = [
    dict(type='DecordInit'),
    dict(type='DenseSampleFrames', clip_len=1, frame_interval=1, num_clips=35),
    dict(type='DecordDecode'),
    dict(
        type='MultiScaleCrop',
        input_size=224,
        scales=(1, 0.875, 0.75, 0.66),
        random_crop=False,
        max_wh_scale_gap=1),
    dict(type='Resize', scale=(224, 224), keep_ratio=False),
    dict(type='Flip', flip_ratio=0.5),
    dict(type='Normalize', **img_norm_cfg),
    dict(type='FormatShape', input_format='NCHW'),
    dict(type='Collect', keys=['imgs', 'label'], meta_keys=[]),
    dict(type='ToTensor', keys=['imgs', 'label'])
]
val_pipeline = [
    dict(type='DecordInit'),
    dict(
        type='DenseSampleFrames',
        clip_len=1,
        frame_interval=1,
        num_clips=8,
        test_mode=True),
    dict(type='DecordDecode'),
    dict(type='Resize', scale=(-1, 256)),
    dict(type='CenterCrop', crop_size=224),
    dict(type='Normalize', **img_norm_cfg),
    dict(type='FormatShape', input_format='NCHW'),
    dict(type='Collect', keys=['imgs', 'label'], meta_keys=[]),
    dict(type='ToTensor', keys=['imgs'])
]
test_pipeline = [
    dict(type='DecordInit'),
    dict(
        type='DenseSampleFrames',
        clip_len=1,
        frame_interval=1,
        num_clips=8,
        test_mode=True),
    dict(type='DecordDecode'),
    dict(type='Resize', scale=(-1, 256)),
    dict(type='TenCrop', crop_size=224),
    dict(type='Normalize', **img_norm_cfg),
    dict(type='FormatShape', input_format='NCHW'),
    dict(type='Collect', keys=['imgs', 'label'], meta_keys=[]),
    dict(type='ToTensor', keys=['imgs'])
]
data = dict(
    videos_per_gpu=1,
    workers_per_gpu=1,
    val_dataloader=dict(videos_per_gpu=1),
    test_dataloader=dict(videos_per_gpu=1),
    train=dict(
        type=dataset_type,
        ann_file=ann_file_train,
        data_prefix=data_root,
        pipeline=train_pipeline),
    val=dict(
        type=dataset_type,
        ann_file=ann_file_val,
        data_prefix=data_root_val,
        pipeline=val_pipeline),
    test=dict(
        type=dataset_type,
        ann_file=ann_file_test,
        data_prefix=data_root_val,
        pipeline=test_pipeline))
evaluation = dict(
    interval=1, metrics=['top_k_accuracy', 'mean_class_accuracy'])

# runtime settings
work_dir = './work_dirs/test/'`

**Comment by hukkai** [comment]
@edanherrera You need to modify the model head configs to have only one class.

**Comment by edanherrera** [comment]
@hukkai I'm sorry, could you tell me how I do that?

**Comment by tkdguraa** [comment]
You should modifying the "num_classes" in the "mmaction2/configs/_base_/models/tsn_r50.py" into 2.
