### ISSUE TITLE
[Feature] Hello, in addition to the following algorithms, can other models based on bone point action recognition algorithms be used in your visualization program? For example, HD-GCN or Cstr-gcn  ST-GCN (AAAI'2018) 2s- agcn (CVPR'2019) posec3d (CVPR'2022) stgcn ++ (ArXiv'2022)

### ISSUE THREAD

**Issue by ya-92626** [open-mmlab/mmaction2#2493]
### What is the problem this feature will solve?

Hello, in addition to the following algorithms,
ST-GCN (AAAI'2018) 2s- agcn (CVPR'2019) posec3d (CVPR'2022) stgcn ++ (ArXiv'2022)
 can other models based on bone point action recognition algorithms be used in your visualization program? 
For example, HD-GCN (      https://github.com/Jho-Yonsei/HD-GCN     )         or 
 CTR-GCN(  https://github.com/Uason-Chen/CTR-GCN  ).

### What is the feature?

Hello, in addition to the following algorithms,
ST-GCN (AAAI'2018) 2s- agcn (CVPR'2019) posec3d (CVPR'2022) stgcn ++ (ArXiv'2022)
 can other models based on bone point action recognition algorithms be used in your visualization program? 
For example, HD-GCN (      https://github.com/Jho-Yonsei/HD-GCN     )         or 
 CTR-GCN(  https://github.com/Uason-Chen/CTR-GCN  ).

**Comment by Dai-Wenxun** [comment]
of course
