### ISSUE TITLE
[Bug] About K400 dataset

### ISSUE THREAD

**Issue by kaiw7** [open-mmlab/mmaction2#2504]
### Branch

main branch (1.x version, such as `v1.0.0`, or `dev-1.x` branch)

### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmaction2/issues) and [Discussions](https://github.com/open-mmlab/mmaction2/discussions) but cannot get the expected help.
- [X] I have read the [documentation](https://mmaction2.readthedocs.io/en/latest/) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version](https://github.com/open-mmlab/mmaction2).

### Environment

Hi, I try to extract the audio stream from K400, but it shows that the video files don't contain any audio stream. Could I know whether the audios are removed from video files? Many thanks.

### Describe the bug

About audio stream in K400 dataset

**Comment by hukkai** [comment]
It depends on how you get the dataset. If you downloaded it from Youtube, some videos contain audio. If you downloaded it from a third party source, the video might be resized and then the audio may be missing.
