### ISSUE TITLE
How to use the skeleton-based recognition models in projects to run the demo?

### ISSUE THREAD

**Issue by ya-92626** [open-mmlab/mmaction2#2527]
### What is the problem this feature will solve?

Hello, may I ask that the skeleton in the configs file only includes "2s-agcn, posec3d, stgcn, STGCN ++". Does that mean that "ctrgcn" in projects cannot use "demo" to display from video to skeletal action recognition? If so, what should I do?

I hope to get your reply. It is very important to me. Thank you very much!

### What is the feature?

Hello, may I ask that the skeleton in the configs file only includes "2s-agcn, posec3d, stgcn, STGCN ++". Does that mean that "ctrgcn" in projects cannot use "demo" to display from video to skeletal action recognition? If so, what should I do?

I hope to get your reply. It is very important to me. Thank you very much!

**Comment by Dai-Wenxun** [comment]
- step1: delele this [line](https://github.com/open-mmlab/mmaction2/blob/main/projects/ctrgcn/configs/ctrgcn_8xb16-joint-u100-80e_ntu60-xsub-keypoint-2d.py#L3) in ctrgcn ntu60_2d config.
- step2: add `import projects.ctrgcn.models` in `demo/demo_skeleton.py` to import ctrgcn model.
- step3: run the following command:
```shell
python demo/demo_skeleton.py 
demo/demo_skeleton.mp4
demo/demo_skeleton_out.mp4
--config
projects/ctrgcn/configs/ctrgcn_8xb16-joint-u100-80e_ntu60-xsub-keypoint-2d.py
--checkpoint
https://download.openmmlab.com/mmaction/v1.0/projects/ctrgcn/ctrgcn_8xb16-joint-u100-80e_ntu60-xsub-keypoint-2d/ctrgcn_8xb16-joint-u100-80e_ntu60-xsub-keypoint-2d_20230308-7aba454e.pth
--det-config
demo/demo_configs/faster-rcnn_r50_fpn_2x_coco_infer.py
--det-checkpoint
checkpoint/faster_rcnn_r50_fpn_2x_coco_bbox_mAP-0.384_20200504_210434-a5d8aa15.pth
--det-score-thr
0.9
--det-cat-id
0
--pose-config
demo/demo_configs/td-hm_hrnet-w32_8xb64-210e_coco-256x192_infer.py
--pose-checkpoint
checkpoint/hrnet_w32_coco_256x192-c78dce93_20200708.pth
--label-map
tools/data/skeleton/label_map_ntu60.txt
```
`Note` that I have changed the paths of det-checkpoint  and pose-checkpoint.

**Comment by ya-92626** [comment]
> * 步骤1：在CTRGCN ntu60_2d配置中对这一[行](https://github.com/open-mmlab/mmaction2/blob/main/projects/ctrgcn/configs/ctrgcn_8xb16-joint-u100-80e_ntu60-xsub-keypoint-2d.py#L3)进行Delele。
> * 第 2 步：添加以导入 CTRGCN 模型。`import projects.ctrgcn.models``demo/demo_skeleton.py`
> * 步骤3：运行以下命令：
> 
> ```shell
> python demo/demo_skeleton.py 
> demo/demo_skeleton.mp4
> demo/demo_skeleton_out.mp4
> --config
> projects/ctrgcn/configs/ctrgcn_8xb16-joint-u100-80e_ntu60-xsub-keypoint-2d.py
> --checkpoint
> https://download.openmmlab.com/mmaction/v1.0/projects/ctrgcn/ctrgcn_8xb16-joint-u100-80e_ntu60-xsub-keypoint-2d/ctrgcn_8xb16-joint-u100-80e_ntu60-xsub-keypoint-2d_20230308-7aba454e.pth
> --det-config
> demo/demo_configs/faster-rcnn_r50_fpn_2x_coco_infer.py
> --det-checkpoint
> checkpoint/faster_rcnn_r50_fpn_2x_coco_bbox_mAP-0.384_20200504_210434-a5d8aa15.pth
> --det-score-thr
> 0.9
> --det-cat-id
> 0
> --pose-config
> demo/demo_configs/td-hm_hrnet-w32_8xb64-210e_coco-256x192_infer.py
> --pose-checkpoint
> checkpoint/hrnet_w32_coco_256x192-c78dce93_20200708.pth
> --label-map
> tools/data/skeleton/label_map_ntu60.txt
> ```
> 
> `Note`我已经更改了det检查点和姿势检查点的路径。

thank you！！！very much！！！ i will try right away
