### ISSUE TITLE
[Docs] The documentation is not clear about how to training kinetics 400 

### ISSUE THREAD

**Issue by aixiaodewugege** [open-mmlab/mmaction2#2528]
### The doc issue

The downloaded annotation file is as follow:
![image](https://github.com/open-mmlab/mmaction2/assets/47085237/abd0f5b9-746b-44dd-99fc-7b5d2d674925)

How to convert it to the format that you suggested in guide? Or is it necessary?
![image](https://github.com/open-mmlab/mmaction2/assets/47085237/85ae375a-7682-4fbd-ad02-c890a0d8904d)

**Comment by Dai-Wenxun** [comment]
You could follow this [guide](https://github.com/open-mmlab/mmaction2/tree/main/tools/data/kinetics#readme) to prepare the K400 dataset and the data format is mandatory.

**Comment by cir7** [comment]
You can try to download from [OpenDataLab](https://opendatalab.com/Kinetics-400), this version can be directly used in MMAction2.
