### ISSUE TITLE
Regarding I3d using Resnet3d.

### ISSUE THREAD

**Issue by commandermsv** [open-mmlab/mmaction2#2535]
### What is the problem this feature will solve?

I3d implementation using Resnet3d.
Im little bit confused while checking the implementation of I3d using Resnet3d.
The issue is resnet3d.py is already having 3d convolution, and I3D uses Inflate(upgrading 2d kernels to 3d kernels). When kernels mentioned in resnet3d.py are already in 3d then how inflation is happening? Then inflate will have no effect, because kernels are already in 3d.

model = dict(
    type='Recognizer3D',
    backbone=dict(
        type='ResNet3d',
        pretrained2d=True,
        pretrained='torchvision://resnet50',
        depth=50,
        conv1_kernel=(5, 7, 7),
        conv1_stride_t=2,
        pool1_stride_t=2,
        conv_cfg=dict(type='Conv3d'),
        norm_eval=False,
        **inflate=((1, 1, 1), (1, 0, 1, 0), (1, 0, 1, 0, 1, 0), (0, 1, 0)),**
        zero_init_residual=False),
        
        
        Inflate wil have no effect, so can you clarify how actually I3d is implementing inflate in resnet3d. I tried to figure this out using provided docs, but not able to find out any satisfiable answer.
        
        
        Thanks in Advance....
        

### What is the feature?

I3d implementation using Resnet3d.

**Comment by cir7** [comment]
you could refer to the source code [here](https://github.com/open-mmlab/mmaction2/blob/1485998e0dfde4dc369fcf072fe74dfe79d49e32/mmaction/models/backbones/resnet3d.py#L378) to see that how the argument works
