### ISSUE TITLE
[Docs] Demo example

### ISSUE THREAD

**Issue by LairChen** [open-mmlab/mmaction2#2550]
### The doc issue

When will the demo example (like [demo_gradcam.](https://github.com/open-mmlab/mmaction2/blob/0.x/demo/demo_gradcam.py)) officially be added in the last version (0.x)?

**Comment by cir7** [comment]
Hi, @LairChen 
Do you mean to add to the main branch? the script had been implemented, located at [here](https://github.com/open-mmlab/mmaction2/blob/main/tools/visualizations/vis_cam.py).
