### ISSUE TITLE
Cuda out of Memory when doing Demo

### ISSUE THREAD

**Issue by itruonghai** [open-mmlab/mmaction2#257]
I try to test my model on a RawFrame directory, as the code below (Note that I train my model on Colab with V100 and 16GB Vram)
```import torch

from mmaction.apis import init_recognizer, inference_recognizer

config_file = '/content/mmaction2/configs/recognition/csn/ircsn_ig65m_pretrained_bnfrozen_r152_32x2x1_58e_kinetics400_rgb.py'
# download the checkpoint from model zoo and put it in `checkpoints/`
checkpoint_file = '/content/drive/My Drive/0TruongHai/Sport/epoch_52.pth'

# assign the desired device.
device = 'cuda:0' # or 'cpu'
device = torch.device(device)

 # build the model from a config file and a checkpoint file
model = init_recognizer(config_file, checkpoint_file, device=device, use_frames=True)

# test rawframe directory of a single video and show the result:
video = '/content/mmaction2/mydata/val/Defensive_Backhand_Backspin/3197874210_00176_00340/'
labels = '/content/label.txt'
results = inference_recognizer(model, video, labels, use_frames=True)

# show the results
print(f'The top-5 labels with corresponding scores are:')
for result in results:
    print(f'{result[0]}: ', result[1])
```
But it return cuda out of memory, I also set video_per_gpu to 1 but it didn't work. Here is the error
```
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-1-b3e9746cc7a0> in <module>()
     17 video = '/content/mmaction2/mydata/val/Defensive_Backhand_Backspin/3197874210_00176_00340/'
     18 labels = '/content/label.txt'
---> 19 results = inference_recognizer(model, video, labels, use_frames=True)
     20 
     21 # show the results

17 frames
/usr/local/lib/python3.6/dist-packages/torch/nn/functional.py in batch_norm(input, running_mean, running_var, weight, bias, training, momentum, eps)
   1921     return torch.batch_norm(
   1922         input, weight, bias, running_mean, running_var,
-> 1923         training, momentum, eps, torch.backends.cudnn.enabled
   1924     )
   1925 

RuntimeError: CUDA out of memory. Tried to allocate 3.75 GiB (GPU 0; 15.75 GiB total capacity; 9.25 GiB already allocated; 2.62 GiB free; 12.07 GiB reserved in total by PyTorch)
```

**Comment by innerlee** [comment]
@dreamerlin does this relate to https://github.com/open-mmlab/mmaction2/pull/250

**Comment by dreamerlin** [comment]
> @dreamerlin does this relate to #250 ?

No, since it is a demo for a single video. See [here](https://github.com/open-mmlab/mmaction2/blob/master/mmaction/apis/inference.py#L108)

**Comment by dreamerlin** [comment]
> I try to test my model on a RawFrame directory, as the code below (Note that I train my model on Colab with V100 and 16GB Vram)
> 
> ```
> 
> from mmaction.apis import init_recognizer, inference_recognizer
> 
> config_file = '/content/mmaction2/configs/recognition/csn/ircsn_ig65m_pretrained_bnfrozen_r152_32x2x1_58e_kinetics400_rgb.py'
> # download the checkpoint from model zoo and put it in `checkpoints/`
> checkpoint_file = '/content/drive/My Drive/0TruongHai/Sport/epoch_52.pth'
> 
> # assign the desired device.
> device = 'cuda:0' # or 'cpu'
> device = torch.device(device)
> 
>  # build the model from a config file and a checkpoint file
> model = init_recognizer(config_file, checkpoint_file, device=device, use_frames=True)
> 
> # test rawframe directory of a single video and show the result:
> video = '/content/mmaction2/mydata/val/Defensive_Backhand_Backspin/3197874210_00176_00340/'
> labels = '/content/label.txt'
> results = inference_recognizer(model, video, labels, use_frames=True)
> 
> # show the results
> print(f'The top-5 labels with corresponding scores are:')
> for result in results:
>     print(f'{result[0]}: ', result[1])
> ```
> 
> But it return cuda out of memory, I also set video_per_gpu to 1 but it didn't work. Here is the error
> 
> ```
> ---------------------------------------------------------------------------
> RuntimeError                              Traceback (most recent call last)
> <ipython-input-1-b3e9746cc7a0> in <module>()
>      17 video = '/content/mmaction2/mydata/val/Defensive_Backhand_Backspin/3197874210_00176_00340/'
>      18 labels = '/content/label.txt'
> ---> 19 results = inference_recognizer(model, video, labels, use_frames=True)
>      20 
>      21 # show the results
> 
> 17 frames
> /usr/local/lib/python3.6/dist-packages/torch/nn/functional.py in batch_norm(input, running_mean, running_var, weight, bias, training, momentum, eps)
>    1921     return torch.batch_norm(
>    1922         input, weight, bias, running_mean, running_var,
> -> 1923         training, momentum, eps, torch.backends.cudnn.enabled
>    1924     )
>    1925 
> 
> RuntimeError: CUDA out of memory. Tried to allocate 3.75 GiB (GPU 0; 15.75 GiB total capacity; 9.25 GiB already allocated; 2.62 GiB free; 12.07 GiB reserved in total by PyTorch)
> ```

Since `CSN` is a huge model, you can try to change `test_pipeline` to a light one. 

For example, `num_clips=16` => `num_clips=1`; `dict(type='ThreeCrop', crop_size=256)` -> `dict(type='CenterCrop', crop_size=224)`

**Comment by innerlee** [comment]
random thought: adding a `demo_pipeline` for realtime demo, what do u think

**Comment by dreamerlin** [comment]
> random thought: adding a `demo_pipeline` for realtime demo, what do u think

Yeah, we may add a default `demo_pipeline` for each model respectively. That will help to avoid some cases when performing demo like OOM

**Comment by itruonghai** [comment]
@innerlee @dreamerlin  thank you. It's ok now
