### ISSUE TITLE
demo_video_structuralize.py file is missing in the latest mmaction2 package

### ISSUE THREAD

**Issue by mitraavi** [open-mmlab/mmaction2#2586]
### Branch

main branch (1.x version, such as `v1.0.0`, or `dev-1.x` branch)

### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmaction2/issues) and [Discussions](https://github.com/open-mmlab/mmaction2/discussions) but cannot get the expected help.
- [X] I have read the [documentation](https://mmaction2.readthedocs.io/en/latest/) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version](https://github.com/open-mmlab/mmaction2).

### Environment

file missing in the latest version

### Describe the bug

**demo_video_structuralize.py** file is missing in the latest mmaction2 package, which was part of demo package version mmaction2 0.24.1. Demo file was an example of **skeleton-based action detection** on videos

**Comment by cir7** [comment]
We have migrated the demo to 1.x version, you could have a try.
