### ISSUE TITLE
[Bug] 代码中未初始化权重导致数值过大

### ISSUE THREAD

**Issue by bityangtian** [open-mmlab/mmaction2#2609]
### Branch

main branch (1.x version, such as `v1.0.0`, or `dev-1.x` branch)

### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmaction2/issues) and [Discussions](https://github.com/open-mmlab/mmaction2/discussions) but cannot get the expected help.
- [X] I have read the [documentation](https://mmaction2.readthedocs.io/en/latest/) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version](https://github.com/open-mmlab/mmaction2).

### Environment

main

### Describe the bug

mmaction2/mmaction/models/similarity/adapters.py中的TransformerAdapter未调用自己的init_weights，导致self.positional_embedding仍然是由torch.empty生成的，数值会过大导致难以训练，建议在init的最后加上一行self.init_weights()

**Comment by cir7** [comment]
The `TransformerAdapter` inherits from `mmengine.model.BaseModule`, which would call `init_weights()` recursively by  `mmengine.runner.Runner` in the training process.
