### ISSUE TITLE
[Bug] How is the prediction result of 10 num_clips calculated during the test?

### ISSUE THREAD

**Issue by KunLiam** [open-mmlab/mmaction2#2611]
### Branch

main branch (1.x version, such as `v1.0.0`, or `dev-1.x` branch)

### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmaction2/issues) and [Discussions](https://github.com/open-mmlab/mmaction2/discussions) but cannot get the expected help.
- [X] I have read the [documentation](https://mmaction2.readthedocs.io/en/latest/) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version](https://github.com/open-mmlab/mmaction2).

### Environment

I have installed all the required environments for the 1.x version

### Describe the bug

**First,** I list my test_pipeline：
`test_pipeline = [
    dict(
        type='SampleFrames',
        clip_len=8,
        frame_interval=8,
        num_clips=10,
        test_mode=True),
    dict(type='RawFrameDecode', **file_client_args),
    dict(type='Resize', scale=(-1, 256)),
    dict(type='ThreeCrop', crop_size=256),
    dict(type='FormatShape', input_format='NCTHW'),
    dict(type='PackActionInputs')
]`
**Secondly**, if there are 10 num_clips in the test process, how is the prediction result calculated? Are you averaging 10 num_clips or are you voting? I want to see the internal code of the test, which package can I find the specific code in?
**Finally**, I would appreciate it if you could answer my questions!

### Additional information

I tried to dbug and found that the mmengine package was used during the test, but I couldn't find where the code was actually calculated. I found the test_step function in the test_time_aug.py file, and the code is as follows:
`    def test_step(self, data):
        """Get predictions of each enhanced data, a multiple predictions.

        Args:
            data (DataBatch): Enhanced data batch sampled from dataloader.

        Returns:
            MergedDataSamples: Merged prediction.
        """
        data_list: Union[List[dict], List[list]]
        if isinstance(data, dict):
            num_augs = len(data[next(iter(data))])
            data_list = [{key: value[idx]
                          for key, value in data.items()}
                         for idx in range(num_augs)]
        elif isinstance(data, (tuple, list)):
            num_augs = len(data[0])
            data_list = [[_data[idx] for _data in data]
                         for idx in range(num_augs)]
        else:
            raise TypeError('data given by dataLoader should be a dict, '
                            f'tuple or a list, but got {type(data)}')

        predictions = []
        print('*********predictions', predictions)
        for data in data_list:  # type: ignore
            predictions.append(self.module.test_step(data))
        return self.merge_preds(list(zip(*predictions)))  # type: ignore`
However, I added a print statement and found that no information was printed when I tested it. My test instructions are as follows:
`CUDA_DEVICE_ORDER=PCI_BUS_ID CUDA_VISIBLE_DEVICES=0  PORT=29501 tools/dist_test.sh configs/recognition/tpn/tpn-slowonly_imagenet-pretrained-r50_8xb8-8x8x1-150e_kinetics400-rgb.py work_dirs/tpn-slowonly_imagenet-pretrained-r50_8xb8-8x8x1-150e_kinetics400-rgb/best_acc_top1_epoch_63.pth 1`
I hope you can help solve my problem, thank you!

**Comment by KunLiam** [comment]
It has been four days, please answer my questions. Thank you!

**Comment by cir7** [comment]
similar issue to #2641
