### ISSUE TITLE
[Bug] config error

### ISSUE THREAD

**Issue by Ishihara-Masabumi** [open-mmlab/mmaction2#2616]
### Branch

main branch (1.x version, such as `v1.0.0`, or `dev-1.x` branch)

### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmaction2/issues) and [Discussions](https://github.com/open-mmlab/mmaction2/discussions) but cannot get the expected help.
- [X] I have read the [documentation](https://mmaction2.readthedocs.io/en/latest/) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version](https://github.com/open-mmlab/mmaction2).

### Environment

python 3.8
mmaction2 1.1.0

### Describe the bug

When I run a test script, the following error occurred.

### Reproduces the problem - command or script

python tools/test.py configs/recognition/mvit/mvit-small-p244_16x4x1_kinetics400-rgb.py     checkpoints/SOME_CHECKPOINT.pth --dump result.pkl

### Reproduces the problem - error message

Traceback (most recent call last):
  File "tools/test.py", line 118, in <module>
    main()
  File "tools/test.py", line 93, in main
    cfg = Config.fromfile(args.config)
  File "/home/dl/miniconda3/envs/openmmlab/lib/python3.8/site-packages/mmengine/config/config.py", line 455, in fromfile
    lazy_import is None and not Config._is_lazy_import(filename):
  File "/home/dl/miniconda3/envs/openmmlab/lib/python3.8/site-packages/mmengine/config/config.py", line 1651, in _is_lazy_import
    with open(filename, encoding='utf-8') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'configs/recognition/mvit/mvit-small-p244_16x4x1_kinetics400-rgb.py'

**Comment by Dai-Wenxun** [comment]
[mvit-small-p244_32xb16-16x4x1-200e_kinetics400-rgb.py](https://github.com/open-mmlab/mmaction2/blob/main/configs/recognition/mvit/mvit-small-p244_32xb16-16x4x1-200e_kinetics400-rgb.py)

**Comment by cir7** [comment]
similar issue to https://github.com/open-mmlab/mmaction2/issues/2617
