### ISSUE TITLE
Show the results for each frame in demo.py

### ISSUE THREAD

**Issue by edanherrera** [open-mmlab/mmaction2#2627]
### Branch

main branch (1.x version, such as `v1.0.0`, or `dev-1.x` branch)

### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmaction2/issues) and [Discussions](https://github.com/open-mmlab/mmaction2/discussions) but cannot get the expected help.
- [X] I have read the [documentation](https://mmaction2.readthedocs.io/en/latest/) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version](https://github.com/open-mmlab/mmaction2).
- 
### Describe the bug

I have been using the demo.py but I have noticed that it only records the highest label at the end of the video.
I would like to know if i can print the result of these frame by frame.

**Comment by cir7** [comment]
Hi, @edanherrera 
currently, the demo only infers once for the input video, you could refer to the long video demo [here](https://github.com/open-mmlab/mmaction2/pull/2602/files#diff-fe1a59ce12953b3ef8a31159b55ec903a939e9c84e6e47f101d51c2800ee047b), which may be what you want.
