### ISSUE TITLE
[Bug] FormatShape bug for optical flow

### ISSUE THREAD

**Issue by makecent** [open-mmlab/mmaction2#2630]
### Branch

main branch (1.x version, such as `v1.0.0`, or `dev-1.x` branch)

### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmaction2/issues) and [Discussions](https://github.com/open-mmlab/mmaction2/discussions) but cannot get the expected help.
- [X] I have read the [documentation](https://mmaction2.readthedocs.io/en/latest/) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version](https://github.com/open-mmlab/mmaction2).

### Environment

N/A

### Describe the bug

As the **Normalization operation** now is moved from the pipeline to the **data preprocessor**. The necessary processing step for optical flows, which is originally in the `Normalize` pipeline in the older version, is missing:

In **older version**, the `Normalize` pipeline **stacks** the `flow_x` and `flow_y`:

https://github.com/open-mmlab/mmaction2/blob/02d5d9b84a66914a69fc2e569029c4fe1b81ebf3/mmaction/datasets/pipelines/augmentations.py#L1207-L1232

In `1.x` version, the stacking operation is lost as the `Normalize` pipeline is no longer used. Causing the dimension error in `FormatShape`:
```terminal
  File "/home/louis/miniconda3/envs/mmengine/lib/python3.8/site-packages/mmaction/datasets/transforms/formatting.py", line 260, in transform
    imgs = np.transpose(imgs, (0, 1, 5, 2, 3, 4))
  File "<__array_function__ internals>", line 180, in transpose
  File "/home/louis/.local/lib/python3.8/site-packages/numpy/core/fromnumeric.py", line 660, in transpose
    return _wrapfunc(a, 'transpose', axes)
  File "/home/louis/.local/lib/python3.8/site-packages/numpy/core/fromnumeric.py", line 57, in _wrapfunc
    return bound(*args, **kwds)
ValueError: axes don't match array
```

**Comment by Dai-Wenxun** [comment]
For the formatting of the optical flow, you need to set the `input_format ` of `FormatShape ` as `NCHW_Flow`, as shown [here](https://github.com/open-mmlab/mmaction2/blob/main/mmaction/datasets/transforms/formatting.py#L307). The code of this branch will stack the optical flow at the last dimension as in your #2631.

**Comment by Dai-Wenxun** [comment]
For the normalization of optical flow, I think we can implement it as follows: 

```python

clip_len = 5

model = dict(
    type='Recognizer2D',
    backbone=dict(...),
    cls_head=dict(...),
    data_preprocessor=dict(
        type='ActionDataPreprocessor',
        mean=[128, 128] *clip_len,
        std=[128, 128] * clip_len,
        format_shape='NCHW_flow'))

train_pipeline = [
    dict(type='SampleFrames', clip_len=clip_len, frame_interval=1, num_clips=3),
   ....
    dict(type='FormatShape', input_format='NCHW_Flow'),
   ...
]
```

**Comment by Dai-Wenxun** [comment]
Since the `NCHW_flow` is not defined in the `ActionDataPreprocessor`, could you please help us to implement it in action2? The functionality of NCHW_flow should be equivalent to that of NCHW.

**Comment by Dai-Wenxun** [comment]
of course, if you have any better ideas to process the optical flow, feel free to let me know. Thank u, bro!

**Comment by makecent** [comment]
@Dai-Wenxun I am a little confused about the `NCHW_Flow`: why it does not contain a `T` dimension? In my understanding, the format of optical flows should be the same with RGB frames , i.e., using the `NCTHW`, albeit C=3 for RGB, and C=2 for Flow.

As for a better idea, I think my PR #2631 is simple and effective. To work with optical flows, we can just simply set the FormatShape as `NCTHW` like RGBs, and as for the normalization, we can set a 2D mean = [x, x] and 2D std=[x, x]. I have tested my PR on working optical flows and it worked.

**Comment by makecent** [comment]
I have never used the `NCHW` FormatShape, so I guess the `NCHW_Flow` is the flow-version of `NCHW` FormatShape. If that is the case, then we may  at least need an addtional `NCTHW_Flow`
