### ISSUE TITLE
The problem about GPU-Util

### ISSUE THREAD

**Issue by hero-y** [open-mmlab/mmaction2#264]
When I train the network (for example, I3D, slowfast), the GPU-Util index has been fluctuating, sometimes even 0%. Is this normal？

**Comment by innerlee** [comment]
wild guess:  it is an io issue

**Comment by hero-y** [comment]
How can I deal with it?  When I train the mmdetection, the GPU-Utile is normal, but when I train the mmaction2, it's not normal.

**Comment by innerlee** [comment]
actions requires much more resource than det.

diagnose steps:
1. check cpu usage: `htop`, to see if cpus are busy
2. check disk usage: `nmon` and press `d`, to see if ssd/hdd are busy

if cpu is busy, then the bottleneck is pre-processing
if disk is busy, then the bottleneck is io

**Comment by dreamerlin** [comment]
How is it going now ? @hero-y

**Comment by hero-y** [comment]
Thank you for your waiting. I try to load the data from the ssd. During training, through nmon tool, the CPU utilization rate is about 60% , and the disk is not busy. GPU still fluctuates, so is the bottleneck  cpu?

**Comment by SuX97** [comment]
> Thank you for your waiting. I try to load the data from the ssd. During training, through nmon tool, the CPU utilization rate is about 60% , and the disk is not busy. GPU still fluctuates, so is the bottleneck cpu?

How is it going, @hero-y ?

Another diagnose method may be check the `wa` stats in htop. If it takes the rest of your CPU time, say 20~40%, it may still be an io issue.
