### ISSUE TITLE
[Docs] BMN Dataset Building Issue: clip_feature_extraction.py Producing Incorrect Feature Dimensions

### ISSUE THREAD

**Issue by YancyGuo** [open-mmlab/mmaction2#2655]
### The doc issue

I followed the [documentation](https://github.com/open-mmlab/mmaction2/blob/main/tools/data/activitynet/README.md) and went with Option 2 to build my custom dataset for BMN. When I reached step 6, I used tools\misc\clip_feature_extraction.py to extract features from my dataset. However, I encountered an issue: it only generates the pred_scores for the entire video, rather than the frame_score for each individual frame.

According to the guidelines, it should produce a 100-t X 400-d feature for Action Detection. But the clip_feature_extraction.py script is only producing a 1-t X 400-d feature.

**Comment by makecent** [comment]
Did you set the `--dump-score`?

**Comment by YancyGuo** [comment]
> Did you set the `--dump-score`?

Yes, and based on my understanding, `--dump-score` will produce scores for multiple frames rather than a single frame. This is the reason why it can't produce 'frame_len'-t X 400-d.

**Comment by sunshineluoxh** [comment]
Hi Yancy , meeting the same problem to you , can you show me how to deal with it in the end ? Looking forward to your reply, thanks !

**Comment by YancyGuo** [comment]
> Hi Yancy , meeting the same problem to you , can you show me how to deal with it in the end ? Looking forward to your reply, thanks !

Hi there,

Thank you for reaching out. Unfortunately, I haven't been able to resolve this issue myself either. I'm sorry that I can't be of more assistance at this moment. If I come across any solution in the future, I'll be sure to share it.
