### ISSUE TITLE
results['filename'] = results['frame_dir'] + '.mp4' KeyError: 'frame_dir'

### ISSUE THREAD

**Issue by rouge012** [open-mmlab/mmaction2#2660]
### Branch

main branch (1.x version, such as `v1.0.0`, or `dev-1.x` branch)

### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmaction2/issues) and [Discussions](https://github.com/open-mmlab/mmaction2/discussions) but cannot get the expected help.
- [X] I have read the [documentation](https://mmaction2.readthedocs.io/en/latest/) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version](https://github.com/open-mmlab/mmaction2).

### Environment

python demo/demo_skeleton.py demo/demo_skeleton.mp4 demo/demo_skeleton_out.mp4 \
    --config configs/skeleton/posec3d/rgbpose_conv3d/rgbpose_conv3d.py \
    --checkpoint checkpoints/rgbpose_conv3d_20230301-ac7b0e77.pth \
    --det-config demo/demo_configs/faster-rcnn_r50_fpn_2x_coco_infer.py \
    --det-checkpoint checkpoints/faster_rcnn_r50_fpn_2x_coco_bbox_mAP-0.384_20200504_210434-a5d8aa15.pth \
    --det-score-thr 0.9 \
    --det-cat-id 0 \
    --pose-config demo/demo_configs/td-hm_hrnet-w32_8xb64-210e_coco-256x192_infer.py \
    --pose-checkpoint checkpoints/hrnet_w32_coco_256x192-c78dce93_20200708.pth \
    --label-map tools/data/skeleton/label_map_ntu60.txt

### Describe the bug

results['filename'] = results['frame_dir'] + '.mp4'
KeyError: 'frame_dir'

### Additional information

Hello! When I run the code below, I encounter an error. Even when I change the dataset_type, there are still other errors. How can I resolve this?"

**Comment by cir7** [comment]
@rouge012 Currently, the demo only supports skeleton-only config, while `rgbpose_conv3d.py` takes rgb and skeleton as input.

**Comment by rouge012** [comment]
which demo supports rgbpose_conv3d.py?



---- Replied Message ----
| From | ***@***.***> |
| Date | 08/30/2023 10:04 |
| To | ***@***.***> |
| Cc | ***@***.***>***@***.***> |
| Subject | Re: [open-mmlab/mmaction2] results['filename'] = results['frame_dir'] + '.mp4' KeyError: 'frame_dir' (Issue #2660) |

@rouge012 Currently, the demo only supports skeleton-only config, while rgbpose_conv3d.py takes rgb and skeleton as input.

**Comment by cir7** [comment]
currently, no demo supports inference on ` rgbpose_conv3d.py`
