### ISSUE TITLE
[Docs] Definition of the output_scores provided by each action model

### ISSUE THREAD

**Issue by CarmelaCalabrese** [open-mmlab/mmaction2#2662]
### The doc issue

I am trying to work with a temporal version of ActionCLIP and I'd like to compare my results with a different approach. Specifically, I want to analyse the detected actions in contrast with those I obtained through the Spatiotemporal Action demo but I have a problem in action threshold definition to be consistent. While from the ActionCLIP page I understand that the score represents a probability and is the result of a softmax function, I don't understand the multilabel classification approach used in Spatiotemporal Action because the sum of all the scores is not 1. What does that score value represent? Is it a probability as outcome of a "One-vesus-All" multilabel classification approach? Or are those values all related each other in some way?

This clarification in the documentation can help.

**Comment by cir7** [comment]
For normal action detection models, it's a typical multi-label classification problem, the output score of each class is the "One-versus-All" probability. While ActionClip is actually a retrieval problem, the final score is the softmax result among all classes, similar to single-label classification. 
In your situation, I think that directly skipping the softmax, using the video-text similarity as the probability, and setting a threshold to classify can also work.

**Comment by CarmelaCalabrese** [comment]
Thank you for this clarification.
