### ISSUE TITLE
how to use omnisource config?where?

### ISSUE THREAD

**Issue by yangzhaojason** [open-mmlab/mmaction2#272]

**Comment by kennymckormick** [comment]
Currently, we only released OmniSource checkpoints, you can test those checkpoints on Kinetics or use them for pretraining on downstream tasks. We will release OmniSource data, training code, and training configs soon (in the next version).

**Comment by dreamerlin** [comment]
The training code and training configs are provided. https://github.com/open-mmlab/mmaction2/pull/242, https://github.com/open-mmlab/mmaction2/pull/296
