### ISSUE TITLE
How to extract frame-level flow feature directly from untrimmed videos without building raw frames?

### ISSUE THREAD

**Issue by DgntYang** [open-mmlab/mmaction2#2749]
### The doc issue

NOTE:
1. I have searched related issues but cannot get the expected help.
2. I have read docs in this repo for a long time.

Hi there,
I am trying to extracting rgb and flow features for some large-scale datasets like(DAHLIA). However, due to disk capacity limitations, I am unable to save all raw frames locally.

I noted that this toolbox can load and decode videos using tools like decord (tsn_extract_video_feat_config.py), but didnot find it possible to extract flow feature from decoded untrimmed videos (with no function calls for denseflow during my debug). Are there any solutions can help sovling my  dilemma?

**Comment by HaichenHe** [comment]
Hi, I'm also looking for an answer to this question, can you share how you solved it?

**Comment by DgntYang** [comment]
Hello, I did't solve it but bought a 2T mechanical hard disk. Then I used denseflow to extract flow feature from local flow frames.
