### ISSUE TITLE
Problems with Preparing dataset sthv1 

### ISSUE THREAD

**Issue by yuhuixu1993** [open-mmlab/mmaction2#275]
Thanks for your error report and we appreciate it a lot.

**Checklist**
1. I have searched related issues but cannot get the expected help.
2. The bug has not been fixed in the latest version.

**Describe the bug**
Hi, thanks for your contribution. Recently I try to run the experiments of TSM on sthv1. When preparing the dataset, the totalframes are missing in the generated rawframes list.
[sthv1_train_list_rawframes.txt](https://github.com/open-mmlab/mmaction2/files/5429824/sthv1_train_list_rawframes.txt)

**Reproduction**
1. What command or script did you run?
```
bash generate_rawframes_filelist.sh

```
2. Did you make any modifications on the code or config? Did you understand what you have modified?
None
3. What dataset did you use?
sthv1
**Environment**

1. Please run `PYTHONPATH=${PWD}:$PYTHONPATH python mmaction/utils/collect_env.py` to collect necessary environment information and paste it here.
2. You may add addition that may be helpful for locating the problem, such as
    - How you installed PyTorch [e.g., pip, conda, source]
    - Other environment variables that may be related (such as `$PATH`, `$LD_LIBRARY_PATH`, `$PYTHONPATH`, etc.)

**Error traceback**
If applicable, paste the error traceback here.
```
A placeholder for traceback.
```

**Bug fix**
If you have already identified the reason, you can provide the information here. If you are willing to create a PR to fix it, please also leave a comment here and that would be much appreciated!

**Comment by dreamerlin** [comment]
Thanks for your report, we are preparing a fix [here](https://github.com/open-mmlab/mmaction2/pull/278)
