### ISSUE TITLE
Problems: raw frames filelist of sthv2

### ISSUE THREAD

**Issue by yuhuixu1993** [open-mmlab/mmaction2#276]
Thanks for your error report and we appreciate it a lot.

**Checklist**
1. I have searched related issues but cannot get the expected help.
2. The bug has not been fixed in the latest version.

**Describe the bug**
Thanks for your contribution!  After the rawframes are extracted by open CV, I can not generate the rawframes file list.![1603463415(1)](https://user-images.githubusercontent.com/17807154/97016744-1b39b880-151b-11eb-8997-58b237fb9b3a.png)

**Reproduction**
1. What command or script did you run?
```
bash generate_rawframes_filelist.sh 

```
2. Did you make any modifications on the code or config? Did you understand what you have modified?
3. What dataset did you use?
sthv2

**Environment**

1. Please run `PYTHONPATH=${PWD}:$PYTHONPATH python mmaction/utils/collect_env.py` to collect necessary environment information and paste it here.
2. You may add addition that may be helpful for locating the problem, such as
    - How you installed PyTorch [e.g., pip, conda, source]
    - Other environment variables that may be related (such as `$PATH`, `$LD_LIBRARY_PATH`, `$PYTHONPATH`, etc.)

**Error traceback**
If applicable, paste the error traceback here.
```
A placeholder for traceback.
```

**Bug fix**
If you have already identified the reason, you can provide the information here. If you are willing to create a PR to fix it, please also leave a comment here and that would be much appreciated!

**Comment by dreamerlin** [comment]
Thanks for your report, we are preparing a fix [here](https://github.com/open-mmlab/mmaction2/pull/278)
