### ISSUE TITLE
ssn train error

### ISSUE THREAD

**Issue by chengweige** [open-mmlab/mmaction2#290]
RuntimeError: Given input size: (2048x1x7). Calculated output size: (2048x-5x1). Output size is too small

i print the imgs shape at ssn forward_train
    def forward_train(self, imgs, proposal_scale_factor, proposal_type,
                      proposal_labels, reg_targets, **kwargs):
        """Define the computation performed at every call when training."""
        print('imgs.shape 1', imgs.shape)
        imgs = imgs.reshape((-1, self.in_channels) + imgs.shape[4:])
        print('imgs.shape 2', imgs.shape)

imgs.shape 1 torch.Size([1, 8, 9, 3, 17, 224])
imgs.shape 2 torch.Size([72, 3, 17, 224])

so why height is 17?

**Comment by tony2016uestc** [comment]
Based on `$MMACTION2/configs/localization/ssn_r50_450e_thumos14_rgb_train.py`, I print the imgs shape at the same place.

imgs.shape 1 torch.Size([1, 8, 9, 3, 224, 224])
imgs.shape 2 torch.Size([72, 3, 224, 224])

**Comment by curiosity654** [comment]
I believe this error is due to raw frames extracted using OpenCV script is not compatible with the `keep_ratio` in Resize transform, I switched it to False and everything works, except for some minor difference in accuracy.
