### ISSUE TITLE
 Errors: when training and testing the c3d_sports1m_16x1x1_45e_ucf101_rgb model : RuntimeError: Given input size: (512x4x1x14). Calculated output size: (512x2x0x7). Output size is too small

### ISSUE THREAD

**Issue by shuyuandeqipa** [open-mmlab/mmaction2#293]
Thanks for your error report and we appreciate it a lot.

**Checklist**
1. I have searched related issues but cannot get the expected help.
2. The bug has not been fixed in the latest version.

**Describe the bug**

**Reproduction**
1. What command or script did you run?
```
A placeholder for the command.
```
2. Did you make any modifications on the code or config? Did you understand what you have modified?
3. What dataset did you use?

**Environment**

1. Please run `PYTHONPATH=${PWD}:$PYTHONPATH python mmaction/utils/collect_env.py` to collect necessary environment information and paste it here.
2. You may add addition that may be helpful for locating the problem, such as
    - How you installed PyTorch [e.g., pip, conda, source]
    - Other environment variables that may be related (such as `$PATH`, `$LD_LIBRARY_PATH`, `$PYTHONPATH`, etc.)

**Error traceback**
If applicable, paste the error traceback here.
```
A placeholder for traceback.
```

**Bug fix**
If you have already identified the reason, you can provide the information here. If you are willing to create a PR to fix it, please also leave a comment here and that would be much appreciated!

**Comment by dreamerlin** [comment]
The issue description seems ambiguous, can you provide more details?

**Comment by congee524** [comment]
Have you modified the c3d config file？How you handle the dataset? Could you provide more details？

**Comment by shuyuandeqipa** [comment]
Thank you!  The problem is solved. 
I do not modify the c3d config file.  
There are some problems when we prepare the ucf101 train and val data sets. 
 The python code of this project is good!

**Comment by zehuichen123** [comment]
@shuyuandeqipa  Hi, I got the same problem with this error. Would you please share your solution? Thanks!

**Comment by zehuichen123** [comment]
@dreamerlin  There are two videos whose size is not (240, 320). Hence it will generate two (97, 112) samples, which can not be pooled correctly at pool_4 layer in backbone. Currently my solution is to modify keep_ratio at Resize from True to False to avoid generating such samples. I think a more elegant way should be considered, such as padding.

**Comment by mbilalshaikh** [comment]
Hi everyone, I got the same error. Would you please share the solution?

**Comment by AndssY** [comment]
I got the same error, modify keep_ratio at Resize can avoid this error, but the acc of model would decrease by 10%(83% -> 72%), so is there any better way?

**Comment by Sibyl233** [comment]
I got the same error,any solution?

**Comment by aksenventwo** [comment]
`python build_rawframes.py ../../data/ucf101/videos/ ../../data/ucf101/rawframes/ --task rgb --level 2  --ext avi --new-width 320 --new-height 240` is ok, and test results：

```
top1_acc: 0.8319
top5_acc: 0.9590
```
