### ISSUE TITLE
decord  SampleFrames start_index=1 bug

### ISSUE THREAD

**Issue by irvingzhang0512** [open-mmlab/mmaction2#30]
i try to train kinetics with [this config](https://github.com/open-mmlab/mmaction2/blob/master/configs/recognition/i3d/i3d_r50_video_32x2x1_100e_kinetics400_rgb.py), but get `index out of range` error.
after some debugging, i find that this bug is caused by default setting `start_index = 1` in `SampleFrames`.
I think `start_index` should be `0` for `decord`.

**Comment by innerlee** [comment]
yes decord starts with 0. thanks for the report

**Comment by dreamerlin** [comment]
we are preparing a fix now https://github.com/open-mmlab/mmaction2/pull/31
