### ISSUE TITLE
Iteration Plan - Nov 2020

### ISSUE THREAD

**Issue by dreamerlin** [open-mmlab/mmaction2#300]
MMAction2 v0.8 will be released soon. Now it's time to plan for the next iteration, i.e. v0.9.
This will be a one-month iteration and our focus in this iteration is to enrich the supported tasks. We will add support for Spatio-Temporal Action Detction and enrich algorithms/models for action recognition.

**Algorithms**:
- [ ] ~~FastRCNN on AVA (https://github.com/open-mmlab/mmaction2/pull/351)~~
- [ ] ~~SlowFast on AVA~~
- [ ] ~~MOC (https://github.com/open-mmlab/mmaction2/pull/308, https://github.com/open-mmlab/mmaction2/pull/326)~~
- [ ] ~~AVSlowFast (https://github.com/open-mmlab/mmaction2/pull/355)~~
- [ ] ~~TAM (https://github.com/open-mmlab/mmaction2/pull/304)~~
- [ ] ~~SCSampler (https://github.com/open-mmlab/mmaction2/pull/381)~~
- [x] GYM RGB+Flow baseline (https://github.com/open-mmlab/mmaction2/pull/336)

**Datasets**:
- [x] GYM (https://github.com/open-mmlab/mmaction2/pull/331)

**Tools**:

**Misc**:

---

Deferred:

- [ ] FastRCNN on AVA (https://github.com/open-mmlab/mmaction2/pull/351)
- [ ] MOC (https://github.com/open-mmlab/mmaction2/pull/308, https://github.com/open-mmlab/mmaction2/pull/326)
- [ ] TAM (https://github.com/open-mmlab/mmaction2/pull/304)
- [ ] SCSampler (https://github.com/open-mmlab/mmaction2/pull/381)
- [ ] SlowFast on AVA
- [ ] AVSlowFast (https://github.com/open-mmlab/mmaction2/pull/355)

**Comment by innerlee** [comment]
It would be great to give their project links to each item

**Comment by kennymckormick** [comment]
Cannot find the trained model of AVSlowFast, something wrong? @dreamerlin

**Comment by innerlee** [comment]
Checkout https://github.com/open-mmlab/mmaction2/blob/6dc009bdf0b276afc4b19f2bad936b2d20f7b695/configs/recognition_audio/audioonly/README.md
