### ISSUE TITLE
Could you please share Kinetics datasets with cloud disk?

### ISSUE THREAD

**Issue by MakeCent** [open-mmlab/mmaction2#305]
**Describe the feature**
Downloading Kinetics is so time-consuming and we have to handle various problems such as lots of missing videos, rejected by youtube because of too many attempts, large disk space need for uncropped videos... After struggling with the downloading for several weeks, I still failed to download a relatively complete kinetics-400.

Since we always tend to use temporally and spatially cropped videos, therefore the total size of the final Kinetics won't be too large, about 500G I guess. Could you please share your downloaded kinetics-400 with cloud disks like Baidu Yun or Dropbox?
This can save me a lot of time and I believe this will also be very helpful for anyone who hasn't downloaded the dataset. Thank you very much.

**Motivation**
It is very convenient when people want to use mmaction2 on kinetics while haven't downloaded the datasets.

**Comment by innerlee** [comment]
dup of https://github.com/open-mmlab/mmaction2/issues/137
