### ISSUE TITLE
Validation error with distributed training setting with Pytorch 1.7.0

### ISSUE THREAD

**Issue by ZichenMiao** [open-mmlab/mmaction2#313]
RuntimeError: replicas_[0].size() == rebuilt_param_indices_.size() INTERNAL ASSERT FAILED at "/pytorch/torch/csrc/distributed/c10d/reducer.cpp":1326, please report a bug to PyTorch. re
built parameter indices size is not same as original model parameters size.161 versus 89999
Traceback (most recent call last):
  File "./tools/train.py", line 178, in <module>
    main()                                    
  File "./tools/train.py", line 174, in main
    meta=meta)                                
  File "/home/mzc/mmaction2/mmaction/apis/train.py", line 141, in train_model
    runner.run(data_loaders, cfg.workflow, cfg.total_epochs, **runner_kwargs)
  File "/home/mzc/.pyenv/versions/3.7.0/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 125, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/home/mzc/.pyenv/versions/3.7.0/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 54, in train
    self.call_hook('after_train_epoch')
  File "/home/mzc/.pyenv/versions/3.7.0/lib/python3.7/site-packages/mmcv/runner/base_runner.py", line 307, in call_hook
    getattr(hook, fn_name)(self)
  File "/home/mzc/mmaction2/mmaction/core/evaluation/eval_hooks.py", line 265, in after_train_epoch
    gpu_collect=self.gpu_collect)
  File "/home/mzc/mmaction2/mmaction/apis/test.py", line 68, in multi_gpu_test
    result = model(return_loss=False, **data)
  File "/home/mzc/.pyenv/versions/3.7.0/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/mzc/.pyenv/versions/3.7.0/lib/python3.7/site-packages/torch/nn/parallel/distributed.py", line 606, in forward
    if self.reducer._rebuild_buckets():

I have solved this bug by downgrading pytorch to 1.6.0. I don't think the mmcv works well with the newest pytorch 1.7.0.

**Comment by SuX97** [comment]
Could you please describe your config, cmd line, and mmcv version for us to reproduce it? Thanks!

**Comment by mitming** [comment]
This error is happened at #320 , same error can be seen at [here](https://github.com/open-mmlab/mmaction2/issues/320#issuecomment-724561079), I also think that mmcv cannot support pytorch 1.7.0 well

**Comment by SuX97** [comment]
For now, switch to Pytorch 1.6 would be ok. For a temporary solution, please check [this issue](https://github.com/pytorch/pytorch/issues/47050) out.

**Comment by mitming** [comment]
> For now, switch to Pytorch 1.6 would be ok. For a temporary solution, please check [this issue](https://github.com/pytorch/pytorch/issues/47050) out.

Actually, there are also some problems when using PyTorch 1,6, When the whole training process are finished, the same error will occur, but this will not affect the training process and results

**Comment by SuX97** [comment]
>Actually, there are also some problems when using PyTorch 1,6, When the whole training process are finished, the same error will occur, but this will not affect the training process and results


```
diff --git a/mmcv/parallel/distributed.py b/mmcv/parallel/distributed.py
index 07771a3..60e2f31 100644
--- a/mmcv/parallel/distributed.py
+++ b/mmcv/parallel/distributed.py
@@ -28,6 +28,9 @@ class MMDistributedDataParallel(DistributedDataParallel):
         ``self.module.forward()`` with ``self.module.train_step()``.
         It is compatible with PyTorch 1.1 - 1.5.
         """
+        if self.reducer._rebuild_buckets():
+            print("Reducer buckets have been rebuilt in this iteration.")
+
         if getattr(self, 'require_forward_param_sync', True):
             self._sync_params()
         if self.device_ids:
```
Alternatively, you can try to add two lines in mmcv and build from the source.

**Comment by innerlee** [comment]
does this patch live in mmcv master?

**Comment by SuX97** [comment]
>does this patch live in mmcv master?

No, it is suggested by Pytorch official. I have tested it and it works.

**Comment by mitming** [comment]
Thanks for your help! Could you please check #362 ?
