### ISSUE TITLE
AttributeError: 'ConfigDict' object has no attribute 'omnisource' in training mmaction colab

### ISSUE THREAD

**Issue by ezzatmostafa96** [open-mmlab/mmaction2#315]
Thanks for your error report and we appreciate it a lot.

**Checklist**
1. I have searched related issues but cannot get the expected help.
2. The bug has not been fixed in the latest version.

**Describe the bug**

**Reproduction**
1. What command or script did you run?
```
A placeholder for the command.
```
2. Did you make any modifications on the code or config? Did you understand what you have modified?
3. What dataset did you use?

**Environment**

1. Please run `PYTHONPATH=${PWD}:$PYTHONPATH python mmaction/utils/collect_env.py` to collect necessary environment information and paste it here.
2. You may add addition that may be helpful for locating the problem, such as
    - How you installed PyTorch [e.g., pip, conda, source]
    - Other environment variables that may be related (such as `$PATH`, `$LD_LIBRARY_PATH`, `$PYTHONPATH`, etc.)

**Error traceback**
If applicable, paste the error traceback here.
```
A placeholder for traceback.
```

**Bug fix**
If you have already identified the reason, you can provide the information here. If you are willing to create a PR to fix it, please also leave a comment here and that would be much appreciated!

**Comment by kennymckormick** [comment]
Sorry that when I was adding the omnisource cfgs, I forgot to set `omnisource=True` in the config file. You can simply add a line `omnisource=True` in the config to fix this error. I also raised PR #316  to fix this error, which is under review now.

**Comment by ezzatmostafa96** [comment]
the error s still there

**Comment by ezzatmostafa96** [comment]
the new error 
TypeError                                 Traceback (most recent call last)
<ipython-input-28-e322cf97d082> in <module>()
     15 # Create work_dir
     16 mmcv.mkdir_or_exist(osp.abspath(cfg.work_dir))
---> 17 train_model(model, datasets, cfg, distributed=False, validate=True)

2 frames
/content/mmaction2/mmaction/apis/train.py in train_model(model, dataset, cfg, distributed, validate, timestamp, meta)
    139     if cfg.omnisource:
    140         runner_kwargs = dict(train_ratio=train_ratio)
--> 141     runner.run(data_loaders, cfg.workflow, cfg.total_epochs, **runner_kwargs)

/content/mmaction2/mmaction/core/runner/omnisource_runner.py in run(self, data_loaders, workflow, max_epochs, **kwargs)
    157                 if mode == 'train' and self.epoch >= self._max_epochs:
    158                     break
--> 159                 epoch_runner(data_loaders, **kwargs)
    160 
    161         time.sleep(1)  # wait for some hooks like loggers to finish

/content/mmaction2/mmaction/core/runner/omnisource_runner.py in train(self, data_loaders, **kwargs)
     71         if 'train_ratio' in kwargs:
     72             train_ratio = kwargs.pop('train_ratio')
---> 73             use_aux_per_niter = train_ratio[0]
     74             auxiliary_iter_times = train_ratio[1:]
     75 

TypeError: 'NoneType' object is not subscriptable

**Comment by kennymckormick** [comment]
Guess u are running omnisource with single auxiliary dataset, so you can add `train_ratio=[1, 1]` in the dictionary named `data` in the config file. The bug is because I wrongly set the default value of `train_ratio` as None in `mmaction/apis/train.py`. A fix is provided in PR #319 .

**Comment by kennymckormick** [comment]
The fix is merged now.

**Comment by ezzatmostafa96** [comment]
can you please run it all in all and see if it's working because there's always an error left

**Comment by ezzatmostafa96** [comment]
How can I test over a new video?

**Comment by ezzatmostafa96** [comment]
and how can I print the ROC curve?

**Comment by kennymckormick** [comment]
> can you please run it all in all and see if it's working because there's always an error left

OK, I'll run training for all configs to test that they work well.
BTW, seems u are trying to run the training of OmniSource. If so, you should first fill in a [data request form](https://docs.google.com/forms/d/e/1FAIpQLSd8_GlmHzG8FcDbW-OEu__G7qLgOSYZpH-i5vYVJcu7wcb_TQ/viewform?usp=sf_link) and we will share with you the OmniSource web datasets. Without those datasets, you can not run OmniSource training.
If you just want to test OmniSource models, you should download those checkpoints and run testing scripts. You can follow [new_dataset](https://github.com/open-mmlab/mmaction2/blob/master/docs/tutorials/new_dataset.md) to see how to test on a new dataset; or follow [tutorial](https://github.com/open-mmlab/mmaction2/blob/master/demo/mmaction2_tutorial.ipynb) to see how to test a single video.

**Comment by ezzatmostafa96** [comment]
no test my model on a new video.

**Comment by nixczhou** [comment]
PR #316 still does not add `omnisource=True` to all of the cfg files, so some user might still have the error when using the colab tutorial. Please add them ASAP.

**Comment by kennymckormick** [comment]
> no test my model on a new video.

The configs in OmniSource are mainly used for OmniSource training or testing OmniSource checkpoints. If you want to test your model (btw, I don't know what ur model is), you'd better resort to other config files.

**Comment by kennymckormick** [comment]
> PR #316 still does not add `omnisource=True` to all of the cfg files, so some user might still have the error when using the colab tutorial. Please add them ASAP.

I re-checked those configs files and found I wrongly add the line `omnisource=True` to tsn_r50_1x1x8_100e_minikinetics_rgb.py and I removed it in the new PR #321 . I've tested those config files in the master branch this time and the training goes well.

**Comment by wwdok** [comment]
@kennymckormick Hi, now i am running [colab](https://colab.research.google.com/github/open-mmlab/mmaction2/blob/master/demo/mmaction2_tutorial.ipynb#scrollTo=dDBWkdDRk6oz), this issue still exist 
![image](https://user-images.githubusercontent.com/43233772/99768695-33afe980-2b40-11eb-9c79-95cdd1d637f0.png)

**Comment by dreamerlin** [comment]
Thanks for your report, I will republish a new tutorial ipynb in colab !

**Comment by wwdok** [comment]
By the way, maybe it also need to add `!pip install mmcv`, or the next line `print(mmaction.__version__)` will produce error
![image](https://user-images.githubusercontent.com/43233772/99786389-64504d00-2b59-11eb-967a-32f60c56210f.png)

**Comment by dreamerlin** [comment]
Yeah, The colab is written when we just release the codebase. Thanks for your reminding, we will release a new tutorial for it.
