### ISSUE TITLE
How to get features

### ISSUE THREAD

**Issue by SebastienLinker** [open-mmlab/mmaction2#318]
Hi, This repo is pretty good.

How do you guys generate features given a video? Especially, I want to generate `pgm_proposals` and `pgm_features`, to run a temporal action recognition with `BSN`.
I found some scripts but they require other features to generate the features I need for my new dataset. Is there any way I can get them from scratch?

Thanks

**Comment by kennymckormick** [comment]
You need to use an action recognition model as the feature extractor, please refer to [preparing_activitynet](https://github.com/open-mmlab/mmaction2/blob/master/tools/data/activitynet/preparing_activitynet.md) for details. In the doc, we use the action recognition models pretrained on Kinetics and finetuned on ActivityNet as the feature extractor.
