### ISSUE TITLE
TypeError: init_recognizer() got an unexpected keyword argument 'use_frames'

### ISSUE THREAD

**Issue by lbq779660843** [open-mmlab/mmaction2#330]
I run a demo as what described at **getting_started.md** but get this error, and then I check the function **init_recognizer** and find it truly has a **use_frames** parameter. 
![捕获](https://user-images.githubusercontent.com/27773249/98640805-a6151280-2365-11eb-91a3-2eada6ad9522.PNG)

What's wrong with it?

**Comment by dreamerlin** [comment]
I guess there may be another `MMAction2` of older version. You can try `export PYTHONPATH=`pwd`:$PYTHONPATH` at the lastest `MMAction2` root path.

**Comment by kennymckormick** [comment]
You can check ur version by:
```python
import mmaction
print(mmaction.__version__)
```
make sure it is the latest version
