### ISSUE TITLE
OSError: [WinError 126] Cannot find this module

### ISSUE THREAD

**Issue by Berna-lab** [open-mmlab/mmaction2#348]
Hi,
I worked on demo.But I got WinError 126 error.Please help me.
![image](https://user-images.githubusercontent.com/59365034/99286545-0f0af780-284a-11eb-81de-753ff4c347af.png)
![image](https://user-images.githubusercontent.com/59365034/99286631-2fd34d00-284a-11eb-8136-227600aa2a89.png)
![image](https://user-images.githubusercontent.com/59365034/99286669-3bbf0f00-284a-11eb-8238-bf86699278a7.png)

**Comment by innerlee** [comment]
Thanks for the report. Indeed that part of the code was written for linux.

**Comment by Berna-lab** [comment]
You are right, so how can it be adapted for windows?

**Comment by jkhourybbn** [comment]
I see the same problem on osx
```
OSError: dlopen(libc.so.6, 6): image not found
```

**Comment by innerlee** [comment]
For a quick solution, you can use decord to decode video

**Comment by innerlee** [comment]
python has a `threading.get_ident()`, which is a number that only guarantees unique for threads within the same python instance. We need a system-wide unique identifier.
`threading.get_native_id()` looks perfect, but it is python 3.8+
