### ISSUE TITLE
tools/test.py split error

### ISSUE THREAD

**Issue by liuheng92** [open-mmlab/mmaction2#349]
hi, when you split 'result.json' using osp.splitext, it will return 'result' and '.json', then 'assert' line below will throw an error. I think you mean to use  out.split('.').
https://github.com/open-mmlab/mmaction2/blob/d03d245d133faf4e19e6b7e14be3b6a6697e9585/tools/test.py#L123

**Comment by innerlee** [comment]
Thanks for the report, it is an oversight during refactoring.

**Comment by kennymckormick** [comment]
Fix it in PR #350 .
