### ISSUE TITLE
sth v1 preparation

### ISSUE THREAD

**Issue by d-li14** [open-mmlab/mmaction2#35]
The original something-something v1 dataset already contains frames after extraction. So the preparation process probably needs a refactorization. What is needed is just renaming the extracted frames to follow the naming convention "img_%05d.jpg".

**Comment by innerlee** [comment]
Thanks for the report! Actually renaming is not needed since we support different naming templates. That said, the instructions need to be updated.

Offtopic but, encoding them as mp4 videos might be interesting also.

**Comment by d-li14** [comment]
Thanks for your prompt reply!
1. Supporting different naming templates is definitely a good feature. Sorry I have not investigated deeply regarding this problem.
2. Efficient video loading is also interesting, then the preparation process may also (inversely) include encoding frames into videos.

**Comment by dreamerlin** [comment]
We are praparing a fix now https://github.com/open-mmlab/mmaction2/pull/36
