### ISSUE TITLE
some code mistakes

### ISSUE THREAD

**Issue by liuheng92** [open-mmlab/mmaction2#353]
hi, there are some mistakes in train.py and test.py script. In parse_args function, flag named 'fuse-conv-bn', but using flag named 'fuse_conv_bn'. also like 'eval-options'\'gpu-ids' and so on.

https://github.com/open-mmlab/mmaction2/blob/d52d775849cf78c3346ca1b9410875965b1c430d/tools/train.py#L26

**Comment by dreamerlin** [comment]
Thanks for your attention, but it is not a mistake.

**Comment by dreamerlin** [comment]
Ref: https://stackoverflow.com/questions/12834785/having-options-in-argparse-with-a-dash
