### ISSUE TITLE
Error encountered while verified whether MMAction2 and the required environment are installed correctly

### ISSUE THREAD

**Issue by ylyenjoy** [open-mmlab/mmaction2#356]
**I want to  verify whether MMAction2 and the required environment are installed correctly,but got something wrong,this is code**:
import torch
from mmaction.apis import init_recognizer, inference_recognizer

config_file = 'configs/recognition/tsn/tsn_r50_video_inference_1x1x3_100e_kinetics400_rgb.py'
device = 'cuda' # or 'cpu'
device = torch.device(device)

model = init_recognizer(config_file, device=device)
inference_recognizer(model, 'demo/demo.mp4', 'demo/label_map.txt')

**And got error like this:**
Exception ignored in: <function OpenCVInit.__del__ at 0x7f7b7d19cdd0>
Traceback (most recent call last):
  File "/home/shtf/ysir/mmaction2/mmaction/datasets/pipelines/loading.py", line 948, in __del__
    shutil.rmtree(self.tmp_folder)
AttributeError: 'OpenCVInit' object has no attribute 'tmp_folder'

**my opencv-contrib-python version is  4.4.0.46;and my opencv-python is 4.4.0.46,too.And my cuda is 10.0,pytorch is 1.4,I have done all installation steps,I have no idea about this**

**Comment by dreamerlin** [comment]
Thanks for your report, it is fixed in https://github.com/open-mmlab/mmaction2/pull/357
