### ISSUE TITLE
For those having trouble building the project, can you  provide a built docker image?  So that people can download it from DockerHub. 

### ISSUE THREAD

**Issue by shuyuandeqipa** [open-mmlab/mmaction2#360]

**Comment by dreamerlin** [comment]
[Dorkerfile](https://github.com/open-mmlab/mmaction2/blob/master/docker/Dockerfile) is provided and you can refer to https://github.com/open-mmlab/mmaction2/blob/master/docs/install.md#another-option-docker-image

**Comment by innerlee** [comment]
Could you provide more info on the difficulty? We try to make the usage as smooth as possible

**Comment by shuyuandeqipa** [comment]
Due to the problems in our network environment and system environment, we build the project is still a little hard with the Dorkerfile.  Some tools can not be downloaded successfully.  Besides,  installing the denseflow project to extract flow from videos is a little difficult for me.  If the authors can provide a well-built docker image  for users to download from dockerhub,  all the installing problems can be avoided.

**Comment by shuyuandeqipa** [comment]
The mmactionV2 is the best  project about action recognition we can find, so we definitely hope the project can be built perfectly. 
Thanks  for all your efforts  on the project!  Respect!

**Comment by dreamerlin** [comment]
> The mmactionV2 is the best project about action recognition we can find, so we definitely hope the project can be built perfectly.
> Thanks for all your efforts on the project! Respect!

Thanks for your attention, we will support it as soon as possible !

**Comment by congee524** [comment]
We don't have an official docker account right now. I push the image to my personal account.
```
congee524/mmaction2:base               # built from the Dockerfile
congee524/mmaction2:denseflow          # mmaction2 with denseflow installed
```
For ```congee524/mmaction2:denseflow```，you need to set the following ENV after pulling the docker image.
```
export ZZROOT=/root/app
export PATH=$ZZROOT/bin:$PATH
export LD_LIBRARY_PATH=$ZZROOT/lib:$ZZROOT/lib64:$LD_LIBRARY_PATH
```
Please contact me if you have any questions.

**Comment by shuyuandeqipa** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    
        Thank you very much !  Can you seed me the link to your images please ?  
        I do not know where to download it.   I can not search it just now. 
    
        
            
        
    
    
     
    
        
                    
            
                
                    
                            
                                
                            
                            
                                1228436902
                            
                    
                        
                            
                                    1228436902@qq.com
                            
                        
                
            
        
        
    
    
        签名由
        网易邮箱大师
        定制
    
 

    On 11/24/2020 16:45，congee<notifications@github.com> wrote： 




We don't have an official docker account right now. I push the image to my personal account.

congee524/mmaction2:base               # built from the Dockerfile

congee524/mmaction2:denseflow          # mmaction2 with denseflow installed



For congee524/mmaction2:denseflow，you need to set the following ENV after pulling the docker image.

export ZZROOT=/root/app

export PATH=$ZZROOT/bin:$PATH

export LD_LIBRARY_PATH=$ZZROOT/lib:$ZZROOT/lib64:$LD_LIBRARY_PATH



Please contact me if you have any questions.



—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by congee524** [comment]
https://hub.docker.com/r/congee524/mmaction2

could you see the repo?

**Comment by shuyuandeqipa** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    
        yes !!!
        
    
        
            
        
    
    
     
    
        
                    
            
                
                    
                            
                                
                            
                            
                                1228436902
                            
                    
                        
                            
                                    1228436902@qq.com
                            
                        
                
            
        
        
    
    
        签名由
        网易邮箱大师
        定制
    
 

    On 11/24/2020 17:14，congee<notifications@github.com> wrote： 



https://hub.docker.com/r/congee524/mmaction2
could you see the repo?

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by dreamerlin** [comment]
@congee524 We can add this to [docs](https://github.com/open-mmlab/mmaction2/blob/master/docs/install.md#another-option-docker-image) and describe the steps to use it.
