### ISSUE TITLE
cannot import name 'digit_version' from 'mmcv' (unknown location)

### ISSUE THREAD

**Issue by wwdok** [open-mmlab/mmaction2#364]
I copy the [verification code](https://github.com/open-mmlab/mmaction2/blob/master/docs/install.md#verification) to check if i install successfully,  and paste it in `verification.py`, and run it, it reports error described below:

**Checklist**
1. I have searched related issues but cannot get the expected help.
2. The bug has not been fixed in the latest version.

**Describe the bug**

**Reproduction**
1. What command or script did you run?
```
python verification.py
```
2. Did you make any modifications on the code or config? Did you understand what you have modified?
3. What dataset did you use?

**Environment**

1. Please run `PYTHONPATH=${PWD}:$PYTHONPATH python mmaction/utils/collect_env.py` to collect necessary environment information and paste it here.
```
(base) weidawang@weidawang-TUF-Gaming-FX506LU-FX506LU:~/Repo/mmaction2$ PYTHONPATH=${PWD}:$PYTHONPATH python mmaction/utils/collect_env.py
Traceback (most recent call last):
  File "mmaction/utils/collect_env.py", line 1, in <module>
    from mmcv.utils import collect_env as collect_basic_env
ImportError: cannot import name 'collect_env' from 'mmcv.utils' (unknown location)

```
2. You may add addition that may be helpful for locating the problem, such as
    - How you installed PyTorch [e.g., pip, conda, source]
    - Other environment variables that may be related (such as `$PATH`, `$LD_LIBRARY_PATH`, `$PYTHONPATH`, etc.)

**Error traceback**
If applicable, paste the error traceback here.
```
(base) weidawang@weidawang-TUF-Gaming-FX506LU-FX506LU:~/Repo/mmaction2$ python verification.py
Traceback (most recent call last):
  File "verification.py", line 2, in <module>
    from mmaction.apis import init_recognizer, inference_recognizer
  File "/home/weidawang/Repo/mmaction2/mmaction/__init__.py", line 2, in <module>
    from mmcv import digit_version
ImportError: cannot import name 'digit_version' from 'mmcv' (unknown location)

```

**Bug fix**
If you have already identified the reason, you can provide the information here. If you are willing to create a PR to fix it, please also leave a comment here and that would be much appreciated!

**By the way, how to generate the [overview video](https://github.com/open-mmlab/mmaction2/blob/master/docs/imgs/mmaction2_overview.gif) at the home page, iam just new to here, and i want to have a intuitive sense by playing the demo with mmaction2, thanks!**

**Comment by dreamerlin** [comment]
1. https://github.com/open-mmlab/mmcv/blob/master/mmcv/utils/__init__.py#L29. It seems the `mmcv` in your environment is not installed correctly.
2. You can play with `demo/` to generate the overview video.

**Comment by wwdok** [comment]
@dreamerlin Yes, the order is important, i should uninstall mmcv firstly and then install mmcv-full, **NOT**  install mmcv-full and then uninstall mmcv, i solved it by reinstall mmcv-full.
Thanks for your guide !
