### ISSUE TITLE
RuntimeError: CUDA out of memory

### ISSUE THREAD

**Issue by Berna-lab** [open-mmlab/mmaction2#365]
Hi,
When i run demo with
_python demo/demo.py configs/recognition/tsn/tsn_r50_video_inference_1x1x3_100e_kinetics400_rgb.py  https://download.openmmlab.com/mmaction/recognition/tsn/tsn_r50_1x1x3_100e_kinetics400_rgb/tsn_r50_1x1x3_100e_kinetics400_rgb_20200614-e508be42.pth  demo/demo.mp4 demo/label_map.txt --out-filename demo/demo_out.mp4_
I got **RuntimeError: CUDA out of memory. Tried to allocate 766.00 MiB (GPU 0; 2.00 GiB total capacity; 1003.04 MiB already allocated; 583.66 MiB free; 1.00 GiB reserved in total by PyTorch)** .
Do I need to reduce the batch size ?
If yes, where is the set batch size in code ?

**Comment by dreamerlin** [comment]
[Here] to set the batch_size. And it seems your machine doesn't have enough big GPU. For more explanation, you can refer to https://github.com/open-mmlab/mmaction2/blob/master/docs/config.md
