### ISSUE TITLE
Request of function to generate standard proposal ann_file

### ISSUE THREAD

**Issue by MakeCent** [open-mmlab/mmaction2#368]
Could you share your code used to generate the standard proposal ann_file? I  successfully run BMN on a new dataset but the dump_results function in ActivityNet dataset doesn't support outputting a standard proposal ann_file that can be used in localization models such as the SSN dataset.

Details:
As [said ](https://github.com/open-mmlab/mmaction2/blob/fd77779ea0ee0bf0449db1b855791d601284efeb/mmaction/datasets/ssn_dataset.py#L90)in SSN dataset, a standard proposal ann_file should look like:

    Template information of a video in a standard file:
    .. code-block:: txt
        # index
        video_id
        num_frames
        fps
        num_gts
        label, start_frame, end_frame
        label, start_frame, end_frame
        ...
        num_proposals
        label, best_iou, overlap_self, start_frame, end_frame
        label, best_iou, overlap_self, start_frame, end_frame

While in the[ Activitynet_dataset](https://github.com/open-mmlab/mmaction2/blob/fd77779ea0ee0bf0449db1b855791d601284efeb/mmaction/datasets/activitynet_dataset.py#L159), which is used as the dataset type for proposal models, I cannot find any function that can be used to generate such a kind of ann_file, and I cannot manually generate one because I don't quite understand the meaning of "best_iou" and "overlap_self" in the standard ann_file.

**Comment by kennymckormick** [comment]
I'm not quite familiar with SSN, do you have any ideas? @tony2016uestc

**Comment by tony2016uestc** [comment]
IoU between proposals and targets are calculated, 
`best_iou` is the largest iou of between the proposal and all targets,
`overlap_self` is  overlap / proposal_len.

We will add the function to generate a proposal file.

**Comment by tony2016uestc** [comment]
@MakeCent 
A function to covert `result_proposal.json` of BMN to a standard proposal ann_file, right?
I have to know what is the input file like.

**Comment by MakeCent** [comment]
> @MakeCent
> A function to covert `result_proposal.json` of BMN to a standard proposal ann_file, right?
> I have to know what is the input file like.

Yes. Convert the proposal json file created by [dump_results function of ActivityNet dataset](https://github.com/open-mmlab/mmaction2/blob/fd77779ea0ee0bf0449db1b855791d601284efeb/mmaction/datasets/activitynet_dataset.py#L159); Or maybe make dump_results() support outputting a standard proposal ann_file directly?
