### ISSUE TITLE
How to get features from slowfastnet model

### ISSUE THREAD

**Issue by ayanasser** [open-mmlab/mmaction2#369]
Hi, 
I want to know if u have the ability to get features from the slowfastnet model?
and how could i do this ?

**Comment by dreamerlin** [comment]
The features will be extracted by backbone [here](https://github.com/open-mmlab/mmaction2/blob/master/mmaction/models/recognizers/recognizer2d.py#L17), you can manually modify the code to return it. Or for inference, it is better to registry a custom `Head`, which will return the score and feature.

**Comment by kennymckormick** [comment]
What about making cls_head optional. If cls_head is set as None, the recognizer can return feature or pooled feature.

**Comment by innerlee** [comment]
Feature extraction may be generic. They do not have to be the last output of backbone. Checkout this pr https://github.com/open-mmlab/mmpose/pull/212 to take an inspiration
