### ISSUE TITLE
AVA dataset: Getting frame associated with annotation

### ISSUE THREAD

**Issue by nikky4D** [open-mmlab/mmaction2#370]
I'm trying to get the frame number of the bounding box annotation in the AVA dataset. I followed the download instructions, have gotten the videos, and clipped them from 15th to 30th minute. I've also gotten the rawframes.

Can anyone tell me how to get the frame number for the bounding box annotations using the timestamps in the csv annotation file?

**Comment by kennymckormick** [comment]
The csv annotations provide the timestamp(which second) of the annotated action. Since you extract frames for the clip between 15th and 30th minute with 30FPS, the frame_idx should be 30 * (timestamp - 900).

**Comment by nikky4D** [comment]
Thanks. I tried 30*(timestamp - 901) but I will try 900 to see if that works better
