### ISSUE TITLE
Kinetics class rename problem

### ISSUE THREAD

**Issue by ShoufaChen** [open-mmlab/mmaction2#374]
Hi,

In [rename_classnames.sh](https://github.com/open-mmlab/mmaction2/blob/master/tools/data/kinetics/rename_classnames.sh), the `(` and ``)` will be converted to `-`.

However, the [parse_file_list.py](https://github.com/open-mmlab/mmaction2/blob/master/tools/data/parse_file_list.py#L320) only converts whitespace to '_', without changing the `(` .

This will cause mismatch at build_file_list.py:
```
        rgb_list, flow_list = list(), list()
        for item in split:
            if item[0] not in frame_info:
                continue
```

And some classes will be ignored, such as `skiing_(not_slalom_or_crosscountry)`.

I'm glad to pull a request if it's a bug. And please tell me if I misunderstood it.

**Comment by kennymckormick** [comment]
Thanks a lot for reporting that bug. It will help a lot if you can provide a fix for this bug.

**Comment by ShoufaChen** [comment]
I have a pr https://github.com/open-mmlab/mmaction2/pull/376 for this issue.

**Comment by innerlee** [comment]
@dreamerlin whose bug? `parse_file_list.py` or those rename scripts?

**Comment by ShoufaChen** [comment]
I think it's better to modify the rename script because other codebases, such as SlowFast, Non-Local also leave the `(` unchanged.

**Comment by kennymckormick** [comment]
> @dreamerlin whose bug? `parse_file_list.py` or those rename scripts?

The bug is because the rename scripts and `parse_file_list.py` are not consistent. (related to Kinetics only)

**Comment by kennymckormick** [comment]
@dreamerlin . I also find that it seems the renaming step should be compulsory, which is inconsistent with the description in README. Would u please help check if this step can be omitted?

**Comment by dreamerlin** [comment]
> @dreamerlin . I also find that it seems the renaming step should be compulsory, which is inconsistent with the description in README. Would u please help check if this step can be omitted?

The step is indeed compulsory I think, but the docs doesn't point it out explicitly. I modify it to be more clear,
