### ISSUE TITLE
AttributeError: 'OpenCVInit' object has no attribute 'tmp_folder'

### ISSUE THREAD

**Issue by Sean-hku** [open-mmlab/mmaction2#383]
**Hi, When I run this demo script**
`python demo/demo.py configs/recognition/tsn/tsn_r50_video_inference_1x1x3_100e_kinetics400_rgb.py \
    checkpoints/tsn_r50_1x1x3_100e_kinetics400_rgb_20200614-e508be42.pth \
    demo/demo.mp4 demo/label_map.txt`

**I get this error**
The top-5 labels with corresponding scores are:
arm wrestling:  29.616438
rock scissors paper:  10.754841
shaking hands:  9.908401
clapping:  9.189913
massaging feet:  8.305306
Exception ignored in: <function OpenCVInit.__del__ at 0x7fed6c025290>
Traceback (most recent call last):
  File "/media/hkuit164/TOSHIBA/mmaction2/mmaction/datasets/pipelines/loading.py", line 948, in __del__
    shutil.rmtree(self.tmp_folder)
AttributeError: 'OpenCVInit' object has no attribute 'tmp_folder'

Is this a Opencv problem?

**Comment by innerlee** [comment]
Which version of mmaction2?

I guess this has been fixed in master branch

**Comment by dreamerlin** [comment]
Fix get_thread_id when not using disk as backend (#354, #357). You can see the [changelog](https://github.com/open-mmlab/mmaction2/blob/master/docs/changelog.md)

**Comment by Sean-hku** [comment]
> Which version of mmaction2?
> 
> I guess this has been fixed in master branch

The problem is solved when I updated the latest version. Thank you very much!
