### ISSUE TITLE
A question about SSN reference performance

### ISSUE THREAD

**Issue by kennymckormick** [open-mmlab/mmaction2#387]
In SSN README, the author list the reference performance of SSN of the MMAction implementation. I wonder why those numbers are different from the MMAction repo.

**Comment by dreamerlin** [comment]
@tony2016uestc

**Comment by tony2016uestc** [comment]
The difference is:
MMAction SSN performance is evaluated with `BNInception` backbone, while the reference performance is evaluated with `ResNet50` backbone.

**Comment by kennymckormick** [comment]
If so, it would be better to add some descriptions in the README file, or it will be a little confusing. If we have trained the SSN instantiated with BNInception backbone, we can also add it in the modelzoo.

**Comment by tony2016uestc** [comment]
OK, I will add descriptions in the README.

I have trained the SSN instantiated with BNInception backbone, and the performance is close to that in MMAction.
If we revise BNInception backbone and satisfy the requirements of MMAction2, we will add it in the modelzoo.
