### ISSUE TITLE
Have you tried I3D flow training? 

### ISSUE THREAD

**Issue by yangzhaojason** [open-mmlab/mmaction2#394]

**Comment by innerlee** [comment]
Checkout the model zoo https://mmaction2.readthedocs.io/en/latest/recognition_models.html, all models are published there

**Comment by yangzhaojason** [comment]
> Checkout the model zoo https://mmaction2.readthedocs.io/en/latest/recognition_models.html, all models are published there

I'm sorry I didn't find you training I3D Flow, but it's really important.

**Comment by kennymckormick** [comment]
> > Checkout the model zoo https://mmaction2.readthedocs.io/en/latest/recognition_models.html, all models are published there
> 
> I'm sorry I didn't find you training I3D Flow, but it's really important.

In MMAction2 we provide the SlowOnly-Flow, which has better accuracy comparing to I3D-Flow. In [MMAction](https://github.com/open-mmlab/mmaction) we provide the I3D-Flow checkpoint which is converted from the original repo. Currently, we do not support I3D-Flow training in either of these two repos.

**Comment by yangzhaojason** [comment]
> > > Checkout the model zoo https://mmaction2.readthedocs.io/en/latest/recognition_models.html, all models are published there
> > 
> > 
> > I'm sorry I didn't find you training I3D Flow, but it's really important.
> 
> In MMAction2 we provide the SlowOnly-Flow, which has better accuracy comparing to I3D-Flow on Kinetics-400. In [MMAction](https://github.com/open-mmlab/mmaction) we provide the I3D-Flow checkpoint which is converted from the original repo. Currently, we do not support I3D-Flow training in either of these two repos.

thanks, I tried on ucf101 based on I3D-flow model, top1_acc: 0.7864, top5_acc 0.9307.
