### ISSUE TITLE
assert mmcv version problem

### ISSUE THREAD

**Issue by ShoufaChen** [open-mmlab/mmaction2#396]
https://github.com/open-mmlab/mmaction2/blob/4c3f7c60aaa9a67e6392a44248b1f3636c1eacc7/mmaction/__init__.py#L7-L10

Currently, mmcv version has been bumped to 1.2.1. 

It is reasonable to change the `mmcv_maximum_version` because now error will raise for those who build mmcv from source.

**Comment by innerlee** [comment]
Yeah it will be updated before release of this version
