### ISSUE TITLE
question：how to keep server downloading videos when laptop is closed

### ISSUE THREAD

**Issue by wwdok** [open-mmlab/mmaction2#398]
Last week, i began to download kinetics-400 dataset into server  via ssh command from my ubuntu laptop, but now i found it is far from download completetion, so my trouble is if i want to switch my system from ubuntu to windows10 ( that means i need to shut down my laptop), how to keep server downloading videos when laptop is closed and how to check its status afterwards？ Thanks !

**Comment by innerlee** [comment]
checkout tmux

**Comment by wwdok** [comment]
@innerlee When should i detach tmux session ？ during the downloading or before the downloading ? according my intuitive, it maybe during the downloading, but after i type `tmux detach` and `Ctrl+b d`,  the session seems not have response, is it normal ?
![image](https://user-images.githubusercontent.com/43233772/100687600-8fd60180-33bb-11eb-9038-b1f4c3939085.png)

**Comment by innerlee** [comment]
During downloading. Press `ctrl+b`, release keys, press `d`

**Comment by wwdok** [comment]
Ah, The keypoint is `release keys`, Thanks !!!!!

**Comment by wwdok** [comment]
Hi, @innerlee , now i can keep downloading kinetics400 dataset in the background, but i found it will take more than 2 weeks, so i dicide to just download one of the action class, e.g `faceplanting`， so i change the code in `mmaction2/tools/data/kinetics/download.py` by adding `df = df.loc[df['label-name'] == 'faceplanting']` as below:
![image](https://user-images.githubusercontent.com/43233772/101299446-37947900-386d-11eb-9337-fc5c0e2dc921.png)
and i comment out `python download.py ${ANNO_DIR}/kinetics_train.csv ${DATA_DIR}/videos_train` in `mmaction2/tools/data/kinetics/download_videos.sh` that will take too much time, just leave `videos_val` to download, so that i can walk through a quick but complete process, then i run `bash download_videos.sh kinetics400`, everything is normal at the begining, it printed out something like  `youtube-dl --quiet --no-warnings --no-check-certificate -f mp4 -o "/tmp/kinetics/2357aa58-2a4b-4c41-8033-6daf5cb9a61c.%(ext)s" "https://www.youtube.com/watch?v=**********`, but after all the videos are downloaded, it reports errors like bolow :
![image](https://user-images.githubusercontent.com/43233772/101299280-99a0ae80-386c-11eb-865d-e447f8ff9b50.png)
Is there code somewhere else i need change too to avoid this error ?

**Comment by wwdok** [comment]
Just now, i went to watch the progress of kinetics400-val, it has completed, and it has the same error as above, so does this mean that this error has nothing to do with changing the code to download only one type of action class ?
![image](https://user-images.githubusercontent.com/43233772/101432906-ae507580-3944-11eb-848f-ca0bb576c371.png)

**Comment by innerlee** [comment]
Looks like this is a list of failed downloads. You may collect the filenames, and try again.

**Comment by wwdok** [comment]
This is the full log :  

(base) root@LAB_VM:/home/mmaction2/tools/data/kinetics# bash download_videos.sh kinetics400                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
Requirement already up-to-date: youtube-dl in /root/anaconda3/lib/python3.8/site-packages (2020.12.5)                                                                                         
We are processing kinetics400                                                                                                                                                                 
youtube-dl --quiet --no-warnings --no-check-certificate -f mp4 -o "/tmp/kinetics/a433b0fe-d4f8-4a39-b95c-9829deca061f.%(ext)s" "https://www.youtube.com/watch?v=-0ew-c0w7uc"
youtube-dl --quiet --no-warnings --no-check-certificate -f mp4 -o "/tmp/kinetics/fc6ebbcd-490b-4cbd-b650-a2519b8ae4a3.%(ext)s" "https://www.youtube.com/watch?v=0MJ9Rk0k92Q"
youtube-dl --quiet --no-warnings --no-check-certificate -f mp4 -o "/tmp/kinetics/9582e6e1-fe56-4b3f-8abc-3749898438ff.%(ext)s" "https://www.youtube.com/watch?v=3M8j8pPfGDA"
youtube-dl --quiet --no-warnings --no-check-certificate -f mp4 -o "/tmp/kinetics/09417187-e293-43c5-9885-2394323b0a3d.%(ext)s" "https://www.youtube.com/watch?v=3ht3zPeo7x0"
youtube-dl --quiet --no-warnings --no-check-certificate -f mp4 -o "/tmp/kinetics/aebfa881-9735-49cb-90c1-e4d00baae320.%(ext)s" "https://www.youtube.com/watch?v=4J22wFT7-LQ"
youtube-dl --quiet --no-warnings --no-check-certificate -f mp4 -o "/tmp/kinetics/13df5768-ff0a-4013-bece-be9cbba1e844.%(ext)s" "https://www.youtube.com/watch?v=94uIR7fT_KM"
youtube-dl --quiet --no-warnings --no-check-certificate -f mp4 -o "/tmp/kinetics/511af2a6-c8a5-43c3-bbc6-a24165bd1678.%(ext)s" "https://www.youtube.com/watch?v=GhG5PXDqmUY"
youtube-dl --quiet --no-warnings --no-check-certificate -f mp4 -o "/tmp/kinetics/a196c8eb-f7f9-4a4c-934d-53a4874f25c2.%(ext)s" "https://www.youtube.com/watch?v=HeEsL9yTiKg"
youtube-dl --quiet --no-warnings --no-check-certificate -f mp4 -o "/tmp/kinetics/7a8a32a9-9b6b-4dcf-9e26-3a539f60ff8d.%(ext)s" "https://www.youtube.com/watch?v=AX_CHNc1ThA"
youtube-dl --quiet --no-warnings --no-check-certificate -f mp4 -o "/tmp/kinetics/51f85abb-c992-411f-b5d8-e8ffe546f1bb.%(ext)s" "https://www.youtube.com/watch?v=-ri90Xykrxg"
youtube-dl --quiet --no-warnings --no-check-certificate -f mp4 -o "/tmp/kinetics/ec832993-6f96-45a1-976e-935952c3d44b.%(ext)s" "https://www.youtube.com/watch?v=Q0ITIDt6Z7E"
youtube-dl --quiet --no-warnings --no-check-certificate -f mp4 -o "/tmp/kinetics/e079a004-7b66-4ffd-8c6c-2ab9f8b492fa.%(ext)s" "https://www.youtube.com/watch?v=83DIh7MkoG8"
youtube-dl --quiet --no-warnings --no-check-certificate -f mp4 -o "/tmp/kinetics/6dfad360-6d7a-4e91-80b0-ade6200c7a75.%(ext)s" "https://www.youtube.com/watch?v=6WPoVkWBBBI"
youtube-dl --quiet --no-warnings --no-check-certificate -f mp4 -o "/tmp/kinetics/4ceafffc-9e94-40fb-8ee1-e7da04ff7207.%(ext)s" "https://www.youtube.com/watch?v=6q7v3O77NOI"
youtube-dl --quiet --no-warnings --no-check-certificate -f mp4 -o "/tmp/kinetics/7d51f7c7-368d-4fb1-979d-0f820bbfcd88.%(ext)s" "https://www.youtube.com/watch?v=8heUql3B7hg"
youtube-dl --quiet --no-warnings --no-check-certificate -f mp4 -o "/tmp/kinetics/1a54c1cf-3227-4386-944b-14b62cfd7e48.%(ext)s" "https://www.youtube.com/watch?v=8EMK8AoG3h8"
youtube-dl --quiet --no-warnings --no-check-certificate -f mp4 -o "/tmp/kinetics/72e84246-4b5e-4271-b749-55878cc8f3b7.%(ext)s" "https://www.youtube.com/watch?v=J5n1A-NCuxU"
youtube-dl --quiet --no-warnings --no-check-certificate -f mp4 -o "/tmp/kinetics/a3f6f3e1-ffb5-47e2-a06e-55f266fe767d.%(ext)s" "https://www.youtube.com/watch?v=JqEEGvPSxxA"
youtube-dl --quiet --no-warnings --no-check-certificate -f mp4 -o "/tmp/kinetics/6fa40756-2458-461d-acf6-72d56dc658ea.%(ext)s" "https://www.youtube.com/watch?v=NgVb5pZw8Ak"
youtube-dl --quiet --no-warnings --no-check-certificate -f mp4 -o "/tmp/kinetics/2a5e5f4c-d296-4c30-a5d0-e1db49a467ad.%(ext)s" "https://www.youtube.com/watch?v=_PwXWcCPrGA"
youtube-dl --quiet --no-warnings --no-check-certificate -f mp4 -o "/tmp/kinetics/009733a1-6930-4244-b319-0c98b5af2641.%(ext)s" "https://www.youtube.com/watch?v=aBJnzTcJ70o"
youtube-dl --quiet --no-warnings --no-check-certificate -f mp4 -o "/tmp/kinetics/1eb4bf79-b6ef-4c67-a281-265138e96250.%(ext)s" "https://www.youtube.com/watch?v=ad0MgJg_MBM"
youtube-dl --quiet --no-warnings --no-check-certificate -f mp4 -o "/tmp/kinetics/3845be21-2036-4b34-9fd4-cfe811d9331c.%(ext)s" "https://www.youtube.com/watch?v=Nh25jQx6Y38"
youtube-dl --quiet --no-warnings --no-check-certificate -f mp4 -o "/tmp/kinetics/23cc411b-d5dc-4b4a-b957-50af147c1e34.%(ext)s" "https://www.youtube.com/watch?v=VN3-h6-aAls"
youtube-dl --quiet --no-warnings --no-check-certificate -f mp4 -o "/tmp/kinetics/e9d0a986-f36e-490e-9dd0-eef8b868a5d9.%(ext)s" "https://www.youtube.com/watch?v=cjk3tn-kqkU"
youtube-dl --quiet --no-warnings --no-check-certificate -f mp4 -o "/tmp/kinetics/6197ffee-3089-4129-8d16-0140582ab65a.%(ext)s" "https://www.youtube.com/watch?v=dXhPdo54Eko"
youtube-dl --quiet --no-warnings --no-check-certificate -f mp4 -o "/tmp/kinetics/cffd3236-4548-4c1d-92f5-007ec243eb19.%(ext)s" "https://www.youtube.com/watch?v=e2LIBGlv2Ds"
youtube-dl --quiet --no-warnings --no-check-certificate -f mp4 -o "/tmp/kinetics/c8d82b71-ee9b-4163-baf6-bd25db12dcd2.%(ext)s" "https://www.youtube.com/watch?v=fTob9z1OrpM"
youtube-dl --quiet --no-warnings --no-check-certificate -f mp4 -o "/tmp/kinetics/465323f4-495f-4b21-b981-7ca14bcc257f.%(ext)s" "https://www.youtube.com/watch?v=hlUDq3QKZo8"
youtube-dl --quiet --no-warnings --no-check-certificate -f mp4 -o "/tmp/kinetics/818c143e-7423-46bd-8d2b-e3ac298534b6.%(ext)s" "https://www.youtube.com/watch?v=iLpLgzIQIkQ"
youtube-dl --quiet --no-warnings --no-check-certificate -f mp4 -o "/tmp/kinetics/c7861284-8213-42a8-a871-3982ac9a5cab.%(ext)s" "https://www.youtube.com/watch?v=iVLuQ9fIW6s"
youtube-dl --quiet --no-warnings --no-check-certificate -f mp4 -o "/tmp/kinetics/fa69618f-0e88-42f3-bc73-e87ecbef9b10.%(ext)s" "https://www.youtube.com/watch?v=kwuAR3lbRxI"
youtube-dl --quiet --no-warnings --no-check-certificate -f mp4 -o "/tmp/kinetics/a3aba955-8ce0-4684-8948-ac0262068265.%(ext)s" "https://www.youtube.com/watch?v=mKAvzPnh_Yw"
youtube-dl --quiet --no-warnings --no-check-certificate -f mp4 -o "/tmp/kinetics/5f7e3070-11a5-4ff7-8e75-e64352a4dfe1.%(ext)s" "https://www.youtube.com/watch?v=oOpaLCB7PbQ"
youtube-dl --quiet --no-warnings --no-check-certificate -f mp4 -o "/tmp/kinetics/b9726921-b590-4ee9-adae-3c17bfcd1fd6.%(ext)s" "https://www.youtube.com/watch?v=petld-72OXM"
youtube-dl --quiet --no-warnings --no-check-certificate -f mp4 -o "/tmp/kinetics/e4bf13bd-4994-4aea-ab17-d17d6fcf8876.%(ext)s" "https://www.youtube.com/watch?v=r81d5eNm9Rs"
youtube-dl --quiet --no-warnings --no-check-certificate -f mp4 -o "/tmp/kinetics/6c7e36ca-19f7-4d5d-b141-c29c92d8111b.%(ext)s" "https://www.youtube.com/watch?v=r9INzx9GaAk"
youtube-dl --quiet --no-warnings --no-check-certificate -f mp4 -o "/tmp/kinetics/36d6071d-63a2-4ef3-b369-37d93a40e83a.%(ext)s" "https://www.youtube.com/watch?v=rpaTvmTPC0M"
youtube-dl --quiet --no-warnings --no-check-certificate -f mp4 -o "/tmp/kinetics/6b45e120-e08f-4146-92d3-94fa94a4e3b9.%(ext)s" "https://www.youtube.com/watch?v=tA2patyR1Pg"
youtube-dl --quiet --no-warnings --no-check-certificate -f mp4 -o "/tmp/kinetics/ca3ff4cb-be0d-4fb6-a868-d2d7312abe6b.%(ext)s" "https://www.youtube.com/watch?v=u5u9y_ltKCI"
youtube-dl --quiet --no-warnings --no-check-certificate -f mp4 -o "/tmp/kinetics/6683d9e1-1591-43c8-83e4-848d32223eb7.%(ext)s" "https://www.youtube.com/watch?v=tChIbM9u7t0"
youtube-dl --quiet --no-warnings --no-check-certificate -f mp4 -o "/tmp/kinetics/9668eb1f-8673-4096-9981-8e6bae178b2a.%(ext)s" "https://www.youtube.com/watch?v=wL4EN5CBU9Q"
youtube-dl --quiet --no-warnings --no-check-certificate -f mp4 -o "/tmp/kinetics/befb24de-9de5-4de5-afa5-5e4b7cd18906.%(ext)s" "https://www.youtube.com/watch?v=wdCcRngfyZw"
       youtube-dl --quiet --no-warnings --no-check-certificate -f mp4 -o "/tmp/kinetics/677ac549-c356-4361-af8a-aee8443bb635.%(ext)s" "https://www.youtube.com/watch?v=wu3oEKpw6N4"
youtube-dl --quiet --no-warnings --no-check-certificate -f mp4 -o "/tmp/kinetics/48058ab1-7d5b-4885-87e8-271ac787c368.%(ext)s" "https://www.youtube.com/watch?v=y0f7calGty4"
[('-0ew-c0w7uc_000002_000012', False, b"ERROR: Unable to download webpage: <urlopen error [Errno 99] Cannot assign requested address> (caused by URLError(OSError(99, 'Cannot assign requested
 address')))\n"), ('-ri90Xykrxg_000002_000012', False, b"ERROR: Unable to download webpage: <urlopen error [Errno 99] Cannot assign requested address> (caused by URLError(OSError(99, 'Cannot
 assign requested address')))\n"), ('0MJ9Rk0k92Q_000000_000010', False, b"ERROR: Unable to download webpage: <urlopen error [Errno 99] Cannot assign requested address> (caused by URLError(OS
Error(99, 'Cannot assign requested address')))\n"), ('3M8j8pPfGDA_000016_000026', False, b"ERROR: Unable to download webpage: <urlopen error [Errno 110] Connection timed out> (caused by URLE
rror(TimeoutError(110, 'Connection timed out')))\n"), ('3ht3zPeo7x0_000007_000017', False, b"ERROR: Unable to download webpage: <urlopen error [Errno 110] Connection timed out> (caused by UR
LError(TimeoutError(110, 'Connection timed out')))\n"), ('4J22wFT7-LQ_000000_000010', False, b"ERROR: Unable to download webpage: <urlopen error [Errno 110] Connection timed out> (caused by
URLError(TimeoutError(110, 'Connection timed out')))\n"), ('6WPoVkWBBBI_000022_000032', False, b"ERROR: Unable to download webpage: <urlopen error [Errno 99] Cannot assign requested address>
 (caused by URLError(OSError(99, 'Cannot assign requested address')))\n"), ('6q7v3O77NOI_000005_000015', False, b"ERROR: Unable to download webpage: <urlopen error [Errno 99] Cannot assign r
equested address> (caused by URLError(OSError(99, 'Cannot assign requested address')))\n"), ('83DIh7MkoG8_000009_000019', False, b"ERROR: Unable to download webpage: <urlopen error [Errno 99
] Cannot assign requested address> (caused by URLError(OSError(99, 'Cannot assign requested address')))\n"), ('8EMK8AoG3h8_000012_000022', False, b"ERROR: Unable to download webpage: <urlope
n error [Errno 110] Connection timed out> (caused by URLError(TimeoutError(110, 'Connection timed out')))\n"), ('8heUql3B7hg_000010_000020', False, b"ERROR: Unable to download webpage: <urlo
pen error [Errno 110] Connection timed out> (caused by URLError(TimeoutError(110, 'Connection timed out')))\n"), ('94uIR7fT_KM_000003_000013', False, b"ERROR: Unable to download webpage: <ur
lopen error [Errno 110] Connection timed out> (caused by URLError(TimeoutError(110, 'Connection timed out')))\n"), ('AX_CHNc1ThA_000001_000011', False, b"ERROR: Unable to download webpage: <
urlopen error [Errno 110] Connection timed out> (caused by URLError(TimeoutError(110, 'Connection timed out')))\n"), ('GhG5PXDqmUY_000008_000018', False, b"ERROR: Unable to download webpage:
 <urlopen error [Errno 99] Cannot assign requested address> (caused by URLError(OSError(99, 'Cannot assign requested address')))\n"), ('HeEsL9yTiKg_000033_000043', False, b"ERROR: Unable to
download webpage: <urlopen error [Errno 110] Connection timed out> (caused by URLError(TimeoutError(110, 'Connection timed out')))\n"), ('J5n1A-NCuxU_000008_000018', False, b"ERROR: Unable t
o download webpage: <urlopen error [Errno 99] Cannot assign requested address> (caused by URLError(OSError(99, 'Cannot assign requested address')))\n"), ('JqEEGvPSxxA_000001_000011', False,
b"ERROR: Unable to download webpage: <urlopen error [Errno 99] Cannot assign requested address> (caused by URLError(OSError(99, 'Cannot assign requested address')))\n"), ('NgVb5pZw8Ak_000015
_000025', False, b"ERROR: Unable to download webpage: <urlopen error [Errno 99] Cannot assign requested address> (caused by URLError(OSError(99, 'Cannot assign requested address')))\n"), ('N
h25jQx6Y38_000000_000010', False, b"ERROR: Unable to download webpage: <urlopen error [Errno 99] Cannot assign requested address> (caused by URLError(OSError(99, 'Cannot assign requested add
ress')))\n"), ('Q0ITIDt6Z7E_000004_000014', False, b"ERROR: Unable to download webpage: <urlopen error [Errno 110] Connection timed out> (caused by URLError(TimeoutError(110, 'Connection tim
ed out')))\n"), ('VN3-h6-aAls_000004_000014', False, b"ERROR: Unable to download webpage: <urlopen error [Errno 99] Cannot assign requested address> (caused by URLError(OSError(99, 'Cannot a
ssign requested address')))\n"), ('_PwXWcCPrGA_000010_000020', False, b"ERROR: Unable to download webpage: <urlopen error [Errno 110] Connection timed out> (caused by URLError(TimeoutError(1
10, 'Connection timed out')))\n"), ('aBJnzTcJ70o_000002_000012', False, b"ERROR: Unable to download webpage: <urlopen error [Errno 99] Cannot assign requested address> (caused by URLError(OS
Error(99, 'Cannot assign requested address')))\n"), ('ad0MgJg_MBM_000053_000063', False, b"ERROR: Unable to download webpage: <urlopen error [Errno 99] Cannot assign requested address> (caus
ed by URLError(OSError(99, 'Cannot assign requested address')))\n"), ('cjk3tn-kqkU_000003_000013', False, b"ERROR: Unable to download webpage: <urlopen error [Errno 99] Cannot assign request
ed address> (caused by URLError(OSError(99, 'Cannot assign requested address')))\n"), ('dXhPdo54Eko_000001_000011', False, b"ERROR: Unable to download webpage: <urlopen error [Errno 110] Con
nection timed out> (caused by URLError(TimeoutError(110, 'Connection timed out')))\n"), ('e2LIBGlv2Ds_000016_000026', False, b"ERROR: Unable to download webpage: <urlopen error [Errno 99] Ca
nnot assign requested address> (caused by URLError(OSError(99, 'Cannot assign requested address')))\n"), ('fTob9z1OrpM_000010_000020', False, b"ERROR: Unable to download webpage: <urlopen er
ror [Errno 99] Cannot assign requested address> (caused by URLError(OSError(99, 'Cannot assign requested address')))\n"), ('hlUDq3QKZo8_000012_000022', False, b"ERROR: Unable to download web
page: <urlopen error [Errno 99] Cannot assign requested address> (caused by URLError(OSError(99, 'Cannot assign requested address')))\n"), ('iLpLgzIQIkQ_000000_000010', False, b"ERROR: Unab$
e to download webpage: <urlopen error [Errno 99] Cannot assign requested address> (caused by URLError(OSError(99, 'Cannot assign requested address')))\n"), ('iVLuQ9fIW6s_000002_000012', Fal$
e, b"ERROR: Unable to download webpage: <urlopen error [Errno 99] Cannot assign requested address> (caused by URLError(OSError(99, 'Cannot assign requested address')))\n"), ('kwuAR3lbRxI_00$
010_000020', False, b"ERROR: Unable to download webpage: <urlopen error [Errno 99] Cannot assign requested address> (caused by URLError(OSError(99, 'Cannot assign requested address')))\n"),
('mKAvzPnh_Yw_000009_000019', False, b"ERROR: Unable to download webpage: <urlopen error [Errno 99] Cannot assign requested address> (caused by URLError(OSError(99, 'Cannot assign requested
address')))\n"), ('oOpaLCB7PbQ_000001_000011', False, b"ERROR: Unable to download webpage: <urlopen error [Errno 99] Cannot assign requested address> (caused by URLError(OSError(99, 'Cannot
assign requested address')))\n"), ('petld-72OXM_000001_000011', False, b"ERROR: Unable to download webpage: <urlopen error [Errno 99] Cannot assign requested address> (caused by URLError(OSE
rror(99, 'Cannot assign requested address')))\n"), ('r81d5eNm9Rs_000000_000010', False, b"ERROR: Unable to download webpage: <urlopen error [Errno 99] Cannot assign requested address> (cause
d by URLError(OSError(99, 'Cannot assign requested address')))\n"), ('r9INzx9GaAk_000015_000025', False, b"ERROR: Unable to download webpage: <urlopen error [Errno 99] Cannot assign requeste
d address> (caused by URLError(OSError(99, 'Cannot assign requested address')))\n"), ('rpaTvmTPC0M_000002_000012', False, b"ERROR: Unable to download webpage: <urlopen error [Errno 99] Canno
t assign requested address> (caused by URLError(OSError(99, 'Cannot assign requested address')))\n"), ('tA2patyR1Pg_000009_000019', False, b"ERROR: Unable to download webpage: <urlopen error
 [Errno 99] Cannot assign requested address> (caused by URLError(OSError(99, 'Cannot assign requested address')))\n"), ('tChIbM9u7t0_000003_000013', False, b"ERROR: Unable to download webpag
e: <urlopen error [Errno 99] Cannot assign requested address> (caused by URLError(OSError(99, 'Cannot assign requested address')))\n"), ('u5u9y_ltKCI_000008_000018', False, b"ERROR: Unable t
o download webpage: <urlopen error [Errno 99] Cannot assign requested address> (caused by URLError(OSError(99, 'Cannot assign requested address')))\n"), ('wL4EN5CBU9Q_000003_000013', False,
b"ERROR: Unable to download webpage: <urlopen error [Errno 99] Cannot assign requested address> (caused by URLError(OSError(99, 'Cannot assign requested address')))\n"), ('wdCcRngfyZw_000011
_000021', False, b"ERROR: Unable to download webpage: <urlopen error [Errno 99] Cannot assign requested address> (caused by URLError(OSError(99, 'Cannot assign requested address')))\n"), ('w
u3oEKpw6N4_000000_000010', False, b"ERROR: Unable to download webpage: <urlopen error [Errno 99] Cannot assign requested address> (caused by URLError(OSError(99, 'Cannot assign requested add
ress')))\n"), ('y0f7calGty4_000002_000012', False, b"ERROR: Unable to download webpage: <urlopen error [Errno 99] Cannot assign requested address> (caused by URLError(OSError(99, 'Cannot ass
ign requested address')))\n")]
DeprecationWarning: 'source deactivate' is deprecated. Use 'conda deactivate'.

Then i try it with a single command : 
(base) root@LAB_VM:/home/mmaction2/tools/data/kinetics# youtube-dl --quiet --no-warnings --no-check-certificate -f mp4 -o "/tmp/kinetics/48058ab1-7d5b-4885-87e8-271ac787c368.%(ext)s" "https://www.youtube.com/watch?v=y0f7calGty4"
ERROR: Unable to download webpage: <urlopen error [Errno 99] Cannot assign requested address> (caused by URLError(OSError(99, 'Cannot assign requested address')))

It still faild. The weird thing is that i can access youtube webpage, but why cann't i download its video. Could you please share me the result of runing above single download command in your computer ? I want to see what the right result looks like, thanks !

**Comment by innerlee** [comment]
The error message is shown above

> urlopen error [Errno 99] Cannot assign requested address

Could you search the web to see if there are solutions to this?
