### ISSUE TITLE
About the label_map.txt in /demo

### ISSUE THREAD

**Issue by wzan0001** [open-mmlab/mmaction2#401]
Which dataset is the label_map.txt in /demo generated from? Kinetics400? How to achieve it, and what should I do if I want the label_map of MIT dataset?

**Comment by dreamerlin** [comment]
The `label_map.txt` is generated from Kinetics400 labels. You can customize your `label_map.txt` from `MIT` and use the corresponding checkpoint

**Comment by wzan0001** [comment]
yeah, I mean, how to determine the order of labels?

**Comment by dreamerlin** [comment]
It should be consistent with the one that is used by your checkpoint.
