### ISSUE TITLE
OSError: MoviePy Error: creation of None failed because of the following error:

### ISSUE THREAD

**Issue by 13517592731** [open-mmlab/mmaction2#402]
详细问题：convert-im6.q16: not authorized `@/tmp/tmpyk4jyj0f.txt' @ error/property.c/InterpretImageProperties/3516.
convert-im6.q16: no images defined `PNG32:/tmp/tmpj9_wul8i.png' @ error/convert.c/ConvertImageCommand/3258.
.

.This error can be due to the fact that ImageMagick is not installed on your computer, or (for Windows users) that you didn't specify the path to the ImageMagick binary in file conf.py, or that the path you specified is incorrect

是权限问题，修改权限就行了
cat /etc/ImageMagick-6/policy.xml | sed 's/none/read,write/g'> /etc/ImageMagick-6/policy.xml

**Comment by innerlee** [comment]
Thanks, @dreamerlin do we have a faq for this?

**Comment by dreamerlin** [comment]
Agree, i think we can write a `faq.md` for common issues.

**Comment by dreamerlin** [comment]
If u haven't solved the problem, try [this](https://github.com/open-mmlab/mmaction2/blob/master/docs/install.md#requirements)
