### ISSUE TITLE
Finetune pretrained model with custom number of classes

### ISSUE THREAD

**Issue by ayanasser** [open-mmlab/mmaction2#408]
Hi, 
Do you have the ability for finetuning slowfast model but with 2 classes only?
in another word (could I change the number of classes of the last layer of "pretrained slowfastNet model"

because I want to take the feature from that pretrained model then classify those features with a simple 2 dense layers,
but I need to end up with one model, not 2 models (one for feature extraction and the other for classifying)
Thanks in advanced

**Comment by dreamerlin** [comment]
Refer to: https://github.com/open-mmlab/mmaction2/issues/19#issuecomment-702175631
Or you can modify [load_from](https://github.com/open-mmlab/mmaction2/blob/master/configs/recognition/slowfast/slowfast_r50_4x16x1_256e_kinetics400_rgb.py#L134) to the pretrained model checkpoint path or url, then change the [num_classes](https://github.com/open-mmlab/mmaction2/blob/master/configs/recognition/slowfast/slowfast_r50_4x16x1_256e_kinetics400_rgb.py#L33), it will ignore the unexpected keys.

**Comment by ayanasser** [comment]
I want to freeze all the layers except the classifier layer (the last 2 layers), Is it accessible to freeze them?

**Comment by dreamerlin** [comment]
Try to use `with torch.no_grad():` to wrap [`x = self.extract_feat(imgs)`](https://github.com/open-mmlab/mmaction2/blob/master/mmaction/models/recognizers/recognizer2d.py#L17), it will freeze the backbone.

**Comment by dreamerlin** [comment]
And If you feel we have help you, give us a STAR! : )

**Comment by ayanasser** [comment]
you helped me a lot, sure I will, thank u ^^

**Comment by ayanasser** [comment]
when i try to load from this link:
load_from = 'https://download.openmmlab.com/mmaction/recognition/slowfast/slowfast_r50_256p_4x16x1_256e_kinetics400_rgb/slowfast_r50_256p_4x16x1_256e_kinetics400_rgb_20200728-145f1097.pth'

it gives me this error, do you have any  idea?:
   raise URLError(err)
urllib.error.URLError: <urlopen error [Errno -2] Name or service not known>

**Comment by ayanasser** [comment]
Hi again :D, u said before that i could freeze the backbone by wrapping the features extracted with torch.no_grad(), 
you mean by the backbone "resnet50" or all the layers above the final softmax layer?
because while finetuning the slowfast model i need to freeze all the layers above the final softmax one,

second thing is i found that the backbone recognizer for slowfast is 3D not 2D, Is there a big difference between the 2 recognizers whilem finetunining the model with my custom video dataset ?
