### ISSUE TITLE
Iteration Plan - Dec 2020

### ISSUE THREAD

**Issue by dreamerlin** [open-mmlab/mmaction2#412]
Since MMAction2 v0.9 has been released, now it's time to plan for the next iteration, i.e. v0.10.0.
This will be a one-month iteration and our focus in this iteration is to solve the legacy from the last version and do some **harmless** refactoring to our repo.

**Algorithms**:
- [x] FastRCNN on AVA (https://github.com/open-mmlab/mmaction2/pull/351)
    - Integration with MMDet
    - Seek for good practices for AVA spatio-temporal pipeline
- [x] SlowFast on AVA (https://github.com/open-mmlab/mmaction2/pull/351)
- [x] AVSlowFast (https://github.com/open-mmlab/mmaction2/pull/355)
- [ ] ~~TAM~~ (https://github.com/open-mmlab/mmaction2/pull/304)
- [ ] ~~SCSampler~~ (https://github.com/open-mmlab/mmaction2/pull/381)
    - Implement Visual sampler and audio sampler
- [ ] ~~MOC~~ (https://github.com/open-mmlab/mmaction2/pull/308, https://github.com/open-mmlab/mmaction2/pull/326)
  - Construct data pipeline for UCF101-24 and JHMDB
  - Improve the efficiency of tubelet dataset pipeline
  - Implement MOC

**Improvement**
- [ ] ~~Improve performance of AudioOnly~~
- [ ] ~~Refactor our config file structure~~ (https://github.com/open-mmlab/mmaction2/pull/488)
- [ ] ~~Refactor our unittest file structure~~ (https://github.com/open-mmlab/mmaction2/pull/433)

---

### Deferred
- [ ] MOC (https://github.com/open-mmlab/mmaction2/pull/308, https://github.com/open-mmlab/mmaction2/pull/326)
  - Construct data pipeline for UCF101-24 and JHMDB
  - Improve the efficiency of tubelet dataset pipeline
  - Implement MOC
- [ ] Improve performance of AudioOnly
- [ ] Refactor our config file structure (https://github.com/open-mmlab/mmaction2/pull/488)
- [ ] Refactor our unittest file structure (https://github.com/open-mmlab/mmaction2/pull/433)
- [ ] TAM (https://github.com/open-mmlab/mmaction2/pull/304)
- [ ] SCSampler (https://github.com/open-mmlab/mmaction2/pull/381)
    - Implement Visual sampler and audio sampler

**Comment by irvingzhang0512** [comment]
Plan to implement
+ TSM-MobileNetV2
+ YOWO(After tubedataset is ready)

**Comment by wwdok** [comment]
Do you have plan to add action localization demo ? It seems  if we input video, it can generate proposal file that like caption ?

**Comment by innerlee** [comment]
@wwdok Feature requests goes ➡️  here https://github.com/open-mmlab/mmaction2/issues/19

**Comment by wwdok** [comment]
Got it, Thank you !
