### ISSUE TITLE
How can I implement resnet34 backbone with tsm?

### ISSUE THREAD

**Issue by Ultraman82** [open-mmlab/mmaction2#426]
Where should I change? 
And my classes are 21. Im using kinetic 400 based config file, any advice?
Thanks guys.

model = dict(
    type='Recognizer2D',
    backbone=dict(
        type='ResNetTSM',
        pretrained='torchvision://resnet34',
        depth=34,
        norm_eval=False,
        shift_div=8),
    cls_head=dict(
        type='TSMHead',
        num_classes=21,
        in_channels=2048,
        spatial_type='avg',
        consensus=dict(type='AvgConsensus', dim=1),
        dropout_ratio=0.5,
        init_std=0.001,
        is_shift=True))

**Comment by SuX97** [comment]
Change your current in_channels in the cls_head cfg to 512 would work.

**Comment by Ultraman82** [comment]
Thanks!
