### ISSUE TITLE
Running verification script in `install.md` gives `IndexError: "frame_id" must be between 0 and -1` error

### ISSUE THREAD

**Issue by yxchng** [open-mmlab/mmaction2#428]
Running verification script in `install.md` gives `IndexError: "frame_id" must be between 0 and -1` error. Can I know how to resolve this problem?

**Comment by innerlee** [comment]
Does the video file plays nicely?

**Comment by yxchng** [comment]
@innerlee yes

**Comment by innerlee** [comment]
Could you try to read the demo video file using opencv directly? 
https://opencv-python-tutroals.readthedocs.io/en/latest/py_tutorials/py_gui/py_video_display/py_video_display.html#playing-video-from-file

**Comment by yxchng** [comment]
@innerlee seems like it is because my opencv was not able to read videos. after reinstalling, it works now. thanks.

**Comment by Note-Liu** [comment]
i also meet the bug,how did you solve?
