### ISSUE TITLE
Tutorial/Inclusion of new models (Rubiksnet) for action recognition

### ISSUE THREAD

**Issue by Anto09** [open-mmlab/mmaction2#434]
**Description**
If possible, a guide on how to introduce and use models not found in the model zoo; specifically Rubiksnet. 
Otherwise, just a request to include Rubiksnet pretrained models, specifically on the Kinetics 400 dataset, into the Model Zoo.

**Motivation**
Desire to use and compare the performance of new action recognition models using the well-built pipelines of this repository.

**Related resources**
https://github.com/StanfordVL/RubiksNet

**Additional context**
Should a guide be given, I'd like to personally do it and then create a PR.

**Comment by innerlee** [comment]
Adding support for new model is not hard. Here is an example : https://github.com/open-mmlab/mmaction2/pull/226

**Comment by Anto09** [comment]
@innerlee thanks!

**Comment by dreamerlin** [comment]
You can also refer to the [tutorial](https://github.com/open-mmlab/mmaction2/blob/master/docs/tutorials/new_modules.md#develop-new-components) or [readthedocs](https://mmaction2.readthedocs.io/en/latest/tutorials/new_modules.html#develop-new-components)

**Comment by dreamerlin** [comment]
And for cuda ops, you can add them to mmcv in `mmcv.ops` part like [this](https://github.com/open-mmlab/mmcv/blob/master/mmcv/ops/tin_shift.py), which is used in [TIN](https://github.com/open-mmlab/mmaction2/blob/master/mmaction/models/backbones/resnet_tin.py#L10).
