### ISSUE TITLE
Visualize the training accuracy/loss curves in real-time

### ISSUE THREAD

**Issue by Cogito2012** [open-mmlab/mmaction2#438]
Does this repo support real-time monitoring the training curves of accuracy and loss values? 

I only find there are some tools in `tools/analysis/` to plot accuracy and losses, but they cannot be used in **real-time** during training. This would be important as we typically need to have a global view on the performance during training. It's strongly suggested to include the real-time visualization option by using some libs such as tensorboard to this end.

**Comment by irvingzhang0512** [comment]
You can use `TensorboardLoggerHook` in `log_config`. For example, uncomment this [line](https://github.com/open-mmlab/mmaction2/blob/master/configs/recognition/tsm/tsm_r50_1x1x8_50e_kinetics400_rgb.py#L114)

**Comment by Cogito2012** [comment]
@irvingzhang0512 Got it! Thanks.

**Comment by irvingzhang0512** [comment]
@dreamerlin could this issue be faq , or at least mention this somewhere. My colleagues asked this a few times when using mmaction & mmdetection

**Comment by dreamerlin** [comment]
Thanks, I will add it to our faq.md.
