### ISSUE TITLE
How to show test results?(especially the wrong results)

### ISSUE THREAD

**Issue by SKBL5694** [open-mmlab/mmaction2#441]
I use some my own data during the training and testing, however, the acc is not satisfactory to me. So I want to know which test samples have inaccurate results. Is there any way I can get that?

**Comment by innerlee** [comment]
Do you want

* output & save all predictions, or
* customize evaluation, so that it reports wrong predictions?

**Comment by SKBL5694** [comment]
I want to save all predictions with test file names so that I can find whether each prediction is right.

**Comment by innerlee** [comment]
I think we have supported this? @kennymckormick

**Comment by SKBL5694** [comment]
> I think we have supported this? @kennymckormick

Do you mean during testing, use the command --out xxx.json？

**Comment by kennymckormick** [comment]
> > I think we have supported this? @kennymckormick
> 
> Do you mean during testing, use the command --out xxx.json？

Yes (or output pickle). Besides, the testing output has exactly the same order as the test dataset. So no need to store file names.

**Comment by SKBL5694** [comment]
> Yes (or output pickle). Besides, the testing output has exactly the same order as the test dataset. So no need to store file names.
Got it. Thx. :)

**Comment by SKBL5694** [comment]
> > > I think we have supported this? @kennymckormick
> > 
> > 
> > Do you mean during testing, use the command --out xxx.json？
> 
> Yes (or output pickle). Besides, the testing output has exactly the same order as the test dataset. So no need to store file names.

Got it. Thx. :)

**Comment by keloee** [comment]
> > > I think we have supported this? @kennymckormick
> > 
> > 
> > Do you mean during testing, use the command --out xxx.json？
> 
> Yes (or output pickle). Besides, the testing output has exactly the same order as the test dataset. So no need to store file names.

by the same order you mean the same order of the annfile or the same order of the test directory?
