### ISSUE TITLE
When I debug the test.py ,a KEYERROR follow.

### ISSUE THREAD

**Issue by xiumm9527** [open-mmlab/mmaction2#442]
When I tested according to the official website tutorial , the following errors occurred.
'RawFrameDecode is not in the pipeline registry'
The file I use is c3d/c3d_sports1m_16x1x1_45e_ucf101_rgb.py. I would appreciate your help if make it. Thanks!

**Comment by innerlee** [comment]
RawFrameDecode IS a valid pipeline.

Please check if the installation is correct

```python
import mmaction
print(mmaction.__file__)
print(mmaction.version
from mmaction.datasets.pipelines import  RawFrameDecode 
```

**Comment by xiumm9527** [comment]
Thank you for your answer. I can reference RawFrameDecode through the command you gave, but the error is still the same before running. What aspects can I check again？

**Comment by dreamerlin** [comment]
> Thank you for your answer. I can reference RawFrameDecode through the command you gave, but the error is still the same before running. What aspects can I check again？

You may need to check whether there is another `MMAction2` repo which is in low version and may lead to this error. You can  try `export PYTHONPATH=`pwd`:$PYTHONPATH` in the latest repo's root path, and then verify it again.

**Comment by dreamerlin** [comment]
How is it going now ? @xiumm9527
