### ISSUE TITLE
I try to use this model on my webcam, but i meet with one error as folllows:

### ISSUE THREAD

**Issue by lenka844** [open-mmlab/mmaction2#448]
```bash
(new-open-mmlab) ljh@vision-Z370-HD3:~/MMACTION2/1.mmaction2/1.mmaction-init-master$ python demo/webcam_demo.py configs/recognition/tsn/tsn_r50_video_inference_1x1x3_100e_kinetics400_rgb.py   checkpoints/tsn_r50_1x1x3_100e_kinetics400_rgb_20200614-e508be42.pth demo/label_map.txt --average-size 5   --threshold 0.2 --device cpu
[ WARN:0] global /tmp/pip-req-build-cg56sov1/opencv/modules/videoio/src/cap_v4l.cpp (893) open VIDEOIO(V4L2:/dev/video0): can't open camera by index
Press "Esc", "q" or "Q" to exit
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/home/ljh/.conda/envs/new-open-mmlab/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/home/ljh/.conda/envs/new-open-mmlab/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "demo/webcam_demo.py", line 57, in show_results
    frame_queue.append(np.array(frame[:, :, ::-1]))
TypeError: 'NoneType' object is not subscriptable
```

i have tried to change the default id of the cam,but it didnt work!

**Comment by innerlee** [comment]
> open VIDEOIO(V4L2:/dev/video0): can't open camera by index

Opencv cannot open camera.

**Comment by lenka844** [comment]
> > open VIDEOIO(V4L2:/dev/video0): can't open camera by index
> 
> Opencv cannot open camera.



> > open VIDEOIO(V4L2:/dev/video0): can't open camera by index
> 
> Opencv cannot open camera.

hi @innerlee ,thanks for your help, but i dont get what you said,  can you repeat it thanks again!

**Comment by innerlee** [comment]
The demo uses opencv to read frames from webcam. Look at the end of the second line in your first post, it repots that the webcam cannot be opened.

So you may first try this https://opencv-python-tutroals.readthedocs.io/en/latest/py_tutorials/py_gui/py_video_display/py_video_display.html#capture-video-from-camera to see if your opencv installation is correct, and if the webcam works properly

**Comment by lenka844** [comment]
> The demo uses opencv to read frames from webcam. Look at the end of the second line in your first post, it repots that the webcam cannot be opened.
> 
> So you may first try this https://opencv-python-tutroals.readthedocs.io/en/latest/py_tutorials/py_gui/py_video_display/py_video_display.html#capture-video-from-camera to see if your opencv installation is correct, and if the webcam works properly

hi @innerlee  thanks for your help, in the end i found this is because i dont have the permission to open the cam, so i  change the permission, then i open the cam successfully, but now i meet a new question, the window just show wait for action but dont react to the action in front of it. here is the error code.
QObject::moveToThread: Current thread (0x7f98b4003050) is not the object's thread (0x7f98d10c9700).
Cannot move to target thread (0x7f98b4003050)

**Comment by innerlee** [comment]
Please open a new issue since it is a different problem now. And also please provide more info about the error to help us diagnose

**Comment by lenka844** [comment]
> Please open a new issue since it is a different problem now. And also please provide more info about the error to help us diagnose

ok thanks again!
