### ISSUE TITLE
About data augmentation ThreeCrop 

### ISSUE THREAD

**Issue by SKBL5694** [open-mmlab/mmaction2#449]
I know the operation of ThreeCrop is 'Crop the images equally into three crops with equal intervals along the shorter side'. But I'm confused about how the ThreeCrop affects the final results. In the other hand, on what circumstance should I use ThreeCrop?

**Comment by innerlee** [comment]
More crops, more data are used in inference, hence possibly results in higher accuracy.

**Comment by SKBL5694** [comment]
> More crops, more data are used in inference, hence possibly results in higher accuracy.

I'm not sure if ThreeCrop divides a full frame to three smaller ones then the nn will treat it in another unknown way.

**Comment by innerlee** [comment]
Three crops are treated as independent clips before sending to the network.
In the end, their predictions are fused together.

**Comment by SKBL5694** [comment]
> Three crops are treated as independent clips before sending to the network.
> In the end, their predictions are fused together.

Does that mean I need to use it carefully? Because it may cause my detection target(maybe a person which I want to recognize his movements) to be cut apart or it may cause one or two clips don't have the target at all.

**Comment by innerlee** [comment]
No, just use it and compare the result with single crop.

As long as any one of the crops succeeded, the fused result might be good

**Comment by SKBL5694** [comment]
> No, just use it and compare the result with single crop.
> 
> As long as any one of the crops succeeded, the fused result might be good

I get it. Thx :)

**Comment by SKBL5694** [comment]
> > No, just use it and compare the result with single crop.
> > As long as any one of the crops succeeded, the fused result might be good
> 
> I get it. Thx :)

Sry. One more question. May I use it during my training or testing or both?

**Comment by innerlee** [comment]
Three crop is useless for traning

**Comment by SKBL5694** [comment]
> Three crop is useless for training

Oh, only in testing, I guess that's why you say 'As long as any one of the crops succeeded, the fused result might be good'
