### ISSUE TITLE
Feature frame in ActivityNet annotation

### ISSUE THREAD

**Issue by orikorner** [open-mmlab/mmaction2#453]
In ActivityNet annotation how do I calculate the value of "feature_frame" key for each video?
I am using my own dataset and feature extraction is done using TSN.

**Comment by kennymckormick** [comment]
We extract ANet feature from the raw untrimmed videos, and I'm not quite sure what's the usage of "feature_frame" in annotations. This field is not required if you follow our feature extraction pipeline. For example, you can fill in 0 for all video annos.

**Comment by orikorner** [comment]
I see it is used in line 1553 in loading.py:
corrected_second = float(feature_frame) / video_frame * video_second

which affects the gt bbox in the following lines:
current_start = max(min(1, annotation['segment'][0] / corrected_second), 0)
current_end = max(min(1, annotation['segment'][1] / corrected_second), 0)
gt_bbox.append([current_start, current_end])

So its seems like it affects the training of BMN, doesnt it?

**Comment by SuX97** [comment]
@tony2016uestc Might have some ideas about what that is. Seems that it means the actual number of frames that generate the feature for training.

**Comment by tony2016uestc** [comment]
Yes, the value of `feature_frame` is `num_frames // 16 * 16`, because the feature is extracted by TSN and the interval of snippets is set to 16 on ActivityNet.

For example, frame_id 0, 16...128 of a video with 130 frames will be sampled to generate features, so `feature_frame` is 128.

**Comment by mytk2012** [comment]
Can you distribute label tools in activitynet format?
