### ISSUE TITLE
DecordDecode stucked when calling container[idx].asnumpy()

### ISSUE THREAD

**Issue by Cogito2012** [open-mmlab/mmaction2#472]
When I was testing the HMDB-51 val dataset with the trained I3D model, the program got stuck in calling [`data = test_pipeline(data)`](https://github.com/open-mmlab/mmaction2/blob/777546f27f8f5a3c83e10d966e2149be2fc9fa31/mmaction/apis/inference.py#L107). This problem currently was found when processing one of the HMDB-51 testing videos: `data/hmdb51/videos/shoot_bow/ArcheryMaster_shoot_bow_u_cm_np1_ri_med_0.avi`. 

By tracing the bottleneck problem for this video, I found the program actually get stuck at [the line 974 in mmaction/datasets/pipelines/loading.py](https://github.com/open-mmlab/mmaction2/blob/777546f27f8f5a3c83e10d966e2149be2fc9fa31/mmaction/datasets/pipelines/loading.py#L974). And the following figure reported the possible deadlock problem:

![bug](https://user-images.githubusercontent.com/13028018/102851255-52c4c400-43e9-11eb-9c13-7e3e8c35c4f0.png)

My testing script is as following:
```shell
python demo/demo.py \
    configs/recognition/i3d/finetune_ucf101_i3d_r50_video_inference_32x2x1_100e_kinetics400_rgb.py \
    work_dirs/finetune_ucf101_i3d_r50_dense_32x2x1_100e_kinetics400_rgb/latest.pth \
    data/hmdb51/videos/shoot_bow/ArcheryMaster_shoot_bow_u_cm_np1_ri_med_0.avi \
    data/ucf101/annotations/classInd.txt
```

Since for other HMDB-51 videos, no such problem occurs and the video that caused this problem can be normally played, it's really weird and difficult for me to fix the bug. Hope anyone can help for this problem. Thanks!

**Comment by innerlee** [comment]
You can try pyav decoder.

**Comment by Cogito2012** [comment]
@innerlee When I changed the decoder to pyav, I got the following error when running the demo.py

```shell
Traceback (most recent call last):
  File "demo/demo.py", line 169, in <module>
    main()
  File "demo/demo.py", line 139, in main
    model, args.video, args.label, use_frames=args.use_frames)
  File "/home/exx/mmaction2/mmaction/apis/inference.py", line 107, in inference_recognizer
    data = test_pipeline(data)
  File "/home/exx/mmaction2/mmaction/datasets/pipelines/compose.py", line 41, in __call__
    data = t(data)
  File "/home/exx/mmaction2/mmaction/datasets/pipelines/loading.py", line 746, in __call__
    self.file_client = FileClient(self.io_backend, **self.kwargs)
  File "/home/exx/.conda/envs/mmaction/lib/python3.7/site-packages/mmcv/fileio/file_client.py", line 223, in __init__
    self.client = self._backends[backend](**kwargs)
TypeError: HardDiskBackend() takes no arguments
```

Not clear about what caused this error. Probably the mmcv version (1.2.1) I installed is not compatible with the mmaction version (0.9.0+ce64e57). But anyway, when I changed the decoder to OpenCV, it works now!

**Comment by innerlee** [comment]
If the video is not large, could you share it? github now supports attaching mp4

**Comment by Cogito2012** [comment]
The video is with avi format which is not supported by github. Here, I share it with the google drive link:
[ArcheryMaster_shoot_bow_u_cm_np1_ri_med_0.avi](https://drive.google.com/file/d/1LR1VPjZyKT2gp-9jrkzlu5-GevThDCzi/view?usp=sharing)

You can test it will Decord or PyAV decoder and see if they work for this video.

**Comment by Cogito2012** [comment]
@innerlee If the OpenCV Decoder is used, do I need to manually set `to_bgr=True` in `img_norm_cfg`?  It's not clear whether transforming frames into RGB format is performed **before or after** applying the `mean` and `std`.

**Comment by innerlee** [comment]
The to bgr setting is unrelated to backend. So u can follow existing config
