### ISSUE TITLE
How to deal with short videos/frames ?

### ISSUE THREAD

**Issue by SKBL5694** [open-mmlab/mmaction2#473]
In my dataset, there are some videos last only 1 or 2 seconds(such as the action 'jump') with the fps about 25 and some videos may last 7 seconds or more.This cause a question how to set the length of input frames. most videos of the action 'jump' may only have 30-40 frames or less while other actions may have 50+frames. So I can not use the default params in the configs, such as 'clip_len'=32, 'frame_interval'=2, because it at least needs 64 frames per video. The method I used to solve ths question is to use I3d configs and I change the configs to 'clip_len'=16, 'frame_interval'=2(I delete some data manually), and I'm not sure if it will take bad effect on my result. Recently I want to train my datasets by the slowfast config.I found it may need more frames than I3d, so I asked you for a solution. Could you give me some advice about it?

**Comment by SuX97** [comment]
Slowfast takes 32 frames with 2 as intervals, total footage of 64 frames. You may as well shrink the span by 16x2 or even 16x1. As long as the clip_len is bigger than `resample_rate` in the code, it will not cause a vital error.

BTW, 

> some videos may last 7 seconds or more

in such case, maybe use 2D models such as TSN, TSM, TIN. May perform better than densely sampled 3D models.

**Comment by SKBL5694** [comment]
@SuX97 thx for your help. I will try TSM for my task. But is there any good solution to deal with the question, not for a specific model but for all models. Do I have to sacrifice the length of most videos for shorter videos?
