### ISSUE TITLE
How to prepare data/ActivityNet/anet_anno_val.json

### ISSUE THREAD

**Issue by wwdok** [open-mmlab/mmaction2#480]
Hi, there, is there the download link of `data/ActivityNet/anet_anno_val.json` or the method to generate it ? Thanks !

**Comment by dreamerlin** [comment]
you can refer to https://github.com/open-mmlab/mmaction2/tree/master/tools/data/activitynet

**Comment by wwdok** [comment]
Got it, thanks for your quick response !
