### ISSUE TITLE
Are the commands to preprocess Kinetics dataset in the Preparing Kinetics readme which gives videos of resolution 340x256 different from the resolution used in configs?

### ISSUE THREAD

**Issue by yxchng** [open-mmlab/mmaction2#482]
https://github.com/open-mmlab/mmaction2/tree/master/configs/recognition/slowfast
https://github.com/open-mmlab/mmaction2/tree/master/configs/recognition/r2plus1d

For example, in these configs, the model use short side 320 or short side 256.

Why don't extract_rgb_frames.sh, extract_rgb_frames_opencv.sh, and extract_frames.sh follow that and gives short side 320 or short side 256?

**Comment by innerlee** [comment]
You can modify the scripts to get preferred resolution. See the docs

![image](https://user-images.githubusercontent.com/9464825/103049880-e7881700-45cd-11eb-9d99-3ac3799c2ba0.png)


The default setting occupies smaller disk space, and was historically used by UCF101.

**Comment by yxchng** [comment]
@innerlee yes, i know that i can modify the commands but my question is why is the default setting 340x256 when there is no model that is using that? why not change the default to something that aligns with the is used by the models?

**Comment by innerlee** [comment]
The processing is not wrong. Generally speaking, higher resolution is better. There is a benchmark on resolutions in docs.

![image](https://user-images.githubusercontent.com/9464825/103052249-a135b680-45d3-11eb-9c54-b1600c43915d.png)

**Comment by innerlee** [comment]
@dreamerlin We can add more info on choosing resolutions in the data preparation doc.

**Comment by kennymckormick** [comment]
> @innerlee yes, i know that i can modify the commands but my question is why is the default setting 340x256 when there is no model that is using that? why not change the default to something that aligns with the is used by the models?
> 
> If I have not read the configs, I would not know that I am doing the preprocessing wrong.

That's right, the default setting is 340x256 because of some legacy issues, will raise a PR to switch to shortside 256
