### ISSUE TITLE
Is the original resolution used for SlowFast different from what is mentioned in the original paper?

### ISSUE THREAD

**Issue by yxchng** [open-mmlab/mmaction2#483]
<img width="528" alt="Screenshot 2020-12-24 at 10 29 32 AM" src="https://user-images.githubusercontent.com/10518587/103052107-47cd8780-45d3-11eb-8e26-bd482ca4894e.png">

Here it says "with a shorter side randomly sampled from [256,320]". From what I understand, this means we don't fix the original resolution to be short-side 256 or short-side 320 (which is what is done in this repo), but do the resize online such that they can be any value between 256 and 320. Is that right? Or am I misunderstanding?

**Comment by innerlee** [comment]
It has nothing to do with original resolution.

Whether resizing or not as pre-pre-processing, totally depends on the performance of your machine. If there are no storage issue, IO issue, and do not cares about decoding speed, then you may skip the initial resizing.

**Comment by yxchng** [comment]
@innerlee Yes, I understand that. What I am trying to ask is is the implementation here different from the paper?

**Comment by innerlee** [comment]
See https://github.com/open-mmlab/mmaction2/blob/f4b165b812645d2fb63fee5ba7d0df58693abcc8/mmaction/datasets/pipelines/augmentations.py#L809-L811

**Comment by SuX97** [comment]
There exist slight differences in the data pipeline. For SlowFast, the paper indicates a pipeline of the first random rescales to 320 or 256, then a random crop of 224. For our repo, we first rescale to 256 and then apply a `RandomResized` crop, which has a bigger diversity.

This pipeline is used to be consist of MMAction1,  we may also benchmark the slowfast with `RandomRescale` + `RandomCrop`. @innerlee

**Comment by innerlee** [comment]
Right, the current config is different, as shown in the config file.
If one want to use the description in paper, `RandomRescale` can be used.

Personally I think it is not worthy to train a `RandomRescale` version. Let's see if anyone need it. If anyone wants ckpt for `RandomRescale`, please reply below.

**Comment by SuX97** [comment]
Hi @yxchng , to clarify:

1. Is the **original resolution** used for SlowFast different from what is mentioned in the original paper?

Yes.

The original resolution of PySlowfast is randomly selected between [256, 320]. But ours is fixed to 256 or 320.

2. Is the **actual resolution** used for SlowFast different from what is mentioned in the original paper?

No.

They are both 224 * 224 for training, and 256 * 256 for testing.

3. Is the **data pipelines** used in SlowFast different from what is mentioned in the original paper?

Yes.

There exist slight differences in the data pipeline. For SlowFast, the paper indicates a pipeline of the first random rescales to 320 or 256, then a random crop of 224. For our repo, we first rescale to 256 and then apply a RandomResized crop.
