### ISSUE TITLE
How to modify parameters through command line when training with multiple gpus using ./tools/dist_train.sh?

### ISSUE THREAD

**Issue by yxchng** [open-mmlab/mmaction2#485]
Based on the getting_started readme, we should use ./tools/dist_train.sh to train with multiple gpus. However, this script does not seem to support changing parameters through the command line? Can we do that for mmaction2?

**Comment by dreamerlin** [comment]
https://github.com/open-mmlab/mmaction2/blob/master/tools/dist_train.sh#L9, `${@:3}` can be used to change parameters through the command line

**Comment by innerlee** [comment]
Any arguments from the third one are captured by `${@:3}` in https://github.com/open-mmlab/mmaction2/blob/master/tools/dist_train.sh#L9 and then passed to `train.py`.

**Comment by innerlee** [comment]
It would be good to add comments in the bash script to explain this

**Comment by yxchng** [comment]
@innerlee @dreamerlin modified parameters are not showing on the log. Is that expected?

**Comment by innerlee** [comment]
Smells abnormal. An example would be appriciated

**Comment by yxchng** [comment]
> 2020-12-28 12:40:46,053 INFO Running /opt/tiger/mmaction2/launch.sh configs/recognition/tsn/tsn_r50_1x1x3_75e_ucf101_rgb.py 8 --cfg-options model.backbone.depth=34...
> fatal: not a git repository (or any of the parent directories): .git
> fatal: not a git repository (or any of the parent directories): .git
> 2020-12-28 12:40:56,555 - mmaction - INFO - Environment info:
> ------------------------------------------------------------
> sys.platform: linux
> Python: 3.7.3 (default, Jul 25 2020, 13:03:44) [GCC 8.3.0]
> CUDA available: True
> GPU 0,1,2,3,4,5,6,7: Tesla V100-SXM2-32GB
> CUDA_HOME: /usr/local/cuda
> NVCC: Build cuda_11.0_bu.TC445_37.28845127_0
> GCC: gcc (Debian 8.3.0-6) 8.3.0
> PyTorch: 1.7.1+cu110
> PyTorch compiling details: PyTorch built with:
>   - GCC 7.3
>   - C++ Version: 201402
>   - Intel(R) Math Kernel Library Version 2020.0.0 Product Build 20191122 for Intel(R) 64 architecture applications
>   - Intel(R) MKL-DNN v1.6.0 (Git Hash 5ef631a030a6f73131c77892041042805a06064f)
>   - OpenMP 201511 (a.k.a. OpenMP 4.5)
>   - NNPACK is enabled
>   - CPU capability usage: AVX2
>   - CUDA Runtime 11.0
>   - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80
>   - CuDNN 8.0.5
>   - Magma 2.5.2
>   - Build settings: BLAS=MKL, BUILD_TYPE=Release, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DUSE_VULKAN_WRAPPER -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, USE_CUDA=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, 
> 
> TorchVision: 0.8.2+cu110
> OpenCV: 4.4.0
> MMCV: 1.2.3
> MMCV Compiler: GCC 8.3
> MMCV CUDA Compiler: not available
> MMAction2: 0.9.0+
> ------------------------------------------------------------
> 
> 2020-12-28 12:40:56,555 - mmaction - INFO - Distributed training: True
> 2020-12-28 12:40:56,555 - mmaction - INFO - Config: /opt/tiger/mmaction2/configs/recognition/tsn/tsn_r50_1x1x3_75e_ucf101_rgb.py
> # model settings
> model = dict(
>     type='Recognizer2D',
>     backbone=dict(
>         type='ResNet',
>         pretrained='torchvision://resnet50',
>         depth=50,
>         norm_eval=False),
>     cls_head=dict(
>         type='TSNHead',
>         num_classes=101,
>         in_channels=2048,
>         spatial_type='avg',
>         consensus=dict(type='AvgConsensus', dim=1),
>         dropout_ratio=0.4,
>         init_std=0.001))
> # model training and testing settings
> train_cfg = None
> test_cfg = dict(average_clips=None)
> # dataset settings
> dataset_type = 'RawframeDataset'
> data_root = 'data/ucf101/rawframes/'
> data_root_val = 'data/ucf101/rawframes/'
> split = 1  # official train/test splits. valid numbers: 1, 2, 3
> ann_file_train = f'data/ucf101/ucf101_train_split_{split}_rawframes.txt'
> ann_file_val = f'data/ucf101/ucf101_val_split_{split}_rawframes.txt'
> ann_file_test = f'data/ucf101/ucf101_val_split_{split}_rawframes.txt'
> img_norm_cfg = dict(
>     mean=[123.675, 116.28, 103.53], std=[58.395, 57.12, 57.375], to_bgr=False)
> train_pipeline = [
>     dict(type='SampleFrames', clip_len=1, frame_interval=1, num_clips=3),
>     dict(type='RawFrameDecode'),
>     dict(type='Resize', scale=(-1, 256)),
>     dict(type='RandomResizedCrop'),
>     dict(type='Resize', scale=(224, 224), keep_ratio=False),
>     dict(type='Flip', flip_ratio=0.5),
>     dict(type='Normalize', **img_norm_cfg),
>     dict(type='FormatShape', input_format='NCHW'),
>     dict(type='Collect', keys=['imgs', 'label'], meta_keys=[]),
>     dict(type='ToTensor', keys=['imgs', 'label'])
> ]
> val_pipeline = [
>     dict(
>         type='SampleFrames',
>         clip_len=1,
>         frame_interval=1,
>         num_clips=3,
>         test_mode=True),
>     dict(type='RawFrameDecode'),
>     dict(type='Resize', scale=(-1, 256)),
>     dict(type='CenterCrop', crop_size=256),
>     dict(type='Flip', flip_ratio=0),
>     dict(type='Normalize', **img_norm_cfg),
>     dict(type='FormatShape', input_format='NCHW'),
>     dict(type='Collect', keys=['imgs', 'label'], meta_keys=[]),
>     dict(type='ToTensor', keys=['imgs'])
> ]
> test_pipeline = [
>     dict(
>         type='SampleFrames',
>         clip_len=1,
>         frame_interval=1,
>         num_clips=25,
>         test_mode=True),
>     dict(type='RawFrameDecode'),
>     dict(type='Resize', scale=(-1, 256)),
>     dict(type='ThreeCrop', crop_size=256),
>     dict(type='Flip', flip_ratio=0),
>     dict(type='Normalize', **img_norm_cfg),
>     dict(type='FormatShape', input_format='NCHW'),
>     dict(type='Collect', keys=['imgs', 'label'], meta_keys=[]),
>     dict(type='ToTensor', keys=['imgs'])
> ]
> data = dict(
>     videos_per_gpu=32,
>     workers_per_gpu=4,
>     train=dict(
>         type=dataset_type,
>         ann_file=ann_file_train,
>         data_prefix=data_root,
>         pipeline=train_pipeline),
>     val=dict(
>         type=dataset_type,
>         ann_file=ann_file_val,
>         data_prefix=data_root_val,
>         pipeline=val_pipeline),
>     test=dict(
>         type=dataset_type,
>         ann_file=ann_file_test,
>         data_prefix=data_root_val,
>         pipeline=test_pipeline))
> # optimizer
> optimizer = dict(
>     type='SGD', lr=0.00128, momentum=0.9,
>     weight_decay=0.0005)  # this lr is used for 8 gpus
> optimizer_config = dict(grad_clip=dict(max_norm=40, norm_type=2))
> # learning policy
> lr_config = dict(policy='step', step=[])
> total_epochs = 75
> checkpoint_config = dict(interval=5)
> evaluation = dict(
>     interval=5, metrics=['top_k_accuracy', 'mean_class_accuracy'])
> log_config = dict(
>     interval=20,
>     hooks=[
>         dict(type='TextLoggerHook'),
>         # dict(type='TensorboardLoggerHook'),
>     ])
> # runtime settings
> dist_params = dict(backend='nccl')
> log_level = 'INFO'
> work_dir = f'./work_dirs/tsn_r50_1x1x3_75e_ucf101_split_{split}_rgb/'
> load_from = None
> resume_from = None
> workflow = [('train', 1)]
> 
> fatal: not a git repository (or any of the parent directories): .git
> fatal: not a git repository (or any of the parent directories): .git
> fatal: not a git repository (or any of the parent directories): .git
> fatal: not a git repository (or any of the parent directories): .git
> fatal: not a git repository (or any of the parent directories): .git
> fatal: not a git repository (or any of the parent directories): .git
> Downloading: "https://download.pytorch.org/models/resnet50-19c8e357.pth" to /home/tiger/.cache/torch/hub/checkpoints/resnet50-19c8e357.pth
> 100.0%
> Traceback (most recent call last):
>   File "./tools/train.py", line 178, in <module>
>     main()
>   File "./tools/train.py", line 141, in main
>     cfg.model, train_cfg=cfg.train_cfg, test_cfg=cfg.test_cfg)
>   File "/opt/tiger/mmaction2/mmaction/models/builder.py", line 76, in build_model
>     return build_recognizer(cfg, train_cfg, test_cfg)
>   File "/opt/tiger/mmaction2/mmaction/models/builder.py", line 56, in build_recognizer
>     dict(train_cfg=train_cfg, test_cfg=test_cfg))
>   File "/opt/tiger/mmaction2/mmaction/models/builder.py", line 40, in build
>     return build_from_cfg(cfg, registry, default_args)
>   File "/usr/local/lib/python3.7/dist-packages/mmcv/utils/registry.py", line 171, in build_from_cfg
>     return obj_cls(**args)
>   File "/opt/tiger/mmaction2/mmaction/models/recognizers/base.py", line 51, in __init__
>     self.init_weights()
>   File "/opt/tiger/mmaction2/mmaction/models/recognizers/base.py", line 57, in init_weights
>     self.backbone.init_weights()
>   File "/opt/tiger/mmaction2/mmaction/models/backbones/resnet.py", line 512, in init_weights
>     self._load_torchvision_checkpoint(logger)
>   File "/opt/tiger/mmaction2/mmaction/models/backbones/resnet.py", line 493, in _load_torchvision_checkpoint
>     original_conv_name, loaded_param_names)
>   File "/opt/tiger/mmaction2/mmaction/models/backbones/resnet.py", line 435, in _load_conv_params
>     conv.weight.data.copy_(state_dict_tv[weight_tv_name])
> RuntimeError: The size of tensor a (64) must match the size of tensor b (256) at non-singleton dimension 1
> Traceback (most recent call last):
>   File "./tools/train.py", line 178, in <module>
> Traceback (most recent call last):
>   File "./tools/train.py", line 178, in <module>
>     main()
>   File "./tools/train.py", line 141, in main
>     cfg.model, train_cfg=cfg.train_cfg, test_cfg=cfg.test_cfg)
>       File "/opt/tiger/mmaction2/mmaction/models/builder.py", line 76, in build_model
> main()
>   File "./tools/train.py", line 141, in main
>     return build_recognizer(cfg, train_cfg, test_cfg)
>   File "/opt/tiger/mmaction2/mmaction/models/builder.py", line 56, in build_recognizer
>     cfg.model, train_cfg=cfg.train_cfg, test_cfg=cfg.test_cfg)
>   File "/opt/tiger/mmaction2/mmaction/models/builder.py", line 76, in build_model
>     dict(train_cfg=train_cfg, test_cfg=test_cfg))
>   File "/opt/tiger/mmaction2/mmaction/models/builder.py", line 40, in build
>     return build_recognizer(cfg, train_cfg, test_cfg)
>   File "/opt/tiger/mmaction2/mmaction/models/builder.py", line 56, in build_recognizer
>     return build_from_cfg(cfg, registry, default_args)
>   File "/usr/local/lib/python3.7/dist-packages/mmcv/utils/registry.py", line 171, in build_from_cfg
>     dict(train_cfg=train_cfg, test_cfg=test_cfg))
>   File "/opt/tiger/mmaction2/mmaction/models/builder.py", line 40, in build
>     return build_from_cfg(cfg, registry, default_args)
>       File "/usr/local/lib/python3.7/dist-packages/mmcv/utils/registry.py", line 171, in build_from_cfg
> return obj_cls(**args)
>   File "/opt/tiger/mmaction2/mmaction/models/recognizers/base.py", line 51, in __init__
>     self.init_weights()
>       File "/opt/tiger/mmaction2/mmaction/models/recognizers/base.py", line 57, in init_weights
> return obj_cls(**args)
>   File "/opt/tiger/mmaction2/mmaction/models/recognizers/base.py", line 51, in __init__
>     self.backbone.init_weights()
>   File "/opt/tiger/mmaction2/mmaction/models/backbones/resnet.py", line 512, in init_weights
>     self.init_weights()
>   File "/opt/tiger/mmaction2/mmaction/models/recognizers/base.py", line 57, in init_weights
>     self.backbone.init_weights()
>   File "/opt/tiger/mmaction2/mmaction/models/backbones/resnet.py", line 512, in init_weights
>     self._load_torchvision_checkpoint(logger)
>   File "/opt/tiger/mmaction2/mmaction/models/backbones/resnet.py", line 493, in _load_torchvision_checkpoint
>     self._load_torchvision_checkpoint(logger)
>   File "/opt/tiger/mmaction2/mmaction/models/backbones/resnet.py", line 493, in _load_torchvision_checkpoint
>     original_conv_name, loaded_param_names)
>   File "/opt/tiger/mmaction2/mmaction/models/backbones/resnet.py", line 435, in _load_conv_params
>     original_conv_name, loaded_param_names)
>   File "/opt/tiger/mmaction2/mmaction/models/backbones/resnet.py", line 435, in _load_conv_params
> Traceback (most recent call last):
>   File "./tools/train.py", line 178, in <module>
>     conv.weight.data.copy_(state_dict_tv[weight_tv_name])
> RuntimeError: The size of tensor a (64) must match the size of tensor b (256) at non-singleton dimension 1
>     conv.weight.data.copy_(state_dict_tv[weight_tv_name])
> RuntimeError: The size of tensor a (64) must match the size of tensor b (256) at non-singleton dimension 1
>     main()
>   File "./tools/train.py", line 141, in main
>     cfg.model, train_cfg=cfg.train_cfg, test_cfg=cfg.test_cfg)
>   File "/opt/tiger/mmaction2/mmaction/models/builder.py", line 76, in build_model
>     return build_recognizer(cfg, train_cfg, test_cfg)
>   File "/opt/tiger/mmaction2/mmaction/models/builder.py", line 56, in build_recognizer
>     dict(train_cfg=train_cfg, test_cfg=test_cfg))
>   File "/opt/tiger/mmaction2/mmaction/models/builder.py", line 40, in build
>     return build_from_cfg(cfg, registry, default_args)
>   File "/usr/local/lib/python3.7/dist-packages/mmcv/utils/registry.py", line 171, in build_from_cfg
>     return obj_cls(**args)
>   File "/opt/tiger/mmaction2/mmaction/models/recognizers/base.py", line 51, in __init__
>     self.init_weights()
>   File "/opt/tiger/mmaction2/mmaction/models/recognizers/base.py", line 57, in init_weights
>     self.backbone.init_weights()
>   File "/opt/tiger/mmaction2/mmaction/models/backbones/resnet.py", line 512, in init_weights
>     self._load_torchvision_checkpoint(logger)
>   File "/opt/tiger/mmaction2/mmaction/models/backbones/resnet.py", line 493, in _load_torchvision_checkpoint
> Traceback (most recent call last):
>   File "./tools/train.py", line 178, in <module>
>     original_conv_name, loaded_param_names)
>   File "/opt/tiger/mmaction2/mmaction/models/backbones/resnet.py", line 435, in _load_conv_params
>     conv.weight.data.copy_(state_dict_tv[weight_tv_name])
> RuntimeError: The size of tensor a (64) must match the size of tensor b (256) at non-singleton dimension 1
>     main()
>   File "./tools/train.py", line 141, in main
>     cfg.model, train_cfg=cfg.train_cfg, test_cfg=cfg.test_cfg)
>   File "/opt/tiger/mmaction2/mmaction/models/builder.py", line 76, in build_model
>     return build_recognizer(cfg, train_cfg, test_cfg)
>   File "/opt/tiger/mmaction2/mmaction/models/builder.py", line 56, in build_recognizer
>     dict(train_cfg=train_cfg, test_cfg=test_cfg))
>   File "/opt/tiger/mmaction2/mmaction/models/builder.py", line 40, in build
>     return build_from_cfg(cfg, registry, default_args)
>   File "/usr/local/lib/python3.7/dist-packages/mmcv/utils/registry.py", line 171, in build_from_cfg
>     return obj_cls(**args)
>   File "/opt/tiger/mmaction2/mmaction/models/recognizers/base.py", line 51, in __init__
>     self.init_weights()
>   File "/opt/tiger/mmaction2/mmaction/models/recognizers/base.py", line 57, in init_weights
>     self.backbone.init_weights()
>   File "/opt/tiger/mmaction2/mmaction/models/backbones/resnet.py", line 512, in init_weights
>     self._load_torchvision_checkpoint(logger)
>   File "/opt/tiger/mmaction2/mmaction/models/backbones/resnet.py", line 493, in _load_torchvision_checkpoint
>     original_conv_name, loaded_param_names)
>   File "/opt/tiger/mmaction2/mmaction/models/backbones/resnet.py", line 435, in _load_conv_params
>     conv.weight.data.copy_(state_dict_tv[weight_tv_name])
> RuntimeError: The size of tensor a (64) must match the size of tensor b (256) at non-singleton dimension 1
> Traceback (most recent call last):
>   File "./tools/train.py", line 178, in <module>
> Traceback (most recent call last):
>   File "./tools/train.py", line 178, in <module>
>     main()
>   File "./tools/train.py", line 141, in main
>     main()
>       File "./tools/train.py", line 141, in main
> cfg.model, train_cfg=cfg.train_cfg, test_cfg=cfg.test_cfg)
>   File "/opt/tiger/mmaction2/mmaction/models/builder.py", line 76, in build_model
>         cfg.model, train_cfg=cfg.train_cfg, test_cfg=cfg.test_cfg)return build_recognizer(cfg, train_cfg, test_cfg)
> 
>   File "/opt/tiger/mmaction2/mmaction/models/builder.py", line 76, in build_model
>   File "/opt/tiger/mmaction2/mmaction/models/builder.py", line 56, in build_recognizer
>         dict(train_cfg=train_cfg, test_cfg=test_cfg))return build_recognizer(cfg, train_cfg, test_cfg)
> 
>   File "/opt/tiger/mmaction2/mmaction/models/builder.py", line 40, in build
>   File "/opt/tiger/mmaction2/mmaction/models/builder.py", line 56, in build_recognizer
>     return build_from_cfg(cfg, registry, default_args)
>       File "/usr/local/lib/python3.7/dist-packages/mmcv/utils/registry.py", line 171, in build_from_cfg
> dict(train_cfg=train_cfg, test_cfg=test_cfg))
>   File "/opt/tiger/mmaction2/mmaction/models/builder.py", line 40, in build
>     return build_from_cfg(cfg, registry, default_args)
>   File "/usr/local/lib/python3.7/dist-packages/mmcv/utils/registry.py", line 171, in build_from_cfg
>     return obj_cls(**args)
>   File "/opt/tiger/mmaction2/mmaction/models/recognizers/base.py", line 51, in __init__
>     return obj_cls(**args)
>   File "/opt/tiger/mmaction2/mmaction/models/recognizers/base.py", line 51, in __init__
>     self.init_weights()
>   File "/opt/tiger/mmaction2/mmaction/models/recognizers/base.py", line 57, in init_weights
>     self.init_weights()
>       File "/opt/tiger/mmaction2/mmaction/models/recognizers/base.py", line 57, in init_weights
> self.backbone.init_weights()
>   File "/opt/tiger/mmaction2/mmaction/models/backbones/resnet.py", line 512, in init_weights
>     self.backbone.init_weights()
>   File "/opt/tiger/mmaction2/mmaction/models/backbones/resnet.py", line 512, in init_weights
>     self._load_torchvision_checkpoint(logger)
>   File "/opt/tiger/mmaction2/mmaction/models/backbones/resnet.py", line 493, in _load_torchvision_checkpoint
>     self._load_torchvision_checkpoint(logger)
>   File "/opt/tiger/mmaction2/mmaction/models/backbones/resnet.py", line 493, in _load_torchvision_checkpoint
>     original_conv_name, loaded_param_names)
>   File "/opt/tiger/mmaction2/mmaction/models/backbones/resnet.py", line 435, in _load_conv_params
>     original_conv_name, loaded_param_names)
>   File "/opt/tiger/mmaction2/mmaction/models/backbones/resnet.py", line 435, in _load_conv_params
>     conv.weight.data.copy_(state_dict_tv[weight_tv_name])
> RuntimeError: The size of tensor a (64) must match the size of tensor b (256) at non-singleton dimension 1
> Traceback (most recent call last):
>     conv.weight.data.copy_(state_dict_tv[weight_tv_name])
>   File "./tools/train.py", line 178, in <module>
> RuntimeError: The size of tensor a (64) must match the size of tensor b (256) at non-singleton dimension 1
>     main()
>   File "./tools/train.py", line 141, in main
>     cfg.model, train_cfg=cfg.train_cfg, test_cfg=cfg.test_cfg)
>   File "/opt/tiger/mmaction2/mmaction/models/builder.py", line 76, in build_model
>     return build_recognizer(cfg, train_cfg, test_cfg)
>   File "/opt/tiger/mmaction2/mmaction/models/builder.py", line 56, in build_recognizer
>     dict(train_cfg=train_cfg, test_cfg=test_cfg))
>   File "/opt/tiger/mmaction2/mmaction/models/builder.py", line 40, in build
>     return build_from_cfg(cfg, registry, default_args)
>   File "/usr/local/lib/python3.7/dist-packages/mmcv/utils/registry.py", line 171, in build_from_cfg
>     return obj_cls(**args)
>   File "/opt/tiger/mmaction2/mmaction/models/recognizers/base.py", line 51, in __init__
>     self.init_weights()
>   File "/opt/tiger/mmaction2/mmaction/models/recognizers/base.py", line 57, in init_weights
>     self.backbone.init_weights()
>   File "/opt/tiger/mmaction2/mmaction/models/backbones/resnet.py", line 512, in init_weights
>     self._load_torchvision_checkpoint(logger)
>   File "/opt/tiger/mmaction2/mmaction/models/backbones/resnet.py", line 493, in _load_torchvision_checkpoint
>     original_conv_name, loaded_param_names)
>   File "/opt/tiger/mmaction2/mmaction/models/backbones/resnet.py", line 435, in _load_conv_params
>     conv.weight.data.copy_(state_dict_tv[weight_tv_name])
> RuntimeError: The size of tensor a (64) must match the size of tensor b (256) at non-singleton dimension 1
> Traceback (most recent call last):
>   File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
>     "__main__", mod_spec)
>   File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
>     exec(code, run_globals)
>   File "/usr/local/lib/python3.7/dist-packages/torch/distributed/launch.py", line 260, in <module>
>     main()
>   File "/usr/local/lib/python3.7/dist-packages/torch/distributed/launch.py", line 256, in main
>     cmd=cmd)
> subprocess.CalledProcessError: Command '['/usr/bin/python', '-u', './tools/train.py', '--local_rank=7', 'configs/recognition/tsn/tsn_r50_1x1x3_75e_ucf101_rgb.py', '--launcher', 'pytorch', '--cfg-options', 'model.backbone.depth=34']' returned non-zero exit status 1.
> 2020-12-28 12:41:00,053 INFO /opt/tiger/mmaction2/launch.sh exited with status 1.
> 2020-12-28 12:41:00,053 INFO Killing all processes...
