### ISSUE TITLE
The accuracy for SlowFast network seems to be worse than PySlowFast

### ISSUE THREAD

**Issue by yxchng** [open-mmlab/mmaction2#486]
mmation2:
<img width="1222" alt="Screenshot 2020-12-25 at 1 02 08 AM" src="https://user-images.githubusercontent.com/10518587/103100325-011c7380-464d-11eb-8fc9-aec8d522ab47.png">
pyslowfast:
<img width="1174" alt="Screenshot 2020-12-25 at 1 01 41 AM" src="https://user-images.githubusercontent.com/10518587/103100398-4f317700-464d-11eb-9f42-230b57211529.png">

Based on the figures above, mmaction2 is only able to match the implementation in PySlowFast when using short-side 320. However, implementation in PySlowFast is using short-side 256. That is bad because using larger image has an unfair advantage. Are you guys looking into resolving this problem? It seems like this repo is still not able to match the official implementation when using the same settings.

**Comment by innerlee** [comment]
Could you please pick two "same settings" from both repo, ideally with their config links, so that we can compare them?

**Comment by yxchng** [comment]
https://github.com/open-mmlab/mmaction2/blob/master/configs/recognition/slowfast/slowfast_r50_4x16x1_256e_kinetics400_rgb.py

https://github.com/facebookresearch/SlowFast/blob/master/configs/Kinetics/SLOW_4x16_R50.yaml

**Comment by SuX97** [comment]
@yxchng Hi, thank you for your interest in MMAction2! I guess what you mean is SLOWFAST_4x16_R50.yaml.

One thing to be sorted out first, the `resolution` in our repo means the original input resolution. However, either short-edge 320 or 256 will be eventually resized into 256 * 256 for testing, therefore there would be no concern about the fairness.

We will try to be aligned with the pipeline and training setting of PySlowfast and update the model zoo in the future.
