### ISSUE TITLE
download_videos.sh in kinetics gives exit status 69 when running ffmpeg command to trim the downloaded videos

### ISSUE THREAD

**Issue by yxchng** [open-mmlab/mmaction2#489]
**Describe the bug**
I follow the instruction in https://github.com/open-mmlab/mmaction2/tree/master/tools/data/kinetics and have problems in step 2 when running `bash download_videos.sh kinetics400`. The script does not give any error because they are suppressed by the try get statement here https://github.com/open-mmlab/mmaction2/blob/master/tools/data/kinetics/download.py#L119-L123. If you add `print(err)` in the except part, you will see a lot of errors like this 

`Command 'ffmpeg -i "/tmp/kinetics/d85dbb77-46c6-46ba-9b83-0e45fc50f713.mp4" -ss 73 -t 10 -c:v libx264 -c:a copy -threads 1 -loglevel panic "kinetics400/abseiling/mRdyYMPlJ_8_000073_000083.mp4"' returned non-zero exit status 69.`

This prevents this line https://github.com/open-mmlab/mmaction2/blob/master/tools/data/kinetics/download.py#L127 from running, causing lots of original video to be stored. Currently, I am having 2 tb of space being used even when it has only downloaded 80k videos. As a result, my hard disk is full before completion.

Any ideas how to resolve this problem?

**Reproduction**

1. What command or script did you run?
`bash download_videos.sh kinetics400`

2. Did you make any modifications on the code or config? Did you understand what you have modified?
No. Only add print statement. You need to add the print statement to see the error. Also you will notice that the size of `/tmp/kinetics` keeps growing because these videos are not deleted.

3. What dataset did you use?
N.A.

**Environment**

1. Please run `PYTHONPATH=${PWD}:$PYTHONPATH python mmaction/utils/collect_env.py` to collect necessary environment information and paste it here.

> Python: 3.7.3 (default, Jul 25 2020, 13:03:44) [GCC 8.3.0]
> CUDA available: True
> GPU 0,1,2,3,4,5,6,7: Tesla V100-SXM2-32GB
> CUDA_HOME: /usr/local/cuda
> NVCC: Build cuda_11.0_bu.TC445_37.28845127_0
> GCC: gcc (Debian 8.3.0-6) 8.3.0
> PyTorch: 1.7.1+cu110
> PyTorch compiling details: PyTorch built with:
>   - GCC 7.3
>   - C++ Version: 201402
>   - Intel(R) Math Kernel Library Version 2020.0.0 Product Build 20191122 for Intel(R) 64 architecture applications
>   - Intel(R) MKL-DNN v1.6.0 (Git Hash 5ef631a030a6f73131c77892041042805a06064f)
>   - OpenMP 201511 (a.k.a. OpenMP 4.5)
>   - NNPACK is enabled
>   - CPU capability usage: AVX2
>   - CUDA Runtime 11.0
>   - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80
>   - CuDNN 8.0.5
>   - Magma 2.5.2
>   - Build settings: BLAS=MKL, BUILD_TYPE=Release, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DUSE_VULKAN_WRAPPER -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, USE_CUDA=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON,
> 
> TorchVision: 0.8.2+cu110
> OpenCV: 4.4.0
> MMCV: 1.2.2
> MMCV Compiler: n/a
> MMCV CUDA Compiler: n/a
> MMAction2: 0.9.0+814d97d

**Comment by SuX97** [comment]
Seems that the main issue is that the ffmpeg trimming fails. Could you please share this video with us and your ffmpeg version for bug reproducing?

**Comment by yxchng** [comment]
@SuX97 there are a lot of videos that have this problem. the following is one of them 

`Command 'ffmpeg -i "/tmp/kinetics/d85dbb77-46c6-46ba-9b83-0e45fc50f713.mp4" -ss 73 -t 10 -c:v libx264 -c:a copy -threads 1 -loglevel panic "kinetics400/abseiling/mRdyYMPlJ_8_000073_000083.mp4"' returned non-zero exit status 69.
`

ffmpeg is installed using `sudo apt-get install ffmpeg`

`ffmpeg` gives

```
ffmpeg version 4.1.6-1~deb10u1 Copyright (c) 2000-2020 the FFmpeg developers
  built with gcc 8 (Debian 8.3.0-6)
  configuration: --prefix=/usr --extra-version='1~deb10u1' --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping--enable-avresample --disable-filter=resample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librsvg --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opengl --enable-sdl2 --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
  libavutil      56. 22.100 / 56. 22.100
  libavcodec     58. 35.100 / 58. 35.100
  libavformat    58. 20.100 / 58. 20.100
  libavdevice    58.  5.100 / 58.  5.100
  libavfilter     7. 40.101 /  7. 40.101
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  3.100 /  5.  3.100
  libswresample   3.  3.100 /  3.  3.100
  libpostproc    55.  3.100 / 55.  3.100
Hyper fast Audio and Video encoder
usage: ffmpeg [options] [[infile options] -i infile]... {[outfile options] outfile}...

Use -h to get full help or, even better, run 'man ffmpeg'
```

**Comment by yxchng** [comment]
don't think is ffmpeg problem because if I run the trimming command manually on the terminal, it succeeds without any error

**Comment by dreamerlin** [comment]
The scripts is provided by https://github.com/activitynet/ActivityNet/tree/master/Crawler/Kinetics. You can also try [this](https://academictorrents.com/details/184d11318372f70018cf9a72ef867e2fb9ce1d26)

**Comment by Hanqer** [comment]
I meet the same problems.  Command 'ffmpeg ...'  returned non-zero exit status 69. This makes the temp files in /tmp/kinetics can not be removed.
Hope you can reproduce this problem.

**Comment by innerlee** [comment]
@Hanqer you can remove the `-loglevel panic` in the ffmpeg command to get a detailed error log.

**Comment by Hanqer** [comment]
@innerlee Thansk to your reply. But after I removing the '-loglevel panic' or setting '-loglevel debug'. It also only show returned non-zero exit status 69 but no other information reported. 
I found that the extracted videos are created but not complete. It seems that the processing of extraction of ffmpeg is not complete. And almost all videos are facing this problem.

**Comment by innerlee** [comment]
You can run the command by typing in the terminal. Do not debug through that python script. ffmpeg typically is very wordy

**Comment by Hanqer** [comment]
@innerlee Thanks for your help. The 'ffmpeg' run in the command line performs well.  But it remains errors in the python script. I don't know why. But when I set the number jobs=1, this error disappears. This error only occurs when running ffmpeg in the python script and the jobs>1 in the subprocess.

**Comment by Hanqer** [comment]
I use another pc to test this script, but it seems running without error. The ffmpeg versions are the same. 
I still can not know why it occurs errors in my server computer.

**Comment by dreamerlin** [comment]
> I use another pc to test this script, but it seems running without error. The ffmpeg versions are the same.
> I still can not know why it occurs errors in my server computer.

Maybe you should check the environmental difference between two pc, or install the prerequisite on a raw clean environment

**Comment by Seleucia** [comment]
I got this error also, it is not related to environmental differences. This problem caused by **joblib** library. I got this error for ffmpeg 4.2.4-1ubuntu0.1  and 4.1.4-1ubuntu0.1 versions (tested on two different machines).  
I solve this problem by replacing "joblib" library with,  "multiprocessing.dummy"

**Comment by irvingzhang0512** [comment]
@Seleucia BTW, there are two alternative ways to download kinetics dataset.

**Comment by Seleucia** [comment]
What are they ? I only know to use this bash file, @irvingzhang0512

**Comment by irvingzhang0512** [comment]
> What are they ? I only know to use this bash file, @irvingzhang0512

https://github.com/open-mmlab/mmaction2/tree/master/tools/data/kinetics#step-2-prepare-videos
