### ISSUE TITLE
What is the size of the Kinetics dataset used in mmaction2?

### ISSUE THREAD

**Issue by yxchng** [open-mmlab/mmaction2#498]
There are many links in Kinetics that have expired. As as result, everyone might not be using the same Kinetics dataset. As a reference, the statistics of the Kinetics dataset used in PySlowFast can be found here, https://github.com/facebookresearch/video-nonlocal-net/blob/master/DATASET.md. However, I cannot seem to find similar information for mmaction2. Will you guys be sharing the statistics and the dataset used?

**Comment by yxchng** [comment]
@congee524 Will you guys consider releasing this dataset? Currently if we download from the official site, we can only get 206997 train videos and 17082 val videos, which almost 20% smaller than the dataset you guys are using. This prevents us from reproducing the result and is bad for research.

**Comment by congee524** [comment]
dup of #137
