### ISSUE TITLE
how to do action classifier after getting the proposals of action localization ?

### ISSUE THREAD

**Issue by wwdok** [open-mmlab/mmaction2#499]
Hi, mmaction2 team, I have used the 
`python tools/data/activitynet/convert_proposal_format.py` to get the classification result of proposals. But i found this script just using IOU match between proposal segment and ground truth segment to choose the label id from ground truth label, so if there is no ground truth segment and label, this method will not work. In the README, you said we can use action classifier (Currently supports SSN and P-GCN, not including TSN, I3D etc.) to do the classification, then is there more tutorials on how to train and inference with action classifier model ? Thanks !

**Comment by kennymckormick** [comment]
You can do that in a 2-stage fashion: proposal generation & recognition.
1. Proposal generation is already supported.
2. For recognition, there are two possible approaches:
     1. Use untrimmed videos to train action classifier, and also test them on untrimmed videos. In this case, all proposals belong to a validation video will be assigned with the same label.
     2. First trim untrimmed training videos into clips based on annotated segments, then test them on validation clips trimmed using predicted proposals. 

The recognition accuracy of the two approaches is provided in https://github.com/open-mmlab/mmaction2/tree/master/configs/recognition/tsn. The later approach is a better solution for both recognition and localization.

**Comment by wwdok** [comment]
Yes, if use method2, we can use the [Video demo](https://github.com/open-mmlab/mmaction2/tree/master/demo#video-demo)  script with our trained TSN model to classify those segments generated by BMN model. I am stucked by this sentence """This file converts the output proposal file of proposal generator (BSN, BMN)into the input proposal file of action classifier (Currently supports SSN and P-GCN, not including TSN, I3D etc.).""", i kept thinking what is SSN and P-GCN, and how to use them. But now, i think we can combine the BMN result.json with [Video demo](https://github.com/open-mmlab/mmaction2/tree/master/demo#video-demo)  script together to realize the full process of action localization and classification.

**Comment by pzhren** [comment]
> Yes, if use method2, we can use the [Video demo](https://github.com/open-mmlab/mmaction2/tree/master/demo#video-demo) script with our trained TSN model to classify those segments generated by BMN model. I am stucked by this sentence """This file converts the output proposal file of proposal generator (BSN, BMN)into the input proposal file of action classifier (Currently supports SSN and P-GCN, not including TSN, I3D etc.).""", i kept thinking what is SSN and P-GCN, and how to use them if TSN is not supported. But now, i think we can combine the BMN result.json with [Video demo](https://github.com/open-mmlab/mmaction2/tree/master/demo#video-demo) script and TSN model together to realize the full process of action localization and classification.

Hello, I encountered a similar problem, I used BMN to generate the corresponding proposals, but how do I classify them. Is there any detailed guidance? Thank you very much.
