### ISSUE TITLE
Invalid MiT dataset link 

### ISSUE THREAD

**Issue by Cogito2012** [open-mmlab/mmaction2#506]
The Moments in Time (MiT) dataset configuration codes need to be updated. 

Specifically, the provided download link in the script file `/tools/data/mit/download_data.sh` is no longer valid. See:
```shell
wget http://data.csail.mit.edu/soundnet/actions3/split1/Moments_in_Time_Raw.zip
# reported error:
--2020-12-31 01:17:20--  http://data.csail.mit.edu/soundnet/actions3/split1/Moments_in_Time_Raw.zip
Resolving data.csail.mit.edu (data.csail.mit.edu)... 128.52.129.40
Connecting to data.csail.mit.edu (data.csail.mit.edu)|128.52.129.40|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2020-12-31 01:17:20 ERROR 404: Not Found.

```

After I obtained the correct MiT dataset download link, it seems that now only the MiT-v2 is provided. However, the data structure in MiT-v2 is totally different from the original MiT-v1. Therefore, the shell scripts in `/tools/data/mit/` will not work. 

Hope your team could update the support for this dataset. Thanks!

**Comment by SuX97** [comment]
Got it.

**Comment by innerlee** [comment]
Please download the dataset from the original website, following their instructions. You may need to fill application forms.
We will improve the doc and scripts accordingly
