### ISSUE TITLE
When training, the grad_norm is much bigger than that in the official log file(13 vs 3). Is there any bad effects?

### ISSUE THREAD

**Issue by wuyongfa-genius** [open-mmlab/mmaction2#507]

**Comment by innerlee** [comment]
Please provide more detail: configs, cmd scripts, etc.

**Comment by wuyongfa-genius** [comment]
I modified the config file i3d_nl_dot_product_r50_32x2x1_100e_kinetics400_rgb.py, I think the main differences are that videos_per_gpu=8, lr=0.0025(because I have only one GPU), where the original config is that videos_per_gpu=6, lr=0.03(use 8 GPUs). In addition, I loaded the corresponding pretrained weights and finetune on it.

**Comment by dreamerlin** [comment]
> I modified the config file i3d_nl_dot_product_r50_32x2x1_100e_kinetics400_rgb.py, I think the main differences are that videos_per_gpu=8, lr=0.0025(because I have only one GPU), where the original config is that videos_per_gpu=6, lr=0.03(use 8 GPUs). In addition, I loaded the corresponding pretrained weights and finetune on it.

according to [linear scale rule](https://arxiv.org/abs/1706.02677), you can try `videos_per_gpu=8, lr=0.005`
