### ISSUE TITLE
My wrong operation or a bug

### ISSUE THREAD

**Issue by SKBL5694** [open-mmlab/mmaction2#510]
When I tried this command 
">python tools/train.py configs/detection/AVA/slowfast_kinetics_pretrained_r50_8x8x1_20e_ava_rgb.py --validate"
It raised a "TypeError: __init__() got an unexpected keyword argument 'person_det_score_thr'".
"\mmcv\utils\registry.py", line 171, in build_from_cfg
    return obj_cls(**args)"
I have followed the datasets preparation. I'm confused about that. Is there any update in the file "\mmcv\utils\registry.py"? I've installed this package on 11.23/2020 and I found that the latest version about the file is "two months ago". So I think it's not a version mistake? Is there any helpful advice for me?

**Comment by SKBL5694** [comment]
BTW, the whole tracebak is here:
Traceback (most recent call last):
  File "tools/train.py", line 178, in <module>
    main()
  File "tools/train.py", line 148, in main
    datasets = [build_dataset(cfg.data.train)]
  File "f:\myfile\mmaction\mmaction2-master\mmaction\datasets\builder.py", line 39, in build_dataset
    dataset = build_from_cfg(cfg, DATASETS, default_args)
  File "F:\anaconda\envs\cuda101\lib\site-packages\mmcv\utils\registry.py", line 171, in build_from_cfg
    return obj_cls(**args)
TypeError: __init__() got an unexpected keyword argument 'person_det_score_thr'

**Comment by SKBL5694** [comment]
> That might be a version error. The config files and `ava_dataset.py` are updated 17 days ago (noticed that the path is `AVA` in ur log, in the latest version it's `ava`). Perhaps you can try with the latest master branch of mmaction2.

I'm not familiar with git command QAQ, so I download the latest code of mmaction2. Now the new error change to: 
'ValueError: FastRCNN is not registered in LOCALIZERS, RECOGNIZERS or DETECTORS'. Since I've download the latest mmacion2, I guess the mistake is about mmcv. I'm not sure about that.

**Comment by kennymckormick** [comment]
> > That might be a version error. The config files and `ava_dataset.py` are updated 17 days ago (noticed that the path is `AVA` in ur log, in the latest version it's `ava`). Perhaps you can try with the latest master branch of mmaction2.
> 
> I'm not familiar with git command QAQ, so I download the latest code of mmaction2. Now the new error change to:
> 'ValueError: FastRCNN is not registered in LOCALIZERS, RECOGNIZERS or DETECTORS'. Since I've download the latest mmacion2, I guess the mistake is about mmcv. I'm not sure about that.

Is there another warning: "Please install mmdet to use DETECTORS, build_detector"?
If so, you need also install the latest mmdetection.

**Comment by SKBL5694** [comment]
> > > That might be a version error. The config files and `ava_dataset.py` are updated 17 days ago (noticed that the path is `AVA` in ur log, in the latest version it's `ava`). Perhaps you can try with the latest master branch of mmaction2.
> > 
> > 
> > I'm not familiar with git command QAQ, so I download the latest code of mmaction2. Now the new error change to:
> > 'ValueError: FastRCNN is not registered in LOCALIZERS, RECOGNIZERS or DETECTORS'. Since I've download the latest mmacion2, I guess the mistake is about mmcv. I'm not sure about that.
> 
> Is there another warning: "Please install mmdet to use DETECTORS, build_detector"?
> If so, you need also install the latest mmdetection.

I don't see that waring. All error message is here :

Traceback (most recent call last):
  File "tools/train.py", line 178, in <module>
    main()
  File "tools/train.py", line 141, in main
    cfg.model, train_cfg=cfg.train_cfg, test_cfg=cfg.test_cfg)
  File "e:\aaaaaction2\mmaction2\mmaction\models\builder.py", line 79, in build_model
    raise ValueError(f'{obj_type} is not registered in '
ValueError: FastRCNN is not registered in LOCALIZERS, RECOGNIZERS or DETECTORS

Both train.py and builder.py is the latest.

**Comment by SKBL5694** [comment]
I do find that warning and I use pip install mmdet to install that but failed. Is there any tutorial about how to install mmdet. I only find mmdetection in open-mmlab. Do I have to install mmdection2 or I can only install mmdet?

**Comment by SKBL5694** [comment]
@kennymckormick 
I do find that warning and I use pip install mmdet to install that but failed. Is there any tutorial about how to install mmdet. I only find mmdetection in open-mmlab. Do I have to install mmdection2 or I can only install mmdet?

**Comment by dreamerlin** [comment]
> @kennymckormick
> I do find that warning and I use pip install mmdet to install that but failed. Is there any tutorial about how to install mmdet. I only find mmdetection in open-mmlab. Do I have to install mmdection or I can only install mmdet?

You can refer to https://github.com/open-mmlab/mmdetection/blob/master/docs/get_started.md

**Comment by kennymckormick** [comment]
> @kennymckormick
> I do find that warning and I use pip install mmdet to install that but failed. Is there any tutorial about how to install mmdet. I only find mmdetection in open-mmlab. Do I have to install mmdection or I can only install mmdet?

mmdet is mmdetection. If you can not install mmdet via `pip install`, you can check if you meet the requirement of that package (python 3 should be used, e.g.), or you can try to install mmdet from source.
