### ISSUE TITLE
TSM bi-direction and uni-direction

### ISSUE THREAD

**Issue by wwdok** [open-mmlab/mmaction2#517]
I read the TSM paper, found there are two kinds of TSM module : bi-direction and uni-direction, which are suitable for offline and online respectively. In the model zoo, is it the 3rd - 5th models are using offline bi-direction module, others using online uni-direction module, thank you !
![image](https://user-images.githubusercontent.com/43233772/103659149-0eb7ee80-4fa7-11eb-8a90-4470c5c68086.png)

**Comment by irvingzhang0512** [comment]
For now, uni-direction is not supported in both mmaction2 & original tsm repo.

BTW, in my experience, bi-direction is suitable for online applications, too

**Comment by wwdok** [comment]
Thank you for replying my question at midnight, respect !

**Comment by ZJU-lishuang** [comment]
@irvingzhang0512 
How to use bi-direction in online applications?
Can you explain it briefly?
Thanks for your help.
