### ISSUE TITLE
`Video GradCAM Demo` is prone to get `CUDA out of memory` with more than 32 frames

### ISSUE THREAD

**Issue by wwdok** [open-mmlab/mmaction2#519]
Hi, @irvingzhang0512 , i saw you commit the  [PR](https://github.com/open-mmlab/mmaction2/pull/324) of  Video GradCAM Demo, but i found it is very easy to get `RuntimeError: CUDA out of memory`

My command line is :

`python demo/demo_gradcam.py configs/recognition/tsm/tsm_r50_video_inference_1x1x8_100e_kinetics400_rgb.py     https://download.openmmlab.com/mmaction/recognition/tsm/tsm_r50_video_1x1x8_100e_kinetics400_rgb/tsm_r50_video_1x1x8_100e_kinetics400_rgb_20200702-a77f4328.pth     demo/video1.mp4 --target-layer-name backbone/layer4/1/relu --out-filename demo/gradcam_video1.gif`

I modified 2 places in `test_pipeline` of `tsm_r50_video_inference_1x1x8_100e_kinetics400_rgb.py`:
```
test_pipeline = [
    dict(type='DecordInit', num_threads=1),
    dict(
        type='SampleFrames',
        clip_len=1,
        frame_interval=1,
        num_clips=32,  # change from 8 to 32
        test_mode=True),
    dict(type='DecordDecode'),
    dict(type='Resize', scale=(-1, 256)),
    #dict(type='CenterCrop', crop_size=224),   # comment out this augmentation, i found it will lead wrong heatmap
    dict(type='Normalize', **img_norm_cfg),
    dict(type='FormatShape', input_format='NCHW'),
    dict(type='Collect', keys=['imgs'], meta_keys=[]),
    dict(type='ToTensor', keys=['imgs'])
]
```

My output gif size is [1, 32, 3, 256, 455], then it reported following error:
`RuntimeError: CUDA out of memory. Tried to allocate 114.00 MiB (GPU 0; 5.81 GiB total capacity; 4.20 GiB already allocated; 42.31 MiB free; 4.36 GiB reserved in total by PyTorch)`

I was shocked that just 32 frames would take up such a large amount of memory(114.00 MiB), is there some workaround to successfully generate Grad-CAM gif with more than 32 frames ?

**Comment by irvingzhang0512** [comment]
Unlike model inferencing, GracCAM grads to generate heatmaps, which requires a lot of gpu memory.

I would suggest smaller image resolution. Also, you can manually diable grads for layers before `--target-layer-name` .

BTW, it is not recommended to directly modify `num_clips` for tsm models during testing, #437

**Comment by wwdok** [comment]
Thank you so much for your explanation ! 
But TSM is a 3D model or 2D model ? the config file defines it as 2D recognizer, is this mean TSM is 2D model ?
![image](https://user-images.githubusercontent.com/43233772/103759581-ec79ab80-504e-11eb-9ff7-a5fc88f7bde3.png)

**Comment by irvingzhang0512** [comment]
In my opinion, 3D models are the ones with 3d convolution. TSM don't have 3d convs.

**Comment by wwdok** [comment]
Ok, i will pay attention to the setting of num_clips.
BTW, i said something wrong, CenterCrop may not Influence grad cam result, but it will for TenCrop and ThreeCrop. For that arm wrestling, i found the heatmap does not focus on the hand if not comment out ThreeCrop.
