### ISSUE TITLE
Some bugs may be found

### ISSUE THREAD

**Issue by SKBL5694** [open-mmlab/mmaction2#522]
I've followed the docs to prepare the AVA datasets and my folder structure is similar as below(recommendation in docs)
mmaction2
├── mmaction
├── tools
├── configs
├── data
│   ├── ava
│   │   ├── ava_dense_proposals_train.FAIR.recall_93.9.pkl
│   │   ├── ava_dense_proposals_val.FAIR.recall_93.9.pkl
│   │   ├── ava_dense_proposals_test.FAIR.recall_93.9.pkl
│   │   ├── annotations
│   │   ├── videos
│   │   │   ├── 053oq2xB3oU.mkv
│   │   │   ├── 0f39OWEqJ24.mp4
│   │   │   ├── ...
│   │   ├── videos_15min
│   │   │   ├── 053oq2xB3oU.mkv
│   │   │   ├── 0f39OWEqJ24.mp4
│   │   │   ├── ...
│   │   ├── rawframes
│   │   │   ├── 053oq2xB3oU
|   │   │   │   ├── img_00001.jpg
|   │   │   │   ├── img_00002.jpg
|   │   │   │   ├── ...
but when I try the command 
"python tools/train.py configs/detection/ava/slowfast_kinetics_pretrained_r50_8x8x1_20e_ava_rgb.py --validate"
It raised an error: [Errno 2] No such file or directory: 'data/ava/annotations/ava_dense_proposals_train.FAIR.recall_93.9.pkl'
From the the recommended folder structure : It seems that xxx.pkl and annotations is on the same level directory not the sub-directory. So I think a small bug may be found.

**Comment by SKBL5694** [comment]
BTW, I copy those 3 .pkl files into ava/annotations. And I found the param "load_from" needs to be modified too. Because the url 'https://download.openmmlab.com/mmaction/recognition/slowfast/slowfast_r50_8x8x1_256e_kinetics400_rgb/slowfast_r50_8x8x1_2.pth' seems invalid now. Then I set this to None. 
And it raise another error No such file or directory: '/home/avadata/ava/rawframes/oITFHwzfw_k/img_20159.jpg'
I found that the output filename of the script "extract_rgb_frames_ffmpeg.sh" is like this "oITFHwzfw_k_020159.jpg". The filenames don't match.
I'm not sure if I need to write a script to rename my data to the format 'img_xxxxx.jpg' or I need to modify some codes that are used to read data.
What's more, If the above problem is caused by my misoperation I apologize for that. Please give some advice, thanks a lot.

**Comment by kennymckormick** [comment]
Thanks for reporting the bug. We raised a PR #523 to fix that.

**Comment by SKBL5694** [comment]
> Thanks for reporting the bug. We raised a PR #523 to fix that.
Very lucky to help you find bugs :-)
So in my current situation, which choice is better? Rename the data or modify some codes? Can you give me some advice?

**Comment by SKBL5694** [comment]
> Thanks for reporting the bug. We raised a PR #523 to fix that.

Very lucky to help you find bugs :-)
So in my current situation, which choice is better? Rename the data or modify some codes? Can you give me some advice?

**Comment by kennymckormick** [comment]
> > Thanks for reporting the bug. We raised a PR #523 to fix that.
> 
> Very lucky to help you find bugs :-)
> So in my current situation, which choice is better? Rename the data or modify some codes? Can you give me some advice?

Maybe modifying some codes will be faster, renaming so many frames may take a while.
