### ISSUE TITLE
About Precise BN

### ISSUE THREAD

**Issue by kennymckormick** [open-mmlab/mmaction2#524]
In the implementation of Precise BN, we register a hook which will be called `after_train_epoch`. However, the priority of this hook is not set and seems it will be called after saving checkpoint (which would be useless). Would you please double check it?

**Comment by kennymckormick** [comment]
@gengenkai. It's about changing the priority of PreciseBN and check if there's any difference in performance.

**Comment by gengenkai** [comment]
Got it. 
I will check it this week.

**Comment by dreamerlin** [comment]
You can also refer to https://github.com/facebookresearch/fvcore/blob/master/fvcore/nn/precise_bn.py to update the codes for actual population variance calculation
