### ISSUE TITLE
About  the new way to download kinetics datasets

### ISSUE THREAD

**Issue by zackzhao1** [open-mmlab/mmaction2#526]
You can also download kinetics400 and kinetics700 from [Academic Torrents](https://academictorrents.com/details/184d11318372f70018cf9a72ef867e2fb9ce1d26).

Is the original videos of kinetics400 and kinetics700  the same? I only see a link.
And kinetics600?

**Comment by innerlee** [comment]
@irvingzhang0512

**Comment by irvingzhang0512** [comment]
Kinetics 700 link is [here](https://academictorrents.com/details/49f203189fb69ae96fb40a6d0e129949e1dfec98)

Don't know who upload this, so I have no idea why kinetics 600 is not available.
