### ISSUE TITLE
Testing out AVA model with rawframes

### ISSUE THREAD

**Issue by nikky4D** [open-mmlab/mmaction2#528]
Hi,

I am trying to run the colab demo using one of the AVA checkpoints: 
`checkpoint = 'checkpoints/slowonly_omnisource_pretrained_r50_4x16x1_20e_ava_rgb_20201217-0c6d2e98.pth'
with config file:
`config = 'configs/detection/ava/slowonly_omnisource_pretrained_r50_4x16x1_20e_ava_rgb.py'`

I get an error at the line:
```
# Initialize the recognizer
model = init_recognizer(config, checkpoint, device='cuda:0', use_frames=True)
```
 that says mismatch between inputs as I am using rawframes but input is AVADataset. 

`RuntimeError: input data type should be consist with the dataset type in config, but got input type 'rawframes' and dataset type 'AVADataset'`

Can anyone help me fix this? And what is the AVADataset format?

**Comment by irvingzhang0512** [comment]
Actually, models for ava dataset are not `recognizer`. So you cannot init ava models with `init_recognizer`

**Comment by nikky4D** [comment]
I thought that might be the case. However, how would I use it with the apis then? Is there a sample to extend the API for this?

**Comment by irvingzhang0512** [comment]
@nikky4D There is a demo about ava now, you can refer to [demo_spatiotemporal_det.py](https://github.com/open-mmlab/mmaction2/blob/master/demo/demo_spatiotemporal_det.py)

**Comment by nikky4D** [comment]
Niceeee. Thank you. I'll check it out.

**Comment by skyqwe123** [comment]
> Hi,
> 
> I am trying to run the colab demo using one of the AVA checkpoints:
> `checkpoint = 'checkpoints/slowonly_omnisource_pretrained_r50_4x16x1_20e_ava_rgb_20201217-0c6d2e98.pth' with config file: `config = 'configs/detection/ava/slowonly_omnisource_pretrained_r50_4x16x1_20e_ava_rgb.py'`
> 
> I get an error at the line:
> 
> ```
> # Initialize the recognizer
> model = init_recognizer(config, checkpoint, device='cuda:0', use_frames=True)
> ```
> 
> that says mismatch between inputs as I am using rawframes but input is AVADataset.
> 
> `RuntimeError: input data type should be consist with the dataset type in config, but got input type 'rawframes' and dataset type 'AVADataset'`
> 
> Can anyone help me fix this? And what is the AVADataset format?

@nikky4D @irvingzhang0512 
I meet the same error when i trying to run the tools/test.py:
python tools/test.py  configs/recognition/tpn_slowonly_r50_8x8x1_150e_actev_rgb.py checkpoints/epoch_165.pth
--eval top_k_accuracy mean_class_accuracy
I get an error:
test.py: error: unrecognized arguments: configs/recognition/tpn_slowonly_r50_8x8x1_150e_actev_rgb.py checkpoints/epoch_165.pth
Do you know how to solve it？Thanks

**Comment by nikky4D** [comment]
hi, I have not used this in sometime. however, it looks like you are missing the model checkpoint
