### ISSUE TITLE
Iteration Plan - Jan 2021

### ISSUE THREAD

**Issue by dreamerlin** [open-mmlab/mmaction2#531]
Since MMAction2 v0.10.0 has been released, now it's time to plan for the next iteration, i.e. v0.11.0.
This will be a one-month iteration and our focus in this iteration is to refactor the code/doc structure

**Algorithms**:
- [ ] ~~TAM(https://github.com/open-mmlab/mmaction2/pull/304)~~
- [ ] ~~SCSampler (https://github.com/open-mmlab/mmaction2/pull/381)~~
- [ ] ~~Long-term feature banks~~

**Improvement**
- [x] Refactor our config file structure (https://github.com/open-mmlab/mmaction2/pull/488)
- [x] Refactor our unittest file structure (https://github.com/open-mmlab/mmaction2/pull/433)
- [ ] ~~Refactor codebase according to design document~~

delay:
~~TAM(https://github.com/open-mmlab/mmaction2/pull/304)~~
~~Long-term feature banks~~
~~Refactor codebase according to design document~~

**Comment by irvingzhang0512** [comment]
+ [ ] Support TSM-MobileNetV2. (#415)
+ [ ] Support Imgaug for augmentations in the data pipeline (#492)
+ [ ] Support albumentations for augmentations in the data pipeline.
+ [ ] Train/Test custom classes for ava dataset.
+ [ ] (Maybe) Ava webcam demo.
+ [ ] (Maybe) Train custom dataset for spatio-temporal action detection.
