### ISSUE TITLE
Many samples are missing in official Kinetics annotations.

### ISSUE THREAD

**Issue by irvingzhang0512** [open-mmlab/mmaction2#533]
Kinetics 400 annotaions from [official website](https://storage.googleapis.com/deepmind-media/Datasets/kinetics400.tar.gz) have fewer samples than expected. 

Now, There are only 219561 training samples and 18014 validation samples in the above annotation files. I think the missing samples are removed because they are not avaiable on youtube. 

Incomplete annotations leads to imcomplete filelist.

**Comment by innerlee** [comment]
Interesting, are there any official message about this change? Is the dataset versioned at all?

**Comment by irvingzhang0512** [comment]
I haven't seen related news...

**Comment by dreamerlin** [comment]
See https://github.com/open-mmlab/mmaction2/pull/597, we provide an alternative way to download older kinetics annotations
