### ISSUE TITLE
Still some bugs during AVA training

### ISSUE THREAD

**Issue by SKBL5694** [open-mmlab/mmaction2#534]
I reported some bugs during AVA training last time. Finally(I rename the image files manually), I can run the command 
"./tools/dist_train.sh
configs/detection/ava/slowfast_kinetics_pretrained_r50_8x8x1_20e_ava_rgb.py 4 --validate" in my PC. But during Epoch[1] [120/11524], it raise a bug "FileNotFoundError: [Errno 2] No such file or directory: '/home/avadata/ava/rawframes/7g37N3eoQ9s/img_26368.jpg'". It seems like There are still some bugs in the file name correspondence.  
BTW, I find that in the config file I'm using, line89 and line 90 are as follows :
line89: # Rename is needed to use mmdet detectors
line90:    dict(type='Rename', mapping=dict(imgs='img'))
These codes maybe use for change the file name from ${video_name}_00001.jpg to img_00001.jpg(I guess). But actually, it does not work for some reasons. And I can not find a module named "Rename" in mmdet. 
Hope you can check the questions, thanks a lot.

**Comment by irvingzhang0512** [comment]
`dict(type='Rename', mapping=dict(imgs='img'))` cannot rename {video_name}_00001.jpg to img_00001.jpg.

Have you generated ava frames followed by PySlowFast repo? In PySlowFast, frame filename format is `{video_name}_{:05}.jpg`. In mmaction2, default frame filename format is `img_{:05d}.jpg`

You can generate ava frames after [mmaction2 data tools](https://github.com/open-mmlab/mmaction2/tree/master/tools/data/ava#step-4-extract-rgb-and-flow)

**Comment by SKBL5694** [comment]
> `dict(type='Rename', mapping=dict(imgs='img'))` cannot rename {video_name}_00001.jpg to img_00001.jpg.
> 
> Have you generated ava frames followed by PySlowFast? In PySlowFast, frame filename format is `{video_name}_{:05}.jpg`. In mmaction2, default frame filename format is `img_{:05d}.jpg`
> 
> You can generate ava frames after [mmaction2 data tools](https://github.com/open-mmlab/mmaction2/tree/master/tools/data/ava#step-4-extract-rgb-and-flow).

I don't know what is PySlowFast, can you tell me where can I find it?
I followed this tutorial https://mmaction2.readthedocs.io/en/latest/supported_datasets.html#ava to prepare my data. But after I do all steps, my filename is not same as the filename in step 6.

**Comment by irvingzhang0512** [comment]
Oh I see, this is a bug in `extract_rgb_frames_ffmpeg.sh`.

For now, you could try to extract rgb with `bash extract_rgb_frames.sh` or `bash extract_rgb_frames_opencv.sh`

**Comment by SKBL5694** [comment]
> Oh I see, this is a bug in `extract_rgb_frames_ffmpeg.sh`.
> 
> For now, you could try to extract rgb with `bash extract_rgb_frames.sh` or `bash extract_rgb_frames_opencv.sh`

Is the rename function more than just changing {video_name}_{:05}.jpg to img_{:05d}.jpg? I write a rename script to do that. But is still raise a bug I've reported  [Errno 2] No such file or directory: '/home/avadata/ava/rawframes/7g37N3eoQ9s/img_26368.jpg.
I found in the folder '7g37N3eoQ9s', there are only 26173 frames. I'm afraid after I do `bash extract_rgb_frames.sh` or bash `extract_rgb_frames_opencv.sh` this bug still exists.

**Comment by irvingzhang0512** [comment]
There should be 27030 frames for every video. Could you please check whether your 15min videos are properly cut?

**Comment by SKBL5694** [comment]
> There should be 27030 frames for every video. Could you please check whether your 15min videos are properly cut? I'll try to cut and extract rgb frames of `7g37N3eoQ9s.mkv`

Thanks a lot. I check my files and I found two videos are wrong.
7g37N3eoQ9s: 26173
Gt61_Yekkgc: 25427
I exeract AVA data twice ,one is on my PC and the other is on the public server in our laboratory, both have the same result. I guess it may be a bug coming from ffmpeg.
So the question is how to make some small changes to complete my training. Can you give some commands to help me with this problem?

**Comment by irvingzhang0512** [comment]
I could reproduce your bug, only 26174 frames extracted from 7g37N3eoQ9s.mkv. It seems something going wrong with ffmpeg.

You could recut&extract 7g37N3eoQ9s/Gt61_Yekkgc with script like(remove `-strict experimental` in cut script)

```shell
# recut
ffmpeg -ss 900 -t 901 -r 30 -i "/path/to/videos/7g37N3eoQ9s.mkv" "/path/to/videos_15min/7g37N3eoQ9s.mp4"
ffmpeg -ss 900 -t 901 -r 30 -i "/path/to/videos/Gt61_Yekkgc.mkv"  "/path/to/videos_15min/Gt61_Yekkgc.mp4"
ffmpeg -i "/path/to/videos_15min/7g37N3eoQ9s.mp4" -r 30 -q:v 1 "/path/to/rawframes/7g37N3eoQ9s/img_%05d.jpg"
ffmpeg -i "/path/to/videos_15min/Gt61_Yekkgc.mp4" -r 30 -q:v 1 "/path/to/rawframes/Gt61_Yekkgc/img_%05d.jpg"
```

BTW, it seems opencv could properly extract all videos...

**Comment by SKBL5694** [comment]
> I could reproduce your bug, only 26174 frames extracted from 7g37N3eoQ9s.mkv. It seems something going wrong with ffmpeg.
> 
> You could recut&extract 7g37N3eoQ9s/Gt61_Yekkgc with script like(remove `-strict experimental` in cut script)
> 
> ```shell
> # recut
> ffmpeg -ss 900 -t 901 -r 30 -i "/path/to/videos/7g37N3eoQ9s.mkv" "/path/to/videos_15min/7g37N3eoQ9s.mp4"
> ffmpeg -ss 900 -t 901 -r 30 -i "/path/to/videos/Gt61_Yekkgc.mkv"  "/path/to/videos_15min/Gt61_Yekkgc.mp4"
> ffmpeg -i "/path/to/videos_15min/7g37N3eoQ9s.mp4" -r 30 -q:v 1 "/path/to/rawframes/7g37N3eoQ9s/img_%05d.jpg"
> ffmpeg -i "/path/to/videos_15min/Gt61_Yekkgc.mp4" -r 30 -q:v 1 "/path/to/rawframes/Gt61_Yekkgc/img_%05d.jpg"
> ```
> 
> BTW, it seems opencv could properly extract rgb frames from all videos...

Thanks a lot. 🙇‍ You are so friendly. I will try opencv next time.

**Comment by irvingzhang0512** [comment]
I'm not familiar with ffmpeg. The bug is listed as follows.

```shell
# origin scripts, only 26174 frames extracted
ffmpeg -ss 900 -t 901 -r 30 -i "/path/to/videos/7g37N3eoQ9s.mkv" -strict experimental  "/path/to/videos_15min/7g37N3eoQ9s.mp4"
ffmpeg -i "/path/to/videos_15min/7g37N3eoQ9s.mp4" -r 30 -q:v 1 "/path/to/rawframes/7g37N3eoQ9s/img_%05d.jpg"


# remove `-strict experimental` in cut cmd, 27030 frames extracted 
ffmpeg -ss 900 -t 901 -r 30 -i "/path/to/videos/7g37N3eoQ9s.mkv" "/path/to/videos_15min/7g37N3eoQ9s.mp4"
ffmpeg -i "/path/to/videos_15min/7g37N3eoQ9s.mp4" -r 30 -q:v 1 "/path/to/rawframes/7g37N3eoQ9s/img_%05d.jpg"
```

@innerlee @dreamerlin  Any ideas?

**Comment by irvingzhang0512** [comment]
@SKBL5694 Happy to help. I happened to be doing something similar

**Comment by SKBL5694** [comment]
> @SKBL5694 Happy to help. I happened to be doing something similar

I go to your homepage and I found you are 清欢. I've read your blogs on CSDN and zhihu many times. Thanks again.

**Comment by irvingzhang0512** [comment]
Thanks. 

I tried opencv, it shows there are 27030 frames but only 26172 could be read, so opencv cannot work, either.

**Comment by SKBL5694** [comment]
> Thanks.
> 
> I tried opencv, it shows there are 27030 frames but only 26172 could be read, so opencv cannot work, either.

I use`ffmpeg -ss 900 -t 901 -r 30 -i "/path/to/videos/7g37N3eoQ9s.mkv" "/path/to/videos_15min/7g37N3eoQ9s.mp4"` and 
`ffmpeg -i "/path/to/videos_15min/7g37N3eoQ9s.mp4" -r 30 -q:v 1 "/path/to/rawframes/7g37N3eoQ9s/img_%05d.jpg"`
But I get 26173 frames again QAQ

**Comment by irvingzhang0512** [comment]
我傻了，英文说不出来了，晚点我再看下

**Comment by SKBL5694** [comment]
> 我傻了，英文说不出来了，晚点我再看下

Okay, trouble you. If it is convenient for you, you can add my WeChat：1776539381 name:饮冰

**Comment by kennymckormick** [comment]
> > Oh I see, this is a bug in `extract_rgb_frames_ffmpeg.sh`.
> > For now, you could try to extract rgb with `bash extract_rgb_frames.sh` or `bash extract_rgb_frames_opencv.sh`
> 
> Is the rename function more than just changing {video_name}_{:05}.jpg to img_{:05d}.jpg? I write a rename script to do that. But it still raise a bug I've reported [Errno 2] No such file or directory: '/home/avadata/ava/rawframes/7g37N3eoQ9s/img_26368.jpg.
> I found in the folder '7g37N3eoQ9s', there are only 26173 frames. I'm afraid after I do `bash extract_rgb_frames.sh` or bash `extract_rgb_frames_opencv.sh` this bug still exists.

The Rename function changes the key 'imgs' in the results dictionary to 'img' (just because mmdetction uses 'img'). The `extract_rgb_frames_ffmepg.sh` has a bug (the image name template is wrong). We raise PR #523 to fix it.

**Comment by SKBL5694** [comment]
@irvingzhang0512 今晚b站有商汤官方讲解mmaction2的直播，你要来看一看么(不知道怎么能通知到你，就在这里通知了，sry)

**Comment by irvingzhang0512** [comment]
@SKBL5694 我要带娃，之后会看视频的，看看大佬的风采 @dreamerlin

**Comment by irvingzhang0512** [comment]
> I'm not familiar with ffmpeg. The bug is listed as follows.
> 
> ```shell
> # origin scripts, only 26174 frames extracted
> ffmpeg -ss 900 -t 901 -r 30 -i "/path/to/videos/7g37N3eoQ9s.mkv" -strict experimental  "/path/to/videos_15min/7g37N3eoQ9s.mkv"
> ffmpeg -i "/path/to/videos_15min/7g37N3eoQ9s.mp4" -r 30 -q:v 1 "/path/to/rawframes/7g37N3eoQ9s/img_%05d.jpg"
> 
> 
> # remove `-r 30` in cut cmd, 27030 frames extracted 
> ffmpeg -ss 900 -t 901 -i "/path/to/videos/7g37N3eoQ9s.mkv"  -strict experimental "/path/to/videos_15min/7g37N3eoQ9s.mkv"
> ffmpeg -i "/path/to/videos_15min/7g37N3eoQ9s.mp4" -r 30 -q:v 1 "/path/to/rawframes/7g37N3eoQ9s/img_%05d.jpg"
> ```
> 
> @innerlee @dreamerlin Any ideas?

@dreamerlin The above bug is still there, maybe we need to reopen this issue or open a new issue to track this

**Comment by kennymckormick** [comment]
> > I'm not familiar with ffmpeg. The bug is listed as follows.
> > ```shell
> > # origin scripts, only 26174 frames extracted
> > ffmpeg -ss 900 -t 901 -r 30 -i "/path/to/videos/7g37N3eoQ9s.mkv" -strict experimental  "/path/to/videos_15min/7g37N3eoQ9s.mkv"
> > ffmpeg -i "/path/to/videos_15min/7g37N3eoQ9s.mp4" -r 30 -q:v 1 "/path/to/rawframes/7g37N3eoQ9s/img_%05d.jpg"
> > 
> > 
> > # remove `-r 30` in cut cmd, 27030 frames extracted 
> > ffmpeg -ss 900 -t 901 -i "/path/to/videos/7g37N3eoQ9s.mkv"  -strict experimental "/path/to/videos_15min/7g37N3eoQ9s.mkv"
> > ffmpeg -i "/path/to/videos_15min/7g37N3eoQ9s.mp4" -r 30 -q:v 1 "/path/to/rawframes/7g37N3eoQ9s/img_%05d.jpg"
> > ```
> > 
> > 
> > @innerlee @dreamerlin Any ideas?
> 
> @dreamerlin The above bug is still there, maybe we need to reopen this issue or open a new issue to track this

I reproduced this bug, seems we should remove `-r 30` in `cut_videos.sh`

**Comment by innerlee** [comment]
@irvingzhang0512 @kennymckormick join the party late. I guess `-r` should be placed after the `-i` option.

ffmpeg arguments are sensitive to positions. in `ffmpeg -r 30 -i input.mp4 output.mp4`, the `-r` acts on input video. in `ffmpeg -i input.mp4 -r 30 output.mp4`, the output is set to 30fps.

**Comment by irvingzhang0512** [comment]
> @irvingzhang0512 @kennymckormick join the party late. I guess `-r` should be placed after the `-i` option.
> 
> ffmpeg arguments are sensitive to positions. in `ffmpeg -r 30 -i input.mp4 output.mp4`, the `-r` acts on input video. in `ffmpeg -i input.mp4 -r 30 output.mp4`, the output is set to 30fps.

You are right, successfully get 27030 frames by the following cmds.

```shell
ffmpeg -ss 900 -t 901 -i "./7g37N3eoQ9s.mkv" -r 30 -strict experimental "test.mkv"
ffmpeg -i "test.mkv" -r 30 -q:v 1 "./test/img_%05d.jpg"
```
