### ISSUE TITLE
Pretrained TSN models on ActivityNet v1.3

### ISSUE THREAD

**Issue by haofanwang** [open-mmlab/mmaction2#535]
1. What is the difference between [tsn_r50_320p_1x1x8_50e_activitynet_video_flow.py](https://github.com/open-mmlab/mmaction2/blob/master/configs/recognition/tsn/tsn_r50_320p_1x1x8_50e_activitynet_video_flow.py) and [tsn_r50_320p_1x1x8_50e_activitynet_clip_flow.py](https://github.com/open-mmlab/mmaction2/blob/master/configs/recognition/tsn/tsn_r50_320p_1x1x8_50e_activitynet_clip_flow.py)?

2. How can I test this model on a given video just like the [tutorial](https://github.com/open-mmlab/mmaction2/blob/master/demo/mmaction2_tutorial.ipynb)? I make some modifications as below, but it doesn't work.

3. Given the extracted denseflow images, I want to feed them to a pretrained TSN model (tsn_r50_320p_1x1x8_50e_activitynet_video_flow.py) and get the features. What pre-precessing should I do on the denseflow images?

**Comment by kennymckormick** [comment]
1. Video uses untrimmed videos for training; Clip uses trimmed clips for training. All of them use trimmed clips for testing.
2. You should first extract rgb & flow frames from it, and fed them to rgb / flow based models.
3. Please refer to the [testing pipeline](https://github.com/open-mmlab/mmaction2/blob/28271912a110ddcd7ded1ecd09c9d13fc51436fd/configs/recognition/tsn/tsn_r50_320p_1x1x8_150e_activitynet_video_flow.py#L57). That is the preprocessing procedure needed before you feed it into the model.
