### ISSUE TITLE
How to use BNInception or Inception V3 as a backbone

### ISSUE THREAD

**Issue by AlexanderAsfar** [open-mmlab/mmaction2#536]
What are the possible ways of using the pretrained Inception_V3 from torchvision as a backbone in the configuration files? Also, is there a way to use BNInception as well?

Thank you.

**Comment by kennymckormick** [comment]
@dreamerlin @innerlee What about the following design: most torchvision models has a module named `classifier`, if we register a hook on that module, we can get the input of the classifier, which is the feature we needed for action recognition. By implementing this, we can use any torchvision models for TSN2D, etc.

**Comment by dreamerlin** [comment]
@hellock @https://github.com/LXXXXR, @https://github.com/ycxioooong, A backbone request for MMClassification ?

**Comment by dreamerlin** [comment]
Inception_V3 can be directly loaded in torchvision, see https://github.com/open-mmlab/mmaction2/pull/720;
For BNInception, it will be supported in MMCls in the future
