### ISSUE TITLE
mmdet error

### ISSUE THREAD

**Issue by mytk2012** [open-mmlab/mmaction2#537]
(open-mmlab) c@1:~/projects/mmaction2$ p**ython 1.py**

Traceback (most recent call last):
  File "1.py", line 2, in <module>
    from mmaction.apis import init_recognizer, inference_recognizer
  File "/home/c/projects/mmaction2/mmaction/apis/__init__.py", line 1, in <module>
    from .inference import inference_recognizer, init_recognizer
  File "/home/c/projects/mmaction2/mmaction/apis/inference.py", line 10, in <module>
    from mmaction.core import OutputHook
  File "/home/c/projects/mmaction2/mmaction/core/__init__.py", line 1, in <module>
    from .bbox import *  # noqa: F401, F403
  File "/home/c/projects/mmaction2/mmaction/core/bbox/__init__.py", line 1, in <module>
    from .assigners import MaxIoUAssignerAVA
  File "/home/c/projects/mmaction2/mmaction/core/bbox/assigners/__init__.py", line 1, in <module>
    from .max_iou_assigner_ava import MaxIoUAssignerAVA
  File "/home/c/projects/mmaction2/mmaction/core/bbox/assigners/max_iou_assigner_ava.py", line 6, in <module>
    from mmdet.core.bbox import AssignResult, MaxIoUAssigner
  File "/home/c/projects/ObjectDetection/mmdetection-master/mmdet/core/__init__.py", line 4, in <module>
    from .export import *  # noqa: F401, F403
  File "/home/c/projects/ObjectDetection/mmdetection-master/mmdet/core/export/__init__.py", line 1, in <module>
    from .pytorch2onnx import (build_model_from_cfg,
  File "/home/c/projects/ObjectDetection/mmdetection-master/mmdet/core/export/pytorch2onnx.py", line 11, in <module>
    **raise NotImplementedError('please update mmcv to version>=v1.0.4')**
NotImplementedError: please update mmcv to version>=v1.0.4
(open-mmlab) c@1:~/projects/mmaction2$ p**ip list**
Package               Version             Location
--------------------- ------------------- ---------------------------------------------------
addict                2.4.0
certifi               2020.12.5
cycler                0.10.0
Cython                0.29.21
future                0.18.2
kiwisolver            1.3.1
matplotlib            3.3.3
mkl-fft               1.2.0
mkl-random            1.1.1
mkl-service           2.3.0
mmaction2             0.10.0              /home/c/projects/mmaction2
**mmcv-full             1.2.5**
mmdet                 2.6.0               /home/c/projects/ObjectDetection/mmdetection-master
mmpycocotools         12.0.3
numpy                 1.19.2
olefile               0.46
onnx                  1.8.0
opencv-contrib-python 4.5.1.48
opencv-python         4.5.1.48
Pillow                8.1.0
pip                   20.3.3
protobuf              3.14.0
pyparsing             3.0.0b2
python-dateutil       2.8.1
PyYAML                5.3.1
setuptools            51.0.0.post20201207
six                   1.15.0
terminaltables        3.1.0
torch                 1.5.1
torchvision           0.6.0a0+35d732a
typing-extensions     3.7.4.3
wheel                 0.36.2
yapf                  0.30.0

1.py is:
import torch
from mmaction.apis import init_recognizer, inference_recognizer

config_file = 'configs/recognition/tsn/tsn_r50_video_inference_1x1x3_100e_kinetics400_rgb.py'
device = 'cuda:0' # or 'cpu'
device = torch.device(device)

model = init_recognizer(config_file, device=device)
# inference the demo video
inference_recognizer(model, 'demo/demo.mp4', 'demo/label_map.txt')

**Comment by mytk2012** [comment]
import torch
from mmaction.apis import init_recognizer, inference_recognizer

config_file = 'configs/recognition/tsn/tsn_r50_video_inference_1x1x3_100e_kinetics400_rgb.py'
device = 'cuda:0' # or 'cpu'
device = torch.device(device)
model = init_recognizer(config_file, device=device)
# inference the demo video
inference_recognizer(model, 'demo/demo.mp4', 'demo/label_map.txt')

**Comment by mytk2012** [comment]
I have checked the mmcv_version is 1.2.5,but the error is:please update mmcv to version>=v1.0.4,so confused.

**Comment by dreamerlin** [comment]
It seems that you should update your mmdet (https://github.com/open-mmlab/mmdetection/blob/master/mmdet/core/export/pytorch2onnx.py)

**Comment by mytk2012** [comment]
I have installed it successfully.But when I run your **Verification**.it seemed nothing has happened,is there something wrong?
**Verification codes** are as belows:
import torch
from mmaction.apis import init_recognizer, inference_recognizer

config_file = 'configs/recognition/tsn/tsn_r50_video_inference_1x1x3_100e_kinetics400_rgb.py'
device = 'cuda:0' # or 'cpu'
device = torch.device(device)

model = init_recognizer(config_file, device=device)
# inference the demo video
inference_recognizer(model, 'demo/demo.mp4', 'demo/label_map.txt')

**THE RESPONSE ARE:**
(open-mmlab) c@1:~/projects/mmaction2$ python 1.py 
(open-mmlab) c@1:~/projects/mmaction2$

**Comment by dreamerlin** [comment]
Nothing Wrong. No news is good news. You have succeeded in installing it, congratulations!

**Comment by mytk2012** [comment]
Thanks！

**Comment by dreamerlin** [comment]
> Thanks！

If you feel we have help you, give us a STAR! : )
