### ISSUE TITLE
error occurs at `assert 'policy' in lr_config` when i am training my custom model with TSM

### ISSUE THREAD

**Issue by wwdok** [open-mmlab/mmaction2#539]
I am using TSM to train model on my custom dataset, when it runs to `train_model(model, datasets, cfg, distributed=False, validate=True)` in colab, it reports following error:
![image](https://user-images.githubusercontent.com/43233772/104460557-35020d80-55e9-11eb-8d11-0d9e486018b1.png)
This error seems say that if  'policy' is not in lr_config, it will raise error, but my printed cfg.pretty_text shows that my config contain `lr_config = dict(policy='step', step=[20, 40])`
![image](https://user-images.githubusercontent.com/43233772/104460845-8ca07900-55e9-11eb-8b3f-da0f568104d4.png)

**Comment by dreamerlin** [comment]
Could you show me your full code ? Or the colab url you use ?

**Comment by wwdok** [comment]
It is a little wierd, today i rerun the colab, this error has gone away, maybe there was a problem with the environment yesterday.
