### ISSUE TITLE
Training i3d with optical flow

### ISSUE THREAD

**Issue by AlexanderAsfar** [open-mmlab/mmaction2#550]
Hello,

I'm trying to train i3d with optical flow, but I get this error:
`RuntimeError: Expected 5-dimensional input for 5-dimensional weight [64, 3, 5, 7, 7], but got 4-dimensional input of size [8, 64, 224, 224] instead`
I don't understand why it is asking for a 5 dimensional input when the flow is in grayscale.
Here is the config file I'm using: [i3d_r50_100e_ucf101_flow.py.zip](https://github.com/open-mmlab/mmaction2/files/5839453/i3d_r50_100e_ucf101_flow.py.zip)

Thank you.

**Comment by innerlee** [comment]
Random guess: the format shape is wrong. I3D is 3d model while tsn is 2d, so you may forgot one dim

**Comment by innerlee** [comment]
Okay it seems that NCTHW_Flow is missing right now

**Comment by innerlee** [comment]
@AlexanderAsfar see https://github.com/open-mmlab/mmaction2/blob/master/configs/recognition/slowonly/slowonly_r50_4x16x1_256e_kinetics400_flow.py#L70

**Comment by kennymckormick** [comment]
You may modify the config file based on https://github.com/open-mmlab/mmaction2/blob/master/configs/recognition/slowonly/slowonly_r50_4x16x1_256e_kinetics400_flow.py#L70, maybe change the backbone and frame sampling strategies.

**Comment by dreamerlin** [comment]
If you feel we have help you, give us a STAR! : ) @AlexanderAsfar

**Comment by AlexanderAsfar** [comment]
Hello, I did give you a star. Also, I posted a comment on #565 since that was the same issue I am having but for i3d
