### ISSUE TITLE
Training Slowfast (or any other) Networks on a new dataset with zipped video frames 

### ISSUE THREAD

**Issue by srikanth-sfu** [open-mmlab/mmaction2#554]
Hi,

I would like to process a dataset with video frames stored inside a zip file. Please suggest the quickest way to achieve this.

Thanks!

**Comment by innerlee** [comment]
Writing a script to extract all frames is the fastest AFAIK.

**Comment by srikanth-sfu** [comment]
Unfortunately, It is not possible to have all the video frames unzipped due to physical constraints of the machine.

**Comment by innerlee** [comment]
Do you know the number of frames of videos? Do you want to train or inference?

**Comment by irvingzhang0512** [comment]
Maybe you could write a script to convert frames to videos first, and then use `VideoDataset`. Videos are much smaller than raw frames.

**Comment by srikanth-sfu** [comment]
I want to do both. It is possible to get information about the number of frames in a video beforehand.

**Comment by innerlee** [comment]
Yeah video is a better option

**Comment by srikanth-sfu** [comment]
Thanks -- I do have videos. In my other classifier experiments (outside mmaction), we didn't use videos, but the zipped frames. I didn't try using video directly as input, as I was concerned about the speed.

**Comment by innerlee** [comment]
Videos can be as fast as frames

**Comment by srikanth-sfu** [comment]
I will try using videos then. Thanks for the suggestions. Closing this issue for now.

**Comment by SuX97** [comment]
Hi @srikanth-sfu ,
I am not sure what `zipped video frames` are, are you suggesting something like zipping all frames into a compact database like hdf5/lmdb? Here is an example: https://github.com/open-mmlab/mmaction/blob/c7e3b7c11fb94131be9b48a8e3d510589addc3ce/tools/generate_lmdb.py

**Comment by srikanth-sfu** [comment]
Hi @SuX97, thanks, this is interesting. However, I have my frames stored inside zip files. I have to check if mmcv has similar method to process zip files as opposed to lmdb files.

**Comment by SuX97** [comment]
> Hi @SuX97, thanks, this is interesting. However, I have my frames stored inside zip files. I have to check if mmcv has similar method to process zip files as opposed to lmdb files. One more thing to add here is the way I read images from zip files is quite similar to lmdb code you shared.

That's an interesting request, as most video datasets are distributed by raw videos. This one seems promising, https://github.com/open-mmlab/mmskeleton/blob/82bf68a5d3a6b530721ea407086a65d97cc71ff1/mmskeleton/datasets/utils/zipreader.py, you may integrate it into `RawFrameDecode`.

**Comment by srikanth-sfu** [comment]
The dataset was originally distributed by raw videos. In our classifier pipelines, we first extract frames and then perform further processing on frame folders. However, this wasn't possible with this particular dataset due to size limits. Which is why we resorted to using zipped frame folders.

**Comment by dreamerlin** [comment]
> Thanks -- The dataset was originally distributed by raw videos. In our classifier pipelines, we first extract frames and then perform further processing on frame folders. However, this wasn't possible with this particular dataset due to size limits. Which is why we resorted to using zipped frame folders.
> Also, since I am new to mmaction package, it would be great if you could point out RawFrameDecode integration steps.
> Thanks!

If you feel we have help you, give us a STAR! : )
