### ISSUE TITLE
Would MMAction2 Work for multiple people

### ISSUE THREAD

**Issue by trile127** [open-mmlab/mmaction2#559]
For example, would it work for two people dancing for a specific move, such as a turn? Or should I train it on an individual person. What about people in the background? How would I ignore that 'noise'?

Also, The output classifies the move per frame, would it be possible to classify a set of consecutive frames, such as over 3 seconds?

**Comment by innerlee** [comment]
It depends on your needs.

If the two person's action together count as one action, then you do not need to train on individual person. E.g. you want to find if two dancer are battling. Just directly train one model and see if it is ok.  

The second question. You can try 3d models.
