### ISSUE TITLE
Frame based action recognition model 

### ISSUE THREAD

**Issue by ayanasser** [open-mmlab/mmaction2#560]
Hi, 
I'm looking for a frame based action recognition model, Is there a one ?
 I've found that most of the models here need (a batch of frames) as input

**Comment by innerlee** [comment]
1. simply repeat the same frame
2. 2d models are basically frame based

**Comment by kennymckormick** [comment]
You can train a TSN with `num_segments = 1`, then it is equivalent to an image classifier
