### ISSUE TITLE
How to generate AVA demo gif like yours?

### ISSUE THREAD

**Issue by SKBL5694** [open-mmlab/mmaction2#562]
I've finished training AVA data. I want to know to visualize the results like the gif 'Spatio-Temporal Action Detection Results on AVA-2.1' in the introduction.

**Comment by innerlee** [comment]
Have you tried the https://github.com/open-mmlab/mmaction2/blob/master/demo/demo_spatiotemporal_det.py ?

**Comment by innerlee** [comment]
@kennymckormick we can add a doc at https://github.com/open-mmlab/mmaction2/blob/master/demo/README.md

**Comment by SKBL5694** [comment]
> Have you tried the https://github.com/open-mmlab/mmaction2/blob/master/demo/demo_spatiotemporal_det.py ?

I'll try, thx
