### ISSUE TITLE
Training process stuck at the beginning

### ISSUE THREAD

**Issue by wwdok** [open-mmlab/mmaction2#564]
I am going to training on my 4 action classes dataset, this is the [dataset](https://drive.google.com/file/d/1_K8R08lj_1iHkkWlg-CNqcVuqp1pwkYl/view?usp=sharing) for reproducing this error.
At first, i trained it on [colab](https://colab.research.google.com/drive/1pn0kXRvt0ZRFHkIxVm44ahkyLMaKK9zF#scrollTo=tlhu9byjjt-K), but it stuck at 70th iterration in 1st epoch, then i change `cfg.data.videos_per_gpu` from 8 to 4 , then it stuck at 140th iterration in 1st epoch. I am wonderring why it stuck at the same place ? Is the problem of my video dataset or the problem of code ?
![image](https://user-images.githubusercontent.com/43233772/105830707-cec1b580-6000-11eb-95d0-4626fa06d772.png)

Then, i trained it on my computer whose GPU is GTX 1080 Ti, this time it stucked exactly at the beginning, it has been stuck for several hours, it is similar to [this issue](https://github.com/open-mmlab/mmaction2/issues/421), this issue still occurred even i set `workers_per_gpu=0`
![image](https://user-images.githubusercontent.com/43233772/105830335-53f89a80-6000-11eb-833c-acaa622ab8f7.png)

**Comment by innerlee** [comment]
Please make a mini-mini-dataset, say containing only 100 samples. And try again

**Comment by wwdok** [comment]
emm, it still stuck at some place without any info :
![image](https://user-images.githubusercontent.com/43233772/105856977-c7ac9e80-6024-11eb-8db7-7102ae5d936d.png)
this time i use a [mini dataset](https://drive.google.com/file/d/1Zn3Qcz50BGMqPiSaD7hLN-wQqtZfmt1A/view?usp=sharing).

**Comment by SuX97** [comment]
> emm, it still stuck at some place without any info :

Hi, @wwdok ,

Could you please monitor your machine with `htop`, especially focus on the cpu/memory usage?

Also what dataset and pipeline did you use? This data_time seems very turbulent.

**Comment by wwdok** [comment]
Hi, @SuX97 , please check the screenshots after running the training command for 3 minutes on my own computer: 
Sort by cpu :
![image](https://user-images.githubusercontent.com/43233772/105950199-f1a7a480-60a8-11eb-8419-aea650fed134.png)
Sort by mem :
![image](https://user-images.githubusercontent.com/43233772/105950434-58c55900-60a9-11eb-9d29-c9aacb815ce7.png)
![image](https://user-images.githubusercontent.com/43233772/105950285-13a12700-60a9-11eb-852e-65f4bc75e094.png)
![image](https://user-images.githubusercontent.com/43233772/105950328-26b3f700-60a9-11eb-81d9-7f5655bb3eb2.png)
The computer stuck seems to be caused by the cpu.

**Comment by SuX97** [comment]
@wwdok 
Your load average is too high 
![image](https://user-images.githubusercontent.com/25632694/105953323-f458c880-60ad-11eb-9b0c-43358cb31e87.png), even larger than 1. Although you have multiple CPU but they are not used, a healthy threshold can be ~0.7(at least < 1.0).
.
1.  I am not sure why is there so many same processes since you only have one GPU, did you use many workers or simply start a lot of same processes? 
2. Why did you use only one CPU core which is ~100% utiled, but spare the other 47 ones?

**Comment by wwdok** [comment]
I don't know too, i just started the command `python tools/train.py configs/recognition/tsm/tsm_r50_video_1x1x8_30e_my4classes.py --validate --seed 0` only once and didn't do anything else, no use many workers, no start a lot of same process, no assign dedicated CPU, they are all happened automatically.

**Comment by innerlee** [comment]
Could you try to train on RawFrames? This can rule out the error caused by decoders. BTW if you are using decord, please use the version == 0.4.1. They introduced bugs on 0.4.2

**Comment by wwdok** [comment]
I have tried decoder == 0.4.1, it didn't work. I will try RawFrames these days.

**Comment by innerlee** [comment]
Could you make the the tiny dataset by repeating only one video? That can also rule out the decoding part

**Comment by wwdok** [comment]
Ok, i will try that too. In fact, last week, i can successfully train my custom TSM model with 2 action classes, this week i increase the action classes number to 4, then this error occured, yesterday i tried a mini dataset that is smaller than previous 2 classes dataset, but this problem still exists, so I am not sure if this is because the dataset size become larger or i introduced some troublesome video that produce decoding problem or other reasons.

**Comment by wwdok** [comment]
Maybe i have found the reason, it is very likely a problem with the video. During i run the `build_rawframe.py`, i found some video  happened following warning 'Early stop with {i + 1} out of {len(vr)} frames.' : 

![image](https://user-images.githubusercontent.com/43233772/106248506-0bcdb800-624c-11eb-9a66-7c0d53b9d4cd.png)

these problematic videos were cut out from some long videos with `moviepy`, so i modified the python script and re-generate videos with `moviepy` , this time all videos are normal and won't happen above warning again.
Now i have succefully trained 4 epochs without stuck.

**Comment by innerlee** [comment]
cool, I think we need to have some infrastructure to detect problematic videos. There are many freezing reports recently

**Comment by wwdok** [comment]
Yes, the videos could be the possible casue of training freeze, because when people are preparing their own video dataset,  in this process  it may happen some unpredictable faults, in my case, that is the video meta info is unmatched with its real length, that is to say, i expect to cut video to 5 seconds, but the output video show 13 seconds, this issue may only happen to me, but other kinds of video issue may happend to other peoples.

![image](https://user-images.githubusercontent.com/43233772/106404613-3dbe6480-646e-11eb-9e91-c6f185a26b1f.png)

**Comment by rlleshi** [comment]
Hi, @wwdok 

I am facing a similar issue and suspect to have the same underlying problem as you. For me, the training hangs after it has completed 5 full epochs. However, I am suspecting that some faulty videos might be the issue. I too am using `moviepy` to generate clips from my dataset. 

Could you please describe how did you fix the generating faulty scripts problem with `moviepy`? I am using `ffmpeg_extract_subclip`

**Comment by wwdok** [comment]
Hi @rlleshi , afterwards i used `subclip` instead of `ffmpeg_extract_subclip`, the script is :
```
from moviepy.editor import VideoFileClip
import os
video_folder = "/media/weidawang/DATA/FFOutput/test_folder"
outputs_folder = video_folder + "/output_videos2/"

if not os.path.exists(outputs_folder):
    os.makedirs(outputs_folder)

def SplitVideoWithFixedNumberOfClips():
    for video_name in os.listdir(video_folder):
        video_path = os.path.join(video_folder, video_name)
        if os.path.isdir(video_path):  # exclude outputs_folder
            continue
        print(f"Processing {video_path}")

        with VideoFileClip(video_path) as video:
            duration = video.duration
            print(duration)
            interval = duration // 6
            print(interval)
            for i in range(5):
                starttime = int(interval * i)
                endtime = int(interval * i + 5)
                new = video.subclip(starttime, endtime)
                new.write_videofile(outputs_folder + video_name.split('.')[0] + "_" + str(i) + ".mp4", audio_codec='aac')

SplitVideoWithFixedNumberOfClips()
```
Although the videos outputed by this script won't make training freeze anymore, the width and height of some videos are changed...

**Comment by alejopaullier96** [comment]
@wwdok I tried your approach but faced issues with `moviepy`, I get the error `TypeError: must be real number, not NoneType`, could you provide your `moviepy` version and possibly `ffmpeg`?
