### ISSUE TITLE
TSN temporal stream

### ISSUE THREAD

**Issue by MichelMajdalani** [open-mmlab/mmaction2#565]
Hello
I am trying to create a temporal stream for TSN using optical flow. Given the configuration below, I get the following error: `RuntimeError: Given groups=1, weight of size [64, 3, 7, 7], expected input[3, 10, 224, 224] to have 3 channels, but got 10 channels instead`.
The number of channels in the input after going through the training pipeline doesn't match the expected input of the first convolutional layer of the Resnet backbone model.
If I attempt to change the number of channels the backbone model expects, it leads to a failure when the model attempts to load the weights from torchvision.
What can be done so that I can train a TSN temporal stream?

You can find my Python configuration file as a text file here [tsn_r50_1x1x3_2e_ucf101_flow.py.txt](https://github.com/open-mmlab/mmaction2/files/5874657/tsn_r50_1x1x3_2e_ucf101_flow.py.txt)

**Comment by kennymckormick** [comment]
You should set `in_channels=10`. The function of loading ImageNet pretrained weight to a 10-channel input ResNet seems to be broken after a PR, we will fix it soon. You can also try using Kinetics-Pretrained flow models for initialization, it should work.

**Comment by innerlee** [comment]
Ohh, can we test this? @kennymckormick

**Comment by kennymckormick** [comment]
> Ohh, can we test this? @kennymckormick

Will be added in the next week. It's weird that there are no test cases for ResNet 😓 .

**Comment by MichelMajdalani** [comment]
Thank you @kennymckormick @innerlee!

There is still a related problem when trying to train a temporal stream. Some flow files cannot be found.
The problem comes from the fact that the number of flow files is 1 less than the number of RGB images (since the flow is calculated between two consecutive images). The annotation files give the number of total frames equal to the number of RGB images. Therefore, it is possible to try and get a flow file that doesn't exist. 

The fix I did that worked for me is in the image below. It modifies the `load_annoations` function in the `RawframeDataset` (`mmaction/datasets/rawframe_dataset.py/RawframeDataset/load_annoatations`). I just decrement the total frames by 1 if the modality is Flow.

<img width="331" alt="flow_modality" src="https://user-images.githubusercontent.com/43356588/106775679-53b85a80-6611-11eb-873d-457298b110f1.PNG">

**Comment by AlexanderAsfar** [comment]
Hello, I have the same issue but for i3d. I saw that you made changes to the resnet.py files. Could you please apply the necessary changes for the resnet3d files as well.

**Comment by kennymckormick** [comment]
> Hello, I have the same issue but for i3d. I saw that you made changes to the resnet.py files. Could you please apply the necessary changes for the resnet3d files as well.

Can you paste the error log here? Seems we have already checked the parameter shapes in ResNet3d

**Comment by AlexanderAsfar** [comment]
RuntimeError: Given groups=1, weight of size [64, 3, 5, 7, 7], expected input[8, 2, 5, 224, 224] to have 3 channels, but got 2 channels instead

**Comment by kennymckormick** [comment]
> RuntimeError: Given groups=1, weight of size [64, 3, 5, 7, 7], expected input[8, 2, 5, 224, 224] to have 3 channels, but got 2 channels instead

You need to set `in_channels=2` in the backbone config

**Comment by AlexanderAsfar** [comment]
I got this error changing in_channels to 2 in resnet3d.py
RuntimeError: size mismatch, m1: [8 x 2048], m2: [2 x 101] at /opt/conda/conda-bld/pytorch_1591914880026/work/aten/src/THC/generic/THCTensorMathBlas.cu:283

**Comment by kennymckormick** [comment]
You need to set `in_channels=2` for backbone instead of cls_head.

**Comment by AlexanderAsfar** [comment]
It worked! Thank you.
