### ISSUE TITLE
How to reproduce the csv_mean_100 features?

### ISSUE THREAD

**Issue by cecilia930426** [open-mmlab/mmaction2#568]
For convenience of training and testing, we rescale the feature length of all videos to same length 100, and we provide the rescaled feature at here Google Cloud or Baidu Yun. 

I want to ask how to rescale the feature-length to 100. Thank you for your help.

**Comment by kennymckormick** [comment]
Please refer to the data preprocessing docs of ActivityNet. We demonstrate how to rescale the feature length there.
