### ISSUE TITLE
The TSN result on what you present is different from your logs

### ISSUE THREAD

**Issue by cecilia930426** [open-mmlab/mmaction2#570]
<img width="362" alt="TSN" src="https://user-images.githubusercontent.com/16661965/105994106-31549900-6075-11eb-81b2-5bdae6820b6e.png">
<img width="814" alt="TSN2" src="https://user-images.githubusercontent.com/16661965/105994107-31ed2f80-6075-11eb-888a-67d9674f46f7.png">
How to get the precision the same as you public?

**Comment by dreamerlin** [comment]
the result in the log is for traning dataset. you should run the `tools/test.py`

**Comment by cecilia930426** [comment]
> the result in the log is for traning dataset. you should run the `tools/test.py`

But what I got is top1 acc 67.25% by inference the first model

**Comment by dreamerlin** [comment]
Could you please share your command and the number and resolution of your Kinetics?

**Comment by dreamerlin** [comment]
> Could you please share your command and the number and resolution of your Kinetics?

Ok, It is for ANet

**Comment by cecilia930426** [comment]
export PYTHONPATH=`pwd`:$PYTHONPATH
CUDA_VISIBLE_DEVICES=0 python tools/test.py configs/recognition/tsn/tsn_r50_320p_1x1x8_50e_activitynet_video_rgb.py modelzoo/tsn_r50_320p_1x1x8_50e_activitynet_video_rgb.pth --eval top_k_accuracy mean_class_accuracy

On activitynet

**Comment by dreamerlin** [comment]
https://github.com/open-mmlab/mmaction2/blob/master/configs/recognition/tsn/tsn_r50_320p_1x1x8_50e_activitynet_video_rgb.py#L9, it seems that it should be `video` not `clip`, right ? @kennymckormick

**Comment by cecilia930426** [comment]
What do you mean? How to get the same results?

**Comment by dreamerlin** [comment]
Try to convert `ann_file_test = 'data/ActivityNet/anet_val_clip.txt'` to `ann_file_test = 'data/ActivityNet/anet_video_clip.txt'` [this line](https://github.com/open-mmlab/mmaction2/blob/master/configs/recognition/tsn/tsn_r50_320p_1x1x8_50e_activitynet_video_rgb.py#L9)

**Comment by cecilia930426** [comment]
What I used is anet_video_clip.txt But there are still some differences.

**Comment by kennymckormick** [comment]
> https://github.com/open-mmlab/mmaction2/blob/master/configs/recognition/tsn/tsn_r50_320p_1x1x8_50e_activitynet_video_rgb.py#L9, it seems that it should be `video` not `clip`, right ? @kennymckormick

Right

**Comment by kennymckormick** [comment]
> What I used is anet_video_clip.txt But there are still some differences.

Plz share ur data pipeline for testing.

**Comment by cecilia930426** [comment]
`test_pipeline = [
    dict(
        type='SampleFrames',
        clip_len=1,
        frame_interval=1,
        num_clips=25,
        test_mode=True),
    dict(type='FrameSelector'),
    dict(type='Resize', scale=(-1, 256)),
    dict(type='ThreeCrop', crop_size=256),
    dict(type='Flip', flip_ratio=0),
    dict(type='Normalize', **img_norm_cfg),
    dict(type='FormatShape', input_format='NCHW'),
    dict(type='Collect', keys=['imgs', 'label'], meta_keys=[]),
    dict(type='ToTensor', keys=['imgs'])
]`
I did not change sth

**Comment by cecilia930426** [comment]
Is there sth wrong with the setting?

**Comment by kennymckormick** [comment]
> Is there sth wrong with the setting?

Seems I cannot find anything wrong. I will rerun the testing and share u the log and our testing list, maybe that will help.

**Comment by cecilia930426** [comment]
> > Is there sth wrong with the setting?
> 
> Seems I cannot find anything wrong. I will rerun the testing and share u the log and our testing list, maybe that will help.

That's nice. Thank you.

**Comment by cecilia930426** [comment]
> > Is there sth wrong with the setting?
> 
> Seems I cannot find anything wrong. I will rerun the testing and share u the log and our testing list, maybe that will help.

Hello, any update about it?

**Comment by kennymckormick** [comment]
> > > Is there sth wrong with the setting?
> > 
> > 
> > Seems I cannot find anything wrong. I will rerun the testing and share u the log and our testing list, maybe that will help.
> 
> Hello, any update about it?

Sorry, seems there is some mistake in the performance numbers: we test the model on `anet_val_video.txt` instead of `anet_val_clip.txt`. The performance on `anet_val_clip.txt` should be around 71.99(Top-1), we will fix it in #589 .

**Comment by kennymckormick** [comment]
You can get our testing list here: https://transfer.sh/lxLjN/anet_val_clip.txt
