### ISSUE TITLE
关于demo/webcam_demo.py对摄像头实时预测时cpu和Gpu使用率的问题

### ISSUE THREAD

**Issue by Syorst** [open-mmlab/mmaction2#575]
你好，在服务器上使用demo/webcam_demo.py进行实时预测时，CPU占用率很高，GPU占用很低，有没有可以调节CPU占用率的参数，降低CPU占用数量，而不是全部占用，还是我的配置文件设置有问题？期待回复，多谢！
命令：python demo/webcam_demo.py custom_data/configs/tsm/tsm_r50_video_1x1x8_50e_kinetics400_rgb.py   custom_data/tsm/epoch_60.pth   demo/label_map1.txt   --average-size 1   --threshold 0.2  
CPU：48*Intel(R) Xeon(R) CPU E5-2650 v4 @ 2.20GHz  GPU：Tesla P100
程序启动前CPU情况：
![图片](https://user-images.githubusercontent.com/59610834/106127339-6eb24700-6199-11eb-894f-7f2182487ead.png)
程序启动后CPU使用情况：
![图片](https://user-images.githubusercontent.com/59610834/106127481-8d184280-6199-11eb-8c58-51690394b67a.png)
程序启动后GPU情况：
![图片](https://user-images.githubusercontent.com/59610834/106127589-a3be9980-6199-11eb-9dd2-73f5111b533b.png)

**Comment by innerlee** [comment]
add sleep 0.01s to the loop

**Comment by Syorst** [comment]
> add sleep 0.01s to the loop

 pw.join()这里修改为：
 while True:
     sleep(0.01)
     if not pw.is_alive():
             exit(0)
对么？

**Comment by innerlee** [comment]
Yes

**Comment by innerlee** [comment]
There are two `while True` loops, I'm not sure which one is better

**Comment by irvingzhang0512** [comment]
我这英文不太行，就用中文回答一下，之后等大佬补充英文标准答案。
可以在 `show_results` 和 `inference` 这两个函数里的 `While True` 中添加 sleep：
1）在 show_results 里添加会降低CPU占用（降低从摄像头中读取数据的频率，如果sleep数值大，可能导致展示的结果一卡一卡的），CPU主要用在从从摄像头读取图片。
2）如果在`inference`里添加sleep，会降低CPU和GPU占用，当于进行行为识别的频率降低，CPU主要用在数据预处理还是啥，这个没测过。
个人建议在后者添加可能好一点。

**Comment by innerlee** [comment]
You can add to both. For example, add `sleep(0.05)` to `show_results` and `sleep(1)` to `inference`

**Comment by innerlee** [comment]
@dreamerlin we may add a limiter such that the drawing <= 20fps, and inference <= 4fps

**Comment by irvingzhang0512** [comment]
> @dreamerlin we may add a limiter such that the drawing <= 20fps, and inference <= 4fps

Or add two params `max_inference_fps/max_reading_fps` in argparser

**Comment by dreamerlin** [comment]
Got busy for some design about the whole OpenMMLab projects. @kennymckormick Could you please help for this, since we also plan to provide a more comprehensive pretrained models for all datasets labels.
