### ISSUE TITLE
How can I choose one type of data in rawframes folder when training or test?

### ISSUE THREAD

**Issue by Wnaner** [open-mmlab/mmaction2#577]
I got the follow error,when I test a video,it request img_00166.jpg,but the num of img is 163.But in the the rawframes folder,there are both img and flow data. 
FileNotFoundError: [Errno 2] No such file or directory: '/home/xx/project/activity_detection/mmaction2/data/ucf101/rawframes/ApplyEyeMakeup/v_ApplyEyeMakeup_g01_c01/img_00166.jpg'

**Comment by SuX97** [comment]
@Wnaner :
Please provide the cmd lines and config file that you used for bug reproduction, together with the script you used to generate the file list.

I guess this issue is related to how to train with rgb and flow, maybe @kennymckormick has some ideas.

**Comment by kennymckormick** [comment]
Seems u didn't generate the file list properly, how many rgb / flow images are in the directory `/home/xx/project/activity_detection/mmaction2/data/ucf101/rawframes/ApplyEyeMakeup/v_ApplyEyeMakeup_g01_c01/`? Besides, check ur filelist and find what is the `num_frame` of this video.
