### ISSUE TITLE
Total number of videos found:  0

### ISSUE THREAD

**Issue by mytk2012** [open-mmlab/mmaction2#584]
when i run command：
**python build_rawframes.py /mnt/mmaction2-master/data/sthv1/train/ /mnt/mmaction2-master/data/sthv1/optical/ --task rgb --level 1  --ext webm**
it **reply**s：
Extension of videos:  webm
Total number of videos found:  0

I have checked my path，it should be ok

when i run denseflow /mnt/mmaction2-master/data/ab24.mp4 -b=20 -a=tvl1 -s=1 -v
**it was normal**

It seems my opencv and denseflow are installed correctly.

**Comment by innerlee** [comment]
What if the input to denseflow is webm?

**Comment by mytk2012** [comment]
sorry，it should be mp4，thanks
