### ISSUE TITLE
Error KeyError: 'conv1.weight' resnet

### ISSUE THREAD

**Issue by cecilia930426** [open-mmlab/mmaction2#588]
When I tried to implement tsn model on activitynet, I got one error KeyError: 'conv1.weight'.
 mmaction/models/backbones/resnet.py
Line 435-437 
        if conv.weight.data.shape == state_dict_tv[weight_tv_name].shape:
            conv.weight.data.copy_(state_dict_tv[weight_tv_name])
            loaded_param_names.append(weight_tv_name)

Could you please help me to solve this problem?

**Comment by innerlee** [comment]
Is this pull request related？https://github.com/open-mmlab/mmaction2/pull/582

Is the latest version used?

**Comment by innerlee** [comment]
@kennymckormick maybe there are some convs that do not have weight?

**Comment by cecilia930426** [comment]
> @kennymckormick maybe there are some convs that do not have weight?

I did not change anything about the pre-trained model. Why there are so many convs that do not have weights?

**Comment by cecilia930426** [comment]
@kennymckormick Still have this problem. It said got an unexpected keyword argument 'load_from'

**Comment by kennymckormick** [comment]
> @kennymckormick Still have this problem. It said got an unexpected keyword argument 'load_from'

Please check the change to config file in PR #589 , you need to write `load_from=blahblah` outside the backbone config or model config.
