### ISSUE TITLE
How to produce the same csv_mean_100 features as you provide?

### ISSUE THREAD

**Issue by cecilia930426** [open-mmlab/mmaction2#593]
![WX20210203-180848](https://user-images.githubusercontent.com/16661965/106821389-0b1d9300-664b-11eb-9b67-17714f7d0e5e.png)
The model I used is tsn_r50_320p_1x1x8_50e_activitynet_clip_rgb on Activitynet 1.3. The left side is the csv_mean_100 features, and the right side is the reproduced features followed the same as your document. The distribution of the two is not the same. So I have a question, how to generate the same as yours. Since the features you provided is very good, I want to reproduce similar results as you did (at least the same distribution).

**Comment by cecilia930426** [comment]
The video I used is v_1Ao43T5yRjl

**Comment by cecilia930426** [comment]
![WX20210203-183950](https://user-images.githubusercontent.com/16661965/106823805-8aad6100-664f-11eb-94f3-5390bd08b366.png)
Another video v_1XQUDJhMcj8

**Comment by kennymckormick** [comment]
They are not the same, since csv_mean_100 is released by CUHK (for ActivityNet challenge 17), generated by a different model (which we don't have). You can not produce `csv_mean_100`

**Comment by cecilia930426** [comment]
> They are not the same, since csv_mean_100 is released by CUHK (for ActivityNet challenge 17), generated by a different model (which we don't have). You can not produce `csv_mean_100`

Could you please re-run the model, follow your instructions to see whether we get the same result as we did? Thanks a lot.

**Comment by cecilia930426** [comment]
https://drive.google.com/file/d/1xNgQEA4Xd6l6KXNKR21cMW2XsvnklMQu/view?usp=sharing
https://drive.google.com/file/d/1EhQTerT9THY2eiqePmvu4lTI7VF3MaOi/view?usp=sharing
They are the features we get used the model tsn_r50_320p_1x1x8_50e_activitynet_clip_rgb.

<img width="826" alt="WX20210205-175643@2x" src="https://user-images.githubusercontent.com/16661965/107097687-87df7700-67db-11eb-90d6-b45f7fa6ebf2.png">

video id v_1XQUDJhMcj8   v_1Ao43T5yRjl

**Comment by cecilia930426** [comment]
Only for these two videos. I want to make sure that what I did is the same way you did. Thanks a lot.

**Comment by cecilia930426** [comment]
> They are not the same, since csv_mean_100 is released by CUHK (for ActivityNet challenge 17), generated by a different model (which we don't have). You can not produce `csv_mean_100`

Any update about it? Thanks a lot.

**Comment by kennymckormick** [comment]
> > They are not the same, since csv_mean_100 is released by CUHK (for ActivityNet challenge 17), generated by a different model (which we don't have). You can not produce `csv_mean_100`
> 
> Thank you for your response. I understand that 'csv_mean_100' (or cuhk features that are publicly available) is different from what I can get with your model and your pipeline. We also note that you mention that you get better results than the publicly available cuhk features. Our objective is actually to reproduce the feature sets that you get using the model that you have trained, i.e. the feature sets that provide better results on ActivityNet. On that note, we followed the procedure mentioned in ‘Option 2: Extract ActivityNet feature using MMAction2’ in https://github.com/open-mmlab/mmaction2/blob/master/tools/data/activitynet/README.md , and we use the ‘tsn_r50_320p_1x1x8_50e_activitynet_clip_rgb’ that your provided.
> 
> <img alt="WX20210205-175643@2x" width="826" src="https://user-images.githubusercontent.com/16661965/107097687-87df7700-67db-11eb-90d6-b45f7fa6ebf2.png">
> 
> The feature set we get for the following two videos, v_1XQUDJhMcj8 and v_1Ao43T5yRjl are in these links: [v_1Ao43T5yRjl](https://drive.google.com/file/d/1xNgQEA4Xd6l6KXNKR21cMW2XsvnklMQu/view?usp=sharing) [v_1XQUDJhMcj8](https://drive.google.com/file/d/1EhQTerT9THY2eiqePmvu4lTI7VF3MaOi/view?usp=sharing) Can you please verify on your end if you get the same feature set or not? If something is amiss from my end, please let me know.

Sorry, I have no access to open these two files, can you share it again?

**Comment by cecilia930426** [comment]
> > > They are not the same, since csv_mean_100 is released by CUHK (for ActivityNet challenge 17), generated by a different model (which we don't have). You can not produce `csv_mean_100`
> > 
> > 
> > Thank you for your response. I understand that 'csv_mean_100' (or cuhk features that are publicly available) is different from what I can get with your model and your pipeline. We also note that you mention that you get better results than the publicly available cuhk features. Our objective is actually to reproduce the feature sets that you get using the model that you have trained, i.e. the feature sets that provide better results on ActivityNet. On that note, we followed the procedure mentioned in ‘Option 2: Extract ActivityNet feature using MMAction2’ in https://github.com/open-mmlab/mmaction2/blob/master/tools/data/activitynet/README.md , and we use the ‘tsn_r50_320p_1x1x8_50e_activitynet_clip_rgb’ that your provided.
> > <img alt="WX20210205-175643@2x" width="826" src="https://user-images.githubusercontent.com/16661965/107097687-87df7700-67db-11eb-90d6-b45f7fa6ebf2.png">
> > The feature set we get for the following two videos, v_1XQUDJhMcj8 and v_1Ao43T5yRjl are in these links: [v_1Ao43T5yRjl](https://drive.google.com/file/d/1xNgQEA4Xd6l6KXNKR21cMW2XsvnklMQu/view?usp=sharing) [v_1XQUDJhMcj8](https://drive.google.com/file/d/1EhQTerT9THY2eiqePmvu4lTI7VF3MaOi/view?usp=sharing) Can you please verify on your end if you get the same feature set or not? If something is amiss from my end, please let me know.
> 
> Sorry, I have no access to open these two files, can you share it again?

Sorry for that. Thanks a lot.
[v_1Ao43T5yRjl](https://drive.google.com/file/d/1xNgQEA4Xd6l6KXNKR21cMW2XsvnklMQu/view?usp=sharing)  [v_1XQUDJhMcj8](https://drive.google.com/file/d/1EhQTerT9THY2eiqePmvu4lTI7VF3MaOi/view?usp=sharing)

**Comment by kennymckormick** [comment]
I have compared them with our features, they are not exactly the same, but the trend(like the signal) and magnitude for most feature values are the same. Maybe there are still some misalignments in preprocessing between urs and the pipeline on the README. Besides, what's the localization performance of ur feature?

**Comment by cecilia930426** [comment]
> I have compared them with our features, they are not exactly the same, but the trend(like the signal) and magnitude for most feature values are the same. Maybe there are still some misalignments in preprocessing between urs and the pipeline on the README. Besides, what's the localization performance of ur feature?

Got the performance lower than csv_mean_100. Did you use the same model? Did you do the same preprocessing as your pipeline does? I really want to fix these differences. Thank you.

**Comment by dreamerlin** [comment]
Any updates? @cecilia930426
