### ISSUE TITLE
About default value of `save_best` in EvalHook

### ISSUE THREAD

**Issue by irvingzhang0512** [open-mmlab/mmaction2#599]
By default `save_best=None`, which disables saving best eval ckpt.

I think saving best ckpt is a basic function during training. It doesn't require a lot of resources and should be enabled by default.

It could be done by either set `save_best='auto'` or add `evalution=dict(save_best='xxx')` in all configs. I prefer the latter.

**Comment by irvingzhang0512** [comment]
I could create a pr to solve this. Waht do you think of this modification? @dreamerlin @innerlee

**Comment by dreamerlin** [comment]
`save_best='auto'` may be better, what do you think? @innerlee

**Comment by Bo396543018** [comment]
> `save_best='auto'` may be better, what do you think? @innerlee

Can user choose number of top best checkpoints to save？

**Comment by irvingzhang0512** [comment]
> > `save_best='auto'` may be better, what do you think? @innerlee
> 
> Can user choose number of top best checkpoints to save？

No. But you can save last 5 epochs by `checkpoint_config = dict(interval=1, max_keep_ckpts =5)`
