### ISSUE TITLE
Spatio-temporal region proposals

### ISSUE THREAD

**Issue by VJatla** [open-mmlab/mmaction2#604]
First of all I would like to thank mmaction2 for bringing all SOTA activity recognition algorithms together. Because of this library I was able to propose my work on a custom dataset.

In the suggestions, during my proposal, I was asked to explore **Spatio-temporal** proposals. I see that there are two methods available for this in mmaction2. 

The question I have is regarding the "region proposals". I need to implement it for my custom dataset so I want to make sure I got this right,
1. The proposal boxes + time stamps are from FAIR's Long-term Feature Banks
2. slowfast/slowonly networks (trained as recognizer on the AVA dataset) are used to predict the activity in those proposals.

**Question:** Is the slowfast/slowonly networks retrained on the proposals from FAIR's long-term feature bank?

Please let me know if I don't make any sense. I will try to formulate my question more carefully.

**Comment by kennymckormick** [comment]
Yes, the slowfast/slowonly networks are retrained on proposals from FAIR's long-term feature bank. So to work on a custom dataset, you need to first extract human proposals with a detector, then retrain the models with the extracted proposals.

**Comment by VJatla** [comment]
Thanks for this confirmation. I really appreciate the reply.

**Comment by ImSau** [comment]
@VJatla are you working on your own data for custom classes??
if so, how you are doing FAIR's long-term feature bank?

**Comment by VJatla** [comment]
Hello @ImSau . I am trying to do the spatiotemporal detection for custom classes. But I figured out it requires me to generate region proposals as FAIR recommended. So I moved on doing only trimmed video classification. Sorry for the late reply. Was away for some time.

**Comment by ImSau** [comment]
@kennymckormick 
can we quote like this....

**The Proposal file consisting Groundtruth of the training data in a dictionary format.**
like this : 
{ (< video_id >,  < timestamp > ) : [ < BBox > ] }
If you unpickle that proposal file.

**Comment by kennymckormick** [comment]
> @kennymckormick
> can we quote like this....
> 
> **The Proposal file consisting Groundtruth of the training data in a dictionary format.**
> like this :
> { (< video_id >, < timestamp > ) : [ < BBox > ] }
> If you unpickle that proposal file.
> 
> and one more thing :
> **Is the _tools/train.py_ & provided config file at _/detection/ava/slofast<.....>.py_ is compatible for transfer learning for traing on custom data like ava on custom classes (which are not there in ava) ?**

Yes, but you may need to do some modifications to the AVADataset to load new data.
