### ISSUE TITLE
Default value of start index wrong in 'tsn_r50_1x1x3_75e_ucf101_rgb.py'.

### ISSUE THREAD

**Issue by Hanqer** [open-mmlab/mmaction2#609]
**Describe the bug**
In 'tsn_r50_1x1x3_75e_ucf101_rgb.py', the dataset take the default value '1' of start_index. But in tools/data/ucf101, the scripts preparing data (extract frames) starts with 0. This makes an error in training TSN with UCF101 dataset when sampling to the last frame. 

**Reproduction**

Following the data preparation scripts to download and extract frames. Then run the command:
./tools/dist_train.sh configs/recognition/tsn/tsn_r50_1x1x3_75e_ucf101_rgb.py 8

2. Did you make any modifications on the code or config? Did you understand what you have modified?
No.

3. What dataset did you use?
UCF101

**Bug fix**

By adding start_index=0 in data dict of the config,  this error can be fixed.

**Comment by innerlee** [comment]
The starting index can be 0 or 1, depending on how the frames are extracted. One need to adjust the config based on her/his dataset
