### ISSUE TITLE
"workers_per_gpu" settings do not work

### ISSUE THREAD

**Issue by geek12138** [open-mmlab/mmaction2#61]
My CPU is AMD ThreadRipper 2990wx and GPU is Titan RTX.

No matter how much I set workers_per_gpu to, the code only uses one thread of the cpu, and cannot use all the 64 threads of the cpu.

Can anyone help me,Thanks!!!

**Comment by innerlee** [comment]
Could you provide more info?

* Which config file are used?
* Does workers_per_gpu works for codebases other than mmaction2?
* There is a possibility that the multi-threading lib does not support AMD, but lets rule out other options first.

**Comment by geek12138** [comment]
> Could you provide more info?
> 
> * Which config file are used?
> * Does workers_per_gpu works for codebases other than mmaction2?
> * There is a possibility that the multi-threading lib does not support AMD, but lets rule out other options first.

> * Which config file are used?
tsn_r50_1x1x3_80e_ucf101_rgb.py

> * Does workers_per_gpu works for codebases other than mmaction2?
I am running the training sample code of tsn on mmaction2. 

python tools/train.py configs/recognition/tsn/tsn_r50_1x1x3_80e_ucf101_rgb.py \
    --work-dir work_dirs/tsn_r50_1x1x3_80e_ucf101_rgb \
    --validate --seed 0 --deterministic

Thank you.

**Comment by dreamerlin** [comment]
![num_worker=4](https://user-images.githubusercontent.com/33949370/88642918-a6a9d600-d0f3-11ea-940e-183e092eaaad.png)
Here is our result with
```bash
python tools/train.py configs/recognition/tsn/tsn_r50_1x1x3_80e_ucf101_rgb.py --work-dir work_dirs/tsn_r50_1x1x3_80e_ucf101_rgb --validate --seed 0 --deterministic
```
The environment is: Intel(R) Xeon(R) Silver 4114 CPU @ 2.20GHz, GTX 1080Ti GPU. 
The PID `168761-168764` are corresponding to the `workers_per_gpu=4`. 
There is a possibility that the multi-threading lib does not support AMD. I think you can check whether `workers_per_gpu` works for other codebases.

**Comment by geek12138** [comment]
> ![num_worker=4](https://user-images.githubusercontent.com/33949370/88642918-a6a9d600-d0f3-11ea-940e-183e092eaaad.png)
> Here is our result with
> 
> ```shell
> python tools/train.py configs/recognition/tsn/tsn_r50_1x1x3_80e_ucf101_rgb.py --work-dir work_dirs/tsn_r50_1x1x3_80e_ucf101_rgb --validate --seed 0 --deterministic
> ```
> 
> The environment is: Intel(R) Xeon(R) Silver 4114 CPU @ 2.20GHz, GTX 1080Ti GPU.
> The PID `168761-168764` are corresponding to the `workers_per_gpu=4`.
> There is a possibility that the multi-threading lib does not support AMD. I think you can check whether `workers_per_gpu` works for other codebases.

Thank you, I tested that pytorch's multithreading is invalid for 2990wx.

**Comment by dreamerlin** [comment]
It is grad to see that we find the root of the problem and i will close this issue.
