### ISSUE TITLE
Why Video DataLoader consumes much more GPU memory than raw frame loader?

### ISSUE THREAD

**Issue by xieshuqin** [open-mmlab/mmaction2#613]
Hi,

I noticed the video loader config uses much higher GPU memory than raw frame configs. 

Here is an example. For slow only model, the config `slowonly_r50_video_4x16x1_256e_kinetics400_rgb` consumes 8472M memory while `slowonly_r50_4x16x1_256e_kinetics400_rgb` only takes ~3G. Is there any particular reason for this?

And I also have a question regarding the dense video. I don't see any config that uses the dense video. Is there any reason?

**Comment by innerlee** [comment]
Notice the videos_per_gpu argument.

**Comment by xieshuqin** [comment]
Thanks
