### ISSUE TITLE
Inference after converting from PyTorch to Onnx to TensorRT

### ISSUE THREAD

**Issue by kartik1395** [open-mmlab/mmaction2#614]
I've converted the PyTorch TSN model to Onnx and I'm planning to convert it to TensorRT.  I wanted to know how can I make a prediction for a video input using the TensorRT model. Do I need to make any changes in the `Prediction.py` file ?

**Comment by innerlee** [comment]
Sorry which `Prediction.py`?

**Comment by kartik1395** [comment]
> Sorry which `Prediction.py`?

`tools/prediction.py`

**Comment by kartik1395** [comment]
> > Sorry which `Prediction.py`?
> 
> `tools/prediction.py`

Sorry I used https://github.com/open-mmlab/mmaction2/blob/master/docs/getting_started.md#high-level-apis-for-testing-a-video-and-rawframes to make my own `prediction.py`.

Nonetheless, could you guide on how to make predictions using TensorRT using similar Hight Level API ?

**Comment by kartik1395** [comment]
> Sorry which `Prediction.py`?

Sorry I used https://github.com/open-mmlab/mmaction2/blob/master/docs/getting_started.md#high-level-apis-for-testing-a-video-and-rawframes to make my own `prediction.py.`

Nonetheless, could you guide on how to make predictions using TensorRT using similar Hight Level API ?

**Comment by innerlee** [comment]
Reference code: https://github.com/open-mmlab/mmaction2/blob/master/tools/pytorch2onnx.py#L77-L96

**Comment by kartik1395** [comment]
I see this is for a single image input if I'm not mistaken. How can it be replicated for a video file ? Sorry I'm a bit confused.

**Comment by innerlee** [comment]
Ignore the variable name `one_img`, it was copied from elsewhere. Input shape is determined by `input_shape`.

**Comment by kartik1395** [comment]
I understand. I've been using the high level API for inference that passes video file name as a parameter for making a prediction that prepares data using `inference.py` file https://github.com/open-mmlab/mmaction2/blob/master/mmaction/apis/inference.py. 

Want to know how I can similarly pass the whole video through the TensorRT model.

**Comment by innerlee** [comment]
@dreamerlin maybe we can add support for this in inference.py? Like, adding a `inference_recognizer_onnx()` function?

**Comment by kartik1395** [comment]
> @dreamerlin maybe we can add support for this in inference.py? Like, adding a `inference_recognizer_trt()` function?
> 
> edit: trt

That would be really helpful, thank you!

**Comment by irvingzhang0512** [comment]
I plan to implement this in two months along with `inference_recoginizer_onnx`. May also implement a tool to test inference speed.

**Comment by dreamerlin** [comment]
Ref: https://github.com/open-mmlab/mmclassification/pull/153
