### ISSUE TITLE
why not use SyncBN and Conv3d together

### ISSUE THREAD

**Issue by baibaidj** [open-mmlab/mmaction2#616]
I noticed that SyncBN was used for all Recognizer2Ds but not for Recognizer3Ds. BN3d was used for the latter, instead. 
I was wondering why that is the case.

I've tried to train a 3D segmentor for medical imaging using mmseg, where I used SyncBN for norm_cfg. During training, everything looks fine either for training loss or for evaluation metrics. But after training when I run testing using single GPU, the prediction results are wrongful and not as expected.  BN3d works just fine for my 3D segmentor, so I believe that the issue lies most likely in the SyncBN. 

Thank you.

**Comment by innerlee** [comment]
> SyncBN was used for all Recognizer2Ds

I don't think so?

**Comment by baibaidj** [comment]
> > SyncBN was used for all Recognizer2Ds
> 
> I don't think so?

Well, maybe not. But my point is that SyncBN works for Conv2d  but not for Conv3d. I guess it is not coincidence that SyncBN was not used for Recognizer3D in this project.

**Comment by kennymckormick** [comment]
> > > SyncBN was used for all Recognizer2Ds
> > 
> > 
> > I don't think so?
> 
> Well, maybe not. But my point is that SyncBN works for Conv2d but not for Conv3d. I guess it is not coincidence that SyncBN was not used for Recognizer3D in this project.

In MMAction2, most configs do not use SyncBN. I have ever tried SyncBN on Recognizer3D, and there is no obvious difference in performance.

**Comment by baibaidj** [comment]
> > > > SyncBN was used for all Recognizer2Ds
> > > 
> > > 
> > > I don't think so?
> > 
> > 
> > Well, maybe not. But my point is that SyncBN works for Conv2d but not for Conv3d. I guess it is not coincidence that SyncBN was not used for Recognizer3D in this project.
> 
> In MMAction2, most configs do not use SyncBN. I have ever tried SyncBN on Recognizer3D, and there is no obvious difference in performance.

Thanks. Then I guess the issue lies in other places.
