### ISSUE TITLE
Results of TSN in modelzoo.

### ISSUE THREAD

**Issue by Hanqer** [open-mmlab/mmaction2#618]
In configs/recognition/tsn/README.md , 'tsn_r50_1x1x8_50e_sthv1_rgb' get 18.55 top-1 acc. But in the provided log file. The highest top-1 acc is 17.59 when evaluating every 5 epochs.

How to get the 18.55 top-1 acc model?

**Comment by innerlee** [comment]
The reported accuracy uses test pipeline, while the val accracy in log uses val pipeline. 
Please compare the two pipelines for their differences.
