### ISSUE TITLE
ValueError: FastRCNN is not registered in LOCALIZERS, RECOGNIZERS or DETECTORS

### ISSUE THREAD

**Issue by wen-flow** [open-mmlab/mmaction2#620]
Hello
when I train AVA dataset find a error
ValueError: FastRCNN is not registered in LOCALIZERS, RECOGNIZERS or DETECTORS
how to solve it 
think you very much

**Comment by irvingzhang0512** [comment]
try to install mmdetection first `pip install mmdet`

**Comment by innerlee** [comment]
Yes we use mmdet for detectors. @wen-flow Which doc did you follow? We will add some notes.

**Comment by congee524** [comment]
We need a more conspicuous way to remind users to install `mmdet` when working on spatiotemporal detection tasks.
Where do you think it is more conspicuous for new users? @wen-flow

**Comment by irvingzhang0512** [comment]
Maybe we can add some warnings in `build_detector`, or just raise ImportError here

https://github.com/open-mmlab/mmaction2/blob/e063074944636c4eae0365f50e8e111b7ce086d5/mmaction/models/builder.py#L14

**Comment by congee524** [comment]
> Maybe we can add some warnings in `build_detector`, or just raise ImportError here
> 
> https://github.com/open-mmlab/mmaction2/blob/e063074944636c4eae0365f50e8e111b7ce086d5/mmaction/models/builder.py#L14

The program doesn't enter `build_detector` unless it finds that the model name has been registered.
https://github.com/open-mmlab/mmaction2/blob/e063074944636c4eae0365f50e8e111b7ce086d5/mmaction/models/builder.py#L67

**Comment by irvingzhang0512** [comment]
> The program doesn't enter `build_detector` unless it finds that the model name has been registered.
> https://github.com/open-mmlab/mmaction2/blob/e063074944636c4eae0365f50e8e111b7ce086d5/mmaction/models/builder.py#L67

Thanks for your reply. On one hand, we should improve our install doc. On the other hand, useful error msg should be raised. I think current error msg `ValueError: FastRCNN is not registered in LOCALIZERS, RECOGNIZERS or DETECTORS` is not helpful. Maybe mmdet not installed error or import error should be raised, either in the above `build_model`, or somewhere else.

**Comment by wen-flow** [comment]
> try to install mmdetection first `pip install mmdet`

Thank you for your answer, I have solved this problem 
I think it can be raise a import error to make it  more conspicuous for newcomers
