### ISSUE TITLE
RuntimeError: CUDA error: invalid device function

### ISSUE THREAD

**Issue by wen-flow** [open-mmlab/mmaction2#621]
```bash
/home/wjc/anaconda3/envs/mmaction/lib/python3.7/site-packages/mmdet/models/builder.py:72: UserWarning: train_cfg and test_cfg is deprecated, please specify them in model
  'please specify them in model', UserWarning)
2021-02-20 22:41:52,654 - mmaction - INFO - 184378 out of 184378 frames are valid.
2021-02-20 22:41:54,006 - mmaction - INFO - load checkpoint from https://download.openmmlab.com/mmaction/recognition/slowonly/omni/slowonly_r101_omni_8x8x1_kinetics400_rgb_20200926-b5dbb701.pth
2021-02-20 22:41:54,195 - mmaction - WARNING - The model and loaded state dict do not match exactly

unexpected key in source state_dict: cls_head.fc_cls.weight, cls_head.fc_cls.bias

missing keys in source state_dict: roi_head.bbox_head.fc_cls.weight, roi_head.bbox_head.fc_cls.bias

2021-02-20 22:41:54,196 - mmaction - INFO - Start running, host: wjc@wjc-System-Product-Name, work_dir: /home/wjc/Documents/liuwenlong/mmaction2/work_dirs/ava/slowonly_omnisource_pretrained_r101_8x8x1_20e_ava_rgb
2021-02-20 22:41:54,196 - mmaction - INFO - workflow: [('train', 1)], max: 20 epochs
Traceback (most recent call last):
  File "tools/train.py", line 178, in <module>
    main()
  File "tools/train.py", line 174, in main
    meta=meta)
  File "/home/wjc/Documents/liuwenlong/mmaction2/mmaction/apis/train.py", line 156, in train_model
    runner.run(data_loaders, cfg.workflow, cfg.total_epochs, **runner_kwargs)
  File "/home/wjc/anaconda3/envs/mmaction/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 125, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/home/wjc/anaconda3/envs/mmaction/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 50, in train
    self.run_iter(data_batch, train_mode=True)
  File "/home/wjc/anaconda3/envs/mmaction/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 30, in run_iter
    **kwargs)
  File "/home/wjc/anaconda3/envs/mmaction/lib/python3.7/site-packages/mmcv/parallel/data_parallel.py", line 67, in train_step
    return self.module.train_step(*inputs[0], **kwargs[0])
  File "/home/wjc/anaconda3/envs/mmaction/lib/python3.7/site-packages/mmdet/models/detectors/base.py", line 247, in train_step
    losses = self(**data)
  File "/home/wjc/anaconda3/envs/mmaction/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/wjc/anaconda3/envs/mmaction/lib/python3.7/site-packages/mmcv/runner/fp16_utils.py", line 84, in new_func
    return old_func(*args, **kwargs)
  File "/home/wjc/anaconda3/envs/mmaction/lib/python3.7/site-packages/mmdet/models/detectors/base.py", line 181, in forward
    return self.forward_train(img, img_metas, **kwargs)
  File "/home/wjc/anaconda3/envs/mmaction/lib/python3.7/site-packages/mmdet/models/detectors/two_stage.py", line 164, in forward_train
    **kwargs)
  File "/home/wjc/anaconda3/envs/mmaction/lib/python3.7/site-packages/mmdet/models/roi_heads/standard_roi_head.py", line 121, in forward_train
    img_metas)
  File "/home/wjc/anaconda3/envs/mmaction/lib/python3.7/site-packages/mmdet/models/roi_heads/standard_roi_head.py", line 150, in _bbox_forward_train
    bbox_results = self._bbox_forward(x, rois)
  File "/home/wjc/Documents/liuwenlong/mmaction2/mmaction/models/heads/roi_head.py", line 20, in _bbox_forward
    bbox_feat = self.bbox_roi_extractor(x, rois)
  File "/home/wjc/anaconda3/envs/mmaction/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/wjc/Documents/liuwenlong/mmaction2/mmaction/models/roi_extractors/single_straight3d.py", line 100, in forward
    roi_feat = self.roi_layer(frame_feat, rois)
  File "/home/wjc/anaconda3/envs/mmaction/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/wjc/anaconda3/envs/mmaction/lib/python3.7/site-packages/mmcv/ops/roi_align.py", line 212, in forward
    self.sampling_ratio, self.pool_mode, self.aligned)
  File "/home/wjc/anaconda3/envs/mmaction/lib/python3.7/site-packages/mmcv/ops/roi_align.py", line 102, in forward
    aligned=ctx.aligned)
RuntimeError: CUDA error: invalid device function
Segmentation fault (core dumped)
```

**Comment by innerlee** [comment]
Looks like an mmcv and mmdet issue. cc. @ycxioooong

@wen-flow How is the mmcv packaged installed? Is the mmcv-full installed?

**Comment by wen-flow** [comment]
I have installed mmcv-full According to install.md

**Comment by kennymckormick** [comment]
Hello, here is a minimal test case for testing the `RoIAlign` in mmcv, u can try if u can run it successfully on ur machine. If not, you may try to reinstall the `mmcv-full` (maybe build it from source). @wen-flow 

```python
import torch
from mmcv.ops import RoIAlign
roi_align = RoIAlign(output_size=(7, 7)).cuda()
feat = torch.randn([1, 3, 24, 24]).cuda()
roi = torch.tensor([[0., 0., 0., 1., 1.]], dtype=torch.float32).cuda()
ret = roi_align(feat, roi)
print(ret.shape)
```

**Comment by wen-flow** [comment]
> Hello, here is a minimal test case for testing the `RoIAlign` in mmcv, u can try if u can run it successfully on ur machine. If not, you may try to reinstall the `mmcv-full` (maybe build it from source). @wen-flow
> 
> ```python
> import torch
> from mmcv.ops import RoIAlign
> roi_align = RoIAlign(output_size=(7, 7)).cuda()
> feat = torch.randn([1, 3, 24, 24]).cuda()
> roi = torch.tensor([[0., 0., 0., 1., 1.]], dtype=torch.float32).cuda()
> ret = roi_align(feat, roi)
> print(ret.shape)
> ```
Thank you for your answer

I run the minimal test case for testing the RoIAlign in mmcv and rebuild the mmcv from source but the error still exist 
I test on ubuntu 18.04 with cuda10.1, pytorch 1.7.1 cudatoolkit 10.1 double 1080ti

**Comment by wen-flow** [comment]
> Hello, here is a minimal test case for testing the `RoIAlign` in mmcv, u can try if u can run it successfully on ur machine. If not, you may try to reinstall the `mmcv-full` (maybe build it from source). @wen-flow
> 
> ```python
> import torch
> from mmcv.ops import RoIAlign
> roi_align = RoIAlign(output_size=(7, 7)).cuda()
> feat = torch.randn([1, 3, 24, 24]).cuda()
> roi = torch.tensor([[0., 0., 0., 1., 1.]], dtype=torch.float32).cuda()
> ret = roi_align(feat, roi)
> print(ret.shape)
> ```

all the environment informations as follow

# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
addict                    2.4.0                    pypi_0    pypi
blas                      1.0                         mkl    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
ca-certificates           2021.1.19            h06a4308_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
certifi                   2020.12.5        py37h06a4308_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
cudatoolkit               10.1.243             h6bb024c_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
cycler                    0.10.0                   pypi_0    pypi
cython                    0.29.21                  pypi_0    pypi
ffmpeg                    1.4                      pypi_0    pypi
freetype                  2.10.4               h5ab3b9f_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
intel-openmp              2020.2                      254    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
joblib                    1.0.1                    pypi_0    pypi
jpeg                      9b                   h024ee3a_2    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
kiwisolver                1.3.1                    pypi_0    pypi
lcms2                     2.11                 h396b838_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
ld_impl_linux-64          2.33.1               h53a641e_7    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
libedit                   3.1.20191231         h14c3975_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
libffi                    3.3                  he6710b0_2    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
libgcc-ng                 9.1.0                hdf63c60_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
libpng                    1.6.37               hbc83047_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
libstdcxx-ng              9.1.0                hdf63c60_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
libtiff                   4.1.0                h2733197_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
libuv                     1.40.0               h7b6447c_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
lmdb                      1.1.1                    pypi_0    pypi
lz4-c                     1.9.3                h2531618_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
matplotlib                3.3.4                    pypi_0    pypi
mkl                       2020.2                      256    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
mkl-service               2.3.0            py37he8ac12f_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
mkl_fft                   1.2.0            py37h23d657b_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
mkl_random                1.1.1            py37h0573a6f_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
mmaction2                 0.11.0                    dev_0    <develop>
mmcv-full                 1.2.7                     dev_0    <develop>
mmdet                     2.9.0                    pypi_0    pypi
mmpycocotools             12.0.3                   pypi_0    pypi
ncurses                   6.2                  he6710b0_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
ninja                     1.10.2           py37hff7bd54_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
numpy                     1.19.2           py37h54aff64_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
numpy-base                1.19.2           py37hfa32c7d_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
olefile                   0.46                     py37_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
opencv-contrib-python     4.5.1.48                 pypi_0    pypi
opencv-python             4.5.1.48                 pypi_0    pypi
openssl                   1.1.1j               h27cfd23_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
pillow                    8.1.0            py37he98fc37_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
pip                       20.3.3           py37h06a4308_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
pyparsing                 2.4.7                    pypi_0    pypi
python                    3.7.9                h7579374_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
python-dateutil           2.8.1                    pypi_0    pypi
pytorch                   1.7.1           py3.7_cuda10.1.243_cudnn7.6.3_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch
pyyaml                    5.4.1                    pypi_0    pypi
readline                  8.1                  h27cfd23_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
scikit-learn              0.24.1                   pypi_0    pypi
scipy                     1.6.1                    pypi_0    pypi
setuptools                52.0.0           py37h06a4308_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
six                       1.15.0           py37h06a4308_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
sqlite                    3.33.0               h62c20be_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
threadpoolctl             2.1.0                    pypi_0    pypi
tk                        8.6.10               hbc83047_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
torchaudio                0.7.2                      py37    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch
torchvision               0.8.2                py37_cu101    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch
typing_extensions         3.7.4.3            pyha847dfd_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
wheel                     0.36.2             pyhd3eb1b0_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
xz                        5.2.5                h7b6447c_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
yapf                      0.30.0                   pypi_0    pypi
zlib                      1.2.11               h7b6447c_3    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
zstd                      1.4.5                h9ceee32_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main

**Comment by kennymckormick** [comment]
> > Hello, here is a minimal test case for testing the `RoIAlign` in mmcv, u can try if u can run it successfully on ur machine. If not, you may try to reinstall the `mmcv-full` (maybe build it from source). @wen-flow
> > ```python
> > import torch
> > from mmcv.ops import RoIAlign
> > roi_align = RoIAlign(output_size=(7, 7)).cuda()
> > feat = torch.randn([1, 3, 24, 24]).cuda()
> > roi = torch.tensor([[0., 0., 0., 1., 1.]], dtype=torch.float32).cuda()
> > ret = roi_align(feat, roi)
> > print(ret.shape)
> > ```
> 
> Thank you for your answer
> 
> I run the minimal test case for testing the RoIAlign in mmcv and rebuild the mmcv from source but the error still exist
> I test on ubuntu 18.04 with cuda10.1, pytorch 1.7.1 cudatoolkit 10.1 double 1080ti

You mean you can successfully run the minimal test?

**Comment by wen-flow** [comment]
> > > Hello, here is a minimal test case for testing the `RoIAlign` in mmcv, u can try if u can run it successfully on ur machine. If not, you may try to reinstall the `mmcv-full` (maybe build it from source). @wen-flow
> > > ```python
> > > import torch
> > > from mmcv.ops import RoIAlign
> > > roi_align = RoIAlign(output_size=(7, 7)).cuda()
> > > feat = torch.randn([1, 3, 24, 24]).cuda()
> > > roi = torch.tensor([[0., 0., 0., 1., 1.]], dtype=torch.float32).cuda()
> > > ret = roi_align(feat, roi)
> > > print(ret.shape)
> > > ```
> > 
> > 
> > Thank you for your answer
> > I run the minimal test case for testing the RoIAlign in mmcv and rebuild the mmcv from source but the error still exist
> > I test on ubuntu 18.04 with cuda10.1, pytorch 1.7.1 cudatoolkit 10.1 double 1080ti
> 
> You mean you can successfully run the minimal test?

Traceback (most recent call last):
  File "test.py", line 6, in <module>
    ret = roi_align(feat, roi)
  File "/home/wjc/anaconda3/envs/mmaction/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/wjc/Documents/liuwenlong/mmaction2/mmcv/mmcv/ops/roi_align.py", line 212, in forward
    self.sampling_ratio, self.pool_mode, self.aligned)
  File "/home/wjc/Documents/liuwenlong/mmaction2/mmcv/mmcv/ops/roi_align.py", line 102, in forward
    aligned=ctx.aligned)
RuntimeError: CUDA error: invalid device function
Segmentation fault (core dumped)

the error still exists

**Comment by kennymckormick** [comment]
> > > > Hello, here is a minimal test case for testing the `RoIAlign` in mmcv, u can try if u can run it successfully on ur machine. If not, you may try to reinstall the `mmcv-full` (maybe build it from source). @wen-flow
> > > > ```python
> > > > import torch
> > > > from mmcv.ops import RoIAlign
> > > > roi_align = RoIAlign(output_size=(7, 7)).cuda()
> > > > feat = torch.randn([1, 3, 24, 24]).cuda()
> > > > roi = torch.tensor([[0., 0., 0., 1., 1.]], dtype=torch.float32).cuda()
> > > > ret = roi_align(feat, roi)
> > > > print(ret.shape)
> > > > ```
> > > 
> > > 
> > > Thank you for your answer
> > > I run the minimal test case for testing the RoIAlign in mmcv and rebuild the mmcv from source but the error still exist
> > > I test on ubuntu 18.04 with cuda10.1, pytorch 1.7.1 cudatoolkit 10.1 double 1080ti
> > 
> > 
> > You mean you can successfully run the minimal test?
> 
> Traceback (most recent call last):
> File "test.py", line 6, in
> ret = roi_align(feat, roi)
> File "/home/wjc/anaconda3/envs/mmaction/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
> result = self.forward(*input, **kwargs)
> File "/home/wjc/Documents/liuwenlong/mmaction2/mmcv/mmcv/ops/roi_align.py", line 212, in forward
> self.sampling_ratio, self.pool_mode, self.aligned)
> File "/home/wjc/Documents/liuwenlong/mmaction2/mmcv/mmcv/ops/roi_align.py", line 102, in forward
> aligned=ctx.aligned)
> RuntimeError: CUDA error: invalid device function
> Segmentation fault (core dumped)
> 
> the error still exists

Then you have not installed mmcv correctly, maybe you can raise an issue under mmcv repo.

**Comment by ZacharySha** [comment]
Hello!~~~ have u solved it already? i meet the same problem as you, and i run it on ubuntu 10.04 with cuda 10.1, pytorch 1.7.1 as well, i don't know how to solve it.

**Comment by ZacharySha** [comment]
Hello!~~~ have u solved it already? i meet the same problem as you, and i run it on ubuntu with cuda 10.1, pytorch 1.7.1 as well, i don't know how to solve it.
