### ISSUE TITLE
How to manipulate data in a mini-batch

### ISSUE THREAD

**Issue by irvingzhang0512** [open-mmlab/mmaction2#627]
In order to implement mixup/cutmix, we'll manipulate data in a mini-batch, i.e. [official mixup code](https://github.com/facebookresearch/mixup-cifar10/blob/master/train.py#L119-L134)

I run through mmaction2 and get some ideas.

+ Try to use hooks or other tools in `EpochBasedRunner` but failed.
    + Current methods and hooks couldn't manipulate data in a mini-batch.
    + In order to do what we need, have to add codes in mmcv.
    + Better to modify codes in mmaction2 instead of mmcv.
+ Solutions for now:
    + Add related configs in `train_cfg`.
    + Modify `train_step` in `BaseRecognizer`.
+ Alternative solution : `collate_fn` in `DataLoader`
    + Add related configs in `train_dataloader`
    + Could create a new collate_fn to replace default value `mmcv.parallel.collate`.
+ Alternative solution: Wrap dataset
    + In order to implement mixup/cutmix, we don't have to manipulate data in a mini-batch. We can also create a wrapper for dataset, mix two dataset samples to generate one training sample.
    + I don't think it's a good idea since it doubles the cost of io and cpu.

Any better solutions for this?

**Comment by innerlee** [comment]
related https://github.com/open-mmlab/mmclassification/pull/160

**Comment by irvingzhang0512** [comment]
> related [open-mmlab/mmclassification#160](https://github.com/open-mmlab/mmclassification/pull/160)
Great! I like the idea from the PR, making mixup as the first layer of the model.
