### ISSUE TITLE
will consider to include 'Actor-Context-Actor Relation Network for Spatio-Temporal Action Localization'?

### ISSUE THREAD

**Issue by sijun-zhou** [open-mmlab/mmaction2#641]
Recently, I saw that on ava-kinetics challenge, the new method 'Actor-Context-Actor Relation Network for Spatio-Temporal Action Localization' has a very good performance and take the lead of nearly 6 percent to the second place in the competition 2020. And I think is a good candidate to enrich the area of spatio temporal action localization in mmaction2.  

Will you consider to include this network?

**Comment by innerlee** [comment]
Thanks for the suggestion. Please also leave a comment at https://github.com/open-mmlab/mmaction2/issues/19

**Comment by sijun-zhou** [comment]
> Thanks for the suggestion. Please also leave a comment at #19

Already comment under #19

**Comment by kennymckormick** [comment]
Thanks for the advice, reproducing ACAR-Net is not in our development schedule currently. However, we plan to support AVA-Kinetics weeks later.
