### ISSUE TITLE
AttributeError: 'BMN' object has no attribute 'backbone'

### ISSUE THREAD

**Issue by liuheng92** [open-mmlab/mmaction2#666]
Thanks for your error report and we appreciate it a lot.
If you feel we have help you, give us a STAR! :satisfied:

**Checklist**

1. I have searched related issues but cannot get the expected help.
2. The bug has not been fixed in the latest version.

**Describe the bug**

**Reproduction**

1. What command or script did you run?

```
python tools/train.py configs/localization/bmn/bmn_400x100_2x8_9e_activitynet_feature.py
```

2. Did you make any modifications on the code or config? Did you understand what you have modified?
no
3. What dataset did you use?
**Environment**

1. Please run `PYTHONPATH=${PWD}:$PYTHONPATH python mmaction/utils/collect_env.py` to collect necessary environment information and paste it here.
2. You may add addition that may be helpful for locating the problem, such as
    - How you installed PyTorch [e.g., pip, conda, source]
    - Other environment variables that may be related (such as `$PATH`, `$LD_LIBRARY_PATH`, `$PYTHONPATH`, etc.)

**Error traceback**

If applicable, paste the error traceback here.

```
something wrong with register_module_hooks(model.backbone, cfg.module_hooks), when config did not include backbone like bmn config
```

**Bug fix**

If you have already identified the reason, you can provide the information here. If you are willing to create a PR to fix it, please also leave a comment here and that would be much appreciated!

**Comment by congee524** [comment]
You can remove the line
https://github.com/open-mmlab/mmaction2/blob/4711717ceb751f4a7f08370cdcd6fd40f60b9e89/tools/train.py#L148
and
https://github.com/open-mmlab/mmaction2/blob/4711717ceb751f4a7f08370cdcd6fd40f60b9e89/tools/test.py#L181

And I'll fix it as soon as possible.

**Comment by liuheng92** [comment]
> You can remove the line
> https://github.com/open-mmlab/mmaction2/blob/4711717ceb751f4a7f08370cdcd6fd40f60b9e89/tools/train.py#L148
> 
> 
> and
> https://github.com/open-mmlab/mmaction2/blob/4711717ceb751f4a7f08370cdcd6fd40f60b9e89/tools/test.py#L181
> 
> And I'll fix it as soon as possible.

I'm runing code this way, thank you for reponse.

**Comment by dreamerlin** [comment]
> > You can remove the line
> > https://github.com/open-mmlab/mmaction2/blob/4711717ceb751f4a7f08370cdcd6fd40f60b9e89/tools/train.py#L148
> > 
> > and
> > https://github.com/open-mmlab/mmaction2/blob/4711717ceb751f4a7f08370cdcd6fd40f60b9e89/tools/test.py#L181
> > 
> > And I'll fix it as soon as possible.
> 
> I'm runing code this way, thank you for reponse.

If you feel we have help you, give us a STAR! 😆
