### ISSUE TITLE
runtimeError

### ISSUE THREAD

**Issue by hduer** [open-mmlab/mmaction2#673]
i used one config of Model  Zoo: c3d_sports1m_16x1x1_45e_ucf101_rgb.py
checkpoint also download from mmaction2

when i test c3d, eoor happened

RuntimeError: Given input size: (512x4x1x14). Calculated output size: (512x2x0x7). Output size is too small

**Comment by congee524** [comment]
Could you give more detailed information? The complete backtrace?
