### ISSUE TITLE
can not download UCF101-GT_v2.pkl

### ISSUE THREAD

**Issue by jiaozizhao** [open-mmlab/mmaction2#685]
Hi, Thanks for the great repo. 
You gave the repo for downloading the corrected annotation here https://github.com/gurkirt/corrected-UCF101-Annots. But when I checked the repo, I can not find the file UCF101-GT_v2.pkl in the repo. There is a pkl file called pyannot.pkl. Is this one which you called UCF101-GT_v2.pkl here? So I need to convert the format of pyannot.pkl by myself or is there a specific link to directly download UCF101-GT_v2.pkl? Could you kindly provide it if there is? thanks a lot.

**Comment by innerlee** [comment]
See the doc https://github.com/open-mmlab/mmaction2/tree/master/tools/data/ucf101_24#download-and-extract for data preparation

**Comment by innerlee** [comment]
Reading from the doc, the pkl file will be extracted from UCF101_v2.tar.gz

**Comment by dreamerlin** [comment]
The direct google drive url: https://drive.google.com/drive/folders/1BvGywlAGrACEqRyfYbz3wzlVV3cDFkct. As we indicated in the README: 

You can download the RGB frames, optical flow and ground truth annotations from [google drive](https://drive.google.com/drive/folders/1BvGywlAGrACEqRyfYbz3wzlVV3cDFkct).
The data are provided from [MOC](https://github.com/MCG-NJU/MOC-Detector/blob/master/readme/Dataset.md), which is adapted from [act-detector](https://github.com/vkalogeiton/caffe/tree/act-detector) and [corrected-UCF101-Annots](https://github.com/gurkirt/corrected-UCF101-Annots).

**Comment by dreamerlin** [comment]
@jiaozizhao
