### ISSUE TITLE
Test tpn_tsm with three crop or twice sample may get wrong dim

### ISSUE THREAD

**Issue by Bo396543018** [open-mmlab/mmaction2#696]
When I test trained tpn_tsm model with three crop, it  incured a dim mismatch error `RuntimeError: size mismatch, m1: [2 x 6144], m2: [2048 x 226]`. Same error as twice sample

**Comment by dreamerlin** [comment]
TPN_TSM is not supported now. It will be done when I have time : )
Or you can help with it, it is not difficult : )

**Comment by Bo396543018** [comment]
> TPN_TSM is not supported now. It will be done when I have time : )
> Or you can help with it, it is not difficult : )
OK,  I can do it myself.Thank you
