### ISSUE TITLE
Results are not in range (0,1)

### ISSUE THREAD

**Issue by kartik1395** [open-mmlab/mmaction2#699]
I'm using the high level api to make predictions for a video using TSN `https://github.com/open-mmlab/mmaction2/blob/master/docs/getting_started.md#high-level-apis-for-testing-a-video-and-rawframes`.

I had previously cloned the repo few months back and the results were in the range (0,1). Now I cloned the repo again few days back and the same api is now not giving results in the range (0,1). May I know what change needs to be made ? Do I need to manually add a softmax layer ?

`[('breakdancing', 9.127692), ('cartwheeling', 8.404121), ('faceplanting', 8.309557), ('drop kicking', 7.933985), ('skateboarding', 6.5199614)]`

**Comment by irvingzhang0512** [comment]
[faq](https://github.com/open-mmlab/mmaction2/blob/master/docs/faq.md#testing)

> change this in the config, make model['test_cfg'] = dict(average_clips='prob').

**Comment by kartik1395** [comment]
> [faq](https://github.com/open-mmlab/mmaction2/blob/master/docs/faq.md#testing)
> 
> > change this in the config, make model['test_cfg'] = dict(average_clips='prob').

Thank you so much.
