### ISSUE TITLE
Couldn't reproduce something-something-v2 results with provided ckpt

### ISSUE THREAD

**Issue by irvingzhang0512** [open-mmlab/mmaction2#705]
## Description
Successfully train tsm-r50 sthv2 using provided configs and get reasonable results. Test tsm-r50 sthv2 with model zoo ckpt, get **FAR WORSE** results than that of model zoo.

|model|top1/5 accuracy for efficient mode|top1/5 accuracy for accurate mode|
|:-:|:-:|:-:|
|copy from model zoo|57.86/84.67 |61.12/86.26|
|test with the [model zoo ckpt](https://download.openmmlab.com/mmaction/recognition/tsm/tsm_r50_1x1x8_50e_sthv2_rgb/tsm_r50_1x1x8_50e_sthv2_rgb_20200912-033c4ac6.pth) **by myself**|55.56/82.94|56.92/83.92|
|trained by myself with the [default config](https://github.com/open-mmlab/mmaction2/blob/master/configs/recognition/tsm/tsm_r50_1x1x8_50e_sthv2_rgb.py), trained ckpt [here](https://wp.cethik.com:443/link/9EC6E825165CC8AF556C6DDFC1FBC217)|58.91/85.10|61.68/86.71|

@dreamerlin verified tsm-r50 sthv2 ckpt [here](https://github.com/open-mmlab/mmaction2/pull/694#issuecomment-792776204) and the ckpt trained by me leads to WORSE results([here](https://github.com/open-mmlab/mmaction2/pull/694#issuecomment-793581927))

So I think there is a gap between our sthv2 datasets, which is wired.

+ Test all(tsn/tsm/tin 1x1x8/1x1x16 r50/r101) provided sthv2 ckpts. Done, all of them lead to WORSE results. 
+ Test all sthv1 ckpts, Done, get reasonable results. 
+ Double check all `20bn-something-something-v2-??` files with official md5. Done.
+ Double check all annotation json files. Done.
+ Extract rgb frames with ffmpeg and opencv. Done. Still couldn't reproduce the results.
+ Extracing rgb frames with denseflow. Doing now.

Could anyone test tsm-r50 on something-something-v2 **VIDEO** dataset.

PS: efficient/accurate test pipelines are listed as follows
```python
# efficient
test_pipeline = [
    dict(type='DecordInit'),
    dict(
        type='SampleFrames',
        clip_len=1,
        frame_interval=1,
        num_clips=8,
        test_mode=True),
    dict(type='DecordDecode'),
    dict(type='Resize', scale=(-1, 256)),
    dict(type='CenterCrop', crop_size=224),
    dict(type='FormatShape', input_format='NCHW'),
    dict(type='Collect', keys=['imgs', 'label'], meta_keys=[]),
    dict(type='ToTensor', keys=['imgs'])
]

# accurate
test_pipeline = [
    dict(type='DecordInit'),
    dict(
        type='SampleFrames',
        clip_len=1,
        frame_interval=1,
        num_clips=8,
        twice_sample=True,
        test_mode=True),
    dict(type='DecordDecode'),
    dict(type='Resize', scale=(-1, 256)),
    dict(type='ThreeCrop', crop_size=256),
    dict(type='FormatShape', input_format='NCHW'),
    dict(type='Collect', keys=['imgs', 'label'], meta_keys=[]),
    dict(type='ToTensor', keys=['imgs'])
]
```

**Comment by irvingzhang0512** [comment]
Successfully extract frames with denseflow, still couldn't reproduce sthv2 results... about 55.56 top1 accuracy for efficient mode...

**Comment by dreamerlin** [comment]
Currently, we check all the ckpts again and have carried out take Regression Testing per month now. The ckpts of SSV2 are all OK with correct performance.
