### ISSUE TITLE
Unittest coverage

### ISSUE THREAD

**Issue by dreamerlin** [open-mmlab/mmaction2#709]
- [x] omnisource_runner (https://codecov.io/gh/dreamerlin/mmaction2/src/master/mmaction/core/runner/omnisource_runner.py)
- [x] recall function (https://codecov.io/gh/dreamerlin/mmaction2/src/master/mmaction/core/evaluation/recall.py)

**Comment by kennymckormick** [comment]
The unit test of OmniSource runner is already added in PR #325. However, due to the limitation: 
```python
@pytest.mark.skipif(
    not torch.cuda.is_available(), reason='requires CUDA support')
```
Github CI can not run this test, you can try to remove the limitation to see if it works.

For the recall function, it is no longer used in this repo, maybe I will remove it.
