### ISSUE TITLE
long_video_demo.py

### ISSUE THREAD

**Issue by mytk2012** [open-mmlab/mmaction2#714]
Does long_video_demo.py support TSM model?
Because input of TSM are frames rather than mp4.

**Comment by dreamerlin** [comment]
Yes. The data pipeline should be changed for video. https://github.com/open-mmlab/mmaction2/blob/master/configs/recognition/tsm/tsm_r50_video_inference_1x1x8_100e_kinetics400_rgb.py

**Comment by mytk2012** [comment]
If i apply .pth trained by **tsm_r50_1*1*8_50e_sthv1.py**,does .pth fit **tsm_r50_video_inference_1*1*8_100e_kinetics400_rgb.py**?

**Comment by dreamerlin** [comment]
there is only difference in data pipeline rather than model setting
