### ISSUE TITLE
Some videos in gym99 dataset are unavaialable 

### ISSUE THREAD

**Issue by Gttgithub** [open-mmlab/mmaction2#718]
Some videos in gym99 dataset are unavaialable on Youtube, and can't be downloaded.

**Comment by Gttgithub** [comment]
youtube-dl --quiet --no-warnings --no-check-certificate -f mp4 -o "..\..\..\data\gym\videos\0MtilFKz4cA.mp4" "https://www.youtube.com/watch?v=0MtilFKz4cA"
Video 0MtilFKz4cA is unavaialable, skipping.
youtube-dl --quiet --no-warnings --no-check-certificate -f mp4 -o "..\..\..\data\gym\videos\1_Jqkqc9TgE.mp4" "https://www.youtube.com/watch?v=1_Jqkqc9TgE"
Video 1_Jqkqc9TgE is unavaialable, skipping.

**Comment by innerlee** [comment]
See https://github.com/open-mmlab/mmaction2/discussions/719
