### ISSUE TITLE
How the 27K frames in 'data/ava/rawframes' are mapped to 900 annotation record in CSV file during training of SlowFast Temporal model? 

### ISSUE THREAD

**Issue by arvindchandel** [open-mmlab/mmaction2#721]
I am trying to understand this mapping during the training, but couldn't get this so far. Plz explain this to me

In config file, we gave path to:
data_root = 'data/ava/rawframes'
anno_root = 'data/ava/annotations'

Annotation are done at 1 FPS from 902 - 1798 sec for each video, resulting approx 900 sec (15 min), of which details are available in data/ava/annotation folder. rawframes contains approx 27K frames for each video i.e frames produced at 30 FPS for each 15 min video. so doubt is how during training model maps the frames correspond to entries in annotation record.

**Comment by irvingzhang0512** [comment]
There are 27030 frames, aka 901 sec long video, for each movie.
Say the timestamp in ava annotation if `1000`, then the center frame index is `fps * (timestamp - timestamp_start) + 1`, where `fps=30, timestamp = 1000, timestamp_start=900`

BTW, I think the code you're looking for is 

https://github.com/open-mmlab/mmaction2/blob/13f42bfad0f45380bdbe1526d94953635b3f1fba/mmaction/datasets/pipelines/loading.py#L415-L455

**Comment by arvindchandel** [comment]
Thanks irvingzhang0512.
