### ISSUE TITLE
In SampleAVAFrames,center_index is not the key frame,it is more than one.Is it right?

### ISSUE THREAD

**Issue by ZJU-lishuang** [open-mmlab/mmaction2#726]
In SampleAVAFrames,center_index is from the code below.
```python
center_index = fps * (timestamp - timestamp_start) + 1
```
Why does center_index need to be added 1？
I think the result is not the key frame,it is more than one.

**Comment by irvingzhang0512** [comment]
I do have the same question. In PySlowFast, the center_index is `fps * (timestamp - 900)`. But I haven't compared the difference of sampling implementation between mmaction2 and pyslowfast in details.

**Comment by congee524** [comment]
Since the start idx of our rawframe is 1.

![image](https://user-images.githubusercontent.com/35596075/111310956-9ea9a100-8698-11eb-80fb-aa0194fab322.png)

**Comment by ZJU-lishuang** [comment]
In ava dataset,timestamp_start=0,timestamp is from 902 to 1798.
the key frame index "center_index" didn't have to add 1.frame_inds seems far from 1.
In custom dataset,there is a skip_offsets parameter,which is added to frame_inds.
I think it is no use in preventing cross-border functions.
![image](https://user-images.githubusercontent.com/26588466/111401354-1d87f380-8704-11eb-8f19-239751d9afa9.png)

**Comment by congee524** [comment]
> In ava dataset,timestamp_start=0,timestamp is from 902 to 1798.
> the key frame index "center_index" didn't have to add 1.frame_inds seems far from 1.
> In custom dataset,there is a skip_offsets parameter,which is added to frame_inds.
> I think it is no use in preventing cross-border functions.
> ![image](https://user-images.githubusercontent.com/26588466/111401354-1d87f380-8704-11eb-8f19-239751d9afa9.png)

Our `timestamp_start` should be 900.

https://github.com/open-mmlab/mmaction2/blob/07c34397ebed2bbd323d7d9d2752f01397508c23/mmaction/datasets/ava_dataset.py#L107

**Comment by irvingzhang0512** [comment]
Sec 900 corresponds to frames  frames `[1, 30]`, sec `sec_idx` corresponds to frames `[(sec_idx - 900) * 30 + 1, (sec_idx - 900 + 1) * 30 + 1]`
AVA annotate one frame(or the first frame) per second,  aka `(sec_idx - 900) * 30 + 1`

**Comment by michael-camilleri** [comment]
Shouldn't the center-index be the middle point of the second in question: i.e. if 30 FPS, then frame 15?

**Comment by kennymckormick** [comment]
> Shouldn't the center-index be the middle point of the second in question: i.e. if 30 FPS, then frame 15?

We are not sure whether the groundtruth bbox is associated with the beginning of a second or the middle point of a second. In MMAction2, we assume it's the beginning of a second. Personally, I think it doesn't make large difference.

**Comment by michael-camilleri** [comment]
> > Shouldn't the center-index be the middle point of the second in question: i.e. if 30 FPS, then frame 15?
> 
> We are not sure whether the groundtruth bbox is associated with the beginning of a second or the middle point of a second. In MMAction2, we assume it's the beginning of a second. Personally, I think it doesn't make large difference.

My only concern is the definition of the BBox in the frame of interest. Specifically, I am defining the BBox for the actor(s) (incidentally, my dataset is mice, which move quite quickly) in the middle frame, and hence, if using another frame, there will be (sometimes significant) shifts in the appearance.

I can possibly define my own dataloader for this, but was wondering if there is a solution which does not require this.

**Comment by kennymckormick** [comment]
The easiest solution is to convert your annotation. For example, you can pad 15 empty frames (if 30FPS) at the beginning, then ur BBox will bind to the beginning of a second rather than the middle. 

However, since you said you have a mice dataset, which may move quickly, I think you may need to reconsider using the SlowFast approach. I'm not sure if it can handle subjects that move quickly.

**Comment by michael-camilleri** [comment]
Thanks.

Actually, I am changing my BBox to bind to the first frame (although I am still unsure due to the addition of 1 -- my frames start from 0)
