### ISSUE TITLE
test.py: error: unrecognized arguments

### ISSUE THREAD

**Issue by skyqwe123** [open-mmlab/mmaction2#728]
when I use this command,
python tools/test.py configs/recognition/tpn_slowonly_r50_8x8x1_150e_actev_rgb.py checkpoints/epoch_165.pth
--eval top_k_accuracy mean_class_accuracy
It shows,
test.py: error: unrecognized arguments: configs/recognition/tpn_slowonly_r50_8x8x1_150e_actev_rgb.py checkpoints/epoch_165.pth
The file and path are correct. What's the problem？

**Comment by dreamerlin** [comment]
Wild guess: there maybe another "mmaction2", try `export PYTHONPATH=`pwd`:$PYTHONPATH` and run again.

**Comment by skyqwe123** [comment]
@dreamerlin Thanks,You are right, It works for me. And I what know that how can I set it to be permanent without error.

**Comment by dreamerlin** [comment]
FYI https://github.com/open-mmlab/mmaction2/blob/master/tools/dist_test.sh#L8

**Comment by dreamerlin** [comment]
https://github.com/open-mmlab/mmaction2/blob/master/docs/install.md#developing-with-multiple-mmaction2-versions
