### ISSUE TITLE
What is the function of proposals in ava_dense_proposals_train.FAIR.recall_93.9.pkl during training slowfast?

### ISSUE THREAD

**Issue by ZJU-lishuang** [open-mmlab/mmaction2#729]
What is the function of proposals in ava_dense_proposals_train.FAIR.recall_93.9.pkl during training slwofast?
Is it helpful for training the slowfast model?

**Comment by congee524** [comment]
The proposals were generated by a person detector with 93.9% recognition rate.
AVA is a spatiotemporal detection dataset centered on human behavior, the proposals is used to determine the spatial position of people.

**Comment by irvingzhang0512** [comment]
related issue #508

**Comment by ZJU-lishuang** [comment]
@congee524 But in ava dataset there is already a person box in csv.It is similar to the proposals.
So I'm confusing about it.
Can you explain it with specific code?It is helpful to understand the function of proposals.

**Comment by congee524** [comment]
> @congee524 But in ava dataset there is already a person box in csv.It is similar to the proposals.
> So I'm confusing about it.
> Can you explain it with specific code?It is helpful to understand the function of proposals.

The person box in ava dataset is the ground truth. we cannot use that to test accuracy.

**Comment by congee524** [comment]
On this spatiotemporal dataset, our task is to find out the position of the persons on each keyframe and recognize the actions they are doing.
Now many methods are to transform it into two tasks: detection and recognition, the former is done by a person detector, and the latter is done by some models of video understanding.

**Comment by ZJU-lishuang** [comment]
Is it helpless during training slowfast model?

**Comment by irvingzhang0512** [comment]
> We only use positive examples[IoU > 0.9] in training, and use proposals with high detection scores in testing.

IOU is calculated by proposals and gt labels

**Comment by congee524** [comment]
Slowfast is actually recognizing the actions of the persons in each proposals

**Comment by congee524** [comment]
Unless the model thinks that the proposal box is the background, in other cases, it thinks that a person is in the box.

**Comment by ZJU-lishuang** [comment]
Anther way to ask.
Can I use the gt box in training slowfast instead of the proposal which is generated by the detection?

**Comment by ZJU-lishuang** [comment]
I'm concerned about the function in training slowfast rather than other aspects

**Comment by congee524** [comment]
Formally, you can replace the proposals box with the gt box at any time.

In the training progress, you can do anything to train your models, but when testing, I think you may not use the gt box.

**Comment by ZJU-lishuang** [comment]
@congee524 
Yes.
In testing,I don't use the gt box.
But this issue is pointed out "during the training".

thanks for your help.
