### ISSUE TITLE
BSN README problem

### ISSUE THREAD

**Issue by kennymckormick** [open-mmlab/mmaction2#73]
training command in BSN README

python tools/train.py configs/localization/bsn/bsn_400x100_1x16_20e_activitynet_feature.py

can not run(filename not updated)

**Comment by dreamerlin** [comment]
Preparing a fix [here](https://github.com/open-mmlab/mmaction2/pull/74).

**Comment by innerlee** [comment]
its fair to point out typo issues. 
as an important team member, what's better, is to simply fix the typos and give a pr.

**Comment by kennymckormick** [comment]
> its fair to point out typo issues.
> as an important team member, what's better, is to simply fix the typos and give a pr.

OK, will fix directly next time. @dreamerlin told me before that the workflow is to raise an issue, assign to the code owner, and the code owner raise a PR.

**Comment by dreamerlin** [comment]
> > its fair to point out typo issues.
> > as an important team member, what's better, is to simply fix the typos and give a pr.
> 
> OK, will fix directly next time. @dreamerlin told me before that the workflow is to raise an issue, assign to the code owner, and the code owner raise a PR.

It doesn't bother to give a PR if you already have the solution. : )
