### ISSUE TITLE
can't extract frame in some subactions trimmed in videos  in GYM datasets

### ISSUE THREAD

**Issue by Gttgithub** [open-mmlab/mmaction2#743]
I use command =['ffmpeg', '-i',  '"%s"' % video_path, '-ss', str(start_time), '-t', str(end_time - start_time), '-c:v', 'copy', '-c:a', 'copy', '"%s"' % osp.join(subaction_root, output_filename)] to trim subactions in events. and then I extract frames from all subactions. However, nearly 2/3 of the videos are too short to play and cannot extract frames from them.  I don't know why , can someone help ma? I'll very appreciate it .
Some subactions that can not be extracted are as follows:
rgb 22083 s7pyZPf6fKU_E_003087_003128_A_0005_0007.mp4 None done
rgb 22084 n9-yxVGYMRw_E_001113_001212_A_0014_0015.mp4 None done
rgb 22085 Vq-w0Jk7y7g_E_007076_007181_A_0048_0049.mp4 None done
rgb 22086 s7pyZPf6fKU_E_004800_004901_A_0020_0021.mp4 None done
rgb 22087 ZHpME-SbKdQ_E_005626_005740_A_0053_0054.mp4 None done
rgb 22088 C5Yfd1IWjmM_E_004167_004203_A_0009_0011.mp4 None done
rgb 22089 R5hsatlgi70_E_000648_000736_A_0035_0036.mp4 None done
rgb 22090 EKb2MMJSoeI_E_001806_001893_A_0070_0071.mp4 None done
rgb 22091 1Fdwuy2V9EY_E_007355_007450_A_0072_0073.mp4 None done
rgb 22092 AZ4wWG6Rcak_E_004209_004299_A_0086_0087.mp4 None done
rgb 22093 X6sggzI0mw8_E_004985_005085_A_0089_0091.mp4 None done
rgb 22094 MDxIRDDWw1w_E_002013_002056_A_0010_0012.mp4 None done
rgb 22095 IP96HTdCvWs_E_002851_002887_A_0010_0012.mp4 None done
rgb 22096 e3EsDlpNo0c_E_007702_007737_A_0026_0027.mp4 None done
rgb 22097 aQy3nHo3V0E_E_006009_006098_A_0086_0087.mp4 None done

**Comment by kennymckormick** [comment]
Do you crawl the raw videos from Youtube with our scripts? Besides, what's the version of ur ffmpeg? 
It will be helpful if u provide an example: raw_video -> event -> subaction and tell me the length (number of frames) of your trimmed event and subaction respectively.

**Comment by dreamerlin** [comment]
@Gttgithub
