### ISSUE TITLE
[Fix] Shall we temporarily remove UCF101-24 and JHMDB in supported datasets in README?

### ISSUE THREAD

**Issue by kennymckormick** [open-mmlab/mmaction2#747]
Now we only have data preparation scripts. We haven't trained any models on these two datasets. It will be misleading.

**Comment by kennymckormick** [comment]
as well as jester

**Comment by irvingzhang0512** [comment]
We have(and only have) TSN models for ucf101 and jhmdb.

**Comment by congee524** [comment]
> as well as jester

I'm going to train TRN on jester.

**Comment by innerlee** [comment]
Makes sense. How about removing the ✔️ from the ✅ and leaving the  empty🔲 there. And add a note 

> Datasets marked with 🔲 are not fully supported yet.

**Comment by kennymckormick** [comment]
> Makes sense. How about removing the ✔️ from the ✅ and leaving the empty🔲 there. And add a note
> 
> > Datasets marked with 🔲 are not fully supported yet.

That makes sense.
