### ISSUE TITLE
checkpoint

### ISSUE THREAD

**Issue by zhaijianyang** [open-mmlab/mmaction2#748]
I don’t want to save checkpoints for every epoch. I just want to save the best and last time. How should I change it? Thank you

**Comment by irvingzhang0512** [comment]
`checkpoint_config = dict(interval=1, max_keep_ckpts=1)`

More information about checkpoint hook could refer to [CheckpointHook](https://github.com/open-mmlab/mmcv/blob/97730c2316d3df99a6a9780e2129ea4a462f5b49/mmcv/runner/hooks/checkpoint.py#L9)
