### ISSUE TITLE
CN configs request

### ISSUE THREAD

**Issue by dreamerlin** [open-mmlab/mmaction2#760]
- [x] AVA @kennymckormick 
- [x] LFB @congee524 
- [x] OminiSource @kennymckormick

**Comment by kennymckormick** [comment]
what do u mean by CN config?

**Comment by congee524** [comment]
> what do u mean by CN config?

config README_zh-CN.md

**Comment by kennymckormick** [comment]
OK

**Comment by congee524** [comment]
LFB in #761
