### ISSUE TITLE
ModuleNotFoundError: No module named 'mmaction'

### ISSUE THREAD

**Issue by myNameEA** [open-mmlab/mmaction2#766]
I have encountered an errror like this : ModuleNotFoundError: No module named 'mmaction' . 
![issues](https://user-images.githubusercontent.com/30695325/112837125-1252a180-90ce-11eb-959c-a73dd68e3235.png)
 
But i can import mmaction in python .

**Comment by nobody-cheng** [comment]
how fix ??

**Comment by LMW4444** [comment]
What's the solution

**Comment by andre-zh** [comment]
> What's the solution

An error on path:

import sys
sys.path.append('/XXXXX/mmaction2')
