### ISSUE TITLE
About the AssertionError: MMCV==1.3.0 is used but incompatible. Please install mmcv>=1.2.6, <=1.3.

### ISSUE THREAD

**Issue by nekomiao123** [open-mmlab/mmaction2#768]
Hi, I tried to run the verification code and it said AssertionError. 
<img width="904" alt="image" src="https://user-images.githubusercontent.com/34064940/112847501-b857d900-90d9-11eb-9a57-39cb5163ec59.png">
Then I tried to modify the code in the __init__.py file.
<img width="1106" alt="image" src="https://user-images.githubusercontent.com/34064940/112847727-f48b3980-90d9-11eb-8a8d-8b611f42b9ff.png">
And it works.
I wonder if it is a bug in the __init__.py file.

I find that the init.py like this in another project. So, I think it may be a bug.
<img width="1246" alt="image" src="https://user-images.githubusercontent.com/34064940/112848827-146f2d00-90db-11eb-94c1-2940b6e2c71f.png">

**Comment by dreamerlin** [comment]
Thanks for your report, we have provide a [PR](#769 ) to solve it.
