### ISSUE TITLE
Is the feature available to hook weights and Biases tool with MMaction2 to track experiments?

### ISSUE THREAD

**Issue by arvindchandel** [open-mmlab/mmaction2#771]

**Comment by dreamerlin** [comment]
https://github.com/open-mmlab/mmaction2/pull/458, this may help

**Comment by arvindchandel** [comment]
@dreamerlin I had a look at #458, but couldn't understood much. if you can explore little more about it, it may be helpful.

**Comment by arvindchandel** [comment]
I can hook it now. Thanks @dreamerlin
