### ISSUE TITLE
Iteration Plan - Apr 2021

### ISSUE THREAD

**Issue by dreamerlin** [open-mmlab/mmaction2#779]
Since MMAction2 v0.13.0 has been released, now it's time to plan for the next iteration, i.e. v0.14.0.
This will be a one-month iteration and our focus in this iteration is to support more algorithms and refactor some codes.

**Algorithms**:
- [ ] PoseC3D (https://github.com/open-mmlab/mmaction2/pull/786)
- [x] TRN (https://github.com/open-mmlab/mmaction2/pull/755)
- [ ] TDN

**Dataset**:
- [ ] AVA-Kinetics
- [ ] Charades (https://github.com/open-mmlab/mmaction2/pull/788)

**Misc**:

~~- [ ] Entrypoint Refactoring~~
~~- [ ] Unify parameters initilization (#794)~~ blocked by upstream

- [x] Model Registry (open-mmlab/mmcv#780)
- [x] Registry conflict resolution (#843)
- [ ] Video Transformer researching
- [x] Support auto_fp16 using torch.cuda.amp

**Comment by irvingzhang0512** [comment]
+ Test with ONNX model or TensorRT engine. #758
+ Recognizers Comparision #773
+ Webcam Demo for Spatio-Temporal Action Detection models.
+ [YOWO](https://github.com/wei-tim/YOWO) for ava

**Comment by Deep-learning999** [comment]
I hope to provide pre-training of different frame lengths in slowonly and slowfast of ava-Kinetics, as well as pre-training of TimeSformer in ava2.1 and ava-Kinetics. I think the real-time performance and map should be improved.

> 由于MMAction2 v0.13.0已发布，现在是时候计划下一个迭代，即v0.14.0。
> 这将是一个月的迭代，我们在此迭代中的重点是支持更多算法并重构某些代码。
> 
> **算法**：
> 
> * [ ] 姿势C3D（[＃786](https://github.com/open-mmlab/mmaction2/pull/786)）
> * [x] TRN（[＃755](https://github.com/open-mmlab/mmaction2/pull/755)）
> * [ ]  TDN
> 
> **数据集**：
> 
> * [ ]  AVA运动学
> * [ ] 夏拉德（[＃788](https://github.com/open-mmlab/mmaction2/pull/788)）
> 
> **其他**：
> 
> OpenMMLab重构项目
> 
> * [ ]  入口点重构
> * [ ] 模型注册表（[open-mmlab / mmcv＃780](https://github.com/open-mmlab/mmcv/pull/780)）
> * [ ] 统一参数初始化（[＃794](https://github.com/open-mmlab/mmaction2/pull/794)）
> * [ ]  解决注册表冲突
> * [ ]  视频变压器研究
> * [ ]  使用torch.cuda.amp支持auto_fp16

I hope to provide pre-training of different frame lengths in slowonly and slowfast of ava-Kinetics, as well as pre-training of TimeSformer in ava2.1 and ava-Kinetics. I think the real-time performance and map should be improved.
