### ISSUE TITLE
How to add NECK module

### ISSUE THREAD

**Issue by suki7** [open-mmlab/mmaction2#78]
I want to reimplement TPN in mmaction2. TPN registries the 'TPN' NECK module in the original mmaction, how can I implement this function in mmaction2?

**Comment by dreamerlin** [comment]
We will support `TPN` recently.

**Comment by suki7** [comment]
> We will support `TPN` recently.

thanks!!

**Comment by suki7** [comment]
> We will support `TPN` recently.

when will TPN be supported?  I cannot reproduce the TPN results in mmaction2...thanks for your work in advance!!

**Comment by dreamerlin** [comment]
Related PR is [here](https://github.com/open-mmlab/mmaction2/pull/170)
