### ISSUE TITLE
ValueError: Label should not be None

### ISSUE THREAD

**Issue by Vankeee** [open-mmlab/mmaction2#783]
I used nni to do the model speedup, but I got the error. Could anyone help me, I have no idea what is going on.

```

from nni.algorithms.compression.pytorch.pruning import L2FilterPruner
import nni
from nni.algorithms.compression.pytorch.pruning import *
from nni.compression.pytorch import apply_compression_results, ModelSpeedup

def init_model():
    config_file = '../config/tsn_r50_video_inference_1x1x3_100e_kinetics400_rgb.py'
    device = 'cuda:0' # or 'cpu'
    device = torch.device(device)

    model = init_recognizer(config_file, device=device)
    return model



model = init_model()
config_list = [{ 'sparsity': 0.5, 'op_types': ['Conv2d'] }]
pruner = L2FilterPruner(model, config_list)
model_compressed  = pruner.compress()

mask_path  ='../model/L2Filter_pruned_mask.pth'
model_path =  '../model/L2Filter_pruned_model.pth'
pruner.export_model(model_path =model_path ,mask_path = mask_path)

device = 'cuda:0' # or 'cpu'
device = torch.device(device)
dummy_input = torch.randn([64, 3, 32, 32]).to(device)

m_speedup = ModelSpeedup(model,dummy_input , mask_path, device)
```

> 
> ValueError                                Traceback (most recent call last)
> <ipython-input-87-5ff9577fdc11> in <module>
>       3 dummy_input = torch.randn([64, 3, 32, 32]).to(device)
>       4 
> ----> 5 m_speedup = ModelSpeedup(model,dummy_input , mask_path, device)
> 
> ~/anaconda3/envs/mmlab/lib/python3.8/site-packages/nni/compression/pytorch/speedup/compressor.py in __init__(self, model, dummy_input, masks_file, map_location)
>      36         self.inferred_masks = dict() # key: module_name, value: ModuleMasks
>      37         self.dummy_input = dummy_input
> ---> 38         self.torch_graph = build_module_graph(model, dummy_input)
>      39 
>      40     def infer_module_mask(self, module_name, last_module, mask=None, in_shape=None, out_shape=None):
> 
> ~/anaconda3/envs/mmlab/lib/python3.8/site-packages/nni/common/graph_utils.py in build_module_graph(model, dummy_input)
>      22 
>      23 def build_module_graph(model, dummy_input):
> ---> 24     return TorchModuleGraph(model, dummy_input)
>      25 
>      26 
> 
> ~/anaconda3/envs/mmlab/lib/python3.8/site-packages/nni/common/graph_utils.py in __init__(self, model, dummy_input, traced_model)
>     246 
>     247     def __init__(self, model=None, dummy_input=None, traced_model=None):
> --> 248         super().__init__(model, dummy_input, traced_model)
>     249         self.global_count = 0
>     250         self.name_to_node, self.input_to_node, self.output_to_node = self._build_graph()
> 
> ~/anaconda3/envs/mmlab/lib/python3.8/site-packages/nni/common/graph_utils.py in __init__(self, model, dummy_input, traced_model)
>      64         elif model is not None and dummy_input is not None:
>      65             self.bound_model = model
> ---> 66             self._trace(model, dummy_input)
>      67         else:
>      68             raise Exception(
> 
> ~/anaconda3/envs/mmlab/lib/python3.8/site-packages/nni/common/graph_utils.py in _trace(self, model, dummy_input)
>      72         training = model.training
>      73         model.eval()
> ---> 74         self.trace = torch.jit.trace(model, dummy_input)
>      75         torch._C._jit_pass_inline(self.trace.graph)
>      76         model.train(training)
> 
> ~/anaconda3/envs/mmlab/lib/python3.8/site-packages/torch/jit/_trace.py in trace(func, example_inputs, optimize, check_trace, check_inputs, check_tolerance, strict, _force_outplace, _module_class, _compilation_unit)
>     731 
>     732     if isinstance(func, torch.nn.Module):
> --> 733         return trace_module(
>     734             func,
>     735             {"forward": example_inputs},
> 
> ~/anaconda3/envs/mmlab/lib/python3.8/site-packages/torch/jit/_trace.py in trace_module(mod, inputs, optimize, check_trace, check_inputs, check_tolerance, strict, _force_outplace, _module_class, _compilation_unit)
>     932             func = mod if method_name == "forward" else getattr(mod, method_name)
>     933             example_inputs = make_tuple(example_inputs)
> --> 934             module._c._create_method_from_trace(
>     935                 method_name,
>     936                 func,
> 
> ~/anaconda3/envs/mmlab/lib/python3.8/site-packages/torch/nn/modules/module.py in _call_impl(self, *input, **kwargs)
>     723                 input = result
>     724         if torch._C._get_tracing_state():
> --> 725             result = self._slow_forward(*input, **kwargs)
>     726         else:
>     727             result = self.forward(*input, **kwargs)
> 
> ~/anaconda3/envs/mmlab/lib/python3.8/site-packages/torch/nn/modules/module.py in _slow_forward(self, *input, **kwargs)
>     707                 recording_scopes = False
>     708         try:
> --> 709             result = self.forward(*input, **kwargs)
>     710         finally:
>     711             if recording_scopes:
> 
> ~/mmlab/mmaction2/mmaction/models/recognizers/base.py in forward(self, imgs, label, return_loss, **kwargs)
>     219         if return_loss:
>     220             if label is None:
> --> 221                 raise ValueError('Label should not be None.')
>     222             if self.blending is not None:
>     223                 imgs, label = self.blending(imgs, label)
> 
> ValueError: Label should not be None.
>

**Comment by irvingzhang0512** [comment]
Haven't used nni before. But I think this issued is caused by the input of the model. The input for testing recognizers should be `model(imgs, return_loss=False)`

**Comment by Vankeee** [comment]
@irvingzhang0512 It needs a label file path. When I used summary tring to print the strcuture of the model, the error "Label should not be None."  appeared too. 


```
from torchsummaryX import summary

....
summary(model, dummy_input)
```

**Comment by Vankeee** [comment]
@irvingzhang0512 I got another error when I ran the code. I am totally a newbie

```
dummy_input = torch.randn([50, 64, 3,32, 32]).to(device)
model(dummy_input, return_loss =False)
```



> ---------------------------------------------------------------------------
> RuntimeError                              Traceback (most recent call last)
> <ipython-input-68-2e1dab999ca8> in <module>
> ----> 1 model(dummy_input, return_loss =False)
> 
> ~/anaconda3/envs/mmlab/lib/python3.8/site-packages/torch/nn/modules/module.py in _call_impl(self, *input, **kwargs)
>     725             result = self._slow_forward(*input, **kwargs)
>     726         else:
> --> 727             result = self.forward(*input, **kwargs)
>     728         for hook in itertools.chain(
>     729                 _global_forward_hooks.values(),
> 
> ~/mmlab/mmaction2/mmaction/models/recognizers/base.py in forward(self, imgs, label, return_loss, **kwargs)
>     224             return self.forward_train(imgs, label, **kwargs)
>     225 
> --> 226         return self.forward_test(imgs, **kwargs)
>     227 
>     228     def train_step(self, data_batch, optimizer, **kwargs):
> 
> ~/mmlab/mmaction2/mmaction/models/recognizers/recognizer2d.py in forward_test(self, imgs)
>     130             # If specified, spatially fully-convolutional testing is performed
>     131             return self._do_fcn_test(imgs).cpu().numpy()
> --> 132         return self._do_test(imgs).cpu().numpy()
>     133 
>     134     def forward_dummy(self, imgs):
> 
> RuntimeError: Can't call numpy() on Tensor that requires grad. Use tensor.detach().numpy() instead.
>

**Comment by irvingzhang0512** [comment]
As shown in [inference_recognizer](https://github.com/open-mmlab/mmaction2/blob/18824abfc36ec44b4d51915262af1be3dbf8c74b/mmaction/apis/inference.py#L132), you need `with torch.no_grad():` to wrap test forward pass

https://github.com/open-mmlab/mmaction2/blob/18824abfc36ec44b4d51915262af1be3dbf8c74b/mmaction/apis/inference.py#L132-L133

**Comment by irvingzhang0512** [comment]
I'm not familiar with tensorboardX, maybe you could refer to [pytorch2onnx.py](https://github.com/open-mmlab/mmaction2/blob/master/tools/pytorch2onnx.py)

**Comment by Vankeee** [comment]
@irvingzhang0512 THANKS! I will comment while problems solved.
