### ISSUE TITLE
No such file or directory: 'openmm/mmaction2/data/ucf101/rawframes/Skiing/v_Skiing_g06_c04/img_00300.jpg

### ISSUE THREAD

**Issue by blackmagicianZ** [open-mmlab/mmaction2#79]
for example, the images in folder `openmm/mmaction2/data/ucf101/rawframes/Skiing/v_Skiing_g06_c04/` was `img_00000.jpg~img_00299.jpg`

https://github.com/open-mmlab/mmaction2/blob/6307050d94141157ebda8f9d10a708b6790e61fc/mmaction/datasets/rawframe_dataset.py#L115

i modified this line to 
```
video_info['total_frames'] = int(line_split[idx]) - 1
```
and it started training, is it right?

**Comment by innerlee** [comment]
there is an option to specify start index.

**Comment by dreamerlin** [comment]
You can refer to [this](https://github.com/open-mmlab/mmaction2/blob/master/mmaction/datasets/pipelines/loading.py#L27-L30), we use `start_index` to specify a start index for files, so you can modify the config file in `SampleFrames` part like [this line](https://github.com/open-mmlab/mmaction2/blob/master/configs/recognition/tsn/tsn_r50_video_1x1x8_100e_kinetics400_rgb.py#L36)

**Comment by innerlee** [comment]
@dreamerlin how about we move start_index option to DataSet level? this way, we can normalize everything to 0-based indexing from the beginning. the discoverability is better also

**Comment by innerlee** [comment]
for the record, with_offset is written at DataSet level

**Comment by dreamerlin** [comment]
Sounds good, I will try it.

**Comment by blackmagicianZ** [comment]
> You can refer to [this](https://github.com/open-mmlab/mmaction2/blob/master/mmaction/datasets/pipelines/loading.py#L27-L30), we use `start_index` to specify a start index for files, so you can modify the config file in `SampleFrames` part like [this line](https://github.com/open-mmlab/mmaction2/blob/master/configs/recognition/tsn/tsn_r50_video_1x1x8_100e_kinetics400_rgb.py#L36).

How quick the response is! i see, thanks!

**Comment by dreamerlin** [comment]
> @dreamerlin how about we move start_index option to DataSet level? this way, we can normalize everything to 0-based indexing from the beginning. the discoverability is better also

Now we have move start_index option to DataSet level.

**Comment by skyqwe123** [comment]
@blackmagicianZ  I have the same errors.  Have you find  a soild solutions.

**Comment by innerlee** [comment]
Example of specifying start_index https://github.com/open-mmlab/mmaction2/blob/master/configs/recognition/tsn/tsn_r50_320p_1x1x8_150e_activitynet_video_flow.py#L83

**Comment by skyqwe123** [comment]
@innerlee Thanks for your response.  I don't konw if the file(config_file) have been modified, I try it again as your recommend,it seems works correctly.

**Comment by dreamerlin** [comment]
> @innerlee Thanks for your response. I don't konw if the file(config_file) have been modified, I try it again as your recommend,it seems works correctly.

In fact, we have set `start_index = 1` as default value for [rawframe dataset](https://github.com/open-mmlab/mmaction2/blob/master/mmaction/datasets/rawframe_dataset.py#L96), and `start_index = 0` as default value for [video dataset](https://github.com/open-mmlab/mmaction2/blob/master/mmaction/datasets/video_dataset.py#L40). : ), and if there is still an error, you may need to modify the start_index like [the file mentioned above](https://github.com/open-mmlab/mmaction2/blob/master/configs/recognition/tsn/tsn_r50_320p_1x1x8_150e_activitynet_video_flow.py#L83) manually.

**Comment by dreamerlin** [comment]
And If you feel we have help you, give us a STAR! : )
