### ISSUE TITLE
thumos14 dataset preparation result does not match the result showed in the readme.md

### ISSUE THREAD

**Issue by duduheihei** [open-mmlab/mmaction2#792]
I try to train SSN with thumos14, and prepared dataset with scripts in the directory "tools/data/thumos" ,and extracted rgb frames with denseflow. However, the indices of frames begin with 0. For example the first image extracted is named "img_00000.jpg", which should be "img_00001.jpg". This difference cause error "File not found" when train model with "dist_train.sh".

**Comment by congee524** [comment]
You need to set `start_index=0` for your SSN dataset.
```
data = dict(
    videos_per_gpu=1,
    workers_per_gpu=2,
    train=dict(
        type=dataset_type,
        ann_file=ann_file_train,
        data_prefix=data_root,
        train_cfg=train_cfg,
        test_cfg=test_cfg,
        start_index=0,
        ...),
    val=dict(
        type=dataset_type,
        ann_file=ann_file_val,
        data_prefix=data_root,
        train_cfg=train_cfg,
        test_cfg=test_cfg,
        start_index=0,
        ...),)
```

**Comment by duduheihei** [comment]
> You need to set `start_index=0` for your SSN dataset.
> 
> ```
> data = dict(
>     videos_per_gpu=1,
>     workers_per_gpu=2,
>     train=dict(
>         type=dataset_type,
>         ann_file=ann_file_train,
>         data_prefix=data_root,
>         train_cfg=train_cfg,
>         test_cfg=test_cfg,
>         start_index=0,
>         ...),
>     val=dict(
>         type=dataset_type,
>         ann_file=ann_file_val,
>         data_prefix=data_root,
>         train_cfg=train_cfg,
>         test_cfg=test_cfg,
>         start_index=0,
>         ...))
> ```

That solved my problem, thanks.

**Comment by innerlee** [comment]
@congee524 maybe we can make the error message smart?

**Comment by congee524** [comment]
> @congee524 maybe we can make the error message smart?

This error message is raised by mmcv.
we just pass the paths of frames to the `file_client` and it's hard to warn by just referring to `start_index` or `frame path`
