### ISSUE TITLE
run demo_spatiotemporal_det.py error

### ISSUE THREAD

**Issue by guijuzhejiang** [open-mmlab/mmaction2#802]
When I run demo_spatiotemporal_det.py,the following errors eccur
Traceback (most recent call last):
  File "/home/zzg/workspace/pycharm/mmaction2/demo/demo_spatiotemporal_det.py", line 361, in <module>
    main()
  File "/home/zzg/workspace/pycharm/mmaction2/demo/demo_spatiotemporal_det.py", line 328, in main
    if result[i][j, 4] > args.action_score_thr:
IndexError: index 3 is out of bounds for axis 0 with size 3

I think it is because result[i].shape[0] is smaller than proposal.shape[0].
So I modified my code as following:
#for j in range(proposal.shape[0]):
for j in range(result[i].shape[0])

Is it right?

**Comment by kennymckormick** [comment]
You are right, thanks for pointing out this bug (which caused by adding action_score_thr to config files). We raise PR #803 to fix it.

**Comment by irvingzhang0512** [comment]
I don't think it's ok to replace `proposal.shape[0]` with `result[i].shape[0]`.

To make it clear, rename some params

```python
        for class_id in range(len(result)):
            if class_id + 1 not in self.label_map:
                continue
            for bbox_id in range(result[class_id].shape[0]):
                if result[class_id][bbox_id, 4] > self.score_thr:
                    prediction[bbox_id].append((self.label_map[class_id + 1], result[class_id][bbox_id, 4]))
```

Since `result[class_id].shape[0]` may be different for different `class_id`, then the same `bbox_id` for different `class_id` may refer to different bbox.
@kennymckormick @guijuzhejiang

**Comment by kennymckormick** [comment]
> I don't think it's ok to replace `proposal.shape[0]` with `result[i].shape[0]`.
> 
> To make it clear, rename some params
> 
> ```python
>         for class_id in range(len(result)):
>             if class_id + 1 not in self.label_map:
>                 continue
>             for bbox_id in range(result[class_id].shape[0]):
>                 if result[class_id][bbox_id, 4] > self.score_thr:
>                     prediction[bbox_id].append((self.label_map[class_id + 1], result[class_id][bbox_id, 4]))
> ```
> 
> Since `result[class_id].shape[0]` may be different for different `class_id`, then the same `bbox_id` for different `class_id` may refer to different bbox.
> @kennymckormick @guijuzhejiang

Sorry for my carelessness, I think setting action_score_thr = 0 is a better solution.
