### ISSUE TITLE
ImportError: cannot import name 'train_model' from 'mmaction.apis' 

### ISSUE THREAD

**Issue by vamfantasia** [open-mmlab/mmaction2#810]
![QQ截图20210414200327](https://user-images.githubusercontent.com/73690985/114707370-b8eca280-9d5c-11eb-9a34-e8df10dda154.png)

**Comment by irvingzhang0512** [comment]
What's your mmaction2 version?

BTW, normally I start training under `/path/to/mmaction2` and run `python tools/train.py ...`

**Comment by dreamerlin** [comment]
It seems you are calling another mmaction from some other places.

I suggest you start training under `/path/to/mmaction2`, run `export PYTHONPATH=`pwd`:$PYTHONPATH` and then run `python tools/train.py ...`

**Comment by dreamerlin** [comment]
It seems the problem has been solved. If you feel we have helped you, you can give us a STAR! : )

**Comment by Laowai01** [comment]
export PYTHONPATH='/xx/xx/xx/mmaction2/lib/python3.6/site-packages/':$PYTHONPATH

either command line or in .bashrc will solve the issue.
