### ISSUE TITLE
How to reimplement SSN with two stream features?

### ISSUE THREAD

**Issue by curiosity654** [open-mmlab/mmaction2#818]
Hi, I have just reimplemented the SSN model on RGB frames using the official config file, but I wonder if there's a guide to reimplement it with two-stream features? Because the high accuracy reported in the paper is on two-stream features.

**Comment by tony2016uestc** [comment]
No, the original open-source SSN repo only includes RGB implementation.
Maybe you have to tune hyperparameters of SSN on flow features.
