### ISSUE TITLE
add 'label' argument in forward_test

### ISSUE THREAD

**Issue by MakeCent** [open-mmlab/mmaction2#823]
**Describe the feature**
The current default forward_test() function in all base modules doesn't support the 'label' argument, making the computation of loss in the validation dataset become very inconvenient. Therefore I suggest adding 'label=None' as a default argument.

In addition to the convenience of computing validation loss, this can also be used to identify the testing and validation phase, like:

```python
if label is None:
   do_test_step()
else:
  do_val_step()
```

which is useful when validation and testing have different forward methods.

**Motivation**
To make --validate can compute losses and print it. Identify if validation or testing easily.

**Comment by innerlee** [comment]
Thanks for the report. Testing is used for inference without label, and validation will use labels to compute metrics such as accuracies.

@dreamerlin do we support reporting loss in validation?

**Comment by dreamerlin** [comment]
https://github.com/open-mmlab/mmaction2/pull/123

You can set val workflow to report loss in validation.
