### ISSUE TITLE
train.py just have --resume-from, can't use --load-from

### ISSUE THREAD

**Issue by geek12138** [open-mmlab/mmaction2#830]
When I use train.py to add to the pre-training file, I can only use --resume-from but not --load-from, so that the loaded pre-training file contains some previous training information, which causes the code to stop early. The problem.
But there is an introduction of --load-from in the official documentation.

**Comment by innerlee** [comment]
load_from is typically specified in config file

**Comment by innerlee** [comment]
See https://github.com/open-mmlab/mmaction2/blob/master/configs/_base_/default_runtime.py

**Comment by innerlee** [comment]
This is one of the bad side of the currently so called hierarchy design of configs.

**Comment by geek12138** [comment]
> This is one of the terrible side of the currently so called hierarchy design of configs.

Thank you, it's really hard to find. I tried --load_from in the entire document before but couldn't find it. I didn't expect it to be load_from. Thanks again.

**Comment by geek12138** [comment]
> This is one of the terrible side of the currently so called hierarchy design of configs.

Thank you, it's really hard to find. I tried --load_from in the entire document before but couldn't find it. I didn't expect it to be load_from. Thanks again.
