### ISSUE TITLE
demo_spatiotemporal_det error

### ISSUE THREAD

**Issue by Deep-learning999** [open-mmlab/mmaction2#832]
Before raising a question, you may need to check the following listed items.

**Checklist**

1. I have searched related issues but cannot get the expected help.
2. I have read the [FAQ documentation](https://mmaction2.readthedocs.io/en/latest/faq.html) but cannot get the expected help.
3. 
This error occurs when my first video is longer than 4 minutes, the screen changes quickly, and the characters move faster.
python demo/demo_spatiotemporal_det.py --video demo/4.mp4 \
    --config configs/detection/ava/slowonly_omnisource_pretrained_r101_8x8x1_20e_ava_rgb.py \
    --checkpoint https://download.openmmlab.com/mmaction/detection/ava/slowonly_omnisource_pretrained_r101_8x8x1_20e_ava_rgb/slowonly_omnisource_pretrained_r101_8x8x1_20e_ava_rgb_20201217-16378594.pth \
    --det-config demo/faster_rcnn_r50_fpn_2x_coco.py \
    --det-checkpoint http://download.openmmlab.com/mmdetection/v2.0/faster_rcnn/faster_rcnn_r50_fpn_2x_coco/faster_rcnn_r50_fpn_2x_coco_bbox_mAP-0.384_20200504_210434-a5d8aa15.pth \
    --det-score-thr 0.9 \
    --action-score-thr 0.5 \
    --label-map demo/label_map_ava.txt \
    --predict-stepsize 8 \
    --output-stepsize 4 \
    --output-fps 6

Traceback (most recent call last):
  File "demo/demo_spatiotemporal_det.py", line 401, in <module>
    main()
  File "demo/demo_spatiotemporal_det.py", line 282, in main
    h, w, _ = original_frames[0].shape
IndexError: list index out of range

**Comment by Deep-learning999** [comment]
May I ask what caused this error

**Comment by irvingzhang0512** [comment]
It seems this demo failed to extract frames from the input video

**Comment by kennymckormick** [comment]
It seems that the subroutine frame_extraction returned an empty list. Would you please check if `demo/4.mp4` exists or can be decoded by frame_extraction properly?

**Comment by Deep-learning999** [comment]
demo/4.mp4 exists and Locally playable

**Comment by kennymckormick** [comment]
> demo/4.mp4 exists and Locally playable

Would you please try to decode it using cv2.VideoCapture (like frame_extraction) and check if it works? It may help us figure out the issue.

**Comment by Deep-learning999** [comment]
It can run now, but the 4-minute video is only 1 minute and 17 seconds after the final synthesis, and many frames are ignored

**Comment by Deep-learning999** [comment]
is OK

**Comment by Noceiling1** [comment]
这个问题我也遇到了，请问怎么解决啊
