### ISSUE TITLE
Training hangs for bigger datasets (using multiple GPUs)

### ISSUE THREAD

**Issue by rlleshi** [open-mmlab/mmaction2#838]
I am fine-tuning an I3D model using the `train.py` script (great work with the repo btw).  It works fine for datasets of smaller size, e.g. 1.5k clips but currently, the training is hanging for larger datasets (e.g. 3.5k clips). After the 5th epoch, a checkpoint is saved and thereafter the training process hangs indefinitely. 

Following this [issue](https://github.com/open-mmlab/mmaction2/issues/421), I tried:

- Setting `workers_per_gpu` to 0
- Setting `videos_per_gpu` to a lower value
- Adding a `time.sleep(2)` before `epoch_runner(data_loaders[i], **kwargs)`
- Increasing the shared memory (up to 25gb)

As in the above-mentioned issue, the training hangs @ `mmcv.runner.epoch_based_runner -> epoch_runner(data_loaders[i], **kwargs)`

I currently have 4 GPUs on which I am doing this training. 

Perhaps I should also mention that before this hanging issue, (with the larger dataset) I also came across this [decord error](https://github.com/open-mmlab/mmaction2/issues/362), which I fixed by downgrading `decord` from 0.5.0 to version 0.4.0, rather than filtering the faulty clips (which seem to be the cause of this particular error). This error was also coming only after the 5th epoch. 

At the moment, however, the only issue is the hanging problem after the 5th epoch.

**Comment by rlleshi** [comment]
The problem here had been corrupt videos. I was using `from moviepy.video.io.ffmpeg_tools import ffmpeg_extract_subclip` but one should rather use `from moviepy.editor import VideoFileClip` as described [here](https://github.com/open-mmlab/mmaction2/issues/564#issuecomment-830618091).

**Comment by innerlee** [comment]
Thanks for sharing the solution.
