### ISSUE TITLE
pretrained pth error

### ISSUE THREAD

**Issue by hitcbw** [open-mmlab/mmaction2#840]
# Description:
 1. I downloaded the PTH of slowfast which pretrained on Imagenet. The url is: https://open-mmlab.s3.ap-northeast-2.amazonaws.com/mmaction/models/kinetics400/slowfast_kinetics400_se_rgb_r50_4x16_finetune-4623cf03.pth
2. I loader this pth with --resume-from and commented the code of [read meta data] for the reason of reporting error: key error: meta.
3. the console logged:
``` java
unexpected key in source state_dict: backbone.slow_path.bn1.weight, backbone.slow_path.bn1.bias, backbone.slow_path.bn1.running_mean, backbone.slow_path.bn1.running_var, backbone.slow_path.bn1.num_batches_tracked, backbone.slow_path.layer4_lateral.weight, backbone.slow_path.conv1.weight, back
```
``` java
missing keys in source state_dict: backbone.slow_path.conv1.conv.weight, backbone.slow_path.conv1.bn.weight, backbone.slow_path.conv1.bn.bias, backbone.slow_path.conv1.bn.running_mean, backbone.slow_path.conv1.bn.running_var,
```
As u can see, all the bn's paras are lost. I think that's because the **Conv1 of source pth** doesn't equals to  **Conv1 of slowfast**. The Conv1 structure of Slowfast has one conv(conv1 from pretrained pth), one bn and one relu.
So, you can re-pretrained the model or add the code that delete conv(x). in the slow/fast path.conv(x).bn(x).weight.

**Comment by dreamerlin** [comment]
The checkpoint is from [MMAction](https://github.com/open-mmlab/mmaction) rather than MMAction2
