### ISSUE TITLE
when run  webcam_demo_spatiotemporal_det on cloud gpu into debug

### ISSUE THREAD

**Issue by Deep-learning999** [open-mmlab/mmaction2#842]
Before raising a question, you may need to check the following listed items.

**Checklist**

1. I have searched related issues but cannot get the expected help.
2. I have read the [FAQ documentation](https://mmaction2.readthedocs.io/en/latest/faq.html) but cannot get the expected help.
python demo/webcam_demo_spatiotemporal_det.py \
    --input-video demo/2.mp4 \
    --config configs/detection/ava/slowonly_omnisource_pretrained_r101_8x8x1_20e_ava_rgb.py \
    --checkpoint https://download.openmmlab.com/mmaction/detection/ava/slowonly_omnisource_pretrained_r101_8x8x1_20e_ava_rgb/slowonly_omnisource_pretrained_r101_8x8x1_20e_ava_rgb_20201217-16378594.pth \
    --det-config demo/faster_rcnn_r50_fpn_2x_coco.py \
    --det-checkpoint http://download.openmmlab.com/mmdetection/v2.0/faster_rcnn/faster_rcnn_r50_fpn_2x_coco/faster_rcnn_r50_fpn_2x_coco_bbox_mAP-0.384_20200504_210434-a5d8aa15.pth \
    --det-score-thr 0.9 \
    --action-score-thr 0.5 \
    --label-map demo/label_map_ava.txt \
    --predict-stepsize 20 \
    --output-fps 20 \
    --show
​
Use load_from_http loader
Use load_from_http loader
DEBUG:__main__:Read thread: 3690 ms, 17 fps
/usr/local/lib/python3.8/dist-packages/mmdet/datasets/utils.py:64: UserWarning: "ImageToTensor" pipeline is replaced by "DefaultFormatBundle" for batch inference. It is recommended to manually replace it in the test data pipeline in your config file.
  warnings.warn(
/usr/local/lib/python3.8/dist-packages/mmdet/models/dense_heads/rpn_head.py:191: UserWarning: In rpn_proposal or test_cfg, nms_thr has been moved to a dict named nms as iou_threshold, max_num has been renamed as max_per_img, name of original arguments and the way to specify iou_threshold of NMS will be deprecated.
  warnings.warn(
INFO:__main__:Stdet Results: None
DEBUG:__main__:Main thread inference time 484 ms
DEBUG:__main__:Display thread: 4201 ms, read id 0, display id 0
DEBUG:__main__:Read thread: 1178 ms, 17 fps
INFO:__main__:Stdet Results: None
DEBUG:__main__:Read thread: 1176 ms, 17 fps
DEBUG:__main__:Main thread inference time 1416 ms
DEBUG:__main__:Display thread: 2112 ms, read id 2, display id 1
INFO:__main__:Stdet Results: [[('sit', 0.9589796), ('talk to (e.g., self, a person, a group)', 0.7111095)]]
DEBUG:__main__:Read thread: 1111 ms, 18 fps
DEBUG:__main__:Main thread inference time 1609 ms
DEBUG:__main__:Display thread: 1610 ms, read id 3, display id 2
INFO:__main__:Stdet Results: [[('sit', 0.98160917), ('talk to (e.g., self, a person, a group)', 0.9181804)]]
DEBUG:__main__:Read thread: 1104 ms, 18 fps
DEBUG:__main__:Read thread: 1178 ms, 17 fps
DEBUG:__main__:Read thread: 1160 ms, 17 fps
DEBUG:__main__:Main thread inference time 2901 ms
DEBUG:__main__:Display thread: 2902 ms, read id 6, display id 3
INFO:__main__:Stdet Results: [[('sit', 0.97351325), ('talk to (e.g., self, a person, a group)', 0.81250376)]]
DEBUG:__main__:Main thread inference time 384 ms
DEBUG:__main__:Display thread: 384 ms, read id 6, display id 4
INFO:__main__:Stdet Results: [[('sit', 0.98715776), ('talk to (e.g., self, a person, a group)', 0.92745554)]]
DEBUG:__main__:Read thread: 1094 ms, 18 fps
DEBUG:__main__:Main thread inference time 926 ms
DEBUG:__main__:Display thread: 926 ms, read id 7, display id 5
INFO:__main__:Stdet Results: [[('sit', 0.9661723), ('talk to (e.g., self, a person, a group)', 0.9143741)]]
DEBUG:__main__:Read thread: 1096 ms, 18 fps
DEBUG:__main__:Main thread inference time 1514 ms
DEBUG:__main__:Display thread: 1514 ms, read id 8, display id 6
INFO:__main__:Stdet Results: [[('sit', 0.9726977), ('talk to (e.g., self, a person, a group)', 0.90133816)]]
DEBUG:__main__:Read thread: 1092 ms, 18 fps
DEBUG:__main__:Read thread: 1079 ms, 19 fps
DEBUG:__main__:Read thread: 1159 ms, 17 fps
DEBUG:__main__:Main thread inference time 2578 ms
DEBUG:__main__:Display thread: 2579 ms, read id 11, display id 7
INFO:__main__:Stdet Results: [[('sit', 0.9682999), ('talk to (e.g., self, a person, a group)', 0.9515228)]]
DEBUG:__main__:Main thread inference time 282 ms
DEBUG:__main__:Display thread: 283 ms, read id 11, display id 8
INFO:__main__:Stdet Results: [[('sit', 0.98002636), ('talk to (e.g., self, a person, a group)', 0.8736231)]]
DEBUG:__main__:Main thread inference time 443 ms
DEBUG:__main__:Display thread: 444 ms, read id 11, display id 9
INFO:__main__:Stdet Results: [[('sit', 0.9718218), ('carry/hold (an object)', 0.5342022), ('talk to (e.g., self, a person, a group)', 0.9233674)]]
DEBUG:__main__:Main thread inference time 243 ms
DEBUG:__main__:Display thread: 245 ms, read id 12, display id 10
DEBUG:__main__:Read thread: 1176 ms, 17 fps
INFO:__main__:Stdet Results: [[('sit', 0.9556866), ('carry/hold (an object)', 0.6416971), ('talk to (e.g., self, a person, a group)', 0.92124444)]]
DEBUG:__main__:Main thread inference time 303 ms
DEBUG:__main__:Display thread: 302 ms, read id 12, display id 11
INFO:__main__:Stdet Results: [[('sit', 0.95329607), ('carry/hold (an object)', 0.64250106), ('talk to (e.g., self, a person, a group)', 0.8144327)]]
DEBUG:__main__:Main thread inference time 263 ms
DEBUG:__main__:Display thread: 275 ms, read id 12, display id 12
DEBUG:__main__:Read thread: 1136 ms, 18 fps
INFO:__main__:Stdet Results: [[('sit', 0.96635747), ('carry/hold (an object)', 0.685908), ('talk to (e.g., self, a person, a group)', 0.76616365)]]
DEBUG:__main__:Main thread inference time 225 ms
DEBUG:__main__:Display thread: 885 ms, read id 13, display id 13
DEBUG:__main__:Read thread: 1132 ms, 18 fps
INFO:__main__:Stdet Results: [[('sit', 0.97268265), ('carry/hold (an object)', 0.71732974), ('talk to (e.g., self, a person, a group)', 0.73268604)]]
DEBUG:__main__:Main thread inference time 400 ms
DEBUG:__main__:Display thread: 1307 ms, read id 14, display id 14
DEBUG:__main__:Read thread: 1118 ms, 18 fps
INFO:__main__:Stdet Results: [[('sit', 0.98331535), ('talk to (e.g., self, a person, a group)', 0.8445648)]]
DEBUG:__main__:Main thread inference time 419 ms
DEBUG:__main__:Display thread: 1146 ms, read id 15, display id 15
DEBUG:__main__:Read thread: 1092 ms, 18 fps
INFO:__main__:Stdet Results: [[('sit', 0.7194687)]]
DEBUG:__main__:Main thread inference time 402 ms
DEBUG:__main__:Display thread: 1066 ms, read id 16, display id 16
DEBUG:__main__:Read thread: 1091 ms, 18

 when run cloud gpu why into debug

**Comment by Deep-learning999** [comment]
@kennymckormick @innerlee

**Comment by irvingzhang0512** [comment]
Sorry about my poor English, what do you mean by `run into debug`?
The debug in `DEBUG:main:Main thread inference time 400 ms` is the level of logs. You can just ignore all debug logs by modifying 

https://github.com/open-mmlab/mmaction2/blob/91e0714a4e4b08b27d666e7358514abf934ec6da/demo/webcam_demo_spatiotemporal_det.py#L37

`logging.basicConfig(level=logging.INFO)`

**Comment by Deep-learning999** [comment]
is OK
