### ISSUE TITLE
Inconsistent variable type in generate_labels

### ISSUE THREAD

**Issue by AndersonZhangyq** [open-mmlab/mmaction2#85]
In `generate_labels` 
```python
    def generate_labels(self, gt_bbox):
        """Generate training labels."""
        match_score_confidence_list = []
        match_score_start_list = []
        match_score_end_list = []
        for every_gt_bbox in gt_bbox:
            gt_iou_map = []
            for start, end in every_gt_bbox:
                start = start.numpy()
                end = end.numpy()
         ......
```
The type variable `start` and `end` is `numpy.float64` instead of `tensor`, obviously it has no function named `numpy()`, which leads to an error.
A simple solution would be just comment out these last two lines. (which may be conflict with your design? )
Another solution is found in your training log, just add `gt_bbox` in the argument `keys` of `ToTensor`
```yaml
train_pipeline = [
    dict(type='LoadLocalizationFeature'),
    dict(type='GenerateLocalizationLabels'),
    dict(
        type='Collect',
        keys=['raw_feature', 'gt_bbox'],
        meta_name='video_meta',
        meta_keys=['video_name']),
    # dict(type='ToTensor', keys=['raw_feature']),
    dict(type='ToTensor', keys=['raw_feature', 'gt_bbox']),
    dict(type='ToDataContainer', fields=[dict(key='gt_bbox', stack=False)])
]
```
Maybe it's just a simple mistake when uploading the config file ：）

**Comment by kennymckormick** [comment]
That's right, the two lines:

start = start.numpy()
end = end.numpy()

should be commented. Thanks for pointing that out, I will raise a PR to fix it.
