### ISSUE TITLE
Add support for Youtube-8M?

### ISSUE THREAD

**Issue by Jacobew** [open-mmlab/mmaction2#851]
Hi, do you have any plan of supporting training for [Youtube-8M](https://arxiv.org/abs/1609.08675)?
This is a multi-label video classification dataset of large scale, and it releases two kinds of features, i.e., frame-level (1.5T) and video-level features (30+G).
How can I train on this dataset with the already available features?

**Comment by kennymckormick** [comment]
Currently, we do not have a plan for Youtube-8M. For Youtube-8M classification, algorithms should focus on how to aggregate the frame-level feature. You can refer to works like NetVLAD for Youtube-8M classification. Besides, training an MLP or linear-SVM with video-level features also serves as a baseline.
