### ISSUE TITLE
video feature extraction from i3d/c3d/tsn model

### ISSUE THREAD

**Issue by carolchenyx** [open-mmlab/mmaction2#854]
Dear all, I want to get the optical flow and RGB video clips from a dataset like CUHK-avenue using i3d or c3d. I would like to know could I get them from this repo and how to do that? Indeed, there is a reference repo [](https://github.com/Finspire13/pytorch-i3d-feature-extraction), but I think it is not clear enough. Thank you.

**Comment by kennymckormick** [comment]
You want to extract features or do video data pre-processing?

**Comment by carolchenyx** [comment]
Dear haodong, thanks for the reply. We want to extract features.

Haodong Duan ***@***.***> 于2021年5月5日周三 下午12:40写道：

**Comment by kennymckormick** [comment]
Hi, carol. I raised PR #856 to add the feature of `feature extraction` in MMAction2, you can read it for reference. @carolchenyx

**Comment by carolchenyx** [comment]
Thanks Kenny
