### ISSUE TITLE
python trim_subaction.py  is error

### ISSUE THREAD

**Issue by chenhao-1115** [open-mmlab/mmaction2#858]
Hi, thank you for sharing the code.
I want to use the FineGym dataset, but when I use the following command(python trim_subaction.py ), I find that I don't have the annotation file (event_annotation.json). How can I get this annotation file?

**Comment by congee524** [comment]
The event_annotation.json should be generated on `f'{data_root}/annotations'`. Are there some problems when you running the script?

**Comment by chenhao-1115** [comment]
I use the command 'bash download_annotations.sh' to get the annotation.json' file, and then I use the command' python trim_event.py' to get the events data. When I want to extract the Subactions dataset from the Events dataset, I find that there is no 'event_annotation.json' file. How can I get this file?

**Comment by congee524** [comment]
`event_annotation.json` will be generated by the last line of `trim_event.py`. 
https://github.com/open-mmlab/mmaction2/blob/6d8ee7d81a393129e1408e9ea6ad6b50bacf812a/tools/data/gym/trim_event.py#L57

You can check whether something wrong when you run `trim_event.py`

**Comment by chenhao-1115** [comment]
Ok, thanks for your response. I will try to run it again.

**Comment by chenhao-1115** [comment]
Hi, I generated the 'event_annotation.json' file, but I encountered a new problem. I always get Failed when I run the command' trim_subaction.py'. My ffmpeg version is 2.8.17. What's the problem?
![微信截图_20210510143249](https://user-images.githubusercontent.com/56784057/117616120-44f7bb80-b19d-11eb-9bf7-df04e9c64311.png)
