### ISSUE TITLE
Extracting mAP for each class when evaluating.

### ISSUE THREAD

**Issue by rogercmq** [open-mmlab/mmaction2#859]
Is there some way to extract a mAP (or top1-accuracy) metric for each individual class/label when evaluating?
For example, I just want to check how many instances labelled with "Archery" is classified correctly in UCF101.

**Comment by congee524** [comment]
We calculated testing results in the member function `evaluate` of dataset class, such as
https://github.com/open-mmlab/mmaction2/blob/6d8ee7d81a393129e1408e9ea6ad6b50bacf812a/mmaction/datasets/base.py#L138

maybe you can save what you want.

**Comment by eoozbq** [comment]
I have some questions about this, did you get mAP of each classes
