### ISSUE TITLE
Output predictions as json (for each frame)

### ISSUE THREAD

**Issue by rlleshi** [open-mmlab/mmaction2#862]
The supported outputs currently are  _video_ or _gif_ formats. Could we in addition have as an output _json_ files? 

Using `long_video_demo` for example the output can also be a  _json_ file that contains predictions for every frame of the input video.

**Comment by kennymckormick** [comment]
Good suggestion, we will consider adding this feature. Besides, if you have already implemented this, you are welcome to raise a PR.

**Comment by rlleshi** [comment]
sure
