### ISSUE TITLE
How to realize a two stream network using mmaction2 ?

### ISSUE THREAD

**Issue by sean-001** [open-mmlab/mmaction2#863]
Recently, I want to realize a two stream network (rgb and optical flow) using mmaction2, but I have no idea about it.
Hope you can provide some ideas, thanks !

**Comment by kennymckormick** [comment]
Hi, sean. To realize a two-stream network, you need to train two networks for RGB modality and Flow modality separately, and then combine the prediction of them. We provide some configs for RGB-TSN and Flow-TSN, combining them can get the two-stream TSN. if you want a vanilla two-stream network, you can modify the config and change num_clips to 1.

**Comment by sean-001** [comment]
> Hi, sean. To realize a two-stream network, you need to train two networks for RGB modality and Flow modality separately, and then combine the prediction of them. We provide some configs for RGB-TSN and Flow-TSN, combining them can get the two-stream TSN. if you want a vanilla two-stream network, you can modify the config and change num_clips to 1.

Thanks a lot, kennymckormick! 
In fact, my main problem is how to combine the two models and train them as a whole in mmaction2? Because I still want to use the tools in mmaction2 when training the two-stream network. 
My idea is to register a new backbones module that combines the two branches, is it feasible? 
Hope you can provide some ideas for me.

**Comment by kennymckormick** [comment]
Actually, a typical two-stream network trains two models for both modalities respectively and just fuses the predictions of the two streams. Training two modalities jointly, however, usually leads to inferior results due to overfitting. If you want to design a new model for jointly training two modalities, you may need to write a new backbone, and design some new data pipeline components to deal with two modalities at the same time.

**Comment by kennymckormick** [comment]
> > Hi, sean. To realize a two-stream network, you need to train two networks for RGB modality and Flow modality separately, and then combine the prediction of them. We provide some configs for RGB-TSN and Flow-TSN, combining them can get the two-stream TSN. if you want a vanilla two-stream network, you can modify the config and change num_clips to 1.
> 
> Thanks a lot, kennymckormick!
> In fact, my main problem is how to combine the two models and train them as a whole in mmaction2? Because I still want to use the tools in mmaction2 when training the two-stream network.
> My idea is to register a new backbones module that combines the two branches, is it feasible?
> Hope you can provide some ideas for me.

**Comment by kennymckormick** [comment]
Sorry just mis-closed the issue.

**Comment by sean-001** [comment]
> Actually, a typical two-stream network trains two models for both modalities respectively and just fuses the predictions of the two streams. Training two modalities jointly, however, usually leads to inferior results due to overfitting. If you want to design a new model for jointly training two modalities, you may need to write a new backbone, and design some new data pipeline components to deal with two modalities at the same time.

Thanks for your help, it seems that I can give it a try.

**Comment by aekpic877** [comment]
Hi 

i need support two build two or three modalities  and 3 streams model based on resnet3d
