### ISSUE TITLE
config request

### ISSUE THREAD

**Issue by ZhangHandi** [open-mmlab/mmaction2#865]
Hi,
I have used the config mentioned in this [page](https://github.com/open-mmlab/mmaction2/blob/master/configs/detection/ava/README.md) for slowfast_kinetics_pretrained_r50_8x8x1_20e_ava_rgb model  under 8 gpus but I can't achieve 25.5 mAp. Can I get the config for this model under 8 gpus instead of 8 * 2 gpus? Or can this model achieve 25.5 mAp only under 8 * 2 gpus condition?
Thanks!

**Comment by innerlee** [comment]
The config is for 8 gpus. See https://github.com/open-mmlab/mmaction2/blob/master/configs/detection/ava/slowfast_kinetics_pretrained_r50_8x8x1_20e_ava_rgb.py#L145

You need to multiply the lr by 2 if 16 gpus are used.

**Comment by innerlee** [comment]
As for the performance difference, it is possible

**Comment by ZhangHandi** [comment]
So, the 25.5 mAp result was achieved under 8 * 2 gpus, am I  right? and what's the mAp for this model under 8 gpus?

**Comment by innerlee** [comment]
We haven't trained the model in that gpu setting so sorry :( . Generally speaking the performance should be similar, but the lr needs some tuning.

**Comment by ZhangHandi** [comment]
Ok, thanks a lot!
