### ISSUE TITLE
Extracting ava frames is very slow

### ISSUE THREAD

**Issue by Deep-learning999** [open-mmlab/mmaction2#868]
Before raising a question, you may need to check the following listed items.

**Checklist**

1. I have searched related issues but cannot get the expected help.
2. I have read the [FAQ documentation](https://mmaction2.readthedocs.io/en/latest/faq.html) but cannot get the expected help.

ffmpeg extracts ava frame is very slow, it takes about 20 hours, is there a multi-threaded method to improve the speed

**Comment by Deep-learning999** [comment]
@dreamerlin @lindahua

**Comment by Deep-learning999** [comment]
@dreamerlin @lindahua @hellock @innerlee

**Comment by congee524** [comment]
you can install denseflow

https://github.com/open-mmlab/mmaction2/blob/master/tools/data/ava/README.md#step-4-extract-rgb-and-flow

**Comment by dreamerlin** [comment]
https://github.com/open-mmlab/mmaction2/blob/master/tools/data/build_rawframes.py#L132-L136

**Comment by Deep-learning999** [comment]
Use denseflow to extract frames, if you use 8 threads, how long does it take?

**Comment by irvingzhang0512** [comment]
Maybe I'll add a python script to extract frames by ffmpeg with multi processes.
