### ISSUE TITLE
Top K accuracy during training iterations

### ISSUE THREAD

**Issue by rlleshi** [open-mmlab/mmaction2#874]
Apart from top1 accuracy, by using `metric_options=dict(top_k_accuracy=dict(topk=(1, K)))` in the config file you can set the Top K accuracy during training epochs evaluation. Is it possible to do this for training iterations as well (where the default is 5)?

Otherwise one ends up having a top-k accuracy for each epoch evaluation but a top-5 accuracy during the iterations,

**Comment by congee524** [comment]
Hey, you can modify the training metric in Head.

https://github.com/open-mmlab/mmaction2/blob/2cf6c2e0200b3343f128b139ea32c75e6fd9ba1e/mmaction/models/heads/base.py#L89-L95
