### ISSUE TITLE
Ava custom model prediction error

### ISSUE THREAD

**Issue by Deep-learning999** [open-mmlab/mmaction2#876]
Before raising a question, you may need to check the following listed items.

**Checklist**

1. I have searched related issues but cannot get the expected help.
2. I have read the [FAQ documentation](https://mmaction2.readthedocs.io/en/latest/faq.html) but cannot get the expected help.

When training a specific category of ava, change the original custom_classes = [3, 6, 10, 27, 29, 38, 41, 48, 51, 53, 54, 59, 61, 64, 70, 72] to custom_classes = [38 , 41, 48, 51]. When the model predicts, the prediction result of custom_classes=3 will still appear. I expect the prediction result to appear is only 38, 41, 48, 51 these 4 classes

**Comment by Deep-learning999** [comment]
Stdet Results: [[]]
DEBUG:__main__:Main thread inference time 709 ms
DEBUG:__main__:Display thread: 689 ms, read id 29, display id 29
DEBUG:__main__:Read thread: 1633 ms, 18 fps
INFO:__main__:Stdet Results: [[('crouch/kneel', 0.6173151)]]
DEBUG:__main__:Main thread inference time 145 ms
DEBUG:__main__:Display thread: 924 ms, read id 30, display id 30

**Comment by Deep-learning999** [comment]
@dreamerlin @lindahua @hellock @innerlee

**Comment by irvingzhang0512** [comment]
For ava models trained by custom classes, you need a new `--label-map` file for `webcam_demo_spatiotemporal_det.py`

In this case, label map should be 
```
1: open (e.g., a window, a car door)
2: play musical instrument
3: read
4: sail boat
```

**Comment by irvingzhang0512** [comment]
Maybe I'll create a pr to fix this this weekend.

**Comment by Deep-learning999** [comment]
I used the original 80 classes, only a few of them were kept, and no new actions were defined

**Comment by Deep-learning999** [comment]
I think I have the answer
