### ISSUE TITLE
cannot open video_path stream:../../data/sthv2/videos/69763.webm

### ISSUE THREAD

**Issue by takfate** [open-mmlab/mmaction2#881]
I have installed all packages, but when extracting the frames of `sthv2`, the error `cannot open video_path stream:../../data/sthv2/videos/xxxxx.webm` occurs.

**Comment by innerlee** [comment]
Please check if the path is valid

**Comment by takfate** [comment]
> Please check if the path is valid

I have checked some times. it seems okay. 
Is there a way that checks the reason for this error?

**Comment by innerlee** [comment]
can you `ls` that path at the location where the script is run?

**Comment by takfate** [comment]
The location of running script: `/home/data2/cg/pycharm_workspace/mmaction2/tools/data/sthv2/`
The location of videos data: `/home/data2/cg/pycharm_workspace/mmaction2/data/sthv2/videos/`

**Comment by takfate** [comment]
I have solved this question.

**Comment by takfate** [comment]
I have solved this question.
