### ISSUE TITLE
Get wrong evaluation metrics in tensorboard log

### ISSUE THREAD

**Issue by SCZwangxiao** [open-mmlab/mmaction2#884]
During my training process, I used multi-label classification metrics:
```python
evaluation = dict(
    interval=1,
    metrics=['mmit_mean_average_precision', 'top_k_precision', 'top_k_recall'],
    metric_options=dict(top_k_precision=dict(topk=(1, 5, 10)), top_k_recall=dict(topk=(5, 10))),
    save_best='mmit_mean_average_precision')
```
, where ```top_k_precision``` and ```top_k_recall``` were newly defined metrics.

The metrics were exhibited correctly in the text log. However, in the tensorboard log, there were three empty metrics ```mean_class_accuracy```, ```top1_acc``` , and ```top5_acc```  besides the metrics I defined in config.

**Comment by irvingzhang0512** [comment]
Can you plz share your config and backtrace

**Comment by SCZwangxiao** [comment]
Problem solved. The empty metrics came from other Tensorboard logs in the log directory. I did not notice them for they were in the shared directory in our clusters.
