### ISSUE TITLE
Missing MelLogSpectrogram

### ISSUE THREAD

**Issue by rogercmq** [open-mmlab/mmaction2#886]
Thanks for your error report and we appreciate it a lot.
If you feel we have help you, give us a STAR! :satisfied:

**Checklist**

1. I have searched related issues but cannot get the expected help.
2. The bug has not been fixed in the latest version.

**Describe the bug**

MelLogSpectrogram in mmaction/datasets/pipelines/augmentations.py is removed,  which is given in configs/recognition_audio/resnet/tsn_r50_64x1x1_100e_kinetics400_audio.py

**Reproduction**

1. What command or script did you run? https://github.com/open-mmlab/mmaction2/blob/master/configs/recognition_audio/resnet/tsn_r50_64x1x1_100e_kinetics400_audio.py#L32

2. Did you make any modifications on the code or config? Did you understand what you have modified?
3. What dataset did you use? **The only change is to use my own audio dataset.**

**Comment by kennymckormick** [comment]
@SuX97 Seems that MelLogSpectrogram appears in config without corresponding codes, would you please have a look?

**Comment by SuX97** [comment]
Hi @rogercmq  @kennymckormick , Please check this out: https://github.com/SuX97/mmaction2/blob/5d47eb938a30a7f08f981686e75668749f9d781d/mmaction/datasets/pipelines/augmentations.py#L1194. Seems that it has been removed after a certain refactor.

**Comment by SuX97** [comment]
Note that `this is only `MelSpectrogram`, the `MelLogSpectrogram` is deprecated as online extracting audio feature is too slow. If you want to use LogMelSpectrogram, please refer to [this tool](https://github.com/open-mmlab/mmaction2/blob/master/tools/data/build_audio_features.py). @rogercmq
