### ISSUE TITLE
tsn_r50_320p_1x1x3_110e_kinetics400_flow这个数据外部显示top1是55.7，为什么在log中eval最高只有47.8?

### ISSUE THREAD

**Issue by HydrogenSulfate** [open-mmlab/mmaction2#888]
![image](https://user-images.githubusercontent.com/23737287/119666982-74c6e480-be68-11eb-91da-f4661a7c55a2.png)
外部显示是55.7，但是在log中最高指标是最后一行的{"mode": "val", "epoch": 110, "iter": 470, "lr": 0.0001, "top1_acc": 0.48601, "top5_acc": 0.73626, "mean_class_accuracy": 0.48589}，是这份log不对应最高分的ckpt吗

**Comment by irvingzhang0512** [comment]
val和test的配置是不一样的，可以参考配置文件中的 `val_pipeline` 和 `test_pipeline`

**Comment by HydrogenSulfate** [comment]
> val和test的配置是不一样的，可以参考配置文件中的 `val_pipeline` 和 `test_pipeline`

好的谢谢解答
