### ISSUE TITLE
Serializing Trained model in MMaction2 and using Inference Rcognizer

### ISSUE THREAD

**Issue by tpjesudhas** [open-mmlab/mmaction2#889]
I have trained a model with MMaction with custom data. I would like to evaluate them at a video level using inference_recognizer() method however it only accepts checkpoint files as input. (I'm currently able to serialize the model object and test it on DataLoader across dataset, but would like to evaluate at a video level)

Are there any standards in terms of saving / loading models trained in mmaction2, is it compliant with the Pytorch methods.

**Comment by irvingzhang0512** [comment]
By default ckpts are stored in `work_dir` during training, which could be the input for `inference_recognizer`

Maybe you could share your training config.

**Comment by irvingzhang0512** [comment]
An example of loading model and inference with `inference_recognizer` could refer to [demo.py](https://github.com/open-mmlab/mmaction2/blob/master/demo/demo.py)

**Comment by irvingzhang0512** [comment]
I would recommand to save checkpoints by `checkpoint_config` in [config](https://github.com/open-mmlab/mmaction2/blob/master/docs/tutorials/1_config.md)

Models can generate score or probs, which could be swiched by `test_cfg = dict(average_clips='score')` or `test_cfg = dict(average_clips='prob')` in config.
