### ISSUE TITLE
Transplanting code built with mmaction2-0.6.0 to 0.14.0

### ISSUE THREAD

**Issue by lambert-x** [open-mmlab/mmaction2#892]
Hi, thanks for building this powerful codebase. I am trying to convert a [project](https://github.com/vt-vl-lab/video-data-aug) built with **mmaction2-0.6.0** to be compatible with 0.14.0. Here is the [repository](https://github.com/lambert-x/video_semi) I have got now. I can train the model but **there are three major problems.**
**Background**: I train with the command of 
`./tools/dist_train_semi.sh configs/semi/r3d_r18_8x8x1_180e_ucf101_rgb_all_10percent_v14.py 8 --validate` with the [config](https://github.com/lambert-x/video_semi/blob/main/configs/semi/r3d_r18_8x8x1_180e_ucf101_rgb_all_10percent_nocutup_v14.py). (refering to this [config](https://github.com/lambert-x/video_semi/blob/main/configs/semi/r3d_r18_8x8x1_180e_ucf101_rgb_all_10percent_nocutup_old.py) with the [orignal project](https://github.com/vt-vl-lab/video-data-aug)). 

**Problems**:
1.  The top1 accuracy is a little poorer (now ~32%, old ~34% ) (based on the validation result during training). Could you help me figure out the issue or give me some suggestions?
2.  The validation during training shows reasonable result (metric: topk), however, when I use the following command
 `./tools/dist_test.sh configs/semi/r3d_r18_8x8x1_180e_ucf101_rgb_all_10percent_v14.py  work_dirs/r3d_r18_8x8x1_180e_ucf101_rgb_all_10percent_v14/epoch_180.pth 8 --eval top_k_accuracy`. 
 The results shows to be  `top1_acc        0.0122  / top5_acc        0.0489`. There should be something wrong with the testing part. Could you help me figure out the issue or give me some suggestions?
3. I tried with `--resume-from` argument with my current code 
`
./tools/dist_train_semi.sh configs/semi/r3d_r18_8x8x1_180e_ucf101_rgb_all_10percent_v14.py 8 --resume-from work_dirs/r3d_r18_8x8x1_180e_ucf101_rgb_all_10percent_v14/epoch_180.pth --validate
` 
and find the **learning rate** for the 181-185 epoch  : **181-lr: 0.000e+00** / **182-lr: 1.523e-05** / **183-lr: 6.092e-05** / **184-lr: 1.370e-04** / **185-lr: 2.436e-04**. Does this make sense or not?

**Comment by dreamerlin** [comment]
1. Need to Sync BN buffer: https://github.com/open-mmlab/mmaction2/blob/master/mmaction/core/evaluation/eval_hooks.py#L363-L369
3. gpu_ids need to be sync: https://github.com/open-mmlab/mmaction2/pull/877/files

**Comment by lambert-x** [comment]
> 1. Need to Sync BN buffer: https://github.com/open-mmlab/mmaction2/blob/master/mmaction/core/evaluation/eval_hooks.py#L363-L369
> 2. gpu_ids need to be sync: https://github.com/open-mmlab/mmaction2/pull/877/files
Thanks for the feedback.  Here are some followups:

1.  Does this mean that the previous version is without Sync BN buffer, so the evaluated result is different to the current verision? The current version evaluation is "fairer"?
2.  I have added these lines to the [train_semi.py](https://github.com/lambert-x/video_semi/blob/main/tools/train_semi.py) but still get wrong result with **top1_acc  0.0124** / **top5_acc 0.0500**.  Besides, **I think there is bug with the test part of latest mmaction2**. I train a r2plus1d model with this [config](https://github.com/lambert-x/video_semi/blob/main/configs/recognition/r2plus1d/r2plus1d_r34_8x8x1_180e_ucf101_rgb.py) and test with the saved model (8 gpus). **I then meet with two issues: 1) testing consumes more memory , cuda out of memory error. 2) the result is also wierd.**  Could you please try this [config](https://github.com/lambert-x/video_semi/blob/main/configs/recognition/r2plus1d/r2plus1d_r34_8x8x1_180e_ucf101_rgb.py) and check if you could reproduce this issue? 

Here is some info about my environment:

sys.platform: linux
Python: 3.8.10 (default, May 19 2021, 18:05:58) [GCC 7.3.0]
CUDA available: True
GPU 0,1,2,3,4,5,6,7: TITAN RTX
CUDA_HOME: /usr/local/cuda
NVCC: Cuda compilation tools, release 10.2, V10.2.89
GCC: gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
PyTorch: 1.8.1
PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) oneAPI Math Kernel Library Version 2021.2-Product Build 20210312 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v1.7.0 (Git Hash 7aed236906b1f7a05c0917e5257a1af05e9ff683)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 10.2
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_37,code=compute_37
  - CuDNN 7.6.5
  - Magma 2.5.2
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=10.2, CUDNN_VERSION=7.6.5, CXX_COMPILER=/opt/rh/devtoolset-7/root/usr/bin/c++, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.8.1, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON,

TorchVision: 0.9.1
OpenCV: 4.5.2
MMCV: 1.3.5
MMCV Compiler: GCC 7.5
MMCV CUDA Compiler: 10.2
MMAction2: 0.14.0+230c193

**Comment by dreamerlin** [comment]
1. The evaluation with Sync BN buffer is correct and the same with the result using test scripts.
2. I will try it when I have time (after June 5th)

**Comment by lambert-x** [comment]
> 1. The evaluation with Sync BN buffer is correct and the same with the result using test scripts.
> 2. I will try it when I have time (after June 5th)

Thank you for the reply. I have tried with a lot experiments and solutions and think there is a bug with the test scripts.
