### ISSUE TITLE
TypeError: register_module() missing 1 required positional argument: 'cls'

### ISSUE THREAD

**Issue by gezhaoDL** [open-mmlab/mmaction2#896]
i follow the guide in 'https://github.com/open-mmlab/mmaction2/blob/master/docs_zh_CN/install.md'  to install mmaction2.
**when i run the test code :**

import torch
from mmaction.apis import init_recognizer, inference_recognizer
config_file = 'configs/recognition/tsn/tsn_r50_video_inference_1x1x3_100e_kinetics400_rgb.py'
device = 'cuda:0'
device = torch.device(device)
model = init_recognizer(config_file, device=device)
inference_recognizer(model, 'demo/demo.mp4', 'demo/label_map_k400.txt')

**an error occur:**
Traceback (most recent call last):
  File "test.py", line 2, in <module>
    from mmaction.apis import init_recognizer, inference_recognizer
  File "/data/eul/mmaction2/mmaction/apis/__init__.py", line 1, in <module>
    from .inference import inference_recognizer, init_recognizer
  File "/data/eul/mmaction2/mmaction/apis/inference.py", line 12, in <module>
    from mmaction.models import build_recognizer
  File "/data/eul/mmaction2/mmaction/models/__init__.py", line 1, in <module>
    from .backbones import (C3D, X3D, MobileNetV2, MobileNetV2TSM, ResNet,
  File "/data/eul/mmaction2/mmaction/models/backbones/__init__.py", line 9, in <module>
    from .resnet3d_slowonly import ResNet3dSlowOnly
  File "/data/eul/mmaction2/mmaction/models/backbones/resnet3d_slowonly.py", line 52, in <module>
    MMDET_BACKBONES.register_module()(ResNet3dSlowOnly)
TypeError: register_module() missing 1 required positional argument: 'cls'

what's the problem?

mmaction2              0.15.0           
mmcv-full              1.3.1
mmdet                  1.0rc1+unknown

**Comment by dreamerlin** [comment]
Maybe you should update your MMDet version.

**Comment by gezhaoDL** [comment]
> Maybe you should update your MMDet version.

i update my MMDet version to 2.13.0 and run test.py successfully.**But i got different result every time**




mmaction2              0.15.0            
mmcv-full              1.3.5
mmdet                  2.13.0

**Comment by dreamerlin** [comment]
> > Maybe you should update your MMDet version.
> 
> i update my MMDet version to 2.13.0 and run test.py successfully.**But i got different result every time**
> 
> mmaction2 0.15.0
> mmcv-full 1.3.5
> mmdet 2.13.0

Because it doesn't load any checkpoint, just to verify the pipeline works well
