### ISSUE TITLE
How to add other categories to the detection part of ava spatiotemporal action detection

### ISSUE THREAD

**Issue by Deep-learning999** [open-mmlab/mmaction2#898]
Before raising a question, you may need to check the following listed items.

**Checklist**

1. I have searched related issues but cannot get the expected help.
2. I have read the [FAQ documentation](https://mmaction2.readthedocs.io/en/latest/faq.html) but cannot get the expected help.

I want to add the detection of human face to the fastrcnn part of ava web spatiotemporal motion detection. The drawing frame is to draw both the face and the detection frame of the person at the same time, but the input of the spatiotemporal motion detection only needs the person detection frame. How should the code be modified? .

**Comment by Deep-learning999** [comment]
@irvingzhang0512  @innerlee @lindahua  @hellock

**Comment by dreamerlin** [comment]
Please do not randomly at someone regardless of anything! @kennymckormick See see

**Comment by irvingzhang0512** [comment]
Current webcam stdet demo is not designed for this feature. You need to manage bboxes/visualizer by yourself.

**Comment by Deep-learning999** [comment]
According to your experience, whether this method is feasible is to perform face detection and spatiotemporal motion detection at the same time, and whether the real-time performance can be achieved

**Comment by irvingzhang0512** [comment]
It depends(hardware, models, precision requirements, deployment platform, etc.), you have to find out yourself.

**Comment by kennymckormick** [comment]
Perhaps you need to modify the demo code to additionally apply a face detector to each frame and visualize the detected face boxes. You can refer to the [wider_face](https://github.com/open-mmlab/mmdetection/tree/master/configs/wider_face) section in mmdet to check if it can train a face detector.

**Comment by Deep-learning999** [comment]
I think the detection part can detect faces and human bodies at the same time. If mmdetection has a pre-trained model of OIDV5, then the human body detection box is input into the space-time model, and the face is given to the face recognition model. I mainly know how to separate the two types of detection box codes.

**Comment by Deep-learning999** [comment]
I will solve it by myself
