### ISSUE TITLE
hi, about  spatio-temporal bbox 

### ISSUE THREAD

**Issue by jun0wanan** [open-mmlab/mmaction2#902]
Before raising a question, you may need to check the following listed items.

**Checklist**

1. I have searched related issues but cannot get the expected help.
2. I have read the [FAQ documentation](https://mmaction2.readthedocs.io/en/latest/faq.html) but cannot get the expected help.

**question**
How can I use mmaction2 to get my videos' bboxes (spatio-temporal feature)?  (including video  spatio feature and temporal feature - we call it context feature , and  spatio-temporal feature - bbox from key frame)  
eg : AVA dataset

**Comment by irvingzhang0512** [comment]
Maybe you features you need is the output of `SingleRoIExtractor3D`

https://github.com/open-mmlab/mmaction2/blob/7ea0e01d94fc6b3665c3df4386af570047d98396/mmaction/models/roi_extractors/single_straight3d.py#L27

**Comment by jun0wanan** [comment]
> Maybe the features you need is the output of `SingleRoIExtractor3D`
> 
> https://github.com/open-mmlab/mmaction2/blob/7ea0e01d94fc6b3665c3df4386af570047d98396/mmaction/models/roi_extractors/single_straight3d.py#L27

hi,

     how can I get  input feature(feat, rois) ? sorry I am a newer ......  Can I use mmaction2 to get all end2end (eg : I send my video to it ,and then it return to me the roi_feature 、 the context feature—inculding spatio and temporal feature)

**Comment by irvingzhang0512** [comment]
No step-by-step tutorial for this.

I would recommand you to 

1. check stdet demo or webcam stdet demo from [demo](https://github.com/open-mmlab/mmaction2/tree/7ea0e01d94fc6b3665c3df4386af570047d98396/demo) first

2. impelemnt your own `bbox_head`, to return features you need and replace current `BBoxHeadAVA`.
https://github.com/open-mmlab/mmaction2/blob/7ea0e01d94fc6b3665c3df4386af570047d98396/mmaction/models/heads/bbox_head.py#L123

@kennymckormick any better suggestions?

**Comment by kennymckormick** [comment]
Yes. Currently, we do not provide such APIs. If you want to extract the Context feature and the RoI feature, a good idea is to first extract the spatiotemporal feature of the entire video clip (you can refer to the [feature extraction code](https://github.com/open-mmlab/mmaction2/pull/856) and remove the global pooling for keeping spatial & temporal dimensions). Then you can use RoIAlign to extract the feature of each RoI (suppose you are familiar with RoIAlign).

**Comment by jun0wanan** [comment]
> Yes. Currently, we do not provide such APIs. If you want to extract the Context feature and the RoI feature, a good idea is to first extract the spatiotemporal feature of the entire video clip (you can refer to the [feature extraction code](https://github.com/open-mmlab/mmaction2/pull/856) and remove the global pooling for keeping spatial & temporal dimensions). Then you can use RoIAlign to extract the feature of each RoI (suppose you are familiar with RoIAlign).

  If I can take three step (? I guess after I get some knowledge) :
1. get  video clip feat  (16 frame/clip   eg :  128//16 = 8 clips)
2.  get a frame in every clip as key frame (eg : 8th frame of 16 frames) to get bbox if I have no bbox , Or  
If I have bbox (raw image) 
3. Use the 2th step bbox  to get bbox feat through Roialign   

the 3th step  if I should make sure the bbox size is the same as feature map ? How can I do that  ~? (maybe you have more experience I really want to get your help ~)

**Comment by kennymckormick** [comment]
Yes, this pipeline is OK.
For the RoIAlign step, typically, the feature map you extracted is downsampled by N times. For example, if the original frame size is `H x W`, the feature map will have the size `H / N x W / N`. However, you can still use the boxes on the original frame for RoIAlign, as long you properly set the argument `spatial_scale` properly. You can refer to the [RoIAlign API](https://github.com/open-mmlab/mmcv/blob/master/mmcv/ops/roi_align.py) for more details.

**Comment by jun0wanan** [comment]
> Yes, this pipeline is OK.
> For the RoIAlign step, typically, the feature map you extracted is downsampled by N times. For example, if the original frame size is `H x W`, the feature map will have the size `H / N x W / N`. However, you can still use the boxes on the original frame for RoIAlign, as long you properly set the argument `spatial_scale` properly. You can refer to the [RoIAlign API](https://github.com/open-mmlab/mmcv/blob/master/mmcv/ops/roi_align.py) for more details.

Thanks !! best wishes to you ~

**Comment by jun0wanan** [comment]
> Yes, this pipeline is OK.
> For the RoIAlign step, typically, the feature map you extracted is downsampled by N times. For example, if the original frame size is `H x W`, the feature map will have the size `H / N x W / N`. However, you can still use the boxes on the original frame for RoIAlign, as long you properly set the argument `spatial_scale` properly. You can refer to the [RoIAlign API](https://github.com/open-mmlab/mmcv/blob/master/mmcv/ops/roi_align.py) for more details.

Hi, I'm sorry to bother you again, but I wonder if I can ask you a question. I found that the feature mapping extracted by I3D is too small (4*4). Will the effect of Bbox be affected? Do you have any good methods? Or do you have any information or code recommendations? (No one around knows this question...) ╥﹏╥... Thanks ！ hope hope to get your help~
