### ISSUE TITLE
Can someone clarify my questions about inference process please. 

### ISSUE THREAD

**Issue by balaganeshmohan** [open-mmlab/mmaction2#903]
Hi, I have trained a model on a custom dataset with ~80% accuracy. 

-I am trying to use the grad cam feature, however, I do not understand certain things. How the naming structure works?  I see the default is on layer4/relu. I have tried vaguely changing it but it was no good.
- My output from grad-cam seems to broken. When I give a 60 second video, I only get 30 to 40 frames as output in a<1 second video. Is this intentional lor something I am missing here?
- Lastly, I get this warning, Maybe it is related to my questions.
- >UserWarning: Using a non-full backward hook when the forward contains multiple autograd Nodes is deprecated and will be removed in future versions. This hook will be missing some grad_input. Please use register_full_backward_hook to get the documented behavior.
  warnings.warn("Using a non-full backward hook when the forward contains multiple autograd Nodes "

- Another unrelated question, I do not get the output json of the test results. Is it the probability of the correctly predicted class? If so how can I get the probability of all classes since I have in mind to ensemble with results another architecture.

Would appreciate some help here. Thanks for your time.

**Comment by irvingzhang0512** [comment]
>  How the naming structure works? I see the default is on layer4/relu. I have tried vaguely changing it but it was no good.

You can print all layer names by

```
def print_layer_name(model, layer_name):
    if len(model._modules) == 0:
        print(layer_name)
    else:
        for key in model._modules:
            print_layer_name(model._modules[key], layer_name + '/' + key)
```

> My output from grad-cam seems to broken. When I give a 60 second video, I only get 30 to 40 frames as output in a<1 second video. Is this intentional lor something I am missing here?

I suppose you're using `demo_gradcam.py` without any modifications? This tool exports gradcam results for ONE inference. It is similar to `demo/demo.py`, which predicts ONE result for ONE video.

**Comment by irvingzhang0512** [comment]
> Another unrelated question, I do not get the output json of the test results. Is it the probability of the correctly predicted class? If so how can I get the probability of all classes since I have in mind to ensemble with results another architecture.

what command did you use?

**Comment by rlleshi** [comment]
Just to add for the print layers, there is a script, `tools/get_flops.py` that will also print some Infos about the model's architecture

**Comment by balaganeshmohan** [comment]
> 
> 
> > Another unrelated question, I do not get the output json of the test results. Is it the probability of the correctly predicted class? If so how can I get the probability of all classes since I have in mind to ensemble with results another architecture.
> 
> what command did you use?

Sorry I might have worded it poorly. I do get the outputs. I used this command,
>python tools/test.py configs/recognition/tsm/tsm_r50_1x1x16_50e_kinetics400_rgb.py \
work_dirs/tsm_r50_1x1x16_50e_kinetics400_rgb/epoch_25.pth 
--eval mean_class_accuracy top_k_accuracy  \
--out cremad.json

This when opened as an array gives me a (1116,400) shape. 1116 is the length of my test set. 400 I am not sure. 

Also thanks for the grad cam tip, I'll look into it.

**Comment by irvingzhang0512** [comment]
> This when opened as an array gives me a (1116,400) shape. 1116 is the length of my test set. 400 I am not sure.

400 is the number of classes

Perhaps you should follow this [tutorial](https://mmaction2.readthedocs.io/en/latest/tutorials/2_finetune.html) to train your custom dataset

I think you forget to set `num_classes` for your own model. You can refer to 

https://github.com/open-mmlab/mmaction2/blob/985d284282ef880924eee1516b9736b26913460b/configs/recognition/tsm/tsm_r50_video_1x1x16_50e_diving48_rgb.py#L9

**Comment by balaganeshmohan** [comment]
> 
> 
> > This when opened as an array gives me a (1116,400) shape. 1116 is the length of my test set. 400 I am not sure.
> 
> 400 is the number of classes
> 
> Perhaps you should follow this [tutorial](https://mmaction2.readthedocs.io/en/latest/tutorials/2_finetune.html) to train your custom dataset
> 
> I think you forget to set `num_classes` for your own model. You can refer to
> 
> https://github.com/open-mmlab/mmaction2/blob/985d284282ef880924eee1516b9736b26913460b/configs/recognition/tsm/tsm_r50_video_1x1x16_50e_diving48_rgb.py#L9

Wow thank you. That's a big oversight from me.
