### ISSUE TITLE
inference_recognizer on optical flow model is throwing  "FileNotFoundError, No such file or directory"  accessing non existent frame on rawframe video

### ISSUE THREAD

**Issue by olguin** [open-mmlab/mmaction2#904]
I finetuned a model pretrained on your slowonly_r50_8x8x1_256e_kinetics400_flow  with 2 custom classes. Calculated optical flow using build_rawframe script for input videos, Training, validation and test on test dataset all worked very well. 

I got an error when I tried  to use the pretrained model to make a prediction on a single video (which I had previously calculated its optical flow flow_x_%5d.txt and flow_y_%5d.txt  files using build_rawframes.py script). 

Here is the code for the prediction I am trying to get:

```from mmaction.apis import init_recognizer, inference_recognizer
import torch
device = 'cuda:0' # or 'cpu'
device = torch.device(device)

config_file = 'mmaction2/configs/recognition/slowonly/screw_slowonly_r50_8x8x1_256e_kinetics400_flow.py'
checkpoint_file = 'mmaction2/working_dir/slowonly_screwdriver_flow_run4/best_top1_acc_epoch_75.pth'
model = init_recognizer(config_file, checkpoint_file, device=device, use_frames=True)
video = '/home/ubuntu/dataset/screw9/rawframes/L4IloTT-5zs_1028_1030'
label = '/home/ubuntu/dataset/screw/screw_label_map.txt'
results = inference_recognizer(model, video, label, use_frames=True)
for result in results:
    print(f'{result[0]}: ', result[1])
```

When running that I am getting the error:
**Error traceback**
```
No such file or directory: '/home/ubuntu/dataset/screw/rawframes/L4IloTT-5zs_1028_1030/flow_x_00059.jpg'
```

The things is that  the video L4IloTT-5zs_1028_1030 has only 57 frames (and the frames go from flow_x_00000 to flow_x_00056). 

I think that the error is in the lines:
```~/mmaction2/mmaction/datasets/pipelines/loading.py in __call__(self, results)
   1146                     y_filepath = osp.join(directory,
   1147                                       filename_tmpl.format('y', frame_idx))
-> 1148                     x_img_bytes = self.file_client.get(x_filepath)
```

If I print the list of frame_idx for this video I am getting :

```frames [  3  11  19  27  35  43  51  59   8  16  24  32  40  48  56  64  13  21
  29  37  45  53  61  69  18  26  34  42  50  58  66  74  23  31  39  47
  55  63  71  79  29  37  45  53  61  69  77  85  34  42  50  58  66  74
  82  90  39  47  55  63  71  79  87  95  44  52  60  68  76  84  92 100
  49  57  65  73  81  89  97 105]
```

So something is obviously wrong because the video had as I said only 57 frames (57 optical flow frames, 57 for flow_x and 57 for flow_y).

In case you want, the modified config file I a using is:
[screw_slowonly_r50_8x8x1_256e_kinetics400_flow.py.txt](https://github.com/open-mmlab/mmaction2/files/6601397/screw_slowonly_r50_8x8x1_256e_kinetics400_flow.py.txt)

complete error log  trace is: 
[error_log_slowonly_prediction.txt](https://github.com/open-mmlab/mmaction2/files/6601408/error_log_slowonly_prediction.txt)

PLEASE help, thank you!

**Comment by irvingzhang0512** [comment]
Thanks for your attention.

You can set `start_index` like 

https://github.com/open-mmlab/mmaction2/blob/985d284282ef880924eee1516b9736b26913460b/configs/recognition/tsn/tsn_r50_320p_1x1x8_150e_activitynet_video_flow.py#L69

More details could refer to [faq](https://github.com/open-mmlab/mmaction2/blob/master/docs/faq.md#data)

**Comment by olguin** [comment]
Thank you very much for your prompt response.

I tried the solution but it is Not working.  I used both start_index=0  and start_index=1, and both failed. 

The video L4IloTT-5zs_1028_1030 has 57 optical flow frames (x, y from 00000 to 00056 ). If I set start_index=0 the error I get is :

```No such file or directory: '/home/ubuntu/dataset/screw9/rawframes/L4IloTT-5zs_1028_1030/flow_x_00058.jpg'```

If I set start_index = 1 the error I get is:

```No such file or directory: '/home/ubuntu/dataset/screw9/rawframes/L4IloTT-5zs_1028_1030/flow_x_00059.jpg'```


Finally I set again start_index=0 and I tried copying by hand the last frame flow_x_00056.jpg and flow_y_00056.jpg to  flow_x/y_00058.jpg and run the inference code again, I got "No such file...flow_x_00063". It bears repeating that If I print the content of the variable frame_inds on the file mmaction2/mmaction/datasets/pipelines/loading.py I am getting this:

``` [  2  10  18  26  34  42  50  58   7  15  23  31  39  47  55  63  13  21
  29  37  45  53  61  69  18  26  34  42  50  58  66  74  23  31  39  47
  55  63  71  79  29  37  45  53  61  69  77  85  34  42  50  58  66  74
  82  90  39  47  55  63  71  79  87  95  45  53  61  69  77  85  93 101
  50  58  66  74  82  90  98 106]```


Attaching here the modified config file with start_index=0:  
[screw_slowonly_r50_8x8x1_256e_kinetics400_flow.py.txt](https://github.com/open-mmlab/mmaction2/files/6610000/screw_slowonly_r50_8x8x1_256e_kinetics400_flow.py.txt)


Please help.

**Comment by irvingzhang0512** [comment]
You should check whether your flow file list is properly generated

**Comment by olguin** [comment]
I was able to train / validate and run the following code on test dataset successfully with those same flow file list. 

```
### THIS CODE WORKS WELL: LOAD A model from checkpoint and run predictions on test dataset


import torch
from mmaction.apis import single_gpu_test
from mmaction.datasets import build_dataloader
from mmcv.parallel import MMDataParallel
import os.path as osp

from mmaction.datasets import build_dataset
from mmaction.models import build_model
from mmaction.apis import train_model
from mmaction.apis import init_recognizer, inference_recognizer
import mmcv

device = 'cuda:0' # or 'cpu'
device = torch.device(device)

config_file = 'mmaction2/configs/recognition/slowonly/screw_slowonly_r50_8x8x1_256e_kinetics400_flow.py'
cfg = Config.fromfile(config_file)
checkpoint_file = '/home/ubuntu/mmaction2/working_dir/slowonly_screwdriver_flow_run3/best_top1_acc_epoch_65.pth'
model = init_recognizer(config_file, checkpoint_file, device=device, use_frames=True)


# Build a test dataloader
dataset = build_dataset(cfg.data.test, dict(test_mode=True))
data_loader = build_dataloader(
        dataset,
        videos_per_gpu=1,
        workers_per_gpu=cfg.data.workers_per_gpu,
        dist=False,
        shuffle=False)
model = MMDataParallel(model, device_ids=[0])
outputs = single_gpu_test(model, data_loader)

eval_config = cfg.evaluation
eval_config.pop('interval')
eval_res = dataset.evaluate(outputs, **eval_config)
for name, val in eval_res.items():
    print(f'{name}: {val:.04f}')
```

**Comment by irvingzhang0512** [comment]
Sorry about my carelessness
`inference_recognizer` is designed for rgb inference only.

**Comment by olguin** [comment]
Ooh Got it.   Any chance you can point me to how to modify it to make it work or some workaround? Or how to get the info somehow for the test dataset. I am trying to get what prediction it did to which video for each video in the test dataset. 

Also, If you have a minute can you please take a look at this discussion I opened a while ago, the  highlighting effect on the grad-cam is very curious: https://github.com/open-mmlab/mmaction2/discussions/883

Thank you very much for all your help and the time you took to answer.

**Comment by olguin** [comment]
Not sure if you find it helpful but I made it work by adding the lines :

`   num_frames = len(os.listdir(video_path))
     if modality == 'Flow':  
            num_frames = num_frames // 2
     data = dict(
            frame_dir=video_path,
            total_frames=num_frames,
`
before setting num_frames in the data dict.

**Comment by olguin** [comment]
I saw the PR's code, looks very good. Thank you @irvingzhang0512.
