### ISSUE TITLE
About personid of ava2.2 ava_train_v2.2.csv

### ISSUE THREAD

**Issue by Deep-learning999** [open-mmlab/mmaction2#905]
Before raising a question, you may need to check the following listed items.

**Checklist**

1. I have searched related issues but cannot get the expected help.
2. I have read the [FAQ documentation](https://mmaction2.readthedocs.io/en/latest/faq.html) but cannot get the expected help.

Regarding the personid of ava2.2 ava_train_v2.2.csv, is this field useful when training ava2.1 and ava2.2 models? If it is useful for tracking id of this person, is it equivalent to the action boundary marker? What is in training? Where does the source file or function call this field?
@irvingzhang0512  @lindahua @hellock

**Comment by Deep-learning999** [comment]
@kennymckormick

**Comment by kennymckormick** [comment]
Person ID is not used in our training code.

**Comment by kennymckormick** [comment]
Besides, plz at **related** users when seeking help (you can find the authors of the related feature via git blame). Other users may find it annoying if they are ated in an issue irrelated to them.
