### ISSUE TITLE
 KeyError: 'total_frames'

### ISSUE THREAD

**Issue by cqray1990** [open-mmlab/mmaction2#915]
**Describe the bug**

when i try to  tun demo.py  with config file  in "/recognition/tsn/tsn_r50_320p_1x1x3_100e_kinetics400_rgb.py  and dataset_type = 'VideoDataset' "
when code run here and next step will execute test_pipeline and then raise an error

  total_frames = results['total_frames']
 KeyError: 'total_frames'

  else:
        start_index = cfg.data.test.get('start_index', 0)
        data = dict(
            filename=video_path,
            label=-1,
            start_index=start_index,
            modality='RGB')
    data = test_pipeline(data)

1. What command or script did you run?

```
A placeholder for the command.
```

2. Did you make any modifications on the code or config? Did you understand what you have modified?
3. What dataset did you use?

**Comment by irvingzhang0512** [comment]
Please check [faq](https://github.com/open-mmlab/mmaction2/blob/master/docs/faq.md#data)

**Comment by cqray1990** [comment]
@irvingzhang0512  thks ,but if we test vidieo, did need modify the config file like this  by mannul?
  
    dict(type='DecordInit'),
      
      
            dict(
      
      
                type='SampleFrames',
      
      
                clip_len=32,
      
   
                frame_interval=2,
      num_clips=10,
       dict(type='DecordDecode'),
      
                test_mode=True),

**Comment by irvingzhang0512** [comment]
Yes. `recognition/tsn/tsn_r50_320p_1x1x3_100e_kinetics400_rgb.py` is designed for rawframes. If `dataset_type='VideoDataset'`, related pipelines shoud be modified, too

**Comment by irvingzhang0512** [comment]
FYI, [tsn_r50_video_320p_1x1x3_100e_kinetics400_rgb.py](https://github.com/open-mmlab/mmaction2/blob/master/configs/recognition/tsn/tsn_r50_video_320p_1x1x3_100e_kinetics400_rgb.py) is designed for VideoDataset
