### ISSUE TITLE
Is MOC-Detector integrated in mmaction2?

### ISSUE THREAD

**Issue by Deep-learning999** [open-mmlab/mmaction2#917]
Before raising a question, you may need to check the following listed items.

**Checklist**

1. I have searched related issues but cannot get the expected help.
2. I have read the [FAQ documentation](https://mmaction2.readthedocs.io/en/latest/faq.html) but cannot get the expected help.

I want to use the MOC-Detector Implementation of mmaction2

**Comment by dreamerlin** [comment]
We haven't support it. Besides, if you have already implemented this, you are welcome to raise a PR.

**Comment by Deep-learning999** [comment]
Okay
