### ISSUE TITLE
Could you provide the classification component for Temporal Action Localization task to get the mAP?

### ISSUE THREAD

**Issue by JJBOY** [open-mmlab/mmaction2#92]
Thanks for your awesome job.
Now you provide the code of BSN and BMN for Temporal Action Localization. But it only contains the Temporal Propocal Generation part.  I note that many works apply the untrimmedNet (CUHK & ETHZ & SIAT Submission to ActivityNet Challenge) to the get classification results, but I have not found the classification results file or a easy way to get the classification results .
Do you have plan to provide the code for classifing the proposals to get the final metric mAP?

**Comment by kennymckormick** [comment]
We add a classification results file and scripts to report mAP in PR #192 , which will be merged soon.
