### ISSUE TITLE
How to config memcached in mmaction2?

### ISSUE THREAD

**Issue by xiadingZ** [open-mmlab/mmaction2#928]
My server support memcached backend, how to setup it in mmaction2?

**Comment by irvingzhang0512** [comment]
In MMAction2, you need to config [DecordInit](https://github.com/open-mmlab/mmaction2/blob/aa26715d5c6a0991af4ead5b5ea03c46dd65dcee/mmaction/datasets/pipelines/loading.py#L905) for video dataset or [RawFrameDecode](https://github.com/open-mmlab/mmaction2/blob/aa26715d5c6a0991af4ead5b5ea03c46dd65dcee/mmaction/datasets/pipelines/loading.py#L1089) for rawframes dataset.

you can refer to [FileClient](https://github.com/open-mmlab/mmcv/blob/54ece10ffb144f572c1527b42072f6f925ff4bdf/mmcv/fileio/file_client.py#L207) for more details.

**Comment by dreamerlin** [comment]
For example, in configs

```python
mc_cfg = dict(server_list_cfg='server_list_cfg', client_cfg='client_cfg', sys_path='sys_path')

train_pipeline = [
    ...
    dict(type='RawFrameDecode', io_backend='memcached', **mc_cfg),
    ...
]
```
