### ISSUE TITLE
About New dataset type in PoseC3D

### ISSUE THREAD

**Issue by SKBL5694** [open-mmlab/mmaction2#930]
In PoseC3D config files, I find it uses a new dataset type named "PoseDataset", and the anno files are also different from previous "RawframeDataset" annos. The former use annotation files end with .pkl while later use .txt. I'm not sure how to organize my pose data. Can you provide some example files about that? I think a file tree is helpful.

**Comment by innerlee** [comment]
For datasets, I thought we have "complete" unittests?

**Comment by kennymckormick** [comment]
We will add related documentations. You can also download the pose annotation files to check its organization, or using [visualize_heatmap_volumes](https://github.com/open-mmlab/mmaction2/tree/master/demo/visualize_heatmap_volume.ipynb) to visualize pose annotations, which may help you understand the annotation format.

**Comment by SKBL5694** [comment]
> We will add related documentations. You can also download the pose annotation files to check its organization, or using [visualize_heatmap_volumes](https://github.com/open-mmlab/mmaction2/tree/master/demo/visualize_heatmap_volume.ipynb) to visualize pose annotations, which may help you understand the annotation format.

Thx, Where can I download the annotation files, I can't find them in origin dataset website? 
In the first cell of visualize_heatmap_volumes, I find the comment "# We assume the annotation is already prepared", I'm not familiar with gym dataset but I have NTU data without files named ntu60_xsub_train.pkl

**Comment by SKBL5694** [comment]
> For datasets, I thought we have "complete" unittests?

It seems that this dataset type is different from the past.

**Comment by SKBL5694** [comment]
> We will add related documentations. You can also download the pose annotation files to check its organization, or using [visualize_heatmap_volumes](https://github.com/open-mmlab/mmaction2/tree/master/demo/visualize_heatmap_volume.ipynb) to visualize pose annotations, which may help you understand the annotation format.

Another question is that when I try to run [visualize_heatmap_volumes](https://github.com/open-mmlab/mmaction2/tree/master/demo/visualize_heatmap_volume.ipynb), it raise an error "ModuleNotFoundError: No module named 'poseval' ", It seems that some files have been changed in mmpose. What's the matching version of mmpose for this demo?

**Comment by kennymckormick** [comment]
> > We will add related documentations. You can also download the pose annotation files to check its organization, or using [visualize_heatmap_volumes](https://github.com/open-mmlab/mmaction2/tree/master/demo/visualize_heatmap_volume.ipynb) to visualize pose annotations, which may help you understand the annotation format.
> 
> Thx, Where can I download the annotation files? I can't find them in origin dataset website.
> In the first cell of visualize_heatmap_volumes, I find the comment "# We assume the annotation is already prepared", I'm not familiar with gym dataset but I have NTU data without files named ntu60_xsub_train.pkl

The instructions on downloading the dataset is available here: https://github.com/open-mmlab/mmaction2/tree/master/tools/data/skeleton. For visualize_heatmap_volumes, I don't think there is a strict version requirement, you can follow instructions in mmpose to install `poseval`, which is an external package (outside mmpose).

**Comment by SKBL5694** [comment]
> > > We will add related documentations. You can also download the pose annotation files to check its organization, or using [visualize_heatmap_volumes](https://github.com/open-mmlab/mmaction2/tree/master/demo/visualize_heatmap_volume.ipynb) to visualize pose annotations, which may help you understand the annotation format.
> > 
> > 
> > Thx, Where can I download the annotation files? I can't find them in origin dataset website.
> > In the first cell of visualize_heatmap_volumes, I find the comment "# We assume the annotation is already prepared", I'm not familiar with gym dataset but I have NTU data without files named ntu60_xsub_train.pkl
> 
> The instructions on downloading the dataset is available here: https://github.com/open-mmlab/mmaction2/tree/master/tools/data/skeleton. For visualize_heatmap_volumes, I don't think there is a strict version requirement, you can follow instructions in mmpose to install `poseval`, which is an external package (outside mmpose).

Thank you for your kind help.

**Comment by SKBL5694** [comment]
> The instructions on downloading the dataset is available here: https://github.com/open-mmlab/mmaction2/tree/master/tools/data/skeleton. For visualize_heatmap_volumes, I don't think there is a strict version requirement, you can follow instructions in mmpose to install `poseval`, which is an external package (outside mmpose).

The above problems are solved, the demo can also be used. Thx for your kindness again.

**Comment by sxy-926** [comment]
Can posec3d output visual results with video as input

**Comment by dragen1860** [comment]
looking forward to the PoseC3D demo code with input a video file.

**Comment by sxy-926** [comment]
> looking forward to the PoseC3D demo code with input a video file.

Thank you for your reply，I tried to run "mmaction2 / demo / demo.py", but it came up with 'RuntimeError: input data type should be consist with the dataset type in config, but got input type 'video' and dataset type 'PoseDataset'.
The run command is "python demo/demo.py configs/skeleton/posec3d/slowonly_r50_u48_240e_gym_keypoint.py checkpoints/slowonly_r50_u48_240e_gym_keypoint-b07a98a0.pth demo/demo.mp4 demo/label_map_k400.txt".

Is the file I'm looking for wrong?I would be very grateful if you could tell me which demo file it is.

**Comment by dragen1860** [comment]
> > looking forward to the PoseC3D demo code with input a video file.
> 
> Thank you for your reply，I tried to run "mmaction2 / demo / demo.py", but it came up with 'RuntimeError: input data type should be consist with the dataset type in config, but got input type 'video' and dataset type 'PoseDataset'.
> The run command is "python demo/demo.py configs/skeleton/posec3d/slowonly_r50_u48_240e_gym_keypoint.py checkpoints/slowonly_r50_u48_240e_gym_keypoint-b07a98a0.pth demo/demo.mp4 demo/label_map_k400.txt".
> 
> Is the file I'm looking for wrong?I would be very grateful if you could tell me which demo file it is.

Hi, this is actually a problem. currently mmaction does not provide the demo code for skeleton-based model. Could add me wechat and keeping in touch: dragen1860.

**Comment by kennymckormick** [comment]
@dragen1860 @sxy-926, the posec3d demo is ready now. Please check demo/demo_posec3d.py as well as the instructions in demo/README.md

**Comment by Stanpol** [comment]
Thank you for the demo. I checked it and it works. Obviously it requires `mmdet` and `mmpose` to be installed in addition to `mmaction2`. I also had to upgrade numpy to 1.20.

Could you please share a label file for the NTU RGB+D 60 dataset: `label_map_ntu60.txt`? Or is it just first 60 lines of the 120 file?
