### ISSUE TITLE
Train load  pre-trained model

### ISSUE THREAD

**Issue by rylynchen** [open-mmlab/mmaction2#932]
Where the load_from var add,  I add it in config file, doesn't work.
Anyone has goods idea ?

**Comment by innerlee** [comment]
> I add it in config file

Please share how it was added

**Comment by rylynchen** [comment]
> > I add it in config file
> 
> Please share how it was added

In the configs/recognition/slowfast/slowfast_r50_4x16x1_256e_xxx_rgb.py
```
...
# runtime settings
checkpoint_config = dict(interval=4)
work_dir = './work_dirs/custom_slowfast_r50_3d_4x16x1_256e_cut_rgb'
find_unused_parameters = False
load_from="./work_dirs/custom_slowfast_r50_3d_4x16x1_256e_cut_rgb/latest.pth"
```

**Comment by innerlee** [comment]
The change looks good. What's the begining of the full log of the command? It should print some useful info
