### ISSUE TITLE
How to get the file "label_map_hmdb51.txt"

### ISSUE THREAD

**Issue by yanxinzju** [open-mmlab/mmaction2#934]
I want to inference video on the checkpoint which trained on hmdb51, I want to know how to get the label_map for hmdb51 like "lable_map_k400.txt" in demo/

**Comment by irvingzhang0512** [comment]
If you follow this [tutorial](https://github.com/open-mmlab/mmaction2/tree/master/tools/data/hmdb51) to prepare data for hmdb51, a file named `annotations/classInd.txt` will be generated(during generating filelist). You can convert this file to label map format(remove all indexes).

`classInd.txt` is listed as follows

```txt
1 brush_hair
2 cartwheel
3 catch
4 chew
5 clap
6 climb
7 climb_stairs
8 dive
9 draw_sword
10 dribble
11 drink
12 eat
13 fall_floor
14 fencing
15 flic_flac
16 golf
17 handstand
18 hit
19 hug
20 jump
21 kick
22 kick_ball
23 kiss
24 laugh
25 pick
26 pour
27 pullup
28 punch
29 push
30 pushup
31 ride_bike
32 ride_horse
33 run
34 shake_hands
35 shoot_ball
36 shoot_bow
37 shoot_gun
38 sit
39 situp
40 smile
41 smoke
42 somersault
43 stand
44 swing_baseball
45 sword
46 sword_exercise
47 talk
48 throw
49 turn
50 walk
51 wave
```

**Comment by yanxinzju** [comment]
thank you so much
