### ISSUE TITLE
Strange kernel size and stride in ResNet3D

### ISSUE THREAD

**Issue by MakeCent** [open-mmlab/mmaction2#937]
https://github.com/open-mmlab/mmaction2/blob/e91ee61c566e36f8afa4a938ec37bc5eb0e10077/mmaction/models/backbones/resnet3d.py#L412
https://github.com/open-mmlab/mmaction2/blob/e91ee61c566e36f8afa4a938ec37bc5eb0e10077/mmaction/models/backbones/resnet3d.py#L762-L766

Here the temporal kernel size is 1 while the temporal stride is 2. Won't it cause information loss?

**Comment by dreamerlin** [comment]
The ResNet3D is for I3D model, which keeps the same with [this](https://github.com/open-mmlab/mmaction/blob/master/mmaction/models/tenons/backbones/resnet_i3d.py#L332). For your consideration, you can refer to SlowOnly model

**Comment by MakeCent** [comment]
> The ResNet3D is for I3D model, which keeps the same with [this](https://github.com/open-mmlab/mmaction/blob/master/mmaction/models/tenons/backbones/resnet_i3d.py#L332). For your consideration, you can refer to SlowOnly model

But the problem still exists. And people may use the ResNet3D as the backbone to build their 3D models.

**Comment by irvingzhang0512** [comment]
Thanks for your advice and #939 is related to this issue. There may be some some BC issues

**Comment by MakeCent** [comment]
Well. I don't see any reason to set this kind of stride. Original I3D is based on the Inception-v1, so there are no standard settings for ResNet-I3D models. Stride size larger than kernel size is obviously a bad setting.
