### ISSUE TITLE
Changing the label position in demo.py does not work.

### ISSUE THREAD

**Issue by balaganeshmohan** [open-mmlab/mmaction2#948]
Hello,

On my output demo videos, the labels are getting predicted fine, but the labels are not being displayed on the output video. The default one , writes the label outside of the frame with text cut out and barely legible. 
`text_clips = (
        text_clips.set_position(
            ('bottom','right'),
            relative=True).set_duration(duration_video_clip))`

When changing the set_position parameters to ('center', 'center'), it gives a illegible text in the center. I have also tried with hard numbers and percentage (100,100) and (0.4,0.4) with no resolve. I think this is bug in the moviepy function since I have seen some posts regarding this.

**Comment by dreamerlin** [comment]
Which demo?

**Comment by dreamerlin** [comment]
We have use OpenCV instead of moviepy to plot labels https://github.com/open-mmlab/mmaction2/pull/952.
