### ISSUE TITLE
请问微调是load_from参数在哪里配置呢

### ISSUE THREAD

**Issue by barbecacov** [open-mmlab/mmaction2#951]
[这个文档](https://github.com/open-mmlab/mmaction2/blob/master/docs_zh_CN/tutorials/2_finetune.md)说了微调，可是没有说明在什么地方配置load_from参数

**Comment by innerlee** [comment]
dup https://github.com/open-mmlab/mmaction2/issues/830

@dreamerlin how about moving this arg from `_base_` to somewhere obvious?

**Comment by dreamerlin** [comment]
I think keeping `load_from` in `_base_` is not bad, but I will add some docs to explain it.

**Comment by dreamerlin** [comment]
Hi @barbecacov, If you feel we have helped you, you can give us a STAR! : )
