### ISSUE TITLE
How to take the webcam as input and output the action label in real time

### ISSUE THREAD

**Issue by deepxiaobai** [open-mmlab/mmaction2#958]
I have tried these command on Graphics card RTX3060:
python demo/webcam_demo_spatiotemporal_det.py \
    --input-video 0 \
    --config configs/detection/ava/slowonly_omnisource_pretrained_r101_8x8x1_20e_ava_rgb.py \
    --checkpoint https://download.openmmlab.com/mmaction/detection/ava/slowonly_omnisource_pretrained_r101_8x8x1_20e_ava_rgb/slowonly_omnisource_pretrained_r101_8x8x1_20e_ava_rgb_20201217-16378594.pth \
    --det-config demo/faster_rcnn_r50_fpn_2x_coco.py \
    --det-checkpoint http://download.openmmlab.com/mmdetection/v2.0/faster_rcnn/faster_rcnn_r50_fpn_2x_coco/faster_rcnn_r50_fpn_2x_coco_bbox_mAP-0.384_20200504_210434-a5d8aa15.pth \
    --det-score-thr 0.9 \
    --action-score-thr 0.5 \
    --label-map demo/label_map_ava.txt \
    --predict-stepsize 40 \
    --output-fps 20 \
    --show

python demo/webcam_demo.py configs/recognition/i3d/i3d_r50_video_inference_32x2x1_100e_kinetics400_rgb.py \
  checkpoints/i3d_r50_32x2x1_100e_kinetics400_rgb_20200614-c25ef9a4.pth demo/label_map_k400.txt \
  --average-size 5 --threshold 0.2

But display video lag camera video stream for tens of seconds.

So how to take the webcam as input and output the action label in real time?

**Comment by dreamerlin** [comment]
Try this https://github.com/open-mmlab/mmaction2/tree/master/demo#modify-configs-through-script-arguments

**Comment by irvingzhang0512** [comment]
For stdet webcam demo, there is ["Tips to get a better experience for webcam demo"](https://github.com/open-mmlab/mmaction2/tree/master/demo#spatiotemporal-action-detection-webcam-demo)

**Comment by deepxiaobai** [comment]
Thanks very much.
It seems like that the display time of the video is inconsistent with the current time of the system，which will produce an illusion that it is not real-time.
