### ISSUE TITLE
short-side 320 vs short-side 256

### ISSUE THREAD

**Issue by makecent** [open-mmlab/mmaction2#959]
I notice that the configs of short-side 320 and 256 are exactly the same. 
if the ```short-side 320``` and ```short-side 256``` refer to different preprocessing methods, then their configs should be different.
Or if the ```short-320``` and ```short 256``` are about the original resolution, not preprocessing. In this case, however, why you put ```Resize(-1, 256)```operations in all configs? Won't it make the original resolutions have NO effects?
I am confused.

**Comment by dreamerlin** [comment]
In TSN, we intentionally mention the resolution in the config names. And `short-side 320` is the same as `short-side 256` when applying `Resize(-1, 256)`. But actually, after many experiments, I found that frames with larger resolution may be better in most cases. So We benchmark the results for different resolutions for the community.

**Comment by MakeCent** [comment]
> In TSN, we intentionally mention the resolution in the config names. And `short-side 320` is the same as `short-side 256` when applying `Resize(-1, 256)`. But actually, after many experiments, I found that frames with larger resolution may be better in most cases. So We benchmark the results for different resolutions for the community.

Do you mean larger resolutions got better results even with ```Resize(-1, 256)```?

**Comment by kennymckormick** [comment]
With Resize(-1, 256), the results should be nearly the same for short-side 256 and short-side 320. However, for some checkpoints in MMAction2, the rule doesn't hold (maybe a legacy issue). We will try to figure out the problem.

**Comment by MakeCent** [comment]
> With Resize(-1, 256), the results should be nearly the same for short-side 256 and short-side 320. However, for some checkpoints in MMAction2, the rule doesn't hold (maybe a legacy issue). We will try to figure out the problem.

You are right. I think if ``short-320`` did get better results even with ```Resize(-1, 256)```, then it may because the different method/implementation of **interpolation** used in the ```Resize(-1, 256)``` and the ```resize_video.py```, which will cause different levels of information loss.
