### ISSUE TITLE
about action localization——bmn

### ISSUE THREAD

**Issue by skyqwe123** [open-mmlab/mmaction2#961]
@innerlee  excuse me,
In /mmaction/datasets/pipelines/loading.py
`@PIPELINES.register_module()
class LoadLocalizationFeature:

def init(self, raw_feature_ext='.csv'):
valid_raw_feature_ext = ('.csv', )
if raw_feature_ext not in valid_raw_feature_ext:
raise NotImplementedError
self.raw_feature_ext = raw_feature_ext
`
What is the content of the CSV file? Is there an example？

**Comment by kennymckormick** [comment]
The CSV files are features of the ActivityNet videos. Please refer to Option1 in https://github.com/open-mmlab/mmaction2/tree/master/tools/data/activitynet to download them.
