### ISSUE TITLE
Could not find where optical flow is loaded into TSN model.

### ISSUE THREAD

**Issue by anuraganand1838** [open-mmlab/mmaction2#962]
I am working on TSN action recognition model on a custom dataset. Here, I need to have a look at the way optical flow data is being fed to the model. But, the output tensor from the training pipeline is of dimension [8,3,224,224] which means only 3 channels are being passed into the model. Also Recognizer 2D accepts 3 channels as an input for resnet 50. Can you guys please tell how the optical flow inputs are being fed and is there a way I can edit them to add more information at the video level?

**Comment by kennymckormick** [comment]
For flow-TSN, we have set the in_channels of backbone to N, where N = 2 x clip_len. Please refer to TSN configs with `flow` in their filename.

**Comment by anuraganand1838** [comment]
Thankyou for the reply. I need some additional information on top of what you said right now. I want to train the model together for both rgb and optical flow data of videos. How I can achieve that?

**Comment by kennymckormick** [comment]
In MMAction2, we train two models (like https://github.com/open-mmlab/mmaction2/blob/master/configs/recognition/tsn/tsn_r50_320p_1x1x8_100e_kinetics400_rgb.py and https://github.com/open-mmlab/mmaction2/blob/master/configs/recognition/tsn/tsn_r50_320p_1x1x8_110e_kinetics400_flow.py) separately for the two modality RGB and Flow and fuse the predictions of the two models. To train flow-based model, you need to first extract flow from the videos.

**Comment by anuraganand1838** [comment]
Ok thank you very much for the replies.
