### ISSUE TITLE
sh: 1: denseflow: not found

### ISSUE THREAD

**Issue by Note-Liu** [open-mmlab/mmaction2#965]
I have already installed denseflow:

[100%] Built target denseflow
[ 66%] Built target zzdenseflow
[100%] Built target denseflow
Install the project...
-- Install configuration: ""
-- Installing: /home/software/app/bin/denseflow
-- Set runtime path of "/home/software/app/bin/denseflow" to ""
-- Installing: /home/software/app/lib/libzzdenseflow.a
denseflow installed on /home/software/app

but when i use:
python build_rawframes.py ${SRC_FOLDER} ${OUT_FOLDER} [--task ${TASK}] [--level ${LEVEL}] \
    [--num-worker ${NUM_WORKER}] [--flow-type ${FLOW_TYPE}] [--out-format ${OUT_FORMAT}] \
    [--ext ${EXT}] [--new-width ${NEW_WIDTH}] [--new-height ${NEW_HEIGHT}] [--new-short ${NEW_SHORT}] \
    [--resume] [--use-opencv] [--mixed-ext]

an error message appears:
sh: 1: denseflow: not found

**Comment by dreamerlin** [comment]
Try to add denseflow in your `PATH`

**Comment by Note-Liu** [comment]
> Try to add denseflow in your `PATH`

Thanks!

**Comment by Note-Liu** [comment]
I put 

export ZZROOT=/home/software/app
export PATH=$ZZROOT/bin:$PATH
export LD_LIBRARY_PATH=$ZZROOT/lib:$ZZROOT/lib64:$LD_LIBRARY_PATH

to my ~/.bashrc,and source ~/.bashrc
but it does not work.
What should I do?

**Comment by Note-Liu** [comment]
> Try to add denseflow in your `PATH`

I put

export ZZROOT=/home/software/app
export PATH=$ZZROOT/bin:$PATH
export LD_LIBRARY_PATH=$ZZROOT/lib:$ZZROOT/lib64:$LD_LIBRARY_PATH

to my ~/.bashrc,and source ~/.bashrc
but it does not work.
What should I do?

**Comment by Note-Liu** [comment]
> > Try to add denseflow in your `PATH`
> 
> I put
> 
> export ZZROOT=/home/software/app
> export PATH=$ZZROOT/bin:$PATH
> export LD_LIBRARY_PATH=$ZZROOT/lib:$ZZROOT/lib64:$LD_LIBRARY_PATH
> 
> to my ~/.bashrc,and source ~/.bashrc
> but it does not work.
> What should I do?


检测到中文(简体)
英语
通用领域
生物医药

I've solved it.

**Comment by Note-Liu** [comment]
> > Try to add denseflow in your `PATH`
> 
> I put
> 
> export ZZROOT=/home/software/app
> export PATH=$ZZROOT/bin:$PATH
> export LD_LIBRARY_PATH=$ZZROOT/lib:$ZZROOT/lib64:$LD_LIBRARY_PATH
> 
> to my ~/.bashrc,and source ~/.bashrc
> but it does not work.
> What should I do?

I've solved it.

**Comment by chcchc97** [comment]
> > > Try to add denseflow in your `PATH`
> > 
> > 
> > I put
> > export ZZROOT=/home/software/app
> > export PATH=$ZZROOT/bin:$PATH
> > export LD_LIBRARY_PATH=$ZZROOT/lib:$ZZROOT/lib64:$LD_LIBRARY_PATH
> > to my ~/.bashrc,and source ~/.bashrc
> > but it does not work.
> > What should I do?
> 
> I've solved it.

Hi！How can you solve this problem? @Note-Liu

**Comment by chcchc97** [comment]
> > > > Try to add denseflow in your `PATH`
> > > 
> > > 
> > > I put
> > > export ZZROOT=/home/software/app
> > > export PATH=$ZZROOT/bin:$PATH
> > > export LD_LIBRARY_PATH=$ZZROOT/lib:$ZZROOT/lib64:$LD_LIBRARY_PATH
> > > to my ~/.bashrc,and source ~/.bashrc
> > > but it does not work.
> > > What should I do?
> > 
> > 
> > I've solved it.
> 
> Hi！How can you solve this problem? @Note-Liu

thank you! I have solve this problem after add denseflow in my PATH.
