### ISSUE TITLE
How to implement pose estimation + action recognition ？

### ISSUE THREAD

**Issue by deepxiaobai** [open-mmlab/mmaction2#967]
How to implement pose estimation + action recognition by using the OpenMMlab？
Just like AlphaPose + st-gcn.

**Comment by kennymckormick** [comment]
We are going to release a posec3d demo this week, which implements pose estimation & action recognition inference with OpenMMLAB codebases.

**Comment by deepxiaobai** [comment]
Thanks for your reply. It  will be very useful. I'm looking forward to seeing this amazing demo.

**Comment by SKBL5694** [comment]
> We are going to release a posec3d demo this week, which implements pose estimation & action recognition inference with OpenMMLAB codebases.

Is that a realtime demo or an long-video demo?
BTW, I want to know the how do you generate pose data in PoseC3D dataset? I guess it is generated by a pose estimation Net, am I right?

**Comment by shelly-xue** [comment]
@SKBL5694 hi, "how do you generate pose data in PoseC3D dataset" Did you resolve this? thank you very much!
