### ISSUE TITLE
The numbers of frames and optical flow is not equal

### ISSUE THREAD

**Issue by Note-Liu** [open-mmlab/mmaction2#969]
I use the tool denseflow to extract both frames and optical flow:

python build_rawframes.py ${SRC_FOLDER} ${OUT_FOLDER} [--task ${TASK}] [--level ${LEVEL}] \
    [--num-worker ${NUM_WORKER}] [--flow-type ${FLOW_TYPE}] [--out-format ${OUT_FORMAT}] \
    [--ext ${EXT}] [--new-width ${NEW_WIDTH}] [--new-height ${NEW_HEIGHT}] [--new-short ${NEW_SHORT}] \
    [--resume] [--use-opencv] [--mixed-ext]

but the numbers of frames and optical flow is not equal,I wonder if this is normal？

**Comment by kennymckormick** [comment]
It's OK if you have one more RGB frame than flow frames. Since we estimate a flow frame based on two neighboring RGB frames.

**Comment by Note-Liu** [comment]
Thanks for your reply！

**Comment by Note-Liu** [comment]
> It's OK if you have one more RGB frame than flow frames. Since we estimate a flow frame based on two neighboring RGB frames.

Thanks for your reply！

**Comment by dreamerlin** [comment]
@Note-Liu If you feel we have helped you, you can give us a STAR! : )

**Comment by Note-Liu** [comment]
> @Note-Liu If you feel we have helped you, you can give us a STAR! : )

Thanks for your work!

**Comment by dreamerlin** [comment]
Thx for your appreciation! : )
