### ISSUE TITLE
the folders extracted are empty

### ISSUE THREAD

**Issue by WXLL579** [open-mmlab/mmaction2#970]
你好，请问用mmaction中的build_rawframes.py  命令提取帧的时候，视频都是能正确读到的，但是只生成了每类的文件夹，却没有生成帧的图像，是什么原因呢？

用的这个命令  
python build_rawframes.py  ../../data/Kinetic-TSP/train_videos ../../data/Kinetic-TSP/frames --task rgb --level 2 --num-worker 2 --out-format jpg --ext mp4 --new-short 512

并且中间还显示了sh: 1: denseflow: not found，但是我没有用denseflow提取光流信息啊

**Comment by irvingzhang0512** [comment]
1. denseflow可以提取rgb也可以提取光流
2. 这个脚本默认使用denseflow
3. 如果要用opencv需要指定命令行参数 `--use-opencv`

**Comment by WXLL579** [comment]
谢谢！

**Comment by WXLL579** [comment]
但是加入--use-opencv这个参数后会再运行会提示：
ModuleNotFoundError: No module named 'mmcv' ，已经安装了mmcv

**Comment by WXLL579** [comment]
找到了 谢谢

**Comment by WXLL579** [comment]
请问为什么用opencv过程中还是会出现sh: 1: denseflow: not found呀？并且只是部分能够提取帧，很多都没有提取到，还是空的

**Comment by dreamerlin** [comment]
If you feel we have helped you, you can give us a STAR! : )

**Comment by mayuelala** [comment]
请问你解决了吗，我使用use-opencv后，仍然是空的，请问你是如何解决的
