### ISSUE TITLE
opencv extract frames

### ISSUE THREAD

**Issue by WXLL579** [open-mmlab/mmaction2#971]
请问为什么用opencv过程中还是会出现sh: 1: denseflow: not found呀？并且只是部分能够提取帧，很多都没有提取到，还是空的

**Comment by dreamerlin** [comment]
Need more error information

**Comment by YangXinYe-CMU** [comment]
same problem here. Logs are below:
flow 923 GettingUp/GettingUp_117.mp4 None got something wrong
flow 889 KickingBedBoard/KickingBedBoard_87.mp4 None got something wrong
flow 853 KickingBedBoard/KickingBedBoard_54.mp4 None got something wrong
sh: 1: denseflow: not found
flow 974 GettingUp/GettingUp_53.mp4 None got something wrong
sh: 1: denseflow: not found
sh: 1: denseflow: not found
flow 1007 GettingUp/GettingUp_83.mp4 None got something wrong
flow 946 GettingUp/GettingUp_28.mp4 None got something wrong
sh: 1: denseflow: not found
flow 890 KickingBedBoard/KickingBedBoard_88.mp4 None got something wrong
sh: 1: denseflow: not found
flow 854 KickingBedBoard/KickingBedBoard_55.mp4 None got something wrong
sh: 1: denseflow: not found
sh: 1: denseflow: not found
sh: 1: denseflow: not found
