### ISSUE TITLE
action detection based on the skeleton

### ISSUE THREAD

**Issue by mostar39** [open-mmlab/mmaction2#975]
Hi 
First of all, thank you very much for making Github an easy way to access the field of action recognition (action detection).
Thanks to you, I am very interested in this field and have considered it as my main research area.
I really wanted to say thank you.

I would like to proceed with action detection based on the skeleton. I wanted to learn with my data, so I checked the gym_val.pkl file to make my data annotations.

It was confirmed that the annotation of each video data is composed of a dictionary format. I could clearly see what the other keys meant, but have 4 questions.

For example, if the keypoint dimension is (1, 21, 17, 2),
1. I understand that you mean a video with 21 frames. By the way, which body part does 17 mean? (head, neck, shoulders, etc.)
2. Does the 2 mean that the x and y coordinates are correct?
3. And what does the first number 1 mean is the number of people? For example, if two people appear in one video, is it correct to change the annotation to (2, 21, 17, 2)?
4. In the case of ava dateset, I understood that annotation was generated by extracting 1 frame per second. In the case of gym dataset, how many frames are extracted per second?

please answer about my question.
As always, thank you very much!

**Comment by mostar39** [comment]
Please... help... me..

**Comment by kennymckormick** [comment]
1. 17 means 17 COCO keypoints, which follows the order: 
        0: 'nose',
        1: 'left_eye',
        2: 'right_eye',
        3: 'left_ear',
        4: 'right_ear',
        5: 'left_shoulder',
        6: 'right_shoulder',
        7: 'left_elbow',
        8: 'right_elbow',
        9: 'left_wrist',
        10: 'right_wrist',
        11: 'left_hip',
        12: 'right_hip',
        13: 'left_knee',
        14: 'right_knee',
        15: 'left_ankle',
        16: 'right_ankle'

2. 2 means x & y coordinate
3. 1 means the number of persons in the video.
4. We extract frames from GYM videos densely (around 30fps).

By the way, skeleton-based spatio-temporal detection is a promising idea.

**Comment by kennymckormick** [comment]
@mostar39

**Comment by mostar39** [comment]
@kennymckormick 

Oh my god...... Thank you. You are the light of my life.... Really, really, really.. Really..!!!!!!!!!!!! Thank you!!!!!!!! I will study harder!!!!!!!!!!!!!

But... Really... Just three questions... Can I ask you more...? I'm sorry, but I'll do three more

I want to do action recognition at home. So I actually want to use ntu data, but I want to reduce the number of classes, so I want to train again.

So I changed the annotation and tried to train again, but sadly, the current 'data/posec3d/ntu120_xsub_train.pkl' cannot be downloaded. So, I would like to try making ntu120_xsub_train.pkl or using another dataset.

- Does ntu120_xsub_train.pkl have the same format as gym_train.pkl?
- Is there currently no way to check ntu120_xsub_train.pkl?
- If you have a chance to see it, how can you see it? Or when will it be uploaded?

**Comment by kennymckormick** [comment]
The format of pose annotations of NTURGB-D and FineGYM is the same, Due to the conditions of use of NTURGB-D dataset, we can not release our pose annotations at that time. If you need them, please send a request to my email: dhd.efz@gmail.com.
