### ISSUE TITLE
Skeleton movement infers its own video error

### ISSUE THREAD

**Issue by Deep-learning999** [open-mmlab/mmaction2#990]
Before raising a question, you may need to check the following listed items.

**Checklist**

1. I have searched related issues but cannot get the expected help.
2. I have read the [FAQ documentation](https://mmaction2.readthedocs.io/en/latest/faq.html) but cannot get the expected help.

Use load_from_http loader
Performing Human Detection for each frame
[>>>>>>>>>>>>>>>>>>>>>>>>>>>] 1576/1576, 9.9 task/s, elapsed: 160s, ETA:     0sUse load_from_http loader
Performing Human Pose Estimation for each frame
[>>>>>>>>>>>>>>>>>>>>>>>>>>>] 1576/1576, 29.9 task/s, elapsed: 53s, ETA:     0sTraceback (most recent call last):
  File "demo/demo_posec3d.py", line 273, in <module>
    main()
  File "demo/demo_posec3d.py", line 227, in main
    num_keypoint = pose_results[0][0]['keypoints'].shape[0]
IndexError: list index out of range

**Comment by kennymckormick** [comment]
Seems the demo is not robust enough now. As a simple workaround, you can change this line to `num_keypoint=17`

**Comment by Deep-learning999** [comment]
The above problem is solved. If different people have different actions on the same frame, how to infer each action based on the actions of different people, which is similar to the action effect of time and space.
