### ISSUE TITLE
[PR Welcome] [Doc] Progress of Chinese Documentation

### ISSUE THREAD

**Issue by kennymckormick** [open-mmlab/mmaction2#994]
We are building Chinese Documentation now, PRs of translation from the community are welcomed.
To make the community fully aware of the progress, we list the progress here. Please feel free to leave a message and create a PR if you are willing to translate any one of the documentation.

- [x] https://github.com/open-mmlab/mmaction2/blob/master/docs/feature_extraction.md (#1020  )
- [x] https://github.com/open-mmlab/mmaction2/blob/master/tools/data/skeleton/README.md (#1228  )
- [x] https://github.com/open-mmlab/mmaction2/blob/master/configs/skeleton/posec3d/README.md

**Comment by TRillionZxY** [comment]
Hi, I apply to translate feature_extraction.md.

**Comment by dreamerlin** [comment]
> Hi, I apply to translate feature_extraction.md.

Thx, you can provide a PR and we will review it soon! : )
