### ISSUE TITLE
about posec3d.py

### ISSUE THREAD

**Issue by mostar39** [open-mmlab/mmaction2#995]
Can demo/posec3d.py only predict one class? Or is it possible to predict multiple classes over time?

**Comment by kennymckormick** [comment]
Currently, PoseC3D demo only supports predicting a single label for each clip, we will support PoseC3D demo for long videos in the future.

**Comment by eric-clutch** [comment]
@kennymckormick How can we add keypoints for multi people? I don't have access to the NTU dataset so I cannot see that in the repo itself; but from the PoseC3D paper it says: " cases containing multiple persons, where we
directly accumulate the k-th gaussian maps of all persons
without enlarging the heatmap"; is that implemented?

Thanks!
