### ISSUE TITLE
How to avoid sampling from a same video with RepeatDataset? 

### ISSUE THREAD

**Issue by lambert-x** [open-mmlab/mmaction2#997]
I am facing a bottleneck with frequent dataloader initialization (small dataset). RepeatDataset could alleviate this issue, however, it's important for me to avoid sampling from a same video sample. Any suggestions? 
Thank you.

**Comment by innerlee** [comment]
Related https://github.com/open-mmlab/mmaction2/pull/984

**Comment by kennymckormick** [comment]
You can use torch>=1.7.0 and set `persistent_workers=True`. Then you can get a faster training speed without using `RepeatDataset`.

**Comment by lambert-x** [comment]
Thanks a lot.
